package com.behsazan.corebanking.deposit.account.operations.web;

import com.behsazan.corebanking.deposit.account.balance.application.DepositBalanceService;
import com.behsazan.corebanking.deposit.account.balance.domain.DepositBalanceModels.*;
import com.behsazan.corebanking.deposit.account.closure.application.DepositClosureService;
import com.behsazan.corebanking.deposit.account.closure.domain.DepositClosureModels.*;
import com.behsazan.corebanking.deposit.account.operations.application.DepositAccountOperationsService;
import com.behsazan.corebanking.deposit.account.dashboard.application.DepositAccountDashboardService;
import com.behsazan.corebanking.deposit.account.dashboard.domain.DepositAccountDashboardModels.*;
import com.behsazan.corebanking.deposit.account.operations.domain.DepositAccountOperationsModels.*;
import com.behsazan.corebanking.deposit.account.servicing.application.DepositAccountServicingService;
import com.behsazan.corebanking.deposit.account.servicing.application.DepositAccountWaveAService;
import com.behsazan.corebanking.deposit.account.term.application.DepositTermService;
import com.behsazan.corebanking.deposit.account.transaction.application.DepositTransactionService;
import com.behsazan.corebanking.deposit.account.profit.application.DepositProfitService;
import com.behsazan.corebanking.deposit.account.profit.domain.DepositProfitModels.*;
import com.behsazan.corebanking.deposit.account.term.domain.DepositTermModels.*;
import com.behsazan.corebanking.deposit.account.transaction.domain.DepositTransactionModels.*;
import com.behsazan.corebanking.deposit.account.servicing.domain.DepositAccountServicingModels.*;
import com.behsazan.corebanking.deposit.account.servicing.domain.DepositAccountWaveAModels.*;
import com.behsazan.corebanking.deposit.account.waveb.application.DepositAccountWaveBService;
import com.behsazan.corebanking.deposit.account.wavec.application.DepositAccountWaveCService;
import com.behsazan.corebanking.deposit.account.waved.application.DepositAccountWaveDService;
import com.behsazan.corebanking.deposit.account.waveb.domain.DepositAccountWaveBModels.*;
import com.behsazan.corebanking.deposit.account.wavec.domain.DepositAccountWaveCModels.*;
import com.behsazan.corebanking.deposit.account.waved.domain.DepositAccountWaveDModels.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/deposit-accounts")
public class DepositAccountOperationsController {
    private final DepositAccountOperationsService service; private final DepositAccountDashboardService dashboardService; private final DepositAccountServicingService servicing; private final DepositBalanceService balanceService; private final DepositClosureService closureService; private final DepositTermService termService; private final DepositProfitService profitService; private final DepositTransactionService transactionService; private final DepositAccountWaveAService waveA; private final DepositAccountWaveBService waveB; private final DepositAccountWaveCService waveC; private final DepositAccountWaveDService waveD;
    public DepositAccountOperationsController(DepositAccountOperationsService service,DepositAccountDashboardService dashboardService,DepositAccountServicingService servicing,DepositBalanceService balanceService,DepositClosureService closureService,DepositTermService termService,DepositProfitService profitService,DepositTransactionService transactionService,DepositAccountWaveAService waveA,DepositAccountWaveBService waveB,DepositAccountWaveCService waveC,DepositAccountWaveDService waveD){this.service=service;this.dashboardService=dashboardService;this.servicing=servicing;this.balanceService=balanceService;this.closureService=closureService;this.termService=termService;this.profitService=profitService;this.transactionService=transactionService;this.waveA=waveA;this.waveB=waveB;this.waveC=waveC;this.waveD=waveD;}
    @GetMapping("/dashboard") public ResponseEntity<DashboardView> dashboard(){return ResponseEntity.ok(dashboardService.get());}
    @GetMapping public ResponseEntity<AccountSearchResponse> search(@RequestParam(required=false) String accountNo,@RequestParam(required=false) String status,@RequestParam(required=false) Long openingRequestId,@RequestParam(required=false) Long partyId,@RequestParam(required=false) String productFamilyCode,@RequestParam(defaultValue="0") int offset,@RequestParam(defaultValue="50") int limit){return ResponseEntity.ok(service.search(accountNo,status,openingRequestId,partyId,productFamilyCode,offset,limit));}
    @GetMapping("/{accountId}") public ResponseEntity<AccountDetails> get(@PathVariable long accountId){return ResponseEntity.ok(service.get(accountId));}
    @GetMapping("/{accountId}/balance") public ResponseEntity<BalanceView> balance(@PathVariable long accountId){return ResponseEntity.ok(balanceService.get(accountId));}
    @PostMapping("/{accountId}/balance/postings") public ResponseEntity<PostEntryResponse> postBalance(@PathVariable long accountId,@RequestBody PostEntryRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.post(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/balance/reservations") public ResponseEntity<ReservationActionResponse> reserveBalance(@PathVariable long accountId,@RequestBody CreateReservationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.createReservation(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/balance/reservations/{reservationId}/release") public ResponseEntity<ReservationActionResponse> releaseReservation(@PathVariable long accountId,@PathVariable long reservationId,@RequestBody ReleaseReservationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.releaseReservation(accountId,reservationId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PutMapping("/{accountId}/basic-info") public ResponseEntity<AccountDetails> updateBasicInfo(@PathVariable long accountId,@RequestBody UpdateBasicInfoRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.updateBasicInfo(accountId,request,actor(actor)));}
    @PostMapping("/{accountId}/parties") public ResponseEntity<AccountDetails> addParty(@PathVariable long accountId,@RequestBody AccountPartyRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.addParty(accountId,request,actor(actor)));}
    @DeleteMapping("/{accountId}/parties/{accountPartyId}") public ResponseEntity<AccountDetails> deactivateParty(@PathVariable long accountId,@PathVariable long accountPartyId,@RequestParam(required=false) String reasonCode,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.deactivateParty(accountId,accountPartyId,reasonCode,actor(actor)));}
    @PostMapping("/{accountId}/contacts") public ResponseEntity<AccountDetails> addContact(@PathVariable long accountId,@RequestBody AccountContactRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.addContact(accountId,request,actor(actor)));}
    @DeleteMapping("/{accountId}/contacts/{contactId}") public ResponseEntity<AccountDetails> endContact(@PathVariable long accountId,@PathVariable long contactId,@RequestParam(required=false) String reasonCode,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.endContact(accountId,contactId,reasonCode,actor(actor)));}
    @PostMapping("/{accountId}/lifecycle/suspend") public ResponseEntity<LifecycleActionResponse> suspend(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.suspend(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/lifecycle/reactivate") public ResponseEntity<LifecycleActionResponse> reactivate(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.reactivate(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/lifecycle/mark-dormant") public ResponseEntity<LifecycleActionResponse> markDormant(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.markDormant(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/holds") public ResponseEntity<HoldActionResponse> createHold(@PathVariable long accountId,@RequestBody CreateHoldRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.createHold(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/holds/{holdId}/release") public ResponseEntity<HoldActionResponse> releaseHold(@PathVariable long accountId,@PathVariable long holdId,@RequestBody ReleaseHoldRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.releaseHold(accountId,holdId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/servicing-controls") public ResponseEntity<ServicingControlsView> servicingControls(@PathVariable long accountId){return ResponseEntity.ok(waveA.get(accountId));}
    @PostMapping("/{accountId}/attributes") public ResponseEntity<WaveAActionResponse> upsertAttribute(@PathVariable long accountId,@RequestBody AttributeRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.upsertAttribute(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/condition-overrides") public ResponseEntity<WaveAActionResponse> conditionOverride(@PathVariable long accountId,@RequestBody ConditionOverrideRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.requestConditionOverride(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/condition-overrides/{conditionId}/approve") public ResponseEntity<WaveAActionResponse> approveConditionOverride(@PathVariable long accountId,@PathVariable long conditionId,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.approveConditionOverride(accountId,conditionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/product-changes") public ResponseEntity<WaveAActionResponse> productChange(@PathVariable long accountId,@RequestBody ProductChangeRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.requestProductChange(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/product-changes/{historyId}/approve-execute") public ResponseEntity<WaveAActionResponse> approveExecuteProductChange(@PathVariable long accountId,@PathVariable long historyId,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.approveAndExecuteProductChange(accountId,historyId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/signatory-authorities") public ResponseEntity<WaveAActionResponse> signatoryAuthority(@PathVariable long accountId,@RequestBody SignatoryAuthorityRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.addSignatoryAuthority(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/activation-runs") public ResponseEntity<ActivationActionResponse> activationRun(@PathVariable long accountId,@RequestBody(required=false) ActivationRunRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.runActivationChecks(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/activation-runs/{activationRunId}/execute") public ResponseEntity<ActivationActionResponse> executeActivation(@PathVariable long accountId,@PathVariable long activationRunId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.executeActivation(accountId,activationRunId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/bulk-actions") public ResponseEntity<BulkActionResponse> bulkAction(@RequestBody BulkActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveA.bulk(request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/profit") public ResponseEntity<ProfitView> profit(@PathVariable long accountId){return ResponseEntity.ok(profitService.get(accountId));}
    @PostMapping("/{accountId}/profit/accruals") public ResponseEntity<ProfitActionResponse> accrueProfit(@PathVariable long accountId,@RequestBody(required=false) AccrualRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(profitService.accrue(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/profit/postings") public ResponseEntity<ProfitActionResponse> postProfit(@PathVariable long accountId,@RequestBody(required=false) PostProfitRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(profitService.postAccrued(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/profit/adjustments") public ResponseEntity<ProfitActionResponse> requestProfitAdjustment(@PathVariable long accountId,@RequestBody AdjustmentRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(profitService.requestAdjustment(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/profit/adjustments/{adjustmentId}/approve") public ResponseEntity<ProfitActionResponse> approveProfitAdjustment(@PathVariable long accountId,@PathVariable long adjustmentId,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(profitService.approveAdjustment(accountId,adjustmentId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/profit/adjustments/{adjustmentId}/post") public ResponseEntity<ProfitActionResponse> postProfitAdjustment(@PathVariable long accountId,@PathVariable long adjustmentId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(profitService.postAdjustment(accountId,adjustmentId,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/transactions") public ResponseEntity<TransactionListView> transactions(@PathVariable long accountId){return ResponseEntity.ok(transactionService.list(accountId));}
    @GetMapping("/{accountId}/transactions/{transactionId}") public ResponseEntity<TransactionView> transaction(@PathVariable long accountId,@PathVariable long transactionId){return ResponseEntity.ok(transactionService.get(accountId,transactionId));}
    @PostMapping("/{accountId}/transactions") public ResponseEntity<TransactionActionResponse> initiateTransaction(@PathVariable long accountId,@RequestBody InitiateTransactionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(transactionService.initiate(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transactions/{transactionId}/validate") public ResponseEntity<TransactionActionResponse> validateTransaction(@PathVariable long accountId,@PathVariable long transactionId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(transactionService.validate(accountId,transactionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transactions/{transactionId}/authorize") public ResponseEntity<TransactionActionResponse> authorizeTransaction(@PathVariable long accountId,@PathVariable long transactionId,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(transactionService.authorize(accountId,transactionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transactions/{transactionId}/post") public ResponseEntity<TransactionActionResponse> postTransaction(@PathVariable long accountId,@PathVariable long transactionId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(transactionService.post(accountId,transactionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transactions/{transactionId}/reversals") public ResponseEntity<TransactionActionResponse> reverseTransaction(@PathVariable long accountId,@PathVariable long transactionId,@RequestBody ReversalRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(transactionService.reverse(accountId,transactionId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/term-operations") public ResponseEntity<TermOperationsView> termOperations(@PathVariable long accountId){return ResponseEntity.ok(termService.get(accountId));}
    @PutMapping("/{accountId}/term-operations/maturity-instruction") public ResponseEntity<TermActionResponse> updateMaturityInstruction(@PathVariable long accountId,@RequestBody UpdateMaturityInstructionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.updateInstruction(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/maturity/execute") public ResponseEntity<TermActionResponse> executeMaturity(@PathVariable long accountId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeMaturity(accountId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals") public ResponseEntity<TermActionResponse> requestPartialWithdrawal(@PathVariable long accountId,@RequestBody PartialWithdrawalRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestPartialWithdrawal(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals/{id}/approve") public ResponseEntity<TermActionResponse> approvePartialWithdrawal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approvePartialWithdrawal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals/{id}/execute") public ResponseEntity<TermActionResponse> executePartialWithdrawal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executePartialWithdrawal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals") public ResponseEntity<TermActionResponse> requestRenewal(@PathVariable long accountId,@RequestBody RenewalRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestRenewal(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals/{id}/approve") public ResponseEntity<TermActionResponse> approveRenewal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approveRenewal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals/{id}/execute") public ResponseEntity<TermActionResponse> executeRenewal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeRenewal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions") public ResponseEntity<TermActionResponse> requestConversion(@PathVariable long accountId,@RequestBody ConversionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestConversion(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions/{id}/approve") public ResponseEntity<TermActionResponse> approveConversion(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approveConversion(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions/{id}/execute") public ResponseEntity<TermActionResponse> executeConversion(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeConversion(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/early-terminations") public ResponseEntity<TermActionResponse> requestEarlyTermination(@PathVariable long accountId,@RequestBody EarlyTerminationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestEarlyTermination(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/early-terminations/{id}/execute") public ResponseEntity<TermActionResponse> executeEarlyTermination(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeEarlyTermination(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/wave-b") public ResponseEntity<WaveBView> waveB(@PathVariable long accountId){return ResponseEntity.ok(waveB.get(accountId));}
    @GetMapping("/statement-templates") public ResponseEntity<java.util.List<StatementTemplate>> statementTemplates(){return ResponseEntity.ok(waveB.statementTemplates());}
    @PostMapping("/statement-templates") public ResponseEntity<StatementTemplate> registerStatementTemplate(@RequestBody StatementTemplateRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.registerStatementTemplate(request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/statements") public ResponseEntity<Statement> generateStatement(@PathVariable long accountId,@RequestBody StatementGenerateRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.generateStatement(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/statements/{statementId}/deliveries") public ResponseEntity<Statement> deliverStatement(@PathVariable long accountId,@PathVariable long statementId,@RequestBody StatementDeliveryRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.deliverStatement(accountId,statementId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/limit-controls") public ResponseEntity<LimitControlsView> limitControls(@PathVariable long accountId){return ResponseEntity.ok(waveB.limits(accountId));}
    @PostMapping("/{accountId}/limits") public ResponseEntity<LimitControlsView> createLimit(@PathVariable long accountId,@RequestBody AccountLimitRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.createLimit(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/limits/{limitId}/revoke") public ResponseEntity<LimitControlsView> revokeLimit(@PathVariable long accountId,@PathVariable long limitId,@RequestBody(required=false) ControlReleaseRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.revokeLimit(accountId,limitId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transaction-restrictions") public ResponseEntity<LimitControlsView> createRestriction(@PathVariable long accountId,@RequestBody TransactionRestrictionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.createRestriction(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/transaction-restrictions/{restrictionId}/release") public ResponseEntity<LimitControlsView> releaseRestriction(@PathVariable long accountId,@PathVariable long restrictionId,@RequestBody(required=false) ControlReleaseRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.releaseRestriction(accountId,restrictionId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/maturity-runs") public ResponseEntity<java.util.List<MaturityProcessRun>> maturityRuns(){return ResponseEntity.ok(waveB.maturityRuns());}
    @PostMapping("/maturity-runs") public ResponseEntity<MaturityRunResponse> runMaturity(@RequestBody MaturityRunRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveB.runMaturity(request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/wave-c") public ResponseEntity<WaveCView> waveC(@PathVariable long accountId){return ResponseEntity.ok(waveC.get(accountId));}
    @PostMapping("/{accountId}/inquiries") public ResponseEntity<WaveCView> inquiry(@PathVariable long accountId,@RequestBody InquiryRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.inquiry(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/confirmations") public ResponseEntity<WaveCView> confirmation(@PathVariable long accountId,@RequestBody ConfirmationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.issueConfirmation(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/notification-preferences") public ResponseEntity<WaveCView> notificationPreference(@PathVariable long accountId,@RequestBody NotificationPreferenceRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.notificationPreference(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/notification-events") public ResponseEntity<WaveCView> notificationEvent(@PathVariable long accountId,@RequestBody NotificationEventRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.notificationEvent(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/api-access") public ResponseEntity<WaveCView> grantApiAccess(@PathVariable long accountId,@RequestBody ApiAccessRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.grantApiAccess(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/api-access/{id}/revoke") public ResponseEntity<WaveCView> revokeApiAccess(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.revokeApiAccess(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/signature-rules") public ResponseEntity<WaveCView> signatureRule(@PathVariable long accountId,@RequestBody SignatureRuleRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addSignatureRule(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/delegations") public ResponseEntity<WaveCView> delegation(@PathVariable long accountId,@RequestBody DelegationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addDelegation(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/authorized-users") public ResponseEntity<WaveCView> authorizedUser(@PathVariable long accountId,@RequestBody AuthorizedUserRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addAuthorizedUser(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/beneficiaries") public ResponseEntity<WaveCView> beneficiary(@PathVariable long accountId,@RequestBody BeneficiaryRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addBeneficiary(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/payment-instruments") public ResponseEntity<WaveCView> paymentInstrument(@PathVariable long accountId,@RequestBody PaymentInstrumentRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addPaymentInstrument(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/party-access/{entity}/{id}/deactivate") public ResponseEntity<WaveCView> deactivatePartyAccess(@PathVariable long accountId,@PathVariable String entity,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.deactivatePartyAccess(accountId,entity,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/regulatory-restrictions") public ResponseEntity<WaveCView> regulatoryRestriction(@PathVariable long accountId,@RequestBody RegulatoryRestrictionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addRegulatoryRestriction(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/regulatory-restrictions/{id}/release") public ResponseEntity<WaveCView> releaseRegulatoryRestriction(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.releaseRegulatoryRestriction(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/compliance-evaluations") public ResponseEntity<WaveCView> complianceEvaluation(@PathVariable long accountId,@RequestBody ComplianceEvaluationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.evaluateCompliance(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/pricing-overrides") public ResponseEntity<WaveCView> pricingOverride(@PathVariable long accountId,@RequestBody PricingOverrideRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.requestPricingOverride(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/pricing-overrides/{id}/approve") public ResponseEntity<WaveCView> approvePricingOverride(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.approvePricingOverride(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/tax-exemptions") public ResponseEntity<WaveCView> taxExemption(@PathVariable long accountId,@RequestBody TaxExemptionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.addTaxExemption(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/tax-calculations") public ResponseEntity<WaveCView> taxCalculation(@PathVariable long accountId,@RequestBody TaxCalculationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.calculateTax(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/tax-certificates") public ResponseEntity<WaveCView> taxCertificate(@PathVariable long accountId,@RequestBody TaxCertificateRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveC.issueTaxCertificate(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/wave-d") public ResponseEntity<WaveDView> waveD(@PathVariable long accountId){return ResponseEntity.ok(waveD.get(accountId));}
    @PostMapping("/{accountId}/reconciliation-runs") public ResponseEntity<WaveDView> startReconciliation(@PathVariable long accountId,@RequestBody ReconciliationRunRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.startReconciliation(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reconciliation-runs/{runId}/items") public ResponseEntity<WaveDView> addReconciliationItem(@PathVariable long accountId,@PathVariable long runId,@RequestBody ReconciliationItemRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.addReconciliationItem(accountId,runId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/exceptions") public ResponseEntity<WaveDView> openException(@PathVariable long accountId,@RequestBody ExceptionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.openException(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/discrepancies/{discrepancyId}/refer") public ResponseEntity<WaveDView> referDiscrepancy(@PathVariable long accountId,@PathVariable long discrepancyId,@RequestBody ExceptionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.referDiscrepancy(accountId,discrepancyId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/exceptions/{exceptionId}/assignments") public ResponseEntity<WaveDView> assignException(@PathVariable long accountId,@PathVariable long exceptionId,@RequestBody AssignmentRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.assignException(accountId,exceptionId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/corrections") public ResponseEntity<WaveDView> requestCorrection(@PathVariable long accountId,@RequestBody CorrectionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.requestCorrection(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/corrections/{correctionId}/approve") public ResponseEntity<WaveDView> approveCorrection(@PathVariable long accountId,@PathVariable long correctionId,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.approveCorrection(accountId,correctionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/corrections/{correctionId}/execute") public ResponseEntity<WaveDView> executeCorrection(@PathVariable long accountId,@PathVariable long correctionId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.executeCorrection(accountId,correctionId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PutMapping("/{accountId}/exceptions/{exceptionId}/root-cause") public ResponseEntity<WaveDView> rootCause(@PathVariable long accountId,@PathVariable long exceptionId,@RequestBody RootCauseRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.rootCause(accountId,exceptionId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PutMapping("/{accountId}/correspondent") public ResponseEntity<WaveDView> configureCorrespondent(@PathVariable long accountId,@RequestBody CorrespondentRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.configureCorrespondent(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reward-enrollments") public ResponseEntity<WaveDView> enrollReward(@PathVariable long accountId,@RequestBody RewardEnrollmentRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(waveD.enrollReward(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/closure-workflow") public ResponseEntity<ClosureWorkflowView> closureWorkflow(@PathVariable long accountId){return ResponseEntity.ok(closureService.get(accountId));}
    @PostMapping("/{accountId}/closures") public ResponseEntity<ClosureActionResponse> requestClosure(@PathVariable long accountId,@RequestBody ClosureRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.requestClosure(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/closures/{closureId}/approve") public ResponseEntity<ClosureActionResponse> approveClosure(@PathVariable long accountId,@PathVariable long closureId,@RequestBody(required=false) ApprovalDecisionRequest request,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.approveClosure(accountId,closureId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/closures/{closureId}/execute") public ResponseEntity<ClosureActionResponse> executeClosure(@PathVariable long accountId,@PathVariable long closureId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.executeClosure(accountId,closureId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings") public ResponseEntity<ReopeningActionResponse> requestReopening(@PathVariable long accountId,@RequestBody ReopeningRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.requestReopening(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings/{reopeningId}/approve") public ResponseEntity<ReopeningActionResponse> approveReopening(@PathVariable long accountId,@PathVariable long reopeningId,@RequestBody(required=false) ApprovalDecisionRequest request,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.approveReopening(accountId,reopeningId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings/{reopeningId}/execute") public ResponseEntity<ReopeningActionResponse> executeReopening(@PathVariable long accountId,@PathVariable long reopeningId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.executeReopening(accountId,reopeningId,actor(actor),correlation(correlationId),idempotencyKey));}
    private static String actor(String v){return v==null||v.isBlank()?"deposit.operator":v.trim();} private static String correlation(String v){return v==null||v.isBlank()?UUID.randomUUID().toString():v.trim();}
}
