package com.behsazan.corebanking.deposit.account.operations.web;

import com.behsazan.corebanking.deposit.account.balance.application.DepositBalanceService;
import com.behsazan.corebanking.deposit.account.balance.domain.DepositBalanceModels.*;
import com.behsazan.corebanking.deposit.account.closure.application.DepositClosureService;
import com.behsazan.corebanking.deposit.account.closure.domain.DepositClosureModels.*;
import com.behsazan.corebanking.deposit.account.operations.application.DepositAccountOperationsService;
import com.behsazan.corebanking.deposit.account.operations.domain.DepositAccountOperationsModels.*;
import com.behsazan.corebanking.deposit.account.servicing.application.DepositAccountServicingService;
import com.behsazan.corebanking.deposit.account.term.application.DepositTermService;
import com.behsazan.corebanking.deposit.account.term.domain.DepositTermModels.*;
import com.behsazan.corebanking.deposit.account.servicing.domain.DepositAccountServicingModels.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/deposit-accounts")
public class DepositAccountOperationsController {
    private final DepositAccountOperationsService service; private final DepositAccountServicingService servicing; private final DepositBalanceService balanceService; private final DepositClosureService closureService; private final DepositTermService termService;
    public DepositAccountOperationsController(DepositAccountOperationsService service,DepositAccountServicingService servicing,DepositBalanceService balanceService,DepositClosureService closureService,DepositTermService termService){this.service=service;this.servicing=servicing;this.balanceService=balanceService;this.closureService=closureService;this.termService=termService;}
    @GetMapping public ResponseEntity<AccountSearchResponse> search(@RequestParam(required=false) String accountNo,@RequestParam(required=false) String status,@RequestParam(required=false) Long openingRequestId,@RequestParam(required=false) Long partyId,@RequestParam(required=false) String productFamilyCode,@RequestParam(defaultValue="0") int offset,@RequestParam(defaultValue="50") int limit){return ResponseEntity.ok(service.search(accountNo,status,openingRequestId,partyId,productFamilyCode,offset,limit));}
    @GetMapping("/{accountId}") public ResponseEntity<AccountDetails> get(@PathVariable long accountId){return ResponseEntity.ok(service.get(accountId));}
    @GetMapping("/{accountId}/balance") public ResponseEntity<BalanceView> balance(@PathVariable long accountId){return ResponseEntity.ok(balanceService.get(accountId));}
    @PostMapping("/{accountId}/balance/postings") public ResponseEntity<PostEntryResponse> postBalance(@PathVariable long accountId,@RequestBody PostEntryRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.post(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/balance/reservations") public ResponseEntity<ReservationActionResponse> reserveBalance(@PathVariable long accountId,@RequestBody CreateReservationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.createReservation(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/balance/reservations/{reservationId}/release") public ResponseEntity<ReservationActionResponse> releaseReservation(@PathVariable long accountId,@PathVariable long reservationId,@RequestBody ReleaseReservationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(balanceService.releaseReservation(accountId,reservationId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PutMapping("/{accountId}/basic-info") public ResponseEntity<AccountDetails> updateBasicInfo(@PathVariable long accountId,@RequestBody UpdateBasicInfoRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.updateBasicInfo(accountId,request,actor(actor)));}
    @PostMapping("/{accountId}/parties") public ResponseEntity<AccountDetails> addParty(@PathVariable long accountId,@RequestBody AccountPartyRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.addParty(accountId,request,actor(actor)));}
    @DeleteMapping("/{accountId}/parties/{accountPartyId}") public ResponseEntity<AccountDetails> deactivateParty(@PathVariable long accountId,@PathVariable long accountPartyId,@RequestParam(required=false) String reasonCode,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.deactivateParty(accountId,accountPartyId,reasonCode,actor(actor)));}
    @PostMapping("/{accountId}/contacts") public ResponseEntity<AccountDetails> addContact(@PathVariable long accountId,@RequestBody AccountContactRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.addContact(accountId,request,actor(actor)));}
    @DeleteMapping("/{accountId}/contacts/{contactId}") public ResponseEntity<AccountDetails> endContact(@PathVariable long accountId,@PathVariable long contactId,@RequestParam(required=false) String reasonCode,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor){return ResponseEntity.ok(servicing.endContact(accountId,contactId,reasonCode,actor(actor)));}
    @PostMapping("/{accountId}/lifecycle/suspend") public ResponseEntity<LifecycleActionResponse> suspend(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.suspend(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/lifecycle/reactivate") public ResponseEntity<LifecycleActionResponse> reactivate(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.reactivate(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/lifecycle/mark-dormant") public ResponseEntity<LifecycleActionResponse> markDormant(@PathVariable long accountId,@RequestBody LifecycleActionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.markDormant(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/holds") public ResponseEntity<HoldActionResponse> createHold(@PathVariable long accountId,@RequestBody CreateHoldRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.createHold(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/holds/{holdId}/release") public ResponseEntity<HoldActionResponse> releaseHold(@PathVariable long accountId,@PathVariable long holdId,@RequestBody ReleaseHoldRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(servicing.releaseHold(accountId,holdId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/term-operations") public ResponseEntity<TermOperationsView> termOperations(@PathVariable long accountId){return ResponseEntity.ok(termService.get(accountId));}
    @PutMapping("/{accountId}/term-operations/maturity-instruction") public ResponseEntity<TermActionResponse> updateMaturityInstruction(@PathVariable long accountId,@RequestBody UpdateMaturityInstructionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.updateInstruction(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals") public ResponseEntity<TermActionResponse> requestPartialWithdrawal(@PathVariable long accountId,@RequestBody PartialWithdrawalRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestPartialWithdrawal(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals/{id}/approve") public ResponseEntity<TermActionResponse> approvePartialWithdrawal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approvePartialWithdrawal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/partial-withdrawals/{id}/execute") public ResponseEntity<TermActionResponse> executePartialWithdrawal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executePartialWithdrawal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals") public ResponseEntity<TermActionResponse> requestRenewal(@PathVariable long accountId,@RequestBody RenewalRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestRenewal(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals/{id}/approve") public ResponseEntity<TermActionResponse> approveRenewal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approveRenewal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/renewals/{id}/execute") public ResponseEntity<TermActionResponse> executeRenewal(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeRenewal(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions") public ResponseEntity<TermActionResponse> requestConversion(@PathVariable long accountId,@RequestBody ConversionRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestConversion(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions/{id}/approve") public ResponseEntity<TermActionResponse> approveConversion(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.approveConversion(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/conversions/{id}/execute") public ResponseEntity<TermActionResponse> executeConversion(@PathVariable long accountId,@PathVariable long id,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.executeConversion(accountId,id,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/term-operations/early-terminations") public ResponseEntity<TermActionResponse> requestEarlyTermination(@PathVariable long accountId,@RequestBody EarlyTerminationRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(termService.requestEarlyTermination(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @GetMapping("/{accountId}/closure-workflow") public ResponseEntity<ClosureWorkflowView> closureWorkflow(@PathVariable long accountId){return ResponseEntity.ok(closureService.get(accountId));}
    @PostMapping("/{accountId}/closures") public ResponseEntity<ClosureActionResponse> requestClosure(@PathVariable long accountId,@RequestBody ClosureRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.requestClosure(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/closures/{closureId}/approve") public ResponseEntity<ClosureActionResponse> approveClosure(@PathVariable long accountId,@PathVariable long closureId,@RequestBody(required=false) ApprovalDecisionRequest request,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.approveClosure(accountId,closureId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/closures/{closureId}/execute") public ResponseEntity<ClosureActionResponse> executeClosure(@PathVariable long accountId,@PathVariable long closureId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.executeClosure(accountId,closureId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings") public ResponseEntity<ReopeningActionResponse> requestReopening(@PathVariable long accountId,@RequestBody ReopeningRequest request,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.requestReopening(accountId,request,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings/{reopeningId}/approve") public ResponseEntity<ReopeningActionResponse> approveReopening(@PathVariable long accountId,@PathVariable long reopeningId,@RequestBody(required=false) ApprovalDecisionRequest request,@RequestHeader(name="X-User-Id") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.approveReopening(accountId,reopeningId,actor(actor),correlation(correlationId),idempotencyKey));}
    @PostMapping("/{accountId}/reopenings/{reopeningId}/execute") public ResponseEntity<ReopeningActionResponse> executeReopening(@PathVariable long accountId,@PathVariable long reopeningId,@RequestHeader(name="X-User-Id",defaultValue="deposit.operator") String actor,@RequestHeader(name="X-Correlation-Id",required=false) String correlationId,@RequestHeader(name="X-Idempotency-Key") String idempotencyKey){return ResponseEntity.ok(closureService.executeReopening(accountId,reopeningId,actor(actor),correlation(correlationId),idempotencyKey));}
    private static String actor(String v){return v==null||v.isBlank()?"deposit.operator":v.trim();} private static String correlation(String v){return v==null||v.isBlank()?UUID.randomUUID().toString():v.trim();}
}
