package com.behsazan.corebanking.deposit.account.waveb.application;

import com.behsazan.corebanking.deposit.account.error.DepositAccountNotFoundException;
import com.behsazan.corebanking.deposit.account.waveb.domain.DepositAccountWaveBModels.*;
import com.behsazan.corebanking.deposit.account.waveb.oracle.DepositAccountWaveBRepository;
import com.behsazan.corebanking.deposit.account.waveb.oracle.DepositAccountWaveBRepository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.time.temporal.TemporalAdjusters;
import java.util.*;

@Service
public class DepositAccountWaveBService {
    private static final Set<String> STATEMENT_FORMATS=Set.of("PDF","HTML","CSV","XML");
    private static final Set<String> REQUEST_CHANNELS=Set.of("BRANCH","MOBILE","INTERNET","API");
    private static final Set<String> DELIVERY_CHANNELS=Set.of("EMAIL","PORTAL","API","SMS");
    private static final Set<String> LIMIT_TYPES=Set.of("TRANSACTION_AMOUNT","DAILY_AMOUNT","DAILY_COUNT","MONTHLY_AMOUNT");
    private static final Set<String> LIMIT_SOURCES=Set.of("PRODUCT_OVERRIDE","RISK","LEGAL","COMPLIANCE","CUSTOMER_AGREEMENT","OPERATIONS");
    private static final Set<String> RESTRICTION_MODES=Set.of("BLOCK","ALLOW_ONLY","LIMIT");
    private static final Set<String> DIRECTIONS=Set.of("DEBIT","CREDIT");
    private static final Set<String> RELEASE_POLICIES=Set.of("ORIGIN_ONLY","ORIGIN_OR_AUTHORITY","ORIGIN_OR_OVERRIDE","AUTO_EXPIRY");
    private static final Set<String> RUN_MODES=Set.of("EOD","INTRADAY","MANUAL");
    private static final Set<String> MATURITY_ACTIONS=Set.of("RENEW_PRINCIPAL","RENEW_PRINCIPAL_PAY_PROFIT","PAY_TO_ACCOUNT","CLOSE_AND_SETTLE","WAIT_INSTRUCTION");

    private final DepositAccountWaveBRepository repository;
    public DepositAccountWaveBService(DepositAccountWaveBRepository repository){this.repository=repository;}

    @Transactional(readOnly=true)
    public WaveBView get(long accountId){requireAccount(accountId);return view(accountId);}

    @Transactional(readOnly=true)
    public List<StatementTemplate> statementTemplates(){return repository.templates();}

    @Transactional
    public StatementTemplate registerStatementTemplate(StatementTemplateRequest request,String actor,String correlation,String idempotencyKey){
        if(request==null)throw new IllegalArgumentException("اطلاعات قالب صورتحساب الزامی است.");
        String code=upper(required(request.templateCode(),"TEMPLATE_CODE"));String name=required(request.templateName(),"TEMPLATE_NAME");String format=upper(required(request.formatCode(),"FORMAT_CODE"));if(!STATEMENT_FORMATS.contains(format))throw new IllegalArgumentException("FORMAT_CODE نامعتبر است: "+format);String lang=required(request.languageCode(),"LANGUAGE_CODE");if(lang.length()>10)throw new IllegalArgumentException("LANGUAGE_CODE حداکثر 10 کاراکتر است.");long version=request.versionNo()==null?1:request.versionNo();if(version<=0)throw new IllegalArgumentException("VERSION_NO باید مثبت باشد.");LocalDate from=request.effectiveFrom()==null?LocalDate.now(ZoneOffset.UTC):request.effectiveFrom();if(request.effectiveTo()!=null&&request.effectiveTo().isBefore(from))throw new IllegalArgumentException("EFFECTIVE_TO قبل از EFFECTIVE_FROM مجاز نیست.");
        String h=hash(String.join("|","STMT_TEMPLATE",code,name,format,lang,String.valueOf(version),from.toString(),Objects.toString(request.effectiveTo(),""),Objects.toString(request.templateBody(),"")));
        if(replayOrClaim(idempotencyKey,null,"STATEMENT_TEMPLATE_REGISTER",h,actor,correlation)){long id=parseResult(idempotencyKey,"STMTTPL:");return repository.template(id).orElseThrow();}
        long id=repository.next("SEQ_DEPOSIT_STATEMENT_TEMPLATE");repository.insertTemplate(id,code,name,format,lang,request.templateBody(),version,from,request.effectiveTo(),actor);repository.retireOlderTemplates(code,id,actor);repository.completeIdempotency(idempotencyKey,"STMTTPL:"+id);return repository.template(id).orElseThrow();
    }

    @Transactional
    public Statement generateStatement(long accountId,StatementGenerateRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات تولید صورتحساب الزامی است.");if(request.statementTemplateId()<=0)throw new IllegalArgumentException("STATEMENT_TEMPLATE_ID باید مثبت باشد.");LocalDate from=Objects.requireNonNull(request.dateFrom(),"DATE_FROM الزامی است."),to=Objects.requireNonNull(request.dateTo(),"DATE_TO الزامی است.");if(to.isBefore(from))throw new IllegalArgumentException("DATE_TO قبل از DATE_FROM مجاز نیست.");String reqChannel=upper(required(request.requestChannelCode(),"REQUEST_CHANNEL_CODE"));if(!REQUEST_CHANNELS.contains(reqChannel))throw new IllegalArgumentException("REQUEST_CHANNEL_CODE نامعتبر است: "+reqChannel);String delChannel=upper(trim(request.deliveryChannelCode()));if(delChannel!=null&&!DELIVERY_CHANNELS.contains(delChannel))throw new IllegalArgumentException("DELIVERY_CHANNEL_CODE نامعتبر است: "+delChannel);String target=trim(request.deliveryTarget());validateDeliveryTarget(accountId,delChannel,target);
        StatementTemplate template=repository.template(request.statementTemplateId()).orElseThrow(()->new IllegalArgumentException("Statement Template یافت نشد."));if(!"ACTIVE".equals(upper(template.statusCode())))throw new IllegalArgumentException("فقط Statement Template فعال قابل استفاده است.");LocalDate today=LocalDate.now(ZoneOffset.UTC);if(template.effectiveFrom().isAfter(to)||(template.effectiveTo()!=null&&template.effectiveTo().isBefore(from)))throw new IllegalArgumentException("نسخه قالب در بازه صورتحساب معتبر نیست.");
        String h=hash("STMT|"+accountId+"|"+request.statementTemplateId()+"|"+from+"|"+to+"|"+reqChannel+"|"+Objects.toString(delChannel,"")+"|"+Objects.toString(target,""));if(replayOrClaim(idempotencyKey,accountId,"STATEMENT_GENERATE",h,actor,correlation)){long sid=parseResult(idempotencyKey,"STMT:");return repository.statement(accountId,sid).orElseThrow();}
        long requestId=repository.next("SEQ_DEPOSIT_STATEMENT_REQUEST"),statementId=repository.next("SEQ_DEPOSIT_STATEMENT");repository.insertStatementRequest(requestId,accountId,template.statementTemplateId(),from,to,reqChannel,delChannel,target,actor);BigDecimal opening=repository.openingBalance(accountId,from),running=opening;List<StatementSourceLine> lines=repository.statementSourceLines(accountId,from,to);StringBuilder digest=new StringBuilder().append(accountId).append('|').append(from).append('|').append(to).append('|').append(opening.toPlainString());for(StatementSourceLine line:lines){running="CREDIT".equals(upper(line.debitCreditCode()))?running.add(line.amount()):running.subtract(line.amount());digest.append('|').append(line.subledgerEntryId()).append(':').append(line.debitCreditCode()).append(':').append(line.amount()).append(':').append(running);}
        String docRef="DPS2-STMT-"+statementId,docHash=hash(digest.toString());repository.insertStatement(statementId,requestId,accountId,opening,running,template.formatCode(),docRef,docHash,actor);long seq=0;BigDecimal itemRunning=opening;for(StatementSourceLine line:lines){seq++;BigDecimal debit=BigDecimal.ZERO,credit=BigDecimal.ZERO;if("CREDIT".equals(upper(line.debitCreditCode()))){credit=line.amount();itemRunning=itemRunning.add(line.amount());}else{debit=line.amount();itemRunning=itemRunning.subtract(line.amount());}repository.insertStatementItem(repository.next("SEQ_DEPOSIT_STATEMENT_ITEM"),statementId,line.transactionId(),seq,line.bookingDate(),line.valueDate(),truncate(line.description(),500),debit,credit,itemRunning,actor);}repository.completeStatementRequest(requestId,actor);repository.completeIdempotency(idempotencyKey,"STMT:"+statementId);return repository.statement(accountId,statementId).orElseThrow();
    }

    @Transactional
    public Statement deliverStatement(long accountId,long statementId,StatementDeliveryRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);Statement current=repository.statement(accountId,statementId).orElseThrow(()->new IllegalArgumentException("صورتحساب برای حساب یافت نشد."));String channel=upper(required(request==null?null:request.channelCode(),"CHANNEL_CODE"));if(!DELIVERY_CHANNELS.contains(channel))throw new IllegalArgumentException("CHANNEL_CODE نامعتبر است: "+channel);String destination=trim(request.destination());validateDeliveryTarget(accountId,channel,destination);String h=hash("STMT_DELIVERY|"+accountId+"|"+statementId+"|"+channel+"|"+Objects.toString(destination,""));if(replayOrClaim(idempotencyKey,accountId,"STATEMENT_DELIVERY",h,actor,correlation))return repository.statement(accountId,statementId).orElseThrow();long attempt=repository.nextDeliveryAttempt(statementId,channel),id=repository.next("SEQ_DEPOSIT_STATEMENT_DELIVERY");String provider="DPS2-DELIVERY-"+id;repository.insertDelivery(id,statementId,channel,destination,attempt,"DELIVERED",provider,actor);repository.markStatementDelivered(statementId,actor);repository.completeIdempotency(idempotencyKey,"STMTDEL:"+id);return repository.statement(accountId,statementId).orElse(current);
    }

    @Transactional
    public LimitControlsView createLimit(long accountId,AccountLimitRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات سقف الزامی است.");String type=upper(required(request.limitTypeCode(),"LIMIT_TYPE_CODE"));if(!LIMIT_TYPES.contains(type))throw new IllegalArgumentException("LIMIT_TYPE_CODE نامعتبر است: "+type);String tx=upper(trim(request.transactionTypeCode())),channel=upper(trim(request.channelCode())),source=upper(required(request.sourceCode(),"SOURCE_CODE"));if(!LIMIT_SOURCES.contains(source))throw new IllegalArgumentException("SOURCE_CODE نامعتبر است: "+source);BigDecimal amount=request.amountLimit();Long count=request.countLimit();if(type.endsWith("AMOUNT")&&(amount==null||amount.signum()<0))throw new IllegalArgumentException("AMOUNT_LIMIT برای سقف مبلغ الزامی و نامنفی است.");if(type.endsWith("COUNT")&&(count==null||count<0))throw new IllegalArgumentException("COUNT_LIMIT برای سقف تعداد الزامی و نامنفی است.");if(!type.endsWith("AMOUNT"))amount=null;if(!type.endsWith("COUNT"))count=null;String unit=periodUnit(type),originSystem=defaultUpper(request.originSystemCode(),"CORE_BANKING"),originModule=defaultUpper(request.originModuleCode(),"ACCOUNT_LIMITS"),originRef=trim(request.originRequestRef());if(originRef==null)originRef=idempotencyKey;String policy=defaultUpper(request.revocationPolicyCode(),"ORIGIN_OR_AUTHORITY");if(!RELEASE_POLICIES.contains(policy))throw new IllegalArgumentException("REVOCATION_POLICY_CODE نامعتبر است: "+policy);OffsetDateTime from=request.effectiveFrom();if(from!=null&&request.effectiveTo()!=null&&request.effectiveTo().isBefore(from))throw new IllegalArgumentException("EFFECTIVE_TO قبل از EFFECTIVE_FROM مجاز نیست.");String h=hash("LIMIT|"+accountId+"|"+type+"|"+tx+"|"+channel+"|"+amount+"|"+count+"|"+source+"|"+(from==null?"DB_NOW":from)+"|"+request.effectiveTo()+"|"+originSystem+"|"+originModule+"|"+originRef+"|"+policy);if(replayOrClaim(idempotencyKey,accountId,"ACCOUNT_LIMIT_CREATE",h,actor,correlation))return limits(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_LIMIT");repository.insertLimit(id,accountId,type,tx,channel,amount,count,unit,unit==null?null:1,source,from,request.effectiveTo(),originSystem,originModule,originRef,policy,actor);repository.completeIdempotency(idempotencyKey,"LIMIT:"+id);return limits(accountId);
    }

    @Transactional
    public LimitControlsView revokeLimit(long accountId,long limitId,ControlReleaseRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);AccountLimit limit=repository.limits(accountId).stream().filter(x->x.accountLimitId()==limitId).findFirst().orElseThrow(()->new IllegalArgumentException("سقف حساب یافت نشد."));String sourceSystem=defaultUpper(request==null?null:request.actionSourceSystemCode(),"CORE_BANKING"),sourceModule=defaultUpper(request==null?null:request.actionSourceModuleCode(),"ACCOUNT_LIMITS"),authority=trim(request==null?null:request.authorityReference());enforceRelease(limit.revocationPolicyCode(),limit.originSystemCode(),limit.originModuleCode(),sourceSystem,sourceModule,authority);String h=hash("LIMIT_REVOKE|"+accountId+"|"+limitId+"|"+sourceSystem+"|"+sourceModule+"|"+Objects.toString(authority,""));if(replayOrClaim(idempotencyKey,accountId,"ACCOUNT_LIMIT_REVOKE",h,actor,correlation))return limits(accountId);if(repository.revokeLimit(accountId,limitId,actor)!=1)throw new IllegalArgumentException("فقط سقف ACTIVE قابل لغو است.");repository.completeIdempotency(idempotencyKey,"LIMIT:"+limitId);return limits(accountId);
    }

    @Transactional
    public LimitControlsView createRestriction(long accountId,TransactionRestrictionRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات محدودیت تراکنش الزامی است.");String tx=upper(required(request.transactionTypeCode(),"TRANSACTION_TYPE_CODE")),channel=upper(trim(request.channelCode())),direction=upper(trim(request.directionCode())),mode=upper(required(request.restrictionModeCode(),"RESTRICTION_MODE_CODE"));if(direction!=null&&!DIRECTIONS.contains(direction))throw new IllegalArgumentException("DIRECTION_CODE نامعتبر است: "+direction);if(!RESTRICTION_MODES.contains(mode))throw new IllegalArgumentException("RESTRICTION_MODE_CODE نامعتبر است: "+mode);BigDecimal max=request.maxAmount();if("LIMIT".equals(mode)&&(max==null||max.signum()<0))throw new IllegalArgumentException("MAX_AMOUNT در حالت LIMIT الزامی و نامنفی است.");if(!"LIMIT".equals(mode))max=null;String source=upper(required(request.sourceCode(),"SOURCE_CODE")),authority=trim(request.authorityReference()),originSystem=defaultUpper(request.originSystemCode(),"CORE_BANKING"),originModule=defaultUpper(request.originModuleCode(),"ACCOUNT_LIMITS"),originRef=trim(request.originRequestRef());if(originRef==null)originRef=idempotencyKey;String policy=defaultUpper(request.releasePolicyCode(),"ORIGIN_OR_AUTHORITY");if(!RELEASE_POLICIES.contains(policy))throw new IllegalArgumentException("RELEASE_POLICY_CODE نامعتبر است: "+policy);OffsetDateTime from=request.validFrom();if(from!=null&&request.validTo()!=null&&request.validTo().isBefore(from))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");String h=hash("RESTRICTION|"+accountId+"|"+tx+"|"+channel+"|"+direction+"|"+mode+"|"+max+"|"+source+"|"+authority+"|"+(from==null?"DB_NOW":from)+"|"+request.validTo()+"|"+originSystem+"|"+originModule+"|"+originRef+"|"+policy);if(replayOrClaim(idempotencyKey,accountId,"ACCOUNT_RESTRICTION_CREATE",h,actor,correlation))return limits(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION");repository.insertRestriction(id,accountId,tx,channel,direction,mode,max,source,authority,from,request.validTo(),originSystem,originModule,originRef,policy,actor);repository.completeIdempotency(idempotencyKey,"RESTRICTION:"+id);return limits(accountId);
    }

    @Transactional
    public LimitControlsView releaseRestriction(long accountId,long restrictionId,ControlReleaseRequest request,String actor,String correlation,String idempotencyKey){
        requireAccount(accountId);TransactionRestriction r=repository.restrictions(accountId).stream().filter(x->x.accountTxRestrictionId()==restrictionId).findFirst().orElseThrow(()->new IllegalArgumentException("محدودیت تراکنش یافت نشد."));String sourceSystem=defaultUpper(request==null?null:request.actionSourceSystemCode(),"CORE_BANKING"),sourceModule=defaultUpper(request==null?null:request.actionSourceModuleCode(),"ACCOUNT_LIMITS"),authority=trim(request==null?null:request.authorityReference());enforceRelease(r.releasePolicyCode(),r.originSystemCode(),r.originModuleCode(),sourceSystem,sourceModule,authority);String h=hash("RESTRICTION_RELEASE|"+accountId+"|"+restrictionId+"|"+sourceSystem+"|"+sourceModule+"|"+Objects.toString(authority,""));if(replayOrClaim(idempotencyKey,accountId,"ACCOUNT_RESTRICTION_RELEASE",h,actor,correlation))return limits(accountId);if(repository.releaseRestriction(accountId,restrictionId,actor)!=1)throw new IllegalArgumentException("فقط محدودیت ACTIVE قابل رفع است.");repository.completeIdempotency(idempotencyKey,"RESTRICTION:"+restrictionId);return limits(accountId);
    }

    @Transactional(readOnly=true)
    public LimitControlsView limits(long accountId){requireAccount(accountId);return new LimitControlsView(repository.limits(accountId),repository.usages(accountId),repository.restrictions(accountId));}

    @Transactional
    public void recordPostedTransactionUsage(long accountId,long transactionId,String transactionType,String channel,BigDecimal amount,LocalDate bookingDate,String actor){
        if(bookingDate==null)return;for(UsageLimit limit:repository.activeLimitsForUsage(accountId,transactionType,channel,bookingDate)){PeriodWindow w=periodWindow(limit,bookingDate);UsageTotals totals=repository.postedUsage(accountId,limit.transactionType(),limit.channel(),w.start.toLocalDate(),w.end.toLocalDate(),limit.effectiveFrom(),limit.effectiveTo());repository.upsertLimitUsage(limit.limitId(),accountId,w.start,w.end,totals.amount(),totals.count(),totals.lastTransactionId(),actor);}
    }

    @Transactional
    public MaturityRunResponse runMaturity(MaturityRunRequest request,String actor,String correlation,String idempotencyKey){
        if(request==null)throw new IllegalArgumentException("اطلاعات اجرای سررسید الزامی است.");LocalDate businessDate=request.businessDate()==null?LocalDate.now(ZoneOffset.UTC):request.businessDate();String mode=defaultUpper(request.runModeCode(),"MANUAL");if(!RUN_MODES.contains(mode))throw new IllegalArgumentException("RUN_MODE_CODE نامعتبر است: "+mode);String h=hash("MATURITY_RUN|"+businessDate+"|"+mode);if(replayOrClaim(idempotencyKey,null,"MATURITY_PROCESS_RUN",h,actor,correlation)){long id=parseResult(idempotencyKey,"MATRUN:");return new MaturityRunResponse(repository.maturityRun(id),true);}long runId=repository.next("SEQ_DEPOSIT_MATURITY_PROCESS_RUN");repository.insertMaturityRun(runId,businessDate,mode,actor);List<DueTerm> due=repository.dueTerms(businessDate);long processed=0,failed=0;for(DueTerm term:due){long itemId=repository.next("SEQ_DEPOSIT_MATURITY_PROCESS_ITEM");try{String action=upper(term.instructionCode());if(!MATURITY_ACTIONS.contains(action))throw new IllegalArgumentException("MATURITY_INSTRUCTION_CODE نامعتبر است: "+action);var existing=repository.maturityEvent(term.termContractId(),term.maturityDate());if(existing.isPresent()){repository.insertMaturityItem(itemId,runId,term,existing.get().maturityEventId(),"SKIPPED",null,"Maturity event قبلاً برای این چرخه ثبت شده است.",actor);}else{long eventId=repository.next("SEQ_DEPOSIT_MATURITY_EVENT");repository.insertPendingMaturityEvent(eventId,term,actor);repository.insertMaturityItem(itemId,runId,term,eventId,"PROCESSED",null,"Maturity event در وضعیت PENDING ثبت شد؛ اجرای مالی توسط workflow متناظر انجام می‌شود.",actor);}processed++;}catch(Exception e){failed++;repository.insertMaturityItem(itemId,runId,term,null,"FAILED","MATURITY_ITEM_ERROR",truncate(e.getMessage(),500),actor);}}
        repository.completeMaturityRun(runId,due.size(),processed,failed,actor);repository.completeIdempotency(idempotencyKey,"MATRUN:"+runId);return new MaturityRunResponse(repository.maturityRun(runId),false);
    }

    @Transactional(readOnly=true)
    public List<MaturityProcessRun> maturityRuns(){return repository.recentMaturityRuns();}

    private WaveBView view(long accountId){return new WaveBView(repository.templates(),repository.statements(accountId),new LimitControlsView(repository.limits(accountId),repository.usages(accountId),repository.restrictions(accountId)),repository.recentMaturityRuns());}
    private void requireAccount(long accountId){if(accountId<=0||!repository.accountExists(accountId))throw new DepositAccountNotFoundException("حساب سپرده با شناسه "+accountId+" یافت نشد.");}
    private boolean replayOrClaim(String key,Long accountId,String operation,String payloadHash,String actor,String correlation){String k=required(key,"X-Idempotency-Key");if(k.length()>128)throw new IllegalArgumentException("X-Idempotency-Key حداکثر 128 کاراکتر است.");var row=repository.idempotency(k).orElse(null);if(row!=null){if(!Objects.equals(row.accountId(),accountId)||!operation.equals(row.operation())||!payloadHash.equals(row.payloadHash()))throw new IllegalArgumentException("Idempotency-Key قبلاً برای درخواست دیگری استفاده شده است.");if("COMPLETED".equals(row.status()))return true;throw new IllegalArgumentException("درخواست با همین Idempotency-Key در حال پردازش است.");}repository.claimIdempotency(repository.next("SEQ_DEPOSIT_OPERATION_IDEMPOTENCY"),k,accountId,operation,payloadHash,actor,correlation);return false;}
    private long parseResult(String key,String prefix){String ref=repository.idempotency(key).orElseThrow().resultReference();if(ref==null||!ref.startsWith(prefix))throw new IllegalStateException("Idempotency result نامعتبر است: "+ref);return Long.parseLong(ref.substring(prefix.length()));}
    private void validateDeliveryTarget(long accountId,String channel,String target){if(channel==null)return;if(target==null)throw new IllegalArgumentException("مقصد برای کانال "+channel+" الزامی است.");LocalDate today=LocalDate.now(ZoneOffset.UTC);if("EMAIL".equals(channel)){if(!target.contains("@"))throw new IllegalArgumentException("مقصد EMAIL معتبر نیست.");if(!repository.hasActiveContact(accountId,"EMAIL",target,today))throw new IllegalArgumentException("مقصد EMAIL باید از Contact فعال حساب انتخاب شود.");return;}if("SMS".equals(channel)){if(!target.matches("[+0-9][0-9+ -]{5,24}"))throw new IllegalArgumentException("مقصد SMS معتبر نیست.");if(!repository.hasActiveContact(accountId,"MOBILE",target,today))throw new IllegalArgumentException("مقصد SMS باید از MOBILE فعال حساب انتخاب شود.");return;}if("PORTAL".equals(channel)&&!"PORTAL".equals(target))throw new IllegalArgumentException("مقصد PORTAL نامعتبر است.");if("API".equals(channel)&&!"REQUESTING_API_CLIENT".equals(target))throw new IllegalArgumentException("مقصد API نامعتبر است.");}
    private static void enforceRelease(String policy,String originSystem,String originModule,String actionSystem,String actionModule,String authority){String p=upper(policy);if("AUTO_EXPIRY".equals(p))throw new IllegalArgumentException("رکورد با سیاست AUTO_EXPIRY از مسیر کاربری قابل لغو نیست.");boolean origin=Objects.equals(upper(originSystem),upper(actionSystem))&&(originModule==null||Objects.equals(upper(originModule),upper(actionModule)));if("ORIGIN_ONLY".equals(p)&&!origin)throw new IllegalArgumentException("لغو فقط توسط Origin ثبت‌کننده مجاز است.");if(("ORIGIN_OR_AUTHORITY".equals(p)||"ORIGIN_OR_OVERRIDE".equals(p))&&!origin&&authority==null)throw new IllegalArgumentException("لغو توسط غیر-Origin نیازمند Authority/Override reference است.");}
    private static String periodUnit(String type){if(type.startsWith("DAILY_"))return "DAY";if(type.startsWith("MONTHLY_"))return "MONTH";return null;}
    private static PeriodWindow periodWindow(UsageLimit l,LocalDate booking){String unit=upper(l.periodUnit());if(unit==null){if(l.limitType().startsWith("MONTHLY_"))unit="MONTH";else unit="DAY";}int value=l.periodValue()==null||l.periodValue()<1?1:l.periodValue();LocalDateTime start;LocalDateTime end;if("MONTH".equals(unit)){LocalDate first=booking.withDayOfMonth(1);start=first.atStartOfDay();end=first.plusMonths(value).atStartOfDay().minusNanos(1_000);}else if("WEEK".equals(unit)){LocalDate first=booking.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));start=first.atStartOfDay();end=first.plusWeeks(value).atStartOfDay().minusNanos(1_000);}else if("ROLLING_HOURS".equals(unit)){start=booking.atStartOfDay();end=start.plusHours(value).minusNanos(1_000);}else{start=booking.atStartOfDay();end=booking.plusDays(value).atStartOfDay().minusNanos(1_000);}return new PeriodWindow(start.atOffset(ZoneOffset.UTC),end.atOffset(ZoneOffset.UTC));}
    private static String required(String v,String field){String x=trim(v);if(x==null)throw new IllegalArgumentException(field+" الزامی است.");return x;}
    private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}
    private static String upper(String v){String x=trim(v);return x==null?null:x.toUpperCase(Locale.ROOT);}
    private static String defaultUpper(String v,String d){String x=upper(v);return x==null?d:x;}
    private static String truncate(String v,int n){if(v==null)return null;return v.length()<=n?v:v.substring(0,n);}
    private static String hash(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private record PeriodWindow(OffsetDateTime start,OffsetDateTime end){}
}
