-- Read-only installation-state diagnostic. No COMMIT/ROLLBACK is executed.
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE NONE;
ALTER SESSION SET CURRENT_SCHEMA = FEE;

PROMPT === Oracle connection context ===
SELECT SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV','CON_NAME') CON_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME,
       SYS_CONTEXT('USERENV','SESSION_USER') SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA
  FROM dual;

PROMPT === CBI 1405 provisional state ===
SELECT 'SOURCE' ITEM, COUNT(*) CNT FROM FEE_REGULATORY_SOURCE WHERE SOURCE_CODE='CBI_RIAL_FEE_1405_PROVISIONAL'
UNION ALL
SELECT 'DEFINITIONS', COUNT(*) FROM FEE_DEFINITION WHERE CLASSIFICATION_CODE='CBI_1405_RIAL_PROVISIONAL'
UNION ALL
SELECT 'ACTIVE_VERSIONS', COUNT(*)
  FROM FEE_DEFINITION_VERSION dv JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
 WHERE d.CLASSIFICATION_CODE='CBI_1405_RIAL_PROVISIONAL' AND dv.VERSION_NO='1405.P1' AND dv.STATUS_CODE='ACTIVE'
UNION ALL
SELECT 'ACTIVE_RULES', COUNT(*)
  FROM FEE_CALCULATION_RULE r JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_VERSION_ID=r.FEE_DEFINITION_VERSION_ID
  JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
 WHERE d.CLASSIFICATION_CODE='CBI_1405_RIAL_PROVISIONAL' AND r.IS_ACTIVE='Y';

PROMPT === Prior CBI 1404 non-electronic version state ===
SELECT dv.STATUS_CODE, dv.EFFECTIVE_TO, COUNT(*) CNT
  FROM FEE_DEFINITION_VERSION dv
  JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
  JOIN FEE_FEATURE f ON f.FEE_FEATURE_ID=d.FEE_FEATURE_ID
  JOIN FEE_REGULATORY_SOURCE rs ON rs.REGULATORY_SOURCE_ID=dv.REGULATORY_SOURCE_ID
 WHERE rs.SOURCE_CODE='CBI_FEE_1404_04_35500'
   AND dv.VERSION_NO='1.0'
   AND f.FEATURE_CODE IN ('CBI_GUARANTEE_FEE_GROUP','CBI_REMITTANCE_FEE_GROUP','CBI_SAFE_DEPOSIT_FEE_GROUP','CBI_SECURITIES_FEE_GROUP','CBI_BILL_COLLECTION_FEE_GROUP','CBI_CURRENT_ACCOUNT_FEE_GROUP','CBI_SAVINGS_DEPOSIT_FEE_GROUP','CBI_CERTIFICATE_FEE_GROUP','CBI_STATEMENT_FEE_GROUP','CBI_ACCOUNT_SERVICE_FEE_GROUP','CBI_APPRAISAL_FEE_GROUP','CBI_CREDIT_FEE_GROUP','CBI_OTHER_SERVICE_FEE_GROUP')
 GROUP BY dv.STATUS_CODE,dv.EFFECTIVE_TO
 ORDER BY dv.STATUS_CODE,dv.EFFECTIVE_TO;
