package com.behsazan.corebanking.deposit.account.term.oracle;

import com.behsazan.corebanking.deposit.account.term.domain.DepositTermModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;

@Repository
public class DepositTermRepository {
    public record AccountRow(long accountId,String status,String currencyCode,long currentProductVersionId,String productFamilyCode) {}
    public record TermLock(long termContractId,long accountId,long productVersionId,LocalDate maturityDate,BigDecimal principalAmount,BigDecimal contractRate,long renewalCount,String instructionCode,String statusCode,long recordVersion) {}
    public record ApprovalRow(Long approvalId,String approvalStatus,String requestedByUserId,String approverUserId) {}
    public record IdempotencyRow(Long accountId,String operationType,String payloadHash,String processingStatus,String resultReference) {}
    public record SettlementAccount(long accountId,String accountNo,String status,String currencyCode) {}
    private final NamedParameterJdbcTemplate jdbc; private final String schema,productSchema;
    public DepositTermRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.schemas.deposit-account:DPS2}") String schema,@Value("${core-banking.schemas.product-definition:PDL}") String productSchema){this.jdbc=jdbc;this.schema=id(schema);this.productSchema=id(productSchema);}

    public Optional<AccountRow> account(long accountId,boolean lock){String sql="SELECT A.ACCOUNT_ID,A.ACCOUNT_STATUS_CODE,A.CURRENCY_CODE,A.CURRENT_PRODUCT_VERSION_ID FROM "+schema+".DEPOSIT_ACCOUNT A WHERE A.ACCOUNT_ID=:id"+(lock?" FOR UPDATE":"");var rows=jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new AccountRow(r.getLong(1),r.getString(2),r.getString(3),r.getLong(4),null));if(rows.isEmpty())return Optional.empty();AccountRow a=rows.get(0);return Optional.of(new AccountRow(a.accountId(),a.status(),a.currencyCode(),a.currentProductVersionId(),productFamily(a.currentProductVersionId()).orElse(null)));}
    public Optional<SettlementAccount> settlementAccount(long accountId){String sql="SELECT ACCOUNT_ID,ACCOUNT_NO,ACCOUNT_STATUS_CODE,CURRENCY_CODE FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new SettlementAccount(r.getLong(1),r.getString(2),r.getString(3),r.getString(4))).stream().findFirst();}
    public Optional<SettlementAccount> settlementAccountByReference(String reference){if(reference==null||reference.isBlank())return Optional.empty();String sql="SELECT ACCOUNT_ID,ACCOUNT_NO,ACCOUNT_STATUS_CODE,CURRENCY_CODE FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_NO=:ref";return jdbc.query(sql,new MapSqlParameterSource("ref",reference.trim()),(r,n)->new SettlementAccount(r.getLong(1),r.getString(2),r.getString(3),r.getString(4))).stream().findFirst();}
    public Optional<String> accountOrgUnit(long accountId){String sql="SELECT ORG_UNIT_CODE FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->r.getString(1)).stream().findFirst();}
    public String instructionActor(long termContractId,String fallback){String sql="SELECT COALESCE(UPDATED_BY,CREATED_BY,:fallback) FROM "+schema+".DEPOSIT_TERM_CONTRACT WHERE TERM_CONTRACT_ID=:id";return jdbc.query(sql,new MapSqlParameterSource().addValue("id",termContractId).addValue("fallback",fallback),(r,n)->r.getString(1)).stream().findFirst().orElse(fallback);}
    public Optional<String> productFamily(long productVersionId){String sql="SELECT P.PRODUCT_FAMILY_CODE FROM "+productSchema+".PRODUCT_VERSION PV JOIN "+productSchema+".PRODUCT P ON P.PRODUCT_ID=PV.PRODUCT_ID WHERE PV.PRODUCT_VERSION_ID=:id";return jdbc.query(sql,new MapSqlParameterSource("id",productVersionId),(r,n)->r.getString(1)).stream().findFirst();}
    public Optional<TermLock> lockTerm(long accountId){String sql="SELECT TERM_CONTRACT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,MATURITY_DATE,PRINCIPAL_AMOUNT,CONTRACT_RATE,RENEWAL_COUNT,MATURITY_INSTRUCTION_CODE,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_TERM_CONTRACT WHERE ACCOUNT_ID=:id AND STATUS_CODE='ACTIVE' AND TERM_CONTRACT_ID=(SELECT MAX(X.TERM_CONTRACT_ID) FROM "+schema+".DEPOSIT_TERM_CONTRACT X WHERE X.ACCOUNT_ID=:id AND X.STATUS_CODE='ACTIVE') FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new TermLock(r.getLong(1),r.getLong(2),r.getLong(3),date(r,4),r.getBigDecimal(5),r.getBigDecimal(6),r.getLong(7),r.getString(8),r.getString(9),r.getLong(10))).stream().findFirst();}
    public Optional<TermContract> term(long accountId){String sql="SELECT TERM_CONTRACT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,TERM_CODE,TERM_VALUE,TERM_UNIT_CODE,START_DATE,MATURITY_DATE,PRINCIPAL_AMOUNT,CONTRACT_RATE,RENEWAL_COUNT,MATURITY_SETTLEMENT_ACCOUNT_ID,MATURITY_SETTLEMENT_ACCOUNT_REFERENCE,MATURITY_INSTRUCTION_SOURCE_CODE,MATURITY_INSTRUCTION_CODE,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_TERM_CONTRACT WHERE ACCOUNT_ID=:id ORDER BY TERM_CONTRACT_ID DESC FETCH FIRST 1 ROWS ONLY";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new TermContract(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getLong(5),r.getString(6),date(r,7),date(r,8),r.getBigDecimal(9),r.getBigDecimal(10),r.getLong(11),r.getObject(12,Long.class),r.getString(13),r.getString(14),r.getString(15),r.getString(16),r.getLong(17))).stream().findFirst();}
    public int provisionContractFromOpening(long accountId,long openingRequestId,long productVersionId,String actor){
        String sql="""
                INSERT INTO %s.DEPOSIT_TERM_CONTRACT(
                  TERM_CONTRACT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,TERM_CODE,TERM_VALUE,TERM_UNIT_CODE,START_DATE,MATURITY_DATE,
                  PRINCIPAL_AMOUNT,CONTRACT_RATE,RENEWAL_COUNT,MATURITY_SETTLEMENT_ACCOUNT_ID,MATURITY_SETTLEMENT_ACCOUNT_REFERENCE,
                  MATURITY_INSTRUCTION_SOURCE_CODE,MATURITY_INSTRUCTION_CODE,STATUS_CODE,SOURCE_OPENING_TERM_ID,SOURCE_OPENING_MATURITY_ID,
                  CREATED_AT,CREATED_BY,RECORD_VERSION)
                SELECT %s.SEQ_DEPOSIT_TERM_CONTRACT.NEXTVAL,:aid,:pv,OT.TERM_CODE,OT.TERM_VALUE,OT.TERM_UNIT_CODE,
                       OT.START_DATE,OT.MATURITY_DATE,NVL(B.LEDGER_BALANCE,0),NULL,0,
                       MI.SETTLEMENT_ACCOUNT_ID,MI.SETTLEMENT_ACCOUNT_REFERENCE,NVL(MI.INSTRUCTION_SOURCE_CODE,'PRODUCT_DEFAULT'),
                       NVL(MI.MATURITY_ACTION_CODE,CASE WHEN OT.AUTO_RENEW_FLAG=1 THEN 'RENEW_PRINCIPAL' ELSE 'WAIT_INSTRUCTION' END),
                       'ACTIVE',OT.OPENING_TERM_ID,MI.OPENING_MATURITY_INSTRUCTION_ID,SYSTIMESTAMP,:actor,1
                  FROM %s.DEPOSIT_OPENING_TERM OT
                  LEFT JOIN %s.DEPOSIT_OPENING_MATURITY_INSTRUCTION MI ON MI.OPENING_TERM_ID=OT.OPENING_TERM_ID
                  LEFT JOIN %s.DEPOSIT_ACCOUNT_BALANCE B ON B.ACCOUNT_ID=:aid
                 WHERE OT.OPENING_REQUEST_ID=:oid
                   AND OT.MATURITY_DATE>OT.START_DATE
                   AND NOT EXISTS (SELECT 1 FROM %s.DEPOSIT_TERM_CONTRACT T WHERE T.ACCOUNT_ID=:aid AND T.STATUS_CODE='ACTIVE')
                """.formatted(schema,schema,schema,schema,schema,schema);
        return jdbc.update(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("oid",openingRequestId).addValue("pv",productVersionId).addValue("actor",actor));
    }
    public int updateInstruction(long termId,String code,String source,Long settlementId,String settlementRef,long version,String actor){String sql="UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET MATURITY_INSTRUCTION_CODE=:code,MATURITY_INSTRUCTION_SOURCE_CODE=:src,MATURITY_SETTLEMENT_ACCOUNT_ID=:sid,MATURITY_SETTLEMENT_ACCOUNT_REFERENCE=:sref,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:id AND RECORD_VERSION=:v AND STATUS_CODE='ACTIVE'";return jdbc.update(sql,new MapSqlParameterSource().addValue("code",code).addValue("src",source).addValue("sid",settlementId).addValue("sref",settlementRef).addValue("actor",actor).addValue("id",termId).addValue("v",version));}

    public long next(String seq){Long v=jdbc.queryForObject("SELECT "+schema+"."+seq+".NEXTVAL FROM DUAL",new MapSqlParameterSource(),Long.class);return Objects.requireNonNull(v);}
    public long nextApproval(){return next("SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST");}
    public long nextIdem(){return next("SEQ_DEPOSIT_OPERATION_IDEMPOTENCY");}
    public void insertApproval(long id,long accountId,String operation,String sourceType,long sourceId,String requested,String approver,String org,String idem,String correlation){String tracking="TM-"+id;jdbc.update("INSERT INTO "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST(APPROVAL_REQUEST_ID,TRACKING_NO,ACCOUNT_ID,OPERATION_TYPE_CODE,SOURCE_ENTITY_TYPE,SOURCE_ENTITY_ID,REQUESTED_BY_USER_ID,REQUESTED_AT,APPROVER_USER_ID,APPROVAL_STATUS_CODE,ORG_UNIT_CODE,IDEMPOTENCY_KEY,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tracking,:aid,:op,:stype,:sid,:req,SYSTIMESTAMP,:appr,'PENDING_APPROVAL',:org,:idem,'CORE_BANKING','TERM_DEPOSIT',:idem,:corr,SYSTIMESTAMP,:req,1)",new MapSqlParameterSource().addValue("id",id).addValue("tracking",tracking).addValue("aid",accountId).addValue("op",operation).addValue("stype",sourceType).addValue("sid",sourceId).addValue("req",requested).addValue("appr",approver).addValue("org",org).addValue("idem",idem).addValue("corr",correlation));}
    public int approve(long approvalId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST SET APPROVAL_STATUS_CODE='APPROVED',DECIDED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE APPROVAL_REQUEST_ID=:id AND APPROVAL_STATUS_CODE='PENDING_APPROVAL' AND APPROVER_USER_ID=:actor",new MapSqlParameterSource().addValue("id",approvalId).addValue("actor",actor));}
    public Optional<ApprovalRow> approval(long id){String sql="SELECT APPROVAL_REQUEST_ID,APPROVAL_STATUS_CODE,REQUESTED_BY_USER_ID,APPROVER_USER_ID FROM "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST WHERE APPROVAL_REQUEST_ID=:id";return jdbc.query(sql,new MapSqlParameterSource("id",id),(r,n)->new ApprovalRow(r.getLong(1),r.getString(2),r.getString(3),r.getString(4))).stream().findFirst();}

    public void insertRenewal(long id,long termId,long no,long prevPv,long newPv,LocalDate fromMat,LocalDate start,LocalDate newMat,BigDecimal prevRate,BigDecimal newRate,BigDecimal principal,long approval,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_RENEWAL(TERM_RENEWAL_ID,TERM_CONTRACT_ID,RENEWAL_NO,PREVIOUS_PRODUCT_VERSION_ID,NEW_PRODUCT_VERSION_ID,FROM_MATURITY_DATE,NEW_START_DATE,NEW_MATURITY_DATE,PREVIOUS_RATE,NEW_RATE,RENEWED_PRINCIPAL,APPROVAL_REQUEST_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:no,:ppv,:npv,:fm,:ns,:nm,:pr,:nr,:p,:ap,'REQUESTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("no",no).addValue("ppv",prevPv).addValue("npv",newPv).addValue("fm",java.sql.Date.valueOf(fromMat)).addValue("ns",java.sql.Date.valueOf(start)).addValue("nm",java.sql.Date.valueOf(newMat)).addValue("pr",prevRate).addValue("nr",newRate).addValue("p",principal).addValue("ap",approval).addValue("actor",actor));}
    public int markRenewalApproved(long id,String actor){return statusUpdate("DEPOSIT_TERM_RENEWAL","TERM_RENEWAL_ID",id,"REQUESTED","APPROVED",actor);}
    public int executeRenewal(long id,long termId,long newPv,LocalDate start,LocalDate mat,BigDecimal rate,BigDecimal principal,String actor){int a=jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_RENEWAL SET STATUS_CODE='EXECUTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_RENEWAL_ID=:id AND STATUS_CODE='APPROVED'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id));if(a==1)jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET PRODUCT_VERSION_ID=:pv,START_DATE=:sd,MATURITY_DATE=:md,CONTRACT_RATE=:rate,PRINCIPAL_AMOUNT=:p,RENEWAL_COUNT=RENEWAL_COUNT+1,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("pv",newPv).addValue("sd",java.sql.Date.valueOf(start)).addValue("md",java.sql.Date.valueOf(mat)).addValue("rate",rate).addValue("p",principal).addValue("actor",actor).addValue("tid",termId));return a;}

    public long executeAutomaticRenewal(long termId,long accountId,long renewalNo,long productVersionId,LocalDate fromMaturity,LocalDate newStart,LocalDate newMaturity,BigDecimal rate,BigDecimal principal,String actor){long id=next("SEQ_DEPOSIT_TERM_RENEWAL");jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_RENEWAL(TERM_RENEWAL_ID,TERM_CONTRACT_ID,RENEWAL_NO,PREVIOUS_PRODUCT_VERSION_ID,NEW_PRODUCT_VERSION_ID,FROM_MATURITY_DATE,NEW_START_DATE,NEW_MATURITY_DATE,PREVIOUS_RATE,NEW_RATE,RENEWED_PRINCIPAL,APPROVAL_REQUEST_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:no,:pv,:pv,:fm,:ns,:nm,:rate,:rate,:p,NULL,'EXECUTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("no",renewalNo).addValue("pv",productVersionId).addValue("fm",java.sql.Date.valueOf(fromMaturity)).addValue("ns",java.sql.Date.valueOf(newStart)).addValue("nm",java.sql.Date.valueOf(newMaturity)).addValue("rate",rate).addValue("p",principal).addValue("actor",actor));int u=jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET START_DATE=:sd,MATURITY_DATE=:md,RENEWAL_COUNT=:no,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("sd",java.sql.Date.valueOf(newStart)).addValue("md",java.sql.Date.valueOf(newMaturity)).addValue("no",renewalNo).addValue("actor",actor).addValue("tid",termId).addValue("aid",accountId));if(u!=1)throw new IllegalStateException("Term contract automatic renewal update failed.");return id;}

    public void insertPartialWithdrawal(long id,long termId,long accountId,BigDecimal amount,BigDecimal before,long approval,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_PARTIAL_WITHDRAWAL(PARTIAL_WITHDRAWAL_ID,TERM_CONTRACT_ID,ACCOUNT_ID,REQUESTED_AMOUNT,PRINCIPAL_BEFORE,APPROVAL_REQUEST_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:aid,:amt,:before,:ap,'REQUESTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("aid",accountId).addValue("amt",amount).addValue("before",before).addValue("ap",approval).addValue("actor",actor));}
    public int markPartialApproved(long id,String actor){return statusUpdate("DEPOSIT_TERM_PARTIAL_WITHDRAWAL","PARTIAL_WITHDRAWAL_ID",id,"REQUESTED","APPROVED",actor);}
    public int executePartial(long id,long termId,BigDecimal amount,BigDecimal after,LocalDate date,long transactionId,String actor){int a=jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_PARTIAL_WITHDRAWAL SET EFFECTIVE_AMOUNT=:amt,PRINCIPAL_AFTER=:after,EFFECTIVE_DATE=:dt,TRANSACTION_ID=:tx,STATUS_CODE='EXECUTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE PARTIAL_WITHDRAWAL_ID=:id AND STATUS_CODE='APPROVED'",new MapSqlParameterSource().addValue("amt",amount).addValue("after",after).addValue("dt",java.sql.Date.valueOf(date)).addValue("tx",transactionId).addValue("actor",actor).addValue("id",id));if(a==1)jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET PRINCIPAL_AMOUNT=:after,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("after",after).addValue("actor",actor).addValue("tid",termId));return a;}

    public void insertConversion(long id,long termId,long accountId,long fromPv,long toPv,LocalDate eff,BigDecimal principal,long approval,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_CONVERSION(TERM_CONVERSION_ID,TERM_CONTRACT_ID,ACCOUNT_ID,FROM_PRODUCT_VERSION_ID,TO_PRODUCT_VERSION_ID,EFFECTIVE_DATE,PRINCIPAL_BEFORE,PRINCIPAL_AFTER,APPROVAL_REQUEST_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:aid,:fromPv,:toPv,:eff,:p,:p,:ap,'REQUESTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("aid",accountId).addValue("fromPv",fromPv).addValue("toPv",toPv).addValue("eff",java.sql.Date.valueOf(eff)).addValue("p",principal).addValue("ap",approval).addValue("actor",actor));}
    public int markConversionApproved(long id,String actor){return statusUpdate("DEPOSIT_TERM_CONVERSION","TERM_CONVERSION_ID",id,"REQUESTED","APPROVED",actor);}
    public int executeConversion(long id,long termId,long accountId,long fromPv,long toPv,LocalDate eff,long approval,String actor){int a=jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONVERSION SET STATUS_CODE='EXECUTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONVERSION_ID=:id AND STATUS_CODE='APPROVED'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id));if(a==1){jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET PRODUCT_VERSION_ID=:toPv,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("toPv",toPv).addValue("actor",actor).addValue("tid",termId));jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT SET CURRENT_PRODUCT_VERSION_ID=:toPv,PRODUCT_VERSION_ID=:toPv,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_ID=:aid AND CURRENT_PRODUCT_VERSION_ID=:fromPv",new MapSqlParameterSource().addValue("toPv",toPv).addValue("actor",actor).addValue("aid",accountId).addValue("fromPv",fromPv));jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_PRODUCT_HISTORY(ACCOUNT_PRODUCT_HISTORY_ID,ACCOUNT_ID,FROM_PRODUCT_VERSION_ID,TO_PRODUCT_VERSION_ID,EFFECTIVE_DATE,CHANGE_REASON_CODE,APPROVAL_REQUEST_ID,MIGRATION_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES("+schema+".SEQ_DEPOSIT_ACCOUNT_PRODUCT_HISTORY.NEXTVAL,:aid,:fromPv,:toPv,:eff,'TERM_CONVERSION',:ap,'EXECUTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("aid",accountId).addValue("fromPv",fromPv).addValue("toPv",toPv).addValue("eff",java.sql.Date.valueOf(eff)).addValue("ap",approval).addValue("actor",actor));}return a;}

    public void insertEarlyTermination(long id,long termId,long accountId,LocalDate date,BigDecimal principal,BigDecimal accruedProfit,BigDecimal earlyRate,BigDecimal adjustment,BigDecimal tax,BigDecimal fee,BigDecimal net,long approval,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_EARLY_TERMINATION(EARLY_TERMINATION_ID,TERM_CONTRACT_ID,ACCOUNT_ID,TERMINATION_DATE,PRINCIPAL_AMOUNT,ACCRUED_PROFIT_AMOUNT,EARLY_TERMINATION_RATE,ADJUSTMENT_AMOUNT,TAX_AMOUNT,FEE_AMOUNT,NET_SETTLEMENT_AMOUNT,APPROVAL_REQUEST_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:aid,:dt,:p,:profit,:rate,:adj,:tax,:fee,:net,:ap,'REQUESTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("aid",accountId).addValue("dt",java.sql.Date.valueOf(date)).addValue("p",principal).addValue("profit",accruedProfit).addValue("rate",earlyRate).addValue("adj",adjustment).addValue("tax",tax).addValue("fee",fee).addValue("net",net).addValue("ap",approval).addValue("actor",actor));}
    public void insertCalculatedSettlement(long id,long termId,String type,BigDecimal principal,BigDecimal profit,BigDecimal adjustment,BigDecimal tax,BigDecimal fee,BigDecimal net,String dest,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_SETTLEMENT(TERM_SETTLEMENT_ID,TERM_CONTRACT_ID,SETTLEMENT_TYPE_CODE,GROSS_PRINCIPAL,GROSS_PROFIT,TAX_AMOUNT,FEE_AMOUNT,ADJUSTMENT_AMOUNT,NET_AMOUNT,DESTINATION_ACCOUNT_REFERENCE,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:type,:p,:profit,:tax,:fee,:adj,:net,:dest,'CALCULATED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("type",type).addValue("p",principal).addValue("profit",profit).addValue("tax",tax).addValue("fee",fee).addValue("adj",adjustment).addValue("net",net).addValue("dest",dest).addValue("actor",actor));}
    public void insertPostedSettlement(long id,long termId,String type,BigDecimal principal,BigDecimal profit,BigDecimal adjustment,BigDecimal net,String dest,long transactionId,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_TERM_SETTLEMENT(TERM_SETTLEMENT_ID,TERM_CONTRACT_ID,SETTLEMENT_TYPE_CODE,GROSS_PRINCIPAL,GROSS_PROFIT,ADJUSTMENT_AMOUNT,NET_AMOUNT,DESTINATION_ACCOUNT_REFERENCE,TRANSACTION_ID,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:type,:p,:profit,:adj,:net,:dest,:tx,'POSTED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("type",type).addValue("p",principal).addValue("profit",profit).addValue("adj",adjustment).addValue("net",net).addValue("dest",dest).addValue("tx",transactionId).addValue("actor",actor));}
    public int executeEarlyTermination(long id,long termId,long transactionId,String actor){int a=jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_EARLY_TERMINATION SET SETTLEMENT_TRANSACTION_ID=:tx,STATUS_CODE='EXECUTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE EARLY_TERMINATION_ID=:id AND STATUS_CODE='REQUESTED'",new MapSqlParameterSource().addValue("tx",transactionId).addValue("actor",actor).addValue("id",id));if(a==1)jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET PRINCIPAL_AMOUNT=0,STATUS_CODE='TERMINATED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("tid",termId));return a;}
    public int markCalculatedSettlementPosted(long termId,String type,long transactionId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_SETTLEMENT SET TRANSACTION_ID=:tx,STATUS_CODE='POSTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_SETTLEMENT_ID=(SELECT MAX(S.TERM_SETTLEMENT_ID) FROM "+schema+".DEPOSIT_TERM_SETTLEMENT S WHERE S.TERM_CONTRACT_ID=:tid AND S.SETTLEMENT_TYPE_CODE=:type AND S.STATUS_CODE='CALCULATED')",new MapSqlParameterSource().addValue("tx",transactionId).addValue("actor",actor).addValue("tid",termId).addValue("type",type));}
    public int markContractMatured(long termId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_TERM_CONTRACT SET PRINCIPAL_AMOUNT=0,STATUS_CODE='MATURED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("tid",termId));}

    public long upsertMaturityEvent(long id,long termId,long accountId,LocalDate maturity,String instruction,BigDecimal principal,BigDecimal profit,String result,Long renewalId,Long settlementTransactionId,boolean processed,String actor){MapSqlParameterSource p=new MapSqlParameterSource().addValue("id",id).addValue("tid",termId).addValue("aid",accountId).addValue("md",java.sql.Date.valueOf(maturity)).addValue("ins",instruction).addValue("p",principal).addValue("profit",profit).addValue("result",result).addValue("rid",renewalId).addValue("tx",settlementTransactionId).addValue("actor",actor);String processedSql=processed?"SYSTIMESTAMP":"NULL";int updated=jdbc.update("UPDATE "+schema+".DEPOSIT_MATURITY_EVENT SET INSTRUCTION_CODE=:ins,PRINCIPAL_AMOUNT=:p,PROFIT_AMOUNT=:profit,ACTION_RESULT_CODE=:result,RELATED_RENEWAL_ID=:rid,SETTLEMENT_TRANSACTION_ID=:tx,PROCESSED_AT="+processedSql+",UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TERM_CONTRACT_ID=:tid AND MATURITY_DATE=:md",p);if(updated==0)jdbc.update("INSERT INTO "+schema+".DEPOSIT_MATURITY_EVENT(MATURITY_EVENT_ID,TERM_CONTRACT_ID,ACCOUNT_ID,MATURITY_DATE,INSTRUCTION_CODE,PRINCIPAL_AMOUNT,PROFIT_AMOUNT,ACTION_RESULT_CODE,RELATED_RENEWAL_ID,SETTLEMENT_TRANSACTION_ID,PROCESSED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:aid,:md,:ins,:p,:profit,:result,:rid,:tx,"+processedSql+",SYSTIMESTAMP,:actor,1)",p);return jdbc.queryForObject("SELECT MATURITY_EVENT_ID FROM "+schema+".DEPOSIT_MATURITY_EVENT WHERE TERM_CONTRACT_ID=:tid AND MATURITY_DATE=:md",p,Long.class);}
    public void insertMaturityEvent(long id,long termId,long accountId,LocalDate maturity,String instruction,BigDecimal principal,String result,Long renewalId,String actor){upsertMaturityEvent(id,termId,accountId,maturity,instruction,principal,null,result,renewalId,null,true,actor);}
    public Optional<MaturityEvent> maturityEvent(long termId,LocalDate maturity){String sql="SELECT MATURITY_EVENT_ID,TERM_CONTRACT_ID,ACCOUNT_ID,MATURITY_DATE,INSTRUCTION_CODE,PRINCIPAL_AMOUNT,PROFIT_AMOUNT,ACTION_RESULT_CODE,RELATED_RENEWAL_ID,SETTLEMENT_TRANSACTION_ID,PROCESSED_AT FROM "+schema+".DEPOSIT_MATURITY_EVENT WHERE TERM_CONTRACT_ID=:tid AND MATURITY_DATE=:md";return jdbc.query(sql,new MapSqlParameterSource().addValue("tid",termId).addValue("md",java.sql.Date.valueOf(maturity)),(r,n)->new MaturityEvent(r.getLong(1),r.getLong(2),r.getLong(3),date(r,4),r.getString(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8),r.getObject(9,Long.class),r.getObject(10,Long.class),odt(r.getTimestamp(11)))).stream().findFirst();}


    public List<MaturityEvent> maturityEvents(long accountId){return jdbc.query("SELECT MATURITY_EVENT_ID,TERM_CONTRACT_ID,ACCOUNT_ID,MATURITY_DATE,INSTRUCTION_CODE,PRINCIPAL_AMOUNT,PROFIT_AMOUNT,ACTION_RESULT_CODE,RELATED_RENEWAL_ID,SETTLEMENT_TRANSACTION_ID,PROCESSED_AT FROM "+schema+".DEPOSIT_MATURITY_EVENT WHERE ACCOUNT_ID=:id ORDER BY MATURITY_EVENT_ID DESC",new MapSqlParameterSource("id",accountId),(r,n)->new MaturityEvent(r.getLong(1),r.getLong(2),r.getLong(3),date(r,4),r.getString(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8),r.getObject(9,Long.class),r.getObject(10,Long.class),odt(r.getTimestamp(11))));}
    public List<Renewal> renewals(long accountId){String sql="SELECT R.TERM_RENEWAL_ID,R.TERM_CONTRACT_ID,R.RENEWAL_NO,R.PREVIOUS_PRODUCT_VERSION_ID,R.NEW_PRODUCT_VERSION_ID,R.FROM_MATURITY_DATE,R.NEW_START_DATE,R.NEW_MATURITY_DATE,R.PREVIOUS_RATE,R.NEW_RATE,R.RENEWED_PRINCIPAL,R.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,A.APPROVER_USER_ID,R.STATUS_CODE,R.RECORD_VERSION FROM "+schema+".DEPOSIT_TERM_RENEWAL R JOIN "+schema+".DEPOSIT_TERM_CONTRACT T ON T.TERM_CONTRACT_ID=R.TERM_CONTRACT_ID LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=R.APPROVAL_REQUEST_ID WHERE T.ACCOUNT_ID=:id ORDER BY R.TERM_RENEWAL_ID DESC";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new Renewal(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getLong(5),date(r,6),date(r,7),date(r,8),r.getBigDecimal(9),r.getBigDecimal(10),r.getBigDecimal(11),r.getObject(12,Long.class),r.getString(13),r.getString(14),r.getString(15),r.getLong(16)));}
    public List<PartialWithdrawal> partials(long accountId){String sql="SELECT W.PARTIAL_WITHDRAWAL_ID,W.TERM_CONTRACT_ID,W.ACCOUNT_ID,W.REQUESTED_AMOUNT,W.EFFECTIVE_AMOUNT,W.PRINCIPAL_BEFORE,W.PRINCIPAL_AFTER,W.PROFIT_RECALC_AMOUNT,W.ADJUSTMENT_AMOUNT,W.TRANSACTION_ID,W.EFFECTIVE_DATE,W.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,A.APPROVER_USER_ID,W.STATUS_CODE,W.RECORD_VERSION FROM "+schema+".DEPOSIT_TERM_PARTIAL_WITHDRAWAL W LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=W.APPROVAL_REQUEST_ID WHERE W.ACCOUNT_ID=:id ORDER BY W.PARTIAL_WITHDRAWAL_ID DESC";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new PartialWithdrawal(r.getLong(1),r.getLong(2),r.getLong(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getObject(10,Long.class),r.getDate(11)==null?null:r.getDate(11).toLocalDate(),r.getObject(12,Long.class),r.getString(13),r.getString(14),r.getString(15),r.getLong(16)));}
    public List<TermConversion> conversions(long accountId){String sql="SELECT C.TERM_CONVERSION_ID,C.TERM_CONTRACT_ID,C.ACCOUNT_ID,C.FROM_PRODUCT_VERSION_ID,C.TO_PRODUCT_VERSION_ID,C.EFFECTIVE_DATE,C.PRINCIPAL_BEFORE,C.PRINCIPAL_AFTER,C.ACCRUED_PROFIT_AMOUNT,C.ADJUSTMENT_AMOUNT,C.TRANSACTION_ID,C.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,A.APPROVER_USER_ID,C.STATUS_CODE,C.RECORD_VERSION FROM "+schema+".DEPOSIT_TERM_CONVERSION C LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=C.APPROVAL_REQUEST_ID WHERE C.ACCOUNT_ID=:id ORDER BY C.TERM_CONVERSION_ID DESC";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new TermConversion(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getLong(5),date(r,6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getBigDecimal(10),r.getObject(11,Long.class),r.getObject(12,Long.class),r.getString(13),r.getString(14),r.getString(15),r.getLong(16)));}
    public List<EarlyTermination> earlyTerminations(long accountId){String sql="SELECT E.EARLY_TERMINATION_ID,E.TERM_CONTRACT_ID,E.ACCOUNT_ID,E.TERMINATION_DATE,E.PRINCIPAL_AMOUNT,E.ACCRUED_PROFIT_AMOUNT,E.EARLY_TERMINATION_RATE,E.ADJUSTMENT_AMOUNT,E.TAX_AMOUNT,E.FEE_AMOUNT,E.NET_SETTLEMENT_AMOUNT,E.SETTLEMENT_TRANSACTION_ID,E.APPROVAL_REQUEST_ID,E.STATUS_CODE,E.RECORD_VERSION,(SELECT MAX(C.ACCOUNT_CLOSURE_ID) FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE C WHERE C.ACCOUNT_ID=E.ACCOUNT_ID AND C.CLOSURE_TYPE_CODE='EARLY_TERMINATION' AND C.REASON_CODE='TERM_EARLY_TERMINATION' AND C.APPROVAL_REQUEST_ID=E.APPROVAL_REQUEST_ID) CLOSURE_ID,(SELECT MAX(C.CLOSURE_STATUS_CODE) KEEP (DENSE_RANK LAST ORDER BY C.ACCOUNT_CLOSURE_ID) FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE C WHERE C.ACCOUNT_ID=E.ACCOUNT_ID AND C.CLOSURE_TYPE_CODE='EARLY_TERMINATION' AND C.REASON_CODE='TERM_EARLY_TERMINATION' AND C.APPROVAL_REQUEST_ID=E.APPROVAL_REQUEST_ID) CLOSURE_STATUS FROM "+schema+".DEPOSIT_TERM_EARLY_TERMINATION E WHERE E.ACCOUNT_ID=:id ORDER BY E.EARLY_TERMINATION_ID DESC";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new EarlyTermination(r.getLong(1),r.getLong(2),r.getLong(3),date(r,4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getBigDecimal(10),r.getBigDecimal(11),r.getObject(12,Long.class),r.getObject(13,Long.class),r.getString(14),r.getLong(15),r.getObject(16,Long.class),r.getString(17)));}
    public List<TermSettlement> settlements(long accountId){String sql="SELECT S.TERM_SETTLEMENT_ID,S.TERM_CONTRACT_ID,S.SETTLEMENT_TYPE_CODE,S.GROSS_PRINCIPAL,S.GROSS_PROFIT,S.TAX_AMOUNT,S.FEE_AMOUNT,S.ADJUSTMENT_AMOUNT,S.NET_AMOUNT,S.DESTINATION_ACCOUNT_REFERENCE,S.TRANSACTION_ID,S.STATUS_CODE FROM "+schema+".DEPOSIT_TERM_SETTLEMENT S JOIN "+schema+".DEPOSIT_TERM_CONTRACT T ON T.TERM_CONTRACT_ID=S.TERM_CONTRACT_ID WHERE T.ACCOUNT_ID=:id ORDER BY S.TERM_SETTLEMENT_ID DESC";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new TermSettlement(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getString(10),r.getObject(11,Long.class),r.getString(12)));}

    public Optional<IdempotencyRow> findIdempotency(String key){String sql="SELECT ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,new MapSqlParameterSource("k",key),(r,n)->new IdempotencyRow(r.getObject(1)==null?null:r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5))).stream().findFirst();}
    public void insertIdempotency(String key,long accountId,String operation,String hash,String actor,String correlation){jdbc.update("INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','TERM_DEPOSIT',:key,:corr,1)",new MapSqlParameterSource().addValue("id",nextIdem()).addValue("key",key).addValue("aid",accountId).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation));}
    public void completeIdempotency(String key,String ref){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("key",key).addValue("ref",ref));}

    private int statusUpdate(String table,String pk,long id,String from,String to,String actor){return jdbc.update("UPDATE "+schema+"."+table+" SET STATUS_CODE=:to,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE "+pk+"=:id AND STATUS_CODE=:from",new MapSqlParameterSource().addValue("to",to).addValue("actor",actor).addValue("id",id).addValue("from",from));}
    private static LocalDate date(java.sql.ResultSet r,int i)throws java.sql.SQLException{java.sql.Date d=r.getDate(i);return d==null?null:d.toLocalDate();}
    private static OffsetDateTime odt(Timestamp t){return t==null?null:t.toLocalDateTime().atOffset(ZoneOffset.UTC);}
    private static String id(String raw){String n=raw==null?"":raw.trim().toUpperCase(Locale.ROOT);if(!n.matches("[A-Z][A-Z0-9_$#]{0,127}"))throw new IllegalArgumentException("Invalid Oracle identifier: "+raw);return n;}
}
