-- CAL2 schema bootstrap for the BIAN-aligned 400-year calendar model.
-- Run once as SYSTEM/SYS or another account with CREATE USER privilege.
-- SQL*Plus / SQLcl:
--   @00-create-cal2-schema.sql

SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

ACCEPT CAL2_PASSWORD CHAR PROMPT 'Password for CAL2 user: ' HIDE

CREATE USER CAL2 IDENTIFIED BY "&CAL2_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO CAL2;

PROMPT CAL2 schema is ready.
