-- CAL2 physical model derived from BIAN_Calendar_400Y_Oracle_Import package.
-- Run while connected as CAL2 (recommended) or as a privileged account.

WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF

CREATE TABLE CAL2.CALENDAR_SYSTEM (
    CALENDAR_SYSTEM_ID NUMBER(19) NOT NULL,
    CALENDAR_CODE      VARCHAR2(30 CHAR) NOT NULL,
    NAME_FA            VARCHAR2(100 CHAR) NOT NULL,
    NAME_EN            VARCHAR2(120 CHAR),
    CALENDAR_TYPE      VARCHAR2(20 CHAR) NOT NULL,
    ACTIVE_FLAG        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CAL2_CALENDAR_SYSTEM PRIMARY KEY (CALENDAR_SYSTEM_ID),
    CONSTRAINT UQ_CAL2_CAL_SYSTEM_CODE UNIQUE (CALENDAR_CODE),
    CONSTRAINT CK_CAL2_CAL_SYSTEM_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CAL2.SOURCE_AUTHORITY (
    SOURCE_ID        NUMBER(19) NOT NULL,
    SOURCE_CODE      VARCHAR2(60 CHAR) NOT NULL,
    NAME_FA          VARCHAR2(200 CHAR) NOT NULL,
    NAME_EN          VARCHAR2(250 CHAR),
    SOURCE_TYPE      VARCHAR2(30 CHAR),
    SOURCE_URI       VARCHAR2(1000 CHAR),
    COUNTRY_CODE     VARCHAR2(3 CHAR),
    AUTHORITY_LEVEL  VARCHAR2(30 CHAR),
    ACTIVE_FLAG      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_SOURCE_AUTHORITY PRIMARY KEY (SOURCE_ID),
    CONSTRAINT UQ_CAL2_SOURCE_AUTH_CODE UNIQUE (SOURCE_CODE),
    CONSTRAINT CK_CAL2_SOURCE_AUTH_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CAL2.DATASET_VERSION (
    DATASET_VERSION_ID NUMBER(19) NOT NULL,
    VERSION_CODE       VARCHAR2(80 CHAR) NOT NULL,
    GENERATOR_VERSION  VARCHAR2(100 CHAR),
    ALGORITHM_VERSION  VARCHAR2(150 CHAR),
    SOURCE_VERSION     VARCHAR2(150 CHAR),
    RANGE_START_DATE   DATE NOT NULL,
    RANGE_END_DATE     DATE NOT NULL,
    STATUS             VARCHAR2(30 CHAR) NOT NULL,
    CHECKSUM_SHA256    VARCHAR2(64 CHAR),
    GENERATED_AT       TIMESTAMP(6),
    APPROVED_BY        VARCHAR2(120 CHAR),
    APPROVED_AT        TIMESTAMP(6),
    CONSTRAINT PK_CAL2_DATASET_VERSION PRIMARY KEY (DATASET_VERSION_ID),
    CONSTRAINT UQ_CAL2_DATASET_VERSION_CODE UNIQUE (VERSION_CODE),
    CONSTRAINT CK_CAL2_DATASET_RANGE CHECK (RANGE_END_DATE >= RANGE_START_DATE)
);

CREATE TABLE CAL2.CALENDAR_VARIANT (
    CALENDAR_VARIANT_ID NUMBER(19) NOT NULL,
    CALENDAR_SYSTEM_ID  NUMBER(19) NOT NULL,
    VARIANT_CODE        VARCHAR2(80 CHAR) NOT NULL,
    METHOD_TYPE         VARCHAR2(30 CHAR) NOT NULL,
    ALGORITHM_CODE      VARCHAR2(100 CHAR),
    AUTHORITY_ID        NUMBER(19),
    VALID_FROM          DATE,
    VALID_TO            DATE,
    IS_DEFAULT          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    VERSION_NO          NUMBER(10) DEFAULT 1 NOT NULL,
    ACTIVE_FLAG         CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_CALENDAR_VARIANT PRIMARY KEY (CALENDAR_VARIANT_ID),
    CONSTRAINT UQ_CAL2_CAL_VARIANT_CODE UNIQUE (VARIANT_CODE),
    CONSTRAINT FK_CAL2_CV_SYSTEM FOREIGN KEY (CALENDAR_SYSTEM_ID) REFERENCES CAL2.CALENDAR_SYSTEM (CALENDAR_SYSTEM_ID),
    CONSTRAINT FK_CAL2_CV_AUTHORITY FOREIGN KEY (AUTHORITY_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
    CONSTRAINT CK_CAL2_CV_DEFAULT CHECK (IS_DEFAULT IN ('Y','N')),
    CONSTRAINT CK_CAL2_CV_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_CV_RANGE CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM)
);

CREATE TABLE CAL2.CALENDAR_MONTH (
    CALENDAR_MONTH_ID  NUMBER(19) NOT NULL,
    CALENDAR_SYSTEM_ID NUMBER(19) NOT NULL,
    MONTH_NO           NUMBER(2) NOT NULL,
    NAME_FA            VARCHAR2(100 CHAR) NOT NULL,
    NAME_EN            VARCHAR2(100 CHAR),
    SHORT_NAME_FA      VARCHAR2(30 CHAR),
    SHORT_NAME_EN      VARCHAR2(30 CHAR),
    DISPLAY_ORDER      NUMBER(3),
    CONSTRAINT PK_CAL2_CALENDAR_MONTH PRIMARY KEY (CALENDAR_MONTH_ID),
    CONSTRAINT UQ_CAL2_CAL_MONTH_NO UNIQUE (CALENDAR_SYSTEM_ID, MONTH_NO),
    CONSTRAINT FK_CAL2_CM_SYSTEM FOREIGN KEY (CALENDAR_SYSTEM_ID) REFERENCES CAL2.CALENDAR_SYSTEM (CALENDAR_SYSTEM_ID),
    CONSTRAINT CK_CAL2_CM_MONTH_NO CHECK (MONTH_NO BETWEEN 1 AND 13)
);

CREATE TABLE CAL2.WEEKDAY (
    WEEKDAY_ID        NUMBER(19) NOT NULL,
    ISO_WEEKDAY_NO    NUMBER(1) NOT NULL,
    NAME_FA           VARCHAR2(50 CHAR) NOT NULL,
    NAME_EN           VARCHAR2(50 CHAR),
    SHORT_NAME_FA     VARCHAR2(20 CHAR),
    SHORT_NAME_EN     VARCHAR2(20 CHAR),
    IR_DISPLAY_ORDER  NUMBER(1),
    CONSTRAINT PK_CAL2_WEEKDAY PRIMARY KEY (WEEKDAY_ID),
    CONSTRAINT UQ_CAL2_WEEKDAY_ISO UNIQUE (ISO_WEEKDAY_NO),
    CONSTRAINT CK_CAL2_WEEKDAY_ISO CHECK (ISO_WEEKDAY_NO BETWEEN 1 AND 7),
    CONSTRAINT CK_CAL2_WEEKDAY_IR_ORDER CHECK (IR_DISPLAY_ORDER IS NULL OR IR_DISPLAY_ORDER BETWEEN 1 AND 7)
);

CREATE TABLE CAL2.CANONICAL_DAY (
    DAY_ID          NUMBER(19) NOT NULL,
    EPOCH_DAY       NUMBER(19) NOT NULL,
    CANONICAL_DATE  DATE NOT NULL,
    ISO_DATE_TEXT   VARCHAR2(10 CHAR) NOT NULL,
    WEEKDAY_ID      NUMBER(19) NOT NULL,
    ISO_WEEK_NO     NUMBER(2),
    ISO_WEEK_YEAR   NUMBER(6),
    CREATED_AT      TIMESTAMP(6),
    CONSTRAINT PK_CAL2_CANONICAL_DAY PRIMARY KEY (DAY_ID),
    CONSTRAINT UQ_CAL2_CAN_DAY_EPOCH UNIQUE (EPOCH_DAY),
    CONSTRAINT UQ_CAL2_CAN_DAY_DATE UNIQUE (CANONICAL_DATE),
    CONSTRAINT UQ_CAL2_CAN_DAY_ISO_TEXT UNIQUE (ISO_DATE_TEXT),
    CONSTRAINT FK_CAL2_CAN_DAY_WEEKDAY FOREIGN KEY (WEEKDAY_ID) REFERENCES CAL2.WEEKDAY (WEEKDAY_ID),
    CONSTRAINT CK_CAL2_CAN_DAY_WEEK CHECK (ISO_WEEK_NO IS NULL OR ISO_WEEK_NO BETWEEN 1 AND 53)
);

CREATE TABLE CAL2.CALENDAR_DATE (
    CALENDAR_DATE_ID    NUMBER(19) NOT NULL,
    DAY_ID              NUMBER(19) NOT NULL,
    CALENDAR_VARIANT_ID NUMBER(19) NOT NULL,
    YEAR_NO             NUMBER(6) NOT NULL,
    MONTH_NO            NUMBER(2) NOT NULL,
    DAY_NO              NUMBER(2) NOT NULL,
    DAY_OF_YEAR         NUMBER(3),
    WEEKDAY_ID          NUMBER(19) NOT NULL,
    IS_LEAP_YEAR        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_LEAP_MONTH       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    MONTH_LENGTH        NUMBER(2),
    DATA_STATUS         VARCHAR2(30 CHAR) NOT NULL,
    DATASET_VERSION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT PK_CAL2_CALENDAR_DATE PRIMARY KEY (CALENDAR_DATE_ID),
    CONSTRAINT UQ_CAL2_CAL_DATE_DAY_VARIANT UNIQUE (DAY_ID, CALENDAR_VARIANT_ID),
    CONSTRAINT UQ_CAL2_CAL_DATE_YMD UNIQUE (CALENDAR_VARIANT_ID, YEAR_NO, MONTH_NO, DAY_NO),
    CONSTRAINT FK_CAL2_CD_DAY FOREIGN KEY (DAY_ID) REFERENCES CAL2.CANONICAL_DAY (DAY_ID),
    CONSTRAINT FK_CAL2_CD_VARIANT FOREIGN KEY (CALENDAR_VARIANT_ID) REFERENCES CAL2.CALENDAR_VARIANT (CALENDAR_VARIANT_ID),
    CONSTRAINT FK_CAL2_CD_WEEKDAY FOREIGN KEY (WEEKDAY_ID) REFERENCES CAL2.WEEKDAY (WEEKDAY_ID),
    CONSTRAINT FK_CAL2_CD_DATASET FOREIGN KEY (DATASET_VERSION_ID) REFERENCES CAL2.DATASET_VERSION (DATASET_VERSION_ID),
    CONSTRAINT CK_CAL2_CD_LEAP_YEAR CHECK (IS_LEAP_YEAR IN ('Y','N')),
    CONSTRAINT CK_CAL2_CD_LEAP_MONTH CHECK (IS_LEAP_MONTH IN ('Y','N')),
    CONSTRAINT CK_CAL2_CD_MONTH CHECK (MONTH_NO BETWEEN 1 AND 13),
    CONSTRAINT CK_CAL2_CD_DAY CHECK (DAY_NO BETWEEN 1 AND 31)
);

CREATE TABLE CAL2.EVENT_TYPE (
    EVENT_TYPE_ID    NUMBER(19) NOT NULL,
    EVENT_TYPE_CODE  VARCHAR2(60 CHAR) NOT NULL,
    NAME_FA          VARCHAR2(120 CHAR) NOT NULL,
    NAME_EN          VARCHAR2(120 CHAR),
    ACTIVE_FLAG      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_EVENT_TYPE PRIMARY KEY (EVENT_TYPE_ID),
    CONSTRAINT UQ_CAL2_EVENT_TYPE_CODE UNIQUE (EVENT_TYPE_CODE),
    CONSTRAINT CK_CAL2_EVENT_TYPE_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CAL2.EVENT (
    EVENT_ID                 NUMBER(19) NOT NULL,
    EVENT_CODE               VARCHAR2(80 CHAR) NOT NULL,
    EVENT_TYPE_ID            NUMBER(19) NOT NULL,
    NAME_FA                  VARCHAR2(300 CHAR) NOT NULL,
    NAME_EN                  VARCHAR2(300 CHAR),
    DESCRIPTION              VARCHAR2(2000 CHAR),
    RECURRENCE_TYPE          VARCHAR2(40 CHAR),
    BASE_CALENDAR_SYSTEM_ID  NUMBER(19),
    OFFICIAL_FLAG            CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    DEFAULT_HOLIDAY_FLAG     CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    ACTIVE_FLAG              CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT UQ_CAL2_EVENT_CODE UNIQUE (EVENT_CODE),
    CONSTRAINT FK_CAL2_EVENT_TYPE FOREIGN KEY (EVENT_TYPE_ID) REFERENCES CAL2.EVENT_TYPE (EVENT_TYPE_ID),
    CONSTRAINT FK_CAL2_EVENT_SYSTEM FOREIGN KEY (BASE_CALENDAR_SYSTEM_ID) REFERENCES CAL2.CALENDAR_SYSTEM (CALENDAR_SYSTEM_ID),
    CONSTRAINT CK_CAL2_EVENT_OFFICIAL CHECK (OFFICIAL_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_EVENT_DEF_HOL CHECK (DEFAULT_HOLIDAY_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_EVENT_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CAL2.EVENT_RECURRENCE_RULE (
    EVENT_RULE_ID        NUMBER(19) NOT NULL,
    EVENT_ID             NUMBER(19) NOT NULL,
    RULE_TYPE            VARCHAR2(40 CHAR) NOT NULL,
    CALENDAR_VARIANT_ID  NUMBER(19) NOT NULL,
    YEAR_NO              NUMBER(6),
    MONTH_NO             NUMBER(2) NOT NULL,
    DAY_NO               NUMBER(2) NOT NULL,
    START_YEAR_NO        NUMBER(6),
    END_YEAR_NO          NUMBER(6),
    SOURCE_ID            NUMBER(19),
    DESCRIPTION          VARCHAR2(1000 CHAR),
    ACTIVE_FLAG          CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_EVENT_RULE PRIMARY KEY (EVENT_RULE_ID),
    CONSTRAINT FK_CAL2_ER_EVENT FOREIGN KEY (EVENT_ID) REFERENCES CAL2.EVENT (EVENT_ID),
    CONSTRAINT FK_CAL2_ER_VARIANT FOREIGN KEY (CALENDAR_VARIANT_ID) REFERENCES CAL2.CALENDAR_VARIANT (CALENDAR_VARIANT_ID),
    CONSTRAINT FK_CAL2_ER_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
    CONSTRAINT CK_CAL2_ER_TYPE CHECK (RULE_TYPE IN ('ANNUAL_FIXED_DATE','ONE_TIME_DATE')),
    CONSTRAINT CK_CAL2_ER_MONTH CHECK (MONTH_NO BETWEEN 1 AND 13),
    CONSTRAINT CK_CAL2_ER_DAY CHECK (DAY_NO BETWEEN 1 AND 31),
    CONSTRAINT CK_CAL2_ER_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_ER_RANGE CHECK (END_YEAR_NO IS NULL OR START_YEAR_NO IS NULL OR END_YEAR_NO >= START_YEAR_NO),
    CONSTRAINT CK_CAL2_ER_SHAPE CHECK (
        (RULE_TYPE = 'ANNUAL_FIXED_DATE' AND YEAR_NO IS NULL)
        OR
        (RULE_TYPE = 'ONE_TIME_DATE' AND YEAR_NO IS NOT NULL AND START_YEAR_NO IS NULL AND END_YEAR_NO IS NULL)
    )
);

CREATE TABLE CAL2.EVENT_OCCURRENCE (
    EVENT_OCCURRENCE_ID NUMBER(19) NOT NULL,
    EVENT_ID            NUMBER(19) NOT NULL,
    EVENT_RULE_ID       NUMBER(19),
    DAY_ID              NUMBER(19) NOT NULL,
    SOURCE_ID           NUMBER(19),
    OCCURRENCE_SOURCE   VARCHAR2(30 CHAR) DEFAULT 'MANUAL' NOT NULL,
    DATA_STATUS         VARCHAR2(30 CHAR),
    HOLIDAY_FLAG        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    START_TIME          TIMESTAMP(6),
    END_TIME            TIMESTAMP(6),
    DESCRIPTION         VARCHAR2(2000 CHAR),
    DATASET_VERSION_ID  NUMBER(19),
    CONSTRAINT PK_CAL2_EVENT_OCC PRIMARY KEY (EVENT_OCCURRENCE_ID),
    CONSTRAINT FK_CAL2_EO_EVENT FOREIGN KEY (EVENT_ID) REFERENCES CAL2.EVENT (EVENT_ID),
    CONSTRAINT FK_CAL2_EO_RULE FOREIGN KEY (EVENT_RULE_ID) REFERENCES CAL2.EVENT_RECURRENCE_RULE (EVENT_RULE_ID),
    CONSTRAINT FK_CAL2_EO_DAY FOREIGN KEY (DAY_ID) REFERENCES CAL2.CANONICAL_DAY (DAY_ID),
    CONSTRAINT FK_CAL2_EO_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
    CONSTRAINT FK_CAL2_EO_DATASET FOREIGN KEY (DATASET_VERSION_ID) REFERENCES CAL2.DATASET_VERSION (DATASET_VERSION_ID),
    CONSTRAINT CK_CAL2_EO_SOURCE CHECK (OCCURRENCE_SOURCE IN ('GENERATED','MANUAL','OFFICIAL')),
    CONSTRAINT CK_CAL2_EO_HOLIDAY CHECK (HOLIDAY_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_EO_TIME_RANGE CHECK (END_TIME IS NULL OR START_TIME IS NULL OR END_TIME >= START_TIME)
);

CREATE TABLE CAL2.BUSINESS_CALENDAR (
    BUSINESS_CALENDAR_ID NUMBER(19) NOT NULL,
    CALENDAR_CODE        VARCHAR2(80 CHAR) NOT NULL,
    NAME_FA              VARCHAR2(200 CHAR) NOT NULL,
    NAME_EN              VARCHAR2(200 CHAR),
    COUNTRY_CODE         VARCHAR2(3 CHAR),
    TIME_ZONE            VARCHAR2(80 CHAR),
    ORGANIZATION_ID      VARCHAR2(80 CHAR),
    VALID_FROM           DATE,
    VALID_TO             DATE,
    ACTIVE_FLAG          CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CAL2_BUSINESS_CAL PRIMARY KEY (BUSINESS_CALENDAR_ID),
    CONSTRAINT UQ_CAL2_BUSINESS_CAL_CODE UNIQUE (CALENDAR_CODE),
    CONSTRAINT CK_CAL2_BUS_CAL_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT CK_CAL2_BUS_CAL_RANGE CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM)
);

CREATE TABLE CAL2.BUSINESS_CALENDAR_DAY (
    BUSINESS_CALENDAR_DAY_ID NUMBER(19) NOT NULL,
    BUSINESS_CALENDAR_ID     NUMBER(19) NOT NULL,
    DAY_ID                   NUMBER(19) NOT NULL,
    DAY_STATUS               VARCHAR2(30 CHAR),
    OPEN_TIME                TIMESTAMP(6),
    CLOSE_TIME               TIMESTAMP(6),
    IS_BUSINESS_DAY          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_SETTLEMENT_DAY        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_CLEARING_DAY          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_PROCESSING_DAY        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    REASON_CODE              VARCHAR2(80 CHAR),
    SOURCE_ID                NUMBER(19),
    CONSTRAINT PK_CAL2_BUS_CAL_DAY PRIMARY KEY (BUSINESS_CALENDAR_DAY_ID),
    CONSTRAINT UQ_CAL2_BUS_CAL_DAY UNIQUE (BUSINESS_CALENDAR_ID, DAY_ID),
    CONSTRAINT FK_CAL2_BCD_CAL FOREIGN KEY (BUSINESS_CALENDAR_ID) REFERENCES CAL2.BUSINESS_CALENDAR (BUSINESS_CALENDAR_ID),
    CONSTRAINT FK_CAL2_BCD_DAY FOREIGN KEY (DAY_ID) REFERENCES CAL2.CANONICAL_DAY (DAY_ID),
    CONSTRAINT FK_CAL2_BCD_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
    CONSTRAINT CK_CAL2_BCD_BUSINESS CHECK (IS_BUSINESS_DAY IN ('Y','N')),
    CONSTRAINT CK_CAL2_BCD_SETTLEMENT CHECK (IS_SETTLEMENT_DAY IN ('Y','N')),
    CONSTRAINT CK_CAL2_BCD_CLEARING CHECK (IS_CLEARING_DAY IN ('Y','N')),
    CONSTRAINT CK_CAL2_BCD_PROCESSING CHECK (IS_PROCESSING_DAY IN ('Y','N')),
    CONSTRAINT CK_CAL2_BCD_TIME_RANGE CHECK (CLOSE_TIME IS NULL OR OPEN_TIME IS NULL OR CLOSE_TIME >= OPEN_TIME)
);

CREATE TABLE CAL2.VALIDATION_RUN (
    VALIDATION_RUN_ID    NUMBER(19) NOT NULL,
    DATASET_VERSION_ID   NUMBER(19) NOT NULL,
    RUN_STARTED_AT       TIMESTAMP(6),
    RUN_FINISHED_AT      TIMESTAMP(6),
    VALIDATOR_NAME       VARCHAR2(250 CHAR),
    VALIDATOR_VERSION    VARCHAR2(80 CHAR),
    TOTAL_ASSERTIONS     NUMBER(19),
    PASSED_ASSERTIONS    NUMBER(19),
    FAILED_ASSERTIONS    NUMBER(19),
    RUN_STATUS           VARCHAR2(30 CHAR),
    EVIDENCE_CHECKSUM    VARCHAR2(64 CHAR),
    CONSTRAINT PK_CAL2_VALIDATION_RUN PRIMARY KEY (VALIDATION_RUN_ID),
    CONSTRAINT FK_CAL2_VR_DATASET FOREIGN KEY (DATASET_VERSION_ID) REFERENCES CAL2.DATASET_VERSION (DATASET_VERSION_ID),
    CONSTRAINT CK_CAL2_VR_TIME_RANGE CHECK (RUN_FINISHED_AT IS NULL OR RUN_STARTED_AT IS NULL OR RUN_FINISHED_AT >= RUN_STARTED_AT)
);

CREATE TABLE CAL2.VALIDATION_RESULT (
    VALIDATION_RESULT_ID NUMBER(19) NOT NULL,
    VALIDATION_RUN_ID    NUMBER(19) NOT NULL,
    TEST_CODE            VARCHAR2(120 CHAR) NOT NULL,
    DAY_ID               NUMBER(19),
    CALENDAR_VARIANT_ID  NUMBER(19),
    RESULT_STATUS        VARCHAR2(30 CHAR) NOT NULL,
    EXPECTED_VALUE       VARCHAR2(1000 CHAR),
    ACTUAL_VALUE         VARCHAR2(1000 CHAR),
    ERROR_CODE           VARCHAR2(120 CHAR),
    DETAILS              VARCHAR2(2000 CHAR),
    CONSTRAINT PK_CAL2_VALIDATION_RESULT PRIMARY KEY (VALIDATION_RESULT_ID),
    CONSTRAINT FK_CAL2_VRES_RUN FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES CAL2.VALIDATION_RUN (VALIDATION_RUN_ID),
    CONSTRAINT FK_CAL2_VRES_DAY FOREIGN KEY (DAY_ID) REFERENCES CAL2.CANONICAL_DAY (DAY_ID),
    CONSTRAINT FK_CAL2_VRES_VARIANT FOREIGN KEY (CALENDAR_VARIANT_ID) REFERENCES CAL2.CALENDAR_VARIANT (CALENDAR_VARIANT_ID)
);

CREATE INDEX CAL2.IX_CAL2_CV_SYSTEM ON CAL2.CALENDAR_VARIANT (CALENDAR_SYSTEM_ID);
CREATE INDEX CAL2.IX_CAL2_CV_AUTH ON CAL2.CALENDAR_VARIANT (AUTHORITY_ID);
CREATE INDEX CAL2.IX_CAL2_CM_SYSTEM ON CAL2.CALENDAR_MONTH (CALENDAR_SYSTEM_ID);
CREATE INDEX CAL2.IX_CAL2_CAN_DAY_WEEKDAY ON CAL2.CANONICAL_DAY (WEEKDAY_ID);
CREATE INDEX CAL2.IX_CAL2_CD_DAY ON CAL2.CALENDAR_DATE (DAY_ID);
CREATE INDEX CAL2.IX_CAL2_CD_VARIANT ON CAL2.CALENDAR_DATE (CALENDAR_VARIANT_ID);
CREATE INDEX CAL2.IX_CAL2_CD_DATASET ON CAL2.CALENDAR_DATE (DATASET_VERSION_ID);
CREATE INDEX CAL2.IX_CAL2_CD_WEEKDAY ON CAL2.CALENDAR_DATE (WEEKDAY_ID);
CREATE INDEX CAL2.IX_CAL2_EVENT_TYPE ON CAL2.EVENT (EVENT_TYPE_ID);
CREATE INDEX CAL2.IX_CAL2_ER_EVENT ON CAL2.EVENT_RECURRENCE_RULE (EVENT_ID);
CREATE INDEX CAL2.IX_CAL2_ER_VARIANT ON CAL2.EVENT_RECURRENCE_RULE (CALENDAR_VARIANT_ID);
CREATE INDEX CAL2.IX_CAL2_EO_EVENT ON CAL2.EVENT_OCCURRENCE (EVENT_ID);
CREATE INDEX CAL2.IX_CAL2_EO_RULE ON CAL2.EVENT_OCCURRENCE (EVENT_RULE_ID);
CREATE INDEX CAL2.IX_CAL2_EO_DAY ON CAL2.EVENT_OCCURRENCE (DAY_ID);
CREATE INDEX CAL2.IX_CAL2_BCD_CAL ON CAL2.BUSINESS_CALENDAR_DAY (BUSINESS_CALENDAR_ID);
CREATE INDEX CAL2.IX_CAL2_BCD_DAY ON CAL2.BUSINESS_CALENDAR_DAY (DAY_ID);
CREATE INDEX CAL2.IX_CAL2_VR_DATASET ON CAL2.VALIDATION_RUN (DATASET_VERSION_ID);
CREATE INDEX CAL2.IX_CAL2_VRES_RUN ON CAL2.VALIDATION_RESULT (VALIDATION_RUN_ID);

COMMENT ON TABLE CAL2.CALENDAR_SYSTEM IS 'تعریف سیستم‌های تقویمی مدل CAL2';
COMMENT ON TABLE CAL2.SOURCE_AUTHORITY IS 'مرجع یا منبع تولید/اعلام داده تقویم';
COMMENT ON TABLE CAL2.DATASET_VERSION IS 'نسخه و شناسنامه Dataset تقویم';
COMMENT ON TABLE CAL2.CALENDAR_VARIANT IS 'گونه محاسباتی/رسمی هر سیستم تقویم';
COMMENT ON TABLE CAL2.CALENDAR_MONTH IS 'نام و ترتیب ماه‌ها برای هر سیستم تقویم';
COMMENT ON TABLE CAL2.WEEKDAY IS 'تعریف روزهای هفته';
COMMENT ON TABLE CAL2.CANONICAL_DAY IS 'محور روز Canonical مستقل از نمایش تقویمی';
COMMENT ON TABLE CAL2.CALENDAR_DATE IS 'نگاشت هر روز Canonical به یک Calendar Variant';
COMMENT ON TABLE CAL2.EVENT_TYPE IS 'نوع مناسبت یا رویداد';
COMMENT ON TABLE CAL2.EVENT IS 'تعریف پایدار رویداد/مناسبت';
COMMENT ON TABLE CAL2.EVENT_RECURRENCE_RULE IS 'قاعده تکرار یک مناسبت بر مبنای Calendar Variant';
COMMENT ON TABLE CAL2.EVENT_OCCURRENCE IS 'رخداد واقعی یک رویداد روی روز Canonical';
COMMENT ON TABLE CAL2.BUSINESS_CALENDAR IS 'تعریف تقویم کاری/بانکی';
COMMENT ON TABLE CAL2.BUSINESS_CALENDAR_DAY IS 'وضعیت عملیاتی هر روز در یک تقویم کاری';
COMMENT ON TABLE CAL2.VALIDATION_RUN IS 'اجرای فرآیند اعتبارسنجی Dataset';
COMMENT ON TABLE CAL2.VALIDATION_RESULT IS 'نتیجه تفصیلی/تجمیعی اعتبارسنجی Dataset';

-- Persian column metadata for EA/Oracle comparison and administrative forms.
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.CALENDAR_SYSTEM_ID IS 'شناسه سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.CALENDAR_CODE IS 'کد یکتای سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.NAME_FA IS 'نام فارسی سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.NAME_EN IS 'نام انگلیسی سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.CALENDAR_TYPE IS 'نوع تقویم مانند خورشیدی یا قمری';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.CALENDAR_SYSTEM.CREATED_AT IS 'زمان ایجاد رکورد';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.SOURCE_ID IS 'شناسه منبع یا مرجع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.SOURCE_CODE IS 'کد یکتای منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.NAME_FA IS 'نام فارسی منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.NAME_EN IS 'نام انگلیسی منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.SOURCE_TYPE IS 'نوع منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.SOURCE_URI IS 'نشانی مرجع یا سند منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.COUNTRY_CODE IS 'کد کشور منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.AUTHORITY_LEVEL IS 'سطح اعتبار یا رسمیت منبع';
COMMENT ON COLUMN CAL2.SOURCE_AUTHORITY.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.DATASET_VERSION.DATASET_VERSION_ID IS 'شناسه نسخه Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.VERSION_CODE IS 'کد یکتای نسخه Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.GENERATOR_VERSION IS 'نسخه ابزار مولد';
COMMENT ON COLUMN CAL2.DATASET_VERSION.ALGORITHM_VERSION IS 'نسخه الگوریتم تولید';
COMMENT ON COLUMN CAL2.DATASET_VERSION.SOURCE_VERSION IS 'نسخه منبع یا موتور';
COMMENT ON COLUMN CAL2.DATASET_VERSION.RANGE_START_DATE IS 'تاریخ شروع بازه Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.RANGE_END_DATE IS 'تاریخ پایان بازه Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.STATUS IS 'وضعیت نسخه Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.CHECKSUM_SHA256 IS 'Checksum نوع SHA-256';
COMMENT ON COLUMN CAL2.DATASET_VERSION.GENERATED_AT IS 'زمان تولید Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.APPROVED_BY IS 'تأییدکننده Dataset';
COMMENT ON COLUMN CAL2.DATASET_VERSION.APPROVED_AT IS 'زمان تأیید Dataset';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.CALENDAR_VARIANT_ID IS 'شناسه Variant تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.CALENDAR_SYSTEM_ID IS 'شناسه سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.VARIANT_CODE IS 'کد یکتای Variant';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.METHOD_TYPE IS 'روش تولید یا تعیین تاریخ';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.ALGORITHM_CODE IS 'کد الگوریتم';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.AUTHORITY_ID IS 'شناسه مرجع داده';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.VALID_FROM IS 'شروع دوره اعتبار';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.VALID_TO IS 'پایان دوره اعتبار';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.IS_DEFAULT IS 'نشانگر Variant پیش‌فرض';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.VERSION_NO IS 'شماره نسخه Variant';
COMMENT ON COLUMN CAL2.CALENDAR_VARIANT.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.CALENDAR_MONTH_ID IS 'شناسه ماه تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.CALENDAR_SYSTEM_ID IS 'شناسه سیستم تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.MONTH_NO IS 'شماره ماه';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.NAME_FA IS 'نام فارسی ماه';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.NAME_EN IS 'نام انگلیسی ماه';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.SHORT_NAME_FA IS 'نام کوتاه فارسی ماه';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.SHORT_NAME_EN IS 'نام کوتاه انگلیسی ماه';
COMMENT ON COLUMN CAL2.CALENDAR_MONTH.DISPLAY_ORDER IS 'ترتیب نمایش';
COMMENT ON COLUMN CAL2.WEEKDAY.WEEKDAY_ID IS 'شناسه روز هفته';
COMMENT ON COLUMN CAL2.WEEKDAY.ISO_WEEKDAY_NO IS 'شماره روز هفته مطابق ISO';
COMMENT ON COLUMN CAL2.WEEKDAY.NAME_FA IS 'نام فارسی روز هفته';
COMMENT ON COLUMN CAL2.WEEKDAY.NAME_EN IS 'نام انگلیسی روز هفته';
COMMENT ON COLUMN CAL2.WEEKDAY.SHORT_NAME_FA IS 'نام کوتاه فارسی روز هفته';
COMMENT ON COLUMN CAL2.WEEKDAY.SHORT_NAME_EN IS 'نام کوتاه انگلیسی روز هفته';
COMMENT ON COLUMN CAL2.WEEKDAY.IR_DISPLAY_ORDER IS 'ترتیب نمایش متعارف ایرانی';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.DAY_ID IS 'شناسه یکتای روز Canonical';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.EPOCH_DAY IS 'شماره روز نسبت به Epoch';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.CANONICAL_DATE IS 'تاریخ میلادی Canonical';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.ISO_DATE_TEXT IS 'نمایش متنی ISO تاریخ';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.WEEKDAY_ID IS 'شناسه روز هفته';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.ISO_WEEK_NO IS 'شماره هفته ISO';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.ISO_WEEK_YEAR IS 'سال هفته ISO';
COMMENT ON COLUMN CAL2.CANONICAL_DAY.CREATED_AT IS 'زمان تولید رکورد';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.CALENDAR_DATE_ID IS 'شناسه نگاشت تاریخ';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.DAY_ID IS 'شناسه روز Canonical';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.CALENDAR_VARIANT_ID IS 'شناسه Variant تقویم';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.YEAR_NO IS 'شماره سال';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.MONTH_NO IS 'شماره ماه';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.DAY_NO IS 'شماره روز ماه';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.DAY_OF_YEAR IS 'شماره روز در سال';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.WEEKDAY_ID IS 'شناسه روز هفته';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.IS_LEAP_YEAR IS 'نشانگر سال کبیسه';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.IS_LEAP_MONTH IS 'نشانگر ماه کبیسه';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.MONTH_LENGTH IS 'تعداد روزهای ماه';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.DATA_STATUS IS 'وضعیت محاسباتی یا رسمی داده';
COMMENT ON COLUMN CAL2.CALENDAR_DATE.DATASET_VERSION_ID IS 'شناسه نسخه Dataset';
COMMENT ON COLUMN CAL2.EVENT_TYPE.EVENT_TYPE_ID IS 'شناسه نوع رویداد';
COMMENT ON COLUMN CAL2.EVENT_TYPE.EVENT_TYPE_CODE IS 'کد یکتای نوع رویداد';
COMMENT ON COLUMN CAL2.EVENT_TYPE.NAME_FA IS 'عنوان فارسی نوع رویداد';
COMMENT ON COLUMN CAL2.EVENT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع رویداد';
COMMENT ON COLUMN CAL2.EVENT_TYPE.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.EVENT.EVENT_ID IS 'شناسه رویداد';
COMMENT ON COLUMN CAL2.EVENT.EVENT_CODE IS 'کد یکتای رویداد';
COMMENT ON COLUMN CAL2.EVENT.EVENT_TYPE_ID IS 'شناسه نوع رویداد';
COMMENT ON COLUMN CAL2.EVENT.NAME_FA IS 'عنوان فارسی رویداد';
COMMENT ON COLUMN CAL2.EVENT.NAME_EN IS 'عنوان انگلیسی رویداد';
COMMENT ON COLUMN CAL2.EVENT.DESCRIPTION IS 'توضیحات رویداد';
COMMENT ON COLUMN CAL2.EVENT.RECURRENCE_TYPE IS 'نوع تکرار رویداد';
COMMENT ON COLUMN CAL2.EVENT.BASE_CALENDAR_SYSTEM_ID IS 'سیستم تقویم مبنای رویداد';
COMMENT ON COLUMN CAL2.EVENT.OFFICIAL_FLAG IS 'نشانگر رسمی بودن';
COMMENT ON COLUMN CAL2.EVENT.DEFAULT_HOLIDAY_FLAG IS 'نشانگر تعطیل پیش‌فرض';
COMMENT ON COLUMN CAL2.EVENT.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.EVENT_RULE_ID IS 'شناسه قاعده تکرار';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.EVENT_ID IS 'شناسه رویداد/مناسبت';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.RULE_TYPE IS 'نوع قاعده تکرار';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.CALENDAR_VARIANT_ID IS 'گونه تقویم مبنای قاعده';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.YEAR_NO IS 'سال وقوع برای قاعده یک‌باره';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.MONTH_NO IS 'شماره ماه در Calendar Variant مبنا';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.DAY_NO IS 'شماره روز در ماه مبنا';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.START_YEAR_NO IS 'اولین سال اعمال قاعده سالانه';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.END_YEAR_NO IS 'آخرین سال اعمال قاعده سالانه';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.SOURCE_ID IS 'مرجع تعریف قاعده';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.DESCRIPTION IS 'توضیحات قاعده';
COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.ACTIVE_FLAG IS 'نشانگر فعال بودن قاعده';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.EVENT_OCCURRENCE_ID IS 'شناسه رخداد رویداد';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.EVENT_ID IS 'شناسه رویداد';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.EVENT_RULE_ID IS 'شناسه قاعده مولد رخداد؛ برای رخداد دستی می‌تواند NULL باشد';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.DAY_ID IS 'شناسه روز Canonical وقوع';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.SOURCE_ID IS 'شناسه منبع وقوع';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.OCCURRENCE_SOURCE IS 'منشأ رخداد: تولیدشده، دستی یا رسمی';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.DATA_STATUS IS 'وضعیت داده رخداد';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.HOLIDAY_FLAG IS 'نشانگر تعطیل بودن';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.START_TIME IS 'زمان شروع';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.END_TIME IS 'زمان پایان';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.DESCRIPTION IS 'توضیحات رخداد';
COMMENT ON COLUMN CAL2.EVENT_OCCURRENCE.DATASET_VERSION_ID IS 'شناسه نسخه Dataset';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.BUSINESS_CALENDAR_ID IS 'شناسه تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.CALENDAR_CODE IS 'کد یکتای تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.NAME_FA IS 'نام فارسی تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.NAME_EN IS 'نام انگلیسی تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.COUNTRY_CODE IS 'کد کشور';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.TIME_ZONE IS 'منطقه زمانی';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.ORGANIZATION_ID IS 'شناسه سازمان';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.VALID_FROM IS 'شروع اعتبار';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.VALID_TO IS 'پایان اعتبار';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR.ACTIVE_FLAG IS 'نشانگر فعال بودن';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.BUSINESS_CALENDAR_DAY_ID IS 'شناسه روز تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.BUSINESS_CALENDAR_ID IS 'شناسه تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.DAY_ID IS 'شناسه روز Canonical';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.DAY_STATUS IS 'وضعیت روز کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.OPEN_TIME IS 'زمان بازشدن';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.CLOSE_TIME IS 'زمان بسته‌شدن';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.IS_BUSINESS_DAY IS 'نشانگر روز کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.IS_SETTLEMENT_DAY IS 'نشانگر روز تسویه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.IS_CLEARING_DAY IS 'نشانگر روز پایاپای';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.IS_PROCESSING_DAY IS 'نشانگر روز پردازش';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.REASON_CODE IS 'کد دلیل وضعیت روز';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.SOURCE_ID IS 'شناسه منبع';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.VALIDATION_RUN_ID IS 'شناسه اجرای اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.DATASET_VERSION_ID IS 'شناسه نسخه Dataset';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.RUN_STARTED_AT IS 'زمان شروع اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.RUN_FINISHED_AT IS 'زمان پایان اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.VALIDATOR_NAME IS 'نام Validator';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.VALIDATOR_VERSION IS 'نسخه Validator';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.TOTAL_ASSERTIONS IS 'تعداد کل Assertionها';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.PASSED_ASSERTIONS IS 'تعداد Assertionهای موفق';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.FAILED_ASSERTIONS IS 'تعداد Assertionهای ناموفق';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.RUN_STATUS IS 'وضعیت اجرای اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RUN.EVIDENCE_CHECKSUM IS 'Checksum شواهد اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.VALIDATION_RESULT_ID IS 'شناسه نتیجه اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.VALIDATION_RUN_ID IS 'شناسه اجرای اعتبارسنجی';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.TEST_CODE IS 'کد آزمون';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.DAY_ID IS 'شناسه روز مرتبط در صورت وجود';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.CALENDAR_VARIANT_ID IS 'شناسه Variant مرتبط در صورت وجود';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.RESULT_STATUS IS 'وضعیت نتیجه آزمون';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.EXPECTED_VALUE IS 'مقدار مورد انتظار';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.ACTUAL_VALUE IS 'مقدار واقعی';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.ERROR_CODE IS 'کد خطا';
COMMENT ON COLUMN CAL2.VALIDATION_RESULT.DETAILS IS 'جزئیات نتیجه';

PROMPT 16 CAL2 tables, constraints and indexes created successfully.
