-- Read-only verification of the CAL2 physical model.
SET PAGESIZE 200
SET LINESIZE 220

SELECT OWNER, TABLE_NAME, NUM_ROWS
FROM ALL_TABLES
WHERE OWNER = 'CAL2'
ORDER BY TABLE_NAME;

SELECT COUNT(*) AS CAL2_TABLE_COUNT
FROM ALL_TABLES
WHERE OWNER = 'CAL2'
  AND TABLE_NAME IN (
    'CALENDAR_SYSTEM','SOURCE_AUTHORITY','DATASET_VERSION','CALENDAR_VARIANT','CALENDAR_MONTH','WEEKDAY',
    'CANONICAL_DAY','CALENDAR_DATE','EVENT_TYPE','EVENT','EVENT_RECURRENCE_RULE','EVENT_OCCURRENCE','BUSINESS_CALENDAR',
    'BUSINESS_CALENDAR_DAY','VALIDATION_RUN','VALIDATION_RESULT'
  );


SELECT TABLE_NAME, COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'CAL2'
  AND ((TABLE_NAME = 'EVENT_RECURRENCE_RULE')
       OR (TABLE_NAME = 'EVENT_OCCURRENCE' AND COLUMN_NAME IN ('EVENT_RULE_ID','OCCURRENCE_SOURCE')))
ORDER BY TABLE_NAME, COLUMN_ID;
