SET SERVEROUTPUT ON
PROMPT === FIX89 Rule 193 SQL-resolution diagnostic ===
SELECT R.EVENT_RULE_ID, E.EVENT_CODE, R.MONTH_NO, R.DAY_NO, R.DAY_RESOLUTION_POLICY
  FROM CAL2.EVENT_RECURRENCE_RULE R
  JOIN CAL2.EVENT E ON E.EVENT_ID = R.EVENT_ID
 WHERE R.EVENT_RULE_ID = 193;

PROMPT Expected RESOLVED_MATCH_COUNT = 413 for current 1826..2226 dataset.
SELECT COUNT(*) AS RESOLVED_MATCH_COUNT
  FROM CAL2.CALENDAR_DATE CD
 WHERE CD.CALENDAR_VARIANT_ID = 3
   AND CD.MONTH_NO = 2
   AND CD.DAY_NO = CASE
       WHEN 'LAST_DAY_IF_INVALID' = 'LAST_DAY_IF_INVALID' THEN (
           SELECT NVL(MAX(CASE WHEN RX.DAY_NO = 30 THEN RX.DAY_NO END), MAX(RX.DAY_NO))
             FROM CAL2.CALENDAR_DATE RX
            WHERE RX.CALENDAR_VARIANT_ID = CD.CALENDAR_VARIANT_ID
              AND RX.YEAR_NO = CD.YEAR_NO
              AND RX.MONTH_NO = CD.MONTH_NO
       )
       ELSE 30
   END;

PROMPT Current generated occurrences for Rule 193:
SELECT COUNT(*) AS GENERATED_OCCURRENCES
  FROM CAL2.EVENT_OCCURRENCE
 WHERE EVENT_RULE_ID = 193
   AND OCCURRENCE_SOURCE = 'GENERATED';
