SET DEFINE OFF;

PROMPT === 0.3.20 Party Consent / Preference alignment ===

DECLARE
  PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_def VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_col);
    IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.'||p_table||' ADD ('||p_col||' '||p_def||')'; END IF;
  END;
BEGIN
  add_col('PARTY_CONSENT','CUSTOMER_DECISION_CODE','VARCHAR2(30 CHAR)');
  add_col('PARTY_CONSENT','CAPTURE_CHANNEL_CODE','VARCHAR2(30 CHAR)');
  add_col('PARTY_CONSENT','DECLARED_AT','TIMESTAMP(6)');
  add_col('PARTY_CONSENT','VALID_TO','DATE');
  add_col('PARTY_CONSENT','CONSENT_TEXT_VERSION_CODE','VARCHAR2(50 CHAR)');
  add_col('PARTY_CONSENT','SCOPE_TEXT','VARCHAR2(1000 CHAR)');
  add_col('PARTY_CONSENT','SCOPE_LIMITATION_TEXT','VARCHAR2(1000 CHAR)');
  add_col('COMMUNICATION_PREFERENCE','ALLOWED_DAYS_CODE','VARCHAR2(30 CHAR)');
  add_col('COMMUNICATION_PREFERENCE','TIME_ZONE_CODE','VARCHAR2(50 CHAR)');
  add_col('COMMUNICATION_PREFERENCE','MARKETING_OPT_OUT_FLAG','CHAR(1 CHAR)');
END;
/

COMMENT ON COLUMN CIF.PARTY_CONSENT.CUSTOMER_DECISION_CODE IS 'تصمیم مشتری';
COMMENT ON COLUMN CIF.PARTY_CONSENT.CAPTURE_CHANNEL_CODE IS 'کانال اخذ رضایت';
COMMENT ON COLUMN CIF.PARTY_CONSENT.DECLARED_AT IS 'تاریخ و زمان اعلام';
COMMENT ON COLUMN CIF.PARTY_CONSENT.VALID_TO IS 'اعتبار تا';
COMMENT ON COLUMN CIF.PARTY_CONSENT.CONSENT_TEXT_VERSION_CODE IS 'نسخه متن رضایت';
COMMENT ON COLUMN CIF.PARTY_CONSENT.SCOPE_TEXT IS 'مجموعه دامنه‌های استاندارد انتخاب‌شده برای هدف رضایت؛ مقادیر به‌صورت چندانتخابی نگهداری می‌شوند';
COMMENT ON COLUMN CIF.PARTY_CONSENT.SCOPE_LIMITATION_TEXT IS 'محدودیت‌ها، استثناها یا توضیحات تکمیلی دامنه رضایت';
COMMENT ON COLUMN CIF.COMMUNICATION_PREFERENCE.ALLOWED_DAYS_CODE IS 'کد روزهای مجاز تماس';
COMMENT ON COLUMN CIF.COMMUNICATION_PREFERENCE.TIME_ZONE_CODE IS 'کد منطقه زمانی ترجیح ارتباط';
COMMENT ON COLUMN CIF.COMMUNICATION_PREFERENCE.MARKETING_OPT_OUT_FLAG IS 'نشانگر عدم تمایل به بازاریابی';

PROMPT === 0.3.20 alignment completed ===
