-- Core Banking Prototype 0.3.22 Fix24
-- Party Authority governed document reference + currency UX support
-- Idempotent Oracle migration for existing CIF schemas.

SET DEFINE OFF;
SET SERVEROUTPUT ON;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CIF' AND TABLE_NAME='REF_AUTHORITY_DOCUMENT_TYPE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_AUTHORITY_DOCUMENT_TYPE (
        AUTHORITY_DOCUMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_AUTHORITY_DOCUMENT_TYPE PRIMARY KEY (AUTHORITY_DOCUMENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_AUTHORITY_DOC_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_AUTHORITY_DOC_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_AUTHORITY_DOC_TYPE_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_AUTHORITY_DOC_TYPE_04 CHECK (RECORD_VERSION >= 1)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

COMMENT ON TABLE CIF.REF_AUTHORITY_DOCUMENT_TYPE IS 'اطلاعات پایه مرجع سند اختیار و نمایندگی';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.AUTHORITY_DOCUMENT_TYPE_CODE IS 'کد مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.NAME_FA IS 'عنوان فارسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.NAME_EN IS 'عنوان انگلیسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.SORT_ORDER IS 'ترتیب نمایش مرجع سند اختیار در فهرست مرجع';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن مرجع سند اختیار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.PARENT_CODE IS 'کد والد مرجع سند اختیار، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد مرجع سند اختیار برای کنترل هم‌زمانی';

MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'POWER_OF_ATTORNEY' CODE, 'وکالت‌نامه رسمی' FA, 'Official Power of Attorney' EN, 'سند رسمی اعطای وکالت یا اختیار.' DESCR, 10 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'BOARD_RESOLUTION' CODE, 'مصوبه یا صورتجلسه هیئت‌مدیره' FA, 'Board Resolution' EN, 'مصوبه یا صورتجلسه معتبر هیئت‌مدیره درخصوص تفویض اختیار.' DESCR, 20 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'COURT_ORDER' CODE, 'حکم یا دستور قضایی' FA, 'Court Order' EN, 'حکم یا دستور مرجع قضایی برای ایجاد اختیار یا نمایندگی.' DESCR, 30 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'GUARDIANSHIP_ORDER' CODE, 'حکم قیمومت' FA, 'Guardianship Order' EN, 'حکم رسمی قیمومت یا سرپرستی قانونی.' DESCR, 40 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'EXECUTORSHIP_DOCUMENT' CODE, 'سند وصایت یا وصیت‌نامه' FA, 'Executorship Document' EN, 'سند رسمی وصایت یا وصیت‌نامه مؤثر بر حدود اختیار.' DESCR, 50 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'ARTICLES_OF_ASSOCIATION' CODE, 'اساسنامه یا سند تأسیس' FA, 'Articles of Association' EN, 'اساسنامه یا سند تأسیس که اختیار نمایندگی را تعیین می‌کند.' DESCR, 60 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'OFFICIAL_DELEGATION' CODE, 'ابلاغ یا تفویض اختیار رسمی' FA, 'Official Delegation' EN, 'ابلاغ، حکم اداری یا سند رسمی تفویض اختیار.' DESCR, 70 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);
MERGE INTO CIF.REF_AUTHORITY_DOCUMENT_TYPE T USING
(SELECT 'OTHER_OFFICIAL_DOCUMENT' CODE, 'سایر اسناد رسمی اختیار' FA, 'Other Official Document' EN, 'سایر اسناد رسمی قابل استناد برای اختیار یا نمایندگی.' DESCR, 80 ORD FROM DUAL) S
ON (T.AUTHORITY_DOCUMENT_TYPE_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA,T.NAME_EN=S.EN,T.DESCRIPTION_FA=S.DESCR,T.SORT_ORDER=S.ORD,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (AUTHORITY_DOCUMENT_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,RECORD_VERSION)
VALUES (S.CODE,S.FA,S.EN,S.DESCR,S.ORD,1,1);

COMMENT ON COLUMN CIF.PARTY_AUTHORITY.DOCUMENT_REF IS 'کد مرجع سند اختیار از CIF.REF_AUTHORITY_DOCUMENT_TYPE';

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES WHERE OWNER='CIF' AND INDEX_NAME='IXFK_PARTY_AUTHORITY_REF_AUTH_DOC';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IXFK_PARTY_AUTHORITY_REF_AUTH_DOC ON CIF.PARTY_AUTHORITY (DOCUMENT_REF) TABLESPACE ITS_CIF';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CIF' AND CONSTRAINT_NAME='FK_PARTY_AUTHORITY_REF_AUTH_DOC';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_AUTHORITY ADD CONSTRAINT FK_PARTY_AUTHORITY_REF_AUTH_DOC FOREIGN KEY (DOCUMENT_REF) REFERENCES CIF.REF_AUTHORITY_DOCUMENT_TYPE (AUTHORITY_DOCUMENT_TYPE_CODE) ENABLE NOVALIDATE';
  END IF;
END;
/

COMMIT;

PROMPT === Fix24 verification ===
SELECT AUTHORITY_DOCUMENT_TYPE_CODE, NAME_FA, IS_ACTIVE
FROM CIF.REF_AUTHORITY_DOCUMENT_TYPE
ORDER BY SORT_ORDER, AUTHORITY_DOCUMENT_TYPE_CODE;

SELECT CONSTRAINT_NAME, STATUS, VALIDATED
FROM ALL_CONSTRAINTS
WHERE OWNER='CIF' AND TABLE_NAME='PARTY_AUTHORITY' AND CONSTRAINT_NAME='FK_PARTY_AUTHORITY_REF_AUTH_DOC';
