PROMPT =====================================================================
PROMPT Core Banking Prototype 0.3.22-fix9 - form validation and address source alignment
PROMPT =====================================================================

-- Operational Party address form defines an address-specific vocabulary:
-- CUSTOMER_DECLARATION / POSTAL_SYSTEM / RESIDENCE_DOCUMENT.
-- It must not be mixed with the generic REF_DATA_SOURCE catalog.
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
    FROM ALL_TABLES
   WHERE OWNER='CIF' AND TABLE_NAME='REF_ADDRESS_SOURCE';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_ADDRESS_SOURCE (
        ADDRESS_SOURCE_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_ADDRESS_SOURCE PRIMARY KEY (ADDRESS_SOURCE_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_ADDRESS_SOURCE_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_ADDRESS_SOURCE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_ADDRESS_SOURCE_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_ADDRESS_SOURCE_04 CHECK (RECORD_VERSION >= 1)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

MERGE INTO CIF.REF_ADDRESS_SOURCE T
USING (
  SELECT 'CUSTOMER_DECLARATION' ADDRESS_SOURCE_CODE, 'اظهار مشتری' NAME_FA, 'Customer Declaration' NAME_EN,
         'ثبت نشانی براساس اظهار مشتری' DESCRIPTION_FA, 10 SORT_ORDER FROM DUAL UNION ALL
  SELECT 'POSTAL_SYSTEM', 'سامانه پست', 'Postal System', 'ثبت یا تأیید نشانی از سامانه پست', 20 FROM DUAL UNION ALL
  SELECT 'RESIDENCE_DOCUMENT', 'مدرک سکونت', 'Residence Document', 'ثبت نشانی براساس مدرک سکونت', 30 FROM DUAL
) S
ON (T.ADDRESS_SOURCE_CODE = S.ADDRESS_SOURCE_CODE)
WHEN MATCHED THEN UPDATE SET
  T.NAME_FA=S.NAME_FA,
  T.NAME_EN=S.NAME_EN,
  T.DESCRIPTION_FA=S.DESCRIPTION_FA,
  T.SORT_ORDER=S.SORT_ORDER,
  T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (
  ADDRESS_SOURCE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER,
  IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION
) VALUES (
  S.ADDRESS_SOURCE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER,
  1, NULL, NULL, NULL, 1
);

COMMIT;

DECLARE
  V_TABLE_COUNT NUMBER;
  V_SEED_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_TABLE_COUNT
    FROM ALL_TABLES
   WHERE OWNER='CIF' AND TABLE_NAME='REF_ADDRESS_SOURCE';

  SELECT COUNT(*) INTO V_SEED_COUNT
    FROM CIF.REF_ADDRESS_SOURCE
   WHERE ADDRESS_SOURCE_CODE IN ('CUSTOMER_DECLARATION','POSTAL_SYSTEM','RESIDENCE_DOCUMENT');

  IF V_TABLE_COUNT <> 1 OR V_SEED_COUNT <> 3 THEN
    RAISE_APPLICATION_ERROR(-20091, 'REF_ADDRESS_SOURCE alignment failed. Expected table + 3 operational seed rows.');
  END IF;
END;
/

PROMPT 0.3.22-fix9 form validation and address source alignment completed.
