PROMPT =====================================================================
PROMPT Core Banking Prototype 0.3.22-fix13 - employment contract reference
PROMPT =====================================================================

-- PARTY operational form defines the allowed contract-type vocabulary.
-- The user explicitly requires CONTRACT_TYPE_CODE to be selected from database
-- reference data while the code is stored in PARTY_EMPLOYMENT.
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
    FROM ALL_TABLES
   WHERE OWNER='CIF' AND TABLE_NAME='REF_CONTRACT_TYPE';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_CONTRACT_TYPE (
        CONTRACT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_CONTRACT_TYPE PRIMARY KEY (CONTRACT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_CONTRACT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_CONTRACT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_CONTRACT_TYPE_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_CONTRACT_TYPE_04 CHECK (RECORD_VERSION >= 1)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

MERGE INTO CIF.REF_CONTRACT_TYPE T
USING (
  SELECT 'PERMANENT' CONTRACT_TYPE_CODE, 'دائم' NAME_FA, 'Permanent' NAME_EN, 10 SORT_ORDER FROM DUAL UNION ALL
  SELECT 'TEMPORARY', 'موقت', 'Temporary', 20 FROM DUAL UNION ALL
  SELECT 'CONTRACTOR', 'پیمانکاری', 'Contractor', 30 FROM DUAL UNION ALL
  SELECT 'SELF_EMPLOYED', 'خویش‌فرما', 'Self Employed', 40 FROM DUAL
) S
ON (T.CONTRACT_TYPE_CODE = S.CONTRACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET
  T.NAME_FA=S.NAME_FA,
  T.NAME_EN=S.NAME_EN,
  T.SORT_ORDER=S.SORT_ORDER,
  T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (
  CONTRACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER,
  IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION
) VALUES (
  S.CONTRACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, NULL, S.SORT_ORDER,
  1, NULL, NULL, NULL, 1
);

COMMIT;

DECLARE
  V_TABLE_COUNT NUMBER;
  V_SEED_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_TABLE_COUNT
    FROM ALL_TABLES
   WHERE OWNER='CIF' AND TABLE_NAME='REF_CONTRACT_TYPE';

  SELECT COUNT(*) INTO V_SEED_COUNT
    FROM CIF.REF_CONTRACT_TYPE
   WHERE CONTRACT_TYPE_CODE IN ('PERMANENT','TEMPORARY','CONTRACTOR','SELF_EMPLOYED');

  IF V_TABLE_COUNT <> 1 OR V_SEED_COUNT <> 4 THEN
    RAISE_APPLICATION_ERROR(-20113, 'REF_CONTRACT_TYPE alignment failed. Expected table + 4 operational seed rows.');
  END IF;
END;
/

PROMPT 0.3.22-fix13 employment contract reference completed.
