-- Core Banking Prototype 0.3.15
-- Align PARTY_DOCUMENT with CIF-tables3.xlsx without failing when columns already exist.
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'CIF' AND TABLE_NAME = 'PARTY_DOCUMENT' AND COLUMN_NAME = p_column;
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_DOCUMENT ADD (' || p_ddl || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('ISSUING_AUTHORITY_TEXT', 'ISSUING_AUTHORITY_TEXT VARCHAR2(200 CHAR)');
  add_column_if_missing('CONTROL_STATUS_CODE', 'CONTROL_STATUS_CODE VARCHAR2(30 CHAR)');
  add_column_if_missing('DESCRIPTION_TEXT', 'DESCRIPTION_TEXT VARCHAR2(1000 CHAR)');
END;
/
COMMENT ON COLUMN CIF.PARTY_DOCUMENT.ISSUING_AUTHORITY_TEXT IS 'مرجع صادرکننده';
COMMENT ON COLUMN CIF.PARTY_DOCUMENT.CONTROL_STATUS_CODE IS 'وضعیت کنترل';
COMMENT ON COLUMN CIF.PARTY_DOCUMENT.DESCRIPTION_TEXT IS 'توضیحات مدرک';
