-- Core Banking Prototype 0.3.22-prototype-fix19
-- Party operational grids + role context reference alignment.
-- No operational table schema change is required: PARTY_ROLE already owns CONTEXT_TYPE_CODE/CONTEXT_ID.

MERGE INTO CIF.REF_CONTEXT_TYPE T
USING (
  SELECT 'GLOBAL' CODE, 'سراسری' NAME_FA, 'Global' NAME_EN, 'زمینه عمومی و سراسری' DESCRIPTION_FA, 10 SORT_ORDER FROM DUAL UNION ALL
  SELECT 'ACCOUNT', 'حساب', 'Account', 'زمینه نقش در سطح حساب', 20 FROM DUAL UNION ALL
  SELECT 'PRODUCT', 'محصول', 'Product', 'زمینه نقش در سطح محصول', 30 FROM DUAL UNION ALL
  SELECT 'BRANCH', 'شعبه', 'Branch', 'زمینه نقش در سطح شعبه', 40 FROM DUAL UNION ALL
  SELECT 'CONTRACT', 'قرارداد', 'Contract', 'زمینه نقش در سطح قرارداد', 50 FROM DUAL UNION ALL
  SELECT 'CASE', 'پرونده', 'Case', 'زمینه نقش در سطح پرونده؛ در Prototype برای پرونده KYC قابل انتخاب است', 60 FROM DUAL
) S
ON (T.CONTEXT_TYPE_CODE = S.CODE)
WHEN MATCHED THEN UPDATE SET
  T.NAME_FA=S.NAME_FA,
  T.NAME_EN=S.NAME_EN,
  T.DESCRIPTION_FA=S.DESCRIPTION_FA,
  T.SORT_ORDER=S.SORT_ORDER,
  T.IS_ACTIVE=1,
  T.RECORD_VERSION=CASE WHEN NVL(T.NAME_FA,'#')<>S.NAME_FA OR NVL(T.NAME_EN,'#')<>S.NAME_EN OR NVL(T.DESCRIPTION_FA,'#')<>S.DESCRIPTION_FA THEN T.RECORD_VERSION+1 ELSE T.RECORD_VERSION END
WHEN NOT MATCHED THEN INSERT
  (CONTEXT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES
  (S.CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, 1, NULL, NULL, NULL, 1);

COMMIT;

PROMPT Fix19 reference validation
SELECT CONTEXT_TYPE_CODE, NAME_FA, NAME_EN, IS_ACTIVE
FROM CIF.REF_CONTEXT_TYPE
WHERE CONTEXT_TYPE_CODE IN ('GLOBAL','ACCOUNT','PRODUCT','BRANCH','CONTRACT','CASE')
ORDER BY SORT_ORDER, CONTEXT_TYPE_CODE;
