PROMPT =====================================================================
PROMPT FIX42 diagnostic - no DDL, no data change
PROMPT =====================================================================

PROMPT Parent objects visible to current session:
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE OWNER='GEO'
   AND TABLE_NAME IN ('JOBS','JOB_GROUPS')
 ORDER BY TABLE_NAME;

PROMPT Parent unique constraints:
SELECT c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS,
       LISTAGG(cc.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY cc.POSITION) AS COLUMNS
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONS_COLUMNS cc
    ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
 WHERE c.OWNER='GEO'
   AND c.TABLE_NAME IN ('JOBS','JOB_GROUPS')
   AND c.CONSTRAINT_TYPE IN ('P','U')
 GROUP BY c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS
 ORDER BY c.TABLE_NAME, c.CONSTRAINT_NAME;

PROMPT Current CIF employment foreign keys:
SELECT c.CONSTRAINT_NAME, cc.COLUMN_NAME, c.R_OWNER,
       pc.TABLE_NAME AS PARENT_TABLE, pcc.COLUMN_NAME AS PARENT_COLUMN,
       c.STATUS, c.VALIDATED
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONS_COLUMNS cc
    ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
  LEFT JOIN ALL_CONSTRAINTS pc
    ON pc.OWNER=c.R_OWNER AND pc.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
  LEFT JOIN ALL_CONS_COLUMNS pcc
    ON pcc.OWNER=pc.OWNER AND pcc.CONSTRAINT_NAME=pc.CONSTRAINT_NAME
   AND pcc.POSITION=cc.POSITION
 WHERE c.OWNER='CIF'
   AND c.TABLE_NAME='PARTY_EMPLOYMENT'
   AND c.CONSTRAINT_TYPE='R'
 ORDER BY c.CONSTRAINT_NAME, cc.POSITION;

PROMPT Direct table REFERENCES grants currently visible:
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, PRIVILEGE, GRANTABLE
  FROM ALL_TAB_PRIVS
 WHERE GRANTEE='CIF'
   AND TABLE_SCHEMA='GEO'
   AND TABLE_NAME IN ('JOBS','JOB_GROUPS')
   AND PRIVILEGE='REFERENCES'
 ORDER BY TABLE_NAME;

PROMPT If the previous query returns zero rows, run as GEO owner/DBA:
PROMPT   GRANT REFERENCES ON GEO.JOBS TO CIF;
PROMPT   GRANT REFERENCES ON GEO.JOB_GROUPS TO CIF;
