-- Core Banking Prototype 0.3.16
-- Align PARTY_CLASSIFICATION with CIF-tables3.xlsx without failing when the column already exists.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'CIF' AND TABLE_NAME = 'PARTY_CLASSIFICATION' AND COLUMN_NAME = 'DESCRIPTION_TEXT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_CLASSIFICATION ADD (DESCRIPTION_TEXT VARCHAR2(1000 CHAR))';
  END IF;
END;
/
COMMENT ON COLUMN CIF.PARTY_CLASSIFICATION.DESCRIPTION_TEXT IS 'توضیحات طبقه‌بندی';
