SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ================================================================
PROMPT CIF 0.3.22 Fix21 - Persian comments for reference-data columns
PROMPT 99 reference tables / 994 governed columns
PROMPT ================================================================

DECLARE
  v_exists NUMBER;
  PROCEDURE set_column_comment(
    p_table_name  IN VARCHAR2,
    p_column_name IN VARCHAR2,
    p_comment_fa  IN VARCHAR2
  ) IS
    v_sql VARCHAR2(4000);
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM ALL_TAB_COLUMNS WHERE OWNER = 'CIF' AND TABLE_NAME = UPPER(p_table_name) AND COLUMN_NAME = UPPER(p_column_name);
    IF v_exists = 1 THEN
      v_sql := 'COMMENT ON COLUMN CIF.' || p_table_name || '.' || p_column_name || ' IS ''' || REPLACE(p_comment_fa, '''', '''''') || '''';
      EXECUTE IMMEDIATE v_sql;
    ELSE
      DBMS_OUTPUT.PUT_LINE('SKIP missing column: CIF.' || p_table_name || '.' || p_column_name);
    END IF;
  END;
BEGIN
  set_column_comment('REF_ACTOR_ROLE', 'ACTOR_ROLE_CODE', 'کد نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'NAME_FA', 'عنوان فارسی نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'NAME_EN', 'عنوان انگلیسی نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'DESCRIPTION_FA', 'توضیحات فارسی نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'SORT_ORDER', 'ترتیب نمایش نقش عامل عملیات در فهرست‌های مرجع');
  set_column_comment('REF_ACTOR_ROLE', 'IS_ACTIVE', 'نشانگر فعال بودن نقش عامل عملیات؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ACTOR_ROLE', 'PARENT_CODE', 'کد والد نقش عامل عملیات در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ACTOR_ROLE', 'VALID_FROM', 'تاریخ شروع اعتبار نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'VALID_TO', 'تاریخ پایان اعتبار نقش عامل عملیات');
  set_column_comment('REF_ACTOR_ROLE', 'RECORD_VERSION', 'شماره نسخه رکورد نقش عامل عملیات برای کنترل هم‌زمانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'ADDRESS_SOURCE_CODE', 'کد منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'NAME_FA', 'عنوان فارسی منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'NAME_EN', 'عنوان انگلیسی منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'DESCRIPTION_FA', 'توضیحات فارسی منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'SORT_ORDER', 'ترتیب نمایش منبع نشانی در فهرست‌های مرجع');
  set_column_comment('REF_ADDRESS_SOURCE', 'IS_ACTIVE', 'نشانگر فعال بودن منبع نشانی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ADDRESS_SOURCE', 'PARENT_CODE', 'کد والد منبع نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ADDRESS_SOURCE', 'VALID_FROM', 'تاریخ شروع اعتبار منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'VALID_TO', 'تاریخ پایان اعتبار منبع نشانی');
  set_column_comment('REF_ADDRESS_SOURCE', 'RECORD_VERSION', 'شماره نسخه رکورد منبع نشانی برای کنترل هم‌زمانی');
  set_column_comment('REF_ADDRESS_TYPE', 'ADDRESS_TYPE_CODE', 'کد نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'NAME_FA', 'عنوان فارسی نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع نشانی در فهرست‌های مرجع');
  set_column_comment('REF_ADDRESS_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع نشانی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ADDRESS_TYPE', 'PARENT_CODE', 'کد والد نوع نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ADDRESS_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع نشانی');
  set_column_comment('REF_ADDRESS_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع نشانی برای کنترل هم‌زمانی');
  set_column_comment('REF_ALERT_RESOLUTION', 'RESOLUTION_CODE', 'کد نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'NAME_FA', 'عنوان فارسی نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'NAME_EN', 'عنوان انگلیسی نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'DESCRIPTION_FA', 'توضیحات فارسی نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'SORT_ORDER', 'ترتیب نمایش نتیجه رسیدگی به هشدار در فهرست‌های مرجع');
  set_column_comment('REF_ALERT_RESOLUTION', 'IS_ACTIVE', 'نشانگر فعال بودن نتیجه رسیدگی به هشدار؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ALERT_RESOLUTION', 'PARENT_CODE', 'کد والد نتیجه رسیدگی به هشدار در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ALERT_RESOLUTION', 'VALID_FROM', 'تاریخ شروع اعتبار نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'VALID_TO', 'تاریخ پایان اعتبار نتیجه رسیدگی به هشدار');
  set_column_comment('REF_ALERT_RESOLUTION', 'RECORD_VERSION', 'شماره نسخه رکورد نتیجه رسیدگی به هشدار برای کنترل هم‌زمانی');
  set_column_comment('REF_ALERT_TYPE', 'ALERT_TYPE_CODE', 'کد نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'NAME_FA', 'عنوان فارسی نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع هشدار در فهرست‌های مرجع');
  set_column_comment('REF_ALERT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع هشدار؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ALERT_TYPE', 'PARENT_CODE', 'کد والد نوع هشدار در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ALERT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع هشدار');
  set_column_comment('REF_ALERT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع هشدار برای کنترل هم‌زمانی');
  set_column_comment('REF_ASSIGNMENT_REASON', 'ASSIGNMENT_REASON_CODE', 'کد دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'NAME_FA', 'عنوان فارسی دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'NAME_EN', 'عنوان انگلیسی دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'DESCRIPTION_FA', 'توضیحات فارسی دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'SORT_ORDER', 'ترتیب نمایش دلیل تخصیص در فهرست‌های مرجع');
  set_column_comment('REF_ASSIGNMENT_REASON', 'IS_ACTIVE', 'نشانگر فعال بودن دلیل تخصیص؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ASSIGNMENT_REASON', 'PARENT_CODE', 'کد والد دلیل تخصیص در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ASSIGNMENT_REASON', 'VALID_FROM', 'تاریخ شروع اعتبار دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'VALID_TO', 'تاریخ پایان اعتبار دلیل تخصیص');
  set_column_comment('REF_ASSIGNMENT_REASON', 'RECORD_VERSION', 'شماره نسخه رکورد دلیل تخصیص برای کنترل هم‌زمانی');
  set_column_comment('REF_AUDIT_ACTION', 'AUDIT_ACTION_CODE', 'کد نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'NAME_FA', 'عنوان فارسی نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'NAME_EN', 'عنوان انگلیسی نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'DESCRIPTION_FA', 'توضیحات فارسی نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'SORT_ORDER', 'ترتیب نمایش نوع عملیات ممیزی در فهرست‌های مرجع');
  set_column_comment('REF_AUDIT_ACTION', 'IS_ACTIVE', 'نشانگر فعال بودن نوع عملیات ممیزی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_AUDIT_ACTION', 'PARENT_CODE', 'کد والد نوع عملیات ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_AUDIT_ACTION', 'VALID_FROM', 'تاریخ شروع اعتبار نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'VALID_TO', 'تاریخ پایان اعتبار نوع عملیات ممیزی');
  set_column_comment('REF_AUDIT_ACTION', 'RECORD_VERSION', 'شماره نسخه رکورد نوع عملیات ممیزی برای کنترل هم‌زمانی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'AUDIT_ENTITY_TYPE_CODE', 'کد نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'NAME_FA', 'عنوان فارسی نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع موجودیت ممیزی در فهرست‌های مرجع');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع موجودیت ممیزی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'PARENT_CODE', 'کد والد نوع موجودیت ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع موجودیت ممیزی');
  set_column_comment('REF_AUDIT_ENTITY_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع موجودیت ممیزی برای کنترل هم‌زمانی');
  set_column_comment('REF_AUDIT_REASON', 'AUDIT_REASON_CODE', 'کد دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'NAME_FA', 'عنوان فارسی دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'NAME_EN', 'عنوان انگلیسی دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'DESCRIPTION_FA', 'توضیحات فارسی دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'SORT_ORDER', 'ترتیب نمایش دلیل ممیزی در فهرست‌های مرجع');
  set_column_comment('REF_AUDIT_REASON', 'IS_ACTIVE', 'نشانگر فعال بودن دلیل ممیزی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_AUDIT_REASON', 'PARENT_CODE', 'کد والد دلیل ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_AUDIT_REASON', 'VALID_FROM', 'تاریخ شروع اعتبار دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'VALID_TO', 'تاریخ پایان اعتبار دلیل ممیزی');
  set_column_comment('REF_AUDIT_REASON', 'RECORD_VERSION', 'شماره نسخه رکورد دلیل ممیزی برای کنترل هم‌زمانی');
  set_column_comment('REF_AUTHORITY_SCOPE', 'AUTHORITY_SCOPE_CODE', 'کد دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'NAME_FA', 'عنوان فارسی دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'NAME_EN', 'عنوان انگلیسی دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'DESCRIPTION_FA', 'توضیحات فارسی دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'SORT_ORDER', 'ترتیب نمایش دامنه اختیار در فهرست‌های مرجع');
  set_column_comment('REF_AUTHORITY_SCOPE', 'IS_ACTIVE', 'نشانگر فعال بودن دامنه اختیار؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_AUTHORITY_SCOPE', 'PARENT_CODE', 'کد والد دامنه اختیار در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_AUTHORITY_SCOPE', 'VALID_FROM', 'تاریخ شروع اعتبار دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'VALID_TO', 'تاریخ پایان اعتبار دامنه اختیار');
  set_column_comment('REF_AUTHORITY_SCOPE', 'RECORD_VERSION', 'شماره نسخه رکورد دامنه اختیار برای کنترل هم‌زمانی');
  set_column_comment('REF_AUTHORITY_TYPE', 'AUTHORITY_TYPE_CODE', 'کد نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'NAME_FA', 'عنوان فارسی نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع اختیار در فهرست‌های مرجع');
  set_column_comment('REF_AUTHORITY_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع اختیار؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_AUTHORITY_TYPE', 'PARENT_CODE', 'کد والد نوع اختیار در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_AUTHORITY_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع اختیار');
  set_column_comment('REF_AUTHORITY_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع اختیار برای کنترل هم‌زمانی');
  set_column_comment('REF_BRANCH', 'BRANCH_CODE', 'کد شعبه');
  set_column_comment('REF_BRANCH', 'NAME_FA', 'عنوان فارسی شعبه');
  set_column_comment('REF_BRANCH', 'NAME_EN', 'عنوان انگلیسی شعبه');
  set_column_comment('REF_BRANCH', 'DESCRIPTION_FA', 'توضیحات فارسی شعبه');
  set_column_comment('REF_BRANCH', 'SORT_ORDER', 'ترتیب نمایش شعبه در فهرست‌های مرجع');
  set_column_comment('REF_BRANCH', 'IS_ACTIVE', 'نشانگر فعال بودن شعبه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_BRANCH', 'PARENT_CODE', 'کد والد شعبه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_BRANCH', 'VALID_FROM', 'تاریخ شروع اعتبار شعبه');
  set_column_comment('REF_BRANCH', 'VALID_TO', 'تاریخ پایان اعتبار شعبه');
  set_column_comment('REF_BRANCH', 'RECORD_VERSION', 'شماره نسخه رکورد شعبه برای کنترل هم‌زمانی');
  set_column_comment('REF_CHANNEL', 'CHANNEL_CODE', 'کد کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'NAME_FA', 'عنوان فارسی کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'NAME_EN', 'عنوان انگلیسی کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'DESCRIPTION_FA', 'توضیحات فارسی کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'SORT_ORDER', 'ترتیب نمایش کانال ارتباطی در فهرست‌های مرجع');
  set_column_comment('REF_CHANNEL', 'IS_ACTIVE', 'نشانگر فعال بودن کانال ارتباطی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CHANNEL', 'PARENT_CODE', 'کد والد کانال ارتباطی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CHANNEL', 'VALID_FROM', 'تاریخ شروع اعتبار کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'VALID_TO', 'تاریخ پایان اعتبار کانال ارتباطی');
  set_column_comment('REF_CHANNEL', 'RECORD_VERSION', 'شماره نسخه رکورد کانال ارتباطی برای کنترل هم‌زمانی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'CLASSIFICATION_TYPE_CODE', 'کد نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'NAME_FA', 'عنوان فارسی نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع طبقه‌بندی در فهرست‌های مرجع');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع طبقه‌بندی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'PARENT_CODE', 'کد والد نوع طبقه‌بندی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع طبقه‌بندی برای کنترل هم‌زمانی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'CLASSIFICATION_TYPE_CODE', 'نوع طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'CLASSIFICATION_VALUE_CODE', 'کد مقدار طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'NAME_FA', 'عنوان فارسی مقادیر طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'NAME_EN', 'عنوان انگلیسی مقادیر طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'DESCRIPTION_FA', 'توضیحات فارسی مقادیر طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'SORT_ORDER', 'ترتیب نمایش مقادیر طبقه‌بندی در فهرست‌های مرجع');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'IS_ACTIVE', 'نشانگر فعال بودن مقادیر طبقه‌بندی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'PARENT_CODE', 'کد والد مقادیر طبقه‌بندی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'VALID_FROM', 'تاریخ شروع اعتبار مقادیر طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'VALID_TO', 'تاریخ پایان اعتبار مقادیر طبقه‌بندی');
  set_column_comment('REF_CLASSIFICATION_VALUE', 'RECORD_VERSION', 'شماره نسخه رکورد مقادیر طبقه‌بندی برای کنترل هم‌زمانی');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'COMMUNICATION_PURPOSE_CODE', 'کد هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'NAME_FA', 'عنوان فارسی هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'NAME_EN', 'عنوان انگلیسی هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'DESCRIPTION_FA', 'توضیحات فارسی هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'SORT_ORDER', 'ترتیب نمایش هدف ارتباطات در فهرست‌های مرجع');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'IS_ACTIVE', 'نشانگر فعال بودن هدف ارتباطات؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'PARENT_CODE', 'کد والد هدف ارتباطات در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'VALID_FROM', 'تاریخ شروع اعتبار هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'VALID_TO', 'تاریخ پایان اعتبار هدف ارتباطات');
  set_column_comment('REF_COMMUNICATION_PURPOSE', 'RECORD_VERSION', 'شماره نسخه رکورد هدف ارتباطات برای کنترل هم‌زمانی');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'COMPLAINT_RESOLUTION_CODE', 'کد نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'NAME_FA', 'عنوان فارسی نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'NAME_EN', 'عنوان انگلیسی نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'DESCRIPTION_FA', 'توضیحات فارسی نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'SORT_ORDER', 'ترتیب نمایش نتیجه رسیدگی به شکایت در فهرست‌های مرجع');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'IS_ACTIVE', 'نشانگر فعال بودن نتیجه رسیدگی به شکایت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'PARENT_CODE', 'کد والد نتیجه رسیدگی به شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'VALID_FROM', 'تاریخ شروع اعتبار نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'VALID_TO', 'تاریخ پایان اعتبار نتیجه رسیدگی به شکایت');
  set_column_comment('REF_COMPLAINT_RESOLUTION', 'RECORD_VERSION', 'شماره نسخه رکورد نتیجه رسیدگی به شکایت برای کنترل هم‌زمانی');
  set_column_comment('REF_COMPLAINT_STATUS', 'COMPLAINT_STATUS_CODE', 'کد وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت شکایت در فهرست‌های مرجع');
  set_column_comment('REF_COMPLAINT_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت شکایت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_COMPLAINT_STATUS', 'PARENT_CODE', 'کد والد وضعیت شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_COMPLAINT_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت شکایت برای کنترل هم‌زمانی');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'COMPLAINT_STATUS_REASON_CODE', 'کد دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'NAME_FA', 'عنوان فارسی دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'NAME_EN', 'عنوان انگلیسی دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'DESCRIPTION_FA', 'توضیحات فارسی دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'SORT_ORDER', 'ترتیب نمایش دلیل تغییر وضعیت شکایت در فهرست‌های مرجع');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'IS_ACTIVE', 'نشانگر فعال بودن دلیل تغییر وضعیت شکایت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'PARENT_CODE', 'کد والد دلیل تغییر وضعیت شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'VALID_FROM', 'تاریخ شروع اعتبار دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'VALID_TO', 'تاریخ پایان اعتبار دلیل تغییر وضعیت شکایت');
  set_column_comment('REF_COMPLAINT_STATUS_REASON', 'RECORD_VERSION', 'شماره نسخه رکورد دلیل تغییر وضعیت شکایت برای کنترل هم‌زمانی');
  set_column_comment('REF_COMPLAINT_TYPE', 'COMPLAINT_TYPE_CODE', 'کد نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'NAME_FA', 'عنوان فارسی نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع شکایت در فهرست‌های مرجع');
  set_column_comment('REF_COMPLAINT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع شکایت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_COMPLAINT_TYPE', 'PARENT_CODE', 'کد والد نوع شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_COMPLAINT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع شکایت');
  set_column_comment('REF_COMPLAINT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع شکایت برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'ASSOCIATION_TYPE_CODE', 'کد نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'NAME_FA', 'عنوان فارسی نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع ارتباط اطلاعات تماس در فهرست‌های مرجع');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع ارتباط اطلاعات تماس؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'PARENT_CODE', 'کد والد نوع ارتباط اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع ارتباط اطلاعات تماس');
  set_column_comment('REF_CONTACT_ASSOCIATION_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع ارتباط اطلاعات تماس برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTACT_PURPOSE', 'CONTACT_PURPOSE_CODE', 'کد کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'NAME_FA', 'عنوان فارسی کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'NAME_EN', 'عنوان انگلیسی کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'DESCRIPTION_FA', 'توضیحات فارسی کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'SORT_ORDER', 'ترتیب نمایش کاربرد اطلاعات تماس در فهرست‌های مرجع');
  set_column_comment('REF_CONTACT_PURPOSE', 'IS_ACTIVE', 'نشانگر فعال بودن کاربرد اطلاعات تماس؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTACT_PURPOSE', 'PARENT_CODE', 'کد والد کاربرد اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTACT_PURPOSE', 'VALID_FROM', 'تاریخ شروع اعتبار کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'VALID_TO', 'تاریخ پایان اعتبار کاربرد اطلاعات تماس');
  set_column_comment('REF_CONTACT_PURPOSE', 'RECORD_VERSION', 'شماره نسخه رکورد کاربرد اطلاعات تماس برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTACT_TYPE', 'CONTACT_TYPE_CODE', 'کد نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'NAME_FA', 'عنوان فارسی نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع اطلاعات تماس در فهرست‌های مرجع');
  set_column_comment('REF_CONTACT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع اطلاعات تماس؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTACT_TYPE', 'PARENT_CODE', 'کد والد نوع اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTACT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع اطلاعات تماس');
  set_column_comment('REF_CONTACT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع اطلاعات تماس برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTEXT_TYPE', 'CONTEXT_TYPE_CODE', 'کد نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'NAME_FA', 'عنوان فارسی نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع زمینه در فهرست‌های مرجع');
  set_column_comment('REF_CONTEXT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع زمینه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTEXT_TYPE', 'PARENT_CODE', 'کد والد نوع زمینه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTEXT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع زمینه');
  set_column_comment('REF_CONTEXT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع زمینه برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTRACT_TYPE', 'CONTRACT_TYPE_CODE', 'کد نوع قرارداد');
  set_column_comment('REF_CONTRACT_TYPE', 'NAME_FA', 'عنوان فارسی نوع قرارداد اشتغال');
  set_column_comment('REF_CONTRACT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع قرارداد اشتغال');
  set_column_comment('REF_CONTRACT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع قرارداد اشتغال');
  set_column_comment('REF_CONTRACT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع قرارداد اشتغال در فهرست‌های مرجع');
  set_column_comment('REF_CONTRACT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع قرارداد اشتغال؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTRACT_TYPE', 'PARENT_CODE', 'کد والد نوع قرارداد اشتغال در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTRACT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع قرارداد اشتغال');
  set_column_comment('REF_CONTRACT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع قرارداد اشتغال');
  set_column_comment('REF_CONTRACT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع قرارداد اشتغال برای کنترل هم‌زمانی');
  set_column_comment('REF_CONTROL_BASIS', 'CONTROL_BASIS_CODE', 'کد مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'NAME_FA', 'عنوان فارسی مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'NAME_EN', 'عنوان انگلیسی مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'DESCRIPTION_FA', 'توضیحات فارسی مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'SORT_ORDER', 'ترتیب نمایش مبنای کنترل در فهرست‌های مرجع');
  set_column_comment('REF_CONTROL_BASIS', 'IS_ACTIVE', 'نشانگر فعال بودن مبنای کنترل؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_CONTROL_BASIS', 'PARENT_CODE', 'کد والد مبنای کنترل در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_CONTROL_BASIS', 'VALID_FROM', 'تاریخ شروع اعتبار مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'VALID_TO', 'تاریخ پایان اعتبار مبنای کنترل');
  set_column_comment('REF_CONTROL_BASIS', 'RECORD_VERSION', 'شماره نسخه رکورد مبنای کنترل برای کنترل هم‌زمانی');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'DATA_QUALITY_STATUS_CODE', 'کد وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت کیفیت داده در فهرست‌های مرجع');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت کیفیت داده؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'PARENT_CODE', 'کد والد وضعیت کیفیت داده در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت کیفیت داده');
  set_column_comment('REF_DATA_QUALITY_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت کیفیت داده برای کنترل هم‌زمانی');
  set_column_comment('REF_DATA_SOURCE', 'DATA_SOURCE_CODE', 'کد منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'NAME_FA', 'عنوان فارسی منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'NAME_EN', 'عنوان انگلیسی منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'DESCRIPTION_FA', 'توضیحات فارسی منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'SORT_ORDER', 'ترتیب نمایش منبع داده در فهرست‌های مرجع');
  set_column_comment('REF_DATA_SOURCE', 'IS_ACTIVE', 'نشانگر فعال بودن منبع داده؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_DATA_SOURCE', 'PARENT_CODE', 'کد والد منبع داده در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_DATA_SOURCE', 'VALID_FROM', 'تاریخ شروع اعتبار منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'VALID_TO', 'تاریخ پایان اعتبار منبع داده');
  set_column_comment('REF_DATA_SOURCE', 'RECORD_VERSION', 'شماره نسخه رکورد منبع داده برای کنترل هم‌زمانی');
  set_column_comment('REF_DECISION', 'DECISION_CODE', 'کد تصمیم');
  set_column_comment('REF_DECISION', 'NAME_FA', 'عنوان فارسی تصمیم');
  set_column_comment('REF_DECISION', 'NAME_EN', 'عنوان انگلیسی تصمیم');
  set_column_comment('REF_DECISION', 'DESCRIPTION_FA', 'توضیحات فارسی تصمیم');
  set_column_comment('REF_DECISION', 'SORT_ORDER', 'ترتیب نمایش تصمیم در فهرست‌های مرجع');
  set_column_comment('REF_DECISION', 'IS_ACTIVE', 'نشانگر فعال بودن تصمیم؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_DECISION', 'PARENT_CODE', 'کد والد تصمیم در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_DECISION', 'VALID_FROM', 'تاریخ شروع اعتبار تصمیم');
  set_column_comment('REF_DECISION', 'VALID_TO', 'تاریخ پایان اعتبار تصمیم');
  set_column_comment('REF_DECISION', 'RECORD_VERSION', 'شماره نسخه رکورد تصمیم برای کنترل هم‌زمانی');
  set_column_comment('REF_DOCUMENT_TYPE', 'DOCUMENT_TYPE_CODE', 'کد نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'NAME_FA', 'عنوان فارسی نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع مدرک در فهرست‌های مرجع');
  set_column_comment('REF_DOCUMENT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع مدرک؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_DOCUMENT_TYPE', 'PARENT_CODE', 'کد والد نوع مدرک در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_DOCUMENT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع مدرک');
  set_column_comment('REF_DOCUMENT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع مدرک برای کنترل هم‌زمانی');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'DUE_DILIGENCE_LEVEL_CODE', 'کد سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'NAME_FA', 'عنوان فارسی سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'NAME_EN', 'عنوان انگلیسی سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'DESCRIPTION_FA', 'توضیحات فارسی سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'SORT_ORDER', 'ترتیب نمایش سطح بررسی مشتری در فهرست‌های مرجع');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'IS_ACTIVE', 'نشانگر فعال بودن سطح بررسی مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'PARENT_CODE', 'کد والد سطح بررسی مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'VALID_FROM', 'تاریخ شروع اعتبار سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'VALID_TO', 'تاریخ پایان اعتبار سطح بررسی مشتری');
  set_column_comment('REF_DUE_DILIGENCE_LEVEL', 'RECORD_VERSION', 'شماره نسخه رکورد سطح بررسی مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'ECONOMIC_SECTOR_CODE', 'کد بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'NAME_FA', 'عنوان فارسی بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'NAME_EN', 'عنوان انگلیسی بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'DESCRIPTION_FA', 'توضیحات فارسی بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'SORT_ORDER', 'ترتیب نمایش بخش اقتصادی در فهرست‌های مرجع');
  set_column_comment('REF_ECONOMIC_SECTOR', 'IS_ACTIVE', 'نشانگر فعال بودن بخش اقتصادی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ECONOMIC_SECTOR', 'PARENT_CODE', 'کد والد بخش اقتصادی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ECONOMIC_SECTOR', 'VALID_FROM', 'تاریخ شروع اعتبار بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'VALID_TO', 'تاریخ پایان اعتبار بخش اقتصادی');
  set_column_comment('REF_ECONOMIC_SECTOR', 'RECORD_VERSION', 'شماره نسخه رکورد بخش اقتصادی برای کنترل هم‌زمانی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'EXTERNAL_PROVIDER_CODE', 'کد ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'NAME_FA', 'عنوان فارسی ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'NAME_EN', 'عنوان انگلیسی ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'DESCRIPTION_FA', 'توضیحات فارسی ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'SORT_ORDER', 'ترتیب نمایش ارائه‌دهنده خارجی در فهرست‌های مرجع');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'IS_ACTIVE', 'نشانگر فعال بودن ارائه‌دهنده خارجی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'PARENT_CODE', 'کد والد ارائه‌دهنده خارجی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'VALID_FROM', 'تاریخ شروع اعتبار ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'VALID_TO', 'تاریخ پایان اعتبار ارائه‌دهنده خارجی');
  set_column_comment('REF_EXTERNAL_PROVIDER', 'RECORD_VERSION', 'شماره نسخه رکورد ارائه‌دهنده خارجی برای کنترل هم‌زمانی');
  set_column_comment('REF_GENDER', 'GENDER_CODE', 'کد جنسیت');
  set_column_comment('REF_GENDER', 'NAME_FA', 'عنوان فارسی جنسیت');
  set_column_comment('REF_GENDER', 'NAME_EN', 'عنوان انگلیسی جنسیت');
  set_column_comment('REF_GENDER', 'DESCRIPTION_FA', 'توضیحات فارسی جنسیت');
  set_column_comment('REF_GENDER', 'SORT_ORDER', 'ترتیب نمایش جنسیت در فهرست‌های مرجع');
  set_column_comment('REF_GENDER', 'IS_ACTIVE', 'نشانگر فعال بودن جنسیت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_GENDER', 'PARENT_CODE', 'کد والد جنسیت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_GENDER', 'VALID_FROM', 'تاریخ شروع اعتبار جنسیت');
  set_column_comment('REF_GENDER', 'VALID_TO', 'تاریخ پایان اعتبار جنسیت');
  set_column_comment('REF_GENDER', 'RECORD_VERSION', 'شماره نسخه رکورد جنسیت برای کنترل هم‌زمانی');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'MEMBER_ROLE_CODE', 'کد نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'NAME_FA', 'عنوان فارسی نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'NAME_EN', 'عنوان انگلیسی نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'DESCRIPTION_FA', 'توضیحات فارسی نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'SORT_ORDER', 'ترتیب نمایش نقش عضو گروه در فهرست‌های مرجع');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'IS_ACTIVE', 'نشانگر فعال بودن نقش عضو گروه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'PARENT_CODE', 'کد والد نقش عضو گروه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'VALID_FROM', 'تاریخ شروع اعتبار نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'VALID_TO', 'تاریخ پایان اعتبار نقش عضو گروه');
  set_column_comment('REF_GROUP_MEMBER_ROLE', 'RECORD_VERSION', 'شماره نسخه رکورد نقش عضو گروه برای کنترل هم‌زمانی');
  set_column_comment('REF_GROUP_TYPE', 'GROUP_TYPE_CODE', 'کد نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'NAME_FA', 'عنوان فارسی نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع گروه در فهرست‌های مرجع');
  set_column_comment('REF_GROUP_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع گروه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_GROUP_TYPE', 'PARENT_CODE', 'کد والد نوع گروه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_GROUP_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع گروه');
  set_column_comment('REF_GROUP_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع گروه برای کنترل هم‌زمانی');
  set_column_comment('REF_HASH_ALGORITHM', 'HASH_ALGORITHM_CODE', 'کد الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'NAME_FA', 'عنوان فارسی الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'NAME_EN', 'عنوان انگلیسی الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'DESCRIPTION_FA', 'توضیحات فارسی الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'SORT_ORDER', 'ترتیب نمایش الگوریتم هش در فهرست‌های مرجع');
  set_column_comment('REF_HASH_ALGORITHM', 'IS_ACTIVE', 'نشانگر فعال بودن الگوریتم هش؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_HASH_ALGORITHM', 'PARENT_CODE', 'کد والد الگوریتم هش در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_HASH_ALGORITHM', 'VALID_FROM', 'تاریخ شروع اعتبار الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'VALID_TO', 'تاریخ پایان اعتبار الگوریتم هش');
  set_column_comment('REF_HASH_ALGORITHM', 'RECORD_VERSION', 'شماره نسخه رکورد الگوریتم هش برای کنترل هم‌زمانی');
  set_column_comment('REF_IDENTIFIER_TYPE', 'IDENTIFIER_TYPE_CODE', 'کد نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'NAME_FA', 'عنوان فارسی نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع شناسه در فهرست‌های مرجع');
  set_column_comment('REF_IDENTIFIER_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع شناسه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_IDENTIFIER_TYPE', 'PARENT_CODE', 'کد والد نوع شناسه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_IDENTIFIER_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع شناسه');
  set_column_comment('REF_IDENTIFIER_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع شناسه برای کنترل هم‌زمانی');
  set_column_comment('REF_INQUIRY_RESULT', 'INQUIRY_RESULT_CODE', 'کد نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'NAME_FA', 'عنوان فارسی نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'NAME_EN', 'عنوان انگلیسی نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'DESCRIPTION_FA', 'توضیحات فارسی نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'SORT_ORDER', 'ترتیب نمایش نتیجه استعلام در فهرست‌های مرجع');
  set_column_comment('REF_INQUIRY_RESULT', 'IS_ACTIVE', 'نشانگر فعال بودن نتیجه استعلام؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_INQUIRY_RESULT', 'PARENT_CODE', 'کد والد نتیجه استعلام در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_INQUIRY_RESULT', 'VALID_FROM', 'تاریخ شروع اعتبار نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'VALID_TO', 'تاریخ پایان اعتبار نتیجه استعلام');
  set_column_comment('REF_INQUIRY_RESULT', 'RECORD_VERSION', 'شماره نسخه رکورد نتیجه استعلام برای کنترل هم‌زمانی');
  set_column_comment('REF_INQUIRY_TYPE', 'INQUIRY_TYPE_CODE', 'کد نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'NAME_FA', 'عنوان فارسی نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع استعلام در فهرست‌های مرجع');
  set_column_comment('REF_INQUIRY_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع استعلام؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_INQUIRY_TYPE', 'PARENT_CODE', 'کد والد نوع استعلام در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_INQUIRY_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع استعلام');
  set_column_comment('REF_INQUIRY_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع استعلام برای کنترل هم‌زمانی');
  set_column_comment('REF_INTERACTION_OUTCOME', 'INTERACTION_OUTCOME_CODE', 'کد نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'NAME_FA', 'عنوان فارسی نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'NAME_EN', 'عنوان انگلیسی نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'DESCRIPTION_FA', 'توضیحات فارسی نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'SORT_ORDER', 'ترتیب نمایش نتیجه تعامل در فهرست‌های مرجع');
  set_column_comment('REF_INTERACTION_OUTCOME', 'IS_ACTIVE', 'نشانگر فعال بودن نتیجه تعامل؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_INTERACTION_OUTCOME', 'PARENT_CODE', 'کد والد نتیجه تعامل در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_INTERACTION_OUTCOME', 'VALID_FROM', 'تاریخ شروع اعتبار نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'VALID_TO', 'تاریخ پایان اعتبار نتیجه تعامل');
  set_column_comment('REF_INTERACTION_OUTCOME', 'RECORD_VERSION', 'شماره نسخه رکورد نتیجه تعامل برای کنترل هم‌زمانی');
  set_column_comment('REF_INTERACTION_TYPE', 'INTERACTION_TYPE_CODE', 'کد نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'NAME_FA', 'عنوان فارسی نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع تعامل در فهرست‌های مرجع');
  set_column_comment('REF_INTERACTION_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع تعامل؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_INTERACTION_TYPE', 'PARENT_CODE', 'کد والد نوع تعامل در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_INTERACTION_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع تعامل');
  set_column_comment('REF_INTERACTION_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع تعامل برای کنترل هم‌زمانی');
  set_column_comment('REF_ISIC_ACTIVITY', 'ISIC_CODE', 'کد ISIC');
  set_column_comment('REF_ISIC_ACTIVITY', 'NAME_FA', 'عنوان فارسی فعالیت اقتصادی (ISIC)');
  set_column_comment('REF_ISIC_ACTIVITY', 'NAME_EN', 'عنوان انگلیسی فعالیت اقتصادی (ISIC)');
  set_column_comment('REF_ISIC_ACTIVITY', 'DESCRIPTION_FA', 'توضیحات فارسی فعالیت اقتصادی (ISIC)');
  set_column_comment('REF_ISIC_ACTIVITY', 'SORT_ORDER', 'ترتیب نمایش فعالیت اقتصادی (ISIC) در فهرست‌های مرجع');
  set_column_comment('REF_ISIC_ACTIVITY', 'IS_ACTIVE', 'نشانگر فعال بودن فعالیت اقتصادی (ISIC)؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ISIC_ACTIVITY', 'PARENT_CODE', 'کد والد فعالیت اقتصادی (ISIC) در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ISIC_ACTIVITY', 'VALID_FROM', 'تاریخ شروع اعتبار فعالیت اقتصادی (ISIC)');
  set_column_comment('REF_ISIC_ACTIVITY', 'VALID_TO', 'تاریخ پایان اعتبار فعالیت اقتصادی (ISIC)');
  set_column_comment('REF_ISIC_ACTIVITY', 'RECORD_VERSION', 'شماره نسخه رکورد فعالیت اقتصادی (ISIC) برای کنترل هم‌زمانی');
  set_column_comment('REF_ISSUING_AUTHORITY', 'ISSUING_AUTHORITY_CODE', 'کد مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'NAME_FA', 'عنوان فارسی مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'NAME_EN', 'عنوان انگلیسی مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'DESCRIPTION_FA', 'توضیحات فارسی مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'SORT_ORDER', 'ترتیب نمایش مرجع صادرکننده در فهرست‌های مرجع');
  set_column_comment('REF_ISSUING_AUTHORITY', 'IS_ACTIVE', 'نشانگر فعال بودن مرجع صادرکننده؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ISSUING_AUTHORITY', 'PARENT_CODE', 'کد والد مرجع صادرکننده در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ISSUING_AUTHORITY', 'VALID_FROM', 'تاریخ شروع اعتبار مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'VALID_TO', 'تاریخ پایان اعتبار مرجع صادرکننده');
  set_column_comment('REF_ISSUING_AUTHORITY', 'RECORD_VERSION', 'شماره نسخه رکورد مرجع صادرکننده برای کنترل هم‌زمانی');
  set_column_comment('REF_JOURNEY', 'JOURNEY_CODE', 'کد سفر مشتری');
  set_column_comment('REF_JOURNEY', 'NAME_FA', 'عنوان فارسی سفر مشتری');
  set_column_comment('REF_JOURNEY', 'NAME_EN', 'عنوان انگلیسی سفر مشتری');
  set_column_comment('REF_JOURNEY', 'DESCRIPTION_FA', 'توضیحات فارسی سفر مشتری');
  set_column_comment('REF_JOURNEY', 'SORT_ORDER', 'ترتیب نمایش سفر مشتری در فهرست‌های مرجع');
  set_column_comment('REF_JOURNEY', 'IS_ACTIVE', 'نشانگر فعال بودن سفر مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_JOURNEY', 'PARENT_CODE', 'کد والد سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_JOURNEY', 'VALID_FROM', 'تاریخ شروع اعتبار سفر مشتری');
  set_column_comment('REF_JOURNEY', 'VALID_TO', 'تاریخ پایان اعتبار سفر مشتری');
  set_column_comment('REF_JOURNEY', 'RECORD_VERSION', 'شماره نسخه رکورد سفر مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'JOURNEY_EVENT_TYPE_CODE', 'کد نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'NAME_FA', 'عنوان فارسی نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع رویداد سفر مشتری در فهرست‌های مرجع');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع رویداد سفر مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'PARENT_CODE', 'کد والد نوع رویداد سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع رویداد سفر مشتری');
  set_column_comment('REF_JOURNEY_EVENT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع رویداد سفر مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_JOURNEY_STAGE', 'JOURNEY_STAGE_CODE', 'کد مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'NAME_FA', 'عنوان فارسی مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'NAME_EN', 'عنوان انگلیسی مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'DESCRIPTION_FA', 'توضیحات فارسی مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'SORT_ORDER', 'ترتیب نمایش مرحله سفر مشتری در فهرست‌های مرجع');
  set_column_comment('REF_JOURNEY_STAGE', 'IS_ACTIVE', 'نشانگر فعال بودن مرحله سفر مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_JOURNEY_STAGE', 'PARENT_CODE', 'کد والد مرحله سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_JOURNEY_STAGE', 'VALID_FROM', 'تاریخ شروع اعتبار مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'VALID_TO', 'تاریخ پایان اعتبار مرحله سفر مشتری');
  set_column_comment('REF_JOURNEY_STAGE', 'RECORD_VERSION', 'شماره نسخه رکورد مرحله سفر مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_KYC_TYPE', 'KYC_TYPE_CODE', 'کد نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'NAME_FA', 'عنوان فارسی نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع KYC در فهرست‌های مرجع');
  set_column_comment('REF_KYC_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع KYC؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_KYC_TYPE', 'PARENT_CODE', 'کد والد نوع KYC در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_KYC_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع KYC');
  set_column_comment('REF_KYC_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع KYC برای کنترل هم‌زمانی');
  set_column_comment('REF_LEGAL_CAPACITY', 'LEGAL_CAPACITY_CODE', 'کد اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'NAME_FA', 'عنوان فارسی اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'NAME_EN', 'عنوان انگلیسی اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'DESCRIPTION_FA', 'توضیحات فارسی اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'SORT_ORDER', 'ترتیب نمایش اهلیت قانونی در فهرست‌های مرجع');
  set_column_comment('REF_LEGAL_CAPACITY', 'IS_ACTIVE', 'نشانگر فعال بودن اهلیت قانونی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_LEGAL_CAPACITY', 'PARENT_CODE', 'کد والد اهلیت قانونی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_LEGAL_CAPACITY', 'VALID_FROM', 'تاریخ شروع اعتبار اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'VALID_TO', 'تاریخ پایان اعتبار اهلیت قانونی');
  set_column_comment('REF_LEGAL_CAPACITY', 'RECORD_VERSION', 'شماره نسخه رکورد اهلیت قانونی برای کنترل هم‌زمانی');
  set_column_comment('REF_LEGAL_FORM', 'LEGAL_FORM_CODE', 'کد نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'NAME_FA', 'عنوان فارسی نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'NAME_EN', 'عنوان انگلیسی نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'DESCRIPTION_FA', 'توضیحات فارسی نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'SORT_ORDER', 'ترتیب نمایش نوع شخصیت حقوقی در فهرست‌های مرجع');
  set_column_comment('REF_LEGAL_FORM', 'IS_ACTIVE', 'نشانگر فعال بودن نوع شخصیت حقوقی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_LEGAL_FORM', 'PARENT_CODE', 'کد والد نوع شخصیت حقوقی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_LEGAL_FORM', 'VALID_FROM', 'تاریخ شروع اعتبار نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'VALID_TO', 'تاریخ پایان اعتبار نوع شخصیت حقوقی');
  set_column_comment('REF_LEGAL_FORM', 'RECORD_VERSION', 'شماره نسخه رکورد نوع شخصیت حقوقی برای کنترل هم‌زمانی');
  set_column_comment('REF_LICENSE_TYPE', 'LICENSE_TYPE_CODE', 'کد نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'NAME_FA', 'عنوان فارسی نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع مجوز در فهرست‌های مرجع');
  set_column_comment('REF_LICENSE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع مجوز؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_LICENSE_TYPE', 'PARENT_CODE', 'کد والد نوع مجوز در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_LICENSE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع مجوز');
  set_column_comment('REF_LICENSE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع مجوز برای کنترل هم‌زمانی');
  set_column_comment('REF_LIFE_STATUS', 'LIFE_STATUS_CODE', 'کد وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت حیات در فهرست‌های مرجع');
  set_column_comment('REF_LIFE_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت حیات؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_LIFE_STATUS', 'PARENT_CODE', 'کد والد وضعیت حیات در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_LIFE_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت حیات');
  set_column_comment('REF_LIFE_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت حیات برای کنترل هم‌زمانی');
  set_column_comment('REF_LIMIT_TYPE', 'LIMIT_TYPE_CODE', 'کد نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'NAME_FA', 'عنوان فارسی نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع حد در فهرست‌های مرجع');
  set_column_comment('REF_LIMIT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع حد؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_LIMIT_TYPE', 'PARENT_CODE', 'کد والد نوع حد در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_LIMIT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع حد');
  set_column_comment('REF_LIMIT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع حد برای کنترل هم‌زمانی');
  set_column_comment('REF_MARITAL_STATUS', 'MARITAL_STATUS_CODE', 'کد وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت تأهل در فهرست‌های مرجع');
  set_column_comment('REF_MARITAL_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت تأهل؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_MARITAL_STATUS', 'PARENT_CODE', 'کد والد وضعیت تأهل در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_MARITAL_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت تأهل');
  set_column_comment('REF_MARITAL_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت تأهل برای کنترل هم‌زمانی');
  set_column_comment('REF_METRIC', 'METRIC_CODE', 'کد شاخص');
  set_column_comment('REF_METRIC', 'NAME_FA', 'عنوان فارسی شاخص تحلیلی مشتری');
  set_column_comment('REF_METRIC', 'NAME_EN', 'عنوان انگلیسی شاخص تحلیلی مشتری');
  set_column_comment('REF_METRIC', 'DESCRIPTION_FA', 'توضیحات فارسی شاخص تحلیلی مشتری');
  set_column_comment('REF_METRIC', 'SORT_ORDER', 'ترتیب نمایش شاخص تحلیلی مشتری در فهرست‌های مرجع');
  set_column_comment('REF_METRIC', 'IS_ACTIVE', 'نشانگر فعال بودن شاخص تحلیلی مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_METRIC', 'PARENT_CODE', 'کد والد شاخص تحلیلی مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_METRIC', 'VALID_FROM', 'تاریخ شروع اعتبار شاخص تحلیلی مشتری');
  set_column_comment('REF_METRIC', 'VALID_TO', 'تاریخ پایان اعتبار شاخص تحلیلی مشتری');
  set_column_comment('REF_METRIC', 'RECORD_VERSION', 'شماره نسخه رکورد شاخص تحلیلی مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_METRIC_UNIT', 'METRIC_UNIT_CODE', 'کد واحد اندازه‌گیری');
  set_column_comment('REF_METRIC_UNIT', 'NAME_FA', 'عنوان فارسی واحد اندازه‌گیری شاخص');
  set_column_comment('REF_METRIC_UNIT', 'NAME_EN', 'عنوان انگلیسی واحد اندازه‌گیری شاخص');
  set_column_comment('REF_METRIC_UNIT', 'DESCRIPTION_FA', 'توضیحات فارسی واحد اندازه‌گیری شاخص');
  set_column_comment('REF_METRIC_UNIT', 'SORT_ORDER', 'ترتیب نمایش واحد اندازه‌گیری شاخص در فهرست‌های مرجع');
  set_column_comment('REF_METRIC_UNIT', 'IS_ACTIVE', 'نشانگر فعال بودن واحد اندازه‌گیری شاخص؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_METRIC_UNIT', 'PARENT_CODE', 'کد والد واحد اندازه‌گیری شاخص در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_METRIC_UNIT', 'VALID_FROM', 'تاریخ شروع اعتبار واحد اندازه‌گیری شاخص');
  set_column_comment('REF_METRIC_UNIT', 'VALID_TO', 'تاریخ پایان اعتبار واحد اندازه‌گیری شاخص');
  set_column_comment('REF_METRIC_UNIT', 'RECORD_VERSION', 'شماره نسخه رکورد واحد اندازه‌گیری شاخص برای کنترل هم‌زمانی');
  set_column_comment('REF_MODEL', 'MODEL_CODE', 'کد مدل تحلیلی');
  set_column_comment('REF_MODEL', 'NAME_FA', 'عنوان فارسی مدل تحلیلی');
  set_column_comment('REF_MODEL', 'NAME_EN', 'عنوان انگلیسی مدل تحلیلی');
  set_column_comment('REF_MODEL', 'DESCRIPTION_FA', 'توضیحات فارسی مدل تحلیلی');
  set_column_comment('REF_MODEL', 'SORT_ORDER', 'ترتیب نمایش مدل تحلیلی در فهرست‌های مرجع');
  set_column_comment('REF_MODEL', 'IS_ACTIVE', 'نشانگر فعال بودن مدل تحلیلی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_MODEL', 'PARENT_CODE', 'کد والد مدل تحلیلی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_MODEL', 'VALID_FROM', 'تاریخ شروع اعتبار مدل تحلیلی');
  set_column_comment('REF_MODEL', 'VALID_TO', 'تاریخ پایان اعتبار مدل تحلیلی');
  set_column_comment('REF_MODEL', 'RECORD_VERSION', 'شماره نسخه رکورد مدل تحلیلی برای کنترل هم‌زمانی');
  set_column_comment('REF_NAME_TYPE', 'NAME_TYPE_CODE', 'کد نوع نام');
  set_column_comment('REF_NAME_TYPE', 'NAME_FA', 'عنوان فارسی نوع نام');
  set_column_comment('REF_NAME_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع نام');
  set_column_comment('REF_NAME_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع نام');
  set_column_comment('REF_NAME_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع نام در فهرست‌های مرجع');
  set_column_comment('REF_NAME_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع نام؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_NAME_TYPE', 'PARENT_CODE', 'کد والد نوع نام در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_NAME_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع نام');
  set_column_comment('REF_NAME_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع نام');
  set_column_comment('REF_NAME_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع نام برای کنترل هم‌زمانی');
  set_column_comment('REF_OCCUPATION', 'OCCUPATION_CODE', 'کد شغل');
  set_column_comment('REF_OCCUPATION', 'NAME_FA', 'عنوان فارسی شغل');
  set_column_comment('REF_OCCUPATION', 'NAME_EN', 'عنوان انگلیسی شغل');
  set_column_comment('REF_OCCUPATION', 'DESCRIPTION_FA', 'توضیحات فارسی شغل');
  set_column_comment('REF_OCCUPATION', 'SORT_ORDER', 'ترتیب نمایش شغل در فهرست‌های مرجع');
  set_column_comment('REF_OCCUPATION', 'IS_ACTIVE', 'نشانگر فعال بودن شغل؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_OCCUPATION', 'PARENT_CODE', 'کد والد شغل در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_OCCUPATION', 'VALID_FROM', 'تاریخ شروع اعتبار شغل');
  set_column_comment('REF_OCCUPATION', 'VALID_TO', 'تاریخ پایان اعتبار شغل');
  set_column_comment('REF_OCCUPATION', 'RECORD_VERSION', 'شماره نسخه رکورد شغل برای کنترل هم‌زمانی');
  set_column_comment('REF_OFFER', 'OFFER_CODE', 'کد پیشنهاد');
  set_column_comment('REF_OFFER', 'NAME_FA', 'عنوان فارسی پیشنهاد محصول/خدمت');
  set_column_comment('REF_OFFER', 'NAME_EN', 'عنوان انگلیسی پیشنهاد محصول/خدمت');
  set_column_comment('REF_OFFER', 'DESCRIPTION_FA', 'توضیحات فارسی پیشنهاد محصول/خدمت');
  set_column_comment('REF_OFFER', 'SORT_ORDER', 'ترتیب نمایش پیشنهاد محصول/خدمت در فهرست‌های مرجع');
  set_column_comment('REF_OFFER', 'IS_ACTIVE', 'نشانگر فعال بودن پیشنهاد محصول/خدمت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_OFFER', 'PARENT_CODE', 'کد والد پیشنهاد محصول/خدمت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_OFFER', 'VALID_FROM', 'تاریخ شروع اعتبار پیشنهاد محصول/خدمت');
  set_column_comment('REF_OFFER', 'VALID_TO', 'تاریخ پایان اعتبار پیشنهاد محصول/خدمت');
  set_column_comment('REF_OFFER', 'RECORD_VERSION', 'شماره نسخه رکورد پیشنهاد محصول/خدمت برای کنترل هم‌زمانی');
  set_column_comment('REF_OFFICER_ROLE', 'OFFICER_ROLE_CODE', 'کد سمت/نقش');
  set_column_comment('REF_OFFICER_ROLE', 'NAME_FA', 'عنوان فارسی سمت/نقش سازمانی');
  set_column_comment('REF_OFFICER_ROLE', 'NAME_EN', 'عنوان انگلیسی سمت/نقش سازمانی');
  set_column_comment('REF_OFFICER_ROLE', 'DESCRIPTION_FA', 'توضیحات فارسی سمت/نقش سازمانی');
  set_column_comment('REF_OFFICER_ROLE', 'SORT_ORDER', 'ترتیب نمایش سمت/نقش سازمانی در فهرست‌های مرجع');
  set_column_comment('REF_OFFICER_ROLE', 'IS_ACTIVE', 'نشانگر فعال بودن سمت/نقش سازمانی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_OFFICER_ROLE', 'PARENT_CODE', 'کد والد سمت/نقش سازمانی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_OFFICER_ROLE', 'VALID_FROM', 'تاریخ شروع اعتبار سمت/نقش سازمانی');
  set_column_comment('REF_OFFICER_ROLE', 'VALID_TO', 'تاریخ پایان اعتبار سمت/نقش سازمانی');
  set_column_comment('REF_OFFICER_ROLE', 'RECORD_VERSION', 'شماره نسخه رکورد سمت/نقش سازمانی برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'PARTY_CONSENT_PURPOSE_CODE', 'کد هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'NAME_FA', 'عنوان فارسی هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'NAME_EN', 'عنوان انگلیسی هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'DESCRIPTION_FA', 'توضیحات فارسی هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'SORT_ORDER', 'ترتیب نمایش هدف رضایت Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'IS_ACTIVE', 'نشانگر فعال بودن هدف رضایت Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'PARENT_CODE', 'کد والد هدف رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'VALID_FROM', 'تاریخ شروع اعتبار هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'VALID_TO', 'تاریخ پایان اعتبار هدف رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_PURPOSE', 'RECORD_VERSION', 'شماره نسخه رکورد هدف رضایت Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'CONSENT_STATUS_CODE', 'کد وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت رضایت Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت رضایت Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'PARENT_CODE', 'کد والد وضعیت رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت رضایت Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'CONSENT_TYPE_CODE', 'کد نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'NAME_FA', 'عنوان فارسی نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع رضایت Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع رضایت Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'PARENT_CODE', 'کد والد نوع رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع رضایت Party');
  set_column_comment('REF_PARTY_CONSENT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع رضایت Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'LIFECYCLE_STATUS_CODE', 'کد وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت چرخه‌حیات Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت چرخه‌حیات Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'PARENT_CODE', 'کد والد وضعیت چرخه‌حیات Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت چرخه‌حیات Party');
  set_column_comment('REF_PARTY_LIFECYCLE_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت چرخه‌حیات Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_STATUS_REASON', 'REASON_CODE', 'کد دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'NAME_FA', 'عنوان فارسی دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'NAME_EN', 'عنوان انگلیسی دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'DESCRIPTION_FA', 'توضیحات فارسی دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'SORT_ORDER', 'ترتیب نمایش دلیل وضعیت Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_STATUS_REASON', 'IS_ACTIVE', 'نشانگر فعال بودن دلیل وضعیت Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_STATUS_REASON', 'PARENT_CODE', 'کد والد دلیل وضعیت Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_STATUS_REASON', 'VALID_FROM', 'تاریخ شروع اعتبار دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'VALID_TO', 'تاریخ پایان اعتبار دلیل وضعیت Party');
  set_column_comment('REF_PARTY_STATUS_REASON', 'RECORD_VERSION', 'شماره نسخه رکورد دلیل وضعیت Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PARTY_TYPE', 'PARTY_TYPE_CODE', 'کد نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'NAME_FA', 'عنوان فارسی نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع Party در فهرست‌های مرجع');
  set_column_comment('REF_PARTY_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع Party؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PARTY_TYPE', 'PARENT_CODE', 'کد والد نوع Party در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PARTY_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع Party');
  set_column_comment('REF_PARTY_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع Party برای کنترل هم‌زمانی');
  set_column_comment('REF_PERIOD', 'PERIOD_CODE', 'کد دوره');
  set_column_comment('REF_PERIOD', 'NAME_FA', 'عنوان فارسی دوره زمانی');
  set_column_comment('REF_PERIOD', 'NAME_EN', 'عنوان انگلیسی دوره زمانی');
  set_column_comment('REF_PERIOD', 'DESCRIPTION_FA', 'توضیحات فارسی دوره زمانی');
  set_column_comment('REF_PERIOD', 'SORT_ORDER', 'ترتیب نمایش دوره زمانی در فهرست‌های مرجع');
  set_column_comment('REF_PERIOD', 'IS_ACTIVE', 'نشانگر فعال بودن دوره زمانی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PERIOD', 'PARENT_CODE', 'کد والد دوره زمانی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PERIOD', 'VALID_FROM', 'تاریخ شروع اعتبار دوره زمانی');
  set_column_comment('REF_PERIOD', 'VALID_TO', 'تاریخ پایان اعتبار دوره زمانی');
  set_column_comment('REF_PERIOD', 'RECORD_VERSION', 'شماره نسخه رکورد دوره زمانی برای کنترل هم‌زمانی');
  set_column_comment('REF_PREFERENCE_TYPE', 'PREFERENCE_TYPE_CODE', 'کد نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'NAME_FA', 'عنوان فارسی نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع ترجیح مشتری در فهرست‌های مرجع');
  set_column_comment('REF_PREFERENCE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع ترجیح مشتری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PREFERENCE_TYPE', 'PARENT_CODE', 'کد والد نوع ترجیح مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PREFERENCE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع ترجیح مشتری');
  set_column_comment('REF_PREFERENCE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع ترجیح مشتری برای کنترل هم‌زمانی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'PRODUCT_HOLDING_STATUS_CODE', 'کد وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت رابطه محصولی در فهرست‌های مرجع');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت رابطه محصولی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'PARENT_CODE', 'کد والد وضعیت رابطه محصولی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت رابطه محصولی');
  set_column_comment('REF_PRODUCT_HOLDING_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت رابطه محصولی برای کنترل هم‌زمانی');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'PRODUCT_RELATIONSHIP_ROLE_CODE', 'کد نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'NAME_FA', 'عنوان فارسی نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'NAME_EN', 'عنوان انگلیسی نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'DESCRIPTION_FA', 'توضیحات فارسی نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'SORT_ORDER', 'ترتیب نمایش نقش مشتری نسبت به محصول در فهرست‌های مرجع');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'IS_ACTIVE', 'نشانگر فعال بودن نقش مشتری نسبت به محصول؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'PARENT_CODE', 'کد والد نقش مشتری نسبت به محصول در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'VALID_FROM', 'تاریخ شروع اعتبار نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'VALID_TO', 'تاریخ پایان اعتبار نقش مشتری نسبت به محصول');
  set_column_comment('REF_PRODUCT_RELATIONSHIP_ROLE', 'RECORD_VERSION', 'شماره نسخه رکورد نقش مشتری نسبت به محصول برای کنترل هم‌زمانی');
  set_column_comment('REF_PRODUCT_TYPE', 'PRODUCT_TYPE_CODE', 'کد نوع محصول/خدمت');
  set_column_comment('REF_PRODUCT_TYPE', 'NAME_FA', 'عنوان فارسی نوع محصول/خدمت بانکی');
  set_column_comment('REF_PRODUCT_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع محصول/خدمت بانکی');
  set_column_comment('REF_PRODUCT_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع محصول/خدمت بانکی');
  set_column_comment('REF_PRODUCT_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع محصول/خدمت بانکی در فهرست‌های مرجع');
  set_column_comment('REF_PRODUCT_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع محصول/خدمت بانکی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_PRODUCT_TYPE', 'PARENT_CODE', 'کد والد نوع محصول/خدمت بانکی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_PRODUCT_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع محصول/خدمت بانکی');
  set_column_comment('REF_PRODUCT_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع محصول/خدمت بانکی');
  set_column_comment('REF_PRODUCT_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع محصول/خدمت بانکی برای کنترل هم‌زمانی');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'RECOMMENDATION_STATUS_CODE', 'کد وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت پیشنهاد در فهرست‌های مرجع');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت پیشنهاد؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'PARENT_CODE', 'کد والد وضعیت پیشنهاد در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت پیشنهاد برای کنترل هم‌زمانی');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'RECOMMENDATION_TYPE_CODE', 'کد نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'NAME_FA', 'عنوان فارسی نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع پیشنهاد در فهرست‌های مرجع');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع پیشنهاد؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'PARENT_CODE', 'کد والد نوع پیشنهاد در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع پیشنهاد');
  set_column_comment('REF_RECOMMENDATION_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع پیشنهاد برای کنترل هم‌زمانی');
  set_column_comment('REF_REFERENCE_TYPE', 'REFERENCE_TYPE_CODE', 'کد نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'NAME_FA', 'عنوان فارسی نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع مرجع مرتبط در فهرست‌های مرجع');
  set_column_comment('REF_REFERENCE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع مرجع مرتبط؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_REFERENCE_TYPE', 'PARENT_CODE', 'کد والد نوع مرجع مرتبط در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_REFERENCE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع مرجع مرتبط');
  set_column_comment('REF_REFERENCE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع مرجع مرتبط برای کنترل هم‌زمانی');
  set_column_comment('REF_RESIDENCE_STATUS', 'RESIDENCE_STATUS_CODE', 'کد وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت اقامت در فهرست‌های مرجع');
  set_column_comment('REF_RESIDENCE_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت اقامت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RESIDENCE_STATUS', 'PARENT_CODE', 'کد والد وضعیت اقامت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RESIDENCE_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت اقامت');
  set_column_comment('REF_RESIDENCE_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت اقامت برای کنترل هم‌زمانی');
  set_column_comment('REF_RESTRICTION_REASON', 'REASON_CODE', 'کد دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'NAME_FA', 'عنوان فارسی دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'NAME_EN', 'عنوان انگلیسی دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'DESCRIPTION_FA', 'توضیحات فارسی دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'SORT_ORDER', 'ترتیب نمایش دلیل محدودیت در فهرست‌های مرجع');
  set_column_comment('REF_RESTRICTION_REASON', 'IS_ACTIVE', 'نشانگر فعال بودن دلیل محدودیت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RESTRICTION_REASON', 'PARENT_CODE', 'کد والد دلیل محدودیت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RESTRICTION_REASON', 'VALID_FROM', 'تاریخ شروع اعتبار دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'VALID_TO', 'تاریخ پایان اعتبار دلیل محدودیت');
  set_column_comment('REF_RESTRICTION_REASON', 'RECORD_VERSION', 'شماره نسخه رکورد دلیل محدودیت برای کنترل هم‌زمانی');
  set_column_comment('REF_RESTRICTION_TYPE', 'RESTRICTION_TYPE_CODE', 'کد نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'NAME_FA', 'عنوان فارسی نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع محدودیت در فهرست‌های مرجع');
  set_column_comment('REF_RESTRICTION_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع محدودیت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RESTRICTION_TYPE', 'PARENT_CODE', 'کد والد نوع محدودیت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RESTRICTION_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع محدودیت');
  set_column_comment('REF_RESTRICTION_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع محدودیت برای کنترل هم‌زمانی');
  set_column_comment('REF_RISK_LEVEL', 'RISK_LEVEL_CODE', 'کد سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'NAME_FA', 'عنوان فارسی سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'NAME_EN', 'عنوان انگلیسی سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'DESCRIPTION_FA', 'توضیحات فارسی سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'SORT_ORDER', 'ترتیب نمایش سطح ریسک در فهرست‌های مرجع');
  set_column_comment('REF_RISK_LEVEL', 'IS_ACTIVE', 'نشانگر فعال بودن سطح ریسک؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RISK_LEVEL', 'PARENT_CODE', 'کد والد سطح ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RISK_LEVEL', 'VALID_FROM', 'تاریخ شروع اعتبار سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'VALID_TO', 'تاریخ پایان اعتبار سطح ریسک');
  set_column_comment('REF_RISK_LEVEL', 'RECORD_VERSION', 'شماره نسخه رکورد سطح ریسک برای کنترل هم‌زمانی');
  set_column_comment('REF_RISK_MODEL', 'MODEL_CODE', 'کد مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'NAME_FA', 'عنوان فارسی مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'NAME_EN', 'عنوان انگلیسی مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'DESCRIPTION_FA', 'توضیحات فارسی مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'MODEL_VERSION', 'نسخه فعال مدل ریسک که هنگام ثبت ارزیابی ریسک توسط سامانه استفاده می‌شود');
  set_column_comment('REF_RISK_MODEL', 'MIN_SCORE', 'حداقل امتیاز مجاز برای ارزیابی با این مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'MAX_SCORE', 'حداکثر امتیاز مجاز برای ارزیابی با این مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'SORT_ORDER', 'ترتیب نمایش مدل ریسک در فهرست‌های مرجع');
  set_column_comment('REF_RISK_MODEL', 'IS_ACTIVE', 'نشانگر فعال بودن مدل ریسک؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RISK_MODEL', 'PARENT_CODE', 'کد والد مدل ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RISK_MODEL', 'VALID_FROM', 'تاریخ شروع اعتبار مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'VALID_TO', 'تاریخ پایان اعتبار مدل ریسک');
  set_column_comment('REF_RISK_MODEL', 'RECORD_VERSION', 'شماره نسخه رکورد مدل ریسک برای کنترل هم‌زمانی');
  set_column_comment('REF_RISK_TYPE', 'RISK_TYPE_CODE', 'کد نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'NAME_FA', 'عنوان فارسی نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع ریسک در فهرست‌های مرجع');
  set_column_comment('REF_RISK_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع ریسک؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_RISK_TYPE', 'PARENT_CODE', 'کد والد نوع ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_RISK_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع ریسک');
  set_column_comment('REF_RISK_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع ریسک برای کنترل هم‌زمانی');
  set_column_comment('REF_ROLE_TYPE', 'ROLE_TYPE_CODE', 'کد نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'NAME_FA', 'عنوان فارسی نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع نقش در فهرست‌های مرجع');
  set_column_comment('REF_ROLE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع نقش؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_ROLE_TYPE', 'PARENT_CODE', 'کد والد نوع نقش در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_ROLE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع نقش');
  set_column_comment('REF_ROLE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع نقش برای کنترل هم‌زمانی');
  set_column_comment('REF_SCORE_BAND', 'SCORE_BAND_CODE', 'کد طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'NAME_FA', 'عنوان فارسی طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'NAME_EN', 'عنوان انگلیسی طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'DESCRIPTION_FA', 'توضیحات فارسی طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'SORT_ORDER', 'ترتیب نمایش طبقه امتیاز در فهرست‌های مرجع');
  set_column_comment('REF_SCORE_BAND', 'IS_ACTIVE', 'نشانگر فعال بودن طبقه امتیاز؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCORE_BAND', 'PARENT_CODE', 'کد والد طبقه امتیاز در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCORE_BAND', 'VALID_FROM', 'تاریخ شروع اعتبار طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'VALID_TO', 'تاریخ پایان اعتبار طبقه امتیاز');
  set_column_comment('REF_SCORE_BAND', 'RECORD_VERSION', 'شماره نسخه رکورد طبقه امتیاز برای کنترل هم‌زمانی');
  set_column_comment('REF_SCORE_TYPE', 'SCORE_TYPE_CODE', 'کد نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'NAME_FA', 'عنوان فارسی نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع امتیاز در فهرست‌های مرجع');
  set_column_comment('REF_SCORE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع امتیاز؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCORE_TYPE', 'PARENT_CODE', 'کد والد نوع امتیاز در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCORE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع امتیاز');
  set_column_comment('REF_SCORE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع امتیاز برای کنترل هم‌زمانی');
  set_column_comment('REF_SCREENING_LIST', 'SOURCE_LIST_CODE', 'کد فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'NAME_FA', 'عنوان فارسی فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'NAME_EN', 'عنوان انگلیسی فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'DESCRIPTION_FA', 'توضیحات فارسی فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'SORT_ORDER', 'ترتیب نمایش فهرست پایش و تحریم در فهرست‌های مرجع');
  set_column_comment('REF_SCREENING_LIST', 'IS_ACTIVE', 'نشانگر فعال بودن فهرست پایش و تحریم؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCREENING_LIST', 'PARENT_CODE', 'کد والد فهرست پایش و تحریم در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCREENING_LIST', 'VALID_FROM', 'تاریخ شروع اعتبار فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'VALID_TO', 'تاریخ پایان اعتبار فهرست پایش و تحریم');
  set_column_comment('REF_SCREENING_LIST', 'RECORD_VERSION', 'شماره نسخه رکورد فهرست پایش و تحریم برای کنترل هم‌زمانی');
  set_column_comment('REF_SCREENING_PROVIDER', 'PROVIDER_CODE', 'کد ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'NAME_FA', 'عنوان فارسی ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'NAME_EN', 'عنوان انگلیسی ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'DESCRIPTION_FA', 'توضیحات فارسی ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'SORT_ORDER', 'ترتیب نمایش ارائه‌دهنده سرویس پایش در فهرست‌های مرجع');
  set_column_comment('REF_SCREENING_PROVIDER', 'IS_ACTIVE', 'نشانگر فعال بودن ارائه‌دهنده سرویس پایش؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCREENING_PROVIDER', 'PARENT_CODE', 'کد والد ارائه‌دهنده سرویس پایش در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCREENING_PROVIDER', 'VALID_FROM', 'تاریخ شروع اعتبار ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'VALID_TO', 'تاریخ پایان اعتبار ارائه‌دهنده سرویس پایش');
  set_column_comment('REF_SCREENING_PROVIDER', 'RECORD_VERSION', 'شماره نسخه رکورد ارائه‌دهنده سرویس پایش برای کنترل هم‌زمانی');
  set_column_comment('REF_SCREENING_TYPE', 'SCREENING_TYPE_CODE', 'کد نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'NAME_FA', 'عنوان فارسی نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع پایش در فهرست‌های مرجع');
  set_column_comment('REF_SCREENING_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع پایش؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCREENING_TYPE', 'PARENT_CODE', 'کد والد نوع پایش در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCREENING_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع پایش');
  set_column_comment('REF_SCREENING_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع پایش برای کنترل هم‌زمانی');
  set_column_comment('REF_SCRIPT', 'SCRIPT_CODE', 'کد خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'NAME_FA', 'عنوان فارسی خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'NAME_EN', 'عنوان انگلیسی خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'DESCRIPTION_FA', 'توضیحات فارسی خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'SORT_ORDER', 'ترتیب نمایش خط نوشتاری در فهرست‌های مرجع');
  set_column_comment('REF_SCRIPT', 'IS_ACTIVE', 'نشانگر فعال بودن خط نوشتاری؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SCRIPT', 'PARENT_CODE', 'کد والد خط نوشتاری در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SCRIPT', 'VALID_FROM', 'تاریخ شروع اعتبار خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'VALID_TO', 'تاریخ پایان اعتبار خط نوشتاری');
  set_column_comment('REF_SCRIPT', 'RECORD_VERSION', 'شماره نسخه رکورد خط نوشتاری برای کنترل هم‌زمانی');
  set_column_comment('REF_SEVERITY', 'SEVERITY_CODE', 'کد شدت');
  set_column_comment('REF_SEVERITY', 'NAME_FA', 'عنوان فارسی شدت');
  set_column_comment('REF_SEVERITY', 'NAME_EN', 'عنوان انگلیسی شدت');
  set_column_comment('REF_SEVERITY', 'DESCRIPTION_FA', 'توضیحات فارسی شدت');
  set_column_comment('REF_SEVERITY', 'SORT_ORDER', 'ترتیب نمایش شدت در فهرست‌های مرجع');
  set_column_comment('REF_SEVERITY', 'IS_ACTIVE', 'نشانگر فعال بودن شدت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SEVERITY', 'PARENT_CODE', 'کد والد شدت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SEVERITY', 'VALID_FROM', 'تاریخ شروع اعتبار شدت');
  set_column_comment('REF_SEVERITY', 'VALID_TO', 'تاریخ پایان اعتبار شدت');
  set_column_comment('REF_SEVERITY', 'RECORD_VERSION', 'شماره نسخه رکورد شدت برای کنترل هم‌زمانی');
  set_column_comment('REF_SIGNING_RULE', 'SIGNING_RULE_CODE', 'کد قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'NAME_FA', 'عنوان فارسی قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'NAME_EN', 'عنوان انگلیسی قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'DESCRIPTION_FA', 'توضیحات فارسی قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'SORT_ORDER', 'ترتیب نمایش قاعده امضا در فهرست‌های مرجع');
  set_column_comment('REF_SIGNING_RULE', 'IS_ACTIVE', 'نشانگر فعال بودن قاعده امضا؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SIGNING_RULE', 'PARENT_CODE', 'کد والد قاعده امضا در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SIGNING_RULE', 'VALID_FROM', 'تاریخ شروع اعتبار قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'VALID_TO', 'تاریخ پایان اعتبار قاعده امضا');
  set_column_comment('REF_SIGNING_RULE', 'RECORD_VERSION', 'شماره نسخه رکورد قاعده امضا برای کنترل هم‌زمانی');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'SOURCE_OF_FUNDS_CODE', 'کد منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'NAME_FA', 'عنوان فارسی منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'NAME_EN', 'عنوان انگلیسی منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'DESCRIPTION_FA', 'توضیحات فارسی منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'SORT_ORDER', 'ترتیب نمایش منبع وجوه در فهرست‌های مرجع');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'IS_ACTIVE', 'نشانگر فعال بودن منبع وجوه؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'PARENT_CODE', 'کد والد منبع وجوه در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'VALID_FROM', 'تاریخ شروع اعتبار منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'VALID_TO', 'تاریخ پایان اعتبار منبع وجوه');
  set_column_comment('REF_SOURCE_OF_FUNDS', 'RECORD_VERSION', 'شماره نسخه رکورد منبع وجوه برای کنترل هم‌زمانی');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'SOURCE_OF_WEALTH_CODE', 'کد منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'NAME_FA', 'عنوان فارسی منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'NAME_EN', 'عنوان انگلیسی منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'DESCRIPTION_FA', 'توضیحات فارسی منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'SORT_ORDER', 'ترتیب نمایش منبع ثروت در فهرست‌های مرجع');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'IS_ACTIVE', 'نشانگر فعال بودن منبع ثروت؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'PARENT_CODE', 'کد والد منبع ثروت در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'VALID_FROM', 'تاریخ شروع اعتبار منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'VALID_TO', 'تاریخ پایان اعتبار منبع ثروت');
  set_column_comment('REF_SOURCE_OF_WEALTH', 'RECORD_VERSION', 'شماره نسخه رکورد منبع ثروت برای کنترل هم‌زمانی');
  set_column_comment('REF_SOURCE_SYSTEM', 'SOURCE_SYSTEM_CODE', 'کد سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'NAME_FA', 'عنوان فارسی سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'NAME_EN', 'عنوان انگلیسی سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'DESCRIPTION_FA', 'توضیحات فارسی سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'SORT_ORDER', 'ترتیب نمایش سامانه مبدأ در فهرست‌های مرجع');
  set_column_comment('REF_SOURCE_SYSTEM', 'IS_ACTIVE', 'نشانگر فعال بودن سامانه مبدأ؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SOURCE_SYSTEM', 'PARENT_CODE', 'کد والد سامانه مبدأ در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SOURCE_SYSTEM', 'VALID_FROM', 'تاریخ شروع اعتبار سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'VALID_TO', 'تاریخ پایان اعتبار سامانه مبدأ');
  set_column_comment('REF_SOURCE_SYSTEM', 'RECORD_VERSION', 'شماره نسخه رکورد سامانه مبدأ برای کنترل هم‌زمانی');
  set_column_comment('REF_SPECIMEN_TYPE', 'SPECIMEN_TYPE_CODE', 'کد نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'NAME_FA', 'عنوان فارسی نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'NAME_EN', 'عنوان انگلیسی نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'SORT_ORDER', 'ترتیب نمایش نوع نمونه امضا در فهرست‌های مرجع');
  set_column_comment('REF_SPECIMEN_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن نوع نمونه امضا؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_SPECIMEN_TYPE', 'PARENT_CODE', 'کد والد نوع نمونه امضا در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_SPECIMEN_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار نوع نمونه امضا');
  set_column_comment('REF_SPECIMEN_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد نوع نمونه امضا برای کنترل هم‌زمانی');
  set_column_comment('REF_TAX_STATUS', 'TAX_STATUS_CODE', 'کد وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت مالیاتی در فهرست‌های مرجع');
  set_column_comment('REF_TAX_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت مالیاتی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_TAX_STATUS', 'PARENT_CODE', 'کد والد وضعیت مالیاتی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_TAX_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت مالیاتی');
  set_column_comment('REF_TAX_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت مالیاتی برای کنترل هم‌زمانی');
  set_column_comment('REF_TENURE_TYPE', 'TENURE_TYPE_CODE', 'کد وضعیت تصرف');
  set_column_comment('REF_TENURE_TYPE', 'NAME_FA', 'عنوان فارسی وضعیت تصرف نشانی');
  set_column_comment('REF_TENURE_TYPE', 'NAME_EN', 'عنوان انگلیسی وضعیت تصرف نشانی');
  set_column_comment('REF_TENURE_TYPE', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت تصرف نشانی');
  set_column_comment('REF_TENURE_TYPE', 'SORT_ORDER', 'ترتیب نمایش وضعیت تصرف نشانی در فهرست‌های مرجع');
  set_column_comment('REF_TENURE_TYPE', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت تصرف نشانی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_TENURE_TYPE', 'PARENT_CODE', 'کد والد وضعیت تصرف نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_TENURE_TYPE', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت تصرف نشانی');
  set_column_comment('REF_TENURE_TYPE', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت تصرف نشانی');
  set_column_comment('REF_TENURE_TYPE', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت تصرف نشانی برای کنترل هم‌زمانی');
  set_column_comment('REF_VERIFICATION_METHOD', 'VERIFICATION_METHOD_CODE', 'کد روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'NAME_FA', 'عنوان فارسی روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'NAME_EN', 'عنوان انگلیسی روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'DESCRIPTION_FA', 'توضیحات فارسی روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'SORT_ORDER', 'ترتیب نمایش روش اعتبارسنجی در فهرست‌های مرجع');
  set_column_comment('REF_VERIFICATION_METHOD', 'IS_ACTIVE', 'نشانگر فعال بودن روش اعتبارسنجی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_VERIFICATION_METHOD', 'PARENT_CODE', 'کد والد روش اعتبارسنجی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_VERIFICATION_METHOD', 'VALID_FROM', 'تاریخ شروع اعتبار روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'VALID_TO', 'تاریخ پایان اعتبار روش اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_METHOD', 'RECORD_VERSION', 'شماره نسخه رکورد روش اعتبارسنجی برای کنترل هم‌زمانی');
  set_column_comment('REF_VERIFICATION_STATUS', 'VERIFICATION_STATUS_CODE', 'کد وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت اعتبارسنجی در فهرست‌های مرجع');
  set_column_comment('REF_VERIFICATION_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت اعتبارسنجی؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_VERIFICATION_STATUS', 'PARENT_CODE', 'کد والد وضعیت اعتبارسنجی در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_VERIFICATION_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت اعتبارسنجی');
  set_column_comment('REF_VERIFICATION_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت اعتبارسنجی برای کنترل هم‌زمانی');
  set_column_comment('REF_WORKFLOW_STATUS', 'STATUS_CODE', 'کد وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'NAME_FA', 'عنوان فارسی وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'NAME_EN', 'عنوان انگلیسی وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'DESCRIPTION_FA', 'توضیحات فارسی وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'SORT_ORDER', 'ترتیب نمایش وضعیت گردش‌کار در فهرست‌های مرجع');
  set_column_comment('REF_WORKFLOW_STATUS', 'IS_ACTIVE', 'نشانگر فعال بودن وضعیت گردش‌کار؛ 1 فعال و 0 غیرفعال');
  set_column_comment('REF_WORKFLOW_STATUS', 'PARENT_CODE', 'کد والد وضعیت گردش‌کار در ساختار سلسله‌مراتبی، در صورت کاربرد');
  set_column_comment('REF_WORKFLOW_STATUS', 'VALID_FROM', 'تاریخ شروع اعتبار وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'VALID_TO', 'تاریخ پایان اعتبار وضعیت گردش‌کار');
  set_column_comment('REF_WORKFLOW_STATUS', 'RECORD_VERSION', 'شماره نسخه رکورد وضعیت گردش‌کار برای کنترل هم‌زمانی');
END;
/

PROMPT Verification: columns without Persian comments in governed reference tables
SELECT COUNT(*) AS MISSING_FA_COMMENT_COUNT
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = 'CIF'
   AND C.TABLE_NAME LIKE 'REF\_%' ESCAPE '\'
   AND (CC.COMMENTS IS NULL OR NOT REGEXP_LIKE(CC.COMMENTS, '[آ-ی]'));
