-- Core Banking Prototype 0.3.22
-- Final Party/Customer 360 hardening.
-- Align PARTY_REGISTRATION_REQUEST with CIF-tables4.xlsx when upgrading from the historical CIF DDL snapshot.
-- No reference/FK/check constraints are invented here: the current physical metadata sheets do not expose them.

DECLARE
  v_table_count NUMBER;
  v_seq_count   NUMBER;
  v_index_count NUMBER;
  v_start_with  NUMBER := 1;
BEGIN
  SELECT COUNT(*) INTO v_table_count
    FROM ALL_TABLES
   WHERE OWNER = 'CIF' AND TABLE_NAME = 'PARTY_REGISTRATION_REQUEST';

  SELECT COUNT(*) INTO v_seq_count
    FROM ALL_SEQUENCES
   WHERE SEQUENCE_OWNER = 'CIF' AND SEQUENCE_NAME = 'SEQ_PARTY_REGISTRATION_REQUEST';

  IF v_seq_count = 0 THEN
    IF v_table_count > 0 THEN
      EXECUTE IMMEDIATE 'SELECT NVL(MAX(REGISTRATION_REQUEST_ID),0)+1 FROM CIF.PARTY_REGISTRATION_REQUEST'
        INTO v_start_with;
    END IF;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE CIF.SEQ_PARTY_REGISTRATION_REQUEST START WITH '
      || v_start_with || ' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  IF v_table_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CIF.PARTY_REGISTRATION_REQUEST (
        REGISTRATION_REQUEST_ID NUMBER(19,0) DEFAULT CIF.SEQ_PARTY_REGISTRATION_REQUEST.NEXTVAL NOT NULL,
        TEMPORARY_KEY           VARCHAR2(50 CHAR) NOT NULL,
        PARTY_TYPE_CODE         VARCHAR2(30 CHAR) NOT NULL,
        CREATION_SOURCE_CODE    VARCHAR2(30 CHAR) NOT NULL,
        VALID_FROM              DATE NOT NULL,
        REQUEST_STATUS_CODE     VARCHAR2(30 CHAR) NOT NULL,
        IDENTITY_KIND_CODE      VARCHAR2(30 CHAR),
        REQUESTED_AT            TIMESTAMP(6) NOT NULL,
        EXPIRES_AT              TIMESTAMP(6),
        COMPLETED_PARTY_ID      NUMBER(19,0),
        CREATED_AT              TIMESTAMP(6) NOT NULL,
        CREATED_BY              VARCHAR2(50 CHAR) NOT NULL,
        UPDATED_AT              TIMESTAMP(6),
        UPDATED_BY              VARCHAR2(100 CHAR),
        RECORD_VERSION          NUMBER(19,0) NOT NULL
      ) TABLESPACE TS_CIF
    ~';
  END IF;

  SELECT COUNT(*) INTO v_index_count
    FROM ALL_INDEXES
   WHERE OWNER = 'CIF' AND INDEX_NAME = 'REGISTRATION_REQUEST_ID';
  IF v_index_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CIF.REGISTRATION_REQUEST_ID ON CIF.PARTY_REGISTRATION_REQUEST (REGISTRATION_REQUEST_ID) TABLESPACE TS_CIF';
  END IF;
END;
/

COMMENT ON TABLE CIF.PARTY_REGISTRATION_REQUEST IS 'درخواست ثبت اولیه Party پیش از تکمیل هویت';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.REGISTRATION_REQUEST_ID IS 'شناسه درخواست ثبت';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.TEMPORARY_KEY IS 'کلید موقت پیش‌نویس';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.PARTY_TYPE_CODE IS 'نوع Party';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.CREATION_SOURCE_CODE IS 'منبع ایجاد';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.VALID_FROM IS 'تاریخ شروع درخواست';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.REQUEST_STATUS_CODE IS 'وضعیت درخواست';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.IDENTITY_KIND_CODE IS 'نوع هویت حقیقی یا حقوقی';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.REQUESTED_AT IS 'زمان درخواست';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.EXPIRES_AT IS 'زمان انقضای پیش‌نویس';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.COMPLETED_PARTY_ID IS 'Party ایجادشده پس از تکمیل هویت';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.CREATED_AT IS 'زمان ایجاد';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.CREATED_BY IS 'Creation user';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.UPDATED_AT IS 'زمان ویرایش';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.UPDATED_BY IS 'ویرایش‌کننده';
COMMENT ON COLUMN CIF.PARTY_REGISTRATION_REQUEST.RECORD_VERSION IS 'نسخه رکورد';
