SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;
PROMPT === Fix20: Risk model version and score domain ===

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS WHERE OWNER='CIF' AND TABLE_NAME='REF_RISK_MODEL' AND COLUMN_NAME='MODEL_VERSION';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.REF_RISK_MODEL ADD (MODEL_VERSION VARCHAR2(30 CHAR))'; END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS WHERE OWNER='CIF' AND TABLE_NAME='REF_RISK_MODEL' AND COLUMN_NAME='MIN_SCORE';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.REF_RISK_MODEL ADD (MIN_SCORE NUMBER(12,6))'; END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS WHERE OWNER='CIF' AND TABLE_NAME='REF_RISK_MODEL' AND COLUMN_NAME='MAX_SCORE';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.REF_RISK_MODEL ADD (MAX_SCORE NUMBER(12,6))'; END IF;
END;
/

UPDATE CIF.REF_RISK_MODEL
SET MODEL_VERSION = COALESCE(MODEL_VERSION, '1.0'),
    MIN_SCORE = COALESCE(MIN_SCORE, 0),
    MAX_SCORE = COALESCE(MAX_SCORE, 100)
WHERE MODEL_VERSION IS NULL OR MIN_SCORE IS NULL OR MAX_SCORE IS NULL;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CIF' AND TABLE_NAME='REF_RISK_MODEL' AND CONSTRAINT_NAME='CK_RISK_MODEL_05';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.REF_RISK_MODEL ADD CONSTRAINT CK_RISK_MODEL_05 CHECK (MIN_SCORE <= MAX_SCORE)'; END IF;
END;
/

ALTER TABLE CIF.REF_RISK_MODEL MODIFY (MODEL_VERSION NOT NULL, MIN_SCORE NOT NULL, MAX_SCORE NOT NULL);

COMMENT ON COLUMN CIF.REF_RISK_MODEL.MODEL_VERSION IS 'نسخه فعال/مجاز مدل ریسک برای ثبت ارزیابی';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MIN_SCORE IS 'حداقل امتیاز مجاز مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MAX_SCORE IS 'حداکثر امتیاز مجاز مدل ریسک';

COMMIT;

PROMPT Validation
SELECT MODEL_CODE, NAME_FA, MODEL_VERSION, MIN_SCORE, MAX_SCORE, IS_ACTIVE
FROM CIF.REF_RISK_MODEL ORDER BY SORT_ORDER, MODEL_CODE;
