-- Core Banking Prototype 0.3.79 Fix87
-- CIF Religion / Religious Denomination reference data
-- Idempotent migration for existing Oracle CIF schemas.

SET DEFINE OFF;
SET SERVEROUTPUT ON;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CIF' AND TABLE_NAME='REF_RELIGION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_RELIGION (
        RELIGION_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_REF_RELIGION PRIMARY KEY (RELIGION_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_REF_RELIGION_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_REF_RELIGION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_REF_RELIGION_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_REF_RELIGION_04 CHECK (RECORD_VERSION >= 1)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CIF' AND TABLE_NAME='REF_RELIGIOUS_DENOMINATION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_RELIGIOUS_DENOMINATION (
        DENOMINATION_CODE VARCHAR2(50 CHAR) NOT NULL,
        RELIGION_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_REF_REL_DENOM PRIMARY KEY (DENOMINATION_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_REF_REL_DENOM_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_REF_REL_DENOM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_REF_REL_DENOM_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_REF_REL_DENOM_04 CHECK (RECORD_VERSION >= 1),
        CONSTRAINT FK_REF_REL_DENOM_RELIGION FOREIGN KEY (RELIGION_CODE) REFERENCES CIF.REF_RELIGION (RELIGION_CODE),
        CONSTRAINT FK_REF_REL_DENOM_PARENT FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_RELIGIOUS_DENOMINATION (DENOMINATION_CODE)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES WHERE OWNER='CIF' AND INDEX_NAME='IX_REF_REL_DENOM_RELIGION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_REF_REL_DENOM_RELIGION ON CIF.REF_RELIGIOUS_DENOMINATION (RELIGION_CODE) TABLESPACE ITS_CIF';
  END IF;
END;
/

COMMENT ON TABLE CIF.REF_RELIGION IS 'اطلاعات پایه دین برای Party شخص حقیقی؛ داده حساس و مشمول کنترل دسترسی و حریم خصوصی';
COMMENT ON COLUMN CIF.REF_RELIGION.RELIGION_CODE IS 'کد دین';
COMMENT ON COLUMN CIF.REF_RELIGION.NAME_FA IS 'عنوان فارسی دین';
COMMENT ON COLUMN CIF.REF_RELIGION.NAME_EN IS 'عنوان انگلیسی دین';
COMMENT ON COLUMN CIF.REF_RELIGION.DESCRIPTION_FA IS 'توضیحات فارسی دین';
COMMENT ON COLUMN CIF.REF_RELIGION.SORT_ORDER IS 'ترتیب نمایش';
COMMENT ON COLUMN CIF.REF_RELIGION.IS_ACTIVE IS 'فعال بودن؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RELIGION.PARENT_CODE IS 'کد والد اختیاری دین';
COMMENT ON COLUMN CIF.REF_RELIGION.VALID_FROM IS 'شروع اعتبار';
COMMENT ON COLUMN CIF.REF_RELIGION.VALID_TO IS 'پایان اعتبار';
COMMENT ON COLUMN CIF.REF_RELIGION.RECORD_VERSION IS 'نسخه رکورد';

COMMENT ON TABLE CIF.REF_RELIGIOUS_DENOMINATION IS 'اطلاعات پایه مذهب یا شاخه دینی وابسته به دین';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.DENOMINATION_CODE IS 'کد مذهب یا شاخه دینی';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.RELIGION_CODE IS 'کد دین والد';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.NAME_FA IS 'عنوان فارسی مذهب';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.NAME_EN IS 'عنوان انگلیسی مذهب';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.DESCRIPTION_FA IS 'توضیحات فارسی مذهب';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.SORT_ORDER IS 'ترتیب نمایش';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.IS_ACTIVE IS 'فعال بودن؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.PARENT_CODE IS 'کد مذهب والد در ساختار سلسله‌مراتبی';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.VALID_FROM IS 'شروع اعتبار';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.VALID_TO IS 'پایان اعتبار';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.RECORD_VERSION IS 'نسخه رکورد';

PROMPT === Seed REF_RELIGION ===
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'ISLAM' AS CODE, 'اسلام' AS FA, 'Islam' AS EN, 'دین اسلام.' AS DESCR, 10 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'CHRISTIANITY' AS CODE, 'مسیحیت' AS FA, 'Christianity' AS EN, 'دین مسیحیت.' AS DESCR, 20 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'JUDAISM' AS CODE, 'یهودیت' AS FA, 'Judaism' AS EN, 'دین یهودیت.' AS DESCR, 30 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'ZOROASTRIANISM' AS CODE, 'زرتشتی' AS FA, 'Zoroastrianism' AS EN, 'دین زرتشتی.' AS DESCR, 40 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'NO_RELIGIOUS_AFFILIATION' AS CODE, 'بدون وابستگی دینی' AS FA, 'No religious affiliation' AS EN, 'فاقد وابستگی دینی اعلام‌شده.' AS DESCR, 80 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'OTHER' AS CODE, 'سایر' AS FA, 'Other' AS EN, 'سایر ادیان یا وابستگی‌های دینی.' AS DESCR, 90 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGION T
USING (SELECT 'NOT_DECLARED' AS CODE, 'اظهار نشده' AS FA, 'Not declared' AS EN, 'مشتری دین خود را اظهار نکرده است.' AS DESCR, 100 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RELIGION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

PROMPT === Seed REF_RELIGIOUS_DENOMINATION ===
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SHIA_TWELVER' AS CODE, 'ISLAM' AS RELIGION_CODE, 'شیعه اثناعشری' AS FA, 'Twelver Shia' AS EN, 'مذهب شیعه دوازده‌امامی.' AS DESCR, 10 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SUNNI' AS CODE, 'ISLAM' AS RELIGION_CODE, 'اهل سنت' AS FA, 'Sunni' AS EN, 'عنوان عمومی اهل سنت.' AS DESCR, 20 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SUNNI_HANAFI' AS CODE, 'ISLAM' AS RELIGION_CODE, 'اهل سنت - حنفی' AS FA, 'Sunni Hanafi' AS EN, 'مذهب حنفی از مذاهب اهل سنت.' AS DESCR, 21 AS ORD, 1 AS ACTIVE, 'SUNNI' AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SUNNI_SHAFII' AS CODE, 'ISLAM' AS RELIGION_CODE, 'اهل سنت - شافعی' AS FA, 'Sunni Shafi''i' AS EN, 'مذهب شافعی از مذاهب اهل سنت.' AS DESCR, 22 AS ORD, 1 AS ACTIVE, 'SUNNI' AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SUNNI_MALIKI' AS CODE, 'ISLAM' AS RELIGION_CODE, 'اهل سنت - مالکی' AS FA, 'Sunni Maliki' AS EN, 'مذهب مالکی از مذاهب اهل سنت.' AS DESCR, 23 AS ORD, 1 AS ACTIVE, 'SUNNI' AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'SUNNI_HANBALI' AS CODE, 'ISLAM' AS RELIGION_CODE, 'اهل سنت - حنبلی' AS FA, 'Sunni Hanbali' AS EN, 'مذهب حنبلی از مذاهب اهل سنت.' AS DESCR, 24 AS ORD, 1 AS ACTIVE, 'SUNNI' AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'OTHER_ISLAMIC' AS CODE, 'ISLAM' AS RELIGION_CODE, 'سایر مذاهب اسلامی' AS FA, 'Other Islamic denomination' AS EN, 'سایر مذاهب یا شاخه‌های اسلامی.' AS DESCR, 29 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'ARMENIAN_APOSTOLIC' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'کلیسای حواری ارمنی' AS FA, 'Armenian Apostolic' AS EN, 'شاخه کلیسای حواری ارمنی.' AS DESCR, 40 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'ASSYRIAN_CHURCH_EAST' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'کلیسای آشوری شرق' AS FA, 'Assyrian Church of the East' AS EN, 'کلیسای آشوری شرق.' AS DESCR, 41 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'CATHOLIC' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'کاتولیک' AS FA, 'Catholic' AS EN, 'شاخه کاتولیک مسیحیت.' AS DESCR, 42 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'ORTHODOX' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'ارتدکس' AS FA, 'Orthodox' AS EN, 'شاخه ارتدکس مسیحیت.' AS DESCR, 43 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'PROTESTANT' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'پروتستان' AS FA, 'Protestant' AS EN, 'شاخه پروتستان مسیحیت.' AS DESCR, 44 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'OTHER_CHRISTIAN' AS CODE, 'CHRISTIANITY' AS RELIGION_CODE, 'سایر شاخه‌های مسیحیت' AS FA, 'Other Christian denomination' AS EN, 'سایر شاخه‌های مسیحیت.' AS DESCR, 49 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'JUDAISM_UNSPECIFIED' AS CODE, 'JUDAISM' AS RELIGION_CODE, 'یهودی - بدون تفکیک مذهب' AS FA, 'Judaism - unspecified denomination' AS EN, 'وابستگی به دین یهود بدون ثبت شاخه جزئی‌تر.' AS DESCR, 60 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'ZOROASTRIAN_UNSPECIFIED' AS CODE, 'ZOROASTRIANISM' AS RELIGION_CODE, 'زرتشتی - بدون تفکیک مذهب' AS FA, 'Zoroastrian - unspecified denomination' AS EN, 'وابستگی به دین زرتشتی بدون ثبت شاخه جزئی‌تر.' AS DESCR, 70 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
MERGE INTO CIF.REF_RELIGIOUS_DENOMINATION T
USING (SELECT 'OTHER_DENOMINATION' AS CODE, 'OTHER' AS RELIGION_CODE, 'سایر / بدون طبقه‌بندی' AS FA, 'Other / unclassified' AS EN, 'سایر مذاهب یا شاخه‌های طبقه‌بندی‌نشده.' AS DESCR, 90 AS ORD, 1 AS ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.DENOMINATION_CODE=S.CODE)
WHEN MATCHED THEN UPDATE SET T.RELIGION_CODE=S.RELIGION_CODE, T.NAME_FA=S.FA, T.NAME_EN=S.EN, T.DESCRIPTION_FA=S.DESCR, T.SORT_ORDER=S.ORD, T.IS_ACTIVE=S.ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (DENOMINATION_CODE, RELIGION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION) VALUES (S.CODE, S.RELIGION_CODE, S.FA, S.EN, S.DESCR, S.ORD, S.ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);


COMMIT;

PROMPT === Verification ===
SELECT 'REF_RELIGION' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_RELIGION
UNION ALL
SELECT 'REF_RELIGIOUS_DENOMINATION', COUNT(*) FROM CIF.REF_RELIGIOUS_DENOMINATION;

SELECT D.DENOMINATION_CODE, R.NAME_FA AS RELIGION_NAME_FA, D.NAME_FA AS DENOMINATION_NAME_FA,
       D.PARENT_CODE, D.IS_ACTIVE
FROM CIF.REF_RELIGIOUS_DENOMINATION D
JOIN CIF.REF_RELIGION R ON R.RELIGION_CODE=D.RELIGION_CODE
ORDER BY R.SORT_ORDER, D.SORT_ORDER, D.DENOMINATION_CODE;
