MERGE INTO CIF.REF_OCCUPATION dst
USING (
    SELECT 'HOMEMAKER' AS OCCUPATION_CODE, 'خانه‌دار' AS NAME_FA, 'Homemaker' AS NAME_EN, 'Y' AS ACTIVE_FLAG, 5 AS DISPLAY_ORDER FROM dual
    UNION ALL
    SELECT 'UNEMPLOYED', 'بیکار', 'Unemployed', 'Y', 6 FROM dual
) src
ON (dst.OCCUPATION_CODE = src.OCCUPATION_CODE)
WHEN MATCHED THEN UPDATE SET
    dst.NAME_FA = src.NAME_FA,
    dst.NAME_EN = src.NAME_EN,
    dst.ACTIVE_FLAG = src.ACTIVE_FLAG,
    dst.DISPLAY_ORDER = src.DISPLAY_ORDER
WHEN NOT MATCHED THEN INSERT (OCCUPATION_CODE, NAME_FA, NAME_EN, ACTIVE_FLAG, DISPLAY_ORDER)
VALUES (src.OCCUPATION_CODE, src.NAME_FA, src.NAME_EN, src.ACTIVE_FLAG, src.DISPLAY_ORDER);
