-- 0.3.22-prototype-fix22
-- Legal-entity economic-profile Reference Data and Persian-title UI support.
-- Safe/idempotent on an existing CIF schema.
-- Person/Natural-customer tables and flows are intentionally untouched.

PROMPT [Fix22] Creating dedicated Organization Reference Data tables when absent...

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE CIF.REF_ORGANIZATION_ACTIVITY_STATUS (
      ACTIVITY_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
      NAME_FA VARCHAR2(200 CHAR) NOT NULL,
      NAME_EN VARCHAR2(200 CHAR),
      DESCRIPTION_FA VARCHAR2(1000 CHAR),
      SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      PARENT_CODE VARCHAR2(50 CHAR),
      VALID_FROM DATE,
      VALID_TO DATE,
      RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_ORG_ACTIVITY_STATUS PRIMARY KEY (ACTIVITY_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
      CONSTRAINT CK_ORG_ACTIVITY_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
      CONSTRAINT CK_ORG_ACTIVITY_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
      CONSTRAINT CK_ORG_ACTIVITY_STATUS_03 CHECK (SORT_ORDER >= 0),
      CONSTRAINT CK_ORG_ACTIVITY_STATUS_04 CHECK (RECORD_VERSION >= 1)
    ) TABLESPACE TS_CIF
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE CIF.REF_ENTERPRISE_SIZE (
      ENTERPRISE_SIZE_CODE VARCHAR2(50 CHAR) NOT NULL,
      NAME_FA VARCHAR2(200 CHAR) NOT NULL,
      NAME_EN VARCHAR2(200 CHAR),
      DESCRIPTION_FA VARCHAR2(1000 CHAR),
      SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      PARENT_CODE VARCHAR2(50 CHAR),
      VALID_FROM DATE,
      VALID_TO DATE,
      RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_ENTERPRISE_SIZE PRIMARY KEY (ENTERPRISE_SIZE_CODE) USING INDEX TABLESPACE ITS_CIF,
      CONSTRAINT CK_ENTERPRISE_SIZE_01 CHECK (IS_ACTIVE IN (0,1)),
      CONSTRAINT CK_ENTERPRISE_SIZE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
      CONSTRAINT CK_ENTERPRISE_SIZE_03 CHECK (SORT_ORDER >= 0),
      CONSTRAINT CK_ENTERPRISE_SIZE_04 CHECK (RECORD_VERSION >= 1)
    ) TABLESPACE TS_CIF
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE CIF.REF_OWNERSHIP_TYPE (
      OWNERSHIP_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
      NAME_FA VARCHAR2(200 CHAR) NOT NULL,
      NAME_EN VARCHAR2(200 CHAR),
      DESCRIPTION_FA VARCHAR2(1000 CHAR),
      SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      PARENT_CODE VARCHAR2(50 CHAR),
      VALID_FROM DATE,
      VALID_TO DATE,
      RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_OWNERSHIP_TYPE PRIMARY KEY (OWNERSHIP_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
      CONSTRAINT CK_OWNERSHIP_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
      CONSTRAINT CK_OWNERSHIP_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
      CONSTRAINT CK_OWNERSHIP_TYPE_03 CHECK (SORT_ORDER >= 0),
      CONSTRAINT CK_OWNERSHIP_TYPE_04 CHECK (RECORD_VERSION >= 1)
    ) TABLESPACE TS_CIF
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE CIF.REF_ORGANIZATION_ACTIVITY_STATUS IS 'اطلاعات پایه وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.ACTIVITY_STATUS_CODE IS 'کد وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.NAME_FA IS 'عنوان فارسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن مقدار مرجع؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.PARENT_CODE IS 'کد والد وضعیت فعالیت اقتصادی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت فعالیت اقتصادی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت فعالیت اقتصادی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.RECORD_VERSION IS 'نسخه رکورد مرجع وضعیت فعالیت اقتصادی';

COMMENT ON TABLE CIF.REF_ENTERPRISE_SIZE IS 'اطلاعات پایه اندازه بنگاه شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.ENTERPRISE_SIZE_CODE IS 'کد اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.NAME_FA IS 'عنوان فارسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.NAME_EN IS 'عنوان انگلیسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.DESCRIPTION_FA IS 'توضیحات فارسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.SORT_ORDER IS 'ترتیب نمایش اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.IS_ACTIVE IS 'نشانگر فعال بودن مقدار مرجع؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.PARENT_CODE IS 'کد والد اندازه بنگاه، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.VALID_FROM IS 'تاریخ شروع اعتبار اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.VALID_TO IS 'تاریخ پایان اعتبار اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.RECORD_VERSION IS 'نسخه رکورد مرجع اندازه بنگاه';

COMMENT ON TABLE CIF.REF_OWNERSHIP_TYPE IS 'اطلاعات پایه نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.OWNERSHIP_TYPE_CODE IS 'کد نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.NAME_FA IS 'عنوان فارسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.NAME_EN IS 'عنوان انگلیسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن مقدار مرجع؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.PARENT_CODE IS 'کد والد نوع مالکیت، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع مالکیت';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع مالکیت';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.RECORD_VERSION IS 'نسخه رکورد مرجع نوع مالکیت';

PROMPT [Fix22] Seeding Organization Reference Data...

MERGE INTO CIF.REF_ORGANIZATION_ACTIVITY_STATUS T
USING (
  SELECT 'ACTIVE' ACTIVITY_STATUS_CODE,'فعال' NAME_FA,'Active' NAME_EN,'فعالیت اقتصادی شخص حقوقی فعال است.' DESCRIPTION_FA,10 SORT_ORDER FROM DUAL
  UNION ALL SELECT 'INACTIVE','غیرفعال','Inactive','فعالیت اقتصادی شخص حقوقی غیرفعال است.',20 FROM DUAL
  UNION ALL SELECT 'SUSPENDED','تعلیق‌شده','Suspended','فعالیت اقتصادی شخص حقوقی موقتاً تعلیق شده است.',30 FROM DUAL
  UNION ALL SELECT 'UNDER_REVIEW','در حال بررسی','Under Review','وضعیت فعالیت اقتصادی شخص حقوقی در حال بررسی است.',40 FROM DUAL
) S
ON (T.ACTIVITY_STATUS_CODE=S.ACTIVITY_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA,T.NAME_EN=S.NAME_EN,T.DESCRIPTION_FA=S.DESCRIPTION_FA,T.SORT_ORDER=S.SORT_ORDER,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (ACTIVITY_STATUS_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.ACTIVITY_STATUS_CODE,S.NAME_FA,S.NAME_EN,S.DESCRIPTION_FA,S.SORT_ORDER,1,NULL,NULL,NULL,1);

MERGE INTO CIF.REF_ENTERPRISE_SIZE T
USING (
  SELECT 'MICRO' ENTERPRISE_SIZE_CODE,'بنگاه خرد' NAME_FA,'Micro enterprise' NAME_EN,'رده مرجع بنگاه خرد.' DESCRIPTION_FA,10 SORT_ORDER FROM DUAL
  UNION ALL SELECT 'SMALL','بنگاه کوچک','Small enterprise','رده مرجع بنگاه کوچک.',20 FROM DUAL
  UNION ALL SELECT 'MEDIUM','بنگاه متوسط','Medium enterprise','رده مرجع بنگاه متوسط.',30 FROM DUAL
  UNION ALL SELECT 'LARGE','بنگاه بزرگ','Large enterprise','رده مرجع بنگاه بزرگ.',40 FROM DUAL
) S
ON (T.ENTERPRISE_SIZE_CODE=S.ENTERPRISE_SIZE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA,T.NAME_EN=S.NAME_EN,T.DESCRIPTION_FA=S.DESCRIPTION_FA,T.SORT_ORDER=S.SORT_ORDER,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (ENTERPRISE_SIZE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.ENTERPRISE_SIZE_CODE,S.NAME_FA,S.NAME_EN,S.DESCRIPTION_FA,S.SORT_ORDER,1,NULL,NULL,NULL,1);

MERGE INTO CIF.REF_OWNERSHIP_TYPE T
USING (
  SELECT 'PRIVATE' OWNERSHIP_TYPE_CODE,'خصوصی' NAME_FA,'Private' NAME_EN,'مالکیت خصوصی.' DESCRIPTION_FA,10 SORT_ORDER FROM DUAL
  UNION ALL SELECT 'STATE','دولتی','State-owned','مالکیت دولتی.',20 FROM DUAL
  UNION ALL SELECT 'PUBLIC_NON_GOV','عمومی غیردولتی','Public non-governmental','مالکیت عمومی غیردولتی.',30 FROM DUAL
  UNION ALL SELECT 'COOPERATIVE','تعاونی','Cooperative','مالکیت تعاونی.',40 FROM DUAL
  UNION ALL SELECT 'MIXED','مختلط','Mixed ownership','مالکیت مختلط.',50 FROM DUAL
  UNION ALL SELECT 'OTHER','سایر','Other','سایر انواع مالکیت.',60 FROM DUAL
) S
ON (T.OWNERSHIP_TYPE_CODE=S.OWNERSHIP_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA,T.NAME_EN=S.NAME_EN,T.DESCRIPTION_FA=S.DESCRIPTION_FA,T.SORT_ORDER=S.SORT_ORDER,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (OWNERSHIP_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.OWNERSHIP_TYPE_CODE,S.NAME_FA,S.NAME_EN,S.DESCRIPTION_FA,S.SORT_ORDER,1,NULL,NULL,NULL,1);

PROMPT [Fix22] Re-aligning known ISIC Persian titles to prevent opaque code-only UI...
MERGE INTO CIF.REF_ISIC_ACTIVITY T
USING (
  SELECT '0111' ISIC_CODE,'کشت غلات (به‌جز برنج)، حبوبات و دانه‌های روغنی' NAME_FA,'Growing of cereals (except rice), leguminous crops and oil seeds' NAME_EN FROM DUAL
  UNION ALL SELECT '4690','عمده‌فروشی غیرتخصصی','Non-specialized wholesale trade' FROM DUAL
  UNION ALL SELECT '6201','فعالیت‌های برنامه‌نویسی رایانه‌ای','Computer programming activities' FROM DUAL
  UNION ALL SELECT '6419','سایر واسطه‌گری‌های پولی','Other monetary intermediation' FROM DUAL
) S
ON (T.ISIC_CODE=S.ISIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA,T.NAME_EN=S.NAME_EN,T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (ISIC_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.ISIC_CODE,S.NAME_FA,S.NAME_EN,NULL,10,1,NULL,NULL,NULL,1);

-- Enforce new values without rejecting legacy data already present in ORGANIZATION.
DECLARE
  PROCEDURE ADD_FK_IF_POSSIBLE(P_CONSTRAINT VARCHAR2, P_COLUMN VARCHAR2, P_REF_TABLE VARCHAR2, P_REF_COLUMN VARCHAR2) IS
    V_CONSTRAINT NUMBER;
    V_COLUMN NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_CONSTRAINT FROM ALL_CONSTRAINTS WHERE OWNER='CIF' AND CONSTRAINT_NAME=UPPER(P_CONSTRAINT);
    SELECT COUNT(*) INTO V_COLUMN FROM ALL_TAB_COLUMNS WHERE OWNER='CIF' AND TABLE_NAME='ORGANIZATION' AND COLUMN_NAME=UPPER(P_COLUMN);
    IF V_CONSTRAINT=0 AND V_COLUMN=1 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE CIF.ORGANIZATION ADD CONSTRAINT '||P_CONSTRAINT||' FOREIGN KEY ('||P_COLUMN||') REFERENCES CIF.'||P_REF_TABLE||' ('||P_REF_COLUMN||') ENABLE NOVALIDATE';
    END IF;
  END;
BEGIN
  ADD_FK_IF_POSSIBLE('FK_ORG_ACTIVITY_STATUS','ACTIVITY_STATUS_CODE','REF_ORGANIZATION_ACTIVITY_STATUS','ACTIVITY_STATUS_CODE');
  ADD_FK_IF_POSSIBLE('FK_ORG_ENTERPRISE_SIZE','ENTERPRISE_SIZE_CODE','REF_ENTERPRISE_SIZE','ENTERPRISE_SIZE_CODE');
  ADD_FK_IF_POSSIBLE('FK_ORG_OWNERSHIP_TYPE','OWNERSHIP_TYPE_CODE','REF_OWNERSHIP_TYPE','OWNERSHIP_TYPE_CODE');
END;
/

COMMENT ON COLUMN CIF.ORGANIZATION.ACTIVITY_STATUS_CODE IS 'کد وضعیت فعالیت اقتصادی شخص حقوقی؛ مرجع CIF.REF_ORGANIZATION_ACTIVITY_STATUS';
COMMENT ON COLUMN CIF.ORGANIZATION.EMPLOYEE_COUNT IS 'تعداد واقعی کارکنان شخص حقوقی؛ مقدار عددی و غیرکدینگ';
COMMENT ON COLUMN CIF.ORGANIZATION.ENTERPRISE_SIZE_CODE IS 'کد اندازه بنگاه؛ مرجع CIF.REF_ENTERPRISE_SIZE';
COMMENT ON COLUMN CIF.ORGANIZATION.OWNERSHIP_TYPE_CODE IS 'کد نوع مالکیت شخص حقوقی؛ مرجع CIF.REF_OWNERSHIP_TYPE';
COMMENT ON COLUMN CIF.ORGANIZATION.MAIN_ACTIVITY_DESCRIPTION IS 'شرح متنی فعالیت اصلی شخص حقوقی';
COMMENT ON COLUMN CIF.ORGANIZATION.ISIC_CODE IS 'کد فعالیت اقتصادی ISIC؛ عنوان از CIF.REF_ISIC_ACTIVITY نمایش داده می‌شود';

COMMIT;

PROMPT [Fix22] Validation...
DECLARE
  V_STATUS NUMBER;
  V_SIZE NUMBER;
  V_OWNER NUMBER;
  V_BAD_ISIC NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_STATUS FROM CIF.REF_ORGANIZATION_ACTIVITY_STATUS WHERE IS_ACTIVE=1;
  SELECT COUNT(*) INTO V_SIZE FROM CIF.REF_ENTERPRISE_SIZE WHERE IS_ACTIVE=1;
  SELECT COUNT(*) INTO V_OWNER FROM CIF.REF_OWNERSHIP_TYPE WHERE IS_ACTIVE=1;
  SELECT COUNT(*) INTO V_BAD_ISIC FROM CIF.REF_ISIC_ACTIVITY
   WHERE ISIC_CODE IN ('0111','4690','6201','6419')
     AND (NAME_FA IS NULL OR NAME_FA=ISIC_CODE OR REGEXP_LIKE(NAME_FA,'^[0-9]+$'));
  IF V_STATUS < 4 THEN RAISE_APPLICATION_ERROR(-20121,'Fix22: organization activity-status reference seed incomplete.'); END IF;
  IF V_SIZE < 4 THEN RAISE_APPLICATION_ERROR(-20122,'Fix22: enterprise-size reference seed incomplete.'); END IF;
  IF V_OWNER < 6 THEN RAISE_APPLICATION_ERROR(-20123,'Fix22: ownership-type reference seed incomplete.'); END IF;
  IF V_BAD_ISIC <> 0 THEN RAISE_APPLICATION_ERROR(-20124,'Fix22: ISIC Persian labels are still opaque.'); END IF;
END;
/
