-- Core Banking Prototype 0.3.18
-- Party Operations Phase 7: PARTY_ROLE alignment + PARTY_CUSTOMER.
-- Idempotent upgrade from the historical CIF DDL snapshot.
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS WHERE OWNER='CIF' AND TABLE_NAME=p_table AND COLUMN_NAME=p_column;
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CIF.'||p_table||' ADD ('||p_column||' '||p_definition||')'; END IF;
  END;
BEGIN
  add_column_if_missing('PARTY_ROLE','PRINCIPAL_PARTY_ID','NUMBER(19,0)');
  add_column_if_missing('PARTY_ROLE','RELATIONSHIP_TYPE_CODE','VARCHAR2(30 CHAR)');
  add_column_if_missing('PARTY_ROLE','AUTHORITY_BASIS_CODE','VARCHAR2(30 CHAR)');
  add_column_if_missing('PARTY_ROLE','AUTHORITY_DOCUMENT_NO','VARCHAR2(100 CHAR)');
  add_column_if_missing('PARTY_ROLE','AUTHORITY_ISSUER','VARCHAR2(200 CHAR)');
  add_column_if_missing('PARTY_ROLE','AUTHORITY_SCOPE_TEXT','VARCHAR2(500 CHAR)');
  add_column_if_missing('PARTY_ROLE','ASSIGNMENT_REASON_TEXT','VARCHAR2(500 CHAR)');
  add_column_if_missing('PARTY_ROLE','DESCRIPTION_TEXT','VARCHAR2(500 CHAR)');
END;
/

DECLARE
  v_count NUMBER;
  v_table_exists NUMBER;
  v_start NUMBER := 1;
BEGIN
  SELECT COUNT(*) INTO v_table_exists FROM ALL_TABLES WHERE OWNER='CIF' AND TABLE_NAME='PARTY_CUSTOMER';
  SELECT COUNT(*) INTO v_count FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='CIF' AND SEQUENCE_NAME='SEQ_PARTY_CUSTOMER';
  IF v_count=0 THEN
    IF v_table_exists>0 THEN EXECUTE IMMEDIATE 'SELECT NVL(MAX(PARTY_CUSTOMER_ID),0)+1 FROM CIF.PARTY_CUSTOMER' INTO v_start; END IF;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE CIF.SEQ_PARTY_CUSTOMER START WITH '||v_start||' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  IF v_table_exists=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.PARTY_CUSTOMER (
        PARTY_CUSTOMER_ID NUMBER(19,0) DEFAULT CIF.SEQ_PARTY_CUSTOMER.NEXTVAL NOT NULL,
        PARTY_ID NUMBER(19,0) NOT NULL,
        PARTY_ROLE_ID NUMBER(19,0) NOT NULL,
        CUSTOMER_NO VARCHAR2(30 CHAR) NOT NULL,
        CUSTOMER_STATUS_CODE VARCHAR2(30 CHAR) NOT NULL,
        VALID_FROM DATE NOT NULL,
        VALID_TO DATE,
        IS_CURRENT CHAR(1 CHAR) NOT NULL,
        CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
        UPDATED_AT TIMESTAMP(6),
        UPDATED_BY VARCHAR2(100 CHAR),
        RECORD_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_PARTY_CUSTOMER PRIMARY KEY (PARTY_CUSTOMER_ID),
        CONSTRAINT UQ_PARTY_CUSTOMER_NO UNIQUE (CUSTOMER_NO),
        CONSTRAINT CK_PARTY_CUSTOMER_CURRENT CHECK (IS_CURRENT IN ('Y','N')),
        CONSTRAINT CK_PARTY_CUSTOMER_DATES CHECK (VALID_TO IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_PARTY_CUSTOMER_VERSION CHECK (RECORD_VERSION >= 1),
        CONSTRAINT FK_PARTY_CUSTOMER_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CIF.PARTY(PARTY_ID),
        CONSTRAINT FK_PARTY_CUSTOMER_ROLE FOREIGN KEY (PARTY_ROLE_ID) REFERENCES CIF.PARTY_ROLE(PARTY_ROLE_ID)
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_PARTY_CUSTOMER_PARTY ON CIF.PARTY_CUSTOMER(PARTY_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_PARTY_CUSTOMER_ROLE ON CIF.PARTY_CUSTOMER(PARTY_ROLE_ID)';
  END IF;
END;
/

-- Prototype customer-number policy. The EA/XMI model defines CUSTOMER_NO but not its numbering algorithm.
-- This sequence is isolated so the bank-specific numbering policy can replace it later without changing PARTY_CUSTOMER_ID.
DECLARE
  v_count NUMBER;
  v_start NUMBER := 10000000;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='CIF' AND SEQUENCE_NAME='SEQ_CUSTOMER_NO';
  IF v_count=0 THEN
    BEGIN
      EXECUTE IMMEDIATE q'[SELECT GREATEST(10000000, NVL(MAX(TO_NUMBER(CUSTOMER_NO)),9999999)+1) FROM CIF.PARTY_CUSTOMER WHERE REGEXP_LIKE(CUSTOMER_NO,'^[0-9]+$')]' INTO v_start;
    EXCEPTION WHEN OTHERS THEN v_start := 10000000;
    END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE CIF.SEQ_CUSTOMER_NO START WITH '||v_start||' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

-- Operational role values present in the supplied Party operational form.
UPDATE CIF.REF_ROLE_TYPE SET NAME_FA='مشتری بانک' WHERE ROLE_TYPE_CODE='CUSTOMER' AND NAME_FA='مشتری';
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'PROSPECT' c,'متقاضی' fa,'Prospect' en,60 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'ATTORNEY' c,'وکیل' fa,'Attorney' en,70 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'GUARDIAN' c,'قیم' fa,'Guardian' en,80 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'EXECUTOR' c,'وصی' fa,'Executor' en,90 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'TRUSTEE' c,'امین' fa,'Trustee' en,100 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'LEGAL_REPRESENTATIVE' c,'نماینده قانونی' fa,'Legal Representative' en,110 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'PLEDGOR' c,'وثیقه‌گذار' fa,'Pledgor' en,120 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'BENEFICIARY' c,'ذی‌نفع' fa,'Beneficiary' en,130 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'SUPPLIER' c,'تأمین‌کننده' fa,'Supplier' en,140 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
MERGE INTO CIF.REF_ROLE_TYPE t USING (SELECT 'EMPLOYEE' c,'کارمند' fa,'Employee' en,150 so FROM dual) s ON (t.ROLE_TYPE_CODE=s.c)
WHEN NOT MATCHED THEN INSERT (ROLE_TYPE_CODE,NAME_FA,NAME_EN,SORT_ORDER,IS_ACTIVE,RECORD_VERSION) VALUES(s.c,s.fa,s.en,s.so,1,1);
COMMIT;

COMMENT ON TABLE CIF.PARTY_CUSTOMER IS 'رابطه Party با نقش مشتری بانک و شماره مشتری';
COMMENT ON COLUMN CIF.PARTY_CUSTOMER.PARTY_ROLE_ID IS 'نقش CUSTOMER متناظر در PARTY_ROLE';
COMMENT ON COLUMN CIF.PARTY_CUSTOMER.CUSTOMER_NO IS 'شماره مشتری بانک';
COMMENT ON COLUMN CIF.PARTY_CUSTOMER.IS_CURRENT IS 'نشانگر رابطه جاری مشتری بانک';
