SET DEFINE OFF;

PROMPT === 0.3.21 Party lifecycle / merge alignment ===

DECLARE
  v_table_count NUMBER;
  v_seq_count NUMBER;
  v_start NUMBER := 1;

  PROCEDURE ensure_sequence(p_sequence VARCHAR2, p_table VARCHAR2, p_id_column VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_seq_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_sequence);
    IF v_seq_count = 0 THEN
      SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table);
      IF v_table_count > 0 THEN
        EXECUTE IMMEDIATE 'SELECT NVL(MAX(' || p_id_column || '),0)+1 FROM CIF.' || p_table INTO v_start;
      ELSE
        v_start := 1;
      END IF;
      EXECUTE IMMEDIATE 'CREATE SEQUENCE CIF.' || p_sequence || ' START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
  END;
BEGIN
  ensure_sequence('SEQ_PARTY_STATUS_HISTORY', 'PARTY_STATUS_HISTORY', 'PARTY_STATUS_HISTORY_ID');
  ensure_sequence('SEQ_PARTY_MERGE_HISTORY', 'PARTY_MERGE_HISTORY', 'PARTY_MERGE_ID');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='PARTY_STATUS_HISTORY';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CIF.PARTY_STATUS_HISTORY (
        PARTY_STATUS_HISTORY_ID NUMBER(19,0) DEFAULT CIF.SEQ_PARTY_STATUS_HISTORY.NEXTVAL NOT NULL,
        PARTY_ID NUMBER(19,0) NOT NULL,
        LIFECYCLE_STATUS_CODE VARCHAR2(30 CHAR) NOT NULL,
        STATUS_REASON_CODE VARCHAR2(30 CHAR) NOT NULL,
        VALID_FROM DATE NOT NULL,
        VALID_TO DATE,
        DESCRIPTION_TEXT VARCHAR2(1000 CHAR),
        CREATED_AT TIMESTAMP(6) NOT NULL,
        CREATED_BY VARCHAR2(50 CHAR) NOT NULL,
        UPDATED_AT TIMESTAMP(6),
        UPDATED_BY VARCHAR2(100 CHAR),
        RECORD_VERSION NUMBER(19,0) NOT NULL,
        CONSTRAINT PK_PARTY_STATUS_HISTORY PRIMARY KEY (PARTY_STATUS_HISTORY_ID),
        CONSTRAINT FK_PARTY_STATUS_HIST_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CIF.PARTY(PARTY_ID),
        CONSTRAINT FK_PARTY_STATUS_HIST_LIFE FOREIGN KEY (LIFECYCLE_STATUS_CODE) REFERENCES CIF.REF_PARTY_LIFECYCLE_STATUS(LIFECYCLE_STATUS_CODE),
        CONSTRAINT FK_PARTY_STATUS_HIST_REASON FOREIGN KEY (STATUS_REASON_CODE) REFERENCES CIF.REF_PARTY_STATUS_REASON(REASON_CODE)
      )
    ~';
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_PARTY_STATUS_HIST_PARTY ON CIF.PARTY_STATUS_HISTORY(PARTY_ID, VALID_FROM)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='PARTY_MERGE_HISTORY';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CIF.PARTY_MERGE_HISTORY (
        PARTY_MERGE_ID NUMBER(19,0) DEFAULT CIF.SEQ_PARTY_MERGE_HISTORY.NEXTVAL NOT NULL,
        SOURCE_PARTY_ID NUMBER(19,0) NOT NULL,
        TARGET_PARTY_ID NUMBER(19,0) NOT NULL,
        MERGE_REASON_CODE VARCHAR2(30 CHAR) NOT NULL,
        CONFLICT_RESOLUTION_CODE VARCHAR2(30 CHAR),
        MERGED_AT TIMESTAMP(6) NOT NULL,
        MERGED_BY VARCHAR2(100 CHAR) NOT NULL,
        CREATED_AT TIMESTAMP(6) NOT NULL,
        CREATED_BY VARCHAR2(50 CHAR) NOT NULL,
        UPDATED_AT TIMESTAMP(6),
        UPDATED_BY VARCHAR2(100 CHAR),
        RECORD_VERSION NUMBER(19,0) NOT NULL,
        CREATED_DATE TIMESTAMP(6) NOT NULL,
        CONSTRAINT PK_PARTY_MERGE_HISTORY PRIMARY KEY (PARTY_MERGE_ID),
        CONSTRAINT FK_PARTY_MERGE_SOURCE FOREIGN KEY (SOURCE_PARTY_ID) REFERENCES CIF.PARTY(PARTY_ID),
        CONSTRAINT FK_PARTY_MERGE_TARGET FOREIGN KEY (TARGET_PARTY_ID) REFERENCES CIF.PARTY(PARTY_ID),
        CONSTRAINT CK_PARTY_MERGE_DIFFERENT CHECK (SOURCE_PARTY_ID <> TARGET_PARTY_ID)
      )
    ~';
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_PARTY_MERGE_SOURCE ON CIF.PARTY_MERGE_HISTORY(SOURCE_PARTY_ID, MERGED_AT)';
    EXECUTE IMMEDIATE 'CREATE INDEX CIF.IX_PARTY_MERGE_TARGET ON CIF.PARTY_MERGE_HISTORY(TARGET_PARTY_ID, MERGED_AT)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME='PARTY_MERGE_HISTORY' AND COLUMN_NAME='CREATED_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_MERGE_HISTORY ADD (CREATED_DATE TIMESTAMP(6))';
    EXECUTE IMMEDIATE 'UPDATE CIF.PARTY_MERGE_HISTORY SET CREATED_DATE = NVL(CREATED_AT, MERGED_AT) WHERE CREATED_DATE IS NULL';
    EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_MERGE_HISTORY MODIFY (CREATED_DATE NOT NULL)';
  END IF;
END;
/

COMMENT ON TABLE CIF.PARTY_STATUS_HISTORY IS 'تاریخچه زمان‌مند تغییر وضعیت Party';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.PARTY_STATUS_HISTORY_ID IS 'شناسه تاریخچه وضعیت';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.PARTY_ID IS 'شناسه Party';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.LIFECYCLE_STATUS_CODE IS 'وضعیت چرخه عمر';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.STATUS_REASON_CODE IS 'دلیل وضعیت';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.VALID_FROM IS 'از تاریخ';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.VALID_TO IS 'تا تاریخ';
COMMENT ON COLUMN CIF.PARTY_STATUS_HISTORY.DESCRIPTION_TEXT IS 'شرح تکمیلی علت و جزئیات تغییر وضعیت پارتی';

COMMENT ON TABLE CIF.PARTY_MERGE_HISTORY IS 'تاریخچه ادغام Partyهای تکراری';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.PARTY_MERGE_ID IS 'شناسه ادغام';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.SOURCE_PARTY_ID IS 'Party مبدأ';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.TARGET_PARTY_ID IS 'Party مقصد';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.MERGE_REASON_CODE IS 'دلیل ادغام';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.CONFLICT_RESOLUTION_CODE IS 'روش رفع تعارض';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.MERGED_AT IS 'زمان ادغام';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.MERGED_BY IS 'انجام‌دهنده';
COMMENT ON COLUMN CIF.PARTY_MERGE_HISTORY.CREATED_DATE IS 'Creation timestamp';

PROMPT === 0.3.21 alignment completed ===
