PROMPT =====================================================================
PROMPT Core Banking Prototype 0.3.22-fix17 - Party document/classification/date fixes
PROMPT =====================================================================

-- VERIFIED_AT is a business event timestamp and can legitimately predate the
-- physical database-row creation timestamp. The old check caused valid document
-- inserts to fail when verification time was captured before/at save time.
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
    FROM ALL_CONSTRAINTS
   WHERE OWNER='CIF' AND TABLE_NAME='PARTY_DOCUMENT' AND CONSTRAINT_NAME='CK_DOC_VERIFY_DATE';
  IF V_COUNT > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CIF.PARTY_DOCUMENT DROP CONSTRAINT CK_DOC_VERIFY_DATE';
  END IF;
END;
/


-- Fix17: normalized Persian classification vocabulary and complete type-dependent values.
MERGE INTO CIF.REF_CLASSIFICATION_TYPE T
USING (
  SELECT 'CUSTOMER_TIER' CLASSIFICATION_TYPE_CODE, 'رده مشتری' NAME_FA, 'Customer Tier' NAME_EN, 'رده کسب‌وکاری مشتری برای بخش‌بندی سطح‌بالا؛ کد در PARTY_CLASSIFICATION ذخیره می‌شود.' DESCRIPTION_FA, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'گروه صنعت' NAME_FA, 'Industry Group' NAME_EN, 'گروه صنعت در سطح پرتفوی. برای فعالیت اقتصادی تفصیلی از ISIC استفاده شود.' DESCRIPTION_FA, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RISK_CLASS' CLASSIFICATION_TYPE_CODE, 'طبقه ریسک' NAME_FA, 'Risk Class' NAME_EN, 'طبقه‌بندی سطح ریسک Party بر اساس خروجی فرآیند یا مدل مصوب.' DESCRIPTION_FA, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RELATIONSHIP_CLASS' CLASSIFICATION_TYPE_CODE, 'طبقه رابطه با بانک' NAME_FA, 'Relationship Class' NAME_EN, 'طبقه‌بندی کیفیت یا اهمیت رابطه Party با بانک.' DESCRIPTION_FA, 40 SORT_ORDER FROM DUAL
) S
ON (T.CLASSIFICATION_TYPE_CODE=S.CLASSIFICATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (CLASSIFICATION_TYPE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.CLASSIFICATION_TYPE_CODE,S.NAME_FA,S.NAME_EN,S.DESCRIPTION_FA,S.SORT_ORDER,1,NULL,NULL,NULL,1);

MERGE INTO CIF.REF_CLASSIFICATION_VALUE T
USING (
  SELECT 'CUSTOMER_TIER' CLASSIFICATION_TYPE_CODE, 'RETAIL' CLASSIFICATION_VALUE_CODE, 'مشتری خرد' NAME_FA, 'Retail' NAME_EN, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'CUSTOMER_TIER' CLASSIFICATION_TYPE_CODE, 'SME' CLASSIFICATION_VALUE_CODE, 'کسب‌وکار کوچک و متوسط' NAME_FA, 'SME' NAME_EN, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'CUSTOMER_TIER' CLASSIFICATION_TYPE_CODE, 'CORPORATE' CLASSIFICATION_VALUE_CODE, 'مشتری شرکتی' NAME_FA, 'Corporate' NAME_EN, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'CUSTOMER_TIER' CLASSIFICATION_TYPE_CODE, 'VIP' CLASSIFICATION_VALUE_CODE, 'مشتری ویژه' NAME_FA, 'VIP' NAME_EN, 40 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'AGRICULTURE' CLASSIFICATION_VALUE_CODE, 'کشاورزی، جنگلداری و شیلات' NAME_FA, 'Agriculture, forestry and fishing' NAME_EN, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'MANUFACTURING' CLASSIFICATION_VALUE_CODE, 'تولید و صنایع کارخانه‌ای' NAME_FA, 'Manufacturing' NAME_EN, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'CONSTRUCTION' CLASSIFICATION_VALUE_CODE, 'ساختمان و ساخت‌وساز' NAME_FA, 'Construction' NAME_EN, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'TRADE' CLASSIFICATION_VALUE_CODE, 'عمده‌فروشی و خرده‌فروشی' NAME_FA, 'Wholesale and retail trade' NAME_EN, 40 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'TRANSPORT_LOGISTICS' CLASSIFICATION_VALUE_CODE, 'حمل‌ونقل و لجستیک' NAME_FA, 'Transportation and logistics' NAME_EN, 50 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'INFORMATION_TECHNOLOGY' CLASSIFICATION_VALUE_CODE, 'اطلاعات و فناوری' NAME_FA, 'Information and technology' NAME_EN, 60 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'FINANCIAL_SERVICES' CLASSIFICATION_VALUE_CODE, 'خدمات مالی و بیمه' NAME_FA, 'Financial and insurance services' NAME_EN, 70 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'PROFESSIONAL_SERVICES' CLASSIFICATION_VALUE_CODE, 'خدمات حرفه‌ای و تخصصی' NAME_FA, 'Professional services' NAME_EN, 80 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'INDUSTRY' CLASSIFICATION_TYPE_CODE, 'OTHER_SERVICES' CLASSIFICATION_VALUE_CODE, 'سایر خدمات' NAME_FA, 'Other services' NAME_EN, 90 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RISK_CLASS' CLASSIFICATION_TYPE_CODE, 'LOW_RISK' CLASSIFICATION_VALUE_CODE, 'ریسک پایین' NAME_FA, 'Low Risk' NAME_EN, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RISK_CLASS' CLASSIFICATION_TYPE_CODE, 'MEDIUM_RISK' CLASSIFICATION_VALUE_CODE, 'ریسک متوسط' NAME_FA, 'Medium Risk' NAME_EN, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RISK_CLASS' CLASSIFICATION_TYPE_CODE, 'HIGH_RISK' CLASSIFICATION_VALUE_CODE, 'ریسک بالا' NAME_FA, 'High Risk' NAME_EN, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RELATIONSHIP_CLASS' CLASSIFICATION_TYPE_CODE, 'STANDARD' CLASSIFICATION_VALUE_CODE, 'رابطه عادی' NAME_FA, 'Standard Relationship' NAME_EN, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RELATIONSHIP_CLASS' CLASSIFICATION_TYPE_CODE, 'PREFERRED' CLASSIFICATION_VALUE_CODE, 'رابطه ترجیحی' NAME_FA, 'Preferred Relationship' NAME_EN, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RELATIONSHIP_CLASS' CLASSIFICATION_TYPE_CODE, 'SPECIAL' CLASSIFICATION_VALUE_CODE, 'رابطه ویژه' NAME_FA, 'Special Relationship' NAME_EN, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'RELATIONSHIP_CLASS' CLASSIFICATION_TYPE_CODE, 'STRATEGIC' CLASSIFICATION_VALUE_CODE, 'رابطه راهبردی' NAME_FA, 'Strategic Relationship' NAME_EN, 40 SORT_ORDER FROM DUAL
) S
ON (T.CLASSIFICATION_TYPE_CODE=S.CLASSIFICATION_TYPE_CODE AND T.CLASSIFICATION_VALUE_CODE=S.CLASSIFICATION_VALUE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (CLASSIFICATION_TYPE_CODE,CLASSIFICATION_VALUE_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.CLASSIFICATION_TYPE_CODE,S.CLASSIFICATION_VALUE_CODE,S.NAME_FA,S.NAME_EN,NULL,S.SORT_ORDER,1,NULL,NULL,NULL,1);

MERGE INTO CIF.REF_ASSIGNMENT_REASON T
USING (
  SELECT 'RULE_BASED' ASSIGNMENT_REASON_CODE, 'قاعده کسب‌وکاری' NAME_FA, 'Rule Based' NAME_EN, 10 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'MANUAL_REVIEW' ASSIGNMENT_REASON_CODE, 'بررسی و تخصیص دستی' NAME_FA, 'Manual Review' NAME_EN, 20 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'MODEL_OUTPUT' ASSIGNMENT_REASON_CODE, 'خروجی مدل یا امتیازدهی' NAME_FA, 'Model Output' NAME_EN, 30 SORT_ORDER FROM DUAL
  UNION ALL
  SELECT 'REGULATORY_REQUIREMENT' ASSIGNMENT_REASON_CODE, 'الزام مقرراتی' NAME_FA, 'Regulatory Requirement' NAME_EN, 40 SORT_ORDER FROM DUAL
) S
ON (T.ASSIGNMENT_REASON_CODE=S.ASSIGNMENT_REASON_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (ASSIGNMENT_REASON_CODE,NAME_FA,NAME_EN,DESCRIPTION_FA,SORT_ORDER,IS_ACTIVE,PARENT_CODE,VALID_FROM,VALID_TO,RECORD_VERSION)
VALUES (S.ASSIGNMENT_REASON_CODE,S.NAME_FA,S.NAME_EN,NULL,S.SORT_ORDER,1,NULL,NULL,NULL,1);

COMMIT;

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM CIF.REF_CLASSIFICATION_TYPE WHERE IS_ACTIVE=1
   AND CLASSIFICATION_TYPE_CODE IN ('CUSTOMER_TIER','INDUSTRY','RISK_CLASS','RELATIONSHIP_CLASS');
  IF V_COUNT <> 4 THEN RAISE_APPLICATION_ERROR(-20171, 'Fix17 classification type seed failed.'); END IF;

  SELECT COUNT(*) INTO V_COUNT FROM CIF.REF_CLASSIFICATION_VALUE WHERE IS_ACTIVE=1
   AND CLASSIFICATION_TYPE_CODE IN ('CUSTOMER_TIER','INDUSTRY','RISK_CLASS','RELATIONSHIP_CLASS');
  IF V_COUNT < 20 THEN RAISE_APPLICATION_ERROR(-20172, 'Fix17 classification value seed incomplete.'); END IF;

  SELECT COUNT(*) INTO V_COUNT FROM CIF.REF_ASSIGNMENT_REASON WHERE IS_ACTIVE=1
   AND ASSIGNMENT_REASON_CODE IN ('RULE_BASED','MANUAL_REVIEW','MODEL_OUTPUT','REGULATORY_REQUIREMENT');
  IF V_COUNT <> 4 THEN RAISE_APPLICATION_ERROR(-20173, 'Fix17 assignment reason seed failed.'); END IF;

  SELECT COUNT(*) INTO V_COUNT FROM ALL_CONSTRAINTS
   WHERE OWNER='CIF' AND TABLE_NAME='PARTY_DOCUMENT' AND CONSTRAINT_NAME='CK_DOC_VERIFY_DATE';
  IF V_COUNT <> 0 THEN RAISE_APPLICATION_ERROR(-20174, 'Fix17 document verify-date constraint was not removed.'); END IF;
END;
/

PROMPT 0.3.22-fix17 completed successfully.
