PROMPT =====================================================================
PROMPT Core Banking Prototype 0.3.22-fix2 - Party address reference alignment
PROMPT =====================================================================

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM ALL_TABLES WHERE OWNER='CIF' AND TABLE_NAME='REF_TENURE_TYPE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CIF.REF_TENURE_TYPE (
        TENURE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
        NAME_FA VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN VARCHAR2(200 CHAR),
        DESCRIPTION_FA VARCHAR2(1000 CHAR),
        SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        PARENT_CODE VARCHAR2(50 CHAR),
        VALID_FROM DATE,
        VALID_TO DATE,
        RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_TENURE_TYPE PRIMARY KEY (TENURE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
        CONSTRAINT CK_TENURE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
        CONSTRAINT CK_TENURE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
        CONSTRAINT CK_TENURE_TYPE_03 CHECK (SORT_ORDER >= 0),
        CONSTRAINT CK_TENURE_TYPE_04 CHECK (RECORD_VERSION >= 1)
      ) TABLESPACE TS_CIF
    ]';
  END IF;
END;
/

MERGE INTO CIF.REF_TENURE_TYPE T
USING (
  SELECT 'OWNER' TENURE_TYPE_CODE, 'مالک' NAME_FA, 'Owner' NAME_EN, 10 SORT_ORDER FROM DUAL UNION ALL
  SELECT 'TENANT', 'مستأجر', 'Tenant', 20 FROM DUAL UNION ALL
  SELECT 'ORGANIZATIONAL', 'سازمانی', 'Organizational', 30 FROM DUAL UNION ALL
  SELECT 'OTHER', 'سایر', 'Other', 40 FROM DUAL
) S
ON (T.TENURE_TYPE_CODE = S.TENURE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET
  T.NAME_FA=S.NAME_FA,
  T.NAME_EN=S.NAME_EN,
  T.SORT_ORDER=S.SORT_ORDER,
  T.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (
  TENURE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER,
  IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION
) VALUES (
  S.TENURE_TYPE_CODE, S.NAME_FA, S.NAME_EN, NULL, S.SORT_ORDER,
  1, NULL, NULL, NULL, 1
);

COMMIT;

PROMPT 0.3.22-fix2 address reference alignment completed.
