-- R20 Lite installed Oracle contract verifier only (READ-ONLY; NO DDL/DML).
-- Run with SYSTEM in FREEPDB1, where RGL SYSTEM-HF1 was already smoke-tested.
SET SERVEROUTPUT ON
PROMPT RGL_R20_CHECK_BEGIN
SELECT SYS_CONTEXT('USERENV','CON_NAME') AS PDB, SYS_CONTEXT('USERENV','SESSION_USER') AS EXECUTOR FROM DUAL;
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='PDL' AND TABLE_NAME IN ('RULE_POLICY_VERSION','RULE_CONTROL_POLICY') ORDER BY TABLE_NAME;
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE FROM ALL_TAB_COLUMNS
 WHERE OWNER='PDL' AND TABLE_NAME='PRODUCT_VERSION' AND COLUMN_NAME='RULE_POLICY_VERSION_ID';
SELECT CONSTRAINT_NAME, STATUS FROM ALL_CONSTRAINTS
 WHERE OWNER='PDL' AND TABLE_NAME='PRODUCT_VERSION' AND CONSTRAINT_NAME='FK_PV_RULE_POLICY_VERSION';
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM ALL_OBJECTS
 WHERE OWNER='PDL' AND OBJECT_NAME IN ('TRG_RPV_FREEZE','TRG_RCP_DRAFT_ONLY') ORDER BY OBJECT_NAME;
SELECT NAME, TYPE, LINE, TEXT FROM ALL_ERRORS
 WHERE OWNER='PDL' AND NAME IN ('TRG_RPV_FREEZE','TRG_RCP_DRAFT_ONLY');
PROMPT RGL_R20_CHECK_END
