-- PB-R14 read-only readiness diagnostic for DPS reference / PDL enum compatibility.
-- SQL Developer or SQL*Plus; no INSERT, UPDATE, DELETE, MERGE, DDL or COMMIT.
SET DEFINE OFF;
PROMPT === DPS: live reference codes, titles and active flags ===
SELECT 'OWNERSHIP_TYPE' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_OWNERSHIP_TYPE_CODE ORDER BY CODE;
SELECT 'SIGNING_RULE' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_SIGNING_RULE_CODE ORDER BY CODE;
SELECT 'PROFIT_DISTRIBUTION' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_PROFIT_DISTRIBUTION_CODE ORDER BY CODE;
SELECT 'HOLD_TYPE' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_HOLD_TYPE_CODE ORDER BY CODE;
SELECT 'CLOSURE_TYPE' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_CLOSURE_TYPE_CODE ORDER BY CODE;
SELECT 'BALANCE_DESTINATION' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_BALANCE_DESTINATION_CODE ORDER BY CODE;
SELECT 'RULE_STATUS' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_RULE_STATUS_CODE ORDER BY CODE;
SELECT 'SETTLEMENT_METHOD' AS REFERENCE, CODE, NAME_FA, IS_ACTIVE FROM DPS.REF_SETTLEMENT_METHOD_CODE ORDER BY CODE;
PROMPT === PDL: real Oracle CHECK constraints for affected forms ===
SELECT TABLE_NAME, CONSTRAINT_NAME, SEARCH_CONDITION_VC
  FROM ALL_CONSTRAINTS
 WHERE OWNER='PDL'
   AND TABLE_NAME IN ('DEPOSIT_PRODUCT_JOINT_RULE','DEPOSIT_PRODUCT_HOLD_RULE',
                     'DEPOSIT_PRODUCT_CLOSURE_RULE','DEPOSIT_PRODUCT_CLOSURE_SETTLEMENT_RULE')
   AND CONSTRAINT_TYPE='C'
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;
