-- PB-R13 | READ ONLY diagnostic for the Product Builder deposit forms.
-- Run as an account with SELECT grants on DPS, PDL, FEE. No DML or DDL.
-- Empty/missing active reference options must be fixed in governed reference data;
-- do not insert example IDs from the standalone HTML into live banking tables.
SET SERVEROUTPUT ON
PROMPT == PB-R13 | Governed active CURRENT reference counts ==
SELECT 'REF_DEPOSIT_GROUP_CODE' AS REFERENCE_NAME, COUNT(*) AS CURRENT_ACTIVE_ROWS
FROM DPS.REF_DEPOSIT_GROUP_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_DEPOSIT_TYPE_CODE', COUNT(*)
FROM DPS.REF_DEPOSIT_TYPE_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_WITHDRAWAL_MEDIA_CODE', COUNT(*)
FROM DPS.REF_WITHDRAWAL_MEDIA_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_OWNERSHIP_TYPE_CODE', COUNT(*)
FROM DPS.REF_OWNERSHIP_TYPE_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_SIGNING_RULE_CODE', COUNT(*)
FROM DPS.REF_SIGNING_RULE_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_PROFIT_DISTRIBUTION_CODE', COUNT(*)
FROM DPS.REF_PROFIT_DISTRIBUTION_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_INACTIVITY_PERIOD_UNIT_CODE', COUNT(*)
FROM DPS.REF_INACTIVITY_PERIOD_UNIT_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_WARNING_PERIOD_UNIT_CODE', COUNT(*)
FROM DPS.REF_WARNING_PERIOD_UNIT_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'REF_REACTIVATION_METHOD_CODE', COUNT(*)
FROM DPS.REF_REACTIVATION_METHOD_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1;
PROMPT == PB-R13 | Real governing codes for profile identity ==
SELECT 'DEPOSIT_GROUP' AS REFERENCE, CODE, NAME_FA
FROM DPS.REF_DEPOSIT_GROUP_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
UNION ALL
SELECT 'DEPOSIT_TYPE', CODE, NAME_FA
FROM DPS.REF_DEPOSIT_TYPE_CODE WHERE IS_ACTIVE=1 AND IS_CURRENT=1
ORDER BY 1,2;
PROMPT == PB-R13 | Active fee definition versions eligible for dormancy ==
SELECT V.FEE_DEFINITION_VERSION_ID, V.VERSION_NO, V.FEE_PLAN_NAME, D.FEE_CODE, D.NAME_FA
FROM FEE.FEE_DEFINITION_VERSION V
JOIN FEE.FEE_DEFINITION D ON D.FEE_DEFINITION_ID=V.FEE_DEFINITION_ID
WHERE V.STATUS_CODE='ACTIVE' AND D.IS_ACTIVE='Y'
  AND V.EFFECTIVE_FROM<=TRUNC(SYSDATE)
  AND (V.EFFECTIVE_TO IS NULL OR V.EFFECTIVE_TO>=TRUNC(SYSDATE))
  AND (UPPER(D.FEE_CODE) LIKE '%DORM%' OR UPPER(D.FEE_CODE) LIKE '%INACT%'
       OR UPPER(NVL(D.CATEGORY_CODE,'-')) LIKE '%DORM%'
       OR D.NAME_FA LIKE '%راکد%' OR V.FEE_PLAN_NAME LIKE '%راکد%'
       OR UPPER(NVL(V.FEE_PLAN_TYPE_CODE,'-')) LIKE '%DORM%')
ORDER BY D.NAME_FA, V.VERSION_NO DESC;
PROMPT == PB-R13 | Profile of reported PRODUCT_VERSION_ID 26 ==
SELECT V.PRODUCT_VERSION_ID, V.PRODUCT_ID, P.PRODUCT_FAMILY_CODE,
       CASE P.PRODUCT_FAMILY_CODE
         WHEN 'QARD_SAVINGS' THEN 'QARD_HASAN/SAVINGS'
         WHEN 'CURRENT_ACCOUNT' THEN 'CURRENT/CURRENT_NO_INTEREST'
         WHEN 'SHORT_TERM_DEPOSIT' THEN 'SHORT_TERM/SHORT_TERM_DEPOSIT'
         WHEN 'LONG_TERM_DEPOSIT' THEN 'LONG_TERM/LONG_TERM_DEPOSIT'
         WHEN 'CERTIFICATE_OF_DEPOSIT' THEN 'CERTIFICATE/CERTIFICATE_OF_DEPOSIT'
         WHEN 'SAVINGS' THEN 'QARD_HASAN/SAVINGS (legacy)'
         WHEN 'CURRENT' THEN 'CURRENT/CURRENT_NO_INTEREST (legacy)'
         ELSE 'NOT GOVERNED / REQUIRE DOMAIN REVIEW' END AS PROFILE_IDENTITY
FROM PDL.PRODUCT_VERSION V
JOIN PDL.PRODUCT P ON P.PRODUCT_ID=V.PRODUCT_ID
WHERE V.PRODUCT_VERSION_ID=26;
PROMPT == PB-R13 | Completed READ-ONLY diagnostics ==
