package com.behsazan.corebanking.deposit.account.waved.oracle;

import com.behsazan.corebanking.deposit.account.waved.domain.DepositAccountWaveDModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.*;
import java.util.*;

@Repository
public class DepositAccountWaveDRepository {
    private final NamedParameterJdbcTemplate jdbc; private final String schema,productSchema;
    public DepositAccountWaveDRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.oracle.business-schema:DPS2}") String schema,@Value("${core-banking.schemas.product-definition:PDL}") String productSchema){this.jdbc=jdbc;this.schema=id(schema);this.productSchema=id(productSchema);}
    public long next(String seq){return jdbc.queryForObject("SELECT "+schema+"."+id(seq)+".NEXTVAL FROM DUAL",Map.of(),Long.class);}
    public boolean accountExists(long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),Long.class);return n!=null&&n>0;}
    public String accountCurrency(long accountId){return jdbc.queryForObject("SELECT CURRENCY_CODE FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),String.class);}
    public String accountNo(long accountId){return jdbc.queryForObject("SELECT ACCOUNT_NO FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),String.class);}
    public Long currentProductVersion(long accountId){return jdbc.queryForObject("SELECT CURRENT_PRODUCT_VERSION_ID FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),Long.class);}
    public BigDecimal ledgerBalance(long accountId){BigDecimal v=jdbc.queryForObject("SELECT LEDGER_BALANCE FROM "+schema+".DEPOSIT_ACCOUNT_BALANCE WHERE ACCOUNT_ID=:id",Map.of("id",accountId),BigDecimal.class);return v==null?BigDecimal.ZERO:v;}
    public BigDecimal transactionAmount(long txId){return jdbc.queryForObject("SELECT AMOUNT FROM "+schema+".DEPOSIT_TRANSACTION WHERE TRANSACTION_ID=:id",Map.of("id",txId),BigDecimal.class);}
    public boolean postedTransaction(long accountId,long txId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_TRANSACTION WHERE TRANSACTION_ID=:tx AND ACCOUNT_ID=:aid AND TRANSACTION_STATUS_CODE='POSTED'",new MapSqlParameterSource().addValue("tx",txId).addValue("aid",accountId),Long.class);return n!=null&&n>0;}

    public Long correspondentProductVersion(String accountType,String currency){String sql="SELECT PRODUCT_VERSION_ID FROM "+productSchema+".CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE WHERE ACCOUNT_TYPE_CODE=:type AND SETTLEMENT_CURRENCY_CODE=:cur ORDER BY CORRESPONDENT_PRODUCT_PROFILE_ID DESC FETCH FIRST 1 ROWS ONLY";return jdbc.query(sql,new MapSqlParameterSource().addValue("type",accountType).addValue("cur",currency),(r,n)->r.getLong(1)).stream().findFirst().orElse(null);}
    public void insertCorrespondentAccountMaster(long accountId,String accountNo,long productVersionId,String currency,String accountName,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT(ACCOUNT_ID,ACCOUNT_NO,OPENING_REQUEST_ID,PRODUCT_VERSION_ID,CURRENCY_CODE,OPENING_AMOUNT,ACCOUNT_STATUS_CODE,ACTIVATED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION,OPENED_PRODUCT_VERSION_ID,CURRENT_PRODUCT_VERSION_ID,OWNERSHIP_TYPE_CODE,OPENED_ON,LEDGER_BALANCE,AVAILABLE_BALANCE,OPENING_ORG_UNIT_CODE,ACCOUNT_NAME,ORG_UNIT_CODE) VALUES(:id,:no,NULL,:pv,:cur,0,'ACTIVE',SYSTIMESTAMP,SYSTIMESTAMP,:actor,1,:pv,:pv,'INDIVIDUAL',TRUNC(SYSDATE),0,0,'HO',:name,'HO')";jdbc.update(sql,new MapSqlParameterSource().addValue("id",accountId).addValue("no",accountNo).addValue("pv",productVersionId).addValue("cur",currency).addValue("actor",actor).addValue("name",accountName));}

    public void insertReconRun(long id,LocalDate date,String type,String source,String target,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_RECONCILIATION_RUN(RECONCILIATION_RUN_ID,BUSINESS_DATE,RECONCILIATION_TYPE_CODE,SOURCE_SYSTEM_CODE,TARGET_LEDGER_CODE,STATUS_CODE,STARTED_AT,TOTAL_SOURCE_AMOUNT,TOTAL_TARGET_AMOUNT,DIFFERENCE_AMOUNT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:bd,:type,:src,:target,'IN_PROGRESS',SYSTIMESTAMP,0,0,0,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("bd",Date.valueOf(date)).addValue("type",type).addValue("src",source).addValue("target",target).addValue("actor",actor));}
    public Long findReconRun(LocalDate date,String type,String source,String target){String sql="SELECT RECONCILIATION_RUN_ID FROM "+schema+".DEPOSIT_RECONCILIATION_RUN WHERE BUSINESS_DATE=:bd AND RECONCILIATION_TYPE_CODE=:type AND SOURCE_SYSTEM_CODE=:src AND TARGET_LEDGER_CODE=:target";return jdbc.query(sql,new MapSqlParameterSource().addValue("bd",Date.valueOf(date)).addValue("type",type).addValue("src",source).addValue("target",target),(r,n)->r.getLong(1)).stream().findFirst().orElse(null);}
    public void insertReconItem(long id,long runId,long accountId,String sourceRef,String targetRef,BigDecimal sourceAmount,BigDecimal targetAmount,String match,String discrepancyType,String actor){BigDecimal diff=nvl(sourceAmount).subtract(nvl(targetAmount));String sql="INSERT INTO "+schema+".DEPOSIT_RECONCILIATION_ITEM(RECONCILIATION_ITEM_ID,RECONCILIATION_RUN_ID,ACCOUNT_ID,SOURCE_REFERENCE,TARGET_REFERENCE,SOURCE_AMOUNT,TARGET_AMOUNT,DIFFERENCE_AMOUNT,MATCH_STATUS_CODE,DISCREPANCY_TYPE_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:run,:aid,:sr,:tr,:sa,:ta,:diff,:match,:dtype,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("run",runId).addValue("aid",accountId).addValue("sr",sourceRef,Types.VARCHAR).addValue("tr",targetRef,Types.VARCHAR).addValue("sa",sourceAmount,Types.NUMERIC).addValue("ta",targetAmount,Types.NUMERIC).addValue("diff",diff).addValue("match",match).addValue("dtype",discrepancyType,Types.VARCHAR).addValue("actor",actor));}
    public void insertDiscrepancy(long id,long itemId,String type,BigDecimal expected,BigDecimal actual,String severity,String actor){BigDecimal diff=nvl(expected).subtract(nvl(actual));String sql="INSERT INTO "+schema+".DEPOSIT_DISCREPANCY(DISCREPANCY_ID,RECONCILIATION_ITEM_ID,DISCREPANCY_TYPE_CODE,EXPECTED_AMOUNT,ACTUAL_AMOUNT,DIFFERENCE_AMOUNT,SEVERITY_CODE,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:item,:type,:exp,:act,:diff,:sev,'OPEN',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("item",itemId).addValue("type",type).addValue("exp",expected,Types.NUMERIC).addValue("act",actual,Types.NUMERIC).addValue("diff",diff).addValue("sev",severity).addValue("actor",actor));}
    public void insertSuspense(long id,long accountId,String code,String ref,BigDecimal amount,String currency,OffsetDateTime due,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_SUSPENSE_OPEN_ITEM(SUSPENSE_OPEN_ITEM_ID,ACCOUNT_ID,SUSPENSE_ACCOUNT_CODE,SOURCE_REFERENCE,AMOUNT,CURRENCY_CODE,OPENED_AT,SLA_DUE_AT,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:code,:ref,:amt,:cur,SYSTIMESTAMP,:due,'OPEN',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("code",code).addValue("ref",ref).addValue("amt",amount).addValue("cur",currency).addValue("due",ts(due),Types.TIMESTAMP).addValue("actor",actor));}
    public ReconItemSuspenseSource reconciliationItemForSuspense(long itemId,long accountId){String sql="SELECT I.RECONCILIATION_ITEM_ID,I.SOURCE_REFERENCE,I.DIFFERENCE_AMOUNT,I.MATCH_STATUS_CODE FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM I WHERE I.RECONCILIATION_ITEM_ID=:iid AND I.ACCOUNT_ID=:aid";return jdbc.query(sql,new MapSqlParameterSource().addValue("iid",itemId).addValue("aid",accountId),(r,n)->new ReconItemSuspenseSource(r.getLong(1),r.getString(2),r.getBigDecimal(3),r.getString(4))).stream().findFirst().orElse(null);}
    public Long existingSuspenseId(String code,String sourceReference){String sql="SELECT SUSPENSE_OPEN_ITEM_ID FROM "+schema+".DEPOSIT_SUSPENSE_OPEN_ITEM WHERE SUSPENSE_ACCOUNT_CODE=:code AND SOURCE_REFERENCE=:ref";return jdbc.query(sql,new MapSqlParameterSource().addValue("code",code).addValue("ref",sourceReference),(r,n)->r.getLong(1)).stream().findFirst().orElse(null);}
    public void completeReconRun(long runId,String actor){String sql="UPDATE "+schema+".DEPOSIT_RECONCILIATION_RUN R SET STATUS_CODE='COMPLETED',COMPLETED_AT=SYSTIMESTAMP,TOTAL_SOURCE_AMOUNT=(SELECT NVL(SUM(NVL(SOURCE_AMOUNT,0)),0) FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM I WHERE I.RECONCILIATION_RUN_ID=R.RECONCILIATION_RUN_ID),TOTAL_TARGET_AMOUNT=(SELECT NVL(SUM(NVL(TARGET_AMOUNT,0)),0) FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM I WHERE I.RECONCILIATION_RUN_ID=R.RECONCILIATION_RUN_ID),DIFFERENCE_AMOUNT=(SELECT NVL(SUM(NVL(DIFFERENCE_AMOUNT,0)),0) FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM I WHERE I.RECONCILIATION_RUN_ID=R.RECONCILIATION_RUN_ID),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE RECONCILIATION_RUN_ID=:id";jdbc.update(sql,new MapSqlParameterSource().addValue("actor",actor).addValue("id",runId));}
    public List<ReconciliationRun> reconRuns(long accountId){String sql="SELECT R.RECONCILIATION_RUN_ID,R.BUSINESS_DATE,R.RECONCILIATION_TYPE_CODE,R.SOURCE_SYSTEM_CODE,R.TARGET_LEDGER_CODE,R.STATUS_CODE,R.TOTAL_SOURCE_AMOUNT,R.TOTAL_TARGET_AMOUNT,R.DIFFERENCE_AMOUNT,R.STARTED_AT,R.COMPLETED_AT FROM "+schema+".DEPOSIT_RECONCILIATION_RUN R WHERE EXISTS (SELECT 1 FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM I WHERE I.RECONCILIATION_RUN_ID=R.RECONCILIATION_RUN_ID AND I.ACCOUNT_ID=:id) OR EXISTS (SELECT 1 FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY O WHERE O.ACCOUNT_ID=:id AND O.OPERATION_TYPE_CODE='RECONCILIATION_RUN' AND O.PROCESSING_STATUS_CODE='COMPLETED' AND O.RESULT_REFERENCE='RECONRUN:'||TO_CHAR(R.RECONCILIATION_RUN_ID)) ORDER BY R.RECONCILIATION_RUN_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ReconciliationRun(r.getLong(1),date(r.getDate(2)),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),offset(r.getTimestamp(10)),offset(r.getTimestamp(11))));}
    public List<ReconciliationItem> reconItems(long accountId){String sql="SELECT RECONCILIATION_ITEM_ID,RECONCILIATION_RUN_ID,ACCOUNT_ID,SOURCE_REFERENCE,TARGET_REFERENCE,SOURCE_AMOUNT,TARGET_AMOUNT,DIFFERENCE_AMOUNT,MATCH_STATUS_CODE,DISCREPANCY_TYPE_CODE FROM "+schema+".DEPOSIT_RECONCILIATION_ITEM WHERE ACCOUNT_ID=:id ORDER BY RECONCILIATION_ITEM_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ReconciliationItem(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getString(9),r.getString(10)));}
    public List<Discrepancy> discrepancies(long accountId){String sql="SELECT D.DISCREPANCY_ID,D.RECONCILIATION_ITEM_ID,D.DISCREPANCY_TYPE_CODE,D.EXPECTED_AMOUNT,D.ACTUAL_AMOUNT,D.DIFFERENCE_AMOUNT,D.SEVERITY_CODE,D.STATUS_CODE,D.EXCEPTION_CASE_ID FROM "+schema+".DEPOSIT_DISCREPANCY D JOIN "+schema+".DEPOSIT_RECONCILIATION_ITEM I ON I.RECONCILIATION_ITEM_ID=D.RECONCILIATION_ITEM_ID WHERE I.ACCOUNT_ID=:id ORDER BY D.DISCREPANCY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Discrepancy(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getString(7),r.getString(8),r.getObject(9,Long.class)));}
    public List<SuspenseOpenItem> suspense(long accountId){String sql="SELECT SUSPENSE_OPEN_ITEM_ID,ACCOUNT_ID,SUSPENSE_ACCOUNT_CODE,SOURCE_REFERENCE,AMOUNT,CURRENCY_CODE,STATUS_CODE,RESOLUTION_REFERENCE FROM "+schema+".DEPOSIT_SUSPENSE_OPEN_ITEM WHERE ACCOUNT_ID=:id ORDER BY SUSPENSE_OPEN_ITEM_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new SuspenseOpenItem(r.getLong(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getBigDecimal(5),r.getString(6),r.getString(7),r.getString(8)));}

    public long insertException(long id,long accountId,Long tx,String type,String reason,String severity,String queue,OffsetDateTime due,String actor){String no="EXC-"+id;String sql="INSERT INTO "+schema+".DEPOSIT_EXCEPTION_CASE(EXCEPTION_CASE_ID,CASE_NO,ACCOUNT_ID,TRANSACTION_ID,EXCEPTION_TYPE_CODE,REASON_CODE,SEVERITY_CODE,QUEUE_CODE,SLA_DUE_AT,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:no,:aid,:tx,:type,:reason,:sev,:queue,:due,'OPEN',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("no",no).addValue("aid",accountId).addValue("tx",tx,Types.NUMERIC).addValue("type",type).addValue("reason",reason).addValue("sev",severity).addValue("queue",queue).addValue("due",ts(due),Types.TIMESTAMP).addValue("actor",actor));return id;}
    public void linkDiscrepancy(long discrepancyId,long exceptionId,String actor){jdbc.update("UPDATE "+schema+".DEPOSIT_DISCREPANCY SET EXCEPTION_CASE_ID=:exc,STATUS_CODE='REFERRED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE DISCREPANCY_ID=:id AND EXCEPTION_CASE_ID IS NULL",new MapSqlParameterSource().addValue("exc",exceptionId).addValue("actor",actor).addValue("id",discrepancyId));}
    public void insertAssignment(long id,long exceptionId,String queue,String assignee,OffsetDateTime due,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_EXCEPTION_ASSIGNMENT(EXCEPTION_ASSIGNMENT_ID,EXCEPTION_CASE_ID,QUEUE_CODE,ASSIGNEE_REFERENCE,ASSIGNED_AT,SLA_DUE_AT,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:exc,:queue,:assignee,SYSTIMESTAMP,:due,'ASSIGNED',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("exc",exceptionId).addValue("queue",queue).addValue("assignee",assignee,Types.VARCHAR).addValue("due",ts(due),Types.TIMESTAMP).addValue("actor",actor));}
    public void insertCorrectionRequest(long id,long accountId,Long tx,Long exc,String type,String reason,LocalDate date,String requestedBy,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_CORRECTION_REQUEST(CORRECTION_REQUEST_ID,REQUEST_NO,ACCOUNT_ID,ORIGINAL_TRANSACTION_ID,EXCEPTION_CASE_ID,CORRECTION_TYPE_CODE,REASON_CODE,REQUESTED_EFFECTIVE_DATE,REQUESTED_BY,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:no,:aid,:tx,:exc,:type,:reason,:ed,:req,'PENDING_APPROVAL',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("no","COR-"+id).addValue("aid",accountId).addValue("tx",tx,Types.NUMERIC).addValue("exc",exc,Types.NUMERIC).addValue("type",type).addValue("reason",reason).addValue("ed",Date.valueOf(date)).addValue("req",requestedBy).addValue("actor",actor));}
    public void insertCorrectionAuthorization(long id,long reqId,String approver,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_CORRECTION_AUTHORIZATION(CORRECTION_AUTHORIZATION_ID,CORRECTION_REQUEST_ID,AUTHORIZATION_LEVEL,DECISION_CODE,DECIDED_BY,DECIDED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:req,1,'PENDING',:approver,SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("req",reqId).addValue("approver",approver).addValue("actor",actor));}
    public CorrectionLock correction(long accountId,long id){String sql="SELECT C.CORRECTION_REQUEST_ID,C.ORIGINAL_TRANSACTION_ID,C.CORRECTION_TYPE_CODE,C.REQUESTED_EFFECTIVE_DATE,C.STATUS_CODE,C.RECORD_VERSION,A.CORRECTION_AUTHORIZATION_ID,A.DECIDED_BY,A.DECISION_CODE,A.RECORD_VERSION FROM "+schema+".DEPOSIT_CORRECTION_REQUEST C JOIN "+schema+".DEPOSIT_CORRECTION_AUTHORIZATION A ON A.CORRECTION_REQUEST_ID=C.CORRECTION_REQUEST_ID AND A.AUTHORIZATION_LEVEL=1 WHERE C.ACCOUNT_ID=:aid AND C.CORRECTION_REQUEST_ID=:id FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("id",id),(r,n)->new CorrectionLock(r.getLong(1),r.getObject(2,Long.class),r.getString(3),date(r.getDate(4)),r.getString(5),r.getLong(6),r.getLong(7),r.getString(8),r.getString(9),r.getLong(10))).stream().findFirst().orElse(null);}
    public int approveCorrection(CorrectionLock c,String actor){int a=jdbc.update("UPDATE "+schema+".DEPOSIT_CORRECTION_AUTHORIZATION SET DECISION_CODE='APPROVED',DECIDED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE CORRECTION_AUTHORIZATION_ID=:id AND RECORD_VERSION=:ver AND DECISION_CODE='PENDING' AND DECIDED_BY=:actor",new MapSqlParameterSource().addValue("actor",actor).addValue("id",c.authorizationId()).addValue("ver",c.authorizationVersion()));if(a!=1)return 0;return jdbc.update("UPDATE "+schema+".DEPOSIT_CORRECTION_REQUEST SET STATUS_CODE='APPROVED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE CORRECTION_REQUEST_ID=:id AND RECORD_VERSION=:ver AND STATUS_CODE='PENDING_APPROVAL'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",c.id()).addValue("ver",c.version()));}
    public void insertCorrectionEntry(long id,long reqId,Long original,Long corrective,String type,LocalDate effective,BigDecimal amount,String posting,String audit,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_CORRECTION_ENTRY(CORRECTION_ENTRY_ID,CORRECTION_REQUEST_ID,ORIGINAL_TRANSACTION_ID,CORRECTIVE_TRANSACTION_ID,ENTRY_TYPE_CODE,EFFECTIVE_DATE,BOOKING_TIMESTAMP,AMOUNT,POSTING_REFERENCE,AUDIT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:req,:orig,:corr,:type,:ed,SYSTIMESTAMP,:amt,:posting,:audit,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("req",reqId).addValue("orig",original,Types.NUMERIC).addValue("corr",corrective,Types.NUMERIC).addValue("type",type).addValue("ed",Date.valueOf(effective)).addValue("amt",amount,Types.NUMERIC).addValue("posting",posting,Types.VARCHAR).addValue("audit",audit).addValue("actor",actor));jdbc.update("UPDATE "+schema+".DEPOSIT_CORRECTION_REQUEST SET STATUS_CODE='EXECUTED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE CORRECTION_REQUEST_ID=:id",new MapSqlParameterSource().addValue("actor",actor).addValue("id",reqId));}
    public void upsertRootCause(long id,long exceptionId,String code,String description,String corrective,String preventive,String owner,LocalDate target,String actor){String sql="MERGE INTO "+schema+".DEPOSIT_ROOT_CAUSE_ANALYSIS T USING(SELECT :exc EXCEPTION_CASE_ID FROM DUAL) S ON(T.EXCEPTION_CASE_ID=S.EXCEPTION_CASE_ID) WHEN MATCHED THEN UPDATE SET ROOT_CAUSE_CODE=:code,ROOT_CAUSE_DESCRIPTION=:descr,CORRECTIVE_ACTION=:corr,PREVENTIVE_ACTION=:prev,OWNER_REFERENCE=:owner,TARGET_DATE=:target,STATUS_CODE='OPEN',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=T.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(ROOT_CAUSE_ANALYSIS_ID,EXCEPTION_CASE_ID,ROOT_CAUSE_CODE,ROOT_CAUSE_DESCRIPTION,CORRECTIVE_ACTION,PREVENTIVE_ACTION,OWNER_REFERENCE,TARGET_DATE,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:exc,:code,:descr,:corr,:prev,:owner,:target,'OPEN',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("exc",exceptionId).addValue("code",code).addValue("descr",description).addValue("corr",corrective,Types.VARCHAR).addValue("prev",preventive,Types.VARCHAR).addValue("owner",owner,Types.VARCHAR).addValue("target",target==null?null:Date.valueOf(target),Types.DATE).addValue("actor",actor));}
    public List<ExceptionCase> exceptionCases(long accountId){String sql="SELECT EXCEPTION_CASE_ID,CASE_NO,ACCOUNT_ID,TRANSACTION_ID,EXCEPTION_TYPE_CODE,REASON_CODE,SEVERITY_CODE,QUEUE_CODE,STATUS_CODE,RESOLUTION_CODE FROM "+schema+".DEPOSIT_EXCEPTION_CASE WHERE ACCOUNT_ID=:id ORDER BY EXCEPTION_CASE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ExceptionCase(r.getLong(1),r.getString(2),r.getObject(3,Long.class),r.getObject(4,Long.class),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10)));}
    public List<ExceptionAssignment> assignments(long accountId){String sql="SELECT A.EXCEPTION_ASSIGNMENT_ID,A.EXCEPTION_CASE_ID,A.QUEUE_CODE,A.ASSIGNEE_REFERENCE,A.ASSIGNED_AT,A.SLA_DUE_AT,A.COMPLETED_AT,A.STATUS_CODE FROM "+schema+".DEPOSIT_EXCEPTION_ASSIGNMENT A JOIN "+schema+".DEPOSIT_EXCEPTION_CASE C ON C.EXCEPTION_CASE_ID=A.EXCEPTION_CASE_ID WHERE C.ACCOUNT_ID=:id ORDER BY A.EXCEPTION_ASSIGNMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ExceptionAssignment(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),offset(r.getTimestamp(5)),offset(r.getTimestamp(6)),offset(r.getTimestamp(7)),r.getString(8)));}
    public List<Correction> corrections(long accountId){String sql="SELECT CORRECTION_REQUEST_ID,REQUEST_NO,ACCOUNT_ID,ORIGINAL_TRANSACTION_ID,EXCEPTION_CASE_ID,CORRECTION_TYPE_CODE,REASON_CODE,REQUESTED_EFFECTIVE_DATE,REQUESTED_BY,STATUS_CODE FROM "+schema+".DEPOSIT_CORRECTION_REQUEST WHERE ACCOUNT_ID=:id ORDER BY CORRECTION_REQUEST_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Correction(r.getLong(1),r.getString(2),r.getLong(3),r.getObject(4,Long.class),r.getObject(5,Long.class),r.getString(6),r.getString(7),date(r.getDate(8)),r.getString(9),r.getString(10)));}
    public List<CorrectionAuthorization> authorizations(long accountId){String sql="SELECT A.CORRECTION_AUTHORIZATION_ID,A.CORRECTION_REQUEST_ID,A.AUTHORIZATION_LEVEL,A.DECISION_CODE,A.DECIDED_BY,A.DECIDED_AT,A.DECISION_REASON_CODE FROM "+schema+".DEPOSIT_CORRECTION_AUTHORIZATION A JOIN "+schema+".DEPOSIT_CORRECTION_REQUEST C ON C.CORRECTION_REQUEST_ID=A.CORRECTION_REQUEST_ID WHERE C.ACCOUNT_ID=:id ORDER BY A.CORRECTION_AUTHORIZATION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new CorrectionAuthorization(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),offset(r.getTimestamp(6)),r.getString(7)));}
    public List<CorrectionEntry> correctionEntries(long accountId){String sql="SELECT E.CORRECTION_ENTRY_ID,E.CORRECTION_REQUEST_ID,E.ORIGINAL_TRANSACTION_ID,E.CORRECTIVE_TRANSACTION_ID,E.ENTRY_TYPE_CODE,E.EFFECTIVE_DATE,E.AMOUNT,E.POSTING_REFERENCE,E.AUDIT_REFERENCE FROM "+schema+".DEPOSIT_CORRECTION_ENTRY E JOIN "+schema+".DEPOSIT_CORRECTION_REQUEST C ON C.CORRECTION_REQUEST_ID=E.CORRECTION_REQUEST_ID WHERE C.ACCOUNT_ID=:id ORDER BY E.CORRECTION_ENTRY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new CorrectionEntry(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getObject(4,Long.class),r.getString(5),date(r.getDate(6)),r.getBigDecimal(7),r.getString(8),r.getString(9)));}
    public List<RootCause> rootCauses(long accountId){String sql="SELECT R.ROOT_CAUSE_ANALYSIS_ID,R.EXCEPTION_CASE_ID,R.ROOT_CAUSE_CODE,R.ROOT_CAUSE_DESCRIPTION,R.CORRECTIVE_ACTION,R.PREVENTIVE_ACTION,R.OWNER_REFERENCE,R.TARGET_DATE,R.STATUS_CODE FROM "+schema+".DEPOSIT_ROOT_CAUSE_ANALYSIS R JOIN "+schema+".DEPOSIT_EXCEPTION_CASE C ON C.EXCEPTION_CASE_ID=R.EXCEPTION_CASE_ID WHERE C.ACCOUNT_ID=:id ORDER BY R.ROOT_CAUSE_ANALYSIS_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new RootCause(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),date(r.getDate(8)),r.getString(9)));}

    public void upsertCorrespondent(long extId,long profileId,long accountId,String type,long bankParty,String bic,String externalRef,String currency,String statement,String frequency,boolean autoMatch,BigDecimal tolerance,String actor){String ext="MERGE INTO "+schema+".CORRESPONDENT_ACCOUNT_EXTENSION T USING(SELECT :aid ACCOUNT_ID FROM DUAL) S ON(T.ACCOUNT_ID=S.ACCOUNT_ID) WHEN MATCHED THEN UPDATE SET ACCOUNT_TYPE_CODE=:type,CORRESPONDENT_BANK_PARTY_ID=:bank,CORRESPONDENT_BIC=:bic,EXTERNAL_ACCOUNT_REFERENCE=:eref,SETTLEMENT_CURRENCY_CODE=:cur,RECONCILIATION_STATUS_CODE='READY',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=T.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(CORRESPONDENT_ACCOUNT_EXTENSION_ID,ACCOUNT_ID,ACCOUNT_TYPE_CODE,CORRESPONDENT_BANK_PARTY_ID,CORRESPONDENT_BIC,EXTERNAL_ACCOUNT_REFERENCE,SETTLEMENT_CURRENCY_CODE,RECONCILIATION_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:eid,:aid,:type,:bank,:bic,:eref,:cur,'READY',SYSTIMESTAMP,:actor,1)";MapSqlParameterSource p=new MapSqlParameterSource().addValue("eid",extId).addValue("aid",accountId).addValue("type",type).addValue("bank",bankParty).addValue("bic",bic,Types.VARCHAR).addValue("eref",externalRef).addValue("cur",currency).addValue("actor",actor);jdbc.update(ext,p);Long actual=jdbc.queryForObject("SELECT CORRESPONDENT_ACCOUNT_EXTENSION_ID FROM "+schema+".CORRESPONDENT_ACCOUNT_EXTENSION WHERE ACCOUNT_ID=:aid",Map.of("aid",accountId),Long.class);String prof="MERGE INTO "+schema+".CORRESPONDENT_RECONCILIATION_PROFILE T USING(SELECT :ext CORRESPONDENT_ACCOUNT_EXTENSION_ID FROM DUAL) S ON(T.CORRESPONDENT_ACCOUNT_EXTENSION_ID=S.CORRESPONDENT_ACCOUNT_EXTENSION_ID) WHEN MATCHED THEN UPDATE SET STATEMENT_SOURCE_CODE=:stmt,RECONCILIATION_FREQUENCY_CODE=:freq,AUTO_MATCH_ALLOWED=:auto,TOLERANCE_AMOUNT=:tol,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=T.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(CORRESPONDENT_RECON_PROFILE_ID,CORRESPONDENT_ACCOUNT_EXTENSION_ID,STATEMENT_SOURCE_CODE,RECONCILIATION_FREQUENCY_CODE,AUTO_MATCH_ALLOWED,TOLERANCE_AMOUNT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:pid,:ext,:stmt,:freq,:auto,:tol,SYSTIMESTAMP,:actor,1)";jdbc.update(prof,new MapSqlParameterSource().addValue("pid",profileId).addValue("ext",actual).addValue("stmt",statement).addValue("freq",frequency).addValue("auto",autoMatch?1:0).addValue("tol",tolerance).addValue("actor",actor));}
    public List<Correspondent> correspondents(long accountId){String sql="SELECT E.CORRESPONDENT_ACCOUNT_EXTENSION_ID,E.ACCOUNT_ID,E.ACCOUNT_TYPE_CODE,E.CORRESPONDENT_BANK_PARTY_ID,E.CORRESPONDENT_BIC,E.EXTERNAL_ACCOUNT_REFERENCE,E.SETTLEMENT_CURRENCY_CODE,E.RECONCILIATION_STATUS_CODE,P.CORRESPONDENT_RECON_PROFILE_ID,P.STATEMENT_SOURCE_CODE,P.RECONCILIATION_FREQUENCY_CODE,P.AUTO_MATCH_ALLOWED,P.TOLERANCE_AMOUNT,P.LAST_RECONCILED_AT FROM "+schema+".CORRESPONDENT_ACCOUNT_EXTENSION E LEFT JOIN "+schema+".CORRESPONDENT_RECONCILIATION_PROFILE P ON P.CORRESPONDENT_ACCOUNT_EXTENSION_ID=E.CORRESPONDENT_ACCOUNT_EXTENSION_ID WHERE E.ACCOUNT_ID=:id";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Correspondent(r.getLong(1),r.getLong(2),r.getString(3),r.getLong(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getObject(9,Long.class),r.getString(10),r.getString(11),r.getObject(12)==null?null:r.getInt(12)==1,r.getBigDecimal(13),offset(r.getTimestamp(14))));}

    public void insertRewardProgram(long id,String code,String name,String type,Long productVersion,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_REWARD_PROGRAM(PROGRAM_ID,PROGRAM_CODE,PROGRAM_NAME,PROGRAM_TYPE_CODE,PRODUCT_VERSION_ID,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:code,:name,:type,:pvid,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("code",code).addValue("name",name).addValue("type",type).addValue("pvid",productVersion,Types.NUMERIC).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertRewardEligibilityRule(long id,long programId,BigDecimal minBalance,Integer minDays,boolean excludeDormant,BigDecimal entryUnit,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_REWARD_ELIGIBILITY_RULE(REWARD_ELIGIBILITY_RULE_ID,PROGRAM_ID,MIN_AVERAGE_BALANCE,MIN_ACTIVE_DAYS,EXCLUDE_DORMANT_FLAG,ENTRY_UNIT_AMOUNT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:bal,:days,:dormant,:unit,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",programId).addValue("bal",minBalance).addValue("days",minDays,Types.NUMERIC).addValue("dormant",excludeDormant?1:0).addValue("unit",entryUnit).addValue("actor",actor));}

    public List<RewardProgram> activePrograms(Long productVersionId){String sql="SELECT PROGRAM_ID,PROGRAM_CODE,PROGRAM_NAME,PROGRAM_TYPE_CODE,PRODUCT_VERSION_ID,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE FROM "+schema+".DEPOSIT_REWARD_PROGRAM WHERE STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE)) AND (PRODUCT_VERSION_ID IS NULL OR PRODUCT_VERSION_ID=:pv) ORDER BY PROGRAM_ID DESC";return jdbc.query(sql,new MapSqlParameterSource().addValue("pv",productVersionId,Types.NUMERIC),(r,n)->new RewardProgram(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getObject(5,Long.class),date(r.getDate(6)),date(r.getDate(7)),r.getString(8)));}
    public boolean programApplicable(long programId,long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_REWARD_PROGRAM P JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:aid WHERE P.PROGRAM_ID=:pid AND P.STATUS_CODE='ACTIVE' AND P.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (P.EFFECTIVE_TO IS NULL OR P.EFFECTIVE_TO>=TRUNC(SYSDATE)) AND (P.PRODUCT_VERSION_ID IS NULL OR P.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID)",new MapSqlParameterSource().addValue("aid",accountId).addValue("pid",programId),Long.class);return n!=null&&n>0;}
    public boolean programEligible(long programId,long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_REWARD_PROGRAM P LEFT JOIN "+schema+".DEPOSIT_REWARD_ELIGIBILITY_RULE R ON R.PROGRAM_ID=P.PROGRAM_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:aid WHERE P.PROGRAM_ID=:pid AND P.STATUS_CODE='ACTIVE' AND P.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (P.EFFECTIVE_TO IS NULL OR P.EFFECTIVE_TO>=TRUNC(SYSDATE)) AND (P.PRODUCT_VERSION_ID IS NULL OR P.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND (R.REWARD_ELIGIBILITY_RULE_ID IS NULL OR R.MIN_AVERAGE_BALANCE IS NULL OR (SELECT NVL(SUM(B.LEDGER_BALANCE),0) FROM "+schema+".DEPOSIT_ACCOUNT_BALANCE B WHERE B.ACCOUNT_ID=A.ACCOUNT_ID)>=R.MIN_AVERAGE_BALANCE) AND (R.REWARD_ELIGIBILITY_RULE_ID IS NULL OR R.MIN_ACTIVE_DAYS IS NULL OR TRUNC(SYSDATE)-TRUNC(NVL(A.ACTIVATED_AT,A.CREATED_AT))>=R.MIN_ACTIVE_DAYS) AND (R.REWARD_ELIGIBILITY_RULE_ID IS NULL OR R.EXCLUDE_DORMANT_FLAG=0 OR A.ACCOUNT_STATUS_CODE<>'DORMANT')",new MapSqlParameterSource().addValue("aid",accountId).addValue("pid",programId),Long.class);return n!=null&&n>0;}
    public void insertEnrollment(long id,long programId,long accountId,String consent,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_REWARD_ENROLLMENT(REWARD_ENROLLMENT_ID,PROGRAM_ID,ACCOUNT_ID,ENROLLED_AT,ELIGIBILITY_STATUS_CODE,STATUS_CODE,CONSENT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:aid,SYSTIMESTAMP,'ELIGIBLE','ACTIVE',:consent,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",programId).addValue("aid",accountId).addValue("consent",consent,Types.VARCHAR).addValue("actor",actor));}
    public void upsertEnrollment(long id,long programId,long accountId,String consent,boolean eligible,String actor){String sql="MERGE INTO "+schema+".DEPOSIT_REWARD_ENROLLMENT T USING(SELECT :pid PROGRAM_ID,:aid ACCOUNT_ID FROM DUAL) S ON(T.PROGRAM_ID=S.PROGRAM_ID AND T.ACCOUNT_ID=S.ACCOUNT_ID) WHEN MATCHED THEN UPDATE SET ELIGIBILITY_STATUS_CODE=:eligibility,STATUS_CODE=:status,CONSENT_REFERENCE=:consent,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=T.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(REWARD_ENROLLMENT_ID,PROGRAM_ID,ACCOUNT_ID,ENROLLED_AT,ELIGIBILITY_STATUS_CODE,STATUS_CODE,CONSENT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:aid,SYSTIMESTAMP,:eligibility,:status,:consent,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",programId).addValue("aid",accountId).addValue("eligibility",eligible?"ELIGIBLE":"INELIGIBLE").addValue("status",eligible?"ACTIVE":"INELIGIBLE").addValue("consent",consent,Types.VARCHAR).addValue("actor",actor));}
    public List<RewardEnrollment> enrollments(long accountId){String sql="SELECT REWARD_ENROLLMENT_ID,PROGRAM_ID,ACCOUNT_ID,ENROLLED_AT,ELIGIBILITY_STATUS_CODE,STATUS_CODE,CONSENT_REFERENCE FROM "+schema+".DEPOSIT_REWARD_ENROLLMENT WHERE ACCOUNT_ID=:id ORDER BY REWARD_ENROLLMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new RewardEnrollment(r.getLong(1),r.getLong(2),r.getLong(3),offset(r.getTimestamp(4)),r.getString(5),r.getString(6),r.getString(7)));}
    public List<LotteryEntry> lotteryEntries(long accountId){String sql="SELECT E.LOTTERY_ENTRY_ID,E.LOTTERY_DRAW_ID,E.REWARD_ENROLLMENT_ID,E.ELIGIBLE_BALANCE,E.ENTRY_COUNT,E.ENTRY_STATUS_CODE FROM "+schema+".DEPOSIT_LOTTERY_ENTRY E JOIN "+schema+".DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE R.ACCOUNT_ID=:id ORDER BY E.LOTTERY_ENTRY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new LotteryEntry(r.getLong(1),r.getLong(2),r.getLong(3),r.getBigDecimal(4),r.getLong(5),r.getString(6)));}
    public List<LotteryWinner> lotteryWinners(long accountId){String sql="SELECT W.LOTTERY_WINNER_ID,W.LOTTERY_DRAW_ID,W.LOTTERY_ENTRY_ID,W.PRIZE_CODE,W.PRIZE_DESCRIPTION,W.PRIZE_AMOUNT,W.WINNER_STATUS_CODE,W.PAYMENT_TRANSACTION_ID,W.PAYMENT_REFERENCE FROM "+schema+".DEPOSIT_LOTTERY_WINNER W JOIN "+schema+".DEPOSIT_LOTTERY_ENTRY E ON E.LOTTERY_ENTRY_ID=W.LOTTERY_ENTRY_ID JOIN "+schema+".DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE R.ACCOUNT_ID=:id ORDER BY W.LOTTERY_WINNER_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new LotteryWinner(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getString(7),r.getObject(8,Long.class),r.getString(9)));}

    public boolean completedReconRunForAccount(long runId,long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_RECONCILIATION_RUN R JOIN "+schema+".DEPOSIT_RECONCILIATION_ITEM I ON I.RECONCILIATION_RUN_ID=R.RECONCILIATION_RUN_ID WHERE R.RECONCILIATION_RUN_ID=:rid AND R.STATUS_CODE='COMPLETED' AND I.ACCOUNT_ID=:aid",new MapSqlParameterSource().addValue("rid",runId).addValue("aid",accountId),Long.class);return n!=null&&n>0;}
    public int markCorrespondentReconciled(long accountId,String actor){String sql="UPDATE "+schema+".CORRESPONDENT_RECONCILIATION_PROFILE P SET P.LAST_RECONCILED_AT=SYSTIMESTAMP,P.UPDATED_AT=SYSTIMESTAMP,P.UPDATED_BY=:actor,P.RECORD_VERSION=P.RECORD_VERSION+1 WHERE P.CORRESPONDENT_ACCOUNT_EXTENSION_ID IN (SELECT E.CORRESPONDENT_ACCOUNT_EXTENSION_ID FROM "+schema+".CORRESPONDENT_ACCOUNT_EXTENSION E WHERE E.ACCOUNT_ID=:aid AND E.RECONCILIATION_STATUS_CODE='READY')";return jdbc.update(sql,new MapSqlParameterSource().addValue("actor",actor).addValue("aid",accountId));}

    public boolean activeProgramForAccount(long programId,long accountId){return programEligible(programId,accountId);}
    public void insertLotteryDraw(long id,long programId,String drawNo,LocalDate drawDate,LocalDate cutoff,String seed,String audit,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_LOTTERY_DRAW(LOTTERY_DRAW_ID,PROGRAM_ID,DRAW_NO,DRAW_DATE,ELIGIBILITY_CUTOFF_DATE,STATUS_CODE,RANDOM_SEED_REFERENCE,AUDIT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:no,:dd,:cutoff,'OPEN',:seed,:audit,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",programId).addValue("no",drawNo).addValue("dd",Date.valueOf(drawDate)).addValue("cutoff",Date.valueOf(cutoff)).addValue("seed",seed).addValue("audit",audit).addValue("actor",actor));}
    public List<LotteryDraw> lotteryDraws(long accountId){String sql="SELECT DISTINCT D.LOTTERY_DRAW_ID,D.PROGRAM_ID,D.DRAW_NO,D.DRAW_DATE,D.ELIGIBILITY_CUTOFF_DATE,D.STATUS_CODE,D.RANDOM_SEED_REFERENCE,D.AUDIT_REFERENCE FROM "+schema+".DEPOSIT_LOTTERY_DRAW D JOIN "+schema+".DEPOSIT_REWARD_PROGRAM P ON P.PROGRAM_ID=D.PROGRAM_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:aid WHERE P.PRODUCT_VERSION_ID IS NULL OR P.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID ORDER BY D.DRAW_DATE DESC,D.LOTTERY_DRAW_ID DESC";return jdbc.query(sql,Map.of("aid",accountId),(r,n)->new LotteryDraw(r.getLong(1),r.getLong(2),r.getString(3),date(r.getDate(4)),date(r.getDate(5)),r.getString(6),r.getString(7),r.getString(8)));}
    public boolean enrollmentBelongsToAccount(long enrollmentId,long accountId,long programId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_REWARD_ENROLLMENT WHERE REWARD_ENROLLMENT_ID=:eid AND ACCOUNT_ID=:aid AND PROGRAM_ID=:pid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("eid",enrollmentId).addValue("aid",accountId).addValue("pid",programId),Long.class);return n!=null&&n>0;}
    public LotteryDrawLock lotteryDraw(long drawId){String sql="SELECT LOTTERY_DRAW_ID,PROGRAM_ID,STATUS_CODE,ELIGIBILITY_CUTOFF_DATE FROM "+schema+".DEPOSIT_LOTTERY_DRAW WHERE LOTTERY_DRAW_ID=:id";return jdbc.query(sql,Map.of("id",drawId),(r,n)->new LotteryDrawLock(r.getLong(1),r.getLong(2),r.getString(3),date(r.getDate(4)))).stream().findFirst().orElse(null);}
    public void insertLotteryEntry(long id,long drawId,long enrollmentId,BigDecimal balance,long count,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_LOTTERY_ENTRY(LOTTERY_ENTRY_ID,LOTTERY_DRAW_ID,REWARD_ENROLLMENT_ID,ELIGIBLE_BALANCE,ENTRY_COUNT,ENTRY_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:did,:eid,:bal,:cnt,'ELIGIBLE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("did",drawId).addValue("eid",enrollmentId).addValue("bal",balance).addValue("cnt",count).addValue("actor",actor));}
    public boolean entryBelongsToAccount(long entryId,long accountId,long drawId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_LOTTERY_ENTRY E JOIN "+schema+".DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE E.LOTTERY_ENTRY_ID=:eid AND E.LOTTERY_DRAW_ID=:did AND R.ACCOUNT_ID=:aid",new MapSqlParameterSource().addValue("eid",entryId).addValue("did",drawId).addValue("aid",accountId),Long.class);return n!=null&&n>0;}
    public void insertLotteryWinner(long id,long drawId,long entryId,String prizeCode,String description,BigDecimal amount,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_LOTTERY_WINNER(LOTTERY_WINNER_ID,LOTTERY_DRAW_ID,LOTTERY_ENTRY_ID,PRIZE_CODE,PRIZE_DESCRIPTION,PRIZE_AMOUNT,WINNER_STATUS_CODE,VERIFIED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:did,:eid,:code,:descr,:amount,'VERIFIED',SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("did",drawId).addValue("eid",entryId).addValue("code",prizeCode).addValue("descr",description,Types.VARCHAR).addValue("amount",amount).addValue("actor",actor));}
    public List<LotteryPoolRow> eligibleLotteryPool(long programId){String sql="SELECT R.REWARD_ENROLLMENT_ID,R.ACCOUNT_ID,A.ACCOUNT_NO,(SELECT NVL(SUM(B.LEDGER_BALANCE),0) FROM "+schema+".DEPOSIT_ACCOUNT_BALANCE B WHERE B.ACCOUNT_ID=A.ACCOUNT_ID) ELIGIBLE_BALANCE,ER.ENTRY_UNIT_AMOUNT FROM "+schema+".DEPOSIT_REWARD_ENROLLMENT R JOIN "+schema+".DEPOSIT_REWARD_PROGRAM P ON P.PROGRAM_ID=R.PROGRAM_ID JOIN "+schema+".DEPOSIT_REWARD_ELIGIBILITY_RULE ER ON ER.PROGRAM_ID=P.PROGRAM_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=R.ACCOUNT_ID WHERE R.PROGRAM_ID=:pid AND R.STATUS_CODE='ACTIVE' AND R.ELIGIBILITY_STATUS_CODE='ELIGIBLE' AND P.STATUS_CODE='ACTIVE' AND P.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (P.EFFECTIVE_TO IS NULL OR P.EFFECTIVE_TO>=TRUNC(SYSDATE)) AND (P.PRODUCT_VERSION_ID IS NULL OR P.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND A.ACCOUNT_STATUS_CODE='ACTIVE' AND (ER.MIN_AVERAGE_BALANCE IS NULL OR (SELECT NVL(SUM(B2.LEDGER_BALANCE),0) FROM "+schema+".DEPOSIT_ACCOUNT_BALANCE B2 WHERE B2.ACCOUNT_ID=A.ACCOUNT_ID)>=ER.MIN_AVERAGE_BALANCE) AND (ER.MIN_ACTIVE_DAYS IS NULL OR TRUNC(SYSDATE)-TRUNC(NVL(A.ACTIVATED_AT,A.CREATED_AT))>=ER.MIN_ACTIVE_DAYS) AND (ER.EXCLUDE_DORMANT_FLAG=0 OR A.ACCOUNT_STATUS_CODE<>'DORMANT') AND ER.ENTRY_UNIT_AMOUNT IS NOT NULL AND ER.ENTRY_UNIT_AMOUNT>0 ORDER BY R.REWARD_ENROLLMENT_ID";return jdbc.query(sql,Map.of("pid",programId),(r,n)->new LotteryPoolRow(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getBigDecimal(5)));}
    public int verifyLotteryDraw(long drawId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_LOTTERY_DRAW SET STATUS_CODE='VERIFIED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE LOTTERY_DRAW_ID=:id AND STATUS_CODE='OPEN'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",drawId));}
    public LotteryWinnerResult lotteryWinnerResult(long winnerId){String sql="SELECT W.LOTTERY_WINNER_ID,W.LOTTERY_DRAW_ID,R.ACCOUNT_ID,A.ACCOUNT_NO,D.DRAW_NO,D.AUDIT_REFERENCE FROM "+schema+".DEPOSIT_LOTTERY_WINNER W JOIN "+schema+".DEPOSIT_LOTTERY_ENTRY E ON E.LOTTERY_ENTRY_ID=W.LOTTERY_ENTRY_ID JOIN "+schema+".DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=R.ACCOUNT_ID JOIN "+schema+".DEPOSIT_LOTTERY_DRAW D ON D.LOTTERY_DRAW_ID=W.LOTTERY_DRAW_ID WHERE W.LOTTERY_WINNER_ID=:id";return jdbc.query(sql,Map.of("id",winnerId),(r,n)->new LotteryWinnerResult(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getString(6))).stream().findFirst().orElse(null);}
    public long lotteryDrawEntryCount(long drawId){Long n=jdbc.queryForObject("SELECT NVL(SUM(ENTRY_COUNT),0) FROM "+schema+".DEPOSIT_LOTTERY_ENTRY WHERE LOTTERY_DRAW_ID=:id",Map.of("id",drawId),Long.class);return n==null?0:n;}
    public WinnerLock winnerForPayment(long winnerId,long accountId){String sql="SELECT W.LOTTERY_WINNER_ID,W.PRIZE_AMOUNT,W.WINNER_STATUS_CODE,W.PAYMENT_TRANSACTION_ID FROM "+schema+".DEPOSIT_LOTTERY_WINNER W JOIN "+schema+".DEPOSIT_LOTTERY_ENTRY E ON E.LOTTERY_ENTRY_ID=W.LOTTERY_ENTRY_ID JOIN "+schema+".DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE W.LOTTERY_WINNER_ID=:wid AND R.ACCOUNT_ID=:aid FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("wid",winnerId).addValue("aid",accountId),(r,n)->new WinnerLock(r.getLong(1),r.getBigDecimal(2),r.getString(3),r.getObject(4,Long.class))).stream().findFirst().orElse(null);}
    public int markWinnerPaid(long winnerId,long transactionId,String paymentReference,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_LOTTERY_WINNER SET WINNER_STATUS_CODE='PAID',PAYMENT_TRANSACTION_ID=:tx,PAYMENT_REFERENCE=:ref,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE LOTTERY_WINNER_ID=:id AND WINNER_STATUS_CODE='VERIFIED' AND PAYMENT_TRANSACTION_ID IS NULL",new MapSqlParameterSource().addValue("tx",transactionId).addValue("ref",paymentReference).addValue("actor",actor).addValue("id",winnerId));}

    public record ReconItemSuspenseSource(long reconciliationItemId,String sourceReference,BigDecimal differenceAmount,String matchStatusCode){}
    public record LotteryPoolRow(long rewardEnrollmentId,long accountId,String accountNo,BigDecimal eligibleBalance,BigDecimal entryUnitAmount){}
    public record LotteryWinnerResult(long lotteryWinnerId,long lotteryDrawId,long winnerAccountId,String winnerAccountNo,String drawNo,String auditReference){}
    public record LotteryDrawLock(long id,long programId,String status,LocalDate cutoff){}
    public record WinnerLock(long id,BigDecimal prizeAmount,String status,Long paymentTransactionId){}

    public Optional<IdemRow> idempotency(String key){String sql="SELECT IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,Map.of("k",key),(r,n)->new IdemRow(r.getString(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getString(5),r.getString(6))).stream().findFirst();}
    public void claimIdempotency(long id,String key,Long accountId,String operation,String hash,String actor,String correlation){String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','WAVE_D',:key,:corr,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("key",key).addValue("aid",accountId,Types.NUMERIC).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation,Types.VARCHAR));}
    public void completeIdempotency(String key,String result){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("ref",result).addValue("key",key));}

    public record CorrectionLock(long id,Long originalTransactionId,String type,LocalDate effectiveDate,String status,long version,long authorizationId,String approver,String decision,long authorizationVersion){}
    public record IdemRow(String key,Long accountId,String operation,String payloadHash,String status,String resultReference){}
    private static BigDecimal nvl(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
    private static String id(String v){if(v==null||!v.matches("[A-Za-z0-9_]+"))throw new IllegalArgumentException("Oracle identifier نامعتبر است: "+v);return v.toUpperCase(Locale.ROOT);}
    private static LocalDate date(Date d){return d==null?null:d.toLocalDate();}
    private static OffsetDateTime offset(Timestamp t){return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}
    private static Timestamp ts(OffsetDateTime v){return v==null?null:Timestamp.from(v.toInstant());}
}
