SET SERVEROUTPUT ON;
DECLARE
    V_RELEASE_ID NUMBER;
    V_TOTAL NUMBER;
    V_FA NUMBER;
    V_EN NUMBER;
    V_TRANSLATED NUMBER;
    V_BAD_PARENT NUMBER;
    V_BAD_LEVEL NUMBER;
    V_BAD_SELECTABLE NUMBER;
    V_SELECTABLE NUMBER;
    V_OLD_COLUMNS NUMBER;
    V_NOTE_TABLE NUMBER;
BEGIN
    SELECT ISIC_RELEASE_ID INTO V_RELEASE_ID
      FROM CIF.REF_ISIC_RELEASE
     WHERE CLASSIFICATION_CODE='ISIC'
       AND REVISION_CODE='4'
       AND VARIANT_CODE='UNSD'
       AND COUNTRY_CODE IS NULL;

    SELECT COUNT(*),
           SUM(CASE WHEN TRIM(NAME_FA) IS NOT NULL THEN 1 ELSE 0 END),
           SUM(CASE WHEN TRIM(NAME_EN) IS NOT NULL THEN 1 ELSE 0 END),
           SUM(CASE WHEN TRANSLATION_STATUS_CODE='BANK_TRANSLATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN IS_SELECTABLE=1 THEN 1 ELSE 0 END)
      INTO V_TOTAL, V_FA, V_EN, V_TRANSLATED, V_SELECTABLE
      FROM CIF.REF_ISIC_ACTIVITY2
     WHERE ISIC_RELEASE_ID=V_RELEASE_ID;

    SELECT COUNT(*) INTO V_BAD_PARENT
      FROM CIF.REF_ISIC_ACTIVITY2 C
      LEFT JOIN CIF.REF_ISIC_ACTIVITY2 P
        ON P.ISIC_RELEASE_ID=C.ISIC_RELEASE_ID
       AND P.ISIC_ACTIVITY_ID=C.PARENT_ACTIVITY_ID
     WHERE C.ISIC_RELEASE_ID=V_RELEASE_ID
       AND (
           (C.LEVEL_NO=1 AND C.PARENT_ACTIVITY_ID IS NOT NULL)
        OR (C.LEVEL_NO BETWEEN 2 AND 4 AND
            (P.ISIC_ACTIVITY_ID IS NULL OR P.LEVEL_NO<>C.LEVEL_NO-1))
        OR (C.LEVEL_NO=5 AND
            (P.ISIC_ACTIVITY_ID IS NULL OR P.LEVEL_CODE NOT IN ('CLASS','NATIONAL_SUBCLASS')))
       );

    SELECT COUNT(*) INTO V_BAD_LEVEL
      FROM CIF.REF_ISIC_ACTIVITY2
     WHERE ISIC_RELEASE_ID=V_RELEASE_ID
       AND NOT ((LEVEL_CODE='SECTION' AND LEVEL_NO=1)
             OR (LEVEL_CODE='DIVISION' AND LEVEL_NO=2)
             OR (LEVEL_CODE='GROUP' AND LEVEL_NO=3)
             OR (LEVEL_CODE='CLASS' AND LEVEL_NO=4)
             OR (LEVEL_CODE='NATIONAL_SUBCLASS' AND LEVEL_NO=5));

    SELECT COUNT(*) INTO V_BAD_SELECTABLE
      FROM CIF.REF_ISIC_ACTIVITY2
     WHERE ISIC_RELEASE_ID=V_RELEASE_ID
       AND ((LEVEL_CODE='CLASS' AND IS_SELECTABLE<>1)
         OR (LEVEL_CODE IN ('SECTION','DIVISION','GROUP') AND IS_SELECTABLE<>0));

    SELECT COUNT(*) INTO V_OLD_COLUMNS
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='CIF'
       AND TABLE_NAME='REF_ISIC_ACTIVITY2'
       AND COLUMN_NAME IN ('BASE_ISIC_CODE','PARENT_ISIC_CODE','SECTION_CODE',
                           'DESCRIPTION_FA','DESCRIPTION_EN','INCLUSIONS_FA','INCLUSIONS_EN','EXCLUSIONS_FA','EXCLUSIONS_EN');

    SELECT COUNT(*) INTO V_NOTE_TABLE
      FROM ALL_TABLES
     WHERE OWNER='CIF' AND TABLE_NAME='REF_ISIC_ACTIVITY_NOTE';

    DBMS_OUTPUT.PUT_LINE(
        'UNSD Rev.4 total='||V_TOTAL||
        ', NAME_FA='||V_FA||
        ', NAME_EN='||V_EN||
        ', BANK_TRANSLATED='||V_TRANSLATED||
        ', selectable='||V_SELECTABLE
    );
    DBMS_OUTPUT.PUT_LINE(
        'bad_parent='||V_BAD_PARENT||
        ', bad_level='||V_BAD_LEVEL||
        ', bad_selectable='||V_BAD_SELECTABLE||
        ', legacy_activity2_columns='||V_OLD_COLUMNS||
        ', note_table='||V_NOTE_TABLE
    );

    IF V_TOTAL<>766
       OR V_FA<>766
       OR V_EN<>766
       OR V_TRANSLATED<>766
       OR V_SELECTABLE<>419
       OR V_BAD_PARENT<>0
       OR V_BAD_LEVEL<>0
       OR V_BAD_SELECTABLE<>0
       OR V_OLD_COLUMNS<>0
       OR V_NOTE_TABLE<>1 THEN
        RAISE_APPLICATION_ERROR(-20072,'ISIC2 validation failed.');
    END IF;
END;
/

SELECT LEVEL_CODE,
       LEVEL_NO,
       COUNT(*) ROW_COUNT,
       SUM(CASE WHEN TRIM(NAME_FA) IS NOT NULL THEN 1 ELSE 0 END) FA_COUNT,
       SUM(CASE WHEN TRIM(NAME_EN) IS NOT NULL THEN 1 ELSE 0 END) EN_COUNT,
       SUM(IS_SELECTABLE) SELECTABLE_COUNT
  FROM CIF.REF_ISIC_ACTIVITY2 A
  JOIN CIF.REF_ISIC_RELEASE R ON R.ISIC_RELEASE_ID=A.ISIC_RELEASE_ID
 WHERE R.CLASSIFICATION_CODE='ISIC'
   AND R.REVISION_CODE='4'
   AND R.VARIANT_CODE='UNSD'
   AND R.COUNTRY_CODE IS NULL
 GROUP BY LEVEL_CODE, LEVEL_NO
 ORDER BY LEVEL_NO;

SELECT COUNT(*) NOTE_COUNT FROM CIF.REF_ISIC_ACTIVITY_NOTE;
