-- Post-install validation for ISIC Rev.4 / UNSD seed
SET PAGESIZE 200
SET LINESIZE 220

PROMPT [1] Release row
SELECT ISIC_RELEASE_ID, CLASSIFICATION_CODE, REVISION_CODE, VARIANT_CODE,
       DATASET_STATUS_CODE, IS_CURRENT, IS_ACTIVE
FROM CIF.REF_ISIC_RELEASE
WHERE CLASSIFICATION_CODE='ISIC' AND REVISION_CODE='4' AND VARIANT_CODE='UNSD';

PROMPT [2] Expected hierarchy counts: SECTION=21, DIVISION=88, GROUP=238, CLASS=419, TOTAL=766
SELECT A.LEVEL_CODE, COUNT(*) AS ROW_COUNT
FROM CIF.REF_ISIC_ACTIVITY2 A
JOIN CIF.REF_ISIC_RELEASE R ON R.ISIC_RELEASE_ID=A.ISIC_RELEASE_ID
WHERE R.CLASSIFICATION_CODE='ISIC' AND R.REVISION_CODE='4' AND R.VARIANT_CODE='UNSD'
GROUP BY A.LEVEL_CODE
ORDER BY CASE A.LEVEL_CODE WHEN 'SECTION' THEN 1 WHEN 'DIVISION' THEN 2 WHEN 'GROUP' THEN 3 WHEN 'CLASS' THEN 4 ELSE 5 END;

SELECT COUNT(*) AS TOTAL_ROWS
FROM CIF.REF_ISIC_ACTIVITY2 A
JOIN CIF.REF_ISIC_RELEASE R ON R.ISIC_RELEASE_ID=A.ISIC_RELEASE_ID
WHERE R.CLASSIFICATION_CODE='ISIC' AND R.REVISION_CODE='4' AND R.VARIANT_CODE='UNSD';

PROMPT [3] Expected selectable leaf count: 419
SELECT COUNT(*) AS SELECTABLE_ROWS
FROM CIF.REF_ISIC_ACTIVITY2 A
JOIN CIF.REF_ISIC_RELEASE R ON R.ISIC_RELEASE_ID=A.ISIC_RELEASE_ID
WHERE R.CLASSIFICATION_CODE='ISIC' AND R.REVISION_CODE='4' AND R.VARIANT_CODE='UNSD'
  AND A.IS_SELECTABLE=1;

PROMPT [4] Expected orphan count: 0
SELECT COUNT(*) AS ORPHAN_ROWS
FROM CIF.REF_ISIC_ACTIVITY2 C
JOIN CIF.REF_ISIC_RELEASE R ON R.ISIC_RELEASE_ID=C.ISIC_RELEASE_ID
LEFT JOIN CIF.REF_ISIC_ACTIVITY2 P
  ON P.ISIC_RELEASE_ID=C.ISIC_RELEASE_ID
 AND P.ISIC_CODE=C.PARENT_ISIC_CODE
WHERE R.CLASSIFICATION_CODE='ISIC' AND R.REVISION_CODE='4' AND R.VARIANT_CODE='UNSD'
  AND C.PARENT_ISIC_CODE IS NOT NULL
  AND P.ISIC_ACTIVITY_ID IS NULL;

PROMPT [5] Expected duplicate business keys: 0
SELECT COUNT(*) AS DUPLICATE_KEYS
FROM (
    SELECT ISIC_RELEASE_ID, ISIC_CODE, COUNT(*) C
    FROM CIF.REF_ISIC_ACTIVITY2
    GROUP BY ISIC_RELEASE_ID, ISIC_CODE
    HAVING COUNT(*) > 1
);

PROMPT [6] Sample lookup rows
SELECT ISIC_CODE, LEVEL_CODE, PARENT_ISIC_CODE, SECTION_CODE,
       DISPLAY_NAME, TRANSLATION_STATUS
FROM CIF.V_REF_ISIC_ACTIVITY_LOOKUP2
WHERE REVISION_CODE='4' AND VARIANT_CODE='UNSD'
  AND ISIC_CODE IN ('0111','4690','6201','6419')
ORDER BY ISIC_CODE;
