package com.behsazan.corebanking.deposit.account.closure.oracle;

import com.behsazan.corebanking.deposit.account.closure.domain.DepositClosureModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Types;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;

@Repository
public class DepositClosureRepository {
    private final NamedParameterJdbcTemplate jdbc;
    private final String schema;
    public DepositClosureRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.schemas.deposit-account:DPS2}") String schema){this.jdbc=jdbc;this.schema=requireIdentifier(schema);}

    public record AccountLock(long accountId,long openingRequestId,String status,String currency,long recordVersion){}
    public record BalanceRow(long balanceId,BigDecimal ledger,BigDecimal available,BigDecimal blocked,BigDecimal pendingDebit,long recordVersion){}
    public record ClosureLock(long closureId,long accountId,String status,String type,String reason,String settlementRef,long approvalId,String requestedBy,String approver,long recordVersion){}
    public record ReopeningLock(long reopeningId,long accountId,String status,String reason,long approvalId,long recordVersion){}
    public record IdempotencyRow(Long accountId,String operationType,String payloadHash,String processingStatus,String resultReference){}

    public Optional<AccountLock> findAccount(long accountId,boolean lock){String sql="SELECT ACCOUNT_ID,OPENING_REQUEST_ID,ACCOUNT_STATUS_CODE,CURRENCY_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id"+(lock?" FOR UPDATE":"");return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new AccountLock(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5))).stream().findFirst();}
    public Optional<BalanceRow> lockBalance(long accountId){String sql="SELECT ACCOUNT_BALANCE_ID,LEDGER_BALANCE,AVAILABLE_BALANCE,BLOCKED_AMOUNT,PENDING_DEBIT_AMOUNT,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_BALANCE WHERE ACCOUNT_ID=:id FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new BalanceRow(r.getLong(1),r.getBigDecimal(2),r.getBigDecimal(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getLong(6))).stream().findFirst();}
    public long activeHoldCount(long accountId){return count("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_HOLD WHERE ACCOUNT_ID=:id AND HOLD_STATUS_CODE='ACTIVE' AND (VALID_TO IS NULL OR VALID_TO>SYSTIMESTAMP)",accountId);}
    public long activeReservationCount(long accountId){return count("SELECT COUNT(*) FROM "+schema+".DEPOSIT_BALANCE_RESERVATION WHERE ACCOUNT_ID=:id AND RESERVATION_STATUS_CODE='ACTIVE' AND (EXPIRES_AT IS NULL OR EXPIRES_AT>SYSTIMESTAMP)",accountId);}
    public long openClosureCount(long accountId){return count("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE WHERE ACCOUNT_ID=:id AND CLOSURE_STATUS_CODE IN ('REQUESTED','APPROVED')",accountId);}
    public long openReopeningCount(long accountId){return count("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_REOPENING WHERE ACCOUNT_ID=:id AND REOPEN_STATUS_CODE IN ('REQUESTED','APPROVED')",accountId);}
    private long count(String sql,long id){Long n=jdbc.queryForObject(sql,new MapSqlParameterSource("id",id),Long.class);return n==null?0:n;}

    public long nextClosureId(){return next("SEQ_DEPOSIT_ACCOUNT_CLOSURE");}
    public long nextClosureCheckId(){return next("SEQ_DEPOSIT_ACCOUNT_CLOSURE_CHECK");}
    public long nextSettlementId(){return next("SEQ_DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM");}
    public long nextReopeningId(){return next("SEQ_DEPOSIT_ACCOUNT_REOPENING");}
    public long nextApprovalId(){return next("SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST");}
    public long nextLifecycleEventId(){return next("SEQ_DEP_ACCOUNT_LIFECYCLE_EVT");}
    public long nextStatusHistoryId(){return next("SEQ_DEPOSIT_ACCOUNT_STATUS_HISTORY");}
    public long nextIdempotencyId(){return next("SEQ_DEPOSIT_OPERATION_IDEMPOTENCY");}
    private long next(String sequence){Long v=jdbc.getJdbcOperations().queryForObject("SELECT "+schema+"."+sequence+".NEXTVAL FROM DUAL",Long.class);if(v==null)throw new IllegalStateException(sequence+" returned null");return v;}

    public void insertApproval(long id,long accountId,String operation,String sourceType,long sourceId,String requestedBy,String approver,String org,String idem,String correlation){String tracking=(operation.startsWith("ACCOUNT_REOPEN")?"RO-":"CL-")+id;jdbc.update("INSERT INTO "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST(APPROVAL_REQUEST_ID,TRACKING_NO,ACCOUNT_ID,OPERATION_TYPE_CODE,SOURCE_ENTITY_TYPE,SOURCE_ENTITY_ID,REQUESTED_BY_USER_ID,REQUESTED_AT,APPROVER_USER_ID,APPROVAL_STATUS_CODE,ORG_UNIT_CODE,IDEMPOTENCY_KEY,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tracking,:aid,:op,:stype,:sid,:requested,SYSTIMESTAMP,:approver,'PENDING_APPROVAL',:org,:idem,'CORE_BANKING','DEPOSIT_CLOSURE',:idem,:corr,SYSTIMESTAMP,:requested,1)",new MapSqlParameterSource().addValue("id",id).addValue("tracking",tracking).addValue("aid",accountId).addValue("op",operation).addValue("stype",sourceType).addValue("sid",sourceId).addValue("requested",requestedBy).addValue("approver",approver).addValue("org",org).addValue("idem",idem).addValue("corr",correlation));}
    public int approve(long approvalId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST SET APPROVAL_STATUS_CODE='APPROVED',DECIDED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE APPROVAL_REQUEST_ID=:id AND APPROVAL_STATUS_CODE='PENDING_APPROVAL' AND APPROVER_USER_ID=:actor",new MapSqlParameterSource().addValue("id",approvalId).addValue("actor",actor));}

    public void insertClosure(long id,long accountId,String type,LocalDate effectiveDate,String settlementRef,String reason,long approvalId,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_CLOSURE(ACCOUNT_CLOSURE_ID,ACCOUNT_ID,CLOSURE_TYPE_CODE,REQUESTED_AT,EFFECTIVE_DATE,SETTLEMENT_ACCOUNT_REFERENCE,CLOSURE_STATUS_CODE,REASON_CODE,APPROVAL_REQUEST_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,SYSTIMESTAMP,:effective,:settlement,'REQUESTED',:reason,:approval,SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("effective",effectiveDate==null?null:java.sql.Date.valueOf(effectiveDate),Types.DATE).addValue("settlement",settlementRef,Types.VARCHAR).addValue("reason",reason).addValue("approval",approvalId).addValue("actor",actor));}
    public void insertCheck(long closureId,String code,boolean pass,String message,String evidence,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_CLOSURE_CHECK(CLOSURE_CHECK_ID,ACCOUNT_CLOSURE_ID,CHECK_CODE,RESULT_STATUS_CODE,RESULT_MESSAGE,EVALUATED_AT,EVIDENCE_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:cid,:code,:result,:message,SYSTIMESTAMP,:evidence,SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",nextClosureCheckId()).addValue("cid",closureId).addValue("code",code).addValue("result",pass?"PASS":"FAIL").addValue("message",message).addValue("evidence",evidence).addValue("actor",actor));}
    public void insertSettlement(long closureId,BigDecimal amount,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM(CLOSURE_SETTLEMENT_ITEM_ID,ACCOUNT_CLOSURE_ID,SEQUENCE_NO,COMPONENT_CODE,GROSS_AMOUNT,DEBIT_CREDIT_CODE,NET_AMOUNT,SETTLEMENT_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:cid,1,'PRINCIPAL',:amount,'DEBIT',:amount,'CALCULATED',SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",nextSettlementId()).addValue("cid",closureId).addValue("amount",amount).addValue("actor",actor));}
    public Optional<ClosureLock> lockClosure(long accountId,long closureId){String sql="SELECT c.ACCOUNT_CLOSURE_ID,c.ACCOUNT_ID,c.CLOSURE_STATUS_CODE,c.CLOSURE_TYPE_CODE,c.REASON_CODE,c.SETTLEMENT_ACCOUNT_REFERENCE,c.APPROVAL_REQUEST_ID,a.REQUESTED_BY_USER_ID,a.APPROVER_USER_ID,c.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE c JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST a ON a.APPROVAL_REQUEST_ID=c.APPROVAL_REQUEST_ID WHERE c.ACCOUNT_ID=:aid AND c.ACCOUNT_CLOSURE_ID=:id FOR UPDATE OF c.CLOSURE_STATUS_CODE";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("id",closureId),(r,n)->new ClosureLock(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getLong(7),r.getString(8),r.getString(9),r.getLong(10))).stream().findFirst();}
    public long failedClosureChecks(long closureId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE_CHECK WHERE ACCOUNT_CLOSURE_ID=:id AND RESULT_STATUS_CODE<>'PASS'",new MapSqlParameterSource("id",closureId),Long.class);return n==null?0:n;}
    public int markClosureApproved(long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_CLOSURE SET CLOSURE_STATUS_CODE='APPROVED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_CLOSURE_ID=:id AND CLOSURE_STATUS_CODE='REQUESTED'",new MapSqlParameterSource().addValue("id",id).addValue("actor",actor));}
    public void settleItems(long id,Long transactionId,String actor){jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM SET TRANSACTION_ID=COALESCE(TRANSACTION_ID,:tx),SETTLEMENT_STATUS_CODE='SETTLED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_CLOSURE_ID=:id AND SETTLEMENT_STATUS_CODE='CALCULATED'",new MapSqlParameterSource().addValue("id",id).addValue("tx",transactionId,Types.NUMERIC).addValue("actor",actor));}
    public void settleItems(long id,String actor){settleItems(id,null,actor);}
    public int executeClosure(long id,String settlementReference,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_CLOSURE SET CLOSURE_STATUS_CODE='EXECUTED',SETTLEMENT_TRANSACTION_REFERENCE=:ref,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_CLOSURE_ID=:id AND CLOSURE_STATUS_CODE='APPROVED'",new MapSqlParameterSource().addValue("id",id).addValue("ref",settlementReference,Types.VARCHAR).addValue("actor",actor));}

    public void insertReopening(long id,long accountId,String reason,long approvalId,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_REOPENING(ACCOUNT_REOPENING_ID,ACCOUNT_ID,REOPEN_REASON_CODE,REQUESTED_AT,REOPEN_STATUS_CODE,APPROVAL_REQUEST_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:reason,SYSTIMESTAMP,'REQUESTED',:approval,SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("reason",reason).addValue("approval",approvalId).addValue("actor",actor));}
    public Optional<ReopeningLock> lockReopening(long accountId,long reopeningId){String sql="SELECT ACCOUNT_REOPENING_ID,ACCOUNT_ID,REOPEN_STATUS_CODE,REOPEN_REASON_CODE,APPROVAL_REQUEST_ID,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_REOPENING WHERE ACCOUNT_ID=:aid AND ACCOUNT_REOPENING_ID=:id FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("id",reopeningId),(r,n)->new ReopeningLock(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5),r.getLong(6))).stream().findFirst();}
    public int markReopeningApproved(long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_REOPENING SET REOPEN_STATUS_CODE='APPROVED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_REOPENING_ID=:id AND REOPEN_STATUS_CODE='REQUESTED'",new MapSqlParameterSource().addValue("id",id).addValue("actor",actor));}
    public int executeReopening(long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_REOPENING SET REOPEN_STATUS_CODE='EXECUTED',EXECUTED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_REOPENING_ID=:id AND REOPEN_STATUS_CODE='APPROVED'",new MapSqlParameterSource().addValue("id",id).addValue("actor",actor));}

    public int changeStatus(long accountId,long version,String from,String to,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT SET ACCOUNT_STATUS_CODE=:to,DORMANCY_DATE=NULL,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_ID=:id AND ACCOUNT_STATUS_CODE=:from AND RECORD_VERSION=:version",new MapSqlParameterSource().addValue("to",to).addValue("actor",actor).addValue("id",accountId).addValue("from",from).addValue("version",version));}
    public void insertLifecycle(long accountId,long openingId,String event,String from,String to,String reason,long approvalId,String actor,String correlation){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_LIFECYCLE_EVENT(LIFECYCLE_EVENT_ID,ACCOUNT_ID,OPENING_REQUEST_ID,EVENT_TYPE_CODE,FROM_STATUS_CODE,TO_STATUS_CODE,APPROVAL_REQUEST_ID,CORRELATION_ID,EVENT_AT,EVENT_BY,CREATED_AT,CREATED_BY,EVENT_STATUS_CODE,REQUESTED_AT,EFFECTIVE_AT,REASON_CODE,RECORD_VERSION) VALUES(:id,:aid,:oid,:event,:from,:to,:approval,:corr,SYSTIMESTAMP,:actor,SYSTIMESTAMP,:actor,'EXECUTED',SYSTIMESTAMP,SYSTIMESTAMP,:reason,1)",new MapSqlParameterSource().addValue("id",nextLifecycleEventId()).addValue("aid",accountId).addValue("oid",openingId).addValue("event",event).addValue("from",from).addValue("to",to).addValue("approval",approvalId).addValue("corr",correlation).addValue("actor",actor).addValue("reason",reason));}
    public void insertStatusHistory(long accountId,String from,String to,String reason,String ref,Long approvalRequestId,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_STATUS_HISTORY(ACCOUNT_STATUS_HISTORY_ID,ACCOUNT_ID,FROM_STATUS_CODE,TO_STATUS_CODE,EFFECTIVE_AT,REASON_CODE,EVENT_REFERENCE,APPROVAL_REQUEST_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:from,:to,SYSTIMESTAMP,:reason,:ref,:approval,SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",nextStatusHistoryId()).addValue("aid",accountId).addValue("from",from).addValue("to",to).addValue("reason",reason).addValue("ref",ref).addValue("approval",approvalRequestId,Types.NUMERIC).addValue("actor",actor));}

    public List<ClosureCase> closures(long accountId){String sql="SELECT c.ACCOUNT_CLOSURE_ID,c.ACCOUNT_ID,c.CLOSURE_TYPE_CODE,c.REQUESTED_AT,c.EFFECTIVE_DATE,c.SETTLEMENT_ACCOUNT_REFERENCE,c.CLOSURE_STATUS_CODE,c.REASON_CODE,c.APPROVAL_REQUEST_ID,a.APPROVAL_STATUS_CODE,a.APPROVER_USER_ID,c.SETTLEMENT_TRANSACTION_REFERENCE,c.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE c LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST a ON a.APPROVAL_REQUEST_ID=c.APPROVAL_REQUEST_ID WHERE c.ACCOUNT_ID=:id ORDER BY c.ACCOUNT_CLOSURE_ID DESC FETCH FIRST 20 ROWS ONLY";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(r,n)->new ClosureCase(r.getLong(1),r.getLong(2),r.getString(3),odt(r.getTimestamp(4)),r.getDate(5)==null?null:r.getDate(5).toLocalDate(),r.getString(6),r.getString(7),r.getString(8),r.getObject(9)==null?null:r.getLong(9),r.getString(10),r.getString(11),r.getString(12),List.of(),List.of(),r.getLong(13))).stream().map(c->new ClosureCase(c.accountClosureId(),c.accountId(),c.closureTypeCode(),c.requestedAt(),c.effectiveDate(),c.settlementAccountReference(),c.closureStatusCode(),c.reasonCode(),c.approvalRequestId(),c.approvalStatusCode(),c.approverUserId(),c.settlementTransactionReference(),checks(c.accountClosureId()),settlements(c.accountClosureId()),c.recordVersion())).toList();}
    private List<ClosureCheck> checks(long closureId){return jdbc.query("SELECT CLOSURE_CHECK_ID,CHECK_CODE,RESULT_STATUS_CODE,RESULT_MESSAGE,EVALUATED_AT,EVIDENCE_REFERENCE FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE_CHECK WHERE ACCOUNT_CLOSURE_ID=:id ORDER BY CLOSURE_CHECK_ID",new MapSqlParameterSource("id",closureId),(r,n)->new ClosureCheck(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),odt(r.getTimestamp(5)),r.getString(6)));}
    private List<ClosureSettlementItem> settlements(long closureId){return jdbc.query("SELECT CLOSURE_SETTLEMENT_ITEM_ID,SEQUENCE_NO,COMPONENT_CODE,GROSS_AMOUNT,DEBIT_CREDIT_CODE,NET_AMOUNT,TRANSACTION_ID,SETTLEMENT_STATUS_CODE FROM "+schema+".DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM WHERE ACCOUNT_CLOSURE_ID=:id ORDER BY SEQUENCE_NO",new MapSqlParameterSource("id",closureId),(r,n)->new ClosureSettlementItem(r.getLong(1),r.getInt(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getBigDecimal(6),r.getObject(7)==null?null:r.getLong(7),r.getString(8)));}
    public List<ReopeningCase> reopenings(long accountId){String sql="SELECT r.ACCOUNT_REOPENING_ID,r.ACCOUNT_ID,r.REOPEN_REASON_CODE,r.REQUESTED_AT,r.REOPEN_STATUS_CODE,r.APPROVAL_REQUEST_ID,a.APPROVAL_STATUS_CODE,a.APPROVER_USER_ID,r.EXECUTED_AT,r.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_REOPENING r LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST a ON a.APPROVAL_REQUEST_ID=r.APPROVAL_REQUEST_ID WHERE r.ACCOUNT_ID=:id ORDER BY r.ACCOUNT_REOPENING_ID DESC FETCH FIRST 20 ROWS ONLY";return jdbc.query(sql,new MapSqlParameterSource("id",accountId),(x,n)->new ReopeningCase(x.getLong(1),x.getLong(2),x.getString(3),odt(x.getTimestamp(4)),x.getString(5),x.getObject(6)==null?null:x.getLong(6),x.getString(7),x.getString(8),odt(x.getTimestamp(9)),x.getLong(10)));}

    public Optional<IdempotencyRow> findIdempotency(String key){String sql="SELECT ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,new MapSqlParameterSource("k",key),(r,n)->new IdempotencyRow(r.getObject(1)==null?null:r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5))).stream().findFirst();}
    public void insertIdempotency(String key,long accountId,String operation,String hash,String actor,String correlation){jdbc.update("INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','DEPOSIT_CLOSURE',:key,:corr,1)",new MapSqlParameterSource().addValue("id",nextIdempotencyId()).addValue("key",key).addValue("aid",accountId).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation));}
    public void completeIdempotency(String key,String ref){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("key",key).addValue("ref",ref));}

    private static OffsetDateTime odt(java.sql.Timestamp t){return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}
    private static String requireIdentifier(String v){if(v==null||!v.matches("[A-Za-z][A-Za-z0-9_$#]*"))throw new IllegalArgumentException("Invalid schema identifier");return v.toUpperCase(Locale.ROOT);}
}
