-- Phase 4: Organization and Product reference data.
-- GEO.CURRENCIES and DPS.REF_ORG_UNIT_CODE remain the existing sources of truth and are not duplicated in CIF.
-- Target schema CIF

PROMPT Creating CIF.REF_ECONOMIC_SECTOR
CREATE TABLE CIF.REF_ECONOMIC_SECTOR (
  ECONOMIC_SECTOR_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ECONOMIC_SECTOR PRIMARY KEY (ECONOMIC_SECTOR_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ECONOMIC_SECTOR_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ECONOMIC_SECTOR_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ECONOMIC_SECTOR_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ECONOMIC_SECTOR_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ISIC_ACTIVITY
CREATE TABLE CIF.REF_ISIC_ACTIVITY (
  ISIC_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ISIC_ACTIVITY PRIMARY KEY (ISIC_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ISIC_ACTIVITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ISIC_ACTIVITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ISIC_ACTIVITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ISIC_ACTIVITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LEGAL_FORM
CREATE TABLE CIF.REF_LEGAL_FORM (
  LEGAL_FORM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LEGAL_FORM PRIMARY KEY (LEGAL_FORM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LEGAL_FORM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LEGAL_FORM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LEGAL_FORM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LEGAL_FORM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LICENSE_TYPE
CREATE TABLE CIF.REF_LICENSE_TYPE (
  LICENSE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LICENSE_TYPE PRIMARY KEY (LICENSE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LICENSE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LICENSE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LICENSE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LICENSE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OCCUPATION
CREATE TABLE CIF.REF_OCCUPATION (
  OCCUPATION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OCCUPATION PRIMARY KEY (OCCUPATION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OCCUPATION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OCCUPATION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OCCUPATION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OCCUPATION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OFFER
CREATE TABLE CIF.REF_OFFER (
  OFFER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OFFER PRIMARY KEY (OFFER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OFFER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OFFER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OFFER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OFFER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OFFICER_ROLE
CREATE TABLE CIF.REF_OFFICER_ROLE (
  OFFICER_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OFFICER_ROLE PRIMARY KEY (OFFICER_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OFFICER_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OFFICER_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OFFICER_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OFFICER_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PERIOD
CREATE TABLE CIF.REF_PERIOD (
  PERIOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PERIOD PRIMARY KEY (PERIOD_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PERIOD_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PERIOD_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PERIOD_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PERIOD_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_HOLDING_STATUS
CREATE TABLE CIF.REF_PRODUCT_HOLDING_STATUS (
  PRODUCT_HOLDING_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_HOLDING_STATUS PRIMARY KEY (PRODUCT_HOLDING_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_RELATIONSHIP_ROLE
CREATE TABLE CIF.REF_PRODUCT_RELATIONSHIP_ROLE (
  PRODUCT_RELATIONSHIP_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_RELATIONSHIP_ROLE PRIMARY KEY (PRODUCT_RELATIONSHIP_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_01 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_03 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_TYPE
CREATE TABLE CIF.REF_PRODUCT_TYPE (
  PRODUCT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_TYPE PRIMARY KEY (PRODUCT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PRODUCT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTRACT_TYPE
CREATE TABLE CIF.REF_CONTRACT_TYPE (
  CONTRACT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTRACT_TYPE PRIMARY KEY (CONTRACT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTRACT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTRACT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTRACT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTRACT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;


-- Fix22: dedicated Organization economic-profile Reference Data.

PROMPT Creating CIF.REF_ORGANIZATION_ACTIVITY_STATUS
CREATE TABLE CIF.REF_ORGANIZATION_ACTIVITY_STATUS (
  ACTIVITY_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ORG_ACTIVITY_STATUS PRIMARY KEY (ACTIVITY_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ORG_ACTIVITY_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ORG_ACTIVITY_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ORG_ACTIVITY_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ORG_ACTIVITY_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
COMMENT ON TABLE CIF.REF_ORGANIZATION_ACTIVITY_STATUS IS 'اطلاعات پایه وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.ACTIVITY_STATUS_CODE IS 'کد وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.NAME_FA IS 'عنوان فارسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت فعالیت اقتصادی شخص حقوقی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت فعالیت اقتصادی شخص حقوقی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.PARENT_CODE IS 'کد والد وضعیت فعالیت اقتصادی شخص حقوقی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت فعالیت اقتصادی شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ORGANIZATION_ACTIVITY_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت فعالیت اقتصادی شخص حقوقی برای کنترل هم‌زمانی';

PROMPT Creating CIF.REF_ENTERPRISE_SIZE
CREATE TABLE CIF.REF_ENTERPRISE_SIZE (
  ENTERPRISE_SIZE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ENTERPRISE_SIZE PRIMARY KEY (ENTERPRISE_SIZE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ENTERPRISE_SIZE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ENTERPRISE_SIZE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ENTERPRISE_SIZE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ENTERPRISE_SIZE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
COMMENT ON TABLE CIF.REF_ENTERPRISE_SIZE IS 'اطلاعات پایه اندازه بنگاه شخص حقوقی';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.ENTERPRISE_SIZE_CODE IS 'کد اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.NAME_FA IS 'عنوان فارسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.NAME_EN IS 'عنوان انگلیسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.DESCRIPTION_FA IS 'توضیحات فارسی اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.SORT_ORDER IS 'ترتیب نمایش اندازه بنگاه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.IS_ACTIVE IS 'نشانگر فعال بودن اندازه بنگاه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.PARENT_CODE IS 'کد والد اندازه بنگاه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.VALID_FROM IS 'تاریخ شروع اعتبار اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.VALID_TO IS 'تاریخ پایان اعتبار اندازه بنگاه';
COMMENT ON COLUMN CIF.REF_ENTERPRISE_SIZE.RECORD_VERSION IS 'شماره نسخه رکورد اندازه بنگاه برای کنترل هم‌زمانی';

PROMPT Creating CIF.REF_OWNERSHIP_TYPE
CREATE TABLE CIF.REF_OWNERSHIP_TYPE (
  OWNERSHIP_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OWNERSHIP_TYPE PRIMARY KEY (OWNERSHIP_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OWNERSHIP_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OWNERSHIP_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OWNERSHIP_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OWNERSHIP_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
COMMENT ON TABLE CIF.REF_OWNERSHIP_TYPE IS 'اطلاعات پایه نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.OWNERSHIP_TYPE_CODE IS 'کد نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.NAME_FA IS 'عنوان فارسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.NAME_EN IS 'عنوان انگلیسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع مالکیت شخص حقوقی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع مالکیت شخص حقوقی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.PARENT_CODE IS 'کد والد نوع مالکیت شخص حقوقی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع مالکیت شخص حقوقی';
COMMENT ON COLUMN CIF.REF_OWNERSHIP_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع مالکیت شخص حقوقی برای کنترل هم‌زمانی';

-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.CONTRACT_TYPE_CODE IS 'کد نوع قرارداد';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.NAME_FA IS 'عنوان فارسی نوع قرارداد اشتغال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع قرارداد اشتغال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع قرارداد اشتغال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع قرارداد اشتغال در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع قرارداد اشتغال؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.PARENT_CODE IS 'کد والد نوع قرارداد اشتغال در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع قرارداد اشتغال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع قرارداد اشتغال';
COMMENT ON COLUMN CIF.REF_CONTRACT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع قرارداد اشتغال برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.ECONOMIC_SECTOR_CODE IS 'کد بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.NAME_FA IS 'عنوان فارسی بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.NAME_EN IS 'عنوان انگلیسی بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.DESCRIPTION_FA IS 'توضیحات فارسی بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.SORT_ORDER IS 'ترتیب نمایش بخش اقتصادی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.IS_ACTIVE IS 'نشانگر فعال بودن بخش اقتصادی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.PARENT_CODE IS 'کد والد بخش اقتصادی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.VALID_FROM IS 'تاریخ شروع اعتبار بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.VALID_TO IS 'تاریخ پایان اعتبار بخش اقتصادی';
COMMENT ON COLUMN CIF.REF_ECONOMIC_SECTOR.RECORD_VERSION IS 'شماره نسخه رکورد بخش اقتصادی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.ISIC_CODE IS 'کد ISIC';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.NAME_FA IS 'عنوان فارسی فعالیت اقتصادی (ISIC)';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.NAME_EN IS 'عنوان انگلیسی فعالیت اقتصادی (ISIC)';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.DESCRIPTION_FA IS 'توضیحات فارسی فعالیت اقتصادی (ISIC)';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.SORT_ORDER IS 'ترتیب نمایش فعالیت اقتصادی (ISIC) در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.IS_ACTIVE IS 'نشانگر فعال بودن فعالیت اقتصادی (ISIC)؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.PARENT_CODE IS 'کد والد فعالیت اقتصادی (ISIC) در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.VALID_FROM IS 'تاریخ شروع اعتبار فعالیت اقتصادی (ISIC)';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.VALID_TO IS 'تاریخ پایان اعتبار فعالیت اقتصادی (ISIC)';
COMMENT ON COLUMN CIF.REF_ISIC_ACTIVITY.RECORD_VERSION IS 'شماره نسخه رکورد فعالیت اقتصادی (ISIC) برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.LEGAL_FORM_CODE IS 'کد نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.NAME_FA IS 'عنوان فارسی نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.NAME_EN IS 'عنوان انگلیسی نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.DESCRIPTION_FA IS 'توضیحات فارسی نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.SORT_ORDER IS 'ترتیب نمایش نوع شخصیت حقوقی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.IS_ACTIVE IS 'نشانگر فعال بودن نوع شخصیت حقوقی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.PARENT_CODE IS 'کد والد نوع شخصیت حقوقی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.VALID_FROM IS 'تاریخ شروع اعتبار نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.VALID_TO IS 'تاریخ پایان اعتبار نوع شخصیت حقوقی';
COMMENT ON COLUMN CIF.REF_LEGAL_FORM.RECORD_VERSION IS 'شماره نسخه رکورد نوع شخصیت حقوقی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.LICENSE_TYPE_CODE IS 'کد نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.NAME_FA IS 'عنوان فارسی نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.NAME_EN IS 'عنوان انگلیسی نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع مجوز در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع مجوز؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.PARENT_CODE IS 'کد والد نوع مجوز در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع مجوز';
COMMENT ON COLUMN CIF.REF_LICENSE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع مجوز برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_OCCUPATION.OCCUPATION_CODE IS 'کد شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.NAME_FA IS 'عنوان فارسی شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.NAME_EN IS 'عنوان انگلیسی شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.DESCRIPTION_FA IS 'توضیحات فارسی شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.SORT_ORDER IS 'ترتیب نمایش شغل در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_OCCUPATION.IS_ACTIVE IS 'نشانگر فعال بودن شغل؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_OCCUPATION.PARENT_CODE IS 'کد والد شغل در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_OCCUPATION.VALID_FROM IS 'تاریخ شروع اعتبار شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.VALID_TO IS 'تاریخ پایان اعتبار شغل';
COMMENT ON COLUMN CIF.REF_OCCUPATION.RECORD_VERSION IS 'شماره نسخه رکورد شغل برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_OFFER.OFFER_CODE IS 'کد پیشنهاد';
COMMENT ON COLUMN CIF.REF_OFFER.NAME_FA IS 'عنوان فارسی پیشنهاد محصول/خدمت';
COMMENT ON COLUMN CIF.REF_OFFER.NAME_EN IS 'عنوان انگلیسی پیشنهاد محصول/خدمت';
COMMENT ON COLUMN CIF.REF_OFFER.DESCRIPTION_FA IS 'توضیحات فارسی پیشنهاد محصول/خدمت';
COMMENT ON COLUMN CIF.REF_OFFER.SORT_ORDER IS 'ترتیب نمایش پیشنهاد محصول/خدمت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_OFFER.IS_ACTIVE IS 'نشانگر فعال بودن پیشنهاد محصول/خدمت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_OFFER.PARENT_CODE IS 'کد والد پیشنهاد محصول/خدمت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_OFFER.VALID_FROM IS 'تاریخ شروع اعتبار پیشنهاد محصول/خدمت';
COMMENT ON COLUMN CIF.REF_OFFER.VALID_TO IS 'تاریخ پایان اعتبار پیشنهاد محصول/خدمت';
COMMENT ON COLUMN CIF.REF_OFFER.RECORD_VERSION IS 'شماره نسخه رکورد پیشنهاد محصول/خدمت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.OFFICER_ROLE_CODE IS 'کد سمت/نقش';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.NAME_FA IS 'عنوان فارسی سمت/نقش سازمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.NAME_EN IS 'عنوان انگلیسی سمت/نقش سازمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.DESCRIPTION_FA IS 'توضیحات فارسی سمت/نقش سازمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.SORT_ORDER IS 'ترتیب نمایش سمت/نقش سازمانی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.IS_ACTIVE IS 'نشانگر فعال بودن سمت/نقش سازمانی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.PARENT_CODE IS 'کد والد سمت/نقش سازمانی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.VALID_FROM IS 'تاریخ شروع اعتبار سمت/نقش سازمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.VALID_TO IS 'تاریخ پایان اعتبار سمت/نقش سازمانی';
COMMENT ON COLUMN CIF.REF_OFFICER_ROLE.RECORD_VERSION IS 'شماره نسخه رکورد سمت/نقش سازمانی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.PERIOD_CODE IS 'کد دوره';
COMMENT ON COLUMN CIF.REF_PERIOD.NAME_FA IS 'عنوان فارسی دوره زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.NAME_EN IS 'عنوان انگلیسی دوره زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.DESCRIPTION_FA IS 'توضیحات فارسی دوره زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.SORT_ORDER IS 'ترتیب نمایش دوره زمانی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PERIOD.IS_ACTIVE IS 'نشانگر فعال بودن دوره زمانی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PERIOD.PARENT_CODE IS 'کد والد دوره زمانی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PERIOD.VALID_FROM IS 'تاریخ شروع اعتبار دوره زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.VALID_TO IS 'تاریخ پایان اعتبار دوره زمانی';
COMMENT ON COLUMN CIF.REF_PERIOD.RECORD_VERSION IS 'شماره نسخه رکورد دوره زمانی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.PRODUCT_HOLDING_STATUS_CODE IS 'کد وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.NAME_FA IS 'عنوان فارسی وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت رابطه محصولی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت رابطه محصولی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.PARENT_CODE IS 'کد والد وضعیت رابطه محصولی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت رابطه محصولی';
COMMENT ON COLUMN CIF.REF_PRODUCT_HOLDING_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت رابطه محصولی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.PRODUCT_RELATIONSHIP_ROLE_CODE IS 'کد نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.NAME_FA IS 'عنوان فارسی نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.NAME_EN IS 'عنوان انگلیسی نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.DESCRIPTION_FA IS 'توضیحات فارسی نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.SORT_ORDER IS 'ترتیب نمایش نقش مشتری نسبت به محصول در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.IS_ACTIVE IS 'نشانگر فعال بودن نقش مشتری نسبت به محصول؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.PARENT_CODE IS 'کد والد نقش مشتری نسبت به محصول در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.VALID_FROM IS 'تاریخ شروع اعتبار نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.VALID_TO IS 'تاریخ پایان اعتبار نقش مشتری نسبت به محصول';
COMMENT ON COLUMN CIF.REF_PRODUCT_RELATIONSHIP_ROLE.RECORD_VERSION IS 'شماره نسخه رکورد نقش مشتری نسبت به محصول برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.PRODUCT_TYPE_CODE IS 'کد نوع محصول/خدمت';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.NAME_FA IS 'عنوان فارسی نوع محصول/خدمت بانکی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع محصول/خدمت بانکی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع محصول/خدمت بانکی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع محصول/خدمت بانکی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع محصول/خدمت بانکی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.PARENT_CODE IS 'کد والد نوع محصول/خدمت بانکی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع محصول/خدمت بانکی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع محصول/خدمت بانکی';
COMMENT ON COLUMN CIF.REF_PRODUCT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع محصول/خدمت بانکی برای کنترل هم‌زمانی';
