-- Phase 4: Organization and Product reference data.
-- GEO.CURRENCIES and DPS.REF_ORG_UNIT_CODE remain the existing sources of truth and are not duplicated in CIF.
-- Target schema CIF

PROMPT Creating CIF.REF_ECONOMIC_SECTOR
CREATE TABLE CIF.REF_ECONOMIC_SECTOR (
  ECONOMIC_SECTOR_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ECONOMIC_SECTOR PRIMARY KEY (ECONOMIC_SECTOR_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ECONOMIC_SECTOR_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ECONOMIC_SECTOR_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ECONOMIC_SECTOR_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ECONOMIC_SECTOR_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ISIC_ACTIVITY
CREATE TABLE CIF.REF_ISIC_ACTIVITY (
  ISIC_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ISIC_ACTIVITY PRIMARY KEY (ISIC_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ISIC_ACTIVITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ISIC_ACTIVITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ISIC_ACTIVITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ISIC_ACTIVITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LEGAL_FORM
CREATE TABLE CIF.REF_LEGAL_FORM (
  LEGAL_FORM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LEGAL_FORM PRIMARY KEY (LEGAL_FORM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LEGAL_FORM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LEGAL_FORM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LEGAL_FORM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LEGAL_FORM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LICENSE_TYPE
CREATE TABLE CIF.REF_LICENSE_TYPE (
  LICENSE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LICENSE_TYPE PRIMARY KEY (LICENSE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LICENSE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LICENSE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LICENSE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LICENSE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OCCUPATION
CREATE TABLE CIF.REF_OCCUPATION (
  OCCUPATION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OCCUPATION PRIMARY KEY (OCCUPATION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OCCUPATION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OCCUPATION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OCCUPATION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OCCUPATION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OFFER
CREATE TABLE CIF.REF_OFFER (
  OFFER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OFFER PRIMARY KEY (OFFER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OFFER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OFFER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OFFER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OFFER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_OFFICER_ROLE
CREATE TABLE CIF.REF_OFFICER_ROLE (
  OFFICER_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OFFICER_ROLE PRIMARY KEY (OFFICER_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_OFFICER_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_OFFICER_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_OFFICER_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_OFFICER_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PERIOD
CREATE TABLE CIF.REF_PERIOD (
  PERIOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PERIOD PRIMARY KEY (PERIOD_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PERIOD_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PERIOD_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PERIOD_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PERIOD_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_HOLDING_STATUS
CREATE TABLE CIF.REF_PRODUCT_HOLDING_STATUS (
  PRODUCT_HOLDING_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_HOLDING_STATUS PRIMARY KEY (PRODUCT_HOLDING_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_HOLDING_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_RELATIONSHIP_ROLE
CREATE TABLE CIF.REF_PRODUCT_RELATIONSHIP_ROLE (
  PRODUCT_RELATIONSHIP_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_RELATIONSHIP_ROLE PRIMARY KEY (PRODUCT_RELATIONSHIP_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_01 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_03 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_RELATIONSHIP_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PRODUCT_TYPE
CREATE TABLE CIF.REF_PRODUCT_TYPE (
  PRODUCT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODUCT_TYPE PRIMARY KEY (PRODUCT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PRODUCT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRODUCT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PRODUCT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PRODUCT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
