-- Phase 4 seed data
-- Persian labels with broken word order from the source mockup were normalized using the source English meaning.

MERGE INTO CIF.REF_ECONOMIC_SECTOR T
USING (SELECT 'BANKING' AS ECONOMIC_SECTOR_CODE, 'بانکداری' AS NAME_FA, 'Banking' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ECONOMIC_SECTOR_CODE=S.ECONOMIC_SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ECONOMIC_SECTOR_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ECONOMIC_SECTOR_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ECONOMIC_SECTOR T
USING (SELECT 'MANUFACTURING' AS ECONOMIC_SECTOR_CODE, 'تولید و صنعت' AS NAME_FA, 'Manufacturing' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ECONOMIC_SECTOR_CODE=S.ECONOMIC_SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ECONOMIC_SECTOR_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ECONOMIC_SECTOR_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ECONOMIC_SECTOR T
USING (SELECT 'SERVICES' AS ECONOMIC_SECTOR_CODE, 'خدمات' AS NAME_FA, 'Services' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ECONOMIC_SECTOR_CODE=S.ECONOMIC_SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ECONOMIC_SECTOR_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ECONOMIC_SECTOR_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ECONOMIC_SECTOR T
USING (SELECT 'TRADE' AS ECONOMIC_SECTOR_CODE, 'بازرگانی و تجارت' AS NAME_FA, 'Trade' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ECONOMIC_SECTOR_CODE=S.ECONOMIC_SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ECONOMIC_SECTOR_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ECONOMIC_SECTOR_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ECONOMIC_SECTOR T
USING (SELECT 'AGRICULTURE' AS ECONOMIC_SECTOR_CODE, 'کشاورزی' AS NAME_FA, 'Agriculture' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ECONOMIC_SECTOR_CODE=S.ECONOMIC_SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ECONOMIC_SECTOR_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ECONOMIC_SECTOR_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ISIC_ACTIVITY T
USING (SELECT '6419' AS ISIC_CODE, 'سایر واسطه‌گری‌های پولی' AS NAME_FA, 'Other monetary intermediation' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ISIC_CODE=S.ISIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ISIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ISIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ISIC_ACTIVITY T
USING (SELECT '6201' AS ISIC_CODE, 'فعالیت‌های برنامه‌نویسی رایانه‌ای' AS NAME_FA, 'Computer programming activities' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ISIC_CODE=S.ISIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ISIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ISIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ISIC_ACTIVITY T
USING (SELECT '4690' AS ISIC_CODE, 'عمده‌فروشی غیرتخصصی' AS NAME_FA, 'Non-specialized wholesale trade' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ISIC_CODE=S.ISIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ISIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ISIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ISIC_ACTIVITY T
USING (SELECT '0111' AS ISIC_CODE, 'کشت غلات (به‌جز برنج)، حبوبات و دانه‌های روغنی' AS NAME_FA, 'Growing of cereals (except rice), leguminous crops and oil seeds' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ISIC_CODE=S.ISIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ISIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ISIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LEGAL_FORM T
USING (SELECT 'PRIVATE_JSC' AS LEGAL_FORM_CODE, 'شرکت سهامی خاص' AS NAME_FA, 'Private JSC' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LEGAL_FORM_CODE=S.LEGAL_FORM_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LEGAL_FORM_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LEGAL_FORM_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LEGAL_FORM T
USING (SELECT 'PUBLIC_JSC' AS LEGAL_FORM_CODE, 'شرکت سهامی عام' AS NAME_FA, 'Public JSC' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LEGAL_FORM_CODE=S.LEGAL_FORM_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LEGAL_FORM_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LEGAL_FORM_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LEGAL_FORM T
USING (SELECT 'LLC' AS LEGAL_FORM_CODE, 'شرکت با مسئولیت محدود' AS NAME_FA, 'LLC' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LEGAL_FORM_CODE=S.LEGAL_FORM_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LEGAL_FORM_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LEGAL_FORM_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LEGAL_FORM T
USING (SELECT 'COOPERATIVE' AS LEGAL_FORM_CODE, 'تعاونی' AS NAME_FA, 'Cooperative' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LEGAL_FORM_CODE=S.LEGAL_FORM_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LEGAL_FORM_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LEGAL_FORM_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LEGAL_FORM T
USING (SELECT 'GOVERNMENT' AS LEGAL_FORM_CODE, 'دولتی' AS NAME_FA, 'Government' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LEGAL_FORM_CODE=S.LEGAL_FORM_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LEGAL_FORM_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LEGAL_FORM_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LICENSE_TYPE T
USING (SELECT 'BUSINESS_LICENSE' AS LICENSE_TYPE_CODE, 'مجوز کسب‌وکار' AS NAME_FA, 'Business License' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LICENSE_TYPE_CODE=S.LICENSE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LICENSE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LICENSE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LICENSE_TYPE T
USING (SELECT 'PROFESSIONAL_LICENSE' AS LICENSE_TYPE_CODE, 'مجوز حرفه‌ای' AS NAME_FA, 'Professional License' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LICENSE_TYPE_CODE=S.LICENSE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LICENSE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LICENSE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_LICENSE_TYPE T
USING (SELECT 'EXPORT_IMPORT' AS LICENSE_TYPE_CODE, 'مجوز صادرات و واردات' AS NAME_FA, 'Export Import' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.LICENSE_TYPE_CODE=S.LICENSE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (LICENSE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.LICENSE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OCCUPATION T
USING (SELECT 'EMPLOYEE' AS OCCUPATION_CODE, 'کارمند' AS NAME_FA, 'Employee' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OCCUPATION_CODE=S.OCCUPATION_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OCCUPATION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OCCUPATION_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OCCUPATION T
USING (SELECT 'SELF_EMPLOYED' AS OCCUPATION_CODE, 'خویش‌فرما' AS NAME_FA, 'Self Employed' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OCCUPATION_CODE=S.OCCUPATION_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OCCUPATION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OCCUPATION_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OCCUPATION T
USING (SELECT 'RETIRED' AS OCCUPATION_CODE, 'بازنشسته' AS NAME_FA, 'Retired' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OCCUPATION_CODE=S.OCCUPATION_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OCCUPATION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OCCUPATION_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OCCUPATION T
USING (SELECT 'STUDENT' AS OCCUPATION_CODE, 'دانشجو' AS NAME_FA, 'Student' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OCCUPATION_CODE=S.OCCUPATION_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OCCUPATION_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OCCUPATION_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFER T
USING (SELECT 'OFFER_DEPOSIT_01' AS OFFER_CODE, 'پیشنهاد سپرده 01' AS NAME_FA, 'Offer Deposit 01' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFER_CODE=S.OFFER_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFER_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFER_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFER T
USING (SELECT 'OFFER_CARD_01' AS OFFER_CODE, 'پیشنهاد کارت 01' AS NAME_FA, 'Offer Card 01' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFER_CODE=S.OFFER_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFER_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFER_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFER T
USING (SELECT 'OFFER_LOAN_01' AS OFFER_CODE, 'پیشنهاد تسهیلات 01' AS NAME_FA, 'Offer Loan 01' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFER_CODE=S.OFFER_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFER_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFER_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFICER_ROLE T
USING (SELECT 'CEO' AS OFFICER_ROLE_CODE, 'مدیرعامل' AS NAME_FA, 'CEO' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFICER_ROLE_CODE=S.OFFICER_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFICER_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFICER_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFICER_ROLE T
USING (SELECT 'BOARD_MEMBER' AS OFFICER_ROLE_CODE, 'عضو هیئت‌مدیره' AS NAME_FA, 'Board Member' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFICER_ROLE_CODE=S.OFFICER_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFICER_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFICER_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFICER_ROLE T
USING (SELECT 'CFO' AS OFFICER_ROLE_CODE, 'مدیر مالی' AS NAME_FA, 'CFO' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFICER_ROLE_CODE=S.OFFICER_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFICER_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFICER_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_OFFICER_ROLE T
USING (SELECT 'AUTHORIZED_SIGNATORY' AS OFFICER_ROLE_CODE, 'صاحب امضای مجاز' AS NAME_FA, 'Authorized Signatory' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.OFFICER_ROLE_CODE=S.OFFICER_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (OFFICER_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.OFFICER_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PERIOD T
USING (SELECT 'DAILY' AS PERIOD_CODE, 'روزانه' AS NAME_FA, 'Daily' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PERIOD_CODE=S.PERIOD_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PERIOD_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PERIOD_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PERIOD T
USING (SELECT 'WEEKLY' AS PERIOD_CODE, 'هفتگی' AS NAME_FA, 'Weekly' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PERIOD_CODE=S.PERIOD_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PERIOD_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PERIOD_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PERIOD T
USING (SELECT 'MONTHLY' AS PERIOD_CODE, 'ماهانه' AS NAME_FA, 'Monthly' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PERIOD_CODE=S.PERIOD_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PERIOD_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PERIOD_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PERIOD T
USING (SELECT 'ANNUAL' AS PERIOD_CODE, 'سالانه' AS NAME_FA, 'Annual' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PERIOD_CODE=S.PERIOD_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PERIOD_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PERIOD_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_HOLDING_STATUS T
USING (SELECT 'ACTIVE' AS PRODUCT_HOLDING_STATUS_CODE, 'فعال' AS NAME_FA, 'Active' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_HOLDING_STATUS_CODE=S.PRODUCT_HOLDING_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_HOLDING_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_HOLDING_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_HOLDING_STATUS T
USING (SELECT 'DORMANT' AS PRODUCT_HOLDING_STATUS_CODE, 'راکد' AS NAME_FA, 'Dormant' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_HOLDING_STATUS_CODE=S.PRODUCT_HOLDING_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_HOLDING_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_HOLDING_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_HOLDING_STATUS T
USING (SELECT 'CLOSED' AS PRODUCT_HOLDING_STATUS_CODE, 'بسته‌شده' AS NAME_FA, 'Closed' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_HOLDING_STATUS_CODE=S.PRODUCT_HOLDING_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_HOLDING_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_HOLDING_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_RELATIONSHIP_ROLE T
USING (SELECT 'OWNER' AS PRODUCT_RELATIONSHIP_ROLE_CODE, 'مالک' AS NAME_FA, 'Owner' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_RELATIONSHIP_ROLE_CODE=S.PRODUCT_RELATIONSHIP_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_RELATIONSHIP_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_RELATIONSHIP_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_RELATIONSHIP_ROLE T
USING (SELECT 'JOINT_OWNER' AS PRODUCT_RELATIONSHIP_ROLE_CODE, 'مالک مشترک' AS NAME_FA, 'Joint Owner' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_RELATIONSHIP_ROLE_CODE=S.PRODUCT_RELATIONSHIP_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_RELATIONSHIP_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_RELATIONSHIP_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_RELATIONSHIP_ROLE T
USING (SELECT 'GUARANTOR' AS PRODUCT_RELATIONSHIP_ROLE_CODE, 'ضامن' AS NAME_FA, 'Guarantor' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_RELATIONSHIP_ROLE_CODE=S.PRODUCT_RELATIONSHIP_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_RELATIONSHIP_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_RELATIONSHIP_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_RELATIONSHIP_ROLE T
USING (SELECT 'BENEFICIARY' AS PRODUCT_RELATIONSHIP_ROLE_CODE, 'ذی‌نفع' AS NAME_FA, 'Beneficiary' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_RELATIONSHIP_ROLE_CODE=S.PRODUCT_RELATIONSHIP_ROLE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_RELATIONSHIP_ROLE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_RELATIONSHIP_ROLE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_TYPE T
USING (SELECT 'DEPOSIT' AS PRODUCT_TYPE_CODE, 'سپرده' AS NAME_FA, 'Deposit' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_TYPE_CODE=S.PRODUCT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_TYPE T
USING (SELECT 'LOAN' AS PRODUCT_TYPE_CODE, 'تسهیلات' AS NAME_FA, 'Loan' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_TYPE_CODE=S.PRODUCT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_TYPE T
USING (SELECT 'CARD' AS PRODUCT_TYPE_CODE, 'کارت' AS NAME_FA, 'Card' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_TYPE_CODE=S.PRODUCT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_TYPE T
USING (SELECT 'SAFE_DEPOSIT' AS PRODUCT_TYPE_CODE, 'صندوق امانات' AS NAME_FA, 'Safe Deposit' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_TYPE_CODE=S.PRODUCT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_PRODUCT_TYPE T
USING (SELECT 'DIGITAL_WALLET' AS PRODUCT_TYPE_CODE, 'کیف پول دیجیتال' AS NAME_FA, 'Digital Wallet' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.PRODUCT_TYPE_CODE=S.PRODUCT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (PRODUCT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.PRODUCT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

COMMIT;

MERGE INTO CIF.REF_CONTRACT_TYPE T
USING (SELECT 'PERMANENT' AS CONTRACT_TYPE_CODE, 'دائم' AS NAME_FA, 'Permanent' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTRACT_TYPE_CODE=S.CONTRACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTRACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTRACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTRACT_TYPE T
USING (SELECT 'TEMPORARY' AS CONTRACT_TYPE_CODE, 'موقت' AS NAME_FA, 'Temporary' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTRACT_TYPE_CODE=S.CONTRACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTRACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTRACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTRACT_TYPE T
USING (SELECT 'CONTRACTOR' AS CONTRACT_TYPE_CODE, 'پیمانکاری' AS NAME_FA, 'Contractor' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTRACT_TYPE_CODE=S.CONTRACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTRACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTRACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTRACT_TYPE T
USING (SELECT 'SELF_EMPLOYED' AS CONTRACT_TYPE_CODE, 'خویش‌فرما' AS NAME_FA, 'Self Employed' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTRACT_TYPE_CODE=S.CONTRACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTRACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTRACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);
