PROMPT Verifying Organization and Product CIF reference tables
SELECT 'REF_ECONOMIC_SECTOR' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_ECONOMIC_SECTOR;
SELECT 'REF_ISIC_ACTIVITY' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_ISIC_ACTIVITY;
SELECT 'REF_LEGAL_FORM' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_LEGAL_FORM;
SELECT 'REF_LICENSE_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_LICENSE_TYPE;
SELECT 'REF_OCCUPATION' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_OCCUPATION;
SELECT 'REF_OFFER' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_OFFER;
SELECT 'REF_OFFICER_ROLE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_OFFICER_ROLE;
SELECT 'REF_PERIOD' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_PERIOD;
SELECT 'REF_PRODUCT_HOLDING_STATUS' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_PRODUCT_HOLDING_STATUS;
SELECT 'REF_PRODUCT_RELATIONSHIP_ROLE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_PRODUCT_RELATIONSHIP_ROLE;
SELECT 'REF_PRODUCT_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_PRODUCT_TYPE;
SELECT * FROM CIF.REF_LEGAL_FORM WHERE LEGAL_FORM_CODE='PRIVATE_JSC';
SELECT * FROM CIF.REF_ECONOMIC_SECTOR WHERE ECONOMIC_SECTOR_CODE='BANKING';
SELECT * FROM CIF.REF_OCCUPATION WHERE OCCUPATION_CODE='EMPLOYEE';
SELECT * FROM CIF.REF_PRODUCT_TYPE WHERE PRODUCT_TYPE_CODE='DEPOSIT';
SELECT * FROM CIF.REF_PERIOD WHERE PERIOD_CODE='DAILY';
SELECT 'REF_CONTRACT_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_CONTRACT_TYPE;
SELECT * FROM CIF.REF_CONTRACT_TYPE WHERE CONTRACT_TYPE_CODE='PERMANENT';

SELECT 'REF_ORGANIZATION_ACTIVITY_STATUS' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_ORGANIZATION_ACTIVITY_STATUS;
SELECT 'REF_ENTERPRISE_SIZE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_ENTERPRISE_SIZE;
SELECT 'REF_OWNERSHIP_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_OWNERSHIP_TYPE;
