-- Phase 3: Contact reference data. Existing GEO remains source of truth for country/province/city/district/language.
-- Target schema CIF

PROMPT Creating CIF.REF_ADDRESS_TYPE
CREATE TABLE CIF.REF_ADDRESS_TYPE (
  ADDRESS_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ADDRESS_TYPE PRIMARY KEY (ADDRESS_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ADDRESS_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ADDRESS_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ADDRESS_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ADDRESS_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_BRANCH
CREATE TABLE CIF.REF_BRANCH (
  BRANCH_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_BRANCH_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_BRANCH_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_BRANCH_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_BRANCH_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CHANNEL
CREATE TABLE CIF.REF_CHANNEL (
  CHANNEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CHANNEL PRIMARY KEY (CHANNEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CHANNEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CHANNEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CHANNEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CHANNEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMMUNICATION_PURPOSE
CREATE TABLE CIF.REF_COMMUNICATION_PURPOSE (
  COMMUNICATION_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMMUNICATION_PURPOSE PRIMARY KEY (COMMUNICATION_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMMUNICATION_PURPOSE_01 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_02 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_ASSOCIATION_TYPE
CREATE TABLE CIF.REF_CONTACT_ASSOCIATION_TYPE (
  ASSOCIATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_ASSOCIATION_TYPE PRIMARY KEY (ASSOCIATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_PURPOSE
CREATE TABLE CIF.REF_CONTACT_PURPOSE (
  CONTACT_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_PURPOSE PRIMARY KEY (CONTACT_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_PURPOSE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_PURPOSE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_PURPOSE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_PURPOSE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_TYPE
CREATE TABLE CIF.REF_CONTACT_TYPE (
  CONTACT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_TYPE PRIMARY KEY (CONTACT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCRIPT
CREATE TABLE CIF.REF_SCRIPT (
  SCRIPT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCRIPT PRIMARY KEY (SCRIPT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCRIPT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCRIPT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCRIPT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCRIPT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ADDRESS_SOURCE
CREATE TABLE CIF.REF_ADDRESS_SOURCE (
  ADDRESS_SOURCE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ADDRESS_SOURCE PRIMARY KEY (ADDRESS_SOURCE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ADDRESS_SOURCE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ADDRESS_SOURCE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ADDRESS_SOURCE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ADDRESS_SOURCE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
