-- Phase 3: Contact reference data. Existing GEO remains source of truth for country/province/city/district/language.
-- Target schema CIF

PROMPT Creating CIF.REF_ADDRESS_TYPE
CREATE TABLE CIF.REF_ADDRESS_TYPE (
  ADDRESS_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ADDRESS_TYPE PRIMARY KEY (ADDRESS_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ADDRESS_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ADDRESS_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ADDRESS_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ADDRESS_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_BRANCH
CREATE TABLE CIF.REF_BRANCH (
  BRANCH_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_BRANCH_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_BRANCH_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_BRANCH_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_BRANCH_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CHANNEL
CREATE TABLE CIF.REF_CHANNEL (
  CHANNEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CHANNEL PRIMARY KEY (CHANNEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CHANNEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CHANNEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CHANNEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CHANNEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMMUNICATION_PURPOSE
CREATE TABLE CIF.REF_COMMUNICATION_PURPOSE (
  COMMUNICATION_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMMUNICATION_PURPOSE PRIMARY KEY (COMMUNICATION_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMMUNICATION_PURPOSE_01 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_02 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMMUNICATION_PURPOSE_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_ASSOCIATION_TYPE
CREATE TABLE CIF.REF_CONTACT_ASSOCIATION_TYPE (
  ASSOCIATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_ASSOCIATION_TYPE PRIMARY KEY (ASSOCIATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_ASSOCIATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_PURPOSE
CREATE TABLE CIF.REF_CONTACT_PURPOSE (
  CONTACT_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_PURPOSE PRIMARY KEY (CONTACT_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_PURPOSE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_PURPOSE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_PURPOSE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_PURPOSE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTACT_TYPE
CREATE TABLE CIF.REF_CONTACT_TYPE (
  CONTACT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTACT_TYPE PRIMARY KEY (CONTACT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTACT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTACT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTACT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTACT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCRIPT
CREATE TABLE CIF.REF_SCRIPT (
  SCRIPT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCRIPT PRIMARY KEY (SCRIPT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCRIPT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCRIPT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCRIPT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCRIPT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ADDRESS_SOURCE
CREATE TABLE CIF.REF_ADDRESS_SOURCE (
  ADDRESS_SOURCE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ADDRESS_SOURCE PRIMARY KEY (ADDRESS_SOURCE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ADDRESS_SOURCE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ADDRESS_SOURCE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ADDRESS_SOURCE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ADDRESS_SOURCE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;


-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.ADDRESS_SOURCE_CODE IS 'کد منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.NAME_FA IS 'عنوان فارسی منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.NAME_EN IS 'عنوان انگلیسی منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.DESCRIPTION_FA IS 'توضیحات فارسی منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.SORT_ORDER IS 'ترتیب نمایش منبع نشانی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.IS_ACTIVE IS 'نشانگر فعال بودن منبع نشانی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.PARENT_CODE IS 'کد والد منبع نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.VALID_FROM IS 'تاریخ شروع اعتبار منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.VALID_TO IS 'تاریخ پایان اعتبار منبع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_SOURCE.RECORD_VERSION IS 'شماره نسخه رکورد منبع نشانی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.ADDRESS_TYPE_CODE IS 'کد نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.NAME_FA IS 'عنوان فارسی نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.NAME_EN IS 'عنوان انگلیسی نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع نشانی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع نشانی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.PARENT_CODE IS 'کد والد نوع نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع نشانی';
COMMENT ON COLUMN CIF.REF_ADDRESS_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع نشانی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_BRANCH.BRANCH_CODE IS 'کد شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.NAME_FA IS 'عنوان فارسی شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.NAME_EN IS 'عنوان انگلیسی شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.DESCRIPTION_FA IS 'توضیحات فارسی شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.SORT_ORDER IS 'ترتیب نمایش شعبه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_BRANCH.IS_ACTIVE IS 'نشانگر فعال بودن شعبه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_BRANCH.PARENT_CODE IS 'کد والد شعبه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_BRANCH.VALID_FROM IS 'تاریخ شروع اعتبار شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.VALID_TO IS 'تاریخ پایان اعتبار شعبه';
COMMENT ON COLUMN CIF.REF_BRANCH.RECORD_VERSION IS 'شماره نسخه رکورد شعبه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CHANNEL.CHANNEL_CODE IS 'کد کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.NAME_FA IS 'عنوان فارسی کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.NAME_EN IS 'عنوان انگلیسی کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.DESCRIPTION_FA IS 'توضیحات فارسی کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.SORT_ORDER IS 'ترتیب نمایش کانال ارتباطی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CHANNEL.IS_ACTIVE IS 'نشانگر فعال بودن کانال ارتباطی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CHANNEL.PARENT_CODE IS 'کد والد کانال ارتباطی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CHANNEL.VALID_FROM IS 'تاریخ شروع اعتبار کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.VALID_TO IS 'تاریخ پایان اعتبار کانال ارتباطی';
COMMENT ON COLUMN CIF.REF_CHANNEL.RECORD_VERSION IS 'شماره نسخه رکورد کانال ارتباطی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.COMMUNICATION_PURPOSE_CODE IS 'کد هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.NAME_FA IS 'عنوان فارسی هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.NAME_EN IS 'عنوان انگلیسی هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.DESCRIPTION_FA IS 'توضیحات فارسی هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.SORT_ORDER IS 'ترتیب نمایش هدف ارتباطات در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.IS_ACTIVE IS 'نشانگر فعال بودن هدف ارتباطات؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.PARENT_CODE IS 'کد والد هدف ارتباطات در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.VALID_FROM IS 'تاریخ شروع اعتبار هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.VALID_TO IS 'تاریخ پایان اعتبار هدف ارتباطات';
COMMENT ON COLUMN CIF.REF_COMMUNICATION_PURPOSE.RECORD_VERSION IS 'شماره نسخه رکورد هدف ارتباطات برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.ASSOCIATION_TYPE_CODE IS 'کد نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.NAME_FA IS 'عنوان فارسی نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.NAME_EN IS 'عنوان انگلیسی نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع ارتباط اطلاعات تماس در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع ارتباط اطلاعات تماس؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.PARENT_CODE IS 'کد والد نوع ارتباط اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع ارتباط اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_ASSOCIATION_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع ارتباط اطلاعات تماس برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.CONTACT_PURPOSE_CODE IS 'کد کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.NAME_FA IS 'عنوان فارسی کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.NAME_EN IS 'عنوان انگلیسی کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.DESCRIPTION_FA IS 'توضیحات فارسی کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.SORT_ORDER IS 'ترتیب نمایش کاربرد اطلاعات تماس در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.IS_ACTIVE IS 'نشانگر فعال بودن کاربرد اطلاعات تماس؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.PARENT_CODE IS 'کد والد کاربرد اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.VALID_FROM IS 'تاریخ شروع اعتبار کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.VALID_TO IS 'تاریخ پایان اعتبار کاربرد اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_PURPOSE.RECORD_VERSION IS 'شماره نسخه رکورد کاربرد اطلاعات تماس برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.CONTACT_TYPE_CODE IS 'کد نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.NAME_FA IS 'عنوان فارسی نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع اطلاعات تماس در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع اطلاعات تماس؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.PARENT_CODE IS 'کد والد نوع اطلاعات تماس در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع اطلاعات تماس';
COMMENT ON COLUMN CIF.REF_CONTACT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع اطلاعات تماس برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.LEGAL_CAPACITY_CODE IS 'کد اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.NAME_FA IS 'عنوان فارسی اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.NAME_EN IS 'عنوان انگلیسی اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.DESCRIPTION_FA IS 'توضیحات فارسی اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.SORT_ORDER IS 'ترتیب نمایش اهلیت قانونی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.IS_ACTIVE IS 'نشانگر فعال بودن اهلیت قانونی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.PARENT_CODE IS 'کد والد اهلیت قانونی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.VALID_FROM IS 'تاریخ شروع اعتبار اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.VALID_TO IS 'تاریخ پایان اعتبار اهلیت قانونی';
COMMENT ON COLUMN CIF.REF_LEGAL_CAPACITY.RECORD_VERSION IS 'شماره نسخه رکورد اهلیت قانونی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCRIPT.SCRIPT_CODE IS 'کد خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.NAME_FA IS 'عنوان فارسی خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.NAME_EN IS 'عنوان انگلیسی خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.DESCRIPTION_FA IS 'توضیحات فارسی خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.SORT_ORDER IS 'ترتیب نمایش خط نوشتاری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCRIPT.IS_ACTIVE IS 'نشانگر فعال بودن خط نوشتاری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCRIPT.PARENT_CODE IS 'کد والد خط نوشتاری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCRIPT.VALID_FROM IS 'تاریخ شروع اعتبار خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.VALID_TO IS 'تاریخ پایان اعتبار خط نوشتاری';
COMMENT ON COLUMN CIF.REF_SCRIPT.RECORD_VERSION IS 'شماره نسخه رکورد خط نوشتاری برای کنترل هم‌زمانی';
