-- Phase 3 seed data

MERGE INTO CIF.REF_ADDRESS_TYPE T
USING (SELECT 'RESIDENTIAL' AS ADDRESS_TYPE_CODE, 'مسکونی' AS NAME_FA, 'Residential' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_TYPE_CODE=S.ADDRESS_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ADDRESS_TYPE T
USING (SELECT 'WORK' AS ADDRESS_TYPE_CODE, 'محل کار' AS NAME_FA, 'Work' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_TYPE_CODE=S.ADDRESS_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ADDRESS_TYPE T
USING (SELECT 'REGISTERED' AS ADDRESS_TYPE_CODE, 'ثبتی' AS NAME_FA, 'Registered' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_TYPE_CODE=S.ADDRESS_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ADDRESS_TYPE T
USING (SELECT 'MAILING' AS ADDRESS_TYPE_CODE, 'مکاتباتی' AS NAME_FA, 'Mailing' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_TYPE_CODE=S.ADDRESS_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_BRANCH T
USING (SELECT 'BR001' AS BRANCH_CODE, 'شعبه ۰۰۱' AS NAME_FA, 'Br001' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.BRANCH_CODE=S.BRANCH_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (BRANCH_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.BRANCH_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_BRANCH T
USING (SELECT 'BR002' AS BRANCH_CODE, 'شعبه ۰۰۲' AS NAME_FA, 'Br002' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.BRANCH_CODE=S.BRANCH_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (BRANCH_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.BRANCH_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_BRANCH T
USING (SELECT 'DIGITAL' AS BRANCH_CODE, 'شعبه دیجیتال' AS NAME_FA, 'Digital' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.BRANCH_CODE=S.BRANCH_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (BRANCH_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.BRANCH_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'SMS' AS CHANNEL_CODE, 'پیامک' AS NAME_FA, 'Sms' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'EMAIL' AS CHANNEL_CODE, 'ایمیل' AS NAME_FA, 'Email' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'PHONE' AS CHANNEL_CODE, 'تلفن' AS NAME_FA, 'Phone' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'BRANCH' AS CHANNEL_CODE, 'شعبه' AS NAME_FA, 'Branch' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'MOBILE_APP' AS CHANNEL_CODE, 'همراه‌بانک' AS NAME_FA, 'Mobile App' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'WEB' AS CHANNEL_CODE, 'وب' AS NAME_FA, 'Web' AS NAME_EN, NULL AS DESCRIPTION_FA, 60 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CHANNEL T
USING (SELECT 'BACK_OFFICE' AS CHANNEL_CODE, 'ستاد' AS NAME_FA, 'Back Office' AS NAME_EN, NULL AS DESCRIPTION_FA, 70 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CHANNEL_CODE=S.CHANNEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CHANNEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CHANNEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_COMMUNICATION_PURPOSE T
USING (SELECT 'GENERAL' AS COMMUNICATION_PURPOSE_CODE, 'عمومی' AS NAME_FA, 'General' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.COMMUNICATION_PURPOSE_CODE=S.COMMUNICATION_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (COMMUNICATION_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.COMMUNICATION_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_COMMUNICATION_PURPOSE T
USING (SELECT 'NOTIFICATION' AS COMMUNICATION_PURPOSE_CODE, 'اطلاع‌رسانی' AS NAME_FA, 'Notification' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.COMMUNICATION_PURPOSE_CODE=S.COMMUNICATION_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (COMMUNICATION_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.COMMUNICATION_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_COMMUNICATION_PURPOSE T
USING (SELECT 'MARKETING' AS COMMUNICATION_PURPOSE_CODE, 'بازاریابی' AS NAME_FA, 'Marketing' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.COMMUNICATION_PURPOSE_CODE=S.COMMUNICATION_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (COMMUNICATION_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.COMMUNICATION_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_COMMUNICATION_PURPOSE T
USING (SELECT 'KYC' AS COMMUNICATION_PURPOSE_CODE, 'شناخت مشتری' AS NAME_FA, 'Kyc' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.COMMUNICATION_PURPOSE_CODE=S.COMMUNICATION_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (COMMUNICATION_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.COMMUNICATION_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_COMMUNICATION_PURPOSE T
USING (SELECT 'TRANSACTION' AS COMMUNICATION_PURPOSE_CODE, 'تراکنش' AS NAME_FA, 'Transaction' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.COMMUNICATION_PURPOSE_CODE=S.COMMUNICATION_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (COMMUNICATION_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.COMMUNICATION_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_ASSOCIATION_TYPE T
USING (SELECT 'HOME_CONTACT' AS ASSOCIATION_TYPE_CODE, 'اطلاعات تماس منزل' AS NAME_FA, 'Home Contact' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ASSOCIATION_TYPE_CODE=S.ASSOCIATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ASSOCIATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ASSOCIATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_ASSOCIATION_TYPE T
USING (SELECT 'WORK_CONTACT' AS ASSOCIATION_TYPE_CODE, 'اطلاعات تماس محل کار' AS NAME_FA, 'Work Contact' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ASSOCIATION_TYPE_CODE=S.ASSOCIATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ASSOCIATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ASSOCIATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_ASSOCIATION_TYPE T
USING (SELECT 'REGISTERED_CONTACT' AS ASSOCIATION_TYPE_CODE, 'اطلاعات تماس ثبت‌شده' AS NAME_FA, 'Registered Contact' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ASSOCIATION_TYPE_CODE=S.ASSOCIATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ASSOCIATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ASSOCIATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_PURPOSE T
USING (SELECT 'GENERAL' AS CONTACT_PURPOSE_CODE, 'عمومی' AS NAME_FA, 'General' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_PURPOSE_CODE=S.CONTACT_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_PURPOSE T
USING (SELECT 'NOTIFICATION' AS CONTACT_PURPOSE_CODE, 'اطلاع‌رسانی' AS NAME_FA, 'Notification' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_PURPOSE_CODE=S.CONTACT_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_PURPOSE T
USING (SELECT 'MARKETING' AS CONTACT_PURPOSE_CODE, 'بازاریابی' AS NAME_FA, 'Marketing' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_PURPOSE_CODE=S.CONTACT_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_PURPOSE T
USING (SELECT 'KYC' AS CONTACT_PURPOSE_CODE, 'شناخت مشتری' AS NAME_FA, 'Kyc' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_PURPOSE_CODE=S.CONTACT_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_PURPOSE T
USING (SELECT 'TRANSACTION' AS CONTACT_PURPOSE_CODE, 'تراکنش' AS NAME_FA, 'Transaction' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_PURPOSE_CODE=S.CONTACT_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_PURPOSE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_PURPOSE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_TYPE T
USING (SELECT 'MOBILE' AS CONTACT_TYPE_CODE, 'تلفن همراه' AS NAME_FA, 'Mobile' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_TYPE_CODE=S.CONTACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_TYPE T
USING (SELECT 'PHONE' AS CONTACT_TYPE_CODE, 'تلفن' AS NAME_FA, 'Phone' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_TYPE_CODE=S.CONTACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_TYPE T
USING (SELECT 'EMAIL' AS CONTACT_TYPE_CODE, 'ایمیل' AS NAME_FA, 'Email' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_TYPE_CODE=S.CONTACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_CONTACT_TYPE T
USING (SELECT 'FAX' AS CONTACT_TYPE_CODE, 'نمابر' AS NAME_FA, 'Fax' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.CONTACT_TYPE_CODE=S.CONTACT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (CONTACT_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.CONTACT_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCRIPT T
USING (SELECT 'ARAB' AS SCRIPT_CODE, 'خط عربی' AS NAME_FA, 'Arab' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCRIPT_CODE=S.SCRIPT_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCRIPT_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCRIPT_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCRIPT T
USING (SELECT 'LATN' AS SCRIPT_CODE, 'خط لاتین' AS NAME_FA, 'Latn' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCRIPT_CODE=S.SCRIPT_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCRIPT_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCRIPT_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

COMMIT;

PROMPT Seeding CIF.REF_ADDRESS_SOURCE
MERGE INTO CIF.REF_ADDRESS_SOURCE T
USING (SELECT 'CUSTOMER_DECLARATION' AS ADDRESS_SOURCE_CODE, 'اظهار مشتری' AS NAME_FA, 'Customer Declaration' AS NAME_EN, 'ثبت نشانی براساس اظهار مشتری' AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_SOURCE_CODE=S.ADDRESS_SOURCE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_SOURCE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_SOURCE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ADDRESS_SOURCE T
USING (SELECT 'POSTAL_SYSTEM' AS ADDRESS_SOURCE_CODE, 'سامانه پست' AS NAME_FA, 'Postal System' AS NAME_EN, 'ثبت یا تأیید نشانی از سامانه پست' AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_SOURCE_CODE=S.ADDRESS_SOURCE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_SOURCE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_SOURCE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_ADDRESS_SOURCE T
USING (SELECT 'RESIDENCE_DOCUMENT' AS ADDRESS_SOURCE_CODE, 'مدرک سکونت' AS NAME_FA, 'Residence Document' AS NAME_EN, 'ثبت نشانی براساس مدرک سکونت' AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.ADDRESS_SOURCE_CODE=S.ADDRESS_SOURCE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (ADDRESS_SOURCE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.ADDRESS_SOURCE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

COMMIT;
