PROMPT Verifying Contact reference tables
SELECT 'REF_ADDRESS_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_ADDRESS_TYPE;
SELECT 'REF_BRANCH' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_BRANCH;
SELECT 'REF_CHANNEL' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_CHANNEL;
SELECT 'REF_COMMUNICATION_PURPOSE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_COMMUNICATION_PURPOSE;
SELECT 'REF_CONTACT_ASSOCIATION_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_CONTACT_ASSOCIATION_TYPE;
SELECT 'REF_CONTACT_PURPOSE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_CONTACT_PURPOSE;
SELECT 'REF_CONTACT_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_CONTACT_TYPE;
SELECT 'REF_SCRIPT' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_SCRIPT;
SELECT * FROM CIF.REF_ADDRESS_TYPE WHERE ADDRESS_TYPE_CODE='RESIDENTIAL';
SELECT * FROM CIF.REF_CONTACT_TYPE WHERE CONTACT_TYPE_CODE='MOBILE';
SELECT * FROM CIF.REF_CONTACT_PURPOSE WHERE CONTACT_PURPOSE_CODE='GENERAL';
