-- Fee Prototype P1 - core standalone physical model
CREATE TABLE FEE.FEE_DEFINITION (
  FEE_DEFINITION_ID NUMBER(19,0) NOT NULL,
  FEE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION VARCHAR2(1000 CHAR),
  CATEGORY_CODE VARCHAR2(50 CHAR),
  CLASSIFICATION_CODE VARCHAR2(30 CHAR) DEFAULT 'FEE' NOT NULL,
  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR),
  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FEE_DEFINITION PRIMARY KEY (FEE_DEFINITION_ID),
  CONSTRAINT UK_FEE_DEFINITION_CODE UNIQUE (FEE_CODE)
);

CREATE TABLE FEE.FEE_DEFINITION_VERSION (
  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  FEE_DEFINITION_ID NUMBER(19,0) NOT NULL,
  VERSION_NO NUMBER(10,0) NOT NULL,
  LIFECYCLE_STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'DRAFT' NOT NULL,
  EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
  APPROVED_AT TIMESTAMP(6), APPROVED_BY VARCHAR2(100 CHAR),
  ACTIVATED_AT TIMESTAMP(6), ACTIVATED_BY VARCHAR2(100 CHAR),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FEE_DEF_VERSION PRIMARY KEY (FEE_DEFINITION_VERSION_ID),
  CONSTRAINT FK_FEE_DEF_VERSION_DEF FOREIGN KEY (FEE_DEFINITION_ID) REFERENCES FEE.FEE_DEFINITION(FEE_DEFINITION_ID),
  CONSTRAINT UK_FEE_DEF_VERSION UNIQUE (FEE_DEFINITION_ID, VERSION_NO),
  CONSTRAINT CK_FEE_DEF_VERSION_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);

CREATE TABLE FEE.FEE_APPLICABILITY_RULE (
  APPLICABILITY_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  RULE_CODE VARCHAR2(50 CHAR) NOT NULL, NAME_FA VARCHAR2(200 CHAR), PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL,
  MATCH_MODE_CODE VARCHAR2(20 CHAR) DEFAULT 'ALL' NOT NULL, ACTION_CODE VARCHAR2(20 CHAR) DEFAULT 'APPLY' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_APPLICABILITY_RULE PRIMARY KEY (APPLICABILITY_RULE_ID),
  CONSTRAINT FK_FEE_APP_RULE_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT UK_FEE_APP_RULE UNIQUE (FEE_DEFINITION_VERSION_ID, RULE_CODE)
);

CREATE TABLE FEE.FEE_APPLICABILITY_CONDITION (
  CONDITION_ID NUMBER(19,0) NOT NULL, APPLICABILITY_RULE_ID NUMBER(19,0) NOT NULL, SEQUENCE_NO NUMBER(5,0) NOT NULL,
  DIMENSION_CODE VARCHAR2(50 CHAR) NOT NULL, OPERATOR_CODE VARCHAR2(30 CHAR) NOT NULL,
  TEXT_VALUE VARCHAR2(200 CHAR), NUMBER_VALUE_FROM NUMBER(23,4), NUMBER_VALUE_TO NUMBER(23,4), DATE_VALUE_FROM DATE, DATE_VALUE_TO DATE,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_APP_CONDITION PRIMARY KEY (CONDITION_ID),
  CONSTRAINT FK_FEE_APP_COND_RULE FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID)
);

CREATE TABLE FEE.FEE_CALCULATION_RULE (
  CALCULATION_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL, APPLICABILITY_RULE_ID NUMBER(19,0),
  RULE_CODE VARCHAR2(50 CHAR) NOT NULL, PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL,
  CALCULATION_STRATEGY_CODE VARCHAR2(40 CHAR) NOT NULL, BASIS_TYPE_CODE VARCHAR2(30 CHAR) DEFAULT 'AMOUNT' NOT NULL,
  FIXED_AMOUNT NUMBER(23,4), RATE_VALUE NUMBER(18,10), MIN_FEE_AMOUNT NUMBER(23,4), MAX_FEE_AMOUNT NUMBER(23,4),
  CURRENCY_CODE VARCHAR2(50 CHAR), ROUNDING_MODE_CODE VARCHAR2(30 CHAR) DEFAULT 'HALF_UP' NOT NULL, ROUNDING_SCALE NUMBER(2,0) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_CALC_RULE PRIMARY KEY (CALCULATION_RULE_ID),
  CONSTRAINT FK_FEE_CALC_RULE_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT FK_FEE_CALC_RULE_APP FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID),
  CONSTRAINT UK_FEE_CALC_RULE UNIQUE (FEE_DEFINITION_VERSION_ID, RULE_CODE),
  CONSTRAINT CK_FEE_CALC_RATE CHECK (RATE_VALUE IS NULL OR RATE_VALUE >= 0),
  CONSTRAINT CK_FEE_CALC_MINMAX CHECK (MIN_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT >= MIN_FEE_AMOUNT)
);

CREATE TABLE FEE.FEE_CALCULATION_TIER (
  CALCULATION_TIER_ID NUMBER(19,0) NOT NULL, CALCULATION_RULE_ID NUMBER(19,0) NOT NULL, TIER_NO NUMBER(5,0) NOT NULL,
  FROM_VALUE NUMBER(23,4) NOT NULL, TO_VALUE NUMBER(23,4), TIER_STRATEGY_CODE VARCHAR2(40 CHAR) NOT NULL,
  FIXED_AMOUNT NUMBER(23,4), RATE_VALUE NUMBER(18,10), MIN_FEE_AMOUNT NUMBER(23,4), MAX_FEE_AMOUNT NUMBER(23,4),
  CONSTRAINT PK_FEE_CALC_TIER PRIMARY KEY (CALCULATION_TIER_ID),
  CONSTRAINT FK_FEE_CALC_TIER_RULE FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID),
  CONSTRAINT UK_FEE_CALC_TIER UNIQUE (CALCULATION_RULE_ID, TIER_NO),
  CONSTRAINT CK_FEE_CALC_TIER_RANGE CHECK (TO_VALUE IS NULL OR TO_VALUE > FROM_VALUE)
);

CREATE TABLE FEE.FEE_CURRENCY_RULE (
  CURRENCY_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  CONFIG_CURRENCY_CODE VARCHAR2(50 CHAR) NOT NULL, BASIS_CURRENCY_MODE_CODE VARCHAR2(30 CHAR) NOT NULL, CHARGE_CURRENCY_MODE_CODE VARCHAR2(30 CHAR) NOT NULL,
  CHARGE_CURRENCY_CODE VARCHAR2(50 CHAR), FX_RATE_TYPE_CODE VARCHAR2(50 CHAR), FX_RATE_SOURCE_REF VARCHAR2(200 CHAR),
  ROUNDING_MODE_CODE VARCHAR2(30 CHAR) DEFAULT 'HALF_UP' NOT NULL, ROUNDING_SCALE NUMBER(2,0) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_CURRENCY_RULE PRIMARY KEY (CURRENCY_RULE_ID),
  CONSTRAINT FK_FEE_CURRENCY_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT UK_FEE_CURRENCY_VERSION UNIQUE (FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_TIMING_RULE (
  TIMING_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  APPLICATION_TIMING_CODE VARCHAR2(30 CHAR) NOT NULL, FREQUENCY_CODE VARCHAR2(30 CHAR), EVENT_CODE VARCHAR2(50 CHAR),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_TIMING_RULE PRIMARY KEY (TIMING_RULE_ID),
  CONSTRAINT FK_FEE_TIMING_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT UK_FEE_TIMING_VERSION UNIQUE (FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_COLLECTION_RULE (
  COLLECTION_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  COLLECTION_METHOD_CODE VARCHAR2(30 CHAR) NOT NULL, REVERSAL_METHOD_CODE VARCHAR2(30 CHAR), REFERENCE_REQUIRED_FLAG CHAR(1) DEFAULT 'N' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_COLLECTION_RULE PRIMARY KEY (COLLECTION_RULE_ID),
  CONSTRAINT FK_FEE_COLLECTION_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT UK_FEE_COLLECTION_VERSION UNIQUE (FEE_DEFINITION_VERSION_ID),
  CONSTRAINT CK_FEE_COLLECTION_REF CHECK (REFERENCE_REQUIRED_FLAG IN ('Y','N'))
);

CREATE TABLE FEE.FEE_POSTING_RULE (
  POSTING_RULE_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  POSTING_PROFILE_CODE VARCHAR2(50 CHAR) NOT NULL, DOCUMENT_TYPE_CODE VARCHAR2(50 CHAR), DEBIT_NARRATION VARCHAR2(500 CHAR), CREDIT_NARRATION VARCHAR2(500 CHAR),
  REVERSAL_PROFILE_CODE VARCHAR2(50 CHAR), CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_POSTING_RULE PRIMARY KEY (POSTING_RULE_ID),
  CONSTRAINT FK_FEE_POSTING_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT UK_FEE_POSTING_VERSION UNIQUE (FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_ADJUSTMENT_POLICY (
  ADJUSTMENT_POLICY_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL, APPLICABILITY_RULE_ID NUMBER(19,0),
  POLICY_CODE VARCHAR2(50 CHAR) NOT NULL, NAME_FA VARCHAR2(200 CHAR) NOT NULL, PRICING_FEATURE_TYPE_CODE VARCHAR2(40 CHAR) DEFAULT 'STANDARD' NOT NULL,
  ADJUSTMENT_TYPE_CODE VARCHAR2(40 CHAR) NOT NULL, PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL,
  PERCENT_VALUE NUMBER(18,10), FIXED_AMOUNT NUMBER(23,4), REPLACEMENT_AMOUNT NUMBER(23,4), REPLACEMENT_RATE NUMBER(18,10),
  CURRENCY_CODE VARCHAR2(50 CHAR), MIN_FINAL_FEE_AMOUNT NUMBER(23,4), STACKING_MODE_CODE VARCHAR2(30 CHAR) DEFAULT 'EXCLUSIVE' NOT NULL,
  APPROVAL_REQUIRED_FLAG CHAR(1) DEFAULT 'N' NOT NULL, EFFECTIVE_FROM DATE, EFFECTIVE_TO DATE,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_ADJUST_POLICY PRIMARY KEY (ADJUSTMENT_POLICY_ID),
  CONSTRAINT FK_FEE_ADJUST_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT FK_FEE_ADJUST_APP FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID),
  CONSTRAINT UK_FEE_ADJUST_POLICY UNIQUE (FEE_DEFINITION_VERSION_ID, POLICY_CODE),
  CONSTRAINT CK_FEE_ADJUST_APPROVAL CHECK (APPROVAL_REQUIRED_FLAG IN ('Y','N'))
);

CREATE TABLE FEE.FEE_ALLOCATION_POLICY (
  ALLOCATION_POLICY_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  POLICY_CODE VARCHAR2(50 CHAR) NOT NULL, NAME_FA VARCHAR2(200 CHAR) NOT NULL, RESIDUAL_METHOD_CODE VARCHAR2(30 CHAR) DEFAULT 'FIRST_PRIORITY' NOT NULL,
  EFFECTIVE_FROM DATE, EFFECTIVE_TO DATE, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_ALLOC_POLICY PRIMARY KEY (ALLOCATION_POLICY_ID),
  CONSTRAINT FK_FEE_ALLOC_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_ALLOCATION_RULE (
  ALLOCATION_RULE_ID NUMBER(19,0) NOT NULL, ALLOCATION_POLICY_ID NUMBER(19,0) NOT NULL, PRIORITY_NO NUMBER(10,0) NOT NULL,
  BENEFICIARY_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL, BENEFICIARY_REF VARCHAR2(200 CHAR), ALLOCATION_METHOD_CODE VARCHAR2(30 CHAR) NOT NULL,
  PERCENT_VALUE NUMBER(18,10), FIXED_AMOUNT NUMBER(23,4), CURRENCY_CODE VARCHAR2(50 CHAR),
  CONSTRAINT PK_FEE_ALLOC_RULE PRIMARY KEY (ALLOCATION_RULE_ID),
  CONSTRAINT FK_FEE_ALLOC_RULE_POLICY FOREIGN KEY (ALLOCATION_POLICY_ID) REFERENCES FEE.FEE_ALLOCATION_POLICY(ALLOCATION_POLICY_ID)
);

CREATE TABLE FEE.FEE_ARRANGEMENT (
  FEE_ARRANGEMENT_ID NUMBER(19,0) NOT NULL, ARRANGEMENT_NO VARCHAR2(100 CHAR) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  PRODUCT_REF VARCHAR2(200 CHAR), PRODUCT_FEATURE_REF VARCHAR2(200 CHAR), PARTY_REF VARCHAR2(200 CHAR), ACCOUNT_REF VARCHAR2(200 CHAR),
  ORIGIN_CODE VARCHAR2(30 CHAR) DEFAULT 'STANDARD' NOT NULL, STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  OVERRIDE_FIXED_AMOUNT NUMBER(23,4), OVERRIDE_RATE_VALUE NUMBER(18,10), OVERRIDE_MIN_FEE_AMOUNT NUMBER(23,4), OVERRIDE_MAX_FEE_AMOUNT NUMBER(23,4),
  EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL, RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FEE_ARRANGEMENT PRIMARY KEY (FEE_ARRANGEMENT_ID), CONSTRAINT UK_FEE_ARR_NO UNIQUE (ARRANGEMENT_NO),
  CONSTRAINT FK_FEE_ARR_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_INSTRUCTION (
  FEE_INSTRUCTION_ID NUMBER(19,0) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(100 CHAR) NOT NULL, CORRELATION_ID VARCHAR2(100 CHAR),
  FEE_ARRANGEMENT_ID NUMBER(19,0), FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL, BUSINESS_TRANSACTION_REF VARCHAR2(200 CHAR),
  PARTY_REF VARCHAR2(200 CHAR), ACCOUNT_REF VARCHAR2(200 CHAR), ACTIVITY_CODE VARCHAR2(50 CHAR), TRANSACTION_TYPE_CODE VARCHAR2(50 CHAR), CHANNEL_CODE VARCHAR2(50 CHAR),
  BASIS_AMOUNT NUMBER(23,4), BASIS_CURRENCY_CODE VARCHAR2(50 CHAR), STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'CREATED' NOT NULL,
  REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_INSTRUCTION PRIMARY KEY (FEE_INSTRUCTION_ID), CONSTRAINT UK_FEE_INSTRUCTION_IDEMP UNIQUE (IDEMPOTENCY_KEY),
  CONSTRAINT FK_FEE_INSTR_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID),
  CONSTRAINT FK_FEE_INSTR_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID)
);

CREATE TABLE FEE.FEE_TRANSACTION (
  FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL, FEE_INSTRUCTION_ID NUMBER(19,0) NOT NULL, FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  FEE_ARRANGEMENT_ID NUMBER(19,0), CALCULATION_RULE_ID NUMBER(19,0), BUSINESS_TRANSACTION_REF VARCHAR2(200 CHAR),
  GROSS_FEE_AMOUNT NUMBER(23,4) NOT NULL, ADJUSTMENT_AMOUNT NUMBER(23,4) DEFAULT 0 NOT NULL, NET_FEE_AMOUNT NUMBER(23,4) NOT NULL,
  CHARGED_AMOUNT NUMBER(23,4), FEE_CURRENCY_CODE VARCHAR2(50 CHAR) NOT NULL, STATUS_CODE VARCHAR2(30 CHAR) NOT NULL,
  CALCULATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CHARGED_AT TIMESTAMP(6), CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_TRANSACTION PRIMARY KEY (FEE_TRANSACTION_ID),
  CONSTRAINT FK_FEE_TX_INSTR FOREIGN KEY (FEE_INSTRUCTION_ID) REFERENCES FEE.FEE_INSTRUCTION(FEE_INSTRUCTION_ID),
  CONSTRAINT FK_FEE_TX_VERSION FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID),
  CONSTRAINT FK_FEE_TX_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID),
  CONSTRAINT FK_FEE_TX_CALC FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID)
);

CREATE TABLE FEE.FEE_CALCULATION_SNAPSHOT (
  CALCULATION_SNAPSHOT_ID NUMBER(19,0) NOT NULL, FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL,
  CALCULATION_STRATEGY_CODE VARCHAR2(40 CHAR) NOT NULL, BASIS_AMOUNT NUMBER(23,4), BASIS_CURRENCY_CODE VARCHAR2(50 CHAR),
  FIXED_AMOUNT NUMBER(23,4), RATE_VALUE NUMBER(18,10), MIN_FEE_AMOUNT NUMBER(23,4), MAX_FEE_AMOUNT NUMBER(23,4),
  FX_RATE_VALUE NUMBER(24,12), FX_RATE_TYPE_CODE VARCHAR2(50 CHAR), FX_RATE_SOURCE_REF VARCHAR2(200 CHAR), FX_RATE_TIMESTAMP TIMESTAMP(6),
  GROSS_FEE_AMOUNT NUMBER(23,4) NOT NULL, TOTAL_ADJUSTMENT_AMOUNT NUMBER(23,4) DEFAULT 0 NOT NULL, NET_FEE_AMOUNT NUMBER(23,4) NOT NULL,
  EXPLANATION_JSON CLOB, CALCULATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FEE_CALC_SNAPSHOT PRIMARY KEY (CALCULATION_SNAPSHOT_ID), CONSTRAINT UK_FEE_CALC_SNAPSHOT_TX UNIQUE (FEE_TRANSACTION_ID),
  CONSTRAINT FK_FEE_CALC_SNAPSHOT_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID)
);

CREATE TABLE FEE.FEE_APPLIED_ADJUSTMENT (
  APPLIED_ADJUSTMENT_ID NUMBER(19,0) NOT NULL, FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL, ADJUSTMENT_POLICY_ID NUMBER(19,0), SEQUENCE_NO NUMBER(5,0) NOT NULL,
  ADJUSTMENT_TYPE_CODE VARCHAR2(40 CHAR) NOT NULL, BASE_AMOUNT NUMBER(23,4), PERCENT_VALUE NUMBER(18,10), ADJUSTMENT_AMOUNT NUMBER(23,4) NOT NULL, RESULT_AMOUNT NUMBER(23,4) NOT NULL,
  CURRENCY_CODE VARCHAR2(50 CHAR) NOT NULL, APPROVAL_REF VARCHAR2(200 CHAR), APPLIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FEE_APPLIED_ADJUST PRIMARY KEY (APPLIED_ADJUSTMENT_ID),
  CONSTRAINT FK_FEE_APPLIED_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID),
  CONSTRAINT FK_FEE_APPLIED_POLICY FOREIGN KEY (ADJUSTMENT_POLICY_ID) REFERENCES FEE.FEE_ADJUSTMENT_POLICY(ADJUSTMENT_POLICY_ID)
);

CREATE TABLE FEE.FEE_ALLOCATION_RESULT (
  ALLOCATION_RESULT_ID NUMBER(19,0) NOT NULL, FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL, ALLOCATION_RULE_ID NUMBER(19,0),
  BENEFICIARY_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL, BENEFICIARY_REF VARCHAR2(200 CHAR), ALLOCATED_AMOUNT NUMBER(23,4) NOT NULL, CURRENCY_CODE VARCHAR2(50 CHAR) NOT NULL,
  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'CALCULATED' NOT NULL, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FEE_ALLOC_RESULT PRIMARY KEY (ALLOCATION_RESULT_ID),
  CONSTRAINT FK_FEE_ALLOC_RESULT_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID),
  CONSTRAINT FK_FEE_ALLOC_RESULT_RULE FOREIGN KEY (ALLOCATION_RULE_ID) REFERENCES FEE.FEE_ALLOCATION_RULE(ALLOCATION_RULE_ID)
);

CREATE TABLE FEE.FEE_POSTING_REFERENCE (
  POSTING_REFERENCE_ID NUMBER(19,0) NOT NULL, FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL, FEE_REVERSAL_ID NUMBER(19,0),
  POSTING_PURPOSE_CODE VARCHAR2(30 CHAR) NOT NULL, ACCOUNTING_INSTRUCTION_REF VARCHAR2(200 CHAR), POSTING_REF VARCHAR2(200 CHAR), JOURNAL_REF VARCHAR2(200 CHAR),
  POSTING_STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'PREVIEW' NOT NULL, REQUESTED_AT TIMESTAMP(6), COMPLETED_AT TIMESTAMP(6), CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FEE_POSTING_REF PRIMARY KEY (POSTING_REFERENCE_ID),
  CONSTRAINT FK_FEE_POSTING_REF_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID)
);

CREATE TABLE FEE.FEE_REVERSAL (
  FEE_REVERSAL_ID NUMBER(19,0) NOT NULL, FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL, REVERSAL_NO NUMBER(10,0) NOT NULL,
  REVERSAL_TYPE_CODE VARCHAR2(20 CHAR) NOT NULL, REVERSAL_AMOUNT NUMBER(23,4) NOT NULL, CURRENCY_CODE VARCHAR2(50 CHAR) NOT NULL,
  REASON_CODE VARCHAR2(50 CHAR), AUTHORIZATION_REF VARCHAR2(200 CHAR), STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'REQUESTED' NOT NULL,
  REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP(6), CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_FEE_REVERSAL PRIMARY KEY (FEE_REVERSAL_ID), CONSTRAINT UK_FEE_REVERSAL_NO UNIQUE (FEE_TRANSACTION_ID, REVERSAL_NO),
  CONSTRAINT FK_FEE_REVERSAL_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID),
  CONSTRAINT CK_FEE_REVERSAL_TYPE CHECK (REVERSAL_TYPE_CODE IN ('FULL','PARTIAL'))
);
