-- CBI Fee 1404 verification
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = FEE;
SET SERVEROUTPUT ON;

DECLARE
  v NUMBER;
  PROCEDURE assert_eq(p_label VARCHAR2, p_actual NUMBER, p_expected NUMBER) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD(p_label,45)||' actual='||p_actual||' expected='||p_expected);
    IF p_actual <> p_expected THEN RAISE_APPLICATION_ERROR(-20140, p_label||' mismatch'); END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO v FROM FEE_DEFINITION WHERE CLASSIFICATION_CODE='CBI_1404' AND IS_ACTIVE='Y';
  assert_eq('CBI1404 active definitions', v, 229);

  SELECT COUNT(*) INTO v
    FROM FEE_DEFINITION_VERSION dv
    JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
    JOIN FEE_REGULATORY_SOURCE rs ON rs.REGULATORY_SOURCE_ID=dv.REGULATORY_SOURCE_ID
   WHERE d.CLASSIFICATION_CODE='CBI_1404' AND dv.VERSION_NO='1.0' AND rs.SOURCE_CODE='CBI_FEE_1404_04_35500';
  assert_eq('CBI1404 definition versions', v, 229);

  SELECT COUNT(*) INTO v
    FROM FEE_DEFINITION d
   WHERE d.CLASSIFICATION_CODE='CBI_1404'
     AND NOT EXISTS (SELECT 1 FROM FEE_DEFINITION_VERSION dv WHERE dv.FEE_DEFINITION_ID=d.FEE_DEFINITION_ID AND dv.VERSION_NO='1.0');
  assert_eq('definitions without version', v, 0);

  SELECT COUNT(*) INTO v
    FROM FEE_DEFINITION d JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_ID=d.FEE_DEFINITION_ID
   WHERE d.CLASSIFICATION_CODE='CBI_1404'
     AND NOT EXISTS (SELECT 1 FROM FEE_CALCULATION_RULE r WHERE r.FEE_DEFINITION_VERSION_ID=dv.FEE_DEFINITION_VERSION_ID AND r.IS_ACTIVE='Y');
  assert_eq('definitions without active calc rule', v, 0);

  SELECT COUNT(*) INTO v
    FROM FEE_CALCULATION_RULE r
    JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_VERSION_ID=r.FEE_DEFINITION_VERSION_ID
    JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
   WHERE d.CLASSIFICATION_CODE='CBI_1404' AND r.RATE_VALUE IS NOT NULL AND (r.RATE_VALUE < 0 OR r.RATE_VALUE > 1);
  assert_eq('invalid normalized rate values', v, 0);

  SELECT COUNT(*) INTO v
    FROM FEE_CALCULATION_TIER t
    JOIN FEE_CALCULATION_RULE r ON r.CALCULATION_RULE_ID=t.CALCULATION_RULE_ID
    JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_VERSION_ID=r.FEE_DEFINITION_VERSION_ID
    JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
   WHERE d.CLASSIFICATION_CODE='CBI_1404';
  assert_eq('CBI1404 appraisal tiers', v, 15);

  SELECT COUNT(*) INTO v FROM (
    SELECT FEE_CODE FROM FEE_DEFINITION WHERE CLASSIFICATION_CODE='CBI_1404' GROUP BY FEE_CODE HAVING COUNT(*)>1
  );
  assert_eq('duplicate internal fee codes', v, 0);

  SELECT COUNT(*) INTO v
    FROM FEE_CALCULATION_RULE r
    JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_VERSION_ID=r.FEE_DEFINITION_VERSION_ID
    JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
   WHERE d.FEE_CODE='CBI_CREDIT_EXPERTISE_FEE' AND r.RULE_CODE='CREDIT_STAGE2' AND r.RATE_VALUE=0.001;
  assert_eq('corrected credit expertise stage2', v, 1);

  DBMS_OUTPUT.PUT_LINE('CBI Fee 1404 verification OK.');
END;
/

SELECT CALCULATION_STRATEGY_CODE, COUNT(*) AS RULE_COUNT
  FROM FEE_CALCULATION_RULE r
  JOIN FEE_DEFINITION_VERSION dv ON dv.FEE_DEFINITION_VERSION_ID=r.FEE_DEFINITION_VERSION_ID
  JOIN FEE_DEFINITION d ON d.FEE_DEFINITION_ID=dv.FEE_DEFINITION_ID
 WHERE d.CLASSIFICATION_CODE='CBI_1404' AND r.IS_ACTIVE='Y'
 GROUP BY CALCULATION_STRATEGY_CODE
 ORDER BY CALCULATION_STRATEGY_CODE;
