// Generated by tools/sync-system-specification.mjs. Do not edit manually.
export const GENERATED_SYSTEM_VERSIONS = {
  release: "0.3.80",
  java: "21",
  springBoot: "4.1.0",
  oracleJdbc: "23.26.2.0.0",
  angular: "21.0.0",
  angularMaterial: "21.0.0",
  rxjs: "7.8.2",
  typescript: "5.9.2"
} as const;
