package com.behsazan.corebanking.deposit.account.wavec.oracle;

import com.behsazan.corebanking.deposit.account.wavec.domain.DepositAccountWaveCModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.*;
import java.util.*;

@Repository
public class DepositAccountWaveCRepository {
    private final NamedParameterJdbcTemplate jdbc; private final String schema;
    public DepositAccountWaveCRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.oracle.business-schema:DPS2}") String schema){this.jdbc=jdbc;this.schema=id(schema);}
    public long next(String seq){return jdbc.queryForObject("SELECT "+schema+"."+id(seq)+".NEXTVAL FROM DUAL",Map.of(),Long.class);}
    public boolean accountExists(long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),Long.class);return n!=null&&n>0;}
    public AccountFact accountFact(long accountId){String sql="SELECT A.ACCOUNT_STATUS_CODE,A.CURRENCY_CODE,A.CURRENT_PRODUCT_VERSION_ID,NVL(B.LEDGER_BALANCE,0) FROM "+schema+".DEPOSIT_ACCOUNT A LEFT JOIN "+schema+".DEPOSIT_ACCOUNT_BALANCE B ON B.ACCOUNT_ID=A.ACCOUNT_ID WHERE A.ACCOUNT_ID=:id";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new AccountFact(r.getString(1),r.getString(2),r.getObject(3,Long.class),r.getBigDecimal(4))).stream().findFirst().orElse(null);}
    public boolean activeAccountParty(long accountId,long partyId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_PARTY WHERE ACCOUNT_ID=:aid AND PARTY_ID=:pid AND STATUS_CODE='ACTIVE' AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("pid",partyId),Long.class);return n!=null&&n>0;}
    public Optional<Long> primaryParty(long accountId){String sql="SELECT PARTY_ID FROM "+schema+".DEPOSIT_ACCOUNT_PARTY WHERE ACCOUNT_ID=:id AND STATUS_CODE='ACTIVE' ORDER BY IS_PRIMARY_PARTY DESC,ACCOUNT_PARTY_ID FETCH FIRST 1 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->r.getLong(1)).stream().findFirst();}
    public boolean activeContact(long accountId,String channel,String target){String type="EMAIL".equals(channel)?"EMAIL":"SMS".equals(channel)?"MOBILE":null;if(type==null)return true;Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_CONTACT WHERE ACCOUNT_ID=:aid AND CONTACT_TYPE_CODE=:type AND CONTACT_VALUE=:target AND VALID_FROM<=TRUNC(SYSDATE) AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("type",type).addValue("target",target),Long.class);return n!=null&&n>0;}

    public void insertInquiry(long id,long accountId,String type,String channel,String requestRef,Long party,String responseRef,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_INQUIRY(ACCOUNT_INQUIRY_ID,ACCOUNT_ID,INQUIRY_TYPE_CODE,CHANNEL_CODE,REQUEST_REFERENCE,REQUESTED_BY_PARTY_ID,AS_OF_TIMESTAMP,RESULT_STATUS_CODE,RESPONSE_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,:ch,:req,:pid,SYSTIMESTAMP,'SUCCESS',:resp,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("ch",channel).addValue("req",requestRef).addValue("pid",party,Types.NUMERIC).addValue("resp",responseRef).addValue("actor",actor));}
    public void insertConfirmation(long id,long accountId,String no,String type,BigDecimal balance,String status,String currency,String doc,String delivery,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_CONFIRMATION(ACCOUNT_CONFIRMATION_ID,ACCOUNT_ID,CONFIRMATION_NO,CONFIRMATION_TYPE_CODE,AS_OF_DATE,BALANCE_AMOUNT,ACCOUNT_STATUS_CODE,CURRENCY_CODE,ISSUED_AT,DOCUMENT_REFERENCE,DELIVERY_CHANNEL_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:no,:type,TRUNC(SYSDATE),:bal,:status,:cur,SYSTIMESTAMP,:doc,:delivery,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("no",no).addValue("type",type).addValue("bal",balance).addValue("status",status).addValue("cur",currency).addValue("doc",doc).addValue("delivery",delivery,Types.VARCHAR).addValue("actor",actor));}
    public void upsertNotificationPreference(long id,long accountId,String event,String channel,String target,boolean enabled,LocalDate from,LocalDate to,String actor){String sql="MERGE INTO "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE P USING (SELECT :aid ACCOUNT_ID,:event EVENT_CODE,:ch CHANNEL_CODE,:target DELIVERY_TARGET FROM DUAL) X ON (P.ACCOUNT_ID=X.ACCOUNT_ID AND P.EVENT_CODE=X.EVENT_CODE AND P.CHANNEL_CODE=X.CHANNEL_CODE AND P.DELIVERY_TARGET=X.DELIVERY_TARGET) WHEN MATCHED THEN UPDATE SET P.IS_ENABLED=:enabled,P.VALID_FROM=:vf,P.VALID_TO=:vt,P.UPDATED_AT=SYSTIMESTAMP,P.UPDATED_BY=:actor,P.RECORD_VERSION=P.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(NOTIFICATION_PREFERENCE_ID,ACCOUNT_ID,EVENT_CODE,CHANNEL_CODE,DELIVERY_TARGET,IS_ENABLED,VALID_FROM,VALID_TO,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:event,:ch,:target,:enabled,:vf,:vt,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("event",event).addValue("ch",channel).addValue("target",target).addValue("enabled",enabled?1:0).addValue("vf",from==null?null:Date.valueOf(from),Types.DATE).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertNotificationEvent(long id,long accountId,String event,String ref,String channel,String target,String provider,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_EVENT(NOTIFICATION_EVENT_ID,ACCOUNT_ID,EVENT_CODE,EVENT_REFERENCE,CHANNEL_CODE,DELIVERY_TARGET,DELIVERY_STATUS_CODE,ATTEMPT_NO,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:event,:ref,:ch,:target,'DELIVERED',1,SYSTIMESTAMP,SYSTIMESTAMP,:provider,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("event",event).addValue("ref",ref).addValue("ch",channel).addValue("target",target,Types.VARCHAR).addValue("provider",provider,Types.VARCHAR).addValue("actor",actor));}
    public void insertApiAccess(long id,long accountId,String client,String scope,Long party,String consent,OffsetDateTime from,OffsetDateTime to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_API_ACCESS(ACCOUNT_API_ACCESS_ID,ACCOUNT_ID,CLIENT_REFERENCE,API_SCOPE_CODE,AUTHORIZED_PARTY_ID,CONSENT_REFERENCE,STATUS_CODE,VALID_FROM,VALID_TO,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:client,:scope,:pid,:consent,'ACTIVE',NVL(:vf,SYSTIMESTAMP),:vt,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("client",client).addValue("scope",scope).addValue("pid",party,Types.NUMERIC).addValue("consent",consent,Types.VARCHAR).addValue("vf",ts(from),Types.TIMESTAMP).addValue("vt",ts(to),Types.TIMESTAMP).addValue("actor",actor));}
    public int revokeApiAccess(long accountId,long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_API_ACCESS SET STATUS_CODE='REVOKED',VALID_TO=NVL(VALID_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_API_ACCESS_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("aid",accountId));}

    public List<Inquiry> inquiries(long accountId){String sql="SELECT ACCOUNT_INQUIRY_ID,ACCOUNT_ID,INQUIRY_TYPE_CODE,CHANNEL_CODE,REQUEST_REFERENCE,REQUESTED_BY_PARTY_ID,AS_OF_TIMESTAMP,RESULT_STATUS_CODE,RESPONSE_REFERENCE FROM "+schema+".DEPOSIT_ACCOUNT_INQUIRY WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_INQUIRY_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Inquiry(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getObject(6,Long.class),offset(r.getTimestamp(7)),r.getString(8),r.getString(9)));}
    public List<Confirmation> confirmations(long accountId){String sql="SELECT ACCOUNT_CONFIRMATION_ID,ACCOUNT_ID,CONFIRMATION_NO,CONFIRMATION_TYPE_CODE,AS_OF_DATE,BALANCE_AMOUNT,ACCOUNT_STATUS_CODE,CURRENCY_CODE,ISSUED_AT,DOCUMENT_REFERENCE,DELIVERY_CHANNEL_CODE FROM "+schema+".DEPOSIT_ACCOUNT_CONFIRMATION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_CONFIRMATION_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Confirmation(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),date(r.getDate(5)),r.getBigDecimal(6),r.getString(7),r.getString(8),offset(r.getTimestamp(9)),r.getString(10),r.getString(11)));}
    public List<NotificationPreference> notificationPreferences(long accountId){String sql="SELECT NOTIFICATION_PREFERENCE_ID,ACCOUNT_ID,EVENT_CODE,CHANNEL_CODE,DELIVERY_TARGET,IS_ENABLED,VALID_FROM,VALID_TO,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE WHERE ACCOUNT_ID=:id ORDER BY NOTIFICATION_PREFERENCE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new NotificationPreference(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getInt(6)==1,date(r.getDate(7)),date(r.getDate(8)),r.getLong(9)));}
    public List<NotificationEvent> notificationEvents(long accountId){String sql="SELECT NOTIFICATION_EVENT_ID,ACCOUNT_ID,EVENT_CODE,EVENT_REFERENCE,CHANNEL_CODE,DELIVERY_TARGET,DELIVERY_STATUS_CODE,ATTEMPT_NO,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE FROM "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_EVENT WHERE ACCOUNT_ID=:id ORDER BY NOTIFICATION_EVENT_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new NotificationEvent(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getLong(8),offset(r.getTimestamp(9)),offset(r.getTimestamp(10)),r.getString(11)));}
    public List<ApiAccess> apiAccesses(long accountId){String sql="SELECT ACCOUNT_API_ACCESS_ID,ACCOUNT_ID,CLIENT_REFERENCE,API_SCOPE_CODE,AUTHORIZED_PARTY_ID,CONSENT_REFERENCE,STATUS_CODE,VALID_FROM,VALID_TO,LAST_USED_AT,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_API_ACCESS WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_API_ACCESS_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ApiAccess(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getObject(5,Long.class),r.getString(6),r.getString(7),offset(r.getTimestamp(8)),offset(r.getTimestamp(9)),offset(r.getTimestamp(10)),r.getLong(11)));}

    public void insertSignatureRule(long id,long accountId,String code,Integer min,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_SIGNATURE_RULE(ACCOUNT_SIGNATURE_RULE_ID,ACCOUNT_ID,SIGNATURE_RULE_CODE,MIN_SIGNATURE_COUNT,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:code,:min,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("code",code).addValue("min",min,Types.NUMERIC).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertDelegation(long id,long accountId,long grantor,long delegate,String type,String scope,BigDecimal max,String doc,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_DELEGATION(ACCOUNT_DELEGATION_ID,ACCOUNT_ID,GRANTOR_PARTY_ID,DELEGATE_PARTY_ID,DELEGATION_TYPE_CODE,AUTHORITY_SCOPE_CODE,MAX_AMOUNT,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:grantor,:delegate,:type,:scope,:max,:doc,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("grantor",grantor).addValue("delegate",delegate).addValue("type",type).addValue("scope",scope).addValue("max",max,Types.NUMERIC).addValue("doc",doc).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertAuthorizedUser(long id,long accountId,long party,String role,String channel,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_AUTHORIZED_USER(ACCOUNT_AUTHORIZED_USER_ID,ACCOUNT_ID,PARTY_ID,ACCESS_ROLE_CODE,CHANNEL_SCOPE_CODE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:role,:ch,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party).addValue("role",role).addValue("ch",channel,Types.VARCHAR).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertBeneficiary(long id,long accountId,Long party,String ref,String type,BigDecimal share,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_BENEFICIARY(ACCOUNT_BENEFICIARY_ID,ACCOUNT_ID,BENEFICIARY_PARTY_ID,BENEFICIARY_REFERENCE,BENEFICIARY_TYPE_CODE,SHARE_PERCENT,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:ref,:type,:share,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party,Types.NUMERIC).addValue("ref",ref,Types.VARCHAR).addValue("type",type).addValue("share",share,Types.NUMERIC).addValue("vf",from==null?null:Date.valueOf(from),Types.DATE).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertPaymentInstrument(long id,long accountId,String type,String ref,Long holder,OffsetDateTime issued,OffsetDateTime expires,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT(ACCOUNT_PAYMENT_INSTRUMENT_ID,ACCOUNT_ID,INSTRUMENT_TYPE_CODE,INSTRUMENT_REFERENCE,HOLDER_PARTY_ID,STATUS_CODE,ISSUED_AT,EXPIRES_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,:ref,:holder,'ACTIVE',:issued,:expires,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("ref",ref).addValue("holder",holder,Types.NUMERIC).addValue("issued",ts(issued),Types.TIMESTAMP).addValue("expires",ts(expires),Types.TIMESTAMP).addValue("actor",actor));}
    public int deactivate(String table,String pk,long accountId,long entityId,String actor){return jdbc.update("UPDATE "+schema+"."+id(table)+" SET STATUS_CODE='INACTIVE',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE "+id(pk)+"=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",entityId).addValue("aid",accountId));}

    public List<SignatureRule> signatureRules(long accountId){String sql="SELECT ACCOUNT_SIGNATURE_RULE_ID,ACCOUNT_ID,SIGNATURE_RULE_CODE,MIN_SIGNATURE_COUNT,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_SIGNATURE_RULE WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_SIGNATURE_RULE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new SignatureRule(r.getLong(1),r.getLong(2),r.getString(3),r.getObject(4,Integer.class),date(r.getDate(5)),date(r.getDate(6)),r.getString(7),r.getLong(8)));}
    public List<Delegation> delegations(long accountId){String sql="SELECT ACCOUNT_DELEGATION_ID,ACCOUNT_ID,GRANTOR_PARTY_ID,DELEGATE_PARTY_ID,DELEGATION_TYPE_CODE,AUTHORITY_SCOPE_CODE,MAX_AMOUNT,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_DELEGATION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_DELEGATION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Delegation(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getString(8),date(r.getDate(9)),date(r.getDate(10)),r.getString(11),r.getLong(12)));}
    public List<AuthorizedUser> authorizedUsers(long accountId){String sql="SELECT ACCOUNT_AUTHORIZED_USER_ID,ACCOUNT_ID,PARTY_ID,ACCESS_ROLE_CODE,CHANNEL_SCOPE_CODE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_AUTHORIZED_USER WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_AUTHORIZED_USER_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new AuthorizedUser(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),date(r.getDate(6)),date(r.getDate(7)),r.getString(8),r.getLong(9)));}
    public List<Beneficiary> beneficiaries(long accountId){String sql="SELECT ACCOUNT_BENEFICIARY_ID,ACCOUNT_ID,BENEFICIARY_PARTY_ID,BENEFICIARY_REFERENCE,BENEFICIARY_TYPE_CODE,SHARE_PERCENT,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_BENEFICIARY WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_BENEFICIARY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Beneficiary(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getBigDecimal(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10)));}
    public List<PaymentInstrument> paymentInstruments(long accountId){String sql="SELECT ACCOUNT_PAYMENT_INSTRUMENT_ID,ACCOUNT_ID,INSTRUMENT_TYPE_CODE,INSTRUMENT_REFERENCE,HOLDER_PARTY_ID,STATUS_CODE,ISSUED_AT,EXPIRES_AT,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_PAYMENT_INSTRUMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new PaymentInstrument(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getObject(5,Long.class),r.getString(6),offset(r.getTimestamp(7)),offset(r.getTimestamp(8)),r.getLong(9)));}

    public boolean regulatoryRuleExists(long id){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_REGULATORY_RULE WHERE REGULATORY_RULE_ID=:id AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE))",Map.of("id",id),Long.class);return n!=null&&n>0;}
    public void insertRegRestriction(long id,long accountId,Long rule,String type,String tx,String channel,BigDecimal limit,String legal,String authority,OffsetDateTime from,OffsetDateTime to,String releasePolicy,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION(ACCOUNT_REG_RESTRICTION_ID,ACCOUNT_ID,REGULATORY_RULE_ID,RESTRICTION_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,LIMIT_AMOUNT,LEGAL_ORDER_REFERENCE,ISSUING_AUTHORITY_CODE,VALID_FROM,VALID_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,RELEASE_POLICY_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:type,:tx,:ch,:limit,:legal,:authority,NVL(:vf,SYSTIMESTAMP),:vt,'ACTIVE','CORE_BANKING','COMPLIANCE',:legal,:release,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule,Types.NUMERIC).addValue("type",type).addValue("tx",tx,Types.VARCHAR).addValue("ch",channel,Types.VARCHAR).addValue("limit",limit,Types.NUMERIC).addValue("legal",legal,Types.VARCHAR).addValue("authority",authority,Types.VARCHAR).addValue("vf",ts(from),Types.TIMESTAMP).addValue("vt",ts(to),Types.TIMESTAMP).addValue("release",releasePolicy).addValue("actor",actor));}
    public int releaseRegRestriction(long accountId,long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION SET STATUS_CODE='RELEASED',VALID_TO=NVL(VALID_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_REG_RESTRICTION_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("aid",accountId));}
    public void insertComplianceEvaluation(long id,long rule,long accountId,String result,String reason,String engine,String waiver,String phase,OffsetDateTime valid,boolean recheck,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_COMPLIANCE_EVALUATION(COMPLIANCE_EVALUATION_ID,REGULATORY_RULE_ID,ACCOUNT_ID,RESULT_STATUS_CODE,RESULT_REASON_CODE,EVALUATED_AT,ENGINE_REFERENCE,WAIVER_REFERENCE,EVALUATION_PHASE_CODE,VALID_UNTIL,RECHECK_REQUIRED_FLAG,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rule,:aid,:result,:reason,SYSTIMESTAMP,:engine,:waiver,:phase,:valid,:recheck,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rule",rule).addValue("aid",accountId).addValue("result",result).addValue("reason",reason,Types.VARCHAR).addValue("engine",engine,Types.VARCHAR).addValue("waiver",waiver,Types.VARCHAR).addValue("phase",phase,Types.VARCHAR).addValue("valid",ts(valid),Types.TIMESTAMP).addValue("recheck",recheck?1:0).addValue("actor",actor));}
    public List<RegulatoryRestriction> regulatoryRestrictions(long accountId){String sql="SELECT ACCOUNT_REG_RESTRICTION_ID,ACCOUNT_ID,REGULATORY_RULE_ID,RESTRICTION_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,LIMIT_AMOUNT,LEGAL_ORDER_REFERENCE,ISSUING_AUTHORITY_CODE,VALID_FROM,VALID_TO,STATUS_CODE,RELEASE_POLICY_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_REG_RESTRICTION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new RegulatoryRestriction(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10)),offset(r.getTimestamp(11)),r.getString(12),r.getString(13),r.getLong(14)));}
    public List<ComplianceEvaluation> complianceEvaluations(long accountId){String sql="SELECT COMPLIANCE_EVALUATION_ID,REGULATORY_RULE_ID,ACCOUNT_ID,RESULT_STATUS_CODE,RESULT_REASON_CODE,EVALUATED_AT,ENGINE_REFERENCE,WAIVER_REFERENCE,EVALUATION_PHASE_CODE,VALID_UNTIL,RECHECK_REQUIRED_FLAG FROM "+schema+".DEPOSIT_COMPLIANCE_EVALUATION WHERE ACCOUNT_ID=:id ORDER BY COMPLIANCE_EVALUATION_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ComplianceEvaluation(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),offset(r.getTimestamp(6)),r.getString(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10)),r.getInt(11)==1));}

    public long insertApproval(long id,long accountId,String operation,String sourceType,long sourceId,String requestedBy,String approver,String idem,String correlation,String actor){String tracking="APR-11L-"+id;String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST(APPROVAL_REQUEST_ID,TRACKING_NO,ACCOUNT_ID,OPERATION_TYPE_CODE,SOURCE_ENTITY_TYPE,SOURCE_ENTITY_ID,REQUESTED_BY_USER_ID,REQUESTED_AT,APPROVER_USER_ID,APPROVAL_STATUS_CODE,ORG_UNIT_CODE,IDEMPOTENCY_KEY,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tracking,:aid,:op,:stype,:sid,:req,SYSTIMESTAMP,:approver,'PENDING_APPROVAL','DPS2',:idem,'CORE_BANKING','WAVE_C',:idem,:corr,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("tracking",tracking).addValue("aid",accountId).addValue("op",operation).addValue("stype",sourceType).addValue("sid",sourceId).addValue("req",requestedBy).addValue("approver",approver).addValue("idem",idem).addValue("corr",correlation).addValue("actor",actor));return id;}
    public void insertPricingOverride(long id,long accountId,Long rule,String type,BigDecimal base,BigDecimal value,String authority,long approval,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE(ACCOUNT_PRICING_OVERRIDE_ID,ACCOUNT_ID,PRICING_RULE_ID,OVERRIDE_TYPE_CODE,BASE_VALUE,OVERRIDE_VALUE,AUTHORITY_LEVEL_CODE,APPROVAL_REQUEST_ID,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:type,:base,:value,:authority,:approval,:vf,:vt,'PENDING_APPROVAL',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule,Types.NUMERIC).addValue("type",type).addValue("base",base,Types.NUMERIC).addValue("value",value).addValue("authority",authority).addValue("approval",approval).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public ApprovalLock approval(long id){String sql="SELECT APPROVAL_REQUEST_ID,ACCOUNT_ID,APPROVER_USER_ID,APPROVAL_STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST WHERE APPROVAL_REQUEST_ID=:id FOR UPDATE";return jdbc.query(sql,Map.of("id",id),(r,n)->new ApprovalLock(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5))).stream().findFirst().orElse(null);}
    public PricingOverrideLock pricingOverride(long accountId,long id){String sql="SELECT ACCOUNT_PRICING_OVERRIDE_ID,APPROVAL_REQUEST_ID,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE WHERE ACCOUNT_ID=:aid AND ACCOUNT_PRICING_OVERRIDE_ID=:id FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("id",id),(r,n)->new PricingOverrideLock(r.getLong(1),r.getObject(2,Long.class),r.getString(3),r.getLong(4))).stream().findFirst().orElse(null);}
    public int approveApproval(long id,long ver,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST SET APPROVAL_STATUS_CODE='APPROVED',DECIDED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE APPROVAL_REQUEST_ID=:id AND RECORD_VERSION=:ver AND APPROVAL_STATUS_CODE='PENDING_APPROVAL' AND APPROVER_USER_ID=:actor",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("ver",ver));}
    public int activatePricingOverride(long id,long ver,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE SET STATUS_CODE='ACTIVE',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_PRICING_OVERRIDE_ID=:id AND RECORD_VERSION=:ver AND STATUS_CODE='PENDING_APPROVAL'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("ver",ver));}
    public List<PricingOverride> pricingOverrides(long accountId){String sql="SELECT P.ACCOUNT_PRICING_OVERRIDE_ID,P.ACCOUNT_ID,P.PRICING_RULE_ID,P.OVERRIDE_TYPE_CODE,P.BASE_VALUE,P.OVERRIDE_VALUE,P.AUTHORITY_LEVEL_CODE,P.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,A.APPROVER_USER_ID,P.EFFECTIVE_FROM,P.EFFECTIVE_TO,P.STATUS_CODE,P.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE P LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=P.APPROVAL_REQUEST_ID WHERE P.ACCOUNT_ID=:id ORDER BY P.ACCOUNT_PRICING_OVERRIDE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new PricingOverride(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getString(7),r.getObject(8,Long.class),r.getString(9),r.getString(10),date(r.getDate(11)),date(r.getDate(12)),r.getString(13),r.getLong(14)));}
    public List<FeeAssessment> feeAssessments(long accountId){String sql="SELECT FEE_ASSESSMENT_ID,ACCOUNT_ID,TRANSACTION_ID,FEE_RULE_ID,BASE_AMOUNT,CALCULATED_FEE_AMOUNT,DISCOUNT_AMOUNT,FINAL_FEE_AMOUNT,ASSESSMENT_STATUS_CODE,POSTING_REFERENCE,COLLECTION_METHOD_CODE,COLLECTION_TRANSACTION_ID,WAIVER_REFERENCE FROM "+schema+".DEPOSIT_FEE_ASSESSMENT WHERE ACCOUNT_ID=:id ORDER BY FEE_ASSESSMENT_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new FeeAssessment(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getLong(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getString(9),r.getString(10),r.getString(11),r.getObject(12,Long.class),r.getString(13)));}
    public List<ProfitabilitySnapshot> profitability(long accountId){String sql="SELECT PROFITABILITY_SNAPSHOT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,PARTY_ID,PERIOD_START,PERIOD_END,AVERAGE_BALANCE,INTEREST_EXPENSE,FEE_REVENUE,OTHER_REVENUE,DIRECT_COST,NET_MARGIN,CALCULATED_AT FROM "+schema+".DEPOSIT_PROFITABILITY_SNAPSHOT WHERE ACCOUNT_ID=:id ORDER BY PROFITABILITY_SNAPSHOT_ID DESC FETCH FIRST 24 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ProfitabilitySnapshot(r.getLong(1),r.getObject(2,Long.class),r.getObject(3,Long.class),r.getObject(4,Long.class),date(r.getDate(5)),date(r.getDate(6)),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getBigDecimal(10),r.getBigDecimal(11),r.getBigDecimal(12),offset(r.getTimestamp(13))));}

    public TaxRule taxRule(long id){String sql="SELECT TAX_RULE_ID,TAX_TYPE_CODE,RATE_VALUE,MIN_TAXABLE_AMOUNT FROM "+schema+".DEPOSIT_TAX_RULE WHERE TAX_RULE_ID=:id AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE))";return jdbc.query(sql,Map.of("id",id),(r,n)->new TaxRule(r.getLong(1),r.getString(2),r.getBigDecimal(3),r.getBigDecimal(4))).stream().findFirst().orElse(null);}
    public BigDecimal activeTaxExemptionAmount(long accountId,String taxType,BigDecimal base){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_TAX_EXEMPTION WHERE ACCOUNT_ID=:aid AND TAX_TYPE_CODE=:type AND STATUS_CODE='ACTIVE' AND VALID_FROM<=TRUNC(SYSDATE) AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("type",taxType),Long.class);return n!=null&&n>0?base:BigDecimal.ZERO;}
    public void insertTaxExemption(long id,long party,long accountId,String code,String type,String doc,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_EXEMPTION(TAX_EXEMPTION_ID,PARTY_ID,ACCOUNT_ID,EXEMPTION_CODE,TAX_TYPE_CODE,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:aid,:code,:type,:doc,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",party).addValue("aid",accountId).addValue("code",code).addValue("type",type).addValue("doc",doc).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertTaxCalculation(long id,long accountId,long rule,Long profitPayment,Long tx,BigDecimal base,BigDecimal exempt,BigDecimal rate,BigDecimal amount,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_CALCULATION(TAX_CALCULATION_ID,ACCOUNT_ID,TAX_RULE_ID,PROFIT_PAYMENT_ID,TRANSACTION_ID,TAXABLE_BASE_AMOUNT,EXEMPT_AMOUNT,TAX_RATE,TAX_AMOUNT,CALCULATION_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:profit,:tx,:base,:exempt,:rate,:amount,'CALCULATED',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule).addValue("profit",profitPayment,Types.NUMERIC).addValue("tx",tx,Types.NUMERIC).addValue("base",base).addValue("exempt",exempt).addValue("rate",rate).addValue("amount",amount).addValue("actor",actor));}
    public void insertTaxCertificate(long id,long accountId,long party,String no,String type,LocalDate from,LocalDate to,BigDecimal gross,BigDecimal tax,String doc,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_CERTIFICATE(TAX_CERTIFICATE_ID,ACCOUNT_ID,PARTY_ID,CERTIFICATE_NO,TAX_TYPE_CODE,PERIOD_START,PERIOD_END,GROSS_AMOUNT,TAX_AMOUNT,ISSUED_AT,DOCUMENT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:no,:type,:ps,:pe,:gross,:tax,SYSTIMESTAMP,:doc,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party).addValue("no",no).addValue("type",type).addValue("ps",Date.valueOf(from)).addValue("pe",Date.valueOf(to)).addValue("gross",gross).addValue("tax",tax).addValue("doc",doc,Types.VARCHAR).addValue("actor",actor));}
    public List<TaxExemption> taxExemptions(long accountId){String sql="SELECT TAX_EXEMPTION_ID,PARTY_ID,ACCOUNT_ID,EXEMPTION_CODE,TAX_TYPE_CODE,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_TAX_EXEMPTION WHERE ACCOUNT_ID=:id ORDER BY TAX_EXEMPTION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxExemption(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getString(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10)));}
    public List<TaxCalculation> taxCalculations(long accountId){String sql="SELECT TAX_CALCULATION_ID,ACCOUNT_ID,TAX_RULE_ID,PROFIT_PAYMENT_ID,TRANSACTION_ID,TAXABLE_BASE_AMOUNT,EXEMPT_AMOUNT,TAX_RATE,TAX_AMOUNT,CALCULATION_STATUS_CODE FROM "+schema+".DEPOSIT_TAX_CALCULATION WHERE ACCOUNT_ID=:id ORDER BY TAX_CALCULATION_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxCalculation(r.getLong(1),r.getLong(2),r.getLong(3),r.getObject(4,Long.class),r.getObject(5,Long.class),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getString(10)));}
    public List<TaxCertificate> taxCertificates(long accountId){String sql="SELECT TAX_CERTIFICATE_ID,ACCOUNT_ID,PARTY_ID,CERTIFICATE_NO,TAX_TYPE_CODE,PERIOD_START,PERIOD_END,GROSS_AMOUNT,TAX_AMOUNT,ISSUED_AT,DOCUMENT_REFERENCE FROM "+schema+".DEPOSIT_TAX_CERTIFICATE WHERE ACCOUNT_ID=:id ORDER BY TAX_CERTIFICATE_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxCertificate(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),date(r.getDate(6)),date(r.getDate(7)),r.getBigDecimal(8),r.getBigDecimal(9),offset(r.getTimestamp(10)),r.getString(11)));}

    public Optional<IdemRow> idempotency(String key){String sql="SELECT IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,Map.of("k",key),(r,n)->new IdemRow(r.getString(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getString(5),r.getString(6))).stream().findFirst();}
    public void claimIdempotency(long id,String key,Long accountId,String operation,String hash,String actor,String correlation){String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','WAVE_C',:key,:corr,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("key",key).addValue("aid",accountId,Types.NUMERIC).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation,Types.VARCHAR));}
    public void completeIdempotency(String key,String result){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("ref",result).addValue("key",key));}

    public record AccountFact(String status,String currency,Long productVersionId,BigDecimal ledgerBalance){}
    public record ApprovalLock(long id,long accountId,String approver,String status,long version){}
    public record PricingOverrideLock(long id,Long approvalId,String status,long version){}
    public record TaxRule(long id,String taxType,BigDecimal rate,BigDecimal minTaxable){}
    public record IdemRow(String key,Long accountId,String operation,String payloadHash,String status,String resultReference){}
    private static String id(String v){if(v==null||!v.matches("[A-Za-z0-9_]+"))throw new IllegalArgumentException("Oracle identifier نامعتبر است: "+v);return v.toUpperCase(Locale.ROOT);}
    private static LocalDate date(Date d){return d==null?null:d.toLocalDate();}
    private static OffsetDateTime offset(Timestamp t){return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}
    private static Timestamp ts(OffsetDateTime v){return v==null?null:Timestamp.from(v.toInstant());}
}
