package com.behsazan.corebanking.deposit.account.wavec.oracle;

import com.behsazan.corebanking.deposit.account.wavec.domain.DepositAccountWaveCModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.*;
import java.util.*;

@Repository
public class DepositAccountWaveCRepository {
    private final NamedParameterJdbcTemplate jdbc; private final String schema;
    public DepositAccountWaveCRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.oracle.business-schema:DPS2}") String schema){this.jdbc=jdbc;this.schema=id(schema);}
    public long next(String seq){return jdbc.queryForObject("SELECT "+schema+"."+id(seq)+".NEXTVAL FROM DUAL",Map.of(),Long.class);}
    public boolean accountExists(long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),Long.class);return n!=null&&n>0;}
    public AccountFact accountFact(long accountId){String sql="SELECT A.ACCOUNT_STATUS_CODE,A.CURRENCY_CODE,A.CURRENT_PRODUCT_VERSION_ID,NVL(B.LEDGER_BALANCE,0) FROM "+schema+".DEPOSIT_ACCOUNT A LEFT JOIN "+schema+".DEPOSIT_ACCOUNT_BALANCE B ON B.ACCOUNT_ID=A.ACCOUNT_ID WHERE A.ACCOUNT_ID=:id";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new AccountFact(r.getString(1),r.getString(2),r.getObject(3,Long.class),r.getBigDecimal(4))).stream().findFirst().orElse(null);}
    public boolean activeAccountParty(long accountId,long partyId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_PARTY WHERE ACCOUNT_ID=:aid AND PARTY_ID=:pid AND STATUS_CODE='ACTIVE' AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("pid",partyId),Long.class);return n!=null&&n>0;}
    public Optional<Long> primaryParty(long accountId){String sql="SELECT PARTY_ID FROM "+schema+".DEPOSIT_ACCOUNT_PARTY WHERE ACCOUNT_ID=:id AND STATUS_CODE='ACTIVE' ORDER BY IS_PRIMARY_PARTY DESC,ACCOUNT_PARTY_ID FETCH FIRST 1 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->r.getLong(1)).stream().findFirst();}
    public boolean activeContact(long accountId,String channel,String target){String type="EMAIL".equals(channel)?"EMAIL":"SMS".equals(channel)?"MOBILE":null;if(type==null)return true;Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_CONTACT WHERE ACCOUNT_ID=:aid AND CONTACT_TYPE_CODE=:type AND CONTACT_VALUE=:target AND VALID_FROM<=TRUNC(SYSDATE) AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("type",type).addValue("target",target),Long.class);return n!=null&&n>0;}

    public void insertInquiry(long id,long accountId,String type,String channel,String requestRef,Long party,String responseRef,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_INQUIRY(ACCOUNT_INQUIRY_ID,ACCOUNT_ID,INQUIRY_TYPE_CODE,CHANNEL_CODE,REQUEST_REFERENCE,REQUESTED_BY_PARTY_ID,AS_OF_TIMESTAMP,RESULT_STATUS_CODE,RESPONSE_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,:ch,:req,:pid,SYSTIMESTAMP,'SUCCESS',:resp,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("ch",channel).addValue("req",requestRef).addValue("pid",party,Types.NUMERIC).addValue("resp",responseRef).addValue("actor",actor));}
    public void insertConfirmation(long id,long accountId,String no,String type,BigDecimal balance,String status,String currency,String doc,String delivery,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_CONFIRMATION(ACCOUNT_CONFIRMATION_ID,ACCOUNT_ID,CONFIRMATION_NO,CONFIRMATION_TYPE_CODE,AS_OF_DATE,BALANCE_AMOUNT,ACCOUNT_STATUS_CODE,CURRENCY_CODE,ISSUED_AT,DOCUMENT_REFERENCE,DELIVERY_CHANNEL_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:no,:type,TRUNC(SYSDATE),:bal,:status,:cur,SYSTIMESTAMP,:doc,:delivery,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("no",no).addValue("type",type).addValue("bal",balance).addValue("status",status).addValue("cur",currency).addValue("doc",doc).addValue("delivery",delivery,Types.VARCHAR).addValue("actor",actor));}
    public void upsertNotificationPreference(long id,long accountId,String event,String channel,String target,boolean enabled,LocalDate from,LocalDate to,String actor){String sql="MERGE INTO "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE P USING (SELECT :aid ACCOUNT_ID,:event EVENT_CODE,:ch CHANNEL_CODE,:target DELIVERY_TARGET FROM DUAL) X ON (P.ACCOUNT_ID=X.ACCOUNT_ID AND P.EVENT_CODE=X.EVENT_CODE AND P.CHANNEL_CODE=X.CHANNEL_CODE AND P.DELIVERY_TARGET=X.DELIVERY_TARGET) WHEN MATCHED THEN UPDATE SET P.IS_ENABLED=:enabled,P.VALID_FROM=:vf,P.VALID_TO=:vt,P.UPDATED_AT=SYSTIMESTAMP,P.UPDATED_BY=:actor,P.RECORD_VERSION=P.RECORD_VERSION+1 WHEN NOT MATCHED THEN INSERT(NOTIFICATION_PREFERENCE_ID,ACCOUNT_ID,EVENT_CODE,CHANNEL_CODE,DELIVERY_TARGET,IS_ENABLED,VALID_FROM,VALID_TO,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:event,:ch,:target,:enabled,:vf,:vt,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("event",event).addValue("ch",channel).addValue("target",target).addValue("enabled",enabled?1:0).addValue("vf",from==null?null:Date.valueOf(from),Types.DATE).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertNotificationEvent(long id,long accountId,String event,String ref,String channel,String target,String provider,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_EVENT(NOTIFICATION_EVENT_ID,ACCOUNT_ID,EVENT_CODE,EVENT_REFERENCE,CHANNEL_CODE,DELIVERY_TARGET,DELIVERY_STATUS_CODE,ATTEMPT_NO,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:event,:ref,:ch,:target,'DELIVERED',1,SYSTIMESTAMP,SYSTIMESTAMP,:provider,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("event",event).addValue("ref",ref).addValue("ch",channel).addValue("target",target,Types.VARCHAR).addValue("provider",provider,Types.VARCHAR).addValue("actor",actor));}
    public void insertApiAccess(long id,long accountId,String client,String scope,Long party,String consent,OffsetDateTime from,OffsetDateTime to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_API_ACCESS(ACCOUNT_API_ACCESS_ID,ACCOUNT_ID,CLIENT_REFERENCE,API_SCOPE_CODE,AUTHORIZED_PARTY_ID,CONSENT_REFERENCE,STATUS_CODE,VALID_FROM,VALID_TO,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:client,:scope,:pid,:consent,'ACTIVE',NVL(:vf,SYSTIMESTAMP),:vt,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("client",client).addValue("scope",scope).addValue("pid",party,Types.NUMERIC).addValue("consent",consent,Types.VARCHAR).addValue("vf",ts(from),Types.TIMESTAMP).addValue("vt",ts(to),Types.TIMESTAMP).addValue("actor",actor));}
    public int revokeApiAccess(long accountId,long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_API_ACCESS SET STATUS_CODE='REVOKED',VALID_TO=NVL(VALID_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_API_ACCESS_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("aid",accountId));}

    public List<Inquiry> inquiries(long accountId){String sql="SELECT ACCOUNT_INQUIRY_ID,ACCOUNT_ID,INQUIRY_TYPE_CODE,CHANNEL_CODE,REQUEST_REFERENCE,REQUESTED_BY_PARTY_ID,AS_OF_TIMESTAMP,RESULT_STATUS_CODE,RESPONSE_REFERENCE FROM "+schema+".DEPOSIT_ACCOUNT_INQUIRY WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_INQUIRY_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Inquiry(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getObject(6,Long.class),offset(r.getTimestamp(7)),r.getString(8),r.getString(9)));}
    public List<Confirmation> confirmations(long accountId){String sql="SELECT ACCOUNT_CONFIRMATION_ID,ACCOUNT_ID,CONFIRMATION_NO,CONFIRMATION_TYPE_CODE,AS_OF_DATE,BALANCE_AMOUNT,ACCOUNT_STATUS_CODE,CURRENCY_CODE,ISSUED_AT,DOCUMENT_REFERENCE,DELIVERY_CHANNEL_CODE FROM "+schema+".DEPOSIT_ACCOUNT_CONFIRMATION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_CONFIRMATION_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Confirmation(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),date(r.getDate(5)),r.getBigDecimal(6),r.getString(7),r.getString(8),offset(r.getTimestamp(9)),r.getString(10),r.getString(11)));}
    public List<NotificationPreference> notificationPreferences(long accountId){String sql="SELECT NOTIFICATION_PREFERENCE_ID,ACCOUNT_ID,EVENT_CODE,CHANNEL_CODE,DELIVERY_TARGET,IS_ENABLED,VALID_FROM,VALID_TO,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE WHERE ACCOUNT_ID=:id ORDER BY NOTIFICATION_PREFERENCE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new NotificationPreference(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getInt(6)==1,date(r.getDate(7)),date(r.getDate(8)),r.getLong(9)));}
    public List<NotificationEvent> notificationEvents(long accountId){String sql="SELECT NOTIFICATION_EVENT_ID,ACCOUNT_ID,EVENT_CODE,EVENT_REFERENCE,CHANNEL_CODE,DELIVERY_TARGET,DELIVERY_STATUS_CODE,ATTEMPT_NO,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE FROM "+schema+".DEPOSIT_ACCOUNT_NOTIFICATION_EVENT WHERE ACCOUNT_ID=:id ORDER BY NOTIFICATION_EVENT_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new NotificationEvent(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getLong(8),offset(r.getTimestamp(9)),offset(r.getTimestamp(10)),r.getString(11)));}
    public List<ApiAccess> apiAccesses(long accountId){String sql="SELECT ACCOUNT_API_ACCESS_ID,ACCOUNT_ID,CLIENT_REFERENCE,API_SCOPE_CODE,AUTHORIZED_PARTY_ID,CONSENT_REFERENCE,STATUS_CODE,VALID_FROM,VALID_TO,LAST_USED_AT,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_API_ACCESS WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_API_ACCESS_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ApiAccess(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getObject(5,Long.class),r.getString(6),r.getString(7),offset(r.getTimestamp(8)),offset(r.getTimestamp(9)),offset(r.getTimestamp(10)),r.getLong(11)));}

    public void insertSignatureRule(long id,long accountId,String code,Integer min,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_SIGNATURE_RULE(ACCOUNT_SIGNATURE_RULE_ID,ACCOUNT_ID,SIGNATURE_RULE_CODE,MIN_SIGNATURE_COUNT,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:code,:min,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("code",code).addValue("min",min,Types.NUMERIC).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertDelegation(long id,long accountId,long grantor,long delegate,String type,String scope,BigDecimal max,String doc,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_DELEGATION(ACCOUNT_DELEGATION_ID,ACCOUNT_ID,GRANTOR_PARTY_ID,DELEGATE_PARTY_ID,DELEGATION_TYPE_CODE,AUTHORITY_SCOPE_CODE,MAX_AMOUNT,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:grantor,:delegate,:type,:scope,:max,:doc,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("grantor",grantor).addValue("delegate",delegate).addValue("type",type).addValue("scope",scope).addValue("max",max,Types.NUMERIC).addValue("doc",doc).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertAuthorizedUser(long id,long accountId,long party,String role,String channel,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_AUTHORIZED_USER(ACCOUNT_AUTHORIZED_USER_ID,ACCOUNT_ID,PARTY_ID,ACCESS_ROLE_CODE,CHANNEL_SCOPE_CODE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:role,:ch,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party).addValue("role",role).addValue("ch",channel,Types.VARCHAR).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertBeneficiary(long id,long accountId,Long party,String ref,String type,BigDecimal share,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_BENEFICIARY(ACCOUNT_BENEFICIARY_ID,ACCOUNT_ID,BENEFICIARY_PARTY_ID,BENEFICIARY_REFERENCE,BENEFICIARY_TYPE_CODE,SHARE_PERCENT,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:ref,:type,:share,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party,Types.NUMERIC).addValue("ref",ref,Types.VARCHAR).addValue("type",type).addValue("share",share,Types.NUMERIC).addValue("vf",from==null?null:Date.valueOf(from),Types.DATE).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertPaymentInstrument(long id,long accountId,String type,String ref,Long holder,OffsetDateTime issued,OffsetDateTime expires,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT(ACCOUNT_PAYMENT_INSTRUMENT_ID,ACCOUNT_ID,INSTRUMENT_TYPE_CODE,INSTRUMENT_REFERENCE,HOLDER_PARTY_ID,STATUS_CODE,ISSUED_AT,EXPIRES_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,:ref,:holder,'ACTIVE',:issued,:expires,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("ref",ref).addValue("holder",holder,Types.NUMERIC).addValue("issued",ts(issued),Types.TIMESTAMP).addValue("expires",ts(expires),Types.TIMESTAMP).addValue("actor",actor));}
    public int deactivate(String table,String pk,long accountId,long entityId,String actor){return jdbc.update("UPDATE "+schema+"."+id(table)+" SET STATUS_CODE='INACTIVE',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE "+id(pk)+"=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",entityId).addValue("aid",accountId));}

    public List<SignatureRule> signatureRules(long accountId){String sql="SELECT ACCOUNT_SIGNATURE_RULE_ID,ACCOUNT_ID,SIGNATURE_RULE_CODE,MIN_SIGNATURE_COUNT,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_SIGNATURE_RULE WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_SIGNATURE_RULE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new SignatureRule(r.getLong(1),r.getLong(2),r.getString(3),r.getObject(4,Integer.class),date(r.getDate(5)),date(r.getDate(6)),r.getString(7),r.getLong(8)));}
    public List<Delegation> delegations(long accountId){String sql="SELECT ACCOUNT_DELEGATION_ID,ACCOUNT_ID,GRANTOR_PARTY_ID,DELEGATE_PARTY_ID,DELEGATION_TYPE_CODE,AUTHORITY_SCOPE_CODE,MAX_AMOUNT,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_DELEGATION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_DELEGATION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Delegation(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getString(8),date(r.getDate(9)),date(r.getDate(10)),r.getString(11),r.getLong(12)));}
    public List<AuthorizedUser> authorizedUsers(long accountId){String sql="SELECT ACCOUNT_AUTHORIZED_USER_ID,ACCOUNT_ID,PARTY_ID,ACCESS_ROLE_CODE,CHANNEL_SCOPE_CODE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_AUTHORIZED_USER WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_AUTHORIZED_USER_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new AuthorizedUser(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),date(r.getDate(6)),date(r.getDate(7)),r.getString(8),r.getLong(9)));}
    public List<Beneficiary> beneficiaries(long accountId){String sql="SELECT ACCOUNT_BENEFICIARY_ID,ACCOUNT_ID,BENEFICIARY_PARTY_ID,BENEFICIARY_REFERENCE,BENEFICIARY_TYPE_CODE,SHARE_PERCENT,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_BENEFICIARY WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_BENEFICIARY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new Beneficiary(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getBigDecimal(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10)));}
    public List<PaymentInstrument> paymentInstruments(long accountId){String sql="SELECT ACCOUNT_PAYMENT_INSTRUMENT_ID,ACCOUNT_ID,INSTRUMENT_TYPE_CODE,INSTRUMENT_REFERENCE,HOLDER_PARTY_ID,STATUS_CODE,ISSUED_AT,EXPIRES_AT,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_PAYMENT_INSTRUMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new PaymentInstrument(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getObject(5,Long.class),r.getString(6),offset(r.getTimestamp(7)),offset(r.getTimestamp(8)),r.getLong(9)));}

    public boolean regulatoryRuleExists(long id){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_REGULATORY_RULE WHERE REGULATORY_RULE_ID=:id AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE))",Map.of("id",id),Long.class);return n!=null&&n>0;}
    public void insertRegRestriction(long id,long accountId,Long rule,String type,String tx,String channel,BigDecimal limit,String legal,String authority,OffsetDateTime from,OffsetDateTime to,String releasePolicy,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION(ACCOUNT_REG_RESTRICTION_ID,ACCOUNT_ID,REGULATORY_RULE_ID,RESTRICTION_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,LIMIT_AMOUNT,LEGAL_ORDER_REFERENCE,ISSUING_AUTHORITY_CODE,VALID_FROM,VALID_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,RELEASE_POLICY_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:type,:tx,:ch,:limit,:legal,:authority,NVL(:vf,SYSTIMESTAMP),:vt,'ACTIVE','CORE_BANKING','COMPLIANCE',:legal,:release,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule,Types.NUMERIC).addValue("type",type).addValue("tx",tx,Types.VARCHAR).addValue("ch",channel,Types.VARCHAR).addValue("limit",limit,Types.NUMERIC).addValue("legal",legal,Types.VARCHAR).addValue("authority",authority,Types.VARCHAR).addValue("vf",ts(from),Types.TIMESTAMP).addValue("vt",ts(to),Types.TIMESTAMP).addValue("release",releasePolicy).addValue("actor",actor));}
    public int releaseRegRestriction(long accountId,long id,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION SET STATUS_CODE='RELEASED',VALID_TO=NVL(VALID_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_REG_RESTRICTION_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("aid",accountId));}
    public void insertComplianceEvaluation(long id,long rule,long accountId,String result,String reason,String engine,String waiver,String phase,OffsetDateTime valid,boolean recheck,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_COMPLIANCE_EVALUATION(COMPLIANCE_EVALUATION_ID,REGULATORY_RULE_ID,ACCOUNT_ID,RESULT_STATUS_CODE,RESULT_REASON_CODE,EVALUATED_AT,ENGINE_REFERENCE,WAIVER_REFERENCE,EVALUATION_PHASE_CODE,VALID_UNTIL,RECHECK_REQUIRED_FLAG,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rule,:aid,:result,:reason,SYSTIMESTAMP,:engine,:waiver,:phase,:valid,:recheck,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rule",rule).addValue("aid",accountId).addValue("result",result).addValue("reason",reason,Types.VARCHAR).addValue("engine",engine,Types.VARCHAR).addValue("waiver",waiver,Types.VARCHAR).addValue("phase",phase,Types.VARCHAR).addValue("valid",ts(valid),Types.TIMESTAMP).addValue("recheck",recheck?1:0).addValue("actor",actor));}
    public List<RegulatoryRestriction> regulatoryRestrictions(long accountId){String sql="SELECT ACCOUNT_REG_RESTRICTION_ID,ACCOUNT_ID,REGULATORY_RULE_ID,RESTRICTION_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,LIMIT_AMOUNT,LEGAL_ORDER_REFERENCE,ISSUING_AUTHORITY_CODE,VALID_FROM,VALID_TO,STATUS_CODE,RELEASE_POLICY_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION WHERE ACCOUNT_ID=:id ORDER BY ACCOUNT_REG_RESTRICTION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new RegulatoryRestriction(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10)),offset(r.getTimestamp(11)),r.getString(12),r.getString(13),r.getLong(14)));}
    public List<ComplianceEvaluation> complianceEvaluations(long accountId){String sql="SELECT COMPLIANCE_EVALUATION_ID,REGULATORY_RULE_ID,ACCOUNT_ID,RESULT_STATUS_CODE,RESULT_REASON_CODE,EVALUATED_AT,ENGINE_REFERENCE,WAIVER_REFERENCE,EVALUATION_PHASE_CODE,VALID_UNTIL,RECHECK_REQUIRED_FLAG FROM "+schema+".DEPOSIT_COMPLIANCE_EVALUATION WHERE ACCOUNT_ID=:id ORDER BY COMPLIANCE_EVALUATION_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ComplianceEvaluation(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),offset(r.getTimestamp(6)),r.getString(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10)),r.getInt(11)==1));}

    public long insertApproval(long id,long accountId,String operation,String sourceType,long sourceId,String requestedBy,String approver,String idem,String correlation,String actor){String tracking="APR-11L-"+id;String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST(APPROVAL_REQUEST_ID,TRACKING_NO,ACCOUNT_ID,OPERATION_TYPE_CODE,SOURCE_ENTITY_TYPE,SOURCE_ENTITY_ID,REQUESTED_BY_USER_ID,REQUESTED_AT,APPROVER_USER_ID,APPROVAL_STATUS_CODE,ORG_UNIT_CODE,IDEMPOTENCY_KEY,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tracking,:aid,:op,:stype,:sid,:req,SYSTIMESTAMP,:approver,'PENDING_APPROVAL','DPS2',:idem,'CORE_BANKING','WAVE_C',:idem,:corr,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("tracking",tracking).addValue("aid",accountId).addValue("op",operation).addValue("stype",sourceType).addValue("sid",sourceId).addValue("req",requestedBy).addValue("approver",approver).addValue("idem",idem).addValue("corr",correlation).addValue("actor",actor));return id;}
    public void insertPricingOverride(long id,long accountId,Long rule,String type,BigDecimal base,BigDecimal value,String authority,long approval,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE(ACCOUNT_PRICING_OVERRIDE_ID,ACCOUNT_ID,PRICING_RULE_ID,OVERRIDE_TYPE_CODE,BASE_VALUE,OVERRIDE_VALUE,AUTHORITY_LEVEL_CODE,APPROVAL_REQUEST_ID,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:type,:base,:value,:authority,:approval,:vf,:vt,'PENDING_APPROVAL',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule,Types.NUMERIC).addValue("type",type).addValue("base",base,Types.NUMERIC).addValue("value",value).addValue("authority",authority).addValue("approval",approval).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public ApprovalLock approval(long id){String sql="SELECT APPROVAL_REQUEST_ID,ACCOUNT_ID,APPROVER_USER_ID,APPROVAL_STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST WHERE APPROVAL_REQUEST_ID=:id FOR UPDATE";return jdbc.query(sql,Map.of("id",id),(r,n)->new ApprovalLock(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5))).stream().findFirst().orElse(null);}
    public PricingOverrideLock pricingOverride(long accountId,long id){String sql="SELECT ACCOUNT_PRICING_OVERRIDE_ID,APPROVAL_REQUEST_ID,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE WHERE ACCOUNT_ID=:aid AND ACCOUNT_PRICING_OVERRIDE_ID=:id FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("id",id),(r,n)->new PricingOverrideLock(r.getLong(1),r.getObject(2,Long.class),r.getString(3),r.getLong(4))).stream().findFirst().orElse(null);}
    public int approveApproval(long id,long ver,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST SET APPROVAL_STATUS_CODE='APPROVED',DECIDED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE APPROVAL_REQUEST_ID=:id AND RECORD_VERSION=:ver AND APPROVAL_STATUS_CODE='PENDING_APPROVAL' AND APPROVER_USER_ID=:actor",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("ver",ver));}
    public int activatePricingOverride(long id,long ver,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE SET STATUS_CODE='ACTIVE',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_PRICING_OVERRIDE_ID=:id AND RECORD_VERSION=:ver AND STATUS_CODE='PENDING_APPROVAL'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("ver",ver));}
    public List<PricingOverride> pricingOverrides(long accountId){String sql="SELECT P.ACCOUNT_PRICING_OVERRIDE_ID,P.ACCOUNT_ID,P.PRICING_RULE_ID,P.OVERRIDE_TYPE_CODE,P.BASE_VALUE,P.OVERRIDE_VALUE,P.AUTHORITY_LEVEL_CODE,P.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,A.APPROVER_USER_ID,P.EFFECTIVE_FROM,P.EFFECTIVE_TO,P.STATUS_CODE,P.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_PRICING_OVERRIDE P LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=P.APPROVAL_REQUEST_ID WHERE P.ACCOUNT_ID=:id ORDER BY P.ACCOUNT_PRICING_OVERRIDE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new PricingOverride(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getString(7),r.getObject(8,Long.class),r.getString(9),r.getString(10),date(r.getDate(11)),date(r.getDate(12)),r.getString(13),r.getLong(14)));}
    public List<FeeAssessment> feeAssessments(long accountId){String sql="SELECT FEE_ASSESSMENT_ID,ACCOUNT_ID,TRANSACTION_ID,FEE_RULE_ID,BASE_AMOUNT,CALCULATED_FEE_AMOUNT,DISCOUNT_AMOUNT,FINAL_FEE_AMOUNT,ASSESSMENT_STATUS_CODE,POSTING_REFERENCE,COLLECTION_METHOD_CODE,COLLECTION_TRANSACTION_ID,WAIVER_REFERENCE FROM "+schema+".DEPOSIT_FEE_ASSESSMENT WHERE ACCOUNT_ID=:id ORDER BY FEE_ASSESSMENT_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new FeeAssessment(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getLong(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getString(9),r.getString(10),r.getString(11),r.getObject(12,Long.class),r.getString(13)));}
    public List<ProfitabilitySnapshot> profitability(long accountId){String sql="SELECT PROFITABILITY_SNAPSHOT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,PARTY_ID,PERIOD_START,PERIOD_END,AVERAGE_BALANCE,INTEREST_EXPENSE,FEE_REVENUE,OTHER_REVENUE,DIRECT_COST,NET_MARGIN,CALCULATED_AT FROM "+schema+".DEPOSIT_PROFITABILITY_SNAPSHOT WHERE ACCOUNT_ID=:id ORDER BY PROFITABILITY_SNAPSHOT_ID DESC FETCH FIRST 24 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ProfitabilitySnapshot(r.getLong(1),r.getObject(2,Long.class),r.getObject(3,Long.class),r.getObject(4,Long.class),date(r.getDate(5)),date(r.getDate(6)),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getBigDecimal(10),r.getBigDecimal(11),r.getBigDecimal(12),offset(r.getTimestamp(13))));}

    public TaxRule taxRule(long id){String sql="SELECT TAX_RULE_ID,TAX_TYPE_CODE,RATE_VALUE,MIN_TAXABLE_AMOUNT FROM "+schema+".DEPOSIT_TAX_RULE WHERE TAX_RULE_ID=:id AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE))";return jdbc.query(sql,Map.of("id",id),(r,n)->new TaxRule(r.getLong(1),r.getString(2),r.getBigDecimal(3),r.getBigDecimal(4))).stream().findFirst().orElse(null);}
    public BigDecimal activeTaxExemptionAmount(long accountId,String taxType,BigDecimal base){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_TAX_EXEMPTION WHERE ACCOUNT_ID=:aid AND TAX_TYPE_CODE=:type AND STATUS_CODE='ACTIVE' AND VALID_FROM<=TRUNC(SYSDATE) AND (VALID_TO IS NULL OR VALID_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("type",taxType),Long.class);return n!=null&&n>0?base:BigDecimal.ZERO;}
    public void insertTaxExemption(long id,long party,long accountId,String code,String type,String doc,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_EXEMPTION(TAX_EXEMPTION_ID,PARTY_ID,ACCOUNT_ID,EXEMPTION_CODE,TAX_TYPE_CODE,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:aid,:code,:type,:doc,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",party).addValue("aid",accountId).addValue("code",code).addValue("type",type).addValue("doc",doc).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertTaxCalculation(long id,long accountId,long rule,Long profitPayment,Long tx,BigDecimal base,BigDecimal exempt,BigDecimal rate,BigDecimal amount,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_CALCULATION(TAX_CALCULATION_ID,ACCOUNT_ID,TAX_RULE_ID,PROFIT_PAYMENT_ID,TRANSACTION_ID,TAXABLE_BASE_AMOUNT,EXEMPT_AMOUNT,TAX_RATE,TAX_AMOUNT,CALCULATION_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rule,:profit,:tx,:base,:exempt,:rate,:amount,'CALCULATED',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rule",rule).addValue("profit",profitPayment,Types.NUMERIC).addValue("tx",tx,Types.NUMERIC).addValue("base",base).addValue("exempt",exempt).addValue("rate",rate).addValue("amount",amount).addValue("actor",actor));}
    public void insertTaxCertificate(long id,long accountId,long party,String no,String type,LocalDate from,LocalDate to,BigDecimal gross,BigDecimal tax,String doc,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_CERTIFICATE(TAX_CERTIFICATE_ID,ACCOUNT_ID,PARTY_ID,CERTIFICATE_NO,TAX_TYPE_CODE,PERIOD_START,PERIOD_END,GROSS_AMOUNT,TAX_AMOUNT,ISSUED_AT,DOCUMENT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pid,:no,:type,:ps,:pe,:gross,:tax,SYSTIMESTAMP,:doc,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pid",party).addValue("no",no).addValue("type",type).addValue("ps",Date.valueOf(from)).addValue("pe",Date.valueOf(to)).addValue("gross",gross).addValue("tax",tax).addValue("doc",doc,Types.VARCHAR).addValue("actor",actor));}
    public List<TaxExemption> taxExemptions(long accountId){String sql="SELECT TAX_EXEMPTION_ID,PARTY_ID,ACCOUNT_ID,EXEMPTION_CODE,TAX_TYPE_CODE,DOCUMENT_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_TAX_EXEMPTION WHERE ACCOUNT_ID=:id ORDER BY TAX_EXEMPTION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxExemption(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getString(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10)));}
    public List<TaxCalculation> taxCalculations(long accountId){String sql="SELECT TAX_CALCULATION_ID,ACCOUNT_ID,TAX_RULE_ID,PROFIT_PAYMENT_ID,TRANSACTION_ID,TAXABLE_BASE_AMOUNT,EXEMPT_AMOUNT,TAX_RATE,TAX_AMOUNT,CALCULATION_STATUS_CODE FROM "+schema+".DEPOSIT_TAX_CALCULATION WHERE ACCOUNT_ID=:id ORDER BY TAX_CALCULATION_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxCalculation(r.getLong(1),r.getLong(2),r.getLong(3),r.getObject(4,Long.class),r.getObject(5,Long.class),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getString(10)));}
    public List<TaxCertificate> taxCertificates(long accountId){String sql="SELECT TAX_CERTIFICATE_ID,ACCOUNT_ID,PARTY_ID,CERTIFICATE_NO,TAX_TYPE_CODE,PERIOD_START,PERIOD_END,GROSS_AMOUNT,TAX_AMOUNT,ISSUED_AT,DOCUMENT_REFERENCE FROM "+schema+".DEPOSIT_TAX_CERTIFICATE WHERE ACCOUNT_ID=:id ORDER BY TAX_CERTIFICATE_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxCertificate(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),date(r.getDate(6)),date(r.getDate(7)),r.getBigDecimal(8),r.getBigDecimal(9),offset(r.getTimestamp(10)),r.getString(11)));}

    public Optional<IdemRow> idempotency(String key){String sql="SELECT IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,Map.of("k",key),(r,n)->new IdemRow(r.getString(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getString(5),r.getString(6))).stream().findFirst();}
    public void claimIdempotency(long id,String key,Long accountId,String operation,String hash,String actor,String correlation){String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','WAVE_C',:key,:corr,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("key",key).addValue("aid",accountId,Types.NUMERIC).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation,Types.VARCHAR));}
    public void completeIdempotency(String key,String result){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("ref",result).addValue("key",key));}

    public record AccountFact(String status,String currency,Long productVersionId,BigDecimal ledgerBalance){}
    public List<ReserveRequirement> reserveRequirements(long accountId){String sql="SELECT R.RESERVE_REQUIREMENT_ID,R.REGULATOR_CODE,R.PRODUCT_VERSION_ID,R.PRODUCT_FAMILY_CODE,R.CURRENCY_CODE,R.RESERVE_RATIO,R.ELIGIBLE_BALANCE_RULE_CODE,R.EFFECTIVE_FROM,R.EFFECTIVE_TO,R.STATUS_CODE FROM "+schema+".DEPOSIT_RESERVE_REQUIREMENT R JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:id WHERE R.STATUS_CODE='ACTIVE' AND (R.PRODUCT_VERSION_ID IS NULL OR R.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND (R.CURRENCY_CODE IS NULL OR R.CURRENCY_CODE=A.CURRENCY_CODE) AND R.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (R.EFFECTIVE_TO IS NULL OR R.EFFECTIVE_TO>=TRUNC(SYSDATE)) ORDER BY R.RESERVE_REQUIREMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ReserveRequirement(r.getLong(1),r.getString(2),r.getObject(3,Long.class),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getString(7),date(r.getDate(8)),date(r.getDate(9)),r.getString(10)));}
    public List<ReservePosition> reservePositions(long accountId){String sql="SELECT P.RESERVE_POSITION_ID,P.RESERVE_REQUIREMENT_ID,P.BUSINESS_DATE,P.CURRENCY_CODE,P.ELIGIBLE_BALANCE,P.REQUIRED_RESERVE_AMOUNT,P.ACTUAL_RESERVE_AMOUNT,P.POSITION_STATUS_CODE FROM "+schema+".DEPOSIT_RESERVE_POSITION P JOIN "+schema+".DEPOSIT_RESERVE_REQUIREMENT R ON R.RESERVE_REQUIREMENT_ID=P.RESERVE_REQUIREMENT_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:id WHERE (R.PRODUCT_VERSION_ID IS NULL OR R.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND (R.CURRENCY_CODE IS NULL OR R.CURRENCY_CODE=A.CURRENCY_CODE) ORDER BY P.BUSINESS_DATE DESC,P.RESERVE_POSITION_ID DESC FETCH FIRST 30 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new ReservePosition(r.getLong(1),r.getLong(2),date(r.getDate(3)),r.getString(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8)));}
    public List<RegulatoryReportItem> regulatoryReportItems(long accountId){String sql="SELECT I.REGULATORY_REPORT_ITEM_ID,I.REGULATORY_REPORT_ID,I.ACCOUNT_ID,I.PRODUCT_VERSION_ID,I.MEASURE_CODE,I.MEASURE_AMOUNT,I.MEASURE_COUNT,R.REPORT_TYPE_CODE,R.REGULATOR_CODE,R.PERIOD_START,R.PERIOD_END,R.STATUS_CODE,R.FILE_REFERENCE,R.SUBMISSION_REFERENCE FROM "+schema+".DEPOSIT_REGULATORY_REPORT_ITEM I JOIN "+schema+".DEPOSIT_REGULATORY_REPORT R ON R.REGULATORY_REPORT_ID=I.REGULATORY_REPORT_ID WHERE I.ACCOUNT_ID=:id ORDER BY I.REGULATORY_REPORT_ITEM_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new RegulatoryReportItem(r.getLong(1),r.getLong(2),r.getLong(3),r.getObject(4,Long.class),r.getString(5),r.getBigDecimal(6),r.getObject(7,Long.class),r.getString(8),r.getString(9),date(r.getDate(10)),date(r.getDate(11)),r.getString(12),r.getString(13),r.getString(14)));}

    public List<FeeRule> feeRules(long accountId){String sql="SELECT F.FEE_RULE_ID,F.PRODUCT_VERSION_ID,F.FEE_CODE,F.FEE_EVENT_CODE,F.CALCULATION_METHOD_CODE,F.FIXED_AMOUNT,F.RATE_VALUE,F.MIN_FEE_AMOUNT,F.MAX_FEE_AMOUNT,F.RULE_VERSION_NO,F.EFFECTIVE_FROM,F.EFFECTIVE_TO,F.IS_ACTIVE FROM "+schema+".DEPOSIT_FEE_RULE F JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:id WHERE F.IS_ACTIVE=1 AND (F.PRODUCT_VERSION_ID IS NULL OR F.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND F.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (F.EFFECTIVE_TO IS NULL OR F.EFFECTIVE_TO>=TRUNC(SYSDATE)) ORDER BY F.FEE_RULE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new FeeRule(r.getLong(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getLong(10),date(r.getDate(11)),date(r.getDate(12)),r.getInt(13)==1));}
    public List<FeeTier> feeTiers(long accountId){String sql="SELECT T.FEE_TIER_ID,T.FEE_RULE_ID,T.TIER_NO,T.MIN_BASE_AMOUNT,T.MAX_BASE_AMOUNT,T.FEE_AMOUNT,T.FEE_RATE FROM "+schema+".DEPOSIT_FEE_TIER T JOIN "+schema+".DEPOSIT_FEE_RULE F ON F.FEE_RULE_ID=T.FEE_RULE_ID JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:id WHERE F.IS_ACTIVE=1 AND (F.PRODUCT_VERSION_ID IS NULL OR F.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) ORDER BY T.FEE_RULE_ID,T.TIER_NO";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new FeeTier(r.getLong(1),r.getLong(2),r.getLong(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7)));}
    public boolean activeFeeRule(long accountId,long feeRuleId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_FEE_RULE F JOIN "+schema+".DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=:aid WHERE F.FEE_RULE_ID=:rid AND F.IS_ACTIVE=1 AND (F.PRODUCT_VERSION_ID IS NULL OR F.PRODUCT_VERSION_ID=A.CURRENT_PRODUCT_VERSION_ID) AND F.EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (F.EFFECTIVE_TO IS NULL OR F.EFFECTIVE_TO>=TRUNC(SYSDATE))",new MapSqlParameterSource().addValue("aid",accountId).addValue("rid",feeRuleId),Long.class);return n!=null&&n>0;}
    public void insertFeeOverride(long id,long accountId,long feeRuleId,String type,BigDecimal value,String authority,long approval,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_FEE_OVERRIDE(ACCOUNT_FEE_OVERRIDE_ID,ACCOUNT_ID,FEE_RULE_ID,OVERRIDE_TYPE_CODE,OVERRIDE_VALUE,AUTHORITY_LEVEL_CODE,APPROVAL_REQUEST_ID,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:rid,:type,:value,:authority,:approval,:vf,:vt,'PENDING_APPROVAL',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("rid",feeRuleId).addValue("type",type).addValue("value",value).addValue("authority",authority).addValue("approval",approval).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public FeeOverrideLock feeOverride(long accountId,long id){String sql="SELECT ACCOUNT_FEE_OVERRIDE_ID,APPROVAL_REQUEST_ID,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_FEE_OVERRIDE WHERE ACCOUNT_FEE_OVERRIDE_ID=:id AND ACCOUNT_ID=:aid FOR UPDATE";return jdbc.query(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId),(r,n)->new FeeOverrideLock(r.getLong(1),r.getObject(2,Long.class),r.getString(3),r.getLong(4))).stream().findFirst().orElse(null);}
    public int activateFeeOverride(long id,long version,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_FEE_OVERRIDE SET STATUS_CODE='ACTIVE',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_FEE_OVERRIDE_ID=:id AND RECORD_VERSION=:ver AND STATUS_CODE='PENDING_APPROVAL'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",id).addValue("ver",version));}
    public List<FeeOverride> feeOverrides(long accountId){String sql="SELECT F.ACCOUNT_FEE_OVERRIDE_ID,F.ACCOUNT_ID,F.FEE_RULE_ID,F.OVERRIDE_TYPE_CODE,F.OVERRIDE_VALUE,F.AUTHORITY_LEVEL_CODE,F.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,F.EFFECTIVE_FROM,F.EFFECTIVE_TO,F.STATUS_CODE,F.RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_FEE_OVERRIDE F LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=F.APPROVAL_REQUEST_ID WHERE F.ACCOUNT_ID=:id ORDER BY F.ACCOUNT_FEE_OVERRIDE_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new FeeOverride(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getBigDecimal(5),r.getString(6),r.getObject(7,Long.class),r.getString(8),date(r.getDate(9)),date(r.getDate(10)),r.getString(11),r.getLong(12)));}
    public List<PricingPackage> pricingPackages(){String sql="SELECT PRICING_PACKAGE_ID,PACKAGE_CODE,PACKAGE_NAME,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE FROM "+schema+".DEPOSIT_PRICING_PACKAGE WHERE STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE)) ORDER BY PRICING_PACKAGE_ID DESC";return jdbc.query(sql,Map.of(),(r,n)->new PricingPackage(r.getLong(1),r.getString(2),r.getString(3),date(r.getDate(4)),date(r.getDate(5)),r.getString(6)));}
    public List<PricingPackageBenefit> packageBenefits(){String sql="SELECT B.PACKAGE_BENEFIT_ID,B.PRICING_PACKAGE_ID,B.BENEFIT_TYPE_CODE,B.TARGET_CODE,B.BENEFIT_VALUE,B.MAX_BENEFIT_AMOUNT FROM "+schema+".DEPOSIT_PRICING_PACKAGE_BENEFIT B JOIN "+schema+".DEPOSIT_PRICING_PACKAGE P ON P.PRICING_PACKAGE_ID=B.PRICING_PACKAGE_ID WHERE P.STATUS_CODE='ACTIVE' ORDER BY B.PRICING_PACKAGE_ID,B.PACKAGE_BENEFIT_ID";return jdbc.query(sql,Map.of(),(r,n)->new PricingPackageBenefit(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getBigDecimal(5),r.getBigDecimal(6)));}
    public boolean activePricingPackage(long id){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_PRICING_PACKAGE WHERE PRICING_PACKAGE_ID=:id AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=TRUNC(SYSDATE) AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=TRUNC(SYSDATE))",Map.of("id",id),Long.class);return n!=null&&n>0;}
    public void insertPackageEnrollment(long id,long partyId,long accountId,long packageId,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT(CUSTOMER_PACKAGE_ENROLLMENT_ID,PARTY_ID,ACCOUNT_ID,PRICING_PACKAGE_ID,VALID_FROM,VALID_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pid,:aid,:pkg,:vf,:vt,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pid",partyId).addValue("aid",accountId).addValue("pkg",packageId).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public List<CustomerPackageEnrollment> packageEnrollments(long accountId){String sql="SELECT CUSTOMER_PACKAGE_ENROLLMENT_ID,PARTY_ID,ACCOUNT_ID,PRICING_PACKAGE_ID,VALID_FROM,VALID_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT WHERE ACCOUNT_ID=:id ORDER BY CUSTOMER_PACKAGE_ENROLLMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new CustomerPackageEnrollment(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getLong(4),date(r.getDate(5)),date(r.getDate(6)),r.getString(7),r.getLong(8)));}

    public boolean taxCalculationBelongsToAccount(long accountId,long calcId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_TAX_CALCULATION WHERE TAX_CALCULATION_ID=:cid AND ACCOUNT_ID=:aid",new MapSqlParameterSource().addValue("cid",calcId).addValue("aid",accountId),Long.class);return n!=null&&n>0;}
    public void insertTaxAdjustment(long id,long calcId,String type,BigDecimal amount,String reason,LocalDate effective,long approval,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_ADJUSTMENT(TAX_ADJUSTMENT_ID,TAX_CALCULATION_ID,ADJUSTMENT_TYPE_CODE,ADJUSTMENT_AMOUNT,REASON_CODE,EFFECTIVE_DATE,APPROVAL_REQUEST_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:cid,:type,:amount,:reason,:ed,:approval,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("cid",calcId).addValue("type",type).addValue("amount",amount).addValue("reason",reason).addValue("ed",Date.valueOf(effective)).addValue("approval",approval).addValue("actor",actor));}
    public List<TaxAdjustment> taxAdjustments(long accountId){String sql="SELECT J.TAX_ADJUSTMENT_ID,J.TAX_CALCULATION_ID,J.ADJUSTMENT_TYPE_CODE,J.ADJUSTMENT_AMOUNT,J.REASON_CODE,J.EFFECTIVE_DATE,J.APPROVAL_REQUEST_ID,A.APPROVAL_STATUS_CODE,J.POSTING_REFERENCE FROM "+schema+".DEPOSIT_TAX_ADJUSTMENT J JOIN "+schema+".DEPOSIT_TAX_CALCULATION C ON C.TAX_CALCULATION_ID=J.TAX_CALCULATION_ID LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=J.APPROVAL_REQUEST_ID WHERE C.ACCOUNT_ID=:id ORDER BY J.TAX_ADJUSTMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxAdjustment(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getString(5),date(r.getDate(6)),r.getObject(7,Long.class),r.getString(8),r.getString(9)));}
    public List<TaxLiability> taxLiabilities(long accountId){String sql="SELECT DISTINCT L.TAX_LIABILITY_ID,L.JURISDICTION_CODE,L.TAX_TYPE_CODE,L.PERIOD_START,L.PERIOD_END,L.LIABILITY_AMOUNT,L.PAID_AMOUNT,L.STATUS_CODE FROM "+schema+".DEPOSIT_TAX_LIABILITY L JOIN "+schema+".DEPOSIT_TAX_RULE R ON R.TAX_TYPE_CODE=L.TAX_TYPE_CODE JOIN "+schema+".DEPOSIT_TAX_CALCULATION C ON C.TAX_RULE_ID=R.TAX_RULE_ID WHERE C.ACCOUNT_ID=:id ORDER BY L.PERIOD_END DESC,L.TAX_LIABILITY_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxLiability(r.getLong(1),r.getString(2),r.getString(3),date(r.getDate(4)),date(r.getDate(5)),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8)));}
    public List<TaxPayment> taxPayments(long accountId){String sql="SELECT DISTINCT P.TAX_PAYMENT_ID,P.TAX_LIABILITY_ID,P.PAYMENT_AMOUNT,P.PAYMENT_DATE,P.PAYMENT_STATUS_CODE,P.PAYMENT_REFERENCE FROM "+schema+".DEPOSIT_TAX_PAYMENT P JOIN "+schema+".DEPOSIT_TAX_LIABILITY L ON L.TAX_LIABILITY_ID=P.TAX_LIABILITY_ID JOIN "+schema+".DEPOSIT_TAX_RULE R ON R.TAX_TYPE_CODE=L.TAX_TYPE_CODE JOIN "+schema+".DEPOSIT_TAX_CALCULATION C ON C.TAX_RULE_ID=R.TAX_RULE_ID WHERE C.ACCOUNT_ID=:id ORDER BY P.TAX_PAYMENT_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxPayment(r.getLong(1),r.getLong(2),r.getBigDecimal(3),date(r.getDate(4)),r.getString(5),r.getString(6)));}
    public List<TaxReconciliation> taxReconciliations(long accountId){String sql="SELECT DISTINCT X.TAX_RECONCILIATION_ID,X.BUSINESS_DATE,X.TAX_TYPE_CODE,X.BOOK_AMOUNT,X.REMITTED_AMOUNT,X.EXTERNAL_AMOUNT,X.DIFFERENCE_AMOUNT,X.STATUS_CODE,X.RESOLUTION_REFERENCE FROM "+schema+".DEPOSIT_TAX_RECONCILIATION X JOIN "+schema+".DEPOSIT_TAX_RULE R ON R.TAX_TYPE_CODE=X.TAX_TYPE_CODE JOIN "+schema+".DEPOSIT_TAX_CALCULATION C ON C.TAX_RULE_ID=R.TAX_RULE_ID WHERE C.ACCOUNT_ID=:id ORDER BY X.BUSINESS_DATE DESC,X.TAX_RECONCILIATION_ID DESC";return jdbc.query(sql,Map.of("id",accountId),(r,n)->new TaxReconciliation(r.getLong(1),date(r.getDate(2)),r.getString(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8),r.getString(9)));}

    public ReserveRequirement reserveRequirement(long accountId,long requirementId){return reserveRequirements(accountId).stream().filter(x->x.reserveRequirementId()==requirementId).findFirst().orElse(null);}
    public void insertReservePosition(long id,long requirementId,LocalDate businessDate,String currency,BigDecimal eligible,BigDecimal required,BigDecimal actual,String status,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_RESERVE_POSITION(RESERVE_POSITION_ID,RESERVE_REQUIREMENT_ID,BUSINESS_DATE,CURRENCY_CODE,ELIGIBLE_BALANCE,REQUIRED_RESERVE_AMOUNT,ACTUAL_RESERVE_AMOUNT,POSITION_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rid,:bd,:cur,:eligible,:required,:actual,:status,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rid",requirementId).addValue("bd",Date.valueOf(businessDate)).addValue("cur",currency).addValue("eligible",eligible).addValue("required",required).addValue("actual",actual).addValue("status",status).addValue("actor",actor));}
    public void insertRegulatoryReport(long id,String type,String regulator,LocalDate start,LocalDate end,long version,String fileRef,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_REGULATORY_REPORT(REGULATORY_REPORT_ID,REPORT_TYPE_CODE,REGULATOR_CODE,PERIOD_START,PERIOD_END,REPORT_VERSION_NO,STATUS_CODE,GENERATED_AT,FILE_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:type,:reg,:ps,:pe,:ver,'VALIDATED',SYSTIMESTAMP,:file,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("type",type).addValue("reg",regulator).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)).addValue("ver",version).addValue("file",fileRef).addValue("actor",actor));}
    public void insertRegulatoryReportItem(long id,long reportId,long accountId,Long productVersion,String measureCode,BigDecimal measureAmount,Long measureCount,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_REGULATORY_REPORT_ITEM(REGULATORY_REPORT_ITEM_ID,REGULATORY_REPORT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,MEASURE_CODE,MEASURE_AMOUNT,MEASURE_COUNT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rid,:aid,:pvid,:code,:amount,:cnt,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rid",reportId).addValue("aid",accountId).addValue("pvid",productVersion,Types.NUMERIC).addValue("code",measureCode).addValue("amount",measureAmount).addValue("cnt",measureCount,Types.NUMERIC).addValue("actor",actor));}

    public void insertFeeRule(long id,long productVersionId,String feeCode,String eventCode,String method,BigDecimal fixed,BigDecimal rate,BigDecimal min,BigDecimal max,long version,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_FEE_RULE(FEE_RULE_ID,PRODUCT_VERSION_ID,FEE_CODE,FEE_EVENT_CODE,CALCULATION_METHOD_CODE,FIXED_AMOUNT,RATE_VALUE,MIN_FEE_AMOUNT,MAX_FEE_AMOUNT,RULE_VERSION_NO,EFFECTIVE_FROM,EFFECTIVE_TO,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:pvid,:code,:event,:method,:fixed,:rate,:min,:max,:ver,:vf,:vt,1,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("pvid",productVersionId).addValue("code",feeCode).addValue("event",eventCode).addValue("method",method).addValue("fixed",fixed).addValue("rate",rate).addValue("min",min).addValue("max",max).addValue("ver",version).addValue("vf",Date.valueOf(from)).addValue("vt",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}
    public void insertFeeTier(long id,long feeRuleId,long tierNo,BigDecimal min,BigDecimal max,BigDecimal amount,BigDecimal rate,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_FEE_TIER(FEE_TIER_ID,FEE_RULE_ID,TIER_NO,MIN_BASE_AMOUNT,MAX_BASE_AMOUNT,FEE_AMOUNT,FEE_RATE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rid,:no,:min,:max,:amount,:rate,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rid",feeRuleId).addValue("no",tierNo).addValue("min",min).addValue("max",max).addValue("amount",amount).addValue("rate",rate).addValue("actor",actor));}
    public FeeRule feeRule(long accountId,long ruleId){return feeRules(accountId).stream().filter(x->x.feeRuleId()==ruleId).findFirst().orElse(null);}
    public List<FeeTier> feeTiersForRule(long ruleId){String sql="SELECT FEE_TIER_ID,FEE_RULE_ID,TIER_NO,MIN_BASE_AMOUNT,MAX_BASE_AMOUNT,FEE_AMOUNT,FEE_RATE FROM "+schema+".DEPOSIT_FEE_TIER WHERE FEE_RULE_ID=:id ORDER BY TIER_NO";return jdbc.query(sql,Map.of("id",ruleId),(r,n)->new FeeTier(r.getLong(1),r.getLong(2),r.getLong(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7)));}
    public void insertFeeAssessment(long id,long accountId,Long transactionId,long feeRuleId,BigDecimal base,BigDecimal calculated,BigDecimal discount,BigDecimal finalAmount,String collectionMethod,String waiver,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_FEE_ASSESSMENT(FEE_ASSESSMENT_ID,ACCOUNT_ID,TRANSACTION_ID,FEE_RULE_ID,BASE_AMOUNT,CALCULATED_FEE_AMOUNT,DISCOUNT_AMOUNT,FINAL_FEE_AMOUNT,ASSESSMENT_STATUS_CODE,COLLECTION_METHOD_CODE,WAIVER_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:tx,:rid,:base,:calc,:disc,:final,'CALCULATED',:method,:waiver,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("tx",transactionId,Types.NUMERIC).addValue("rid",feeRuleId).addValue("base",base).addValue("calc",calculated).addValue("disc",discount).addValue("final",finalAmount).addValue("method",collectionMethod).addValue("waiver",waiver).addValue("actor",actor));}
    public BigDecimal feeRevenue(long accountId,LocalDate start,LocalDate end){String sql="SELECT NVL(SUM(FINAL_FEE_AMOUNT),0) FROM "+schema+".DEPOSIT_FEE_ASSESSMENT WHERE ACCOUNT_ID=:aid AND CREATED_AT>=:ps AND CREATED_AT<:pe+1";return jdbc.queryForObject(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)),BigDecimal.class);}
    public BigDecimal interestExpense(long accountId,LocalDate start,LocalDate end){String sql="SELECT NVL(SUM(PAYMENT_AMOUNT),0) FROM "+schema+".DEPOSIT_PROFIT_PAYMENT WHERE ACCOUNT_ID=:aid AND PAYMENT_DATE BETWEEN :ps AND :pe AND PAYMENT_STATUS_CODE='PAID'";return jdbc.queryForObject(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)),BigDecimal.class);}
    public void insertProfitability(long id,long accountId,Long productVersion,Long partyId,LocalDate start,LocalDate end,BigDecimal avg,BigDecimal interest,BigDecimal fees,BigDecimal other,BigDecimal cost,BigDecimal net,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_PROFITABILITY_SNAPSHOT(PROFITABILITY_SNAPSHOT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,PARTY_ID,PERIOD_START,PERIOD_END,AVERAGE_BALANCE,INTEREST_EXPENSE,FEE_REVENUE,OTHER_REVENUE,DIRECT_COST,NET_MARGIN,CALCULATED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:pvid,:pid,:ps,:pe,:avg,:interest,:fees,:other,:cost,:net,SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("pvid",productVersion,Types.NUMERIC).addValue("pid",partyId,Types.NUMERIC).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)).addValue("avg",avg).addValue("interest",interest).addValue("fees",fees).addValue("other",other).addValue("cost",cost).addValue("net",net).addValue("actor",actor));}

    public BigDecimal taxBookAmount(long accountId,String taxType,LocalDate start,LocalDate end){String sql="SELECT NVL(SUM(C.TAX_AMOUNT),0)+NVL((SELECT SUM(J.ADJUSTMENT_AMOUNT) FROM "+schema+".DEPOSIT_TAX_ADJUSTMENT J JOIN "+schema+".DEPOSIT_TAX_CALCULATION C2 ON C2.TAX_CALCULATION_ID=J.TAX_CALCULATION_ID JOIN "+schema+".DEPOSIT_TAX_RULE R2 ON R2.TAX_RULE_ID=C2.TAX_RULE_ID LEFT JOIN "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=J.APPROVAL_REQUEST_ID WHERE C2.ACCOUNT_ID=:aid AND R2.TAX_TYPE_CODE=:type AND J.EFFECTIVE_DATE BETWEEN :ps AND :pe AND (J.APPROVAL_REQUEST_ID IS NULL OR A.APPROVAL_STATUS_CODE='APPROVED')),0) FROM "+schema+".DEPOSIT_TAX_CALCULATION C JOIN "+schema+".DEPOSIT_TAX_RULE R ON R.TAX_RULE_ID=C.TAX_RULE_ID WHERE C.ACCOUNT_ID=:aid AND R.TAX_TYPE_CODE=:type AND C.CREATED_AT>=:ps AND C.CREATED_AT<:pe+1";return jdbc.queryForObject(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("type",taxType).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)),BigDecimal.class);}
    public void insertTaxLiability(long id,String jurisdiction,String taxType,LocalDate start,LocalDate end,BigDecimal amount,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_LIABILITY(TAX_LIABILITY_ID,JURISDICTION_CODE,TAX_TYPE_CODE,PERIOD_START,PERIOD_END,LIABILITY_AMOUNT,PAID_AMOUNT,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:jur,:type,:ps,:pe,:amount,0,:status,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("jur",jurisdiction).addValue("type",taxType).addValue("ps",Date.valueOf(start)).addValue("pe",Date.valueOf(end)).addValue("amount",amount).addValue("status",amount.signum()==0?"PAID":"OPEN").addValue("actor",actor));}
    public TaxLiability taxLiability(long accountId,long liabilityId){return taxLiabilities(accountId).stream().filter(x->x.taxLiabilityId()==liabilityId).findFirst().orElse(null);}
    public void insertTaxPayment(long id,long liabilityId,BigDecimal amount,LocalDate date,String ref,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_PAYMENT(TAX_PAYMENT_ID,TAX_LIABILITY_ID,PAYMENT_AMOUNT,PAYMENT_DATE,PAYMENT_STATUS_CODE,PAYMENT_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:lid,:amount,:pd,'PAID',:ref,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("lid",liabilityId).addValue("amount",amount).addValue("pd",Date.valueOf(date)).addValue("ref",ref).addValue("actor",actor));}
    public void applyTaxPayment(long liabilityId,BigDecimal amount,String actor){String sql="UPDATE "+schema+".DEPOSIT_TAX_LIABILITY SET PAID_AMOUNT=PAID_AMOUNT+:amount,STATUS_CODE=CASE WHEN PAID_AMOUNT+:amount>=LIABILITY_AMOUNT THEN 'PAID' ELSE 'PARTIALLY_PAID' END,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TAX_LIABILITY_ID=:id AND PAID_AMOUNT+:amount<=LIABILITY_AMOUNT";if(jdbc.update(sql,new MapSqlParameterSource().addValue("amount",amount).addValue("actor",actor).addValue("id",liabilityId))!=1)throw new IllegalArgumentException("مبلغ پرداخت از مانده بدهی بیشتر است.");}
    public BigDecimal taxLiabilityAmount(long accountId,String taxType){return taxLiabilities(accountId).stream().filter(x->taxType.equals(x.taxTypeCode())).map(TaxLiability::liabilityAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}
    public BigDecimal taxPaidAmount(long accountId,String taxType){return taxLiabilities(accountId).stream().filter(x->taxType.equals(x.taxTypeCode())).map(TaxLiability::paidAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}
    public void insertTaxReconciliation(long id,LocalDate businessDate,String taxType,BigDecimal book,BigDecimal remitted,BigDecimal external,BigDecimal diff,String status,String resolution,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_TAX_RECONCILIATION(TAX_RECONCILIATION_ID,BUSINESS_DATE,TAX_TYPE_CODE,BOOK_AMOUNT,REMITTED_AMOUNT,EXTERNAL_AMOUNT,DIFFERENCE_AMOUNT,STATUS_CODE,RESOLUTION_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:bd,:type,:book,:remitted,:external,:diff,:status,:resolution,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("bd",Date.valueOf(businessDate)).addValue("type",taxType).addValue("book",book).addValue("remitted",remitted).addValue("external",external).addValue("diff",diff).addValue("status",status).addValue("resolution",resolution).addValue("actor",actor));}
    public int postTaxAdjustment(long adjustmentId,String postingReference,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_TAX_ADJUSTMENT J SET J.POSTING_REFERENCE=:ref,J.UPDATED_AT=SYSTIMESTAMP,J.UPDATED_BY=:actor,J.RECORD_VERSION=J.RECORD_VERSION+1 WHERE J.TAX_ADJUSTMENT_ID=:id AND J.POSTING_REFERENCE IS NULL AND EXISTS(SELECT 1 FROM "+schema+".DEPOSIT_OPERATION_APPROVAL_REQUEST A WHERE A.APPROVAL_REQUEST_ID=J.APPROVAL_REQUEST_ID AND A.APPROVAL_STATUS_CODE='APPROVED')",new MapSqlParameterSource().addValue("ref",postingReference).addValue("actor",actor).addValue("id",adjustmentId));}

    public record FeeOverrideLock(long id,Long approvalId,String status,long version){}
    public record ApprovalLock(long id,long accountId,String approver,String status,long version){}
    public record PricingOverrideLock(long id,Long approvalId,String status,long version){}
    public record TaxRule(long id,String taxType,BigDecimal rate,BigDecimal minTaxable){}
    public record IdemRow(String key,Long accountId,String operation,String payloadHash,String status,String resultReference){}
    private static String id(String v){if(v==null||!v.matches("[A-Za-z0-9_]+"))throw new IllegalArgumentException("Oracle identifier نامعتبر است: "+v);return v.toUpperCase(Locale.ROOT);}
    private static LocalDate date(Date d){return d==null?null:d.toLocalDate();}
    private static OffsetDateTime offset(Timestamp t){return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}
    private static Timestamp ts(OffsetDateTime v){return v==null?null:Timestamp.from(v.toInstant());}
}
