PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_POSTING_REFERENCE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_REFERENCE]: Table name FEE_POSTING_REFERENCE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_POSTING_REFERENCE.columns.AMOUNT]: Document type NUMBER(23,4) differs from database metadata for AMOUNT. Metadata frequencies: NUMBER(15,0) [121], NUMBER [37], NUMBER(20,5) [25], NUMBER(18,0) [23], NUMBER(23,5) [9], NUMBER(12,0) [7], NUMBER(20,0) [6], NUMBER(25,0) [3], NUMBER(24,5) [2], VARCHAR2(21) [2], NUMBER(10,0) [1], NUMBER(14,0) [1], NUMBER(17,0) [1], NUMBER(19,0) [1], NUMBER(3,0) [1], NUMBER(6,0) [1], VARCHAR2(15) [1], VARCHAR2(16) [1], VARCHAR2(28) [1], VARCHAR2(8) [1]. Total occurrences: 245.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_CRACC]: Referenced table FEE_DEMO_ACCOUNT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_CRACC]: Referenced table FEE_DEMO_ACCOUNT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_DBACC]: Referenced table FEE_DEMO_ACCOUNT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_DBACC]: Referenced table FEE_DEMO_ACCOUNT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_REV]: Referenced table FEE_REVERSAL does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_REV]: Referenced table FEE_REVERSAL appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_REFERENCE.foreignKeys.FK_FEE_POST_REF_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_POSTING_REFERENCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مرجع ثبت حسابداری کارمزد
-- Integration evidence/preview ثبت حسابداری Fee یا Reversal؛ Fee مالک Ledger Entry نیست.
CREATE TABLE FEE.FEE_POSTING_REFERENCE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  POSTING_REFERENCE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_POSTING_REFERENCE.NEXTVAL NOT NULL,
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  FEE_REVERSAL_ID NUMBER(19,0),
  /*   0*/  POSTING_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  POSTING_MODALITY_CODE VARCHAR2(50 CHAR),
  /*   0*/  ACCOUNTING_PROFILE_CODE VARCHAR2(80 CHAR),
  /*   0*/  DEBIT_DEMO_ACCOUNT_ID NUMBER(19,0),
  /*   0*/  CREDIT_DEMO_ACCOUNT_ID NUMBER(19,0),
  /* 245*/  AMOUNT NUMBER(23,4) NOT NULL, -- W:TYPE
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR) NOT NULL,
  /*   0*/  ACCOUNTING_INSTRUCTION_REF VARCHAR2(200 CHAR),
  /*   0*/  POSTING_REF VARCHAR2(200 CHAR),
  /*   0*/  JOURNAL_REF VARCHAR2(200 CHAR),
  /*   0*/  LEDGER_TRANSACTION_REF VARCHAR2(200 CHAR),
  /*   0*/  POSTING_STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
  /*   2*/  REQUESTED_AT TIMESTAMP(6),
  /*   1*/  COMPLETED_AT TIMESTAMP(6),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT PK_FEE_POSTING_REFERENCE PRIMARY KEY (POSTING_REFERENCE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_POSTING_REFERENCE_POSTING_REFERENCE_ID ON FEE.FEE_POSTING_REFERENCE(POSTING_REFERENCE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

CREATE INDEX FEE.IX_FEE_POST_REF_STATUS ON FEE.FEE_POSTING_REFERENCE(POSTING_STATUS_CODE,REQUESTED_AT)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_POSTING_REFERENCE_FEE_TRANSACTION_ID ON FEE.FEE_POSTING_REFERENCE(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_POSTING_REFERENCE_FEE_REVERSAL_ID ON FEE.FEE_POSTING_REFERENCE(FEE_REVERSAL_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_POSTING_REFERENCE_DEBIT_DEMO_ACCOUNT_ID ON FEE.FEE_POSTING_REFERENCE(DEBIT_DEMO_ACCOUNT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_POSTING_REFERENCE_CREDIT_DEMO_ACCOUNT_ID ON FEE.FEE_POSTING_REFERENCE(CREDIT_DEMO_ACCOUNT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_POSTING_REFERENCE ADD CONSTRAINT FK_FEE_POST_REF_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_POSTING_REFERENCE ADD CONSTRAINT FK_FEE_POST_REF_REV FOREIGN KEY (FEE_REVERSAL_ID) REFERENCES FEE.FEE_REVERSAL(FEE_REVERSAL_ID) ENABLE;

ALTER TABLE FEE.FEE_POSTING_REFERENCE ADD CONSTRAINT FK_FEE_POST_REF_DBACC FOREIGN KEY (DEBIT_DEMO_ACCOUNT_ID) REFERENCES FEE.FEE_DEMO_ACCOUNT(DEMO_ACCOUNT_ID) ENABLE;

ALTER TABLE FEE.FEE_POSTING_REFERENCE ADD CONSTRAINT FK_FEE_POST_REF_CRACC FOREIGN KEY (CREDIT_DEMO_ACCOUNT_ID) REFERENCES FEE.FEE_DEMO_ACCOUNT(DEMO_ACCOUNT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_POSTING_REFERENCE IS 'مرجع ثبت حسابداری کارمزد';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.POSTING_REFERENCE_ID IS 'شناسه مرجع ثبت - ستون فیزیکی Oracle POSTING_REFERENCE_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.FEE_REVERSAL_ID IS 'شناسه برگشت کارمزد - ستون فیزیکی Oracle FEE_REVERSAL_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.POSTING_PURPOSE_CODE IS 'هدف ثبت - ستون فیزیکی Oracle POSTING_PURPOSE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.POSTING_MODALITY_CODE IS 'مدالیتی ثبت - ستون فیزیکی Oracle POSTING_MODALITY_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.ACCOUNTING_PROFILE_CODE IS 'پروفایل حسابداری - ستون فیزیکی Oracle ACCOUNTING_PROFILE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.DEBIT_DEMO_ACCOUNT_ID IS 'شناسه حساب آزمایشی بدهکار - ستون فیزیکی Oracle DEBIT_DEMO_ACCOUNT_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.CREDIT_DEMO_ACCOUNT_ID IS 'شناسه حساب آزمایشی بستانکار - ستون فیزیکی Oracle CREDIT_DEMO_ACCOUNT_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.AMOUNT IS 'مبلغ ثبت - ستون فیزیکی Oracle AMOUNT.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.CURRENCY_CODE IS 'ارز ثبت - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.ACCOUNTING_INSTRUCTION_REF IS 'مرجع دستور حسابداری - ستون فیزیکی Oracle ACCOUNTING_INSTRUCTION_REF.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.POSTING_REF IS 'مرجع Posting - ستون فیزیکی Oracle POSTING_REF.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.JOURNAL_REF IS 'مرجع سند روزنامه - ستون فیزیکی Oracle JOURNAL_REF.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.LEDGER_TRANSACTION_REF IS 'مرجع تراکنش دفترکل - ستون فیزیکی Oracle LEDGER_TRANSACTION_REF.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.POSTING_STATUS_CODE IS 'وضعیت ثبت - ستون فیزیکی Oracle POSTING_STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.REQUESTED_AT IS 'زمان درخواست ثبت - ستون فیزیکی Oracle REQUESTED_AT.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.COMPLETED_AT IS 'زمان تکمیل ثبت - ستون فیزیکی Oracle COMPLETED_AT.';

COMMENT ON COLUMN FEE.FEE_POSTING_REFERENCE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 18
Primary Keys : 1
Unique Keys  : 0
Checks       : 0
Foreign Keys : 4
Physical FKs : 4
Logical FKs  : 0
Indexes      : 5
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:13 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/