PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_DEFINITION_VERSION]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DEFINITION_VERSION]: Table name FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_DEFINITION_VERSION.columns.VERSION_NO]: Document type VARCHAR2(30 CHAR) differs from database metadata for VERSION_NO. Metadata frequencies: NUMBER(10,0) [52], NUMBER(6,0) [1]. Total occurrences: 53.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_DEF]: Referenced table FEE_DEFINITION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_DEF]: Referenced table FEE_DEFINITION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_POLICY]: Referenced table FEE_POLICY_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_POLICY]: Referenced table FEE_POLICY_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_REG]: Referenced table FEE_REGULATORY_SOURCE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DEFINITION_VERSION.foreignKeys.FK_FEE_DEF_VER_REG]: Referenced table FEE_REGULATORY_SOURCE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_DEFINITION_VERSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: نسخه تعریف کارمزد
-- نسخه اثرگذار یک Fee Definition در یک Policy Version شامل نگاشت مقرراتی، Fee Plan و شرایط پایه.
CREATE TABLE FEE.FEE_DEFINITION_VERSION -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_DEFINITION_VERSION.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  POLICY_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  REGULATORY_SOURCE_ID NUMBER(19,0),
  /*   0*/  REGULATORY_TARIFF_CODE VARCHAR2(80 CHAR),
  /*  53*/  VERSION_NO VARCHAR2(30 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  VERSION_TYPE_CODE VARCHAR2(20 CHAR) DEFAULT 'MAJOR' NOT NULL,
  /*  16*/  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'DRAFT' NOT NULL,
  /*   0*/  FEE_PLAN_NAME VARCHAR2(250 CHAR),
  /*   0*/  FEE_PLAN_TYPE_CODE VARCHAR2(30 CHAR),
  /*   0*/  DEFAULT_BEARER_TYPE_CODE VARCHAR2(30 CHAR),
  /*   0*/  DEFAULT_DEBIT_CREDIT_CODE VARCHAR2(10 CHAR),
  /*   0*/  DEFAULT_DIRECTION_CODE VARCHAR2(20 CHAR),
  /*   0*/  FEE_REASON VARCHAR2(2000 CHAR),
  /*   6*/  EFFECTIVE_FROM DATE NOT NULL,
  /*   6*/  EFFECTIVE_TO DATE,
  /*   3*/  APPROVED_AT TIMESTAMP(6),
  /*   4*/  APPROVED_BY VARCHAR2(100 CHAR),
  /*   0*/  ACTIVATED_AT TIMESTAMP(6),
  /*   0*/  ACTIVATED_BY VARCHAR2(100 CHAR),
  /*   0*/  CONFIG_HASH VARCHAR2(128 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_DEFINITION_VERSION PRIMARY KEY (FEE_DEFINITION_VERSION_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_DEFINITION_VERSION_FEE_DEFINITION_VERSION_ID ON FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_DEFINITION_VERSION ADD CONSTRAINT CK_FEE_DEF_VER_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_DEFINITION_VERSION ADD CONSTRAINT UK_FEE_DEF_VERSION UNIQUE(FEE_DEFINITION_ID,VERSION_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_DEF_VERSION ON FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_ID,VERSION_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_DEF_VER_ACTIVE ON FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_ID,STATUS_CODE,EFFECTIVE_FROM)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DEFINITION_VERSION_FEE_DEFINITION_ID ON FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DEFINITION_VERSION_POLICY_VERSION_ID ON FEE.FEE_DEFINITION_VERSION(POLICY_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DEFINITION_VERSION_REGULATORY_SOURCE_ID ON FEE.FEE_DEFINITION_VERSION(REGULATORY_SOURCE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_DEFINITION_VERSION ADD CONSTRAINT FK_FEE_DEF_VER_DEF FOREIGN KEY (FEE_DEFINITION_ID) REFERENCES FEE.FEE_DEFINITION(FEE_DEFINITION_ID) ENABLE;

ALTER TABLE FEE.FEE_DEFINITION_VERSION ADD CONSTRAINT FK_FEE_DEF_VER_POLICY FOREIGN KEY (POLICY_VERSION_ID) REFERENCES FEE.FEE_POLICY_VERSION(POLICY_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_DEFINITION_VERSION ADD CONSTRAINT FK_FEE_DEF_VER_REG FOREIGN KEY (REGULATORY_SOURCE_ID) REFERENCES FEE.FEE_REGULATORY_SOURCE(REGULATORY_SOURCE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_DEFINITION_VERSION IS 'نسخه تعریف کارمزد';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.FEE_DEFINITION_ID IS 'شناسه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_ID.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.POLICY_VERSION_ID IS 'شناسه نسخه سیاست - ستون فیزیکی Oracle POLICY_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.REGULATORY_SOURCE_ID IS 'شناسه منبع مقرراتی - ستون فیزیکی Oracle REGULATORY_SOURCE_ID.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.REGULATORY_TARIFF_CODE IS 'کد ردیف تعرفه مقرراتی - ستون فیزیکی Oracle REGULATORY_TARIFF_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.VERSION_NO IS 'شماره نسخه تعریف - ستون فیزیکی Oracle VERSION_NO.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.VERSION_TYPE_CODE IS 'نوع نسخه تعریف - ستون فیزیکی Oracle VERSION_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.STATUS_CODE IS 'وضعیت چرخه عمر - ستون فیزیکی Oracle STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.FEE_PLAN_NAME IS 'نام طرح کارمزد - ستون فیزیکی Oracle FEE_PLAN_NAME.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.FEE_PLAN_TYPE_CODE IS 'نوع طرح کارمزد - ستون فیزیکی Oracle FEE_PLAN_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.DEFAULT_BEARER_TYPE_CODE IS 'نوع پیش‌فرض تحمل‌کننده کارمزد - ستون فیزیکی Oracle DEFAULT_BEARER_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.DEFAULT_DEBIT_CREDIT_CODE IS 'جهت پیش‌فرض بدهکار یا بستانکار - ستون فیزیکی Oracle DEFAULT_DEBIT_CREDIT_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.DEFAULT_DIRECTION_CODE IS 'جهت پیش‌فرض تعدیل - ستون فیزیکی Oracle DEFAULT_DIRECTION_CODE.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.FEE_REASON IS 'علت یا شرح کارمزد - ستون فیزیکی Oracle FEE_REASON.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.APPROVED_AT IS 'زمان تأیید - ستون فیزیکی Oracle APPROVED_AT.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.APPROVED_BY IS 'تأییدکننده - ستون فیزیکی Oracle APPROVED_BY.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.ACTIVATED_AT IS 'زمان فعال‌سازی - ستون فیزیکی Oracle ACTIVATED_AT.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.ACTIVATED_BY IS 'فعال‌کننده - ستون فیزیکی Oracle ACTIVATED_BY.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.CONFIG_HASH IS 'هش تنظیمات نسخه - ستون فیزیکی Oracle CONFIG_HASH.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_DEFINITION_VERSION.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 26
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 3
Physical FKs : 3
Logical FKs  : 0
Indexes      : 4
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:02 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/