PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_POSTING_RULE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_RULE]: Table name FEE_POSTING_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POSTING_RULE.foreignKeys.FK_FEE_POST_RULE_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POSTING_RULE.foreignKeys.FK_FEE_POST_RULE_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_POSTING_RULE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: قاعده ثبت حسابداری کارمزد
-- پیاده‌سازی Fee Posting Modality برای ثبت فوری، پایان روز، تجمیعی یا Deferred بدون مالکیت دفترکل.
CREATE TABLE FEE.FEE_POSTING_RULE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  POSTING_RULE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_POSTING_RULE.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  RULE_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   0*/  POSTING_MODALITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  POSTING_PURPOSE_CODE VARCHAR2(50 CHAR),
  /*   0*/  ACCOUNTING_PROFILE_CODE VARCHAR2(80 CHAR),
  /*   0*/  DEBIT_ACCOUNT_ROLE_CODE VARCHAR2(50 CHAR),
  /*   0*/  CREDIT_ACCOUNT_ROLE_CODE VARCHAR2(50 CHAR),
  /*   0*/  NARRATIVE_TEMPLATE VARCHAR2(1000 CHAR),
  /*   0*/  AGGREGATION_KEY_CODE VARCHAR2(80 CHAR),
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_POSTING_RULE PRIMARY KEY (POSTING_RULE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_POSTING_RULE_POSTING_RULE_ID ON FEE.FEE_POSTING_RULE(POSTING_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_POSTING_RULE ADD CONSTRAINT CK_FEE_POST_RULE_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_POSTING_RULE ADD CONSTRAINT UK_FEE_POST_RULE_CODE UNIQUE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_POST_RULE_CODE ON FEE.FEE_POSTING_RULE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_POSTING_RULE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_POSTING_RULE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_POSTING_RULE ADD CONSTRAINT FK_FEE_POST_RULE_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_POSTING_RULE IS 'قاعده ثبت حسابداری کارمزد';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.POSTING_RULE_ID IS 'شناسه قاعده ثبت - ستون فیزیکی Oracle POSTING_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.RULE_CODE IS 'کد قاعده ثبت - ستون فیزیکی Oracle RULE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.POSTING_MODALITY_TYPE_CODE IS 'نوع مدالیتی ثبت - ستون فیزیکی Oracle POSTING_MODALITY_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.POSTING_PURPOSE_CODE IS 'هدف ثبت - ستون فیزیکی Oracle POSTING_PURPOSE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.ACCOUNTING_PROFILE_CODE IS 'کد پروفایل حسابداری - ستون فیزیکی Oracle ACCOUNTING_PROFILE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.DEBIT_ACCOUNT_ROLE_CODE IS 'نقش حساب بدهکار - ستون فیزیکی Oracle DEBIT_ACCOUNT_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.CREDIT_ACCOUNT_ROLE_CODE IS 'نقش حساب بستانکار - ستون فیزیکی Oracle CREDIT_ACCOUNT_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.NARRATIVE_TEMPLATE IS 'الگوی شرح سند - ستون فیزیکی Oracle NARRATIVE_TEMPLATE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.AGGREGATION_KEY_CODE IS 'کلید تجمیع ثبت - ستون فیزیکی Oracle AGGREGATION_KEY_CODE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_POSTING_RULE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 18
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 1
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:07 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/