PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ARRANGEMENT_ACCOUNT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_ACCOUNT]: Table name FEE_ARRANGEMENT_ACCOUNT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_ACCOUNT.foreignKeys.FK_FEE_ARR_ACC_ACCOUNT]: Referenced table FEE_DEMO_ACCOUNT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_ACCOUNT.foreignKeys.FK_FEE_ARR_ACC_ACCOUNT]: Referenced table FEE_DEMO_ACCOUNT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_ACCOUNT.foreignKeys.FK_FEE_ARR_ACC_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_ACCOUNT.foreignKeys.FK_FEE_ARR_ACC_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ARRANGEMENT_ACCOUNT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: حساب مرتبط با ترتیب کارمزد
-- ارتباط Fee Arrangement با حساب برداشت، بستانکار، برگشت یا تسویه بدون مالکیت Account؛ هم‌راستا با BIAN Fee Arrangement Account.
CREATE TABLE FEE.FEE_ARRANGEMENT_ACCOUNT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  ARRANGEMENT_ACCOUNT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ARRANGEMENT_ACCOUNT.NEXTVAL NOT NULL,
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0) NOT NULL,
  /*   0*/  DEMO_ACCOUNT_ID NUMBER(19,0) NOT NULL,
  /*   0*/  ACCOUNT_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  IS_PRIMARY_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ARRANGEMENT_ACCOUNT PRIMARY KEY (ARRANGEMENT_ACCOUNT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ARRANGEMENT_ACCOUNT_ARRANGEMENT_ACCOUNT_ID ON FEE.FEE_ARRANGEMENT_ACCOUNT(ARRANGEMENT_ACCOUNT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_ACCOUNT ADD CONSTRAINT CK_FEE_ARR_ACC_PRIMARY CHECK(IS_PRIMARY_FLAG IN ('Y','N')) ENABLE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_ACCOUNT_FEE_ARRANGEMENT_ID ON FEE.FEE_ARRANGEMENT_ACCOUNT(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_ACCOUNT_DEMO_ACCOUNT_ID ON FEE.FEE_ARRANGEMENT_ACCOUNT(DEMO_ACCOUNT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_ACCOUNT ADD CONSTRAINT FK_FEE_ARR_ACC_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_ACCOUNT ADD CONSTRAINT FK_FEE_ARR_ACC_ACCOUNT FOREIGN KEY (DEMO_ACCOUNT_ID) REFERENCES FEE.FEE_DEMO_ACCOUNT(DEMO_ACCOUNT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ARRANGEMENT_ACCOUNT IS 'حساب مرتبط با ترتیب کارمزد';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.ARRANGEMENT_ACCOUNT_ID IS 'شناسه حساب ترتیب - ستون فیزیکی Oracle ARRANGEMENT_ACCOUNT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.DEMO_ACCOUNT_ID IS 'شناسه حساب آزمایشی - ستون فیزیکی Oracle DEMO_ACCOUNT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.ACCOUNT_ROLE_CODE IS 'نقش حساب کارمزد - ستون فیزیکی Oracle ACCOUNT_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.IS_PRIMARY_FLAG IS 'حساب اصلی نقش است - ستون فیزیکی Oracle IS_PRIMARY_FLAG.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_ACCOUNT.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 13
Primary Keys : 1
Unique Keys  : 0
Checks       : 1
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:09 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/