PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_REGULATORY_DISCOUNT_LIMIT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REGULATORY_DISCOUNT_LIMIT]: Table name FEE_REGULATORY_DISCOUNT_LIMIT appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_REGULATORY_DISCOUNT_LIMIT.columns.SEGMENT_CODE]: Document type VARCHAR2(80 CHAR) differs from database metadata for SEGMENT_CODE. Metadata frequencies: VARCHAR2(50) [1]. Total occurrences: 1.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_REGULATORY_DISCOUNT_LIMIT.foreignKeys.FK_FEE_REG_DISC_FEATURE]: Referenced table FEE_FEATURE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REGULATORY_DISCOUNT_LIMIT.foreignKeys.FK_FEE_REG_DISC_FEATURE]: Referenced table FEE_FEATURE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_REGULATORY_DISCOUNT_LIMIT.foreignKeys.FK_FEE_REG_DISC_SOURCE]: Referenced table FEE_REGULATORY_SOURCE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REGULATORY_DISCOUNT_LIMIT.foreignKeys.FK_FEE_REG_DISC_SOURCE]: Referenced table FEE_REGULATORY_SOURCE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_REGULATORY_DISCOUNT_LIMIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: سقف مقرراتی تخفیف کارمزد
-- حداکثر تخفیف مجاز بر اساس منبع مقرراتی، گروه مشتری/نوع طرف و در صورت نیاز Fee Feature.
CREATE TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  REG_DISCOUNT_LIMIT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_REGULATORY_DISCOUNT_LIMIT.NEXTVAL NOT NULL,
  /*   0*/  REGULATORY_SOURCE_ID NUMBER(19,0) NOT NULL,
  /*   0*/  FEE_FEATURE_ID NUMBER(19,0),
  /*   1*/  SEGMENT_CODE VARCHAR2(80 CHAR) NOT NULL, -- W:TYPE
  /*   5*/  PARTY_TYPE_CODE VARCHAR2(30 CHAR),
  /*   0*/  MAX_DISCOUNT_RATE NUMBER(18,10) NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE NOT NULL,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_REGULATORY_DISCOUNT_LIMIT PRIMARY KEY (REG_DISCOUNT_LIMIT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_REGULATORY_DISCOUNT_LIMIT_REG_DISCOUNT_LIMIT_ID ON FEE.FEE_REGULATORY_DISCOUNT_LIMIT(REG_DISCOUNT_LIMIT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT ADD CONSTRAINT CK_FEE_REG_DISC_RATE CHECK(MAX_DISCOUNT_RATE >= 0 AND MAX_DISCOUNT_RATE <= 1) ENABLE;

ALTER TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT ADD CONSTRAINT CK_FEE_REG_DISC_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

CREATE INDEX FEE.IX_FEE_REG_DISC_LOOKUP ON FEE.FEE_REGULATORY_DISCOUNT_LIMIT(REGULATORY_SOURCE_ID,SEGMENT_CODE,PARTY_TYPE_CODE,EFFECTIVE_FROM)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_REGULATORY_DISCOUNT_LIMIT_REGULATORY_SOURCE_ID ON FEE.FEE_REGULATORY_DISCOUNT_LIMIT(REGULATORY_SOURCE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_REGULATORY_DISCOUNT_LIMIT_FEE_FEATURE_ID ON FEE.FEE_REGULATORY_DISCOUNT_LIMIT(FEE_FEATURE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT ADD CONSTRAINT FK_FEE_REG_DISC_SOURCE FOREIGN KEY (REGULATORY_SOURCE_ID) REFERENCES FEE.FEE_REGULATORY_SOURCE(REGULATORY_SOURCE_ID) ENABLE;

ALTER TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT ADD CONSTRAINT FK_FEE_REG_DISC_FEATURE FOREIGN KEY (FEE_FEATURE_ID) REFERENCES FEE.FEE_FEATURE(FEE_FEATURE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_REGULATORY_DISCOUNT_LIMIT IS 'سقف مقرراتی تخفیف کارمزد';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.REG_DISCOUNT_LIMIT_ID IS 'شناسه سقف تخفیف - ستون فیزیکی Oracle REG_DISCOUNT_LIMIT_ID.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.REGULATORY_SOURCE_ID IS 'شناسه منبع مقرراتی - ستون فیزیکی Oracle REGULATORY_SOURCE_ID.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.FEE_FEATURE_ID IS 'شناسه ویژگی کارمزد - ستون فیزیکی Oracle FEE_FEATURE_ID.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.SEGMENT_CODE IS 'کد بخش یا گروه مشمول - ستون فیزیکی Oracle SEGMENT_CODE.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.PARTY_TYPE_CODE IS 'نوع طرف مشمول - ستون فیزیکی Oracle PARTY_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.MAX_DISCOUNT_RATE IS 'حداکثر نرخ تخفیف - ستون فیزیکی Oracle MAX_DISCOUNT_RATE.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.DESCRIPTION IS 'شرح محدودیت - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_REGULATORY_DISCOUNT_LIMIT.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 14
Primary Keys : 1
Unique Keys  : 0
Checks       : 2
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 3
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:01 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/