PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_APPLIED_ADJUSTMENT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_APPLIED_ADJUSTMENT]: Table name FEE_APPLIED_ADJUSTMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_APPLIED_ADJUSTMENT.columns.APPROVAL_REF]: Document type VARCHAR2(200 CHAR) differs from database metadata for APPROVAL_REF. Metadata frequencies: VARCHAR2(100) [3]. Total occurrences: 3.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_APPLIED_ADJUSTMENT.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_APPLIED_ADJUSTMENT.foreignKeys.FK_FEE_APPLIED_ADJ_POLICY]: Referenced table FEE_ADJUSTMENT_POLICY does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_APPLIED_ADJUSTMENT.foreignKeys.FK_FEE_APPLIED_ADJ_POLICY]: Referenced table FEE_ADJUSTMENT_POLICY appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_APPLIED_ADJUSTMENT.foreignKeys.FK_FEE_APPLIED_ADJ_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_APPLIED_ADJUSTMENT.foreignKeys.FK_FEE_APPLIED_ADJ_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_APPLIED_ADJUSTMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: تعدیل اعمال‌شده کارمزد
-- Snapshot هر Discount/Waiver/Override تعدیلی که واقعاً روی Fee Transaction اعمال شده است.
CREATE TABLE FEE.FEE_APPLIED_ADJUSTMENT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  APPLIED_ADJUSTMENT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_APPLIED_ADJUSTMENT.NEXTVAL NOT NULL,
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  ADJUSTMENT_POLICY_ID NUMBER(19,0),
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  ADJUSTMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  BASE_AMOUNT NUMBER(23,4),
  /*   0*/  PERCENT_VALUE NUMBER(18,10),
  /*   0*/  ADJUSTMENT_AMOUNT NUMBER(23,4) NOT NULL,
  /*   0*/  RESULT_AMOUNT NUMBER(23,4) NOT NULL,
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR) NOT NULL,
  /*   3*/  APPROVAL_REF VARCHAR2(200 CHAR), -- W:TYPE
  /*   0*/  APPLIED_AT TIMESTAMP(6) NOT NULL,
CONSTRAINT PK_FEE_APPLIED_ADJUSTMENT PRIMARY KEY (APPLIED_ADJUSTMENT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_APPLIED_ADJUSTMENT_APPLIED_ADJUSTMENT_ID ON FEE.FEE_APPLIED_ADJUSTMENT(APPLIED_ADJUSTMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_APPLIED_ADJUSTMENT ADD CONSTRAINT UK_FEE_APPLIED_ADJ_SEQ UNIQUE(FEE_TRANSACTION_ID,SEQUENCE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_APPLIED_ADJ_SEQ ON FEE.FEE_APPLIED_ADJUSTMENT(FEE_TRANSACTION_ID,SEQUENCE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_APPLIED_ADJUSTMENT_FEE_TRANSACTION_ID ON FEE.FEE_APPLIED_ADJUSTMENT(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_APPLIED_ADJUSTMENT_ADJUSTMENT_POLICY_ID ON FEE.FEE_APPLIED_ADJUSTMENT(ADJUSTMENT_POLICY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_APPLIED_ADJUSTMENT ADD CONSTRAINT FK_FEE_APPLIED_ADJ_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_APPLIED_ADJUSTMENT ADD CONSTRAINT FK_FEE_APPLIED_ADJ_POLICY FOREIGN KEY (ADJUSTMENT_POLICY_ID) REFERENCES FEE.FEE_ADJUSTMENT_POLICY(ADJUSTMENT_POLICY_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_APPLIED_ADJUSTMENT IS 'تعدیل اعمال‌شده کارمزد';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.APPLIED_ADJUSTMENT_ID IS 'شناسه تعدیل اعمال‌شده - ستون فیزیکی Oracle APPLIED_ADJUSTMENT_ID.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.ADJUSTMENT_POLICY_ID IS 'شناسه سیاست تعدیل - ستون فیزیکی Oracle ADJUSTMENT_POLICY_ID.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.SEQUENCE_NO IS 'ترتیب اعمال - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.ADJUSTMENT_TYPE_CODE IS 'نوع تعدیل اعمال‌شده - ستون فیزیکی Oracle ADJUSTMENT_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.BASE_AMOUNT IS 'مبلغ مبنای تعدیل - ستون فیزیکی Oracle BASE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.PERCENT_VALUE IS 'نرخ تعدیل اعمال‌شده - ستون فیزیکی Oracle PERCENT_VALUE.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.ADJUSTMENT_AMOUNT IS 'مبلغ تعدیل - ستون فیزیکی Oracle ADJUSTMENT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.RESULT_AMOUNT IS 'مبلغ پس از تعدیل - ستون فیزیکی Oracle RESULT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.CURRENCY_CODE IS 'ارز تعدیل - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.APPROVAL_REF IS 'مرجع تأیید - ستون فیزیکی Oracle APPROVAL_REF.';

COMMENT ON COLUMN FEE.FEE_APPLIED_ADJUSTMENT.APPLIED_AT IS 'زمان اعمال تعدیل - ستون فیزیکی Oracle APPLIED_AT.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 12
Primary Keys : 1
Unique Keys  : 1
Checks       : 0
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:11 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/