PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_TRANSACTION_COMPONENT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION_COMPONENT]: Table name FEE_TRANSACTION_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_TRANSACTION_COMPONENT.columns.COMPONENT_TYPE_CODE]: Document type VARCHAR2(50 CHAR) differs from database metadata for COMPONENT_TYPE_CODE. Metadata frequencies: VARCHAR2(30) [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_TRANSACTION_COMPONENT.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION_COMPONENT.foreignKeys.FK_FEE_TX_COMP_DEF]: Referenced table FEE_CHARGE_COMPONENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION_COMPONENT.foreignKeys.FK_FEE_TX_COMP_DEF]: Referenced table FEE_CHARGE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION_COMPONENT.foreignKeys.FK_FEE_TX_COMP_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION_COMPONENT.foreignKeys.FK_FEE_TX_COMP_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_TRANSACTION_COMPONENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: جزء تراکنش کارمزد
-- Breakdown اجرایی مبلغ کارمزد به مؤلفه‌های درآمد، پست، مالیات، تمبر، هزینه بیرونی و غیره.
CREATE TABLE FEE.FEE_TRANSACTION_COMPONENT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  TRANSACTION_COMPONENT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_TRANSACTION_COMPONENT.NEXTVAL NOT NULL,
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  CHARGE_COMPONENT_ID NUMBER(19,0),
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  COMPONENT_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   1*/  COMPONENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  CALCULATED_AMOUNT NUMBER(23,4),
  /*   0*/  APPLIED_AMOUNT NUMBER(23,4) NOT NULL,
  /*   0*/  DISCOUNT_AMOUNT NUMBER(23,4),
  /*   0*/  REFUNDABLE_AMOUNT NUMBER(23,4),
  /*   0*/  REVENUE_AMOUNT NUMBER(23,4),
  /*   0*/  PASS_THROUGH_AMOUNT NUMBER(23,4),
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR) NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
CONSTRAINT PK_FEE_TRANSACTION_COMPONENT PRIMARY KEY (TRANSACTION_COMPONENT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_TRANSACTION_COMPONENT_TRANSACTION_COMPONENT_ID ON FEE.FEE_TRANSACTION_COMPONENT(TRANSACTION_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_TRANSACTION_COMPONENT ADD CONSTRAINT UK_FEE_TX_COMP_SEQ UNIQUE(FEE_TRANSACTION_ID,SEQUENCE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_TX_COMP_SEQ ON FEE.FEE_TRANSACTION_COMPONENT(FEE_TRANSACTION_ID,SEQUENCE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_TRANSACTION_COMPONENT_FEE_TRANSACTION_ID ON FEE.FEE_TRANSACTION_COMPONENT(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TRANSACTION_COMPONENT_CHARGE_COMPONENT_ID ON FEE.FEE_TRANSACTION_COMPONENT(CHARGE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_TRANSACTION_COMPONENT ADD CONSTRAINT FK_FEE_TX_COMP_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_TRANSACTION_COMPONENT ADD CONSTRAINT FK_FEE_TX_COMP_DEF FOREIGN KEY (CHARGE_COMPONENT_ID) REFERENCES FEE.FEE_CHARGE_COMPONENT(CHARGE_COMPONENT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_TRANSACTION_COMPONENT IS 'جزء تراکنش کارمزد';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.TRANSACTION_COMPONENT_ID IS 'شناسه جزء تراکنش - ستون فیزیکی Oracle TRANSACTION_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.CHARGE_COMPONENT_ID IS 'شناسه مؤلفه تعریف‌شده - ستون فیزیکی Oracle CHARGE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.SEQUENCE_NO IS 'ترتیب جزء - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.COMPONENT_CODE IS 'کد مؤلفه - ستون فیزیکی Oracle COMPONENT_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.COMPONENT_TYPE_CODE IS 'نوع مؤلفه - ستون فیزیکی Oracle COMPONENT_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.CALCULATED_AMOUNT IS 'مبلغ محاسبه‌شده جزء - ستون فیزیکی Oracle CALCULATED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.APPLIED_AMOUNT IS 'مبلغ اعمال‌شده جزء - ستون فیزیکی Oracle APPLIED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.DISCOUNT_AMOUNT IS 'مبلغ تخفیف جزء - ستون فیزیکی Oracle DISCOUNT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.REFUNDABLE_AMOUNT IS 'مبلغ قابل برگشت جزء - ستون فیزیکی Oracle REFUNDABLE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.REVENUE_AMOUNT IS 'مبلغ درآمد بانک - ستون فیزیکی Oracle REVENUE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.PASS_THROUGH_AMOUNT IS 'مبلغ هزینه عبوری - ستون فیزیکی Oracle PASS_THROUGH_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.CURRENCY_CODE IS 'ارز جزء - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION_COMPONENT.DESCRIPTION IS 'شرح جزء - ستون فیزیکی Oracle DESCRIPTION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 14
Primary Keys : 1
Unique Keys  : 1
Checks       : 0
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:11 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/