PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_CHARGE_COMPONENT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_COMPONENT]: Table name FEE_CHARGE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CHARGE_COMPONENT.columns.COMPONENT_TYPE_CODE]: Document type VARCHAR2(50 CHAR) differs from database metadata for COMPONENT_TYPE_CODE. Metadata frequencies: VARCHAR2(30) [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CHARGE_COMPONENT.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CHARGE_COMPONENT.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CHARGE_COMPONENT.foreignKeys.FK_FEE_CHG_COMP_CALC]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_COMPONENT.foreignKeys.FK_FEE_CHG_COMP_CALC]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CHARGE_COMPONENT.foreignKeys.FK_FEE_CHG_COMP_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_COMPONENT.foreignKeys.FK_FEE_CHG_COMP_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_CHARGE_COMPONENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مؤلفه مبلغ کارمزد
-- تفکیک مبلغ نهایی به مؤلفه‌هایی مانند درآمد بانک، هزینه عبوری، مالیات، تمبر، پست و سرویس بیرونی؛ هم‌راستا با IFW ChargeBreakdown.
CREATE TABLE FEE.FEE_CHARGE_COMPONENT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  CHARGE_COMPONENT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_CHARGE_COMPONENT.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0),
  /*   0*/  COMPONENT_CODE VARCHAR2(80 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /* 163*/  NAME_EN VARCHAR2(250 CHAR),
  /*   1*/  COMPONENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL, -- W:TYPE
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  DISCOUNTABLE_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /*   0*/  REFUNDABLE_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /*   0*/  TAXABLE_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   0*/  REVENUE_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /*   0*/  DEFAULT_BEARER_ROLE_CODE VARCHAR2(30 CHAR),
  /*   0*/  POSTING_PROFILE_CODE VARCHAR2(80 CHAR),
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_CHARGE_COMPONENT PRIMARY KEY (CHARGE_COMPONENT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_CHARGE_COMPONENT_CHARGE_COMPONENT_ID ON FEE.FEE_CHARGE_COMPONENT(CHARGE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT CK_FEE_CHG_COMP_DISC CHECK(DISCOUNTABLE_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT CK_FEE_CHG_COMP_REF CHECK(REFUNDABLE_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT CK_FEE_CHG_COMP_TAX CHECK(TAXABLE_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT CK_FEE_CHG_COMP_REV CHECK(REVENUE_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT UK_FEE_CHG_COMP_CODE UNIQUE(FEE_DEFINITION_VERSION_ID,COMPONENT_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_CHG_COMP_CODE ON FEE.FEE_CHARGE_COMPONENT(FEE_DEFINITION_VERSION_ID,COMPONENT_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_CHARGE_COMPONENT_FEE_DEFINITION_VERSION_ID ON FEE.FEE_CHARGE_COMPONENT(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_CHARGE_COMPONENT_CALCULATION_RULE_ID ON FEE.FEE_CHARGE_COMPONENT(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT FK_FEE_CHG_COMP_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_COMPONENT ADD CONSTRAINT FK_FEE_CHG_COMP_CALC FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_CHARGE_COMPONENT IS 'مؤلفه مبلغ کارمزد';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.CHARGE_COMPONENT_ID IS 'شناسه مؤلفه کارمزد - ستون فیزیکی Oracle CHARGE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه مؤلفه - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.COMPONENT_CODE IS 'کد مؤلفه - ستون فیزیکی Oracle COMPONENT_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.NAME_FA IS 'نام فارسی مؤلفه - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.NAME_EN IS 'نام انگلیسی مؤلفه - ستون فیزیکی Oracle NAME_EN.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.COMPONENT_TYPE_CODE IS 'نوع مؤلفه - ستون فیزیکی Oracle COMPONENT_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.SEQUENCE_NO IS 'ترتیب مؤلفه - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.DISCOUNTABLE_FLAG IS 'مشمول تخفیف است - ستون فیزیکی Oracle DISCOUNTABLE_FLAG.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.REFUNDABLE_FLAG IS 'قابل برگشت است - ستون فیزیکی Oracle REFUNDABLE_FLAG.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.TAXABLE_FLAG IS 'مشمول مالیات است - ستون فیزیکی Oracle TAXABLE_FLAG.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.REVENUE_FLAG IS 'درآمد بانک است - ستون فیزیکی Oracle REVENUE_FLAG.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.DEFAULT_BEARER_ROLE_CODE IS 'نقش پیش‌فرض پرداخت‌کننده - ستون فیزیکی Oracle DEFAULT_BEARER_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.POSTING_PROFILE_CODE IS 'پروفایل ثبت مؤلفه - ستون فیزیکی Oracle POSTING_PROFILE_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.DESCRIPTION IS 'شرح مؤلفه - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_CHARGE_COMPONENT.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 20
Primary Keys : 1
Unique Keys  : 1
Checks       : 4
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:05 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/