PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_POLICY_VERSION]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POLICY_VERSION]: Table name FEE_POLICY_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_POLICY_VERSION.columns.VERSION_NO]: Document type VARCHAR2(30 CHAR) differs from database metadata for VERSION_NO. Metadata frequencies: NUMBER(10,0) [52], NUMBER(6,0) [1]. Total occurrences: 53.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_POLICY_VERSION.foreignKeys.FK_FEE_POLICY_VER_SET]: Referenced table FEE_POLICY_SET does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_POLICY_VERSION.foreignKeys.FK_FEE_POLICY_VER_SET]: Referenced table FEE_POLICY_SET appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_POLICY_VERSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: نسخه سیاست کارمزد
-- نسخه اثرگذار مجموعه سیاست، شامل چرخه تصویب/فعال‌سازی و Policy Hash برای بازسازی و ممیزی.
CREATE TABLE FEE.FEE_POLICY_VERSION -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  POLICY_VERSION_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_POLICY_VERSION.NEXTVAL NOT NULL,
  /*   0*/  POLICY_SET_ID NUMBER(19,0) NOT NULL,
  /*  53*/  VERSION_NO VARCHAR2(30 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  VERSION_TYPE_CODE VARCHAR2(20 CHAR) DEFAULT 'MAJOR' NOT NULL,
  /*  16*/  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'DRAFT' NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE NOT NULL,
  /*   6*/  EFFECTIVE_TO DATE,
  /*   3*/  APPROVED_AT TIMESTAMP(6),
  /*   4*/  APPROVED_BY VARCHAR2(100 CHAR),
  /*   0*/  ACTIVATED_AT TIMESTAMP(6),
  /*   0*/  ACTIVATED_BY VARCHAR2(100 CHAR),
  /*   0*/  RETIRED_AT TIMESTAMP(6),
  /*   0*/  POLICY_HASH VARCHAR2(128 CHAR),
  /*   0*/  CHANGE_SUMMARY VARCHAR2(2000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_POLICY_VERSION PRIMARY KEY (POLICY_VERSION_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_POLICY_VERSION_POLICY_VERSION_ID ON FEE.FEE_POLICY_VERSION(POLICY_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_POLICY_VERSION ADD CONSTRAINT CK_FEE_POLICY_VER_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_POLICY_VERSION ADD CONSTRAINT UK_FEE_POLICY_VERSION UNIQUE(POLICY_SET_ID,VERSION_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_POLICY_VERSION ON FEE.FEE_POLICY_VERSION(POLICY_SET_ID,VERSION_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_POLICY_VER_ACTIVE ON FEE.FEE_POLICY_VERSION(POLICY_SET_ID,STATUS_CODE,EFFECTIVE_FROM)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_POLICY_VERSION_POLICY_SET_ID ON FEE.FEE_POLICY_VERSION(POLICY_SET_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_POLICY_VERSION ADD CONSTRAINT FK_FEE_POLICY_VER_SET FOREIGN KEY (POLICY_SET_ID) REFERENCES FEE.FEE_POLICY_SET(POLICY_SET_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_POLICY_VERSION IS 'نسخه سیاست کارمزد';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.POLICY_VERSION_ID IS 'شناسه نسخه سیاست - ستون فیزیکی Oracle POLICY_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.POLICY_SET_ID IS 'شناسه مجموعه سیاست - ستون فیزیکی Oracle POLICY_SET_ID.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.VERSION_NO IS 'شماره نسخه - ستون فیزیکی Oracle VERSION_NO.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.VERSION_TYPE_CODE IS 'نوع نسخه - ستون فیزیکی Oracle VERSION_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.STATUS_CODE IS 'وضعیت چرخه عمر - ستون فیزیکی Oracle STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.APPROVED_AT IS 'زمان تصویب - ستون فیزیکی Oracle APPROVED_AT.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.APPROVED_BY IS 'تصویب‌کننده - ستون فیزیکی Oracle APPROVED_BY.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.ACTIVATED_AT IS 'زمان فعال‌سازی - ستون فیزیکی Oracle ACTIVATED_AT.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.ACTIVATED_BY IS 'فعال‌کننده - ستون فیزیکی Oracle ACTIVATED_BY.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.RETIRED_AT IS 'زمان بازنشستگی - ستون فیزیکی Oracle RETIRED_AT.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.POLICY_HASH IS 'هش نسخه سیاست - ستون فیزیکی Oracle POLICY_HASH.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.CHANGE_SUMMARY IS 'خلاصه تغییرات نسخه - ستون فیزیکی Oracle CHANGE_SUMMARY.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_POLICY_VERSION.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 19
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:00 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/