PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ALLOCATION_POLICY]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ALLOCATION_POLICY]: Table name FEE_ALLOCATION_POLICY appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ALLOCATION_POLICY.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ALLOCATION_POLICY.foreignKeys.FK_FEE_ALLOC_POLICY_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ALLOCATION_POLICY.foreignKeys.FK_FEE_ALLOC_POLICY_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ALLOCATION_POLICY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: سیاست تسهیم کارمزد
-- سیاست تخصیص درآمد/مؤلفه‌های کارمزد بین بانک، عامل، شریک یا ذی‌نفعان دیگر.
CREATE TABLE FEE.FEE_ALLOCATION_POLICY -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  ALLOCATION_POLICY_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ALLOCATION_POLICY.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  POLICY_CODE VARCHAR2(80 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  ALLOCATION_METHOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  RESIDUAL_HANDLING_CODE VARCHAR2(50 CHAR),
  /*   0*/  CURRENCY_MODE_CODE VARCHAR2(50 CHAR),
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ALLOCATION_POLICY PRIMARY KEY (ALLOCATION_POLICY_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ALLOCATION_POLICY_ALLOCATION_POLICY_ID ON FEE.FEE_ALLOCATION_POLICY(ALLOCATION_POLICY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ALLOCATION_POLICY ADD CONSTRAINT CK_FEE_ALLOC_POLICY_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_ALLOCATION_POLICY ADD CONSTRAINT UK_FEE_ALLOC_POLICY UNIQUE(FEE_DEFINITION_VERSION_ID,POLICY_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_ALLOC_POLICY ON FEE.FEE_ALLOCATION_POLICY(FEE_DEFINITION_VERSION_ID,POLICY_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_ALLOCATION_POLICY_FEE_DEFINITION_VERSION_ID ON FEE.FEE_ALLOCATION_POLICY(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ALLOCATION_POLICY ADD CONSTRAINT FK_FEE_ALLOC_POLICY_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ALLOCATION_POLICY IS 'سیاست تسهیم کارمزد';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.ALLOCATION_POLICY_ID IS 'شناسه سیاست تسهیم - ستون فیزیکی Oracle ALLOCATION_POLICY_ID.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.POLICY_CODE IS 'کد سیاست تسهیم - ستون فیزیکی Oracle POLICY_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.NAME_FA IS 'نام فارسی سیاست تسهیم - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.ALLOCATION_METHOD_CODE IS 'روش تسهیم - ستون فیزیکی Oracle ALLOCATION_METHOD_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.RESIDUAL_HANDLING_CODE IS 'روش مدیریت باقیمانده - ستون فیزیکی Oracle RESIDUAL_HANDLING_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.CURRENCY_MODE_CODE IS 'روش تعیین ارز تسهیم - ستون فیزیکی Oracle CURRENCY_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_POLICY.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 16
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 1
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:08 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/