PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_REF_VALUE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REF_VALUE]: Table name FEE_REF_VALUE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_REF_VALUE.foreignKeys.FK_FEE_REF_VALUE_DOMAIN]: Referenced table FEE_REF_DOMAIN does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REF_VALUE.foreignKeys.FK_FEE_REF_VALUE_DOMAIN]: Referenced table FEE_REF_DOMAIN appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_REF_VALUE.foreignKeys.FK_FEE_REF_VALUE_PARENT]: Referenced table FEE_REF_VALUE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_REF_VALUE.foreignKeys.FK_FEE_REF_VALUE_PARENT]: Referenced table FEE_REF_VALUE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_REF_VALUE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مقادیر اطلاعات پایه کارمزد
-- مقادیر هر دامنه اطلاعات پایه شامل کد، عنوان فارسی و انگلیسی و دوره اعتبار.
CREATE TABLE FEE.FEE_REF_VALUE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  VALUE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_REF_VALUE.NEXTVAL NOT NULL,
  /*   0*/  DOMAIN_ID NUMBER(19,0) NOT NULL,
  /*   0*/  PARENT_VALUE_ID NUMBER(19,0),
  /*   0*/  VALUE_CODE VARCHAR2(100 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  /* 163*/  NAME_EN VARCHAR2(200 CHAR),
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 117*/  SORT_ORDER NUMBER(10,0),
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_REF_VALUE PRIMARY KEY (VALUE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_REF_VALUE_VALUE_ID ON FEE.FEE_REF_VALUE(VALUE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_REF_VALUE ADD CONSTRAINT CK_FEE_REF_VALUE_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_REF_VALUE ADD CONSTRAINT CK_FEE_REF_VALUE_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_REF_VALUE ADD CONSTRAINT UK_FEE_REF_VALUE_CODE UNIQUE(DOMAIN_ID,VALUE_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_REF_VALUE_CODE ON FEE.FEE_REF_VALUE(DOMAIN_ID,VALUE_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_REF_VALUE_DOMAIN_ID ON FEE.FEE_REF_VALUE(DOMAIN_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_REF_VALUE_PARENT_VALUE_ID ON FEE.FEE_REF_VALUE(PARENT_VALUE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_REF_VALUE ADD CONSTRAINT FK_FEE_REF_VALUE_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES FEE.FEE_REF_DOMAIN(DOMAIN_ID) ENABLE;

ALTER TABLE FEE.FEE_REF_VALUE ADD CONSTRAINT FK_FEE_REF_VALUE_PARENT FOREIGN KEY (PARENT_VALUE_ID) REFERENCES FEE.FEE_REF_VALUE(VALUE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_REF_VALUE IS 'مقادیر اطلاعات پایه کارمزد';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.VALUE_ID IS 'شناسه مقدار - ستون فیزیکی Oracle VALUE_ID.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.DOMAIN_ID IS 'شناسه دامنه - ستون فیزیکی Oracle DOMAIN_ID.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.PARENT_VALUE_ID IS 'شناسه مقدار والد - ستون فیزیکی Oracle PARENT_VALUE_ID.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.VALUE_CODE IS 'کد مقدار - ستون فیزیکی Oracle VALUE_CODE.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.NAME_FA IS 'عنوان فارسی - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.NAME_EN IS 'عنوان انگلیسی - ستون فیزیکی Oracle NAME_EN.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.DESCRIPTION IS 'شرح مقدار - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.SORT_ORDER IS 'ترتیب نمایش - ستون فیزیکی Oracle SORT_ORDER.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_REF_VALUE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 16
Primary Keys : 1
Unique Keys  : 1
Checks       : 2
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:14 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/