PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_INPUT_DEFINITION]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_INPUT_DEFINITION]: Table name FEE_INPUT_DEFINITION appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_INPUT_DEFINITION.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_INPUT_DEFINITION.foreignKeys.FK_FEE_INPUT_CALC_RULE]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_INPUT_DEFINITION.foreignKeys.FK_FEE_INPUT_CALC_RULE]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_INPUT_DEFINITION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: تعریف ورودی محاسبه کارمزد
-- تعریف ورودی‌های مورد نیاز یک Calculation Rule برای ساخت Dynamic Simulator مانند مبلغ، روز، وثیقه یا تعرفه بیرونی.
CREATE TABLE FEE.FEE_INPUT_DEFINITION -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  INPUT_DEF_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_INPUT_DEFINITION.NEXTVAL NOT NULL,
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0) NOT NULL,
  /*   0*/  INPUT_CODE VARCHAR2(80 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /* 163*/  NAME_EN VARCHAR2(250 CHAR),
  /*   0*/  DATA_TYPE_CODE VARCHAR2(30 CHAR) NOT NULL,
  /*   0*/  UNIT_CODE VARCHAR2(30 CHAR),
  /*   0*/  MANDATORY_FLAG CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /*   0*/  DEFAULT_TEXT_VALUE VARCHAR2(500 CHAR),
  /*   0*/  DEFAULT_NUMBER_VALUE NUMBER(23,4),
  /*   5*/  DISPLAY_ORDER NUMBER(10,0),
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_INPUT_DEFINITION PRIMARY KEY (INPUT_DEF_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_INPUT_DEFINITION_INPUT_DEF_ID ON FEE.FEE_INPUT_DEFINITION(INPUT_DEF_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_INPUT_DEFINITION ADD CONSTRAINT CK_FEE_INPUT_MAND CHECK(MANDATORY_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_INPUT_DEFINITION ADD CONSTRAINT UK_FEE_INPUT_CODE UNIQUE(CALCULATION_RULE_ID,INPUT_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_INPUT_CODE ON FEE.FEE_INPUT_DEFINITION(CALCULATION_RULE_ID,INPUT_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_INPUT_DEFINITION_CALCULATION_RULE_ID ON FEE.FEE_INPUT_DEFINITION(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_INPUT_DEFINITION ADD CONSTRAINT FK_FEE_INPUT_CALC_RULE FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_INPUT_DEFINITION IS 'تعریف ورودی محاسبه کارمزد';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.INPUT_DEF_ID IS 'شناسه تعریف ورودی - ستون فیزیکی Oracle INPUT_DEF_ID.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.INPUT_CODE IS 'کد ورودی - ستون فیزیکی Oracle INPUT_CODE.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.NAME_FA IS 'نام فارسی ورودی - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.NAME_EN IS 'نام انگلیسی ورودی - ستون فیزیکی Oracle NAME_EN.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.DATA_TYPE_CODE IS 'نوع داده ورودی - ستون فیزیکی Oracle DATA_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.UNIT_CODE IS 'واحد ورودی - ستون فیزیکی Oracle UNIT_CODE.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.MANDATORY_FLAG IS 'اجباری است - ستون فیزیکی Oracle MANDATORY_FLAG.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.DEFAULT_TEXT_VALUE IS 'مقدار متنی پیش‌فرض - ستون فیزیکی Oracle DEFAULT_TEXT_VALUE.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.DEFAULT_NUMBER_VALUE IS 'مقدار عددی پیش‌فرض - ستون فیزیکی Oracle DEFAULT_NUMBER_VALUE.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.DISPLAY_ORDER IS 'ترتیب نمایش - ستون فیزیکی Oracle DISPLAY_ORDER.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.DESCRIPTION IS 'شرح ورودی - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_INPUT_DEFINITION.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 17
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 1
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:04 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/