PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ADJUSTMENT_POLICY]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ADJUSTMENT_POLICY]: Table name FEE_ADJUSTMENT_POLICY appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ADJUSTMENT_POLICY.columns.FIXED_AMOUNT]: Document type NUMBER(23,4) differs from database metadata for FIXED_AMOUNT. Metadata frequencies: NUMBER(20,4) [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ADJUSTMENT_POLICY.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ADJUSTMENT_POLICY.columns.PRIORITY_NO]: Document type NUMBER(10,0) differs from database metadata for PRIORITY_NO. Metadata frequencies: NUMBER(6,0) [4], NUMBER(3,0) [1], NUMBER(5,0) [1]. Total occurrences: 6.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_APP]: Referenced table FEE_APPLICABILITY_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_APP]: Referenced table FEE_APPLICABILITY_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_COMPONENT]: Referenced table FEE_CHARGE_COMPONENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_COMPONENT]: Referenced table FEE_CHARGE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_REGLIMIT]: Referenced table FEE_REGULATORY_DISCOUNT_LIMIT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ADJUSTMENT_POLICY.foreignKeys.FK_FEE_ADJ_REGLIMIT]: Referenced table FEE_REGULATORY_DISCOUNT_LIMIT appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ADJUSTMENT_POLICY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: سیاست تخفیف و تعدیل کارمزد
-- تعریف Discount، Waiver، Replace Amount/Rate، Surcharge و Exceptional Fee با کنترل سقف مقرراتی.
CREATE TABLE FEE.FEE_ADJUSTMENT_POLICY -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  ADJUSTMENT_POLICY_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ADJUSTMENT_POLICY.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  APPLICABILITY_RULE_ID NUMBER(19,0),
  /*   0*/  REG_DISCOUNT_LIMIT_ID NUMBER(19,0),
  /*   0*/  CHARGE_COMPONENT_ID NUMBER(19,0),
  /*   0*/  POLICY_CODE VARCHAR2(80 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  ADJUSTMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  PRICING_FEATURE_TYPE_CODE VARCHAR2(50 CHAR),
  /*   6*/  PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL, -- W:TYPE
  /*   0*/  PERCENT_VALUE NUMBER(18,10),
  /*   1*/  FIXED_AMOUNT NUMBER(23,4), -- W:TYPE
  /*   0*/  REPLACEMENT_AMOUNT NUMBER(23,4),
  /*   0*/  REPLACEMENT_RATE NUMBER(18,10),
  /*   0*/  MIN_FINAL_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  STACKING_MODE_CODE VARCHAR2(30 CHAR),
  /*   0*/  APPROVAL_REQUIRED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ADJUSTMENT_POLICY PRIMARY KEY (ADJUSTMENT_POLICY_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ADJUSTMENT_POLICY_ADJUSTMENT_POLICY_ID ON FEE.FEE_ADJUSTMENT_POLICY(ADJUSTMENT_POLICY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT CK_FEE_ADJ_PERCENT CHECK(PERCENT_VALUE IS NULL OR (PERCENT_VALUE >= 0 AND PERCENT_VALUE <= 1)) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT CK_FEE_ADJ_APPROVAL CHECK(APPROVAL_REQUIRED_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT CK_FEE_ADJ_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT UK_FEE_ADJ_POLICY UNIQUE(FEE_DEFINITION_VERSION_ID,POLICY_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_ADJ_POLICY ON FEE.FEE_ADJUSTMENT_POLICY(FEE_DEFINITION_VERSION_ID,POLICY_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_ADJ_PRIORITY ON FEE.FEE_ADJUSTMENT_POLICY(FEE_DEFINITION_VERSION_ID,PRIORITY_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ADJUSTMENT_POLICY_FEE_DEFINITION_VERSION_ID ON FEE.FEE_ADJUSTMENT_POLICY(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ADJUSTMENT_POLICY_APPLICABILITY_RULE_ID ON FEE.FEE_ADJUSTMENT_POLICY(APPLICABILITY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ADJUSTMENT_POLICY_REG_DISCOUNT_LIMIT_ID ON FEE.FEE_ADJUSTMENT_POLICY(REG_DISCOUNT_LIMIT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ADJUSTMENT_POLICY_CHARGE_COMPONENT_ID ON FEE.FEE_ADJUSTMENT_POLICY(CHARGE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT FK_FEE_ADJ_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT FK_FEE_ADJ_APP FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT FK_FEE_ADJ_REGLIMIT FOREIGN KEY (REG_DISCOUNT_LIMIT_ID) REFERENCES FEE.FEE_REGULATORY_DISCOUNT_LIMIT(REG_DISCOUNT_LIMIT_ID) ENABLE;

ALTER TABLE FEE.FEE_ADJUSTMENT_POLICY ADD CONSTRAINT FK_FEE_ADJ_COMPONENT FOREIGN KEY (CHARGE_COMPONENT_ID) REFERENCES FEE.FEE_CHARGE_COMPONENT(CHARGE_COMPONENT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ADJUSTMENT_POLICY IS 'سیاست تخفیف و تعدیل کارمزد';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.ADJUSTMENT_POLICY_ID IS 'شناسه سیاست تعدیل - ستون فیزیکی Oracle ADJUSTMENT_POLICY_ID.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.APPLICABILITY_RULE_ID IS 'شناسه قاعده شرایط اعمال - ستون فیزیکی Oracle APPLICABILITY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.REG_DISCOUNT_LIMIT_ID IS 'شناسه سقف مقرراتی تخفیف - ستون فیزیکی Oracle REG_DISCOUNT_LIMIT_ID.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.CHARGE_COMPONENT_ID IS 'شناسه مؤلفه مشمول تعدیل - ستون فیزیکی Oracle CHARGE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.POLICY_CODE IS 'کد سیاست تعدیل - ستون فیزیکی Oracle POLICY_CODE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.NAME_FA IS 'نام فارسی سیاست تعدیل - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.ADJUSTMENT_TYPE_CODE IS 'نوع تعدیل - ستون فیزیکی Oracle ADJUSTMENT_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.PRICING_FEATURE_TYPE_CODE IS 'نوع ویژگی قیمت‌گذاری - ستون فیزیکی Oracle PRICING_FEATURE_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.PRIORITY_NO IS 'اولویت - ستون فیزیکی Oracle PRIORITY_NO.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.PERCENT_VALUE IS 'نرخ درصدی تعدیل - ستون فیزیکی Oracle PERCENT_VALUE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.FIXED_AMOUNT IS 'مبلغ ثابت تعدیل - ستون فیزیکی Oracle FIXED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.REPLACEMENT_AMOUNT IS 'مبلغ جایگزین - ستون فیزیکی Oracle REPLACEMENT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.REPLACEMENT_RATE IS 'نرخ جایگزین - ستون فیزیکی Oracle REPLACEMENT_RATE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.MIN_FINAL_FEE_AMOUNT IS 'حداقل مبلغ نهایی کارمزد - ستون فیزیکی Oracle MIN_FINAL_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.STACKING_MODE_CODE IS 'روش هم‌پوشانی تعدیل‌ها - ستون فیزیکی Oracle STACKING_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.APPROVAL_REQUIRED_FLAG IS 'نیازمند تأیید است - ستون فیزیکی Oracle APPROVAL_REQUIRED_FLAG.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ADJUSTMENT_POLICY.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 26
Primary Keys : 1
Unique Keys  : 1
Checks       : 3
Foreign Keys : 4
Physical FKs : 4
Logical FKs  : 0
Indexes      : 5
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:07 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/