PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_RULE_COMPONENT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_RULE_COMPONENT]: Table name FEE_RULE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_RULE_COMPONENT.columns.OPERATOR_CODE]: Document type VARCHAR2(30 CHAR) differs from database metadata for OPERATOR_CODE. Metadata frequencies: NUMBER [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_RULE_COMPONENT.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_RULE_COMPONENT.foreignKeys.FK_FEE_RULE_COMP_PARENT]: Referenced table FEE_RULE_COMPONENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_RULE_COMPONENT.foreignKeys.FK_FEE_RULE_COMP_PARENT]: Referenced table FEE_RULE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_RULE_COMPONENT.foreignKeys.FK_FEE_RULE_COMP_RULE]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_RULE_COMPONENT.foreignKeys.FK_FEE_RULE_COMP_RULE]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_RULE_COMPONENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: جزء ترکیبی قاعده محاسبه
-- Nodeهای Expression Tree کنترل‌شده برای فرمول‌های پیچیده مانند MIN_OF، MAX_OF، External Value و Previous Charge.
CREATE TABLE FEE.FEE_RULE_COMPONENT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  RULE_COMPONENT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_RULE_COMPONENT.NEXTVAL NOT NULL,
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0) NOT NULL,
  /*   0*/  PARENT_RULE_COMPONENT_ID NUMBER(19,0),
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  NODE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   1*/  OPERATOR_CODE VARCHAR2(30 CHAR), -- W:TYPE
  /*   0*/  INPUT_CODE VARCHAR2(80 CHAR),
  /*   0*/  CONSTANT_NUMBER NUMBER(23,10),
  /*   0*/  CONSTANT_TEXT VARCHAR2(500 CHAR),
  /*   0*/  REFERENCE_CODE VARCHAR2(200 CHAR),
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_RULE_COMPONENT PRIMARY KEY (RULE_COMPONENT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_RULE_COMPONENT_RULE_COMPONENT_ID ON FEE.FEE_RULE_COMPONENT(RULE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_RULE_COMPONENT ADD CONSTRAINT UK_FEE_RULE_COMP_SEQ UNIQUE(CALCULATION_RULE_ID,SEQUENCE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_RULE_COMP_SEQ ON FEE.FEE_RULE_COMPONENT(CALCULATION_RULE_ID,SEQUENCE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_RULE_COMPONENT_CALCULATION_RULE_ID ON FEE.FEE_RULE_COMPONENT(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_RULE_COMPONENT_PARENT_RULE_COMPONENT_ID ON FEE.FEE_RULE_COMPONENT(PARENT_RULE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_RULE_COMPONENT ADD CONSTRAINT FK_FEE_RULE_COMP_RULE FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_RULE_COMPONENT ADD CONSTRAINT FK_FEE_RULE_COMP_PARENT FOREIGN KEY (PARENT_RULE_COMPONENT_ID) REFERENCES FEE.FEE_RULE_COMPONENT(RULE_COMPONENT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_RULE_COMPONENT IS 'جزء ترکیبی قاعده محاسبه';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.RULE_COMPONENT_ID IS 'شناسه جزء قاعده - ستون فیزیکی Oracle RULE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.PARENT_RULE_COMPONENT_ID IS 'شناسه جزء والد - ستون فیزیکی Oracle PARENT_RULE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.SEQUENCE_NO IS 'ترتیب جزء - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.NODE_TYPE_CODE IS 'نوع گره محاسباتی - ستون فیزیکی Oracle NODE_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.OPERATOR_CODE IS 'عملگر محاسباتی - ستون فیزیکی Oracle OPERATOR_CODE.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.INPUT_CODE IS 'کد ورودی مورد استفاده - ستون فیزیکی Oracle INPUT_CODE.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.CONSTANT_NUMBER IS 'ثابت عددی - ستون فیزیکی Oracle CONSTANT_NUMBER.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.CONSTANT_TEXT IS 'ثابت متنی - ستون فیزیکی Oracle CONSTANT_TEXT.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.REFERENCE_CODE IS 'کد مرجع یا منبع بیرونی - ستون فیزیکی Oracle REFERENCE_CODE.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.DESCRIPTION IS 'شرح جزء قاعده - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_RULE_COMPONENT.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 16
Primary Keys : 1
Unique Keys  : 1
Checks       : 0
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:05 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/