PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_PRODUCT_FEATURE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_PRODUCT_FEATURE]: Table name FEE_PRODUCT_FEATURE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_PRODUCT_FEATURE.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_PRODUCT_FEATURE.foreignKeys.FK_FEE_PROD_FEATURE_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_PRODUCT_FEATURE.foreignKeys.FK_FEE_PROD_FEATURE_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_PRODUCT_FEATURE.foreignKeys.FK_FEE_PROD_FEATURE_DEMO]: Referenced table FEE_DEMO_PRODUCT_FEATURE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_PRODUCT_FEATURE.foreignKeys.FK_FEE_PROD_FEATURE_DEMO]: Referenced table FEE_DEMO_PRODUCT_FEATURE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_PRODUCT_FEATURE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: ویژگی کارمزدی محصول
-- استقرار یک Fee Definition Version روی Product Feature نمایشی؛ هم‌راستا با BIAN Fee Product Feature.
CREATE TABLE FEE.FEE_PRODUCT_FEATURE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  FEE_PRODUCT_FEATURE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_PRODUCT_FEATURE.NEXTVAL NOT NULL,
  /*   0*/  DEMO_PRODUCT_FEATURE_ID NUMBER(19,0) NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR), -- W:TYPE
  /* 163*/  NAME_EN VARCHAR2(250 CHAR),
  /*   0*/  REQUIREMENT_TYPE_CODE VARCHAR2(30 CHAR) DEFAULT 'OPTIONAL' NOT NULL,
  /*   0*/  IS_MANDATORY_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   0*/  DEFAULT_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /*  16*/  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_PRODUCT_FEATURE PRIMARY KEY (FEE_PRODUCT_FEATURE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_PRODUCT_FEATURE_FEE_PRODUCT_FEATURE_ID ON FEE.FEE_PRODUCT_FEATURE(FEE_PRODUCT_FEATURE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT CK_FEE_PROD_FEATURE_MAND CHECK(IS_MANDATORY_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT CK_FEE_PROD_FEATURE_DFLT CHECK(DEFAULT_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT CK_FEE_PROD_FEATURE_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT UK_FEE_PROD_FEATURE UNIQUE(DEMO_PRODUCT_FEATURE_ID,FEE_DEFINITION_VERSION_ID)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_PROD_FEATURE ON FEE.FEE_PRODUCT_FEATURE(DEMO_PRODUCT_FEATURE_ID,FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_PRODUCT_FEATURE_DEMO_PRODUCT_FEATURE_ID ON FEE.FEE_PRODUCT_FEATURE(DEMO_PRODUCT_FEATURE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_PRODUCT_FEATURE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_PRODUCT_FEATURE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT FK_FEE_PROD_FEATURE_DEMO FOREIGN KEY (DEMO_PRODUCT_FEATURE_ID) REFERENCES FEE.FEE_DEMO_PRODUCT_FEATURE(DEMO_PRODUCT_FEATURE_ID) ENABLE;

ALTER TABLE FEE.FEE_PRODUCT_FEATURE ADD CONSTRAINT FK_FEE_PROD_FEATURE_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_PRODUCT_FEATURE IS 'ویژگی کارمزدی محصول';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.FEE_PRODUCT_FEATURE_ID IS 'شناسه ویژگی کارمزدی محصول - ستون فیزیکی Oracle FEE_PRODUCT_FEATURE_ID.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.DEMO_PRODUCT_FEATURE_ID IS 'شناسه ویژگی محصول آزمایشی - ستون فیزیکی Oracle DEMO_PRODUCT_FEATURE_ID.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.NAME_FA IS 'نام فارسی ویژگی کارمزدی محصول - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.NAME_EN IS 'نام انگلیسی ویژگی کارمزدی محصول - ستون فیزیکی Oracle NAME_EN.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.REQUIREMENT_TYPE_CODE IS 'نوع الزام ویژگی - ستون فیزیکی Oracle REQUIREMENT_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.IS_MANDATORY_FLAG IS 'اجباری است - ستون فیزیکی Oracle IS_MANDATORY_FLAG.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.DEFAULT_FLAG IS 'پیش‌فرض محصول است - ستون فیزیکی Oracle DEFAULT_FLAG.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.STATUS_CODE IS 'وضعیت - ستون فیزیکی Oracle STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_PRODUCT_FEATURE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 17
Primary Keys : 1
Unique Keys  : 1
Checks       : 3
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:02 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/