PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_CURRENCY_RULE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CURRENCY_RULE]: Table name FEE_CURRENCY_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CURRENCY_RULE.foreignKeys.FK_FEE_CURRENCY_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CURRENCY_RULE.foreignKeys.FK_FEE_CURRENCY_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_CURRENCY_RULE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: قاعده ارزی کارمزد
-- پیاده‌سازی Fee Currency Modality شامل ارز تعریف، مبنا، Posting و تبدیل ارز.
CREATE TABLE FEE.FEE_CURRENCY_RULE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  CURRENCY_RULE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_CURRENCY_RULE.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  RULE_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   0*/  CURRENCY_MODALITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  DEFINITION_CURRENCY_CODE VARCHAR2(3 CHAR),
  /*   0*/  BASIS_CURRENCY_MODE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  POSTING_CURRENCY_MODE_CODE VARCHAR2(50 CHAR),
  /*   0*/  POSTING_CURRENCY_CODE VARCHAR2(3 CHAR),
  /*   0*/  CONVERSION_REQUIRED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   0*/  FX_RATE_TYPE_CODE VARCHAR2(50 CHAR),
  /*   0*/  FX_RATE_SOURCE_CODE VARCHAR2(80 CHAR),
  /*   0*/  CONVERSION_DIRECTION_CODE VARCHAR2(30 CHAR),
  /*   0*/  CONVERSION_METHOD_CODE VARCHAR2(50 CHAR),
  /*   0*/  ROUNDING_MODE_CODE VARCHAR2(30 CHAR) DEFAULT 'HALF_UP' NOT NULL,
  /*   0*/  ROUNDING_SCALE NUMBER(2,0) DEFAULT 0 NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_CURRENCY_RULE PRIMARY KEY (CURRENCY_RULE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_CURRENCY_RULE_CURRENCY_RULE_ID ON FEE.FEE_CURRENCY_RULE(CURRENCY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_CURRENCY_RULE ADD CONSTRAINT CK_FEE_CURRENCY_CONV CHECK(CONVERSION_REQUIRED_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CURRENCY_RULE ADD CONSTRAINT CK_FEE_CURRENCY_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CURRENCY_RULE ADD CONSTRAINT UK_FEE_CURRENCY_CODE UNIQUE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_CURRENCY_CODE ON FEE.FEE_CURRENCY_RULE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_CURRENCY_RULE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_CURRENCY_RULE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_CURRENCY_RULE ADD CONSTRAINT FK_FEE_CURRENCY_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_CURRENCY_RULE IS 'قاعده ارزی کارمزد';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CURRENCY_RULE_ID IS 'شناسه قاعده ارزی - ستون فیزیکی Oracle CURRENCY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.RULE_CODE IS 'کد قاعده ارزی - ستون فیزیکی Oracle RULE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CURRENCY_MODALITY_TYPE_CODE IS 'نوع مدالیتی ارزی - ستون فیزیکی Oracle CURRENCY_MODALITY_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.DEFINITION_CURRENCY_CODE IS 'ارز تعریف کارمزد - ستون فیزیکی Oracle DEFINITION_CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.BASIS_CURRENCY_MODE_CODE IS 'روش تعیین ارز مبنا - ستون فیزیکی Oracle BASIS_CURRENCY_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.POSTING_CURRENCY_MODE_CODE IS 'روش تعیین ارز ثبت - ستون فیزیکی Oracle POSTING_CURRENCY_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.POSTING_CURRENCY_CODE IS 'ارز ثابت ثبت - ستون فیزیکی Oracle POSTING_CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CONVERSION_REQUIRED_FLAG IS 'تبدیل ارز لازم است - ستون فیزیکی Oracle CONVERSION_REQUIRED_FLAG.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.FX_RATE_TYPE_CODE IS 'نوع نرخ ارز - ستون فیزیکی Oracle FX_RATE_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.FX_RATE_SOURCE_CODE IS 'منبع نرخ ارز - ستون فیزیکی Oracle FX_RATE_SOURCE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CONVERSION_DIRECTION_CODE IS 'جهت تبدیل ارز - ستون فیزیکی Oracle CONVERSION_DIRECTION_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CONVERSION_METHOD_CODE IS 'روش تبدیل ارز - ستون فیزیکی Oracle CONVERSION_METHOD_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.ROUNDING_MODE_CODE IS 'روش گرد کردن - ستون فیزیکی Oracle ROUNDING_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.ROUNDING_SCALE IS 'تعداد رقم اعشار - ستون فیزیکی Oracle ROUNDING_SCALE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_CURRENCY_RULE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 23
Primary Keys : 1
Unique Keys  : 1
Checks       : 2
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 1
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:06 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/