PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ALLOCATION_RULE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ALLOCATION_RULE]: Table name FEE_ALLOCATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ALLOCATION_RULE.columns.FIXED_AMOUNT]: Document type NUMBER(23,4) differs from database metadata for FIXED_AMOUNT. Metadata frequencies: NUMBER(20,4) [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ALLOCATION_RULE.columns.PRIORITY_NO]: Document type NUMBER(10,0) differs from database metadata for PRIORITY_NO. Metadata frequencies: NUMBER(6,0) [4], NUMBER(3,0) [1], NUMBER(5,0) [1]. Total occurrences: 6.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ALLOCATION_RULE.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ALLOCATION_RULE.columns.SETTLEMENT_METHOD_CODE]: Document type VARCHAR2(50 CHAR) differs from database metadata for SETTLEMENT_METHOD_CODE. Metadata frequencies: VARCHAR2(40) [2]. Total occurrences: 2.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ALLOCATION_RULE.foreignKeys.FK_FEE_ALLOC_RULE_PARTY]: Referenced table FEE_DEMO_PARTY does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ALLOCATION_RULE.foreignKeys.FK_FEE_ALLOC_RULE_PARTY]: Referenced table FEE_DEMO_PARTY appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ALLOCATION_RULE.foreignKeys.FK_FEE_ALLOC_RULE_POLICY]: Referenced table FEE_ALLOCATION_POLICY does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ALLOCATION_RULE.foreignKeys.FK_FEE_ALLOC_RULE_POLICY]: Referenced table FEE_ALLOCATION_POLICY appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ALLOCATION_RULE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: قاعده تسهیم کارمزد
-- قاعده درصدی، مبلغ ثابت، Residual یا Rule-based برای هر ذی‌نفع/نقش.
CREATE TABLE FEE.FEE_ALLOCATION_RULE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  ALLOCATION_RULE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ALLOCATION_RULE.NEXTVAL NOT NULL,
  /*   0*/  ALLOCATION_POLICY_ID NUMBER(19,0) NOT NULL,
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  BENEFICIARY_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  DEMO_BENEFICIARY_PARTY_ID NUMBER(19,0),
  /*   0*/  ALLOCATION_BASIS_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  PERCENT_VALUE NUMBER(18,10),
  /*   1*/  FIXED_AMOUNT NUMBER(23,4), -- W:TYPE
  /*   6*/  PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL, -- W:TYPE
  /*   2*/  SETTLEMENT_METHOD_CODE VARCHAR2(50 CHAR), -- W:TYPE
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ALLOCATION_RULE PRIMARY KEY (ALLOCATION_RULE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ALLOCATION_RULE_ALLOCATION_RULE_ID ON FEE.FEE_ALLOCATION_RULE(ALLOCATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ALLOCATION_RULE ADD CONSTRAINT CK_FEE_ALLOC_RULE_PERCENT CHECK(PERCENT_VALUE IS NULL OR (PERCENT_VALUE >= 0 AND PERCENT_VALUE <= 1)) ENABLE;

ALTER TABLE FEE.FEE_ALLOCATION_RULE ADD CONSTRAINT UK_FEE_ALLOC_RULE_SEQ UNIQUE(ALLOCATION_POLICY_ID,SEQUENCE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_ALLOC_RULE_SEQ ON FEE.FEE_ALLOCATION_RULE(ALLOCATION_POLICY_ID,SEQUENCE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_ALLOCATION_RULE_ALLOCATION_POLICY_ID ON FEE.FEE_ALLOCATION_RULE(ALLOCATION_POLICY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ALLOCATION_RULE_DEMO_BENEFICIARY_PARTY_ID ON FEE.FEE_ALLOCATION_RULE(DEMO_BENEFICIARY_PARTY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ALLOCATION_RULE ADD CONSTRAINT FK_FEE_ALLOC_RULE_POLICY FOREIGN KEY (ALLOCATION_POLICY_ID) REFERENCES FEE.FEE_ALLOCATION_POLICY(ALLOCATION_POLICY_ID) ENABLE;

ALTER TABLE FEE.FEE_ALLOCATION_RULE ADD CONSTRAINT FK_FEE_ALLOC_RULE_PARTY FOREIGN KEY (DEMO_BENEFICIARY_PARTY_ID) REFERENCES FEE.FEE_DEMO_PARTY(DEMO_PARTY_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ALLOCATION_RULE IS 'قاعده تسهیم کارمزد';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.ALLOCATION_RULE_ID IS 'شناسه قاعده تسهیم - ستون فیزیکی Oracle ALLOCATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.ALLOCATION_POLICY_ID IS 'شناسه سیاست تسهیم - ستون فیزیکی Oracle ALLOCATION_POLICY_ID.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.SEQUENCE_NO IS 'ترتیب قاعده - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.BENEFICIARY_ROLE_CODE IS 'نقش ذی‌نفع - ستون فیزیکی Oracle BENEFICIARY_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.DEMO_BENEFICIARY_PARTY_ID IS 'شناسه ذی‌نفع آزمایشی - ستون فیزیکی Oracle DEMO_BENEFICIARY_PARTY_ID.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.ALLOCATION_BASIS_CODE IS 'مبنای تخصیص - ستون فیزیکی Oracle ALLOCATION_BASIS_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.PERCENT_VALUE IS 'درصد سهم - ستون فیزیکی Oracle PERCENT_VALUE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.FIXED_AMOUNT IS 'مبلغ ثابت سهم - ستون فیزیکی Oracle FIXED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.PRIORITY_NO IS 'اولویت تخصیص - ستون فیزیکی Oracle PRIORITY_NO.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.SETTLEMENT_METHOD_CODE IS 'روش تسویه سهم - ستون فیزیکی Oracle SETTLEMENT_METHOD_CODE.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ALLOCATION_RULE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 18
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:08 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/