PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_CHARGE_STAGE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_STAGE]: Table name FEE_CHARGE_STAGE appears to be singular. Table names should be plural.
PROMPT [WARNING] PLURAL_COLUMN_COMPONENT [tables.FEE_CHARGE_STAGE.columns.DEDUCT_PREVIOUS_CHARGES_FLAG]: Plural identifier component(s) detected: CHARGES.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CHARGE_STAGE.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] SPELLING_WARNING [tables.FEE_CHARGE_STAGE.columns.NON_REFUNDABLE_MIN_AMOUNT]: Possible spelling error: NON REFUNDABLE. This expression is normally spelled as one or with a hyphen.. Suggestions: non-refundable, nonrefundable. Original identifier is preserved.
PROMPT [WARNING] SPELLING_WARNING [tables.FEE_CHARGE_STAGE.columns.REFUNDABILITY_CODE]: Possible spelling error: REFUNDABILITY. Possible spelling mistake found.. Original identifier is preserved.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CHARGE_STAGE.columns.STAGE_CODE]: Document type VARCHAR2(80 CHAR) differs from database metadata for STAGE_CODE. Metadata frequencies: VARCHAR2(50) [1]. Total occurrences: 1.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_CALC]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_CALC]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_COMP]: Referenced table FEE_CHARGE_COMPONENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_COMP]: Referenced table FEE_CHARGE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CHARGE_STAGE.foreignKeys.FK_FEE_CHG_STAGE_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_CHARGE_STAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مرحله اخذ کارمزد
-- مدل اخذ چندمرحله‌ای کارمزد مانند اخذ بخشی در پذیرش و مابقی در تصویب/انعقاد قرارداد.
CREATE TABLE FEE.FEE_CHARGE_STAGE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  CHARGE_STAGE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_CHARGE_STAGE.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  CHARGE_COMPONENT_ID NUMBER(19,0),
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0) NOT NULL,
  /*   0*/  STAGE_NO NUMBER(5,0) NOT NULL,
  /*   1*/  STAGE_CODE VARCHAR2(80 CHAR) NOT NULL, -- W:TYPE
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  TRIGGER_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   0*/  DEDUCT_PREVIOUS_CHARGES_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL, -- W:SINGULAR
  /*   0*/  REFUNDABILITY_CODE VARCHAR2(30 CHAR) DEFAULT 'REFUNDABLE' NOT NULL, -- W:SPELL
  /*   0*/  NON_REFUNDABLE_MIN_AMOUNT NUMBER(23,4), -- W:SPELL
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_CHARGE_STAGE PRIMARY KEY (CHARGE_STAGE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_CHARGE_STAGE_CHARGE_STAGE_ID ON FEE.FEE_CHARGE_STAGE(CHARGE_STAGE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT CK_FEE_CHG_STAGE_DEDUCT CHECK(DEDUCT_PREVIOUS_CHARGES_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT CK_FEE_CHG_STAGE_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT UK_FEE_CHG_STAGE UNIQUE(FEE_DEFINITION_VERSION_ID,STAGE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_CHG_STAGE ON FEE.FEE_CHARGE_STAGE(FEE_DEFINITION_VERSION_ID,STAGE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_CHARGE_STAGE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_CHARGE_STAGE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_CHARGE_STAGE_CHARGE_COMPONENT_ID ON FEE.FEE_CHARGE_STAGE(CHARGE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_CHARGE_STAGE_CALCULATION_RULE_ID ON FEE.FEE_CHARGE_STAGE(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT FK_FEE_CHG_STAGE_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT FK_FEE_CHG_STAGE_COMP FOREIGN KEY (CHARGE_COMPONENT_ID) REFERENCES FEE.FEE_CHARGE_COMPONENT(CHARGE_COMPONENT_ID) ENABLE;

ALTER TABLE FEE.FEE_CHARGE_STAGE ADD CONSTRAINT FK_FEE_CHG_STAGE_CALC FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_CHARGE_STAGE IS 'مرحله اخذ کارمزد';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.CHARGE_STAGE_ID IS 'شناسه مرحله اخذ - ستون فیزیکی Oracle CHARGE_STAGE_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.CHARGE_COMPONENT_ID IS 'شناسه مؤلفه کارمزد - ستون فیزیکی Oracle CHARGE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه مرحله - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.STAGE_NO IS 'شماره مرحله - ستون فیزیکی Oracle STAGE_NO.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.STAGE_CODE IS 'کد مرحله - ستون فیزیکی Oracle STAGE_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.NAME_FA IS 'نام فارسی مرحله - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.TRIGGER_CODE IS 'رخداد محرک مرحله - ستون فیزیکی Oracle TRIGGER_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.DEDUCT_PREVIOUS_CHARGES_FLAG IS 'مبالغ قبلی کسر شوند - ستون فیزیکی Oracle DEDUCT_PREVIOUS_CHARGES_FLAG.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.REFUNDABILITY_CODE IS 'وضعیت قابلیت برگشت - ستون فیزیکی Oracle REFUNDABILITY_CODE.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.NON_REFUNDABLE_MIN_AMOUNT IS 'حداقل مبلغ غیرقابل برگشت - ستون فیزیکی Oracle NON_REFUNDABLE_MIN_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.DESCRIPTION IS 'شرح مرحله - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_CHARGE_STAGE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 19
Primary Keys : 1
Unique Keys  : 1
Checks       : 2
Foreign Keys : 3
Physical FKs : 3
Logical FKs  : 0
Indexes      : 3
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:06 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/