PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY]: Table name FEE_ARRANGEMENT_MODALITY appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_COLL]: Referenced table FEE_COLLECTION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_COLL]: Referenced table FEE_COLLECTION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_CURR]: Referenced table FEE_CURRENCY_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_CURR]: Referenced table FEE_CURRENCY_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_POST]: Referenced table FEE_POSTING_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_POST]: Referenced table FEE_POSTING_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_TIMING]: Referenced table FEE_TIMING_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_MODALITY.foreignKeys.FK_FEE_ARR_MOD_TIMING]: Referenced table FEE_TIMING_RULE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ARRANGEMENT_MODALITY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مدالیتی ترتیب کارمزد
-- اتصال Arrangement به Ruleهای Timing، Currency، Collection و Posting؛ realization فیزیکی Fee Arrangement Modality.
CREATE TABLE FEE.FEE_ARRANGEMENT_MODALITY -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  ARRANGEMENT_MODALITY_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ARRANGEMENT_MODALITY.NEXTVAL NOT NULL,
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0) NOT NULL,
  /*   0*/  MODALITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  TIMING_RULE_ID NUMBER(19,0),
  /*   0*/  CURRENCY_RULE_ID NUMBER(19,0),
  /*   0*/  COLLECTION_RULE_ID NUMBER(19,0),
  /*   0*/  POSTING_RULE_ID NUMBER(19,0),
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ARRANGEMENT_MODALITY PRIMARY KEY (ARRANGEMENT_MODALITY_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ARRANGEMENT_MODALITY_ARRANGEMENT_MODALITY_ID ON FEE.FEE_ARRANGEMENT_MODALITY(ARRANGEMENT_MODALITY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT CK_FEE_ARR_MOD_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_MODALITY_FEE_ARRANGEMENT_ID ON FEE.FEE_ARRANGEMENT_MODALITY(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_MODALITY_TIMING_RULE_ID ON FEE.FEE_ARRANGEMENT_MODALITY(TIMING_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_MODALITY_CURRENCY_RULE_ID ON FEE.FEE_ARRANGEMENT_MODALITY(CURRENCY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_MODALITY_COLLECTION_RULE_ID ON FEE.FEE_ARRANGEMENT_MODALITY(COLLECTION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_MODALITY_POSTING_RULE_ID ON FEE.FEE_ARRANGEMENT_MODALITY(POSTING_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT FK_FEE_ARR_MOD_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT FK_FEE_ARR_MOD_TIMING FOREIGN KEY (TIMING_RULE_ID) REFERENCES FEE.FEE_TIMING_RULE(TIMING_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT FK_FEE_ARR_MOD_CURR FOREIGN KEY (CURRENCY_RULE_ID) REFERENCES FEE.FEE_CURRENCY_RULE(CURRENCY_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT FK_FEE_ARR_MOD_COLL FOREIGN KEY (COLLECTION_RULE_ID) REFERENCES FEE.FEE_COLLECTION_RULE(COLLECTION_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_MODALITY ADD CONSTRAINT FK_FEE_ARR_MOD_POST FOREIGN KEY (POSTING_RULE_ID) REFERENCES FEE.FEE_POSTING_RULE(POSTING_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ARRANGEMENT_MODALITY IS 'مدالیتی ترتیب کارمزد';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.ARRANGEMENT_MODALITY_ID IS 'شناسه مدالیتی ترتیب - ستون فیزیکی Oracle ARRANGEMENT_MODALITY_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.MODALITY_TYPE_CODE IS 'نوع مدالیتی - ستون فیزیکی Oracle MODALITY_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.TIMING_RULE_ID IS 'شناسه قاعده زمان‌بندی - ستون فیزیکی Oracle TIMING_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.CURRENCY_RULE_ID IS 'شناسه قاعده ارزی - ستون فیزیکی Oracle CURRENCY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.COLLECTION_RULE_ID IS 'شناسه قاعده وصول - ستون فیزیکی Oracle COLLECTION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.POSTING_RULE_ID IS 'شناسه قاعده ثبت - ستون فیزیکی Oracle POSTING_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.DESCRIPTION IS 'شرح مدالیتی - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_MODALITY.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 15
Primary Keys : 1
Unique Keys  : 0
Checks       : 1
Foreign Keys : 5
Physical FKs : 5
Logical FKs  : 0
Indexes      : 5
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:09 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/