PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_SETTLEMENT_REFERENCE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_SETTLEMENT_REFERENCE]: Table name FEE_SETTLEMENT_REFERENCE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_SETTLEMENT_REFERENCE.columns.SETTLEMENT_METHOD_CODE]: Document type VARCHAR2(50 CHAR) differs from database metadata for SETTLEMENT_METHOD_CODE. Metadata frequencies: VARCHAR2(40) [2]. Total occurrences: 2.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_ACCOUNT]: Referenced table FEE_DEMO_ACCOUNT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_ACCOUNT]: Referenced table FEE_DEMO_ACCOUNT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_ALLOC]: Referenced table FEE_ALLOCATION_RESULT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_ALLOC]: Referenced table FEE_ALLOCATION_RESULT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_SETTLEMENT_REFERENCE.foreignKeys.FK_FEE_SETTLE_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_SETTLEMENT_REFERENCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: مرجع تسویه کارمزد
-- مرجع/Simulation تسویه Fee Transaction یا Allocation Result بدون پیاده‌سازی Payment/Settlement enterprise.
CREATE TABLE FEE.FEE_SETTLEMENT_REFERENCE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  SETTLEMENT_REFERENCE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_SETTLEMENT_REFERENCE.NEXTVAL NOT NULL,
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0),
  /*   0*/  ALLOCATION_RESULT_ID NUMBER(19,0),
  /*   2*/  SETTLEMENT_METHOD_CODE VARCHAR2(50 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  SETTLEMENT_STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'PLANNED' NOT NULL,
  /*   0*/  SETTLEMENT_DATE DATE,
  /*   0*/  SETTLEMENT_ACCOUNT_ID NUMBER(19,0),
  /*   0*/  SETTLEMENT_AMOUNT NUMBER(23,4),
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR),
  /*   0*/  SETTLEMENT_REFERENCE VARCHAR2(200 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT PK_FEE_SETTLEMENT_REFERENCE PRIMARY KEY (SETTLEMENT_REFERENCE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_SETTLEMENT_REFERENCE_SETTLEMENT_REFERENCE_ID ON FEE.FEE_SETTLEMENT_REFERENCE(SETTLEMENT_REFERENCE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

CREATE INDEX FEE.IX_FEE_SETTLE_STATUS ON FEE.FEE_SETTLEMENT_REFERENCE(SETTLEMENT_STATUS_CODE,SETTLEMENT_DATE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_SETTLEMENT_REFERENCE_FEE_TRANSACTION_ID ON FEE.FEE_SETTLEMENT_REFERENCE(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_SETTLEMENT_REFERENCE_ALLOCATION_RESULT_ID ON FEE.FEE_SETTLEMENT_REFERENCE(ALLOCATION_RESULT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_SETTLEMENT_REFERENCE_SETTLEMENT_ACCOUNT_ID ON FEE.FEE_SETTLEMENT_REFERENCE(SETTLEMENT_ACCOUNT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_SETTLEMENT_REFERENCE ADD CONSTRAINT FK_FEE_SETTLE_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_SETTLEMENT_REFERENCE ADD CONSTRAINT FK_FEE_SETTLE_ALLOC FOREIGN KEY (ALLOCATION_RESULT_ID) REFERENCES FEE.FEE_ALLOCATION_RESULT(ALLOCATION_RESULT_ID) ENABLE;

ALTER TABLE FEE.FEE_SETTLEMENT_REFERENCE ADD CONSTRAINT FK_FEE_SETTLE_ACCOUNT FOREIGN KEY (SETTLEMENT_ACCOUNT_ID) REFERENCES FEE.FEE_DEMO_ACCOUNT(DEMO_ACCOUNT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_SETTLEMENT_REFERENCE IS 'مرجع تسویه کارمزد';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_REFERENCE_ID IS 'شناسه مرجع تسویه - ستون فیزیکی Oracle SETTLEMENT_REFERENCE_ID.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.ALLOCATION_RESULT_ID IS 'شناسه نتیجه تسهیم - ستون فیزیکی Oracle ALLOCATION_RESULT_ID.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_METHOD_CODE IS 'روش تسویه - ستون فیزیکی Oracle SETTLEMENT_METHOD_CODE.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_STATUS_CODE IS 'وضعیت تسویه - ستون فیزیکی Oracle SETTLEMENT_STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_DATE IS 'تاریخ تسویه - ستون فیزیکی Oracle SETTLEMENT_DATE.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_ACCOUNT_ID IS 'شناسه حساب آزمایشی تسویه - ستون فیزیکی Oracle SETTLEMENT_ACCOUNT_ID.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_AMOUNT IS 'مبلغ تسویه - ستون فیزیکی Oracle SETTLEMENT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.CURRENCY_CODE IS 'ارز تسویه - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.SETTLEMENT_REFERENCE IS 'شماره یا مرجع تسویه - ستون فیزیکی Oracle SETTLEMENT_REFERENCE.';

COMMENT ON COLUMN FEE.FEE_SETTLEMENT_REFERENCE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 11
Primary Keys : 1
Unique Keys  : 0
Checks       : 0
Foreign Keys : 3
Physical FKs : 3
Logical FKs  : 0
Indexes      : 4
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:13 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/