PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_DECISION_TRACE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DECISION_TRACE]: Table name FEE_DECISION_TRACE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_APP]: Referenced table FEE_APPLICABILITY_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_APP]: Referenced table FEE_APPLICABILITY_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_CALC]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_CALC]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_COMP]: Referenced table FEE_RULE_COMPONENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_COMP]: Referenced table FEE_RULE_COMPONENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_DECISION_TRACE.foreignKeys.FK_FEE_TRACE_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_DECISION_TRACE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: ردپای تصمیم کارمزد
-- ثبت مرحله‌به‌مرحله تصمیم Rule Engine برای Explainability و ممیزی؛ برگرفته از IFW DecisionTrace.
CREATE TABLE FEE.FEE_DECISION_TRACE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  TRACE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_DECISION_TRACE.NEXTVAL NOT NULL,
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  STEP_NO NUMBER(10,0) NOT NULL,
  /*   0*/  STEP_NAME VARCHAR2(250 CHAR) NOT NULL,
  /*   0*/  STEP_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0),
  /*   0*/  APPLICABILITY_RULE_ID NUMBER(19,0),
  /*   0*/  RULE_COMPONENT_ID NUMBER(19,0),
  /*   0*/  INPUT_PAYLOAD CLOB,
  /*   0*/  OUTPUT_PAYLOAD CLOB,
  /*   0*/  EVALUATION_RESULT_CODE VARCHAR2(50 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
CONSTRAINT PK_FEE_DECISION_TRACE PRIMARY KEY (TRACE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_DECISION_TRACE_TRACE_ID ON FEE.FEE_DECISION_TRACE(TRACE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_DECISION_TRACE ADD CONSTRAINT UK_FEE_TRACE_STEP UNIQUE(FEE_TRANSACTION_ID,STEP_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_TRACE_STEP ON FEE.FEE_DECISION_TRACE(FEE_TRANSACTION_ID,STEP_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_DECISION_TRACE_FEE_TRANSACTION_ID ON FEE.FEE_DECISION_TRACE(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DECISION_TRACE_CALCULATION_RULE_ID ON FEE.FEE_DECISION_TRACE(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DECISION_TRACE_APPLICABILITY_RULE_ID ON FEE.FEE_DECISION_TRACE(APPLICABILITY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_DECISION_TRACE_RULE_COMPONENT_ID ON FEE.FEE_DECISION_TRACE(RULE_COMPONENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_DECISION_TRACE ADD CONSTRAINT FK_FEE_TRACE_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_DECISION_TRACE ADD CONSTRAINT FK_FEE_TRACE_CALC FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_DECISION_TRACE ADD CONSTRAINT FK_FEE_TRACE_APP FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID) ENABLE;

ALTER TABLE FEE.FEE_DECISION_TRACE ADD CONSTRAINT FK_FEE_TRACE_COMP FOREIGN KEY (RULE_COMPONENT_ID) REFERENCES FEE.FEE_RULE_COMPONENT(RULE_COMPONENT_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_DECISION_TRACE IS 'ردپای تصمیم کارمزد';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.TRACE_ID IS 'شناسه ردپای تصمیم - ستون فیزیکی Oracle TRACE_ID.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.STEP_NO IS 'شماره گام تصمیم - ستون فیزیکی Oracle STEP_NO.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.STEP_NAME IS 'نام گام تصمیم - ستون فیزیکی Oracle STEP_NAME.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.STEP_TYPE_CODE IS 'نوع گام - ستون فیزیکی Oracle STEP_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.APPLICABILITY_RULE_ID IS 'شناسه قاعده شرایط اعمال - ستون فیزیکی Oracle APPLICABILITY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.RULE_COMPONENT_ID IS 'شناسه جزء قاعده - ستون فیزیکی Oracle RULE_COMPONENT_ID.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.INPUT_PAYLOAD IS 'ورودی گام - ستون فیزیکی Oracle INPUT_PAYLOAD.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.OUTPUT_PAYLOAD IS 'خروجی گام - ستون فیزیکی Oracle OUTPUT_PAYLOAD.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.EVALUATION_RESULT_CODE IS 'نتیجه ارزیابی - ستون فیزیکی Oracle EVALUATION_RESULT_CODE.';

COMMENT ON COLUMN FEE.FEE_DECISION_TRACE.CREATED_AT IS 'زمان ثبت گام - ستون فیزیکی Oracle CREATED_AT.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 12
Primary Keys : 1
Unique Keys  : 1
Checks       : 0
Foreign Keys : 4
Physical FKs : 4
Logical FKs  : 0
Indexes      : 4
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:13 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/