PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ARRANGEMENT_CALC_TERM]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] SPELLING_WARNING [tables.FEE_ARRANGEMENT_CALC_TERM]: Possible spelling error: CALC. Possible spelling mistake found.. Suggestions: call, calm, calf. Original identifier is preserved.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_CALC_TERM]: Table name FEE_ARRANGEMENT_CALC_TERM appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ARRANGEMENT_CALC_TERM.columns.APPROVAL_REF]: Document type VARCHAR2(200 CHAR) differs from database metadata for APPROVAL_REF. Metadata frequencies: VARCHAR2(100) [3]. Total occurrences: 3.
PROMPT [WARNING] SPELLING_WARNING [tables.FEE_ARRANGEMENT_CALC_TERM.columns.ARRANGEMENT_CALC_TERM_ID]: Possible spelling error: CALC. Possible spelling mistake found.. Suggestions: call, calm, calf. Original identifier is preserved.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ARRANGEMENT_CALC_TERM.columns.FIXED_AMOUNT]: Document type NUMBER(23,4) differs from database metadata for FIXED_AMOUNT. Metadata frequencies: NUMBER(20,4) [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_ARRANGEMENT_CALC_TERM.columns.RATE_VALUE]: Document type NUMBER(18,10) differs from database metadata for RATE_VALUE. Metadata frequencies: NUMBER(12,8) [3]. Total occurrences: 3.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_CALC_TERM.foreignKeys.FK_FEE_ARR_TERM_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_CALC_TERM.foreignKeys.FK_FEE_ARR_TERM_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_CALC_TERM.foreignKeys.FK_FEE_ARR_TERM_CALC]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_CALC_TERM.foreignKeys.FK_FEE_ARR_TERM_CALC]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ARRANGEMENT_CALC_TERM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: شرط محاسباتی اختصاصی ترتیب
-- شرایط negotiated/exceptional محاسبه در سطح Arrangement بدون تغییر Fee Definition استاندارد.
CREATE TABLE FEE.FEE_ARRANGEMENT_CALC_TERM -- W:SCHEMA|SPELL|TABLE-PLURAL
(
  /*   0*/  ARRANGEMENT_CALC_TERM_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ARRANGEMENT_CALC_TERM.NEXTVAL NOT NULL, -- W:SPELL
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0) NOT NULL,
  /*   0*/  BASE_CALCULATION_RULE_ID NUMBER(19,0),
  /*   0*/  CALCULATION_STRATEGY_CODE VARCHAR2(50 CHAR),
  /*   1*/  FIXED_AMOUNT NUMBER(23,4), -- W:TYPE
  /*   3*/  RATE_VALUE NUMBER(18,10), -- W:TYPE
  /*   0*/  MIN_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  MAX_FEE_AMOUNT NUMBER(23,4),
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR),
  /*   0*/  RATE_PERIOD_CODE VARCHAR2(20 CHAR),
  /*   2*/  DAY_COUNT_BASIS_CODE VARCHAR2(30 CHAR),
  /*   0*/  ROUNDING_MODE_CODE VARCHAR2(30 CHAR),
  /*   0*/  ROUNDING_SCALE NUMBER(2,0),
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /*   3*/  APPROVAL_REF VARCHAR2(200 CHAR), -- W:TYPE
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ARRANGEMENT_CALC_TERM PRIMARY KEY (ARRANGEMENT_CALC_TERM_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ARRANGEMENT_CALC_TERM_ARRANGEMENT_CALC_TERM_ID ON FEE.FEE_ARRANGEMENT_CALC_TERM(ARRANGEMENT_CALC_TERM_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_CALC_TERM ADD CONSTRAINT CK_FEE_ARR_TERM_MINMAX CHECK(MIN_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT >= MIN_FEE_AMOUNT) ENABLE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_CALC_TERM_FEE_ARRANGEMENT_ID ON FEE.FEE_ARRANGEMENT_CALC_TERM(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_CALC_TERM_BASE_CALCULATION_RULE_ID ON FEE.FEE_ARRANGEMENT_CALC_TERM(BASE_CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_CALC_TERM ADD CONSTRAINT FK_FEE_ARR_TERM_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_CALC_TERM ADD CONSTRAINT FK_FEE_ARR_TERM_CALC FOREIGN KEY (BASE_CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ARRANGEMENT_CALC_TERM IS 'شرط محاسباتی اختصاصی ترتیب';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.ARRANGEMENT_CALC_TERM_ID IS 'شناسه شرط محاسباتی ترتیب - ستون فیزیکی Oracle ARRANGEMENT_CALC_TERM_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.BASE_CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه پایه - ستون فیزیکی Oracle BASE_CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.CALCULATION_STRATEGY_CODE IS 'استراتژی محاسبه اختصاصی - ستون فیزیکی Oracle CALCULATION_STRATEGY_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.FIXED_AMOUNT IS 'مبلغ ثابت اختصاصی - ستون فیزیکی Oracle FIXED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.RATE_VALUE IS 'نرخ اختصاصی - ستون فیزیکی Oracle RATE_VALUE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.MIN_FEE_AMOUNT IS 'حداقل کارمزد اختصاصی - ستون فیزیکی Oracle MIN_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.MAX_FEE_AMOUNT IS 'حداکثر کارمزد اختصاصی - ستون فیزیکی Oracle MAX_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.CURRENCY_CODE IS 'ارز شرط اختصاصی - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.RATE_PERIOD_CODE IS 'دوره نرخ اختصاصی - ستون فیزیکی Oracle RATE_PERIOD_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.DAY_COUNT_BASIS_CODE IS 'مبنای شمارش روز اختصاصی - ستون فیزیکی Oracle DAY_COUNT_BASIS_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.ROUNDING_MODE_CODE IS 'روش گرد کردن - ستون فیزیکی Oracle ROUNDING_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.ROUNDING_SCALE IS 'تعداد رقم اعشار - ستون فیزیکی Oracle ROUNDING_SCALE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.APPROVAL_REF IS 'مرجع تأیید شرط اختصاصی - ستون فیزیکی Oracle APPROVAL_REF.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_CALC_TERM.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 22
Primary Keys : 1
Unique Keys  : 0
Checks       : 1
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:10 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/