PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_APPLICABILITY_CONDITION]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_APPLICABILITY_CONDITION]: Table name FEE_APPLICABILITY_CONDITION appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_APPLICABILITY_CONDITION.columns.OPERATOR_CODE]: Document type VARCHAR2(30 CHAR) differs from database metadata for OPERATOR_CODE. Metadata frequencies: NUMBER [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_APPLICABILITY_CONDITION.columns.SEQUENCE_NO]: Document type NUMBER(5,0) differs from database metadata for SEQUENCE_NO. Metadata frequencies: NUMBER(6,0) [4]. Total occurrences: 4.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_APPLICABILITY_CONDITION.foreignKeys.FK_FEE_APP_COND_RULE]: Referenced table FEE_APPLICABILITY_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_APPLICABILITY_CONDITION.foreignKeys.FK_FEE_APP_COND_RULE]: Referenced table FEE_APPLICABILITY_RULE appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_APPLICABILITY_CONDITION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: شرط قاعده اعمال کارمزد
-- Predicateهای کنترل‌شده Rule Builder مانند Party Type، Segment، Channel، Amount، Event و Elapsed Period.
CREATE TABLE FEE.FEE_APPLICABILITY_CONDITION -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  CONDITION_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_APPLICABILITY_CONDITION.NEXTVAL NOT NULL,
  /*   0*/  APPLICABILITY_RULE_ID NUMBER(19,0) NOT NULL,
  /*   4*/  SEQUENCE_NO NUMBER(5,0) NOT NULL, -- W:TYPE
  /*   0*/  GROUP_NO NUMBER(5,0),
  /*   0*/  DIMENSION_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   1*/  OPERATOR_CODE VARCHAR2(30 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  LOGICAL_OPERATOR_CODE VARCHAR2(10 CHAR),
  /*   0*/  VALUE_TYPE_CODE VARCHAR2(20 CHAR) NOT NULL,
  /*   0*/  TEXT_VALUE VARCHAR2(500 CHAR),
  /*   0*/  NUMBER_VALUE_FROM NUMBER(23,4),
  /*   0*/  NUMBER_VALUE_TO NUMBER(23,4),
  /*   0*/  DATE_VALUE_FROM DATE,
  /*   0*/  DATE_VALUE_TO DATE,
  /*   0*/  BOOLEAN_VALUE CHAR(1 CHAR),
  /*   0*/  REFERENCE_CODE VARCHAR2(200 CHAR),
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
CONSTRAINT PK_FEE_APPLICABILITY_CONDITION PRIMARY KEY (CONDITION_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_APPLICABILITY_CONDITION_CONDITION_ID ON FEE.FEE_APPLICABILITY_CONDITION(CONDITION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_APPLICABILITY_CONDITION ADD CONSTRAINT CK_FEE_APP_COND_BOOL CHECK(BOOLEAN_VALUE IS NULL OR BOOLEAN_VALUE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_APPLICABILITY_CONDITION ADD CONSTRAINT UK_FEE_APP_COND_SEQ UNIQUE(APPLICABILITY_RULE_ID,SEQUENCE_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_APP_COND_SEQ ON FEE.FEE_APPLICABILITY_CONDITION(APPLICABILITY_RULE_ID,SEQUENCE_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_APP_COND_DIM ON FEE.FEE_APPLICABILITY_CONDITION(APPLICABILITY_RULE_ID,DIMENSION_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_APPLICABILITY_CONDITION_APPLICABILITY_RULE_ID ON FEE.FEE_APPLICABILITY_CONDITION(APPLICABILITY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_APPLICABILITY_CONDITION ADD CONSTRAINT FK_FEE_APP_COND_RULE FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_APPLICABILITY_CONDITION IS 'شرط قاعده اعمال کارمزد';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.CONDITION_ID IS 'شناسه شرط - ستون فیزیکی Oracle CONDITION_ID.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.APPLICABILITY_RULE_ID IS 'شناسه قاعده اعمال - ستون فیزیکی Oracle APPLICABILITY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.SEQUENCE_NO IS 'ترتیب شرط - ستون فیزیکی Oracle SEQUENCE_NO.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.GROUP_NO IS 'شماره گروه منطقی - ستون فیزیکی Oracle GROUP_NO.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.DIMENSION_CODE IS 'بعد شرط - ستون فیزیکی Oracle DIMENSION_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.OPERATOR_CODE IS 'عملگر شرط - ستون فیزیکی Oracle OPERATOR_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.LOGICAL_OPERATOR_CODE IS 'عملگر منطقی - ستون فیزیکی Oracle LOGICAL_OPERATOR_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.VALUE_TYPE_CODE IS 'نوع مقدار شرط - ستون فیزیکی Oracle VALUE_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.TEXT_VALUE IS 'مقدار متنی - ستون فیزیکی Oracle TEXT_VALUE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.NUMBER_VALUE_FROM IS 'مقدار عددی از - ستون فیزیکی Oracle NUMBER_VALUE_FROM.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.NUMBER_VALUE_TO IS 'مقدار عددی تا - ستون فیزیکی Oracle NUMBER_VALUE_TO.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.DATE_VALUE_FROM IS 'تاریخ از - ستون فیزیکی Oracle DATE_VALUE_FROM.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.DATE_VALUE_TO IS 'تاریخ تا - ستون فیزیکی Oracle DATE_VALUE_TO.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.BOOLEAN_VALUE IS 'مقدار منطقی - ستون فیزیکی Oracle BOOLEAN_VALUE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.REFERENCE_CODE IS 'کد مرجع - ستون فیزیکی Oracle REFERENCE_CODE.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.DESCRIPTION IS 'شرح شرط - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_APPLICABILITY_CONDITION.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 18
Primary Keys : 1
Unique Keys  : 1
Checks       : 1
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:03 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/