PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_ARRANGEMENT_INVOLVEMENT]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_INVOLVEMENT]: Table name FEE_ARRANGEMENT_INVOLVEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_INVOLVEMENT.foreignKeys.FK_FEE_ARR_INV_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_INVOLVEMENT.foreignKeys.FK_FEE_ARR_INV_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_ARRANGEMENT_INVOLVEMENT.foreignKeys.FK_FEE_ARR_INV_PARTY]: Referenced table FEE_DEMO_PARTY does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_ARRANGEMENT_INVOLVEMENT.foreignKeys.FK_FEE_ARR_INV_PARTY]: Referenced table FEE_DEMO_PARTY appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_ARRANGEMENT_INVOLVEMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: نقش طرف در ترتیب کارمزد
-- ثبت Charge Bearer، Charge Agent، Charge Recipient و Charge Account Agent در Fee Arrangement.
CREATE TABLE FEE.FEE_ARRANGEMENT_INVOLVEMENT -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  INVOLVEMENT_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_ARRANGEMENT_INVOLVEMENT.NEXTVAL NOT NULL,
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0) NOT NULL,
  /*   0*/  DEMO_PARTY_ID NUMBER(19,0) NOT NULL,
  /*   0*/  INVOLVEMENT_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  ROLE_DETAIL_CODE VARCHAR2(80 CHAR),
  /*   0*/  IS_PRIMARY_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_ARRANGEMENT_INVOLVEMENT PRIMARY KEY (INVOLVEMENT_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_ARRANGEMENT_INVOLVEMENT_INVOLVEMENT_ID ON FEE.FEE_ARRANGEMENT_INVOLVEMENT(INVOLVEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_INVOLVEMENT ADD CONSTRAINT CK_FEE_ARR_INV_PRIMARY CHECK(IS_PRIMARY_FLAG IN ('Y','N')) ENABLE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_INVOLVEMENT_FEE_ARRANGEMENT_ID ON FEE.FEE_ARRANGEMENT_INVOLVEMENT(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_ARRANGEMENT_INVOLVEMENT_DEMO_PARTY_ID ON FEE.FEE_ARRANGEMENT_INVOLVEMENT(DEMO_PARTY_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_ARRANGEMENT_INVOLVEMENT ADD CONSTRAINT FK_FEE_ARR_INV_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_ARRANGEMENT_INVOLVEMENT ADD CONSTRAINT FK_FEE_ARR_INV_PARTY FOREIGN KEY (DEMO_PARTY_ID) REFERENCES FEE.FEE_DEMO_PARTY(DEMO_PARTY_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_ARRANGEMENT_INVOLVEMENT IS 'نقش طرف در ترتیب کارمزد';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.INVOLVEMENT_ID IS 'شناسه نقش طرف - ستون فیزیکی Oracle INVOLVEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.DEMO_PARTY_ID IS 'شناسه طرف آزمایشی - ستون فیزیکی Oracle DEMO_PARTY_ID.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.INVOLVEMENT_ROLE_CODE IS 'نوع نقش در کارمزد - ستون فیزیکی Oracle INVOLVEMENT_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.ROLE_DETAIL_CODE IS 'جزئیات نقش - ستون فیزیکی Oracle ROLE_DETAIL_CODE.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.IS_PRIMARY_FLAG IS 'نقش اصلی است - ستون فیزیکی Oracle IS_PRIMARY_FLAG.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.DESCRIPTION IS 'شرح نقش - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_ARRANGEMENT_INVOLVEMENT.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 14
Primary Keys : 1
Unique Keys  : 0
Checks       : 1
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 2
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:09 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/