PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_CALCULATION_RULE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CALCULATION_RULE]: Table name FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CALCULATION_RULE.columns.FIXED_AMOUNT]: Document type NUMBER(23,4) differs from database metadata for FIXED_AMOUNT. Metadata frequencies: NUMBER(20,4) [1]. Total occurrences: 1.
PROMPT [WARNING] PLURAL_COLUMN_COMPONENT [tables.FEE_CALCULATION_RULE.columns.MIN_CHARGE_PERIOD_DAYS]: Plural identifier component(s) detected: DAYS.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CALCULATION_RULE.columns.NAME_FA]: Document type VARCHAR2(250 CHAR) differs from database metadata for NAME_FA. Metadata frequencies: VARCHAR2(200) [155], VARCHAR2(500) [3], VARCHAR2(100) [2], VARCHAR2(120) [1], VARCHAR2(300) [1], VARCHAR2(50) [1]. Total occurrences: 163.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CALCULATION_RULE.columns.PRIORITY_NO]: Document type NUMBER(10,0) differs from database metadata for PRIORITY_NO. Metadata frequencies: NUMBER(6,0) [4], NUMBER(3,0) [1], NUMBER(5,0) [1]. Total occurrences: 6.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_CALCULATION_RULE.columns.RATE_VALUE]: Document type NUMBER(18,10) differs from database metadata for RATE_VALUE. Metadata frequencies: NUMBER(12,8) [3]. Total occurrences: 3.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CALCULATION_RULE.foreignKeys.FK_FEE_CALC_RULE_APP]: Referenced table FEE_APPLICABILITY_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CALCULATION_RULE.foreignKeys.FK_FEE_CALC_RULE_APP]: Referenced table FEE_APPLICABILITY_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_CALCULATION_RULE.foreignKeys.FK_FEE_CALC_RULE_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_CALCULATION_RULE.foreignKeys.FK_FEE_CALC_RULE_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_CALCULATION_RULE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: قاعده محاسبه کارمزد
-- پیاده‌سازی فیزیکی Fee Calculation Modality با استراتژی‌های ثابت، درصدی، پلکانی، حاشیه‌ای، سالانه و Composite.
CREATE TABLE FEE.FEE_CALCULATION_RULE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_CALCULATION_RULE.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  APPLICABILITY_RULE_ID NUMBER(19,0),
  /*   0*/  RULE_CODE VARCHAR2(80 CHAR) NOT NULL,
  /* 163*/  NAME_FA VARCHAR2(250 CHAR) NOT NULL, -- W:TYPE
  /*   6*/  PRIORITY_NO NUMBER(10,0) DEFAULT 100 NOT NULL, -- W:TYPE
  /*   0*/  CALCULATION_STRATEGY_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  BASIS_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   1*/  FIXED_AMOUNT NUMBER(23,4), -- W:TYPE
  /*   3*/  RATE_VALUE NUMBER(18,10), -- W:TYPE
  /*   0*/  MIN_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  MAX_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  RATE_PERIOD_CODE VARCHAR2(20 CHAR),
  /*   2*/  DAY_COUNT_BASIS_CODE VARCHAR2(30 CHAR),
  /*   0*/  PRORATION_MODE_CODE VARCHAR2(30 CHAR),
  /*   0*/  MIN_CHARGE_PERIOD_DAYS NUMBER(10,0), -- W:SINGULAR
  /*   7*/  CURRENCY_CODE VARCHAR2(3 CHAR),
  /*   0*/  ROUNDING_MODE_CODE VARCHAR2(30 CHAR) DEFAULT 'HALF_UP' NOT NULL,
  /*   0*/  ROUNDING_SCALE NUMBER(2,0) DEFAULT 0 NOT NULL,
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(2000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_CALCULATION_RULE PRIMARY KEY (CALCULATION_RULE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_CALCULATION_RULE_CALCULATION_RULE_ID ON FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT CK_FEE_CALC_RULE_RATE CHECK(RATE_VALUE IS NULL OR RATE_VALUE >= 0) ENABLE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT CK_FEE_CALC_RULE_MINMAX CHECK(MIN_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT IS NULL OR MAX_FEE_AMOUNT >= MIN_FEE_AMOUNT) ENABLE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT CK_FEE_CALC_RULE_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT CK_FEE_CALC_RULE_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM) ENABLE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT UK_FEE_CALC_RULE_CODE UNIQUE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_CALC_RULE_CODE ON FEE.FEE_CALCULATION_RULE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_CALC_RULE_PRIORITY ON FEE.FEE_CALCULATION_RULE(FEE_DEFINITION_VERSION_ID,PRIORITY_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_CALCULATION_RULE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_CALCULATION_RULE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_CALCULATION_RULE_APPLICABILITY_RULE_ID ON FEE.FEE_CALCULATION_RULE(APPLICABILITY_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT FK_FEE_CALC_RULE_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_CALCULATION_RULE ADD CONSTRAINT FK_FEE_CALC_RULE_APP FOREIGN KEY (APPLICABILITY_RULE_ID) REFERENCES FEE.FEE_APPLICABILITY_RULE(APPLICABILITY_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_CALCULATION_RULE IS 'قاعده محاسبه کارمزد';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.APPLICABILITY_RULE_ID IS 'شناسه قاعده شرایط اعمال - ستون فیزیکی Oracle APPLICABILITY_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.RULE_CODE IS 'کد قاعده محاسبه - ستون فیزیکی Oracle RULE_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.NAME_FA IS 'نام فارسی قاعده محاسبه - ستون فیزیکی Oracle NAME_FA.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.PRIORITY_NO IS 'اولویت محاسبه - ستون فیزیکی Oracle PRIORITY_NO.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.CALCULATION_STRATEGY_CODE IS 'استراتژی محاسبه - ستون فیزیکی Oracle CALCULATION_STRATEGY_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.BASIS_TYPE_CODE IS 'نوع مبنای محاسبه - ستون فیزیکی Oracle BASIS_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.FIXED_AMOUNT IS 'مبلغ ثابت - ستون فیزیکی Oracle FIXED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.RATE_VALUE IS 'مقدار نرخ - ستون فیزیکی Oracle RATE_VALUE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.MIN_FEE_AMOUNT IS 'حداقل مبلغ کارمزد - ستون فیزیکی Oracle MIN_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.MAX_FEE_AMOUNT IS 'حداکثر مبلغ کارمزد - ستون فیزیکی Oracle MAX_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.RATE_PERIOD_CODE IS 'دوره نرخ - ستون فیزیکی Oracle RATE_PERIOD_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.DAY_COUNT_BASIS_CODE IS 'مبنای شمارش روز - ستون فیزیکی Oracle DAY_COUNT_BASIS_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.PRORATION_MODE_CODE IS 'روش سرشکن زمانی - ستون فیزیکی Oracle PRORATION_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.MIN_CHARGE_PERIOD_DAYS IS 'حداقل دوره قابل اخذ به روز - ستون فیزیکی Oracle MIN_CHARGE_PERIOD_DAYS.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.CURRENCY_CODE IS 'ارز قاعده - ستون فیزیکی Oracle CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.ROUNDING_MODE_CODE IS 'روش گرد کردن - ستون فیزیکی Oracle ROUNDING_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.ROUNDING_SCALE IS 'تعداد رقم اعشار - ستون فیزیکی Oracle ROUNDING_SCALE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.DESCRIPTION IS 'شرح قاعده - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_CALCULATION_RULE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 28
Primary Keys : 1
Unique Keys  : 1
Checks       : 4
Foreign Keys : 2
Physical FKs : 2
Logical FKs  : 0
Indexes      : 3
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:04 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/