PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_OVERRIDE_REQUEST]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_OVERRIDE_REQUEST]: Table name FEE_OVERRIDE_REQUEST appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_RULE]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_RULE]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_TX]: Referenced table FEE_TRANSACTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_OVERRIDE_REQUEST.foreignKeys.FK_FEE_OVERRIDE_TX]: Referenced table FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_OVERRIDE_REQUEST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: درخواست Override کارمزد
-- درخواست استثناء Amount/Rate/Waive/Rule همراه با Workflow تأیید؛ برگرفته از IFW OverrideRequest.
CREATE TABLE FEE.FEE_OVERRIDE_REQUEST -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  OVERRIDE_REQUEST_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_OVERRIDE_REQUEST.NEXTVAL NOT NULL,
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0),
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0),
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  OVERRIDE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  OVERRIDE_AMOUNT NUMBER(23,4),
  /*   0*/  OVERRIDE_RATE NUMBER(18,10),
  /*   0*/  OVERRIDE_RULE_ID NUMBER(19,0),
  /*   7*/  REASON_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   0*/  REASON_TEXT VARCHAR2(2000 CHAR),
  /*   0*/  REQUESTED_BY VARCHAR2(100 CHAR) NOT NULL,
  /*   2*/  REQUESTED_AT TIMESTAMP(6) NOT NULL,
  /*  16*/  STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'REQUESTED' NOT NULL,
  /*   4*/  APPROVED_BY VARCHAR2(100 CHAR),
  /*   3*/  APPROVED_AT TIMESTAMP(6),
  /*   0*/  APPLIED_AT TIMESTAMP(6),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_OVERRIDE_REQUEST PRIMARY KEY (OVERRIDE_REQUEST_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_OVERRIDE_REQUEST_OVERRIDE_REQUEST_ID ON FEE.FEE_OVERRIDE_REQUEST(OVERRIDE_REQUEST_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

CREATE INDEX FEE.IX_FEE_OVERRIDE_REQUEST_FEE_ARRANGEMENT_ID ON FEE.FEE_OVERRIDE_REQUEST(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_OVERRIDE_REQUEST_FEE_TRANSACTION_ID ON FEE.FEE_OVERRIDE_REQUEST(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_OVERRIDE_REQUEST_FEE_DEFINITION_VERSION_ID ON FEE.FEE_OVERRIDE_REQUEST(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_OVERRIDE_REQUEST_OVERRIDE_RULE_ID ON FEE.FEE_OVERRIDE_REQUEST(OVERRIDE_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_OVERRIDE_REQUEST ADD CONSTRAINT FK_FEE_OVERRIDE_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_OVERRIDE_REQUEST ADD CONSTRAINT FK_FEE_OVERRIDE_TX FOREIGN KEY (FEE_TRANSACTION_ID) REFERENCES FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID) ENABLE;

ALTER TABLE FEE.FEE_OVERRIDE_REQUEST ADD CONSTRAINT FK_FEE_OVERRIDE_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_OVERRIDE_REQUEST ADD CONSTRAINT FK_FEE_OVERRIDE_RULE FOREIGN KEY (OVERRIDE_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_OVERRIDE_REQUEST IS 'درخواست Override کارمزد';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.OVERRIDE_REQUEST_ID IS 'شناسه درخواست Override - ستون فیزیکی Oracle OVERRIDE_REQUEST_ID.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.OVERRIDE_TYPE_CODE IS 'نوع Override - ستون فیزیکی Oracle OVERRIDE_TYPE_CODE.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.OVERRIDE_AMOUNT IS 'مبلغ Override - ستون فیزیکی Oracle OVERRIDE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.OVERRIDE_RATE IS 'نرخ Override - ستون فیزیکی Oracle OVERRIDE_RATE.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.OVERRIDE_RULE_ID IS 'شناسه قاعده جایگزین - ستون فیزیکی Oracle OVERRIDE_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.REASON_CODE IS 'کد دلیل - ستون فیزیکی Oracle REASON_CODE.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.REASON_TEXT IS 'شرح دلیل - ستون فیزیکی Oracle REASON_TEXT.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.REQUESTED_BY IS 'درخواست‌کننده - ستون فیزیکی Oracle REQUESTED_BY.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.REQUESTED_AT IS 'زمان درخواست - ستون فیزیکی Oracle REQUESTED_AT.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.STATUS_CODE IS 'وضعیت درخواست - ستون فیزیکی Oracle STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.APPROVED_BY IS 'تأییدکننده - ستون فیزیکی Oracle APPROVED_BY.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.APPROVED_AT IS 'زمان تأیید - ستون فیزیکی Oracle APPROVED_AT.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.APPLIED_AT IS 'زمان اعمال - ستون فیزیکی Oracle APPLIED_AT.';

COMMENT ON COLUMN FEE.FEE_OVERRIDE_REQUEST.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 17
Primary Keys : 1
Unique Keys  : 0
Checks       : 0
Foreign Keys : 4
Physical FKs : 4
Logical FKs  : 0
Indexes      : 4
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:12 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/