PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_TRANSACTION]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION]: Table name FEE_TRANSACTION appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_TRANSACTION.columns.TRANSACTION_DATE]: Document type DATE differs from database metadata for TRANSACTION_DATE. Metadata frequencies: NUMBER [1]. Total occurrences: 1.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_TRANSACTION.columns.TRANSACTION_NO]: Document type VARCHAR2(100 CHAR) differs from database metadata for TRANSACTION_NO. Metadata frequencies: NUMBER [3]. Total occurrences: 3.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_ARR]: Referenced table FEE_ARRANGEMENT does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_ARR]: Referenced table FEE_ARRANGEMENT appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_CALC]: Referenced table FEE_CALCULATION_RULE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_CALC]: Referenced table FEE_CALCULATION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_INSTR]: Referenced table FEE_INSTRUCTION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_TRANSACTION.foreignKeys.FK_FEE_TX_INSTR]: Referenced table FEE_INSTRUCTION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_TRANSACTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: تراکنش کارمزد
-- رخداد مالی کارمزد شامل Calculated/Accrued/Applied/Converted/Collected amounts؛ هم‌راستا با BIAN Fee Transaction.
CREATE TABLE FEE.FEE_TRANSACTION -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  FEE_TRANSACTION_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_TRANSACTION.NEXTVAL NOT NULL,
  /*   3*/  TRANSACTION_NO VARCHAR2(100 CHAR) NOT NULL, -- W:TYPE
  /*   0*/  FEE_INSTRUCTION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  FEE_ARRANGEMENT_ID NUMBER(19,0),
  /*   0*/  CALCULATION_RULE_ID NUMBER(19,0),
  /*   1*/  TRANSACTION_DATE DATE NOT NULL, -- W:TYPE
  /*   0*/  CALCULATED_AMOUNT NUMBER(23,4),
  /*   0*/  GROSS_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  ACCRUED_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  APPLIED_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  CONVERTED_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  ADJUSTMENT_AMOUNT NUMBER(23,4),
  /*   0*/  NET_FEE_AMOUNT NUMBER(23,4),
  /*   0*/  COLLECTED_AMOUNT NUMBER(23,4),
  /*   0*/  FEE_CURRENCY_CODE VARCHAR2(3 CHAR) NOT NULL,
  /*   0*/  CONVERTED_CURRENCY_CODE VARCHAR2(3 CHAR),
  /*  16*/  STATUS_CODE VARCHAR2(30 CHAR) NOT NULL,
  /*   0*/  CALCULATED_AT TIMESTAMP(6),
  /*   0*/  APPLIED_AT TIMESTAMP(6),
  /*   0*/  COLLECTED_AT TIMESTAMP(6),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
CONSTRAINT PK_FEE_TRANSACTION PRIMARY KEY (FEE_TRANSACTION_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_TRANSACTION_FEE_TRANSACTION_ID ON FEE.FEE_TRANSACTION(FEE_TRANSACTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_TRANSACTION ADD CONSTRAINT UK_FEE_TRANSACTION_NO UNIQUE(TRANSACTION_NO)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_TRANSACTION_NO ON FEE.FEE_TRANSACTION(TRANSACTION_NO)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_TX_DATE ON FEE.FEE_TRANSACTION(TRANSACTION_DATE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TX_STATUS ON FEE.FEE_TRANSACTION(STATUS_CODE,TRANSACTION_DATE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TRANSACTION_FEE_INSTRUCTION_ID ON FEE.FEE_TRANSACTION(FEE_INSTRUCTION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TRANSACTION_FEE_DEFINITION_VERSION_ID ON FEE.FEE_TRANSACTION(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TRANSACTION_FEE_ARRANGEMENT_ID ON FEE.FEE_TRANSACTION(FEE_ARRANGEMENT_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

CREATE INDEX FEE.IX_FEE_TRANSACTION_CALCULATION_RULE_ID ON FEE.FEE_TRANSACTION(CALCULATION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_TRANSACTION ADD CONSTRAINT FK_FEE_TX_INSTR FOREIGN KEY (FEE_INSTRUCTION_ID) REFERENCES FEE.FEE_INSTRUCTION(FEE_INSTRUCTION_ID) ENABLE;

ALTER TABLE FEE.FEE_TRANSACTION ADD CONSTRAINT FK_FEE_TX_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

ALTER TABLE FEE.FEE_TRANSACTION ADD CONSTRAINT FK_FEE_TX_ARR FOREIGN KEY (FEE_ARRANGEMENT_ID) REFERENCES FEE.FEE_ARRANGEMENT(FEE_ARRANGEMENT_ID) ENABLE;

ALTER TABLE FEE.FEE_TRANSACTION ADD CONSTRAINT FK_FEE_TX_CALC FOREIGN KEY (CALCULATION_RULE_ID) REFERENCES FEE.FEE_CALCULATION_RULE(CALCULATION_RULE_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_TRANSACTION IS 'تراکنش کارمزد';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.FEE_TRANSACTION_ID IS 'شناسه تراکنش کارمزد - ستون فیزیکی Oracle FEE_TRANSACTION_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.TRANSACTION_NO IS 'شماره تراکنش کارمزد - ستون فیزیکی Oracle TRANSACTION_NO.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.FEE_INSTRUCTION_ID IS 'شناسه دستور کارمزد - ستون فیزیکی Oracle FEE_INSTRUCTION_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.FEE_ARRANGEMENT_ID IS 'شناسه ترتیب کارمزد - ستون فیزیکی Oracle FEE_ARRANGEMENT_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CALCULATION_RULE_ID IS 'شناسه قاعده محاسبه اعمال‌شده - ستون فیزیکی Oracle CALCULATION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.TRANSACTION_DATE IS 'تاریخ تراکنش کارمزد - ستون فیزیکی Oracle TRANSACTION_DATE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CALCULATED_AMOUNT IS 'مبلغ محاسبه‌شده - ستون فیزیکی Oracle CALCULATED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.GROSS_FEE_AMOUNT IS 'مبلغ ناخالص کارمزد - ستون فیزیکی Oracle GROSS_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.ACCRUED_FEE_AMOUNT IS 'مبلغ تعهدشده کارمزد - ستون فیزیکی Oracle ACCRUED_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.APPLIED_FEE_AMOUNT IS 'مبلغ اعمال‌شده کارمزد - ستون فیزیکی Oracle APPLIED_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CONVERTED_FEE_AMOUNT IS 'مبلغ تبدیل‌شده کارمزد - ستون فیزیکی Oracle CONVERTED_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.ADJUSTMENT_AMOUNT IS 'مبلغ کل تعدیلات - ستون فیزیکی Oracle ADJUSTMENT_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.NET_FEE_AMOUNT IS 'مبلغ خالص کارمزد - ستون فیزیکی Oracle NET_FEE_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.COLLECTED_AMOUNT IS 'مبلغ وصول‌شده - ستون فیزیکی Oracle COLLECTED_AMOUNT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.FEE_CURRENCY_CODE IS 'ارز کارمزد - ستون فیزیکی Oracle FEE_CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CONVERTED_CURRENCY_CODE IS 'ارز مبلغ تبدیل‌شده - ستون فیزیکی Oracle CONVERTED_CURRENCY_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.STATUS_CODE IS 'وضعیت تراکنش - ستون فیزیکی Oracle STATUS_CODE.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CALCULATED_AT IS 'زمان محاسبه - ستون فیزیکی Oracle CALCULATED_AT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.APPLIED_AT IS 'زمان اعمال - ستون فیزیکی Oracle APPLIED_AT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.COLLECTED_AT IS 'زمان وصول - ستون فیزیکی Oracle COLLECTED_AT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_TRANSACTION.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 23
Primary Keys : 1
Unique Keys  : 1
Checks       : 0
Foreign Keys : 4
Physical FKs : 4
Logical FKs  : 0
Indexes      : 6
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:10 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/