PROMPT ==============================================================
PROMPT SchemaForge Validation Findings
PROMPT ==============================================================
PROMPT [WARNING] SCHEMA_NOT_FOUND [tables.FEE_COLLECTION_RULE]: Schema FEE does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_COLLECTION_RULE]: Table name FEE_COLLECTION_RULE appears to be singular. Table names should be plural.
PROMPT [WARNING] METADATA_DATATYPE_MISMATCH [tables.FEE_COLLECTION_RULE.columns.FAILURE_ACTION_CODE]: Document type VARCHAR2(50 CHAR) differs from database metadata for FAILURE_ACTION_CODE. Metadata frequencies: VARCHAR2(30) [2]. Total occurrences: 2.
PROMPT [WARNING] FK_TABLE_NOT_FOUND [tables.FEE_COLLECTION_RULE.foreignKeys.FK_FEE_COLLECTION_DEFV]: Referenced table FEE_DEFINITION_VERSION does not exist in database metadata.
PROMPT [WARNING] TABLE_NAME_NOT_PLURAL [tables.FEE_COLLECTION_RULE.foreignKeys.FK_FEE_COLLECTION_DEFV]: Referenced table FEE_DEFINITION_VERSION appears to be singular. Table names should be plural.
PROMPT ==============================================================

PROMPT ==============================================================
PROMPT SchemaForge Offline Oracle DDL
PROMPT Source File : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
PROMPT Schema      : FEE
PROMPT ==============================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT [INFRASTRUCTURE TEMPLATE][ORACLE] DBA review required; values are placeholders.
-- Optional permanent tablespace for application data:
-- CREATE TABLESPACE TS_FEE
--   DATAFILE '<DATAFILE_PATH>/ts_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- Optional dedicated index tablespace:
-- CREATE TABLESPACE ITS_FEE
--   DATAFILE '<DATAFILE_PATH>/its_fee_01.dbf'
--   SIZE <INITIAL_SIZE> AUTOEXTEND ON NEXT <NEXT_SIZE> MAXSIZE <MAX_SIZE>
--   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT [SCHEMA BOOTSTRAP] Oracle schema FEE is created by CREATE USER and must be provisioned by a DBA.
-- Secure provisioning template; intentionally not executed by SchemaForge:
-- CREATE USER FEE IDENTIFIED BY "<SECURE_PASSWORD>"
--   DEFAULT TABLESPACE TS_FEE TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON TS_FEE
--   QUOTA UNLIMITED ON ITS_FEE;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
--       CREATE PROCEDURE, CREATE TRIGGER TO FEE;

CREATE SEQUENCE FEE.SEQ_FEE_COLLECTION_RULE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

-- Persian table name: قاعده وصول کارمزد
-- قاعده اجرایی وصول/پرداخت کارمزد؛ Platform Extension در کنار BIAN Fee Payment Method semantics.
CREATE TABLE FEE.FEE_COLLECTION_RULE -- W:SCHEMA|TABLE-PLURAL
(
  /*   0*/  COLLECTION_RULE_ID NUMBER(19,0) DEFAULT FEE.SEQ_FEE_COLLECTION_RULE.NEXTVAL NOT NULL,
  /*   0*/  FEE_DEFINITION_VERSION_ID NUMBER(19,0) NOT NULL,
  /*   0*/  RULE_CODE VARCHAR2(80 CHAR) NOT NULL,
  /*   0*/  PAYMENT_METHOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  /*   0*/  COLLECTION_MODE_CODE VARCHAR2(50 CHAR),
  /*   0*/  CHARGE_ACCOUNT_ROLE_CODE VARCHAR2(50 CHAR),
  /*   0*/  REFERENCE_REQUIRED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   0*/  PARTIAL_COLLECTION_ALLOWED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  /*   2*/  FAILURE_ACTION_CODE VARCHAR2(50 CHAR), -- W:TYPE
  /*   6*/  EFFECTIVE_FROM DATE,
  /*   6*/  EFFECTIVE_TO DATE,
  /* 181*/  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  /* 238*/  DESCRIPTION VARCHAR2(1000 CHAR),
  /* 129*/  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  /* 2858*/  CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
  /* 122*/  UPDATED_AT TIMESTAMP(6),
  /* 118*/  UPDATED_BY VARCHAR2(100 CHAR),
  /* 273*/  RECORD_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,
CONSTRAINT PK_FEE_COLLECTION_RULE PRIMARY KEY (COLLECTION_RULE_ID)
USING INDEX (CREATE UNIQUE INDEX FEE.PK_FEE_COLLECTION_RULE_COLLECTION_RULE_ID ON FEE.FEE_COLLECTION_RULE(COLLECTION_RULE_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE)
)
/*
-- ORACLE TABLE PHYSICAL OPTIONS
PCTFREE 10
INITRANS 1
-- PCTUSED intentionally omitted: with ASSM it is ignored; review only for MSSM tablespaces.
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: redo/recovery policy must come from source/profile.
NOPARALLEL
-- [SOURCE PHYSICAL REVIEW][ORACLE] SEGMENT CREATION is left unspecified so the database/session DEFERRED_SEGMENT_CREATION policy is not overridden.
SEGMENT CREATION <DEFERRED_OR_IMMEDIATE>
*/ TABLESPACE TS_FEE;

ALTER TABLE FEE.FEE_COLLECTION_RULE ADD CONSTRAINT CK_FEE_COLLECTION_REF CHECK(REFERENCE_REQUIRED_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_COLLECTION_RULE ADD CONSTRAINT CK_FEE_COLLECTION_PART CHECK(PARTIAL_COLLECTION_ALLOWED_FLAG IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_COLLECTION_RULE ADD CONSTRAINT CK_FEE_COLLECTION_ACTIVE CHECK(IS_ACTIVE IN ('Y','N')) ENABLE;

ALTER TABLE FEE.FEE_COLLECTION_RULE ADD CONSTRAINT UK_FEE_COLLECTION_CODE UNIQUE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
 USING INDEX (CREATE UNIQUE INDEX FEE.UK_FEE_COLLECTION_CODE ON FEE.FEE_COLLECTION_RULE(FEE_DEFINITION_VERSION_ID,RULE_CODE)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE);

CREATE INDEX FEE.IX_FEE_COLLECTION_RULE_FEE_DEFINITION_VERSION_ID ON FEE.FEE_COLLECTION_RULE(FEE_DEFINITION_VERSION_ID)
/*
-- ORACLE INDEX PHYSICAL OPTIONS
PCTFREE 10
INITRANS 2
NOCOMPRESS
-- LOGGING/NOLOGGING intentionally unspecified: Oracle index logging is independent of the base table.
NOPARALLEL
*/ TABLESPACE ITS_FEE;

ALTER TABLE FEE.FEE_COLLECTION_RULE ADD CONSTRAINT FK_FEE_COLLECTION_DEFV FOREIGN KEY (FEE_DEFINITION_VERSION_ID) REFERENCES FEE.FEE_DEFINITION_VERSION(FEE_DEFINITION_VERSION_ID) ENABLE;

COMMENT ON TABLE FEE.FEE_COLLECTION_RULE IS 'قاعده وصول کارمزد';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.COLLECTION_RULE_ID IS 'شناسه قاعده وصول - ستون فیزیکی Oracle COLLECTION_RULE_ID.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.FEE_DEFINITION_VERSION_ID IS 'شناسه نسخه تعریف کارمزد - ستون فیزیکی Oracle FEE_DEFINITION_VERSION_ID.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.RULE_CODE IS 'کد قاعده وصول - ستون فیزیکی Oracle RULE_CODE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.PAYMENT_METHOD_CODE IS 'روش پرداخت یا وصول - ستون فیزیکی Oracle PAYMENT_METHOD_CODE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.COLLECTION_MODE_CODE IS 'حالت وصول - ستون فیزیکی Oracle COLLECTION_MODE_CODE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.CHARGE_ACCOUNT_ROLE_CODE IS 'نقش حساب برداشت - ستون فیزیکی Oracle CHARGE_ACCOUNT_ROLE_CODE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.REFERENCE_REQUIRED_FLAG IS 'شماره مرجع الزامی است - ستون فیزیکی Oracle REFERENCE_REQUIRED_FLAG.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.PARTIAL_COLLECTION_ALLOWED_FLAG IS 'وصول جزئی مجاز است - ستون فیزیکی Oracle PARTIAL_COLLECTION_ALLOWED_FLAG.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.FAILURE_ACTION_CODE IS 'اقدام در شکست وصول - ستون فیزیکی Oracle FAILURE_ACTION_CODE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار - ستون فیزیکی Oracle EFFECTIVE_FROM.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار - ستون فیزیکی Oracle EFFECTIVE_TO.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.IS_ACTIVE IS 'فعال است - ستون فیزیکی Oracle IS_ACTIVE.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.DESCRIPTION IS 'شرح - ستون فیزیکی Oracle DESCRIPTION.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.CREATED_AT IS 'زمان ایجاد - ستون فیزیکی Oracle CREATED_AT.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.CREATED_BY IS 'ایجادکننده - ستون فیزیکی Oracle CREATED_BY.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.UPDATED_AT IS 'زمان آخرین تغییر - ستون فیزیکی Oracle UPDATED_AT.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.UPDATED_BY IS 'آخرین تغییر دهنده - ستون فیزیکی Oracle UPDATED_BY.';

COMMENT ON COLUMN FEE.FEE_COLLECTION_RULE.RECORD_VERSION IS 'نسخه رکورد - ستون فیزیکی Oracle RECORD_VERSION.';

/*
SchemaForge Object Summary
Schemas      : 1
Sequences    : 1
Tables       : 1
Columns      : 18
Primary Keys : 1
Unique Keys  : 1
Checks       : 3
Foreign Keys : 1
Physical FKs : 1
Logical FKs  : 0
Indexes      : 1
*/

/*
Generated By : SchemaForge
Generated On : 2026-08-29 14:25:06 +03:30
Source File  : FEE-Target-DataModel-Baseline-1.0-EA-Oracle.xml
Dialect      : Oracle
*/