-- Phase 6: Analytics and Recommendation reference data.
-- Generated from the supplied Party/Customer reference model.
-- REF_CUSTOMER_SEGMENT is intentionally NOT created in CIF; DPS.REF_CUSTOMER_SEGMENT_CODE remains source of truth.
-- Target schema CIF

PROMPT Creating CIF.REF_METRIC
CREATE TABLE CIF.REF_METRIC (
  METRIC_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_METRIC PRIMARY KEY (METRIC_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_METRIC_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_METRIC_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_METRIC_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_METRIC_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_METRIC_UNIT
CREATE TABLE CIF.REF_METRIC_UNIT (
  METRIC_UNIT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_METRIC_UNIT PRIMARY KEY (METRIC_UNIT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_METRIC_UNIT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_METRIC_UNIT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_METRIC_UNIT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_METRIC_UNIT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_MODEL
CREATE TABLE CIF.REF_MODEL (
  MODEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_MODEL PRIMARY KEY (MODEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_MODEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_MODEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_MODEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_MODEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RECOMMENDATION_STATUS
CREATE TABLE CIF.REF_RECOMMENDATION_STATUS (
  RECOMMENDATION_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RECOMMENDATION_STATUS PRIMARY KEY (RECOMMENDATION_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RECOMMENDATION_STATUS_01 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_RECOMMENDATION_STATUS_02 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RECOMMENDATION_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RECOMMENDATION_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RECOMMENDATION_TYPE
CREATE TABLE CIF.REF_RECOMMENDATION_TYPE (
  RECOMMENDATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RECOMMENDATION_TYPE PRIMARY KEY (RECOMMENDATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RECOMMENDATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RECOMMENDATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RECOMMENDATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RECOMMENDATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCORE_BAND
CREATE TABLE CIF.REF_SCORE_BAND (
  SCORE_BAND_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCORE_BAND PRIMARY KEY (SCORE_BAND_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCORE_BAND_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCORE_BAND_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCORE_BAND_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCORE_BAND_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCORE_TYPE
CREATE TABLE CIF.REF_SCORE_TYPE (
  SCORE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCORE_TYPE PRIMARY KEY (SCORE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCORE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCORE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCORE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCORE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;


-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_METRIC.METRIC_CODE IS 'کد شاخص';
COMMENT ON COLUMN CIF.REF_METRIC.NAME_FA IS 'عنوان فارسی شاخص تحلیلی مشتری';
COMMENT ON COLUMN CIF.REF_METRIC.NAME_EN IS 'عنوان انگلیسی شاخص تحلیلی مشتری';
COMMENT ON COLUMN CIF.REF_METRIC.DESCRIPTION_FA IS 'توضیحات فارسی شاخص تحلیلی مشتری';
COMMENT ON COLUMN CIF.REF_METRIC.SORT_ORDER IS 'ترتیب نمایش شاخص تحلیلی مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_METRIC.IS_ACTIVE IS 'نشانگر فعال بودن شاخص تحلیلی مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_METRIC.PARENT_CODE IS 'کد والد شاخص تحلیلی مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_METRIC.VALID_FROM IS 'تاریخ شروع اعتبار شاخص تحلیلی مشتری';
COMMENT ON COLUMN CIF.REF_METRIC.VALID_TO IS 'تاریخ پایان اعتبار شاخص تحلیلی مشتری';
COMMENT ON COLUMN CIF.REF_METRIC.RECORD_VERSION IS 'شماره نسخه رکورد شاخص تحلیلی مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.METRIC_UNIT_CODE IS 'کد واحد اندازه‌گیری';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.NAME_FA IS 'عنوان فارسی واحد اندازه‌گیری شاخص';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.NAME_EN IS 'عنوان انگلیسی واحد اندازه‌گیری شاخص';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.DESCRIPTION_FA IS 'توضیحات فارسی واحد اندازه‌گیری شاخص';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.SORT_ORDER IS 'ترتیب نمایش واحد اندازه‌گیری شاخص در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.IS_ACTIVE IS 'نشانگر فعال بودن واحد اندازه‌گیری شاخص؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.PARENT_CODE IS 'کد والد واحد اندازه‌گیری شاخص در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.VALID_FROM IS 'تاریخ شروع اعتبار واحد اندازه‌گیری شاخص';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.VALID_TO IS 'تاریخ پایان اعتبار واحد اندازه‌گیری شاخص';
COMMENT ON COLUMN CIF.REF_METRIC_UNIT.RECORD_VERSION IS 'شماره نسخه رکورد واحد اندازه‌گیری شاخص برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_MODEL.MODEL_CODE IS 'کد مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.NAME_FA IS 'عنوان فارسی مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.NAME_EN IS 'عنوان انگلیسی مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.DESCRIPTION_FA IS 'توضیحات فارسی مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.SORT_ORDER IS 'ترتیب نمایش مدل تحلیلی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_MODEL.IS_ACTIVE IS 'نشانگر فعال بودن مدل تحلیلی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_MODEL.PARENT_CODE IS 'کد والد مدل تحلیلی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_MODEL.VALID_FROM IS 'تاریخ شروع اعتبار مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.VALID_TO IS 'تاریخ پایان اعتبار مدل تحلیلی';
COMMENT ON COLUMN CIF.REF_MODEL.RECORD_VERSION IS 'شماره نسخه رکورد مدل تحلیلی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.RECOMMENDATION_STATUS_CODE IS 'کد وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.NAME_FA IS 'عنوان فارسی وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت پیشنهاد در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت پیشنهاد؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.PARENT_CODE IS 'کد والد وضعیت پیشنهاد در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت پیشنهاد برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.RECOMMENDATION_TYPE_CODE IS 'کد نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.NAME_FA IS 'عنوان فارسی نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.NAME_EN IS 'عنوان انگلیسی نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع پیشنهاد در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع پیشنهاد؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.PARENT_CODE IS 'کد والد نوع پیشنهاد در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع پیشنهاد';
COMMENT ON COLUMN CIF.REF_RECOMMENDATION_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع پیشنهاد برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.SCORE_BAND_CODE IS 'کد طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.NAME_FA IS 'عنوان فارسی طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.NAME_EN IS 'عنوان انگلیسی طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.DESCRIPTION_FA IS 'توضیحات فارسی طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.SORT_ORDER IS 'ترتیب نمایش طبقه امتیاز در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.IS_ACTIVE IS 'نشانگر فعال بودن طبقه امتیاز؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.PARENT_CODE IS 'کد والد طبقه امتیاز در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.VALID_FROM IS 'تاریخ شروع اعتبار طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.VALID_TO IS 'تاریخ پایان اعتبار طبقه امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_BAND.RECORD_VERSION IS 'شماره نسخه رکورد طبقه امتیاز برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.SCORE_TYPE_CODE IS 'کد نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.NAME_FA IS 'عنوان فارسی نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.NAME_EN IS 'عنوان انگلیسی نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع امتیاز در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع امتیاز؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.PARENT_CODE IS 'کد والد نوع امتیاز در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع امتیاز';
COMMENT ON COLUMN CIF.REF_SCORE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع امتیاز برای کنترل هم‌زمانی';
