-- Phase 6: Analytics and Recommendation reference data.
-- Generated from the supplied Party/Customer reference model.
-- REF_CUSTOMER_SEGMENT is intentionally NOT created in CIF; DPS.REF_CUSTOMER_SEGMENT_CODE remains source of truth.
-- Target schema CIF

PROMPT Creating CIF.REF_METRIC
CREATE TABLE CIF.REF_METRIC (
  METRIC_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_METRIC PRIMARY KEY (METRIC_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_METRIC_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_METRIC_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_METRIC_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_METRIC_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_METRIC_UNIT
CREATE TABLE CIF.REF_METRIC_UNIT (
  METRIC_UNIT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_METRIC_UNIT PRIMARY KEY (METRIC_UNIT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_METRIC_UNIT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_METRIC_UNIT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_METRIC_UNIT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_METRIC_UNIT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_MODEL
CREATE TABLE CIF.REF_MODEL (
  MODEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_MODEL PRIMARY KEY (MODEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_MODEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_MODEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_MODEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_MODEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RECOMMENDATION_STATUS
CREATE TABLE CIF.REF_RECOMMENDATION_STATUS (
  RECOMMENDATION_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RECOMMENDATION_STATUS PRIMARY KEY (RECOMMENDATION_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RECOMMENDATION_STATUS_01 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_RECOMMENDATION_STATUS_02 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RECOMMENDATION_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RECOMMENDATION_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RECOMMENDATION_TYPE
CREATE TABLE CIF.REF_RECOMMENDATION_TYPE (
  RECOMMENDATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RECOMMENDATION_TYPE PRIMARY KEY (RECOMMENDATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RECOMMENDATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RECOMMENDATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RECOMMENDATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RECOMMENDATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCORE_BAND
CREATE TABLE CIF.REF_SCORE_BAND (
  SCORE_BAND_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCORE_BAND PRIMARY KEY (SCORE_BAND_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCORE_BAND_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCORE_BAND_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCORE_BAND_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCORE_BAND_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCORE_TYPE
CREATE TABLE CIF.REF_SCORE_TYPE (
  SCORE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCORE_TYPE PRIMARY KEY (SCORE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCORE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCORE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCORE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCORE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

