-- Phase 6 seed data
-- Source codes and English values are preserved; Persian captions were reviewed manually.

MERGE INTO CIF.REF_METRIC T
USING (SELECT 'MONTHLY_TURNOVER' AS METRIC_CODE, 'گردش ماهانه' AS NAME_FA, 'Monthly Turnover' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_CODE=S.METRIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_METRIC T
USING (SELECT 'PRODUCT_COUNT' AS METRIC_CODE, 'تعداد محصولات' AS NAME_FA, 'Product Count' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_CODE=S.METRIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_METRIC T
USING (SELECT 'COMPLAINT_COUNT' AS METRIC_CODE, 'تعداد شکایت‌ها' AS NAME_FA, 'Complaint Count' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_CODE=S.METRIC_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_METRIC_UNIT T
USING (SELECT 'IRR' AS METRIC_UNIT_CODE, 'ریال ایران' AS NAME_FA, 'Irr' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_UNIT_CODE=S.METRIC_UNIT_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_UNIT_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_UNIT_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_METRIC_UNIT T
USING (SELECT 'COUNT' AS METRIC_UNIT_CODE, 'تعداد' AS NAME_FA, 'Count' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_UNIT_CODE=S.METRIC_UNIT_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_UNIT_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_UNIT_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_METRIC_UNIT T
USING (SELECT 'PERCENT' AS METRIC_UNIT_CODE, 'درصد' AS NAME_FA, 'Percent' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.METRIC_UNIT_CODE=S.METRIC_UNIT_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (METRIC_UNIT_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.METRIC_UNIT_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_MODEL T
USING (SELECT 'KYC_RISK_V1' AS MODEL_CODE, 'مدل ریسک KYC نسخه ۱' AS NAME_FA, 'Kyc Risk V1' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.MODEL_CODE=S.MODEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (MODEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.MODEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_MODEL T
USING (SELECT 'VALUE_SCORE_V1' AS MODEL_CODE, 'مدل امتیاز ارزش مشتری نسخه ۱' AS NAME_FA, 'Value Score V1' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.MODEL_CODE=S.MODEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (MODEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.MODEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_MODEL T
USING (SELECT 'SEGMENT_V1' AS MODEL_CODE, 'مدل بخش‌بندی مشتری نسخه ۱' AS NAME_FA, 'Segment V1' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.MODEL_CODE=S.MODEL_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (MODEL_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.MODEL_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_STATUS T
USING (SELECT 'NEW' AS RECOMMENDATION_STATUS_CODE, 'جدید' AS NAME_FA, 'New' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_STATUS_CODE=S.RECOMMENDATION_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_STATUS T
USING (SELECT 'PRESENTED' AS RECOMMENDATION_STATUS_CODE, 'ارائه‌شده' AS NAME_FA, 'Presented' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_STATUS_CODE=S.RECOMMENDATION_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_STATUS T
USING (SELECT 'ACCEPTED' AS RECOMMENDATION_STATUS_CODE, 'پذیرفته‌شده' AS NAME_FA, 'Accepted' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_STATUS_CODE=S.RECOMMENDATION_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_STATUS T
USING (SELECT 'REJECTED' AS RECOMMENDATION_STATUS_CODE, 'ردشده' AS NAME_FA, 'Rejected' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_STATUS_CODE=S.RECOMMENDATION_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_STATUS T
USING (SELECT 'EXPIRED' AS RECOMMENDATION_STATUS_CODE, 'منقضی' AS NAME_FA, 'Expired' AS NAME_EN, NULL AS DESCRIPTION_FA, 50 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_STATUS_CODE=S.RECOMMENDATION_STATUS_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_STATUS_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_STATUS_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_TYPE T
USING (SELECT 'PRODUCT_OFFER' AS RECOMMENDATION_TYPE_CODE, 'پیشنهاد محصول یا خدمت' AS NAME_FA, 'Product Offer' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_TYPE_CODE=S.RECOMMENDATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_TYPE T
USING (SELECT 'NEXT_BEST_ACTION' AS RECOMMENDATION_TYPE_CODE, 'اقدام بعدی پیشنهادی' AS NAME_FA, 'Next Best Action' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_TYPE_CODE=S.RECOMMENDATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_RECOMMENDATION_TYPE T
USING (SELECT 'RETENTION' AS RECOMMENDATION_TYPE_CODE, 'حفظ مشتری' AS NAME_FA, 'Retention' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.RECOMMENDATION_TYPE_CODE=S.RECOMMENDATION_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (RECOMMENDATION_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.RECOMMENDATION_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_BAND T
USING (SELECT 'A' AS SCORE_BAND_CODE, 'طبقه A' AS NAME_FA, 'A' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_BAND_CODE=S.SCORE_BAND_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_BAND_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_BAND_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_BAND T
USING (SELECT 'B' AS SCORE_BAND_CODE, 'طبقه B' AS NAME_FA, 'B' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_BAND_CODE=S.SCORE_BAND_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_BAND_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_BAND_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_BAND T
USING (SELECT 'C' AS SCORE_BAND_CODE, 'طبقه C' AS NAME_FA, 'C' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_BAND_CODE=S.SCORE_BAND_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_BAND_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_BAND_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_BAND T
USING (SELECT 'D' AS SCORE_BAND_CODE, 'طبقه D' AS NAME_FA, 'D' AS NAME_EN, NULL AS DESCRIPTION_FA, 40 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_BAND_CODE=S.SCORE_BAND_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_BAND_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_BAND_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_TYPE T
USING (SELECT 'CUSTOMER_VALUE' AS SCORE_TYPE_CODE, 'ارزش مشتری' AS NAME_FA, 'Customer Value' AS NAME_EN, NULL AS DESCRIPTION_FA, 10 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_TYPE_CODE=S.SCORE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_TYPE T
USING (SELECT 'CHURN_PROPENSITY' AS SCORE_TYPE_CODE, 'احتمال ریزش مشتری' AS NAME_FA, 'Churn Propensity' AS NAME_EN, NULL AS DESCRIPTION_FA, 20 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_TYPE_CODE=S.SCORE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

MERGE INTO CIF.REF_SCORE_TYPE T
USING (SELECT 'CREDIT_AFFINITY' AS SCORE_TYPE_CODE, 'گرایش اعتباری' AS NAME_FA, 'Credit Affinity' AS NAME_EN, NULL AS DESCRIPTION_FA, 30 AS SORT_ORDER, 1 AS IS_ACTIVE, NULL AS PARENT_CODE, NULL AS VALID_FROM, NULL AS VALID_TO, 1 AS RECORD_VERSION FROM DUAL) S
ON (T.SCORE_TYPE_CODE=S.SCORE_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET T.NAME_FA=S.NAME_FA, T.NAME_EN=S.NAME_EN, T.DESCRIPTION_FA=S.DESCRIPTION_FA, T.SORT_ORDER=S.SORT_ORDER, T.IS_ACTIVE=S.IS_ACTIVE, T.PARENT_CODE=S.PARENT_CODE, T.VALID_FROM=S.VALID_FROM, T.VALID_TO=S.VALID_TO, T.RECORD_VERSION=S.RECORD_VERSION
WHEN NOT MATCHED THEN INSERT (SCORE_TYPE_CODE, NAME_FA, NAME_EN, DESCRIPTION_FA, SORT_ORDER, IS_ACTIVE, PARENT_CODE, VALID_FROM, VALID_TO, RECORD_VERSION)
VALUES (S.SCORE_TYPE_CODE, S.NAME_FA, S.NAME_EN, S.DESCRIPTION_FA, S.SORT_ORDER, S.IS_ACTIVE, S.PARENT_CODE, S.VALID_FROM, S.VALID_TO, S.RECORD_VERSION);

COMMIT;
