PROMPT Verifying Analytics and Recommendation CIF reference tables
SELECT 'REF_METRIC' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_METRIC;
SELECT 'REF_METRIC_UNIT' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_METRIC_UNIT;
SELECT 'REF_MODEL' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_MODEL;
SELECT 'REF_RECOMMENDATION_STATUS' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_RECOMMENDATION_STATUS;
SELECT 'REF_RECOMMENDATION_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_RECOMMENDATION_TYPE;
SELECT 'REF_SCORE_BAND' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_SCORE_BAND;
SELECT 'REF_SCORE_TYPE' TABLE_NAME, COUNT(*) ROW_COUNT FROM CIF.REF_SCORE_TYPE;
SELECT * FROM CIF.REF_METRIC WHERE METRIC_CODE IN ('MONTHLY_TURNOVER','PRODUCT_COUNT','COMPLAINT_COUNT');
SELECT * FROM CIF.REF_METRIC_UNIT WHERE METRIC_UNIT_CODE IN ('IRR','COUNT','PERCENT');
SELECT * FROM CIF.REF_MODEL WHERE MODEL_CODE IN ('KYC_RISK_V1','VALUE_SCORE_V1','SEGMENT_V1');
SELECT * FROM CIF.REF_RECOMMENDATION_STATUS WHERE RECOMMENDATION_STATUS_CODE IN ('NEW','ACCEPTED','EXPIRED');
SELECT * FROM CIF.REF_RECOMMENDATION_TYPE WHERE RECOMMENDATION_TYPE_CODE IN ('PRODUCT_OFFER','NEXT_BEST_ACTION','RETENTION');
SELECT * FROM CIF.REF_SCORE_TYPE WHERE SCORE_TYPE_CODE IN ('CUSTOMER_VALUE','CHURN_PROPENSITY','CREDIT_AFFINITY');
PROMPT Customer segment is reused from DPS.REF_CUSTOMER_SEGMENT_CODE (no CIF duplicate).
SELECT CODE, NAME_FA, NAME_EN, IS_ACTIVE, VERSION_NO, IS_CURRENT FROM DPS.REF_CUSTOMER_SEGMENT_CODE WHERE IS_CURRENT = 1 ORDER BY CODE;
