-- Core Banking Prototype 0.11.0 - DPS2 Phase 11G DB verifier
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE ok(x VARCHAR2) IS BEGIN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||x); END;
  PROCEDURE bad(x VARCHAR2) IS BEGIN f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||x); END;
  PROCEDURE tab(x VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=x; IF v=1 THEN ok(x||' exists'); ELSE bad(x||' missing'); END IF; END;
  PROCEDURE col(t VARCHAR2,c VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=t AND COLUMN_NAME=c; IF v=1 THEN ok(t||'.'||c||' exists'); ELSE bad(t||'.'||c||' missing'); END IF; END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('============================================================');DBMS_OUTPUT.PUT_LINE('DPS2 Phase 11G - Profit / Interest Processing DB Verifier');DBMS_OUTPUT.PUT_LINE('============================================================');
  tab('DEPOSIT_PROFIT_CONTRACT');tab('DEPOSIT_PROFIT_ACCRUAL');tab('DEPOSIT_PROFIT_POSTING');tab('DEPOSIT_ACCOUNT_BALANCE');tab('DEPOSIT_SUBLEDGER_ENTRY');
  col('DEPOSIT_PROFIT_CONTRACT','ANNUAL_RATE');col('DEPOSIT_PROFIT_CONTRACT','LAST_PAYMENT_DATE');col('DEPOSIT_PROFIT_CONTRACT','SOURCE_OPENING_PROFIT_INSTRUCTION_ID');
  col('DEPOSIT_PROFIT_ACCRUAL','ACCRUAL_FROM_DATE');col('DEPOSIT_PROFIT_ACCRUAL','ACCRUAL_TO_DATE');col('DEPOSIT_PROFIT_ACCRUAL','DAY_COUNT');col('DEPOSIT_PROFIT_ACCRUAL','BASIS_AMOUNT');col('DEPOSIT_PROFIT_ACCRUAL','ANNUAL_RATE');col('DEPOSIT_PROFIT_ACCRUAL','ACCRUED_AMOUNT');col('DEPOSIT_PROFIT_ACCRUAL','DAY_COUNT_BASIS_CODE');col('DEPOSIT_PROFIT_ACCRUAL','CALCULATION_METHOD_CODE');col('DEPOSIT_PROFIT_ACCRUAL','PROFIT_POSTING_ID');
  col('DEPOSIT_PROFIT_POSTING','POSTING_DATE');col('DEPOSIT_PROFIT_POSTING','DESTINATION_CODE');col('DEPOSIT_PROFIT_POSTING','SUBLEDGER_ENTRY_ID');
  SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_PROFIT_ACCRUAL' AND COLUMN_NAME='PROFIT_POSTING_ID';IF v=1 THEN ok('accrual posting trace column exists');ELSE bad('accrual posting trace column exists');END IF;
  SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_PROFIT_ACCRUAL' AND COLUMN_NAME='PROFIT_PERIOD_ID' AND NULLABLE='N';IF v=0 THEN ok('legacy PROFIT_PERIOD_ID does not block canonical accrual inserts');ELSE bad('legacy PROFIT_PERIOD_ID still blocks canonical accrual inserts');END IF;
  SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_PROFIT_ACCRUAL' AND COLUMN_NAME IN ('ACCRUAL_DATE','BALANCE_BASIS_AMOUNT','RATE_VALUE','DAY_FRACTION','ACCRUAL_AMOUNT','ACCRUAL_STATUS_CODE','CREATED_BY');
  IF v=0 THEN
    ok('canonical-only accrual schema does not require legacy projection');
  ELSIF v=7 THEN
    EXECUTE IMMEDIATE q'~SELECT COUNT(*) FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_CONTRACT_ID IS NOT NULL AND (A.ACCRUAL_DATE IS NULL OR A.BALANCE_BASIS_AMOUNT IS NULL OR A.RATE_VALUE IS NULL OR A.DAY_FRACTION IS NULL OR A.ACCRUAL_AMOUNT IS NULL OR A.ACCRUAL_STATUS_CODE IS NULL OR A.CREATED_BY IS NULL OR A.ACCRUAL_DATE<>A.ACCRUAL_TO_DATE OR A.BALANCE_BASIS_AMOUNT<>A.BASIS_AMOUNT OR A.RATE_VALUE<>ROUND(A.ANNUAL_RATE,6) OR ABS(A.DAY_FRACTION-(A.DAY_COUNT/CASE WHEN A.DAY_COUNT_BASIS_CODE='ACT_360' THEN 360 ELSE 365 END))>0.0000000001 OR A.ACCRUAL_AMOUNT<>A.ACCRUED_AMOUNT OR (A.STATUS_CODE='ACCRUED' AND A.ACCRUAL_STATUS_CODE<>'CALCULATED') OR (A.STATUS_CODE='POSTED' AND A.ACCRUAL_STATUS_CODE<>'POSTED') OR A.CREATED_BY<>A.CALCULATED_BY)~' INTO v;
    IF v=0 THEN ok('legacy accrual projection is dual-written from canonical 11G values');ELSE bad('legacy accrual projection diverges from canonical 11G values');END IF;
  ELSE
    bad('legacy accrual projection is structurally incomplete');
  END IF;
  SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND CONSTRAINT_NAME='FK_DEP_PROFIT_ACCR_POST' AND CONSTRAINT_TYPE='R' AND STATUS='ENABLED';IF v=1 THEN ok('accrual-to-posting FK enabled');ELSE bad('accrual-to-posting FK enabled');END IF;
  SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME='UX_DEP_PROFIT_ACTIVE_ACCOUNT' AND UNIQUENESS='UNIQUE';IF v=1 THEN ok('one-active-profit-contract unique index exists');ELSE bad('one-active-profit-contract unique index exists');END IF;
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_CONTRACT WHERE ANNUAL_RATE<0 OR ACCRUED_AMOUNT<0 OR PAID_AMOUNT<0 OR (EFFECTIVE_TO IS NOT NULL AND EFFECTIVE_TO<EFFECTIVE_FROM);IF v=0 THEN ok('profit contract invariants valid');ELSE bad('profit contract invariants valid');END IF;
  SELECT COUNT(*) INTO v FROM (SELECT ACCOUNT_ID FROM DPS2.DEPOSIT_PROFIT_CONTRACT WHERE STATUS_CODE='ACTIVE' GROUP BY ACCOUNT_ID HAVING COUNT(*)>1);IF v=0 THEN ok('at most one ACTIVE profit contract per account');ELSE bad('at most one ACTIVE profit contract per account');END IF;
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A LEFT JOIN DPS2.DEPOSIT_PROFIT_CONTRACT C ON C.PROFIT_CONTRACT_ID=A.PROFIT_CONTRACT_ID WHERE C.PROFIT_CONTRACT_ID IS NULL OR A.ACCOUNT_ID<>C.ACCOUNT_ID;IF v=0 THEN ok('accrual traceability valid');ELSE bad('accrual traceability valid');END IF;
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_POSTING P LEFT JOIN DPS2.DEPOSIT_SUBLEDGER_ENTRY S ON S.SUBLEDGER_ENTRY_ID=P.SUBLEDGER_ENTRY_ID WHERE P.STATUS_CODE='POSTED' AND P.DESTINATION_CODE='SAME_DEPOSIT' AND (S.SUBLEDGER_ENTRY_ID IS NULL OR S.SOURCE_ENTITY_TYPE<>'DEPOSIT_PROFIT_POSTING' OR S.SOURCE_ENTITY_ID<>P.PROFIT_POSTING_ID);IF v=0 THEN ok('same-deposit profit postings trace to 11D subledger');ELSE bad('same-deposit profit postings trace to 11D subledger');END IF;
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_OPENING_PROFIT_INSTRUCTION P JOIN DPS2.DEPOSIT_ACCOUNT A ON A.OPENING_REQUEST_ID=P.OPENING_REQUEST_ID WHERE P.RATE_VALUE IS NOT NULL AND A.ACCOUNT_STATUS_CODE='ACTIVE' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_CONTRACT C WHERE C.ACCOUNT_ID=A.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE');IF v=0 THEN ok('active accounts with opening profit snapshot have operational profit contract');ELSE bad('active accounts with opening profit snapshot have operational profit contract');END IF;
  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');DBMS_OUTPUT.PUT_LINE('PHASE11G_DB_VERIFIER_PASS='||p);DBMS_OUTPUT.PUT_LINE('PHASE11G_DB_VERIFIER_FAIL='||f);IF f>0 THEN RAISE_APPLICATION_ERROR(-21179,'Phase 11G DB verifier failed: '||f);END IF;DBMS_OUTPUT.PUT_LINE('PHASE11G_DB_BASELINE_PASS');
END;
/
