SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11K - Wave B Steps 06-08 DB Verifier
PROMPT ============================================================
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE chk(label VARCHAR2,ok BOOLEAN) IS BEGIN IF ok THEN p:=p+1;DBMS_OUTPUT.PUT_LINE('PASS | '||label);ELSE f:=f+1;DBMS_OUTPUT.PUT_LINE('FAIL | '||label);END IF; END;
  FUNCTION tab(t VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t);RETURN n>0;END;
  FUNCTION seq_ahead(s VARCHAR2,t VARCHAR2,pk VARCHAR2) RETURN BOOLEAN IS n NUMBER; m NUMBER; BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO n; EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0) FROM DPS2.'||t INTO m; RETURN n>m; END;
BEGIN
  chk('DEPOSIT_STATEMENT_TEMPLATE exists',tab('DEPOSIT_STATEMENT_TEMPLATE'));
  chk('DEPOSIT_STATEMENT_REQUEST exists',tab('DEPOSIT_STATEMENT_REQUEST'));
  chk('DEPOSIT_STATEMENT exists',tab('DEPOSIT_STATEMENT'));
  chk('DEPOSIT_STATEMENT_ITEM exists',tab('DEPOSIT_STATEMENT_ITEM'));
  chk('DEPOSIT_STATEMENT_DELIVERY exists',tab('DEPOSIT_STATEMENT_DELIVERY'));
  chk('DEPOSIT_ACCOUNT_LIMIT exists',tab('DEPOSIT_ACCOUNT_LIMIT'));
  chk('DEPOSIT_ACCOUNT_LIMIT_USAGE exists',tab('DEPOSIT_ACCOUNT_LIMIT_USAGE'));
  chk('DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION exists',tab('DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION'));
  chk('DEPOSIT_MATURITY_PROCESS_RUN exists',tab('DEPOSIT_MATURITY_PROCESS_RUN'));
  chk('DEPOSIT_MATURITY_PROCESS_ITEM exists',tab('DEPOSIT_MATURITY_PROCESS_ITEM'));
  chk('DEPOSIT_MATURITY_EVENT exists',tab('DEPOSIT_MATURITY_EVENT'));

  chk('statement template sequence ahead',seq_ahead('SEQ_DEPOSIT_STATEMENT_TEMPLATE','DEPOSIT_STATEMENT_TEMPLATE','STATEMENT_TEMPLATE_ID'));
  chk('statement request sequence ahead',seq_ahead('SEQ_DEPOSIT_STATEMENT_REQUEST','DEPOSIT_STATEMENT_REQUEST','STATEMENT_REQUEST_ID'));
  chk('statement sequence ahead',seq_ahead('SEQ_DEPOSIT_STATEMENT','DEPOSIT_STATEMENT','STATEMENT_ID'));
  chk('statement item sequence ahead',seq_ahead('SEQ_DEPOSIT_STATEMENT_ITEM','DEPOSIT_STATEMENT_ITEM','STATEMENT_ITEM_ID'));
  chk('statement delivery sequence ahead',seq_ahead('SEQ_DEPOSIT_STATEMENT_DELIVERY','DEPOSIT_STATEMENT_DELIVERY','STATEMENT_DELIVERY_ID'));
  chk('account limit sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_LIMIT','DEPOSIT_ACCOUNT_LIMIT','ACCOUNT_LIMIT_ID'));
  chk('account limit usage sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_LIMIT_USAGE','DEPOSIT_ACCOUNT_LIMIT_USAGE','ACCOUNT_LIMIT_USAGE_ID'));
  chk('transaction restriction sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION','DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION','ACCOUNT_TX_RESTRICTION_ID'));
  chk('maturity run sequence ahead',seq_ahead('SEQ_DEPOSIT_MATURITY_PROCESS_RUN','DEPOSIT_MATURITY_PROCESS_RUN','MATURITY_PROCESS_RUN_ID'));
  chk('maturity item sequence ahead',seq_ahead('SEQ_DEPOSIT_MATURITY_PROCESS_ITEM','DEPOSIT_MATURITY_PROCESS_ITEM','MATURITY_PROCESS_ITEM_ID'));
  chk('maturity event sequence ahead',seq_ahead('SEQ_DEPOSIT_MATURITY_EVENT','DEPOSIT_MATURITY_EVENT','MATURITY_EVENT_ID'));
  chk('idempotency sequence ahead',seq_ahead('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID'));

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_STATEMENT S JOIN DPS2.DEPOSIT_STATEMENT_REQUEST R ON R.STATEMENT_REQUEST_ID=S.STATEMENT_REQUEST_ID WHERE S.ACCOUNT_ID<>R.ACCOUNT_ID;
  chk('statement header/request account trace is coherent',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_STATEMENT S
   WHERE (NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_STATEMENT_ITEM I WHERE I.STATEMENT_ID=S.STATEMENT_ID) AND S.OPENING_BALANCE<>S.CLOSING_BALANCE)
      OR (EXISTS(SELECT 1 FROM DPS2.DEPOSIT_STATEMENT_ITEM I WHERE I.STATEMENT_ID=S.STATEMENT_ID)
          AND S.CLOSING_BALANCE<>(SELECT I.RUNNING_BALANCE FROM DPS2.DEPOSIT_STATEMENT_ITEM I WHERE I.STATEMENT_ID=S.STATEMENT_ID AND I.SEQUENCE_NO=(SELECT MAX(X.SEQUENCE_NO) FROM DPS2.DEPOSIT_STATEMENT_ITEM X WHERE X.STATEMENT_ID=S.STATEMENT_ID)));
  chk('statement closing balance equals final running balance',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_STATEMENT_ITEM I JOIN DPS2.DEPOSIT_STATEMENT S ON S.STATEMENT_ID=I.STATEMENT_ID JOIN DPS2.DEPOSIT_STATEMENT_REQUEST R ON R.STATEMENT_REQUEST_ID=S.STATEMENT_REQUEST_ID WHERE I.BOOKING_DATE<R.DATE_FROM OR I.BOOKING_DATE>R.DATE_TO;
  chk('statement items stay inside request date range',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_STATEMENT S WHERE S.STATEMENT_STATUS_CODE='DELIVERED' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_STATEMENT_DELIVERY D WHERE D.STATEMENT_ID=S.STATEMENT_ID AND D.DELIVERY_STATUS_CODE='DELIVERED');
  chk('delivered statements retain delivery evidence',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_LIMIT_USAGE U JOIN DPS2.DEPOSIT_ACCOUNT_LIMIT L ON L.ACCOUNT_LIMIT_ID=U.ACCOUNT_LIMIT_ID WHERE U.ACCOUNT_ID<>L.ACCOUNT_ID OR U.USED_AMOUNT<0 OR U.USED_COUNT<0 OR U.PERIOD_END<U.PERIOD_START;
  chk('limit usage account and counters are coherent',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_LIMIT_USAGE U JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=U.LAST_TRANSACTION_ID WHERE U.LAST_TRANSACTION_ID IS NOT NULL AND (T.ACCOUNT_ID<>U.ACCOUNT_ID OR T.TRANSACTION_STATUS_CODE<>'POSTED');
  chk('limit usage last transaction points to current POSTED transaction',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION R WHERE R.STATUS_CODE='RELEASED' AND R.VALID_TO IS NULL;
  chk('released transaction restrictions retain validity end',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_PROCESS_RUN R WHERE R.TOTAL_COUNT<>(SELECT COUNT(*) FROM DPS2.DEPOSIT_MATURITY_PROCESS_ITEM I WHERE I.MATURITY_PROCESS_RUN_ID=R.MATURITY_PROCESS_RUN_ID) OR (R.STATUS_CODE IN ('COMPLETED','PARTIAL','FAILED') AND R.PROCESSED_COUNT+R.FAILED_COUNT<>R.TOTAL_COUNT);
  chk('maturity run counters match process items',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_PROCESS_ITEM I JOIN DPS2.DEPOSIT_TERM_CONTRACT T ON T.TERM_CONTRACT_ID=I.TERM_CONTRACT_ID WHERE T.ACCOUNT_ID<>I.ACCOUNT_ID OR T.MATURITY_INSTRUCTION_CODE<>I.ACTION_CODE;
  chk('maturity items trace to term contract account/instruction',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_PROCESS_ITEM I JOIN DPS2.DEPOSIT_MATURITY_EVENT E ON E.MATURITY_EVENT_ID=I.MATURITY_EVENT_ID WHERE I.MATURITY_EVENT_ID IS NOT NULL AND (E.ACCOUNT_ID<>I.ACCOUNT_ID OR E.TERM_CONTRACT_ID<>I.TERM_CONTRACT_ID OR E.INSTRUCTION_CODE<>I.ACTION_CODE);
  chk('maturity items and events preserve canonical trace',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_EVENT E WHERE E.ACTION_RESULT_CODE='PENDING' AND E.PROCESSED_AT IS NOT NULL;
  chk('pending maturity events are not falsely finalized',v=0);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11K_DB_VERIFIER_PASS='||p); DBMS_OUTPUT.PUT_LINE('PHASE11K_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21239,'Phase 11K DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11K_DB_BASELINE_PASS');
END;
/
