SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11J - Wave A Steps 01-02 DB Verifier
PROMPT ============================================================
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE chk(label VARCHAR2,ok BOOLEAN) IS BEGIN IF ok THEN p:=p+1;DBMS_OUTPUT.PUT_LINE('PASS | '||label);ELSE f:=f+1;DBMS_OUTPUT.PUT_LINE('FAIL | '||label);END IF; END;
  FUNCTION tab(t VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t);RETURN n>0;END;
  FUNCTION seq_ahead(s VARCHAR2,t VARCHAR2,pk VARCHAR2) RETURN BOOLEAN IS n NUMBER; m NUMBER; BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO n; EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0) FROM DPS2.'||t INTO m; RETURN n>m; END;
BEGIN
  chk('DEPOSIT_ACCOUNT_ATTRIBUTE exists',tab('DEPOSIT_ACCOUNT_ATTRIBUTE'));
  chk('DEPOSIT_ACCOUNT_CONDITION_OVERRIDE exists',tab('DEPOSIT_ACCOUNT_CONDITION_OVERRIDE'));
  chk('DEPOSIT_ACCOUNT_PRODUCT_HISTORY exists',tab('DEPOSIT_ACCOUNT_PRODUCT_HISTORY'));
  chk('DEPOSIT_ACCOUNT_SIGNATORY exists',tab('DEPOSIT_ACCOUNT_SIGNATORY'));
  chk('DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY exists',tab('DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY'));
  chk('DEPOSIT_ACTIVATION_RUN exists',tab('DEPOSIT_ACTIVATION_RUN'));
  chk('DEPOSIT_ACTIVATION_CHECK exists',tab('DEPOSIT_ACTIVATION_CHECK'));
  chk('DEPOSIT_ACCOUNT_BULK_ACTION exists',tab('DEPOSIT_ACCOUNT_BULK_ACTION'));
  chk('DEPOSIT_ACCOUNT_BULK_ACTION_ITEM exists',tab('DEPOSIT_ACCOUNT_BULK_ACTION_ITEM'));

  chk('attribute sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_ATTRIBUTE','DEPOSIT_ACCOUNT_ATTRIBUTE','ACCOUNT_ATTRIBUTE_ID'));
  chk('condition sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_CONDITION_OVERRIDE','DEPOSIT_ACCOUNT_CONDITION_OVERRIDE','ACCOUNT_CONDITION_OVERRIDE_ID'));
  chk('product history sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_PRODUCT_HISTORY','DEPOSIT_ACCOUNT_PRODUCT_HISTORY','ACCOUNT_PRODUCT_HISTORY_ID'));
  chk('signatory sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_SIGNATORY','DEPOSIT_ACCOUNT_SIGNATORY','SIGNATORY_ID'));
  chk('signatory authority sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY','DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY','SIGNATORY_AUTHORITY_ID'));
  chk('approval sequence ahead',seq_ahead('SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST','DEPOSIT_OPERATION_APPROVAL_REQUEST','APPROVAL_REQUEST_ID'));
  chk('activation run sequence ahead',seq_ahead('SEQ_DEPOSIT_ACTIVATION_RUN','DEPOSIT_ACTIVATION_RUN','ACTIVATION_RUN_ID'));
  chk('activation check sequence ahead',seq_ahead('SEQ_DEPOSIT_ACTIVATION_CHECK','DEPOSIT_ACTIVATION_CHECK','ACTIVATION_CHECK_ID'));
  chk('bulk action sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_BULK_ACTION','DEPOSIT_ACCOUNT_BULK_ACTION','BULK_ACTION_ID'));
  chk('bulk item sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_BULK_ACTION_ITEM','DEPOSIT_ACCOUNT_BULK_ACTION_ITEM','BULK_ACTION_ITEM_ID'));
  chk('servicing history sequence ahead',seq_ahead('SEQ_DEPOSIT_ACCOUNT_SERVICING_HISTORY','DEPOSIT_ACCOUNT_SERVICING_HISTORY','SERVICING_HISTORY_ID'));
  chk('idempotency sequence ahead',seq_ahead('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID'));

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_CONDITION_OVERRIDE C
    JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=C.APPROVAL_REQUEST_ID
   WHERE A.OPERATION_TYPE_CODE='ACCOUNT_CONDITION_OVERRIDE'
     AND (A.ACCOUNT_ID<>C.ACCOUNT_ID OR A.SOURCE_ENTITY_TYPE<>'DEPOSIT_ACCOUNT_CONDITION_OVERRIDE' OR A.SOURCE_ENTITY_ID<>C.ACCOUNT_CONDITION_OVERRIDE_ID OR UPPER(A.REQUESTED_BY_USER_ID)=UPPER(A.APPROVER_USER_ID));
  chk('11J condition overrides preserve maker-checker trace',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_PRODUCT_HISTORY H
    JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=H.APPROVAL_REQUEST_ID
   WHERE A.OPERATION_TYPE_CODE='ACCOUNT_PRODUCT_CHANGE'
     AND (A.ACCOUNT_ID<>H.ACCOUNT_ID OR A.SOURCE_ENTITY_TYPE<>'DEPOSIT_ACCOUNT_PRODUCT_HISTORY' OR A.SOURCE_ENTITY_ID<>H.ACCOUNT_PRODUCT_HISTORY_ID OR UPPER(A.REQUESTED_BY_USER_ID)=UPPER(A.APPROVER_USER_ID));
  chk('11J product changes preserve maker-checker trace',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY AU
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT_SIGNATORY S ON S.SIGNATORY_ID=AU.SIGNATORY_ID
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=S.ACCOUNT_ID
   WHERE S.SIGNATORY_ID IS NULL OR A.ACCOUNT_ID IS NULL;
  chk('signatory authorities trace to signatory and account',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACTIVATION_RUN R
   WHERE R.RUN_STATUS_CODE='READY' AND (R.READY_FLAG<>1 OR R.BLOCKING_CHECK_COUNT<>0 OR NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACTIVATION_CHECK C WHERE C.ACTIVATION_RUN_ID=R.ACTIVATION_RUN_ID));
  chk('READY activation runs have checks and no blockers',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACTIVATION_RUN R
    JOIN DPS2.DEPOSIT_ACTIVATION_CHECK C ON C.ACTIVATION_RUN_ID=R.ACTIVATION_RUN_ID
   WHERE C.ACCOUNT_ID<>R.ACCOUNT_ID;
  chk('activation checks belong to run account',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BULK_ACTION B
   WHERE B.SUCCESS_COUNT<0 OR B.FAILED_COUNT<0 OR B.SUCCESS_COUNT+B.FAILED_COUNT>B.TOTAL_COUNT
      OR (B.ACTION_STATUS_CODE='COMPLETED' AND (B.SUCCESS_COUNT<>B.TOTAL_COUNT OR B.FAILED_COUNT<>0));
  chk('bulk action counters/status are coherent',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BULK_ACTION B
   WHERE (SELECT COUNT(*) FROM DPS2.DEPOSIT_ACCOUNT_BULK_ACTION_ITEM I WHERE I.BULK_ACTION_ID=B.BULK_ACTION_ID)<>B.TOTAL_COUNT;
  chk('bulk action total count matches items',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BULK_ACTION_ITEM I
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=I.ACCOUNT_ID
   WHERE A.ACCOUNT_ID IS NULL;
  chk('bulk items trace to real accounts',v=0);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11J_DB_VERIFIER_PASS='||p); DBMS_OUTPUT.PUT_LINE('PHASE11J_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21219,'Phase 11J DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11J_DB_BASELINE_PASS');
END;
/
