SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11C - Lifecycle + Hold/Block DB Verifier
PROMPT ============================================================
DECLARE
    v_pass NUMBER:=0; v_fail NUMBER:=0; v NUMBER; v_text VARCHAR2(4000);
    PROCEDURE ok(p_ok BOOLEAN,p_msg VARCHAR2) IS BEGIN IF p_ok THEN v_pass:=v_pass+1; DBMS_OUTPUT.PUT_LINE('PASS | '||p_msg); ELSE v_fail:=v_fail+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||p_msg); END IF; END;
    PROCEDURE table_ok(p_table VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=p_table; ok(v=1,p_table||' exists'); END;
    PROCEDURE index_ok(p_index VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=p_index; ok(v=1,p_index||' exists'); END;
BEGIN
    table_ok('DEPOSIT_ACCOUNT'); table_ok('DEPOSIT_ACCOUNT_LIFECYCLE_EVENT'); table_ok('DEPOSIT_ACCOUNT_STATUS_HISTORY'); table_ok('DEPOSIT_ACCOUNT_HOLD'); table_ok('DEPOSIT_ACCOUNT_HOLD_HISTORY'); table_ok('DEPOSIT_OPERATION_IDEMPOTENCY');
    SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT' AND COLUMN_NAME='DORMANCY_DATE'; ok(v=1,'DEPOSIT_ACCOUNT.DORMANCY_DATE exists');
    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT' AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_ACCOUNT_STATUS_CODE'; ok(INSTR(v_text,'''SUSPENDED''')>0 AND INSTR(v_text,'''DORMANT''')>0,'account status supports SUSPENDED/DORMANT');
    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT_LIFECYCLE_EVENT' AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_LIFECYCLE_EVENT_EVENT_TYPE_CODE'; ok(INSTR(v_text,'''SUSPEND''')>0 AND INSTR(v_text,'''REACTIVATE''')>0 AND INSTR(v_text,'''MARK_DORMANT''')>0,'lifecycle event contract supports 11C transitions');
    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT_HOLD' AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_HOLD_HOLD_TYPE_CODE'; ok(INSTR(v_text,'''FULL''')>0 AND INSTR(v_text,'''PARTIAL''')>0 AND INSTR(v_text,'''DEBIT_ONLY''')>0 AND INSTR(v_text,'''CREDIT_ONLY''')>0,'hold type contract is complete');
    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT_HOLD' AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_HOLD_RELEASE_POLICY_CODE'; ok(INSTR(v_text,'''ORIGIN_ONLY''')>0 AND INSTR(v_text,'''AUTO_EXPIRY''')>0,'hold release-policy contract exists');
    SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_OPERATION_IDEMPOTENCY' AND CONSTRAINT_TYPE='U' AND STATUS='ENABLED'; ok(v>=1,'idempotency unique guard enabled');
    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT_SERVICING_HISTORY' AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_SERVICING_HISTORY_CHANGE_TYPE_CODE'; ok(INSTR(v_text,'''STATUS''')>0 AND INSTR(v_text,'''HOLD''')>0,'servicing history supports STATUS/HOLD');
    index_ok('IX_DEP_HOLD_ACCOUNT_STATUS'); index_ok('IX_DEP_STATUS_HIST_ACCOUNT_AT'); index_ok('IX_DEP_IDEMP_ACCOUNT_OP');
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('PHASE11C_DB_VERIFIER_PASS='||v_pass); DBMS_OUTPUT.PUT_LINE('PHASE11C_DB_VERIFIER_FAIL='||v_fail);
    IF v_fail>0 THEN RAISE_APPLICATION_ERROR(-21139,'Phase 11C DB verifier failed: '||v_fail); END IF;
    DBMS_OUTPUT.PUT_LINE('PHASE11C_DB_BASELINE_PASS');
END;
/
