WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
PROMPT ============================================================
PROMPT DPS2 Phase 11N-C - Steps 03-04 Canonical Closure DB Verifier
PROMPT ============================================================
DECLARE
  v NUMBER;
  p NUMBER := 0;
  f NUMBER := 0;
  PROCEDURE chk(label VARCHAR2, bad NUMBER) IS
  BEGIN
    IF bad=0 THEN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||label);
    ELSE f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||label||' | violations='||bad); END IF;
  END;
BEGIN
  -- 11N-C cutover rule:
  -- * executions produced by the evolved 11N-C service must carry a POSTED Step05 transaction;
  -- * pre-11N-C/11F historical executions are not retrofitted with fabricated transactions and are
  --   accepted only when their original direct Package17 posting is still fully traceable.
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_PARTIAL_WITHDRAWAL W
   WHERE W.STATUS_CODE='EXECUTED' AND (
      (W.TRANSACTION_ID IS NOT NULL AND NOT EXISTS(
         SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION T
          WHERE T.TRANSACTION_ID=W.TRANSACTION_ID
            AND T.TRANSACTION_TYPE_CODE='TERM_PARTIAL_WITHDRAWAL'
            AND T.TRANSACTION_STATUS_CODE='POSTED'))
      OR
      (W.TRANSACTION_ID IS NULL AND NOT EXISTS(
         SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
          WHERE S.ACCOUNT_ID=W.ACCOUNT_ID
            AND S.POSTING_REFERENCE='TERM-PW-'||TO_CHAR(W.PARTIAL_WITHDRAWAL_ID)
            AND S.SOURCE_ENTITY_TYPE='TERM_PARTIAL_WITHDRAWAL'
            AND S.SOURCE_ENTITY_ID=W.PARTIAL_WITHDRAWAL_ID
            AND S.DEBIT_CREDIT_CODE='DEBIT'
            AND S.AMOUNT=NVL(W.EFFECTIVE_AMOUNT,W.REQUESTED_AMOUNT)))
   );
  chk('executed partial withdrawals retain Step05 or verified legacy 11D trace',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_PARTIAL_WITHDRAWAL W
   WHERE W.STATUS_CODE='EXECUTED' AND W.TRANSACTION_ID IS NOT NULL AND NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG L JOIN DPS2.DEPOSIT_SUBLEDGER_ENTRY S ON S.TRANSACTION_LEG_ID=L.TRANSACTION_LEG_ID
      WHERE L.TRANSACTION_ID=W.TRANSACTION_ID AND L.ACCOUNT_ID=W.ACCOUNT_ID AND L.DEBIT_CREDIT_CODE='DEBIT'
        AND S.TRANSACTION_ID=W.TRANSACTION_ID AND S.ACCOUNT_ID=W.ACCOUNT_ID);
  chk('partial withdrawal Step05 transaction reaches source subledger',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_EVENT E
   WHERE E.ACTION_RESULT_CODE IN ('SETTLED','TRANSFERRED') AND (E.SETTLEMENT_TRANSACTION_ID IS NULL OR NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.TRANSACTION_ID=E.SETTLEMENT_TRANSACTION_ID
       AND T.TRANSACTION_TYPE_CODE='MATURITY_SETTLEMENT' AND T.TRANSACTION_STATUS_CODE='POSTED'));
  chk('financial maturity events have POSTED MATURITY_SETTLEMENT transaction',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_EVENT E
   WHERE E.ACTION_RESULT_CODE IN ('SETTLED','TRANSFERRED') AND E.SETTLEMENT_TRANSACTION_ID IS NOT NULL AND NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_TERM_SETTLEMENT S WHERE S.TERM_CONTRACT_ID=E.TERM_CONTRACT_ID
       AND S.SETTLEMENT_TYPE_CODE='MATURITY' AND S.STATUS_CODE='POSTED' AND S.TRANSACTION_ID=E.SETTLEMENT_TRANSACTION_ID);
  chk('financial maturity event and term settlement share transaction id',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_EARLY_TERMINATION E
   WHERE E.STATUS_CODE='EXECUTED' AND (E.SETTLEMENT_TRANSACTION_ID IS NULL OR NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.TRANSACTION_ID=E.SETTLEMENT_TRANSACTION_ID
       AND T.TRANSACTION_TYPE_CODE='TERM_EARLY_TERMINATION' AND T.TRANSACTION_STATUS_CODE='POSTED'));
  chk('executed early termination has POSTED Step05 transaction',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_EARLY_TERMINATION E
   WHERE E.STATUS_CODE='EXECUTED' AND E.SETTLEMENT_TRANSACTION_ID IS NOT NULL AND NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_TERM_SETTLEMENT S WHERE S.TERM_CONTRACT_ID=E.TERM_CONTRACT_ID
       AND S.SETTLEMENT_TYPE_CODE='EARLY_TERMINATION' AND S.STATUS_CODE='POSTED' AND S.TRANSACTION_ID=E.SETTLEMENT_TRANSACTION_ID);
  chk('early termination and term settlement share transaction id',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_EARLY_TERMINATION E
   WHERE E.APPROVAL_REQUEST_ID IS NULL OR NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE C WHERE C.ACCOUNT_ID=E.ACCOUNT_ID
       AND C.CLOSURE_TYPE_CODE='EARLY_TERMINATION' AND C.REASON_CODE='TERM_EARLY_TERMINATION'
       AND C.APPROVAL_REQUEST_ID=E.APPROVAL_REQUEST_ID);
  chk('early termination resolves controlled closure through shared approval evidence',v);

  SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS
   WHERE OWNER='DPS2'
     AND TABLE_NAME='DEPOSIT_ACCOUNT_STATUS_HISTORY'
     AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_STATUS_HISTORY_REASON_CODE'
     AND (SEARCH_CONDITION_VC IS NULL OR UPPER(SEARCH_CONDITION_VC) NOT LIKE '%TERM_EARLY_TERMINATION%');
  chk('status-history reason constraint accepts documented early termination reason',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_EARLY_TERMINATION E
   WHERE E.STATUS_CODE='EXECUTED' AND NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE C WHERE C.ACCOUNT_ID=E.ACCOUNT_ID
       AND C.CLOSURE_TYPE_CODE='EARLY_TERMINATION' AND C.REASON_CODE='TERM_EARLY_TERMINATION'
       AND C.CLOSURE_STATUS_CODE='EXECUTED' AND C.SETTLEMENT_TRANSACTION_REFERENCE='TX-'||TO_CHAR(E.SETTLEMENT_TRANSACTION_ID));
  chk('executed early termination closes only through controlled Package16 trace',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_MATURITY_EVENT E
   WHERE E.ACTION_RESULT_CODE IN ('SETTLED','TRANSFERRED') AND NOT EXISTS(
     SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE C WHERE C.ACCOUNT_ID=E.ACCOUNT_ID
       AND C.CLOSURE_TYPE_CODE='MATURITY' AND C.CLOSURE_STATUS_CODE='EXECUTED'
       AND C.SETTLEMENT_TRANSACTION_REFERENCE='TX-'||TO_CHAR(E.SETTLEMENT_TRANSACTION_ID));
  chk('financial maturity closure retains owning transaction reference',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T
   WHERE T.TRANSACTION_TYPE_CODE IN ('TERM_PARTIAL_WITHDRAWAL','MATURITY_SETTLEMENT','TERM_EARLY_TERMINATION','PROFIT_PAYMENT')
     AND T.TRANSACTION_STATUS_CODE='POSTED' AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_AUTHORIZATION A WHERE A.TRANSACTION_ID=T.TRANSACTION_ID
         AND A.DECISION_CODE='APPROVED' AND UPPER(A.REQUESTED_BY)<>UPPER(A.DECIDED_BY));
  chk('derived Step05 transactions retain independent authorization evidence',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T
   WHERE T.TRANSACTION_TYPE_CODE IN ('TERM_PARTIAL_WITHDRAWAL','MATURITY_SETTLEMENT','TERM_EARLY_TERMINATION','PROFIT_PAYMENT')
     AND T.TRANSACTION_STATUS_CODE='POSTED' AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG L WHERE L.TRANSACTION_ID=T.TRANSACTION_ID);
  chk('derived Step05 transactions have transaction legs',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION_LEG L JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=L.TRANSACTION_ID
   WHERE T.TRANSACTION_TYPE_CODE IN ('TERM_PARTIAL_WITHDRAWAL','MATURITY_SETTLEMENT','TERM_EARLY_TERMINATION','PROFIT_PAYMENT')
     AND T.TRANSACTION_STATUS_CODE='POSTED' AND L.ACCOUNT_ID IS NOT NULL AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.TRANSACTION_ID=T.TRANSACTION_ID AND S.TRANSACTION_LEG_ID=L.TRANSACTION_LEG_ID);
  chk('every deposit-account leg of derived Step05 transaction reaches subledger',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PAYMENT P
   WHERE P.PAYMENT_STATUS_CODE='PAID' AND P.PAYMENT_DESTINATION_CODE IN ('LINKED_ACCOUNT','CUSTOMER_SELECTED_ACCOUNT')
     AND (P.POSTING_REFERENCE NOT LIKE 'TX-%' OR NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION T WHERE 'TX-'||TO_CHAR(T.TRANSACTION_ID)=P.POSTING_REFERENCE
         AND T.TRANSACTION_STATUS_CODE='POSTED' AND T.TRANSACTION_TYPE_CODE IN ('PROFIT_PAYMENT','MATURITY_SETTLEMENT')));
  chk('external/internal-destination canonical profit payments use Step05 transaction reference',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A
   WHERE A.PROFIT_PERIOD_ID IS NULL OR NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PERIOD P WHERE P.PROFIT_PERIOD_ID=A.PROFIT_PERIOD_ID);
  chk('canonical accruals remain owned by Profit Period',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PAYMENT P
   WHERE NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PERIOD R WHERE R.PROFIT_PERIOD_ID=P.PROFIT_PERIOD_ID);
  chk('canonical payments remain owned by Profit Period',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PERIOD P
   WHERE NVL(P.PAID_AMOUNT,0)>NVL(P.PAYABLE_AMOUNT,0);
  chk('canonical profit period paid amount never exceeds payable amount',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TERM_CONTRACT T
   WHERE T.STATUS_CODE IN ('MATURED','TERMINATED') AND NVL(T.PRINCIPAL_AMOUNT,0)<>0;
  chk('matured/terminated term contracts have zero principal',v);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11NC_DB_VERIFIER_PASS='||p);
  DBMS_OUTPUT.PUT_LINE('PHASE11NC_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-20420,'Phase 11N-C DB baseline violations='||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11NC_DB_BASELINE_PASS');
END;
/
