WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK OFF
PROMPT ============================================================
PROMPT DPS2 Phase 11N-D - Steps 05-10 Canonical Audit DB Verifier
PROMPT Scope: Steps 05-10 only
PROMPT ============================================================
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE chk(label VARCHAR2, violations NUMBER) IS
  BEGIN
    IF violations=0 THEN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||label);
    ELSE f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||label||' | violations='||violations); END IF;
  END;
  PROCEDURE chk_seq(label VARCHAR2,p_seq VARCHAR2,p_table VARCHAR2,p_pk VARCHAR2) IS
    n NUMBER; m NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p_seq);
    IF n=0 THEN chk(label,1); RETURN; END IF;
    SELECT LAST_NUMBER INTO n FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p_seq);
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||p_pk||'),0) FROM DPS2.'||p_table INTO m;
    chk(label,CASE WHEN n>m THEN 0 ELSE 1 END);
  END;
BEGIN
  -- Step 08 financial closure trace: new 11N-D executions use Step05; exact historical 11E Package17 evidence remains accepted.
  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM s
    JOIN DPS2.DEPOSIT_ACCOUNT_CLOSURE c ON c.ACCOUNT_CLOSURE_ID=s.ACCOUNT_CLOSURE_ID
   WHERE s.SETTLEMENT_STATUS_CODE='SETTLED' AND s.NET_AMOUNT>0 AND (
      (s.TRANSACTION_ID IS NOT NULL AND NOT EXISTS(
        SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION t
         WHERE t.TRANSACTION_ID=s.TRANSACTION_ID
           AND t.TRANSACTION_STATUS_CODE='POSTED'
           AND t.TRANSACTION_TYPE_CODE IN ('ACCOUNT_CLOSURE_SETTLEMENT','MATURITY_SETTLEMENT','TERM_EARLY_TERMINATION')))
      OR
      (s.TRANSACTION_ID IS NULL
       AND NOT EXISTS(
         SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY e
          WHERE e.ACCOUNT_ID=c.ACCOUNT_ID
            AND e.SOURCE_ENTITY_TYPE='ACCOUNT_CLOSURE'
            AND e.SOURCE_ENTITY_ID=c.ACCOUNT_CLOSURE_ID
            AND e.POSTING_REFERENCE='CLOSURE-'||TO_CHAR(c.ACCOUNT_CLOSURE_ID)||'-PRINCIPAL'
            AND e.DEBIT_CREDIT_CODE='DEBIT'
            AND e.AMOUNT=s.NET_AMOUNT)
       AND NOT EXISTS(
         SELECT 1
           FROM DPS2.DEPOSIT_TRANSACTION t
           JOIN DPS2.DEPOSIT_TRANSACTION_LEG l ON l.TRANSACTION_ID=t.TRANSACTION_ID
           JOIN DPS2.DEPOSIT_SUBLEDGER_ENTRY e ON e.TRANSACTION_ID=t.TRANSACTION_ID AND e.TRANSACTION_LEG_ID=l.TRANSACTION_LEG_ID
          WHERE c.SETTLEMENT_TRANSACTION_REFERENCE='TX-'||TO_CHAR(t.TRANSACTION_ID)
            AND t.TRANSACTION_STATUS_CODE='POSTED'
            AND t.TRANSACTION_TYPE_CODE IN ('MATURITY_SETTLEMENT','TERM_EARLY_TERMINATION')
            AND l.ACCOUNT_ID=c.ACCOUNT_ID
            AND l.DEBIT_CREDIT_CODE='DEBIT'
            AND e.ACCOUNT_ID=c.ACCOUNT_ID))
   );
  chk('settled closure items retain Step05, verified 11N-C pre-settled, or legacy direct Package17 trace',v);

  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM s
    JOIN DPS2.DEPOSIT_ACCOUNT_CLOSURE c ON c.ACCOUNT_CLOSURE_ID=s.ACCOUNT_CLOSURE_ID
   WHERE s.TRANSACTION_ID IS NOT NULL
     AND c.CLOSURE_STATUS_CODE='EXECUTED'
     AND NVL(c.SETTLEMENT_TRANSACTION_REFERENCE,'?') <> 'TX-'||TO_CHAR(s.TRANSACTION_ID);
  chk('transaction-linked closure item and closure header share TX reference',v);

  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM s
    JOIN DPS2.DEPOSIT_ACCOUNT_CLOSURE c ON c.ACCOUNT_CLOSURE_ID=s.ACCOUNT_CLOSURE_ID
   WHERE s.TRANSACTION_ID IS NOT NULL
     AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG l
       JOIN DPS2.DEPOSIT_SUBLEDGER_ENTRY e ON e.TRANSACTION_ID=l.TRANSACTION_ID AND e.TRANSACTION_LEG_ID=l.TRANSACTION_LEG_ID
       WHERE l.TRANSACTION_ID=s.TRANSACTION_ID AND l.ACCOUNT_ID=c.ACCOUNT_ID AND l.DEBIT_CREDIT_CODE='DEBIT');
  chk('closure Step05 transaction reaches source-account subledger',v);

  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_TRANSACTION t
   WHERE t.TRANSACTION_TYPE_CODE='ACCOUNT_CLOSURE_SETTLEMENT'
     AND t.TRANSACTION_STATUS_CODE='POSTED'
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_AUTHORIZATION a WHERE a.TRANSACTION_ID=t.TRANSACTION_ID AND a.DECISION_CODE='APPROVED');
  chk('generic closure Step05 transaction retains authorization evidence',v);

  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_ACCOUNT_CLOSURE c
   WHERE c.CLOSURE_STATUS_CODE='EXECUTED'
     AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_STATUS_HISTORY h
        WHERE h.ACCOUNT_ID=c.ACCOUNT_ID AND h.EVENT_REFERENCE='CLOSURE:'||TO_CHAR(c.ACCOUNT_CLOSURE_ID)
          AND (h.APPROVAL_REQUEST_ID=c.APPROVAL_REQUEST_ID OR
               (h.APPROVAL_REQUEST_ID IS NULL AND EXISTS(
                  SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT le
                   WHERE le.ACCOUNT_ID=c.ACCOUNT_ID AND le.EVENT_TYPE_CODE='CLOSE' AND le.APPROVAL_REQUEST_ID=c.APPROVAL_REQUEST_ID))));
  chk('executed closure status-history approval trace is canonical or verified legacy lifecycle-backed',v);

  SELECT COUNT(*) INTO v
    FROM DPS2.DEPOSIT_ACCOUNT_REOPENING r
   WHERE r.REOPEN_STATUS_CODE='EXECUTED'
     AND NOT EXISTS(
       SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_STATUS_HISTORY h
        WHERE h.ACCOUNT_ID=r.ACCOUNT_ID AND h.EVENT_REFERENCE='REOPENING:'||TO_CHAR(r.ACCOUNT_REOPENING_ID)
          AND (h.APPROVAL_REQUEST_ID=r.APPROVAL_REQUEST_ID OR
               (h.APPROVAL_REQUEST_ID IS NULL AND EXISTS(
                  SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT le
                   WHERE le.ACCOUNT_ID=r.ACCOUNT_ID AND le.EVENT_TYPE_CODE='REOPEN' AND le.APPROVAL_REQUEST_ID=r.APPROVAL_REQUEST_ID))));
  chk('executed reopening status-history approval trace is canonical or verified legacy lifecycle-backed',v);

  -- Step 05/06/07 regression invariants.
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION t
   WHERE t.TRANSACTION_STATUS_CODE='POSTED'
     AND EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG l WHERE l.TRANSACTION_ID=t.TRANSACTION_ID AND l.ACCOUNT_ID IS NOT NULL)
     AND EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG l WHERE l.TRANSACTION_ID=t.TRANSACTION_ID AND l.ACCOUNT_ID IS NOT NULL AND l.POSTING_REFERENCE IS NULL);
  chk('posted Step05 deposit legs retain posting references',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_STATEMENT_ITEM i
   WHERE i.TRANSACTION_ID IS NOT NULL AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION t WHERE t.TRANSACTION_ID=i.TRANSACTION_ID);
  chk('statement transaction trace resolves when present',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_LIMIT_USAGE u WHERE u.USED_AMOUNT<0 OR u.USED_COUNT<0;
  chk('limit usage remains non-negative',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION r WHERE r.STATUS_CODE='RELEASED' AND r.VALID_TO IS NULL;
  chk('released transaction restrictions retain end validity',v);

  -- Step 09-10 relationship invariants only. No Step 11-13 objects are referenced here.
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_API_ACCESS a
   WHERE a.STATUS_CODE='ACTIVE' AND a.AUTHORIZED_PARTY_ID IS NOT NULL
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PARTY p WHERE p.ACCOUNT_ID=a.ACCOUNT_ID AND p.PARTY_ID=a.AUTHORIZED_PARTY_ID AND p.STATUS_CODE='ACTIVE');
  chk('active API access authorized party remains active account party',v);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT i
   WHERE i.STATUS_CODE='ACTIVE' AND i.HOLDER_PARTY_ID IS NOT NULL
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PARTY p WHERE p.ACCOUNT_ID=i.ACCOUNT_ID AND p.PARTY_ID=i.HOLDER_PARTY_ID AND p.STATUS_CODE='ACTIVE');
  chk('active payment instrument holder remains active account party',v);

  chk_seq('Step09 inquiry sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_INQUIRY','DEPOSIT_ACCOUNT_INQUIRY','ACCOUNT_INQUIRY_ID');
  chk_seq('Step09 confirmation sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_CONFIRMATION','DEPOSIT_ACCOUNT_CONFIRMATION','ACCOUNT_CONFIRMATION_ID');
  chk_seq('Step09 notification preference sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','NOTIFICATION_PREFERENCE_ID');
  chk_seq('Step09 notification event sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','NOTIFICATION_EVENT_ID');
  chk_seq('Step09 API access sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_API_ACCESS','DEPOSIT_ACCOUNT_API_ACCESS','ACCOUNT_API_ACCESS_ID');
  chk_seq('Step10 signature rule sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_SIGNATURE_RULE','DEPOSIT_ACCOUNT_SIGNATURE_RULE','ACCOUNT_SIGNATURE_RULE_ID');
  chk_seq('Step10 delegation sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_DELEGATION','DEPOSIT_ACCOUNT_DELEGATION','ACCOUNT_DELEGATION_ID');
  chk_seq('Step10 authorized user sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_AUTHORIZED_USER','DEPOSIT_ACCOUNT_AUTHORIZED_USER','ACCOUNT_AUTHORIZED_USER_ID');
  chk_seq('Step10 beneficiary sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_BENEFICIARY','DEPOSIT_ACCOUNT_BENEFICIARY','ACCOUNT_BENEFICIARY_ID');
  chk_seq('Step10 payment instrument sequence is ahead of PK','SEQ_DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','ACCOUNT_PAYMENT_INSTRUMENT_ID');

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11ND_DB_VERIFIER_PASS='||p);
  DBMS_OUTPUT.PUT_LINE('PHASE11ND_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-20439,'Phase 11N-D DB verifier failed'); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11ND_DB_BASELINE_PASS');
END;
/
