-- Core Banking Prototype 0.11.0 - DPS2 Phase 11H DB verifier
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE ok(x VARCHAR2) IS BEGIN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||x); END;
  PROCEDURE bad(x VARCHAR2) IS BEGIN f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||x); END;
  PROCEDURE tab(x VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=x; IF v=1 THEN ok(x||' exists'); ELSE bad(x||' missing'); END IF; END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('============================================================');
  DBMS_OUTPUT.PUT_LINE('DPS2 Phase 11H - Step 04 Canonical Profit DB Verifier');
  DBMS_OUTPUT.PUT_LINE('============================================================');
  tab('DEPOSIT_ACCOUNT_PROFIT_PROFILE');tab('DEPOSIT_PROFIT_PERIOD');tab('DEPOSIT_PROFIT_ACCRUAL_DETAIL');tab('DEPOSIT_PROFIT_ADJUSTMENT');tab('DEPOSIT_PROFIT_PAYMENT');

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_CONTRACT C WHERE C.STATUS_CODE='ACTIVE' AND C.SOURCE_OPENING_PROFIT_INSTRUCTION_ID IS NOT NULL
    AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE P WHERE P.ACCOUNT_ID=C.ACCOUNT_ID AND P.STATUS_CODE='ACTIVE' AND P.SOURCE_OPENING_PROFIT_INST_ID=C.SOURCE_OPENING_PROFIT_INSTRUCTION_ID);
  IF v=0 THEN ok('active profit contracts have canonical account profit profile'); ELSE bad('active profit contracts have canonical account profit profile'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE P JOIN DPS2.DEPOSIT_PROFIT_CONTRACT C ON C.ACCOUNT_ID=P.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE'
   WHERE P.STATUS_CODE='ACTIVE' AND (NVL(P.RATE_VALUE,-1)<>NVL(C.ANNUAL_RATE,-1) OR NVL(P.CALCULATION_METHOD_CODE,'#')<>NVL(C.CALCULATION_METHOD_CODE,'#') OR NVL(P.DAY_COUNT_BASIS_CODE,'#')<>NVL(C.DAY_COUNT_BASIS_CODE,'#') OR NVL(P.PAYMENT_DESTINATION_CODE,'#')<>NVL(C.PAYMENT_DESTINATION_CODE,'#'));
  IF v=0 THEN ok('profile and operational contract snapshots are coherent'); ELSE bad('profile and operational contract snapshots are coherent'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE P JOIN DPS2.DEPOSIT_PROFIT_CONTRACT C ON C.ACCOUNT_ID=P.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE'
   WHERE P.STATUS_CODE='ACTIVE' AND P.PAYMENT_FREQUENCY_CODE='MATURITY' AND C.EFFECTIVE_TO IS NOT NULL
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PERIOD R WHERE R.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID AND R.PERIOD_START_DATE=C.EFFECTIVE_FROM AND R.PERIOD_END_DATE=C.EFFECTIVE_TO);
  IF v=0 THEN ok('MATURITY profiles have canonical profit period'); ELSE bad('MATURITY profiles have canonical profit period'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_CONTRACT_ID IS NOT NULL AND A.PROFIT_PERIOD_ID IS NULL;
  IF v=0 THEN ok('canonical accruals trace to profit period'); ELSE bad('canonical accruals trace to profit period'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_PERIOD_ID IS NOT NULL
    AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL D WHERE D.PROFIT_ACCRUAL_ID=A.PROFIT_ACCRUAL_ID AND D.COMPONENT_CODE='BASE_PROFIT');
  IF v=0 THEN ok('canonical accruals have BASE_PROFIT detail evidence'); ELSE bad('canonical accruals have BASE_PROFIT detail evidence'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL D JOIN DPS2.DEPOSIT_PROFIT_ACCRUAL A ON A.PROFIT_ACCRUAL_ID=D.PROFIT_ACCRUAL_ID
   WHERE D.BASIS_AMOUNT<>A.BASIS_AMOUNT OR D.RATE_VALUE<>ROUND(A.ANNUAL_RATE,6) OR D.ACCRUAL_AMOUNT<>A.ACCRUED_AMOUNT;
  IF v=0 THEN ok('accrual detail projection matches canonical accrual'); ELSE bad('accrual detail projection matches canonical accrual'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ADJUSTMENT J LEFT JOIN DPS2.DEPOSIT_PROFIT_PERIOD P ON P.PROFIT_PERIOD_ID=J.PROFIT_PERIOD_ID LEFT JOIN DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE F ON F.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID
   WHERE P.PROFIT_PERIOD_ID IS NULL OR F.ACCOUNT_ID<>J.ACCOUNT_ID;
  IF v=0 THEN ok('profit adjustment traces to account profit period'); ELSE bad('profit adjustment traces to account profit period'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_ADJUSTMENT J LEFT JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=J.APPROVAL_REQUEST_ID
   WHERE J.ADJUSTMENT_STATUS_CODE IN ('APPROVED','POSTED') AND (A.APPROVAL_REQUEST_ID IS NULL OR A.APPROVAL_STATUS_CODE<>'APPROVED' OR A.REQUESTED_BY_USER_ID=A.APPROVER_USER_ID);
  IF v=0 THEN ok('approved/posted adjustments have approved maker-checker trace'); ELSE bad('approved/posted adjustments have approved maker-checker trace'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PAYMENT X LEFT JOIN DPS2.DEPOSIT_PROFIT_PERIOD P ON P.PROFIT_PERIOD_ID=X.PROFIT_PERIOD_ID LEFT JOIN DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE F ON F.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID
   WHERE P.PROFIT_PERIOD_ID IS NULL OR F.ACCOUNT_ID<>X.ACCOUNT_ID;
  IF v=0 THEN ok('profit payments trace to account profit period'); ELSE bad('profit payments trace to account profit period'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_POSTING G
   WHERE G.STATUS_CODE='POSTED' AND G.DESTINATION_CODE='SAME_DEPOSIT'
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PAYMENT X WHERE X.ACCOUNT_ID=G.ACCOUNT_ID AND X.PAYMENT_STATUS_CODE='PAID' AND X.PAYMENT_AMOUNT=G.AMOUNT AND X.PAYMENT_DATE=G.POSTING_DATE AND X.POSTING_REFERENCE IN ('P11G-PROFIT-'||G.PROFIT_POSTING_ID,'P11H-PROFIT-'||G.PROFIT_POSTING_ID));
  IF v=0 THEN ok('same-deposit postings have canonical profit payment evidence'); ELSE bad('same-deposit postings have canonical profit payment evidence'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PERIOD P
   WHERE ABS(P.TOTAL_ACCRUED_AMOUNT-NVL((SELECT SUM(A.ACCRUED_AMOUNT) FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_PERIOD_ID=P.PROFIT_PERIOD_ID),0))>0.0001;
  IF v=0 THEN ok('profit period accrued total reconciles to accruals'); ELSE bad('profit period accrued total reconciles to accruals'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PERIOD P
   WHERE ABS(P.PAID_AMOUNT-NVL((SELECT SUM(X.PAYMENT_AMOUNT) FROM DPS2.DEPOSIT_PROFIT_PAYMENT X WHERE X.PROFIT_PERIOD_ID=P.PROFIT_PERIOD_ID AND X.PAYMENT_STATUS_CODE='PAID'),0))>0.0001;
  IF v=0 THEN ok('profit period paid total reconciles to payments'); ELSE bad('profit period paid total reconciles to payments'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PERIOD WHERE PAYABLE_AMOUNT<PAID_AMOUNT OR TOTAL_ACCRUED_AMOUNT<0 OR PAID_AMOUNT<0;
  IF v=0 THEN ok('profit period financial invariants valid'); ELSE bad('profit period financial invariants valid'); END IF;

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_PROFIT_PERIOD WHERE PERIOD_STATUS_CODE='PAID' AND PAYABLE_AMOUNT>PAID_AMOUNT;
  IF v=0 THEN ok('PAID profit periods have no outstanding payable balance'); ELSE bad('PAID profit periods have no outstanding payable balance'); END IF;

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11H_DB_VERIFIER_PASS='||p);DBMS_OUTPUT.PUT_LINE('PHASE11H_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21188,'Phase 11H DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11H_DB_BASELINE_PASS');
END;
/
