SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
DECLARE
  v NUMBER; p NUMBER:=0; f NUMBER:=0;
  PROCEDURE ok(m VARCHAR2) IS BEGIN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||m); END;
  PROCEDURE bad(m VARCHAR2) IS BEGIN f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||m); END;
  FUNCTION tab(t VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=t; RETURN n>0; END;
  PROCEDURE chk(m VARCHAR2,b BOOLEAN) IS BEGIN IF b THEN ok(m); ELSE bad(m); END IF; END;
BEGIN
  chk('DEPOSIT_ACCOUNT exists',tab('DEPOSIT_ACCOUNT'));
  chk('DEPOSIT_ACCOUNT_HOLD exists',tab('DEPOSIT_ACCOUNT_HOLD'));
  chk('DEPOSIT_TRANSACTION exists',tab('DEPOSIT_TRANSACTION'));
  chk('DEPOSIT_ACCOUNT_BALANCE exists',tab('DEPOSIT_ACCOUNT_BALANCE'));

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT
   WHERE ACCOUNT_STATUS_CODE NOT IN ('PENDING_ACTIVATION','ACTIVE','SUSPENDED','DORMANT','CLOSED');
  chk('account status projection is canonical',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_HOLD
   WHERE HOLD_STATUS_CODE='ACTIVE' AND HOLD_TYPE_CODE NOT IN ('FULL','PARTIAL','DEBIT_ONLY','CREDIT_ONLY');
  chk('active hold projection is canonical',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION
   WHERE TRANSACTION_STATUS_CODE NOT IN ('INITIATED','VALIDATED','PENDING_AUTH','AUTHORIZED','POSTED','REJECTED','REVERSED');
  chk('transaction status projection is canonical',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
   WHERE NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT A WHERE A.ACCOUNT_ID=B.ACCOUNT_ID);
  chk('balance projection belongs to real account',v=0);

  SELECT COUNT(*) INTO v FROM (
    SELECT CURRENCY_CODE,COUNT(*) ACCOUNT_COUNT,NVL(SUM(LEDGER_BALANCE),0) LEDGER_BALANCE,
           NVL(SUM(AVAILABLE_BALANCE),0) AVAILABLE_BALANCE,NVL(SUM(BLOCKED_AMOUNT),0) BLOCKED_AMOUNT
      FROM DPS2.DEPOSIT_ACCOUNT_BALANCE GROUP BY CURRENCY_CODE
  );
  chk('currency balance aggregation executes',v>=0);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11NA_DB_VERIFIER_PASS='||p);
  DBMS_OUTPUT.PUT_LINE('PHASE11NA_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21270,'Phase11NA DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11NA_DB_BASELINE_PASS');
END;
/
