SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11I - Step 05 Transaction Processing DB Verifier
PROMPT ============================================================
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER;
  PROCEDURE chk(label VARCHAR2,ok BOOLEAN) IS BEGIN IF ok THEN p:=p+1;DBMS_OUTPUT.PUT_LINE('PASS | '||label);ELSE f:=f+1;DBMS_OUTPUT.PUT_LINE('FAIL | '||label);END IF; END;
  FUNCTION tab(t VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t);RETURN n>0;END;
  FUNCTION con(c VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND CONSTRAINT_NAME=UPPER(c) AND STATUS='ENABLED';RETURN n>0;END;
  FUNCTION seq_ahead(s VARCHAR2,t VARCHAR2,pk VARCHAR2) RETURN BOOLEAN IS n NUMBER; m NUMBER; BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO n; EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0) FROM DPS2.'||t INTO m; RETURN n>m; END;
BEGIN
  chk('DEPOSIT_TRANSACTION exists',tab('DEPOSIT_TRANSACTION'));
  chk('DEPOSIT_TRANSACTION_VALIDATION exists',tab('DEPOSIT_TRANSACTION_VALIDATION'));
  chk('DEPOSIT_TRANSACTION_AUTHORIZATION exists',tab('DEPOSIT_TRANSACTION_AUTHORIZATION'));
  chk('DEPOSIT_TRANSACTION_STATUS_HISTORY exists',tab('DEPOSIT_TRANSACTION_STATUS_HISTORY'));
  chk('DEPOSIT_TRANSACTION_LEG exists',tab('DEPOSIT_TRANSACTION_LEG'));
  chk('DEPOSIT_TRANSFER_DETAIL exists',tab('DEPOSIT_TRANSFER_DETAIL'));
  chk('DEPOSIT_CASH_TRANSACTION_DETAIL exists',tab('DEPOSIT_CASH_TRANSACTION_DETAIL'));
  chk('DEPOSIT_TRANSACTION_REVERSAL exists',tab('DEPOSIT_TRANSACTION_REVERSAL'));
  chk('subledger transaction FK enabled',con('FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID'));
  chk('subledger transaction-leg FK enabled',con('FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_LEG_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION is ahead of transaction PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION','DEPOSIT_TRANSACTION','TRANSACTION_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION_VALIDATION is ahead of validation PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION_VALIDATION','DEPOSIT_TRANSACTION_VALIDATION','TRANSACTION_VALIDATION_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION_AUTHORIZATION is ahead of authorization PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION_AUTHORIZATION','DEPOSIT_TRANSACTION_AUTHORIZATION','TRANSACTION_AUTHORIZATION_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION_STATUS_HISTORY is ahead of history PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION_STATUS_HISTORY','DEPOSIT_TRANSACTION_STATUS_HISTORY','TRANSACTION_STATUS_HISTORY_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION_LEG is ahead of leg PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION_LEG','DEPOSIT_TRANSACTION_LEG','TRANSACTION_LEG_ID'));
  chk('SEQ_DEPOSIT_TRANSFER_DETAIL is ahead of transfer detail PK',seq_ahead('SEQ_DEPOSIT_TRANSFER_DETAIL','DEPOSIT_TRANSFER_DETAIL','TRANSFER_DETAIL_ID'));
  chk('SEQ_DEPOSIT_CASH_TRANSACTION_DETAIL is ahead of cash detail PK',seq_ahead('SEQ_DEPOSIT_CASH_TRANSACTION_DETAIL','DEPOSIT_CASH_TRANSACTION_DETAIL','CASH_TRANSACTION_DETAIL_ID'));
  chk('SEQ_DEPOSIT_TRANSACTION_REVERSAL is ahead of reversal PK',seq_ahead('SEQ_DEPOSIT_TRANSACTION_REVERSAL','DEPOSIT_TRANSACTION_REVERSAL','TRANSACTION_REVERSAL_ID'));
  chk('SEQ_DEPOSIT_SUBLEDGER_ENTRY is ahead of subledger PK',seq_ahead('SEQ_DEPOSIT_SUBLEDGER_ENTRY','DEPOSIT_SUBLEDGER_ENTRY','SUBLEDGER_ENTRY_ID'));

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_STATUS_CODE IN ('PENDING_AUTH','AUTHORIZED','POSTED','REVERSED') AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_VALIDATION V WHERE V.TRANSACTION_ID=T.TRANSACTION_ID AND V.RESULT_CODE IN ('PASS','WARN')) AND T.TRANSACTION_TYPE_CODE<>'REVERSAL';
  chk('operational transactions carry validation evidence',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_STATUS_CODE IN ('AUTHORIZED','POSTED','REVERSED') AND T.TRANSACTION_TYPE_CODE<>'REVERSAL' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_AUTHORIZATION A WHERE A.TRANSACTION_ID=T.TRANSACTION_ID AND A.DECISION_CODE='APPROVED');
  chk('authorized/posted transactions carry authorization evidence',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_STATUS_CODE='POSTED' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_LEG L WHERE L.TRANSACTION_ID=T.TRANSACTION_ID);
  chk('posted transactions have transaction legs',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION_LEG L JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=L.TRANSACTION_ID WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_STATUS_CODE IN ('POSTED','REVERSED') AND L.ACCOUNT_ID IS NOT NULL AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY E WHERE E.TRANSACTION_ID=L.TRANSACTION_ID AND E.TRANSACTION_LEG_ID=L.TRANSACTION_LEG_ID);
  chk('posted account legs trace to 11D subledger',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_TYPE_CODE='TRANSFER' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSFER_DETAIL D WHERE D.TRANSACTION_ID=T.TRANSACTION_ID);
  chk('transfer transactions have transfer detail',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_TYPE_CODE IN ('CASH_DEPOSIT','CASH_WITHDRAWAL') AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_CASH_TRANSACTION_DETAIL D WHERE D.TRANSACTION_ID=T.TRANSACTION_ID);
  chk('cash transactions have cash detail',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION T WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND T.TRANSACTION_STATUS_CODE='REVERSED' AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_TRANSACTION_REVERSAL R WHERE R.ORIGINAL_TRANSACTION_ID=T.TRANSACTION_ID AND R.REVERSAL_STATUS_CODE='POSTED');
  chk('reversed originals trace to posted reversal record',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_TRANSACTION_AUTHORIZATION A JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=A.TRANSACTION_ID WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND A.DECISION_CODE='APPROVED' AND UPPER(A.REQUESTED_BY)=UPPER(A.DECIDED_BY) AND T.TRANSACTION_TYPE_CODE<>'REVERSAL';
  chk('transaction maker and authorizer differ',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY E JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=E.TRANSACTION_ID WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND (E.TRANSACTION_LEG_ID IS NULL OR E.SOURCE_ENTITY_TYPE NOT IN ('DEPOSIT_TRANSACTION','DEPOSIT_TRANSACTION_REVERSAL'));
  chk('transaction-linked subledger trace is complete',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY E JOIN DPS2.DEPOSIT_TRANSACTION_LEG L ON L.TRANSACTION_LEG_ID=E.TRANSACTION_LEG_ID JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=E.TRANSACTION_ID WHERE T.SOURCE_OPENING_FUNDING_ID IS NULL AND E.ENTRY_SEQUENCE_NO<>L.LEG_NO;
  chk('transaction-linked subledger entry sequence matches leg number',v=0);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11I_DB_VERIFIER_PASS='||p); DBMS_OUTPUT.PUT_LINE('PHASE11I_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21199,'Phase 11I DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11I_DB_BASELINE_PASS');
END;
/
