SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11N-B - Steps 01-02 Canonical Closure DB Verifier
PROMPT ============================================================
DECLARE
  p NUMBER:=0; f NUMBER:=0; v NUMBER; v_type VARCHAR2(30); v_len NUMBER; v_null VARCHAR2(1);
  PROCEDURE chk(label VARCHAR2,ok BOOLEAN) IS BEGIN IF ok THEN p:=p+1;DBMS_OUTPUT.PUT_LINE('PASS | '||label);ELSE f:=f+1;DBMS_OUTPUT.PUT_LINE('FAIL | '||label);END IF; END;
  FUNCTION tab(t VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t);RETURN n>0;END;
BEGIN
  SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT' AND COLUMN_NAME='ORG_UNIT_CODE';
  chk('DEPOSIT_ACCOUNT.ORG_UNIT_CODE exists',v=1);
  IF v=1 THEN
    SELECT DATA_TYPE,CHAR_LENGTH,NULLABLE INTO v_type,v_len,v_null FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT' AND COLUMN_NAME='ORG_UNIT_CODE';
    chk('ORG_UNIT_CODE is VARCHAR2(30)',v_type='VARCHAR2' AND v_len=30);
    chk('ORG_UNIT_CODE is mandatory',v_null='N');
  END IF;
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT WHERE ORG_UNIT_CODE IS NULL;
  chk('all accounts have current servicing ORG_UNIT_CODE',v=0);
  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT A JOIN DPS2.DEPOSIT_OPENING_REQUEST R ON R.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID
   WHERE R.ORG_UNIT_CODE IS NOT NULL AND NVL(A.OPENING_ORG_UNIT_CODE,'~')<>R.ORG_UNIT_CODE;
  chk('opening org-unit snapshot matches Opening source',v=0);

  chk('condition override table exists',tab('DEPOSIT_ACCOUNT_CONDITION_OVERRIDE'));
  chk('product history table exists',tab('DEPOSIT_ACCOUNT_PRODUCT_HISTORY'));
  chk('signatory authority table exists',tab('DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY'));
  chk('activation run/check tables exist',tab('DEPOSIT_ACTIVATION_RUN') AND tab('DEPOSIT_ACTIVATION_CHECK'));
  chk('bulk action tables exist',tab('DEPOSIT_ACCOUNT_BULK_ACTION') AND tab('DEPOSIT_ACCOUNT_BULK_ACTION_ITEM'));
  chk('hold/idempotency tables exist',tab('DEPOSIT_ACCOUNT_HOLD') AND tab('DEPOSIT_ACCOUNT_HOLD_HISTORY') AND tab('DEPOSIT_OPERATION_IDEMPOTENCY'));

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_CONDITION_OVERRIDE C
    LEFT JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=C.APPROVAL_REQUEST_ID
   WHERE C.APPROVAL_REQUEST_ID IS NULL OR A.APPROVAL_REQUEST_ID IS NULL
      OR A.OPERATION_TYPE_CODE<>'ACCOUNT_CONDITION_OVERRIDE'
      OR A.ACCOUNT_ID<>C.ACCOUNT_ID
      OR UPPER(A.REQUESTED_BY_USER_ID)=UPPER(A.APPROVER_USER_ID);
  chk('condition overrides keep maker-checker trace',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_PRODUCT_HISTORY H
    LEFT JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=H.APPROVAL_REQUEST_ID
   WHERE H.APPROVAL_REQUEST_ID IS NULL OR A.APPROVAL_REQUEST_ID IS NULL
      OR A.OPERATION_TYPE_CODE<>'ACCOUNT_PRODUCT_CHANGE'
      OR A.ACCOUNT_ID<>H.ACCOUNT_ID
      OR H.FROM_PRODUCT_VERSION_ID=H.TO_PRODUCT_VERSION_ID
      OR UPPER(A.REQUESTED_BY_USER_ID)=UPPER(A.APPROVER_USER_ID);
  chk('product changes keep positive version-change approval trace',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY AU
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT_SIGNATORY S ON S.SIGNATORY_ID=AU.SIGNATORY_ID
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT_PARTY P ON P.ACCOUNT_ID=S.ACCOUNT_ID AND P.PARTY_ID=S.PARTY_ID AND P.STATUS_CODE='ACTIVE'
   WHERE S.SIGNATORY_ID IS NULL OR P.ACCOUNT_PARTY_ID IS NULL;
  chk('signatory authority resolves through active account party',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACTIVATION_RUN R
   WHERE R.RUN_STATUS_CODE='READY' AND (R.READY_FLAG<>1 OR R.BLOCKING_CHECK_COUNT<>0 OR NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACTIVATION_CHECK C WHERE C.ACTIVATION_RUN_ID=R.ACTIVATION_RUN_ID));
  chk('READY activation runs contain non-blocking evidence',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT E
   WHERE E.EVENT_TYPE_CODE='ACTIVATE' AND E.EVENT_STATUS_CODE='EXECUTED'
     AND (E.ACTIVATION_RUN_ID IS NULL
       OR NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACTIVATION_RUN R WHERE R.ACTIVATION_RUN_ID=E.ACTIVATION_RUN_ID AND R.ACCOUNT_ID=E.ACCOUNT_ID AND R.RUN_STATUS_CODE='READY'));
  chk('executed activation events require a coherent READY run',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
   WHERE UPPER(H.ORIGIN_SYSTEM_CODE)='COLLATERAL'
     AND (H.HOLD_REASON_CODE<>'COLLATERAL_PLEDGE' OR H.ORIGIN_EXECUTION_MODE_CODE<>'SERVICE' OR H.RELEASE_POLICY_CODE<>'ORIGIN_ONLY' OR H.ORIGIN_REQUEST_REF IS NULL);
  chk('collateral holds enforce origin-only service contract',v=0);

  SELECT COUNT(*) INTO v FROM (
    SELECT ACCOUNT_ID,OPERATION_TYPE_CODE,ORIGIN_SYSTEM_CODE,NVL(ORIGIN_MODULE_CODE,'~') M,ORIGIN_REQUEST_REF,COUNT(*) C
      FROM DPS2.DEPOSIT_OPERATION_IDEMPOTENCY
     WHERE ORIGIN_SYSTEM_CODE='COLLATERAL' AND OPERATION_TYPE_CODE IN ('HOLD_CREATE','HOLD_RELEASE') AND PROCESSING_STATUS_CODE='COMPLETED'
     GROUP BY ACCOUNT_ID,OPERATION_TYPE_CODE,ORIGIN_SYSTEM_CODE,NVL(ORIGIN_MODULE_CODE,'~'),ORIGIN_REQUEST_REF
    HAVING COUNT(*)>1
  );
  chk('collateral origin request is idempotent across transport keys',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
   WHERE UPPER(H.ORIGIN_SYSTEM_CODE)='COLLATERAL'
     AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD_HISTORY HH WHERE HH.ACCOUNT_HOLD_ID=H.ACCOUNT_HOLD_ID AND HH.ACTION_CODE='CREATE' AND HH.ACTION_SOURCE_SYSTEM_CODE='COLLATERAL');
  chk('collateral hold creation is historically traceable',v=0);

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BULK_ACTION B
   WHERE B.SUCCESS_COUNT<0 OR B.FAILED_COUNT<0 OR B.SUCCESS_COUNT+B.FAILED_COUNT>B.TOTAL_COUNT
      OR (B.ACTION_STATUS_CODE='COMPLETED' AND (B.SUCCESS_COUNT<>B.TOTAL_COUNT OR B.FAILED_COUNT<>0));
  chk('bulk action counters/status are coherent',v=0);

  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11NB_DB_VERIFIER_PASS='||p); DBMS_OUTPUT.PUT_LINE('PHASE11NB_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21329,'Phase 11N-B DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11NB_DB_BASELINE_PASS');
END;
/
