SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11D - Balance + Subledger DB Verifier
PROMPT ============================================================
DECLARE
    v_pass NUMBER:=0; v_fail NUMBER:=0; v NUMBER; v2 NUMBER; v_text VARCHAR2(4000); v_index_ddl CLOB;
    PROCEDURE ok(p_ok BOOLEAN,p_msg VARCHAR2) IS BEGIN IF p_ok THEN v_pass:=v_pass+1; DBMS_OUTPUT.PUT_LINE('PASS | '||p_msg); ELSE v_fail:=v_fail+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||p_msg); END IF; END;
    PROCEDURE table_ok(p_table VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=p_table; ok(v=1,p_table||' exists'); END;
    PROCEDURE index_columns_ok(p_table VARCHAR2,p_columns VARCHAR2,p_label VARCHAR2) IS BEGIN
        SELECT COUNT(*) INTO v
          FROM (
                SELECT IC.INDEX_NAME
                  FROM ALL_IND_COLUMNS IC
                 WHERE IC.INDEX_OWNER='DPS2'
                   AND IC.TABLE_OWNER='DPS2'
                   AND IC.TABLE_NAME=UPPER(p_table)
                 GROUP BY IC.INDEX_NAME
                HAVING LISTAGG(IC.COLUMN_NAME,',') WITHIN GROUP (ORDER BY IC.COLUMN_POSITION)=UPPER(REPLACE(p_columns,' ',''))
               );
        ok(v>=1,p_label||' index coverage exists');
    END;
    PROCEDURE number_24_4(p_table VARCHAR2,p_column VARCHAR2) IS p NUMBER; s NUMBER; BEGIN SELECT DATA_PRECISION,DATA_SCALE INTO p,s FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=p_table AND COLUMN_NAME=p_column; ok(p>=24 AND s>=4,p_table||'.'||p_column||' supports 4-decimal monetary precision'); END;
BEGIN
    table_ok('DEPOSIT_ACCOUNT_BALANCE');
    table_ok('DEPOSIT_SUBLEDGER_ENTRY');
    table_ok('DEPOSIT_BALANCE_RESERVATION');
    table_ok('DEPOSIT_ACCOUNT_HOLD');
    table_ok('DEPOSIT_OPERATION_IDEMPOTENCY');

    number_24_4('DEPOSIT_ACCOUNT_BALANCE','LEDGER_BALANCE');
    number_24_4('DEPOSIT_ACCOUNT_BALANCE','AVAILABLE_BALANCE');
    number_24_4('DEPOSIT_ACCOUNT_BALANCE','BLOCKED_AMOUNT');
    number_24_4('DEPOSIT_ACCOUNT_BALANCE','PENDING_DEBIT_AMOUNT');
    number_24_4('DEPOSIT_SUBLEDGER_ENTRY','AMOUNT');
    number_24_4('DEPOSIT_BALANCE_RESERVATION','AMOUNT');

    SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT A WHERE NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B WHERE B.ACCOUNT_ID=A.ACCOUNT_ID);
    ok(v=0,'every deposit account has Package 17 balance row');

    SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B JOIN DPS2.DEPOSIT_ACCOUNT A ON A.ACCOUNT_ID=B.ACCOUNT_ID WHERE B.CURRENCY_CODE<>A.CURRENCY_CODE;
    ok(v=0,'balance currency matches account currency');

    SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
     WHERE B.BLOCKED_AMOUNT<0 OR B.PENDING_DEBIT_AMOUNT<0 OR B.UNCLEARED_AMOUNT<0 OR B.PENDING_CREDIT_AMOUNT<0;
    ok(v=0,'balance non-ledger control amounts are non-negative');

    SELECT COUNT(*) INTO v
      FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
     WHERE B.BLOCKED_AMOUNT <>
           CASE WHEN EXISTS (
                    SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                     WHERE H.ACCOUNT_ID=B.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                       AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                       AND H.HOLD_TYPE_CODE IN ('FULL','DEBIT_ONLY')
                ) THEN GREATEST(B.LEDGER_BALANCE,0)
                ELSE NVL((SELECT SUM(H.HOLD_AMOUNT) FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                           WHERE H.ACCOUNT_ID=B.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                             AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                             AND H.HOLD_TYPE_CODE='PARTIAL'),0) END;
    ok(v=0,'BLOCKED_AMOUNT reflects active debit-blocking holds');

    SELECT COUNT(*) INTO v
      FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
     WHERE B.PENDING_DEBIT_AMOUNT <>
           NVL((SELECT SUM(R.AMOUNT) FROM DPS2.DEPOSIT_BALANCE_RESERVATION R
                 WHERE R.ACCOUNT_ID=B.ACCOUNT_ID AND R.RESERVATION_STATUS_CODE='ACTIVE'
                   AND (R.EXPIRES_AT IS NULL OR R.EXPIRES_AT>SYSTIMESTAMP)),0);
    ok(v=0,'PENDING_DEBIT_AMOUNT reflects active reservations');

    SELECT COUNT(*) INTO v
      FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
     WHERE B.AVAILABLE_BALANCE <>
           CASE WHEN EXISTS (
                    SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                     WHERE H.ACCOUNT_ID=B.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                       AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                       AND H.HOLD_TYPE_CODE IN ('FULL','DEBIT_ONLY')
                ) THEN 0
                ELSE GREATEST(B.LEDGER_BALANCE
                     - NVL((SELECT SUM(H.HOLD_AMOUNT) FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                            WHERE H.ACCOUNT_ID=B.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                              AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                              AND H.HOLD_TYPE_CODE='PARTIAL'),0)
                     - NVL((SELECT SUM(R.AMOUNT) FROM DPS2.DEPOSIT_BALANCE_RESERVATION R
                            WHERE R.ACCOUNT_ID=B.ACCOUNT_ID AND R.RESERVATION_STATUS_CODE='ACTIVE'
                              AND (R.EXPIRES_AT IS NULL OR R.EXPIRES_AT>SYSTIMESTAMP)),0),0) END;
    ok(v=0,'AVAILABLE_BALANCE formula is consistent');

    SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B
     WHERE B.LAST_SUBLEDGER_ENTRY_ID IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.SUBLEDGER_ENTRY_ID=B.LAST_SUBLEDGER_ENTRY_ID AND S.ACCOUNT_ID=B.ACCOUNT_ID);
    ok(v=0,'LAST_SUBLEDGER_ENTRY_ID resolves to same account');

    SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_ACCOUNT_BALANCE' AND CONSTRAINT_NAME='UK_DEPOSIT_ACCOUNT_BALANCE_ACCOUNT_ID' AND STATUS='ENABLED';
    ok(v=1,'one balance row per account is enforced');

    SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_SUBLEDGER_ENTRY' AND CONSTRAINT_NAME='UK_DEPOSIT_SUBLEDGER_ENTRY_POSTING_REFERENCE' AND STATUS='ENABLED';
    ok(v=1,'posting reference idempotency guard enabled');

    SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS
     WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_SUBLEDGER_ENTRY'
       AND CONSTRAINT_NAME='UK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID_ENTRY_SEQUENCE_NO' AND STATUS='ENABLED';
    ok(v=0,'legacy null-sensitive transaction/sequence constraint removed');

    SELECT COUNT(*) INTO v FROM ALL_INDEXES
     WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_SUBLEDGER_ENTRY'
       AND INDEX_NAME='UX_DEP_SUBLEDGER_TX_SEQ_NN' AND UNIQUENESS='UNIQUE' AND STATUS='VALID';
    ok(v=1,'transaction-scoped subledger sequence unique index enabled');

    -- ALL_IND_EXPRESSIONS.COLUMN_EXPRESSION is LONG on Oracle and cannot be safely filtered with LIKE.
    -- Inspect the function-based index DDL as CLOB instead.
    BEGIN
        SELECT DBMS_METADATA.GET_DDL('INDEX','UX_DEP_SUBLEDGER_TX_SEQ_NN','DPS2')
          INTO v_index_ddl
          FROM DUAL;
        IF DBMS_LOB.INSTR(v_index_ddl,'CASE')>0
           AND DBMS_LOB.INSTR(v_index_ddl,'TRANSACTION_ID')>0
           AND DBMS_LOB.INSTR(v_index_ddl,'ENTRY_SEQUENCE_NO')>0
           AND DBMS_LOB.INSTR(v_index_ddl,'IS NOT NULL')>0 THEN
            v:=1;
        ELSE
            v:=0;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        v:=0;
    END;
    ok(v=1,'transaction-scoped unique index excludes NULL transaction postings');

    SELECT COUNT(*) INTO v FROM (
        SELECT TRANSACTION_ID,ENTRY_SEQUENCE_NO
          FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY
         WHERE TRANSACTION_ID IS NOT NULL
         GROUP BY TRANSACTION_ID,ENTRY_SEQUENCE_NO
        HAVING COUNT(*)>1
    );
    ok(v=0,'non-null transaction entry sequence remains unique');

    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_BALANCE_RESERVATION' AND CONSTRAINT_NAME='CHK_DEPOSIT_BALANCE_RESERVATION_RESERVATION_STATUS_CODE';
    ok(INSTR(v_text,'''ACTIVE''')>0 AND INSTR(v_text,'''CONSUMED''')>0 AND INSTR(v_text,'''RELEASED''')>0 AND INSTR(v_text,'''EXPIRED''')>0,'reservation lifecycle contract exists');

    SELECT SEARCH_CONDITION_VC INTO v_text FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME='DEPOSIT_BALANCE_RESERVATION' AND CONSTRAINT_NAME='CHK_DEPOSIT_BALANCE_RESERVATION_RESERVATION_TYPE_CODE';
    ok(INSTR(v_text,'''DEBIT_AUTHORIZATION''')>0 AND INSTR(v_text,'''CLOSURE''')>0,'reservation type contract exists');

    SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY WHERE SOURCE_ENTITY_TYPE='BALANCE_MIGRATION' AND POSTING_REFERENCE LIKE 'PH11D-MIG-%';
    SELECT COUNT(*) INTO v2 FROM DPS2.DEPOSIT_ACCOUNT A
     WHERE NVL(A.LEDGER_BALANCE,0)<>0
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
                        WHERE S.ACCOUNT_ID=A.ACCOUNT_ID AND S.SOURCE_ENTITY_TYPE<>'BALANCE_MIGRATION');
    ok(v>=v2,'legacy non-zero balances without prior Package 17 trace have migration subledger baseline');

    SELECT COUNT(*) INTO v
      FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
      JOIN DPS2.DEPOSIT_ACCOUNT_BALANCE B ON B.ACCOUNT_ID=S.ACCOUNT_ID
     WHERE S.SOURCE_ENTITY_TYPE='BALANCE_MIGRATION'
       AND S.POSTING_REFERENCE='PH11D-MIG-'||S.ACCOUNT_ID
       AND (S.AMOUNT<>ABS(B.LEDGER_BALANCE)
            OR S.DEBIT_CREDIT_CODE<>CASE WHEN B.LEDGER_BALANCE<0 THEN 'DEBIT' ELSE 'CREDIT' END);
    ok(v=0,'migration subledger baseline agrees with cutover ledger balance');

    index_columns_ok('DEPOSIT_SUBLEDGER_ENTRY','ACCOUNT_ID,POSTED_AT','subledger account/posted-at');
    index_columns_ok('DEPOSIT_BALANCE_RESERVATION','ACCOUNT_ID,RESERVATION_STATUS_CODE,EXPIRES_AT','reservation account/status/expiry');

    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('PHASE11D_DB_VERIFIER_PASS='||v_pass);
    DBMS_OUTPUT.PUT_LINE('PHASE11D_DB_VERIFIER_FAIL='||v_fail);
    IF v_fail>0 THEN RAISE_APPLICATION_ERROR(-21149,'Phase 11D DB verifier failed: '||v_fail); END IF;
    DBMS_OUTPUT.PUT_LINE('PHASE11D_DB_BASELINE_PASS');
END;
/
