SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
DECLARE
  p NUMBER:=0; f NUMBER:=0; c NUMBER;
  PROCEDURE chk(cond BOOLEAN,msg VARCHAR2) IS BEGIN IF cond THEN p:=p+1; DBMS_OUTPUT.PUT_LINE('PASS | '||msg); ELSE f:=f+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||msg); END IF; END;
  FUNCTION table_exists(n VARCHAR2) RETURN BOOLEAN IS x NUMBER; BEGIN SELECT COUNT(*) INTO x FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=n; RETURN x=1; END;
  FUNCTION col_exists(t VARCHAR2,n VARCHAR2) RETURN BOOLEAN IS x NUMBER; BEGIN SELECT COUNT(*) INTO x FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=t AND COLUMN_NAME=n; RETURN x=1; END;
BEGIN
  chk(table_exists('DEPOSIT_ACCOUNT_PARTY'),'DEPOSIT_ACCOUNT_PARTY exists');
  chk(table_exists('DEPOSIT_ACCOUNT_CONTACT'),'DEPOSIT_ACCOUNT_CONTACT exists');
  chk(table_exists('DEPOSIT_ACCOUNT_SERVICING_HISTORY'),'DEPOSIT_ACCOUNT_SERVICING_HISTORY exists');
  chk(col_exists('DEPOSIT_ACCOUNT','ACCOUNT_NAME'),'DEPOSIT_ACCOUNT.ACCOUNT_NAME exists');
  chk(col_exists('DEPOSIT_ACCOUNT','OPENING_ORG_UNIT_CODE'),'DEPOSIT_ACCOUNT.OPENING_ORG_UNIT_CODE exists');
  chk(col_exists('DEPOSIT_ACCOUNT_PARTY','SOURCE_OPENING_PARTY_ID'),'Account Party traceability exists');
  SELECT COUNT(*) INTO c FROM DPS2.DEPOSIT_ACCOUNT A JOIN DPS2.DEPOSIT_OPENING_PARTY OP ON OP.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID WHERE NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PARTY AP WHERE AP.SOURCE_OPENING_PARTY_ID=OP.OPENING_PARTY_ID);
  chk(c=0,'all opening parties materialized to account party');
  SELECT COUNT(*) INTO c FROM DPS2.DEPOSIT_ACCOUNT_PARTY WHERE IS_PRIMARY NOT IN (0,1); chk(c=0,'account party primary flags valid');
  SELECT COUNT(*) INTO c FROM DPS2.DEPOSIT_ACCOUNT_PARTY WHERE OWNERSHIP_PERCENT IS NOT NULL AND (OWNERSHIP_PERCENT<0 OR OWNERSHIP_PERCENT>100); chk(c=0,'account party ownership percentages valid');
  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11B_DB_VERIFIER_PASS='||p); DBMS_OUTPUT.PUT_LINE('PHASE11B_DB_VERIFIER_FAIL='||f);
  IF f>0 THEN RAISE_APPLICATION_ERROR(-21121,'Phase 11B DB verifier failed: '||f); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11B_DB_BASELINE_PASS');
END;
/
