SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 0.11.0 - Phase 11N Steps 11-17 Rapid Completion DB Verifier
PROMPT ============================================================
DECLARE
  v_pass NUMBER:=0; v_fail NUMBER:=0; v NUMBER;
  PROCEDURE ok(p VARCHAR2) IS BEGIN v_pass:=v_pass+1; DBMS_OUTPUT.PUT_LINE('PASS | '||p); END;
  PROCEDURE bad(p VARCHAR2,n NUMBER) IS BEGIN v_fail:=v_fail+1; DBMS_OUTPUT.PUT_LINE('FAIL | '||p||' violations='||n); END;
  PROCEDURE assert_zero(p VARCHAR2, q VARCHAR2) IS BEGIN EXECUTE IMMEDIATE q INTO v; IF v=0 THEN ok(p); ELSE bad(p,v); END IF; END;
  PROCEDURE assert_table(p VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); IF v=1 THEN ok(p||' exists'); ELSE bad(p||' exists',1-v); END IF; END;
  PROCEDURE assert_seq(p VARCHAR2,t VARCHAR2,pk VARCHAR2) IS mx NUMBER; lv NUMBER; BEGIN EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0) FROM DPS2.'||t INTO mx; SELECT LAST_NUMBER INTO lv FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); IF lv>mx THEN ok(p||' ahead of PK'); ELSE bad(p||' ahead of PK',1); END IF; EXCEPTION WHEN NO_DATA_FOUND THEN bad(p||' exists',1); END;
BEGIN
  assert_table('DEPOSIT_RESERVE_REQUIREMENT'); assert_table('DEPOSIT_RESERVE_POSITION'); assert_table('DEPOSIT_REGULATORY_REPORT'); assert_table('DEPOSIT_REGULATORY_REPORT_ITEM');
  assert_table('DEPOSIT_ACCOUNT_FEE_OVERRIDE'); assert_table('DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT'); assert_table('DEPOSIT_TAX_ADJUSTMENT'); assert_table('DEPOSIT_TAX_LIABILITY'); assert_table('DEPOSIT_TAX_PAYMENT'); assert_table('DEPOSIT_TAX_RECONCILIATION');
  assert_table('CORRESPONDENT_RECONCILIATION_PROFILE'); assert_table('DEPOSIT_LOTTERY_DRAW'); assert_table('DEPOSIT_LOTTERY_ENTRY'); assert_table('DEPOSIT_LOTTERY_WINNER');
  assert_seq('SEQ_DEPOSIT_ACCOUNT_FEE_OVERRIDE','DEPOSIT_ACCOUNT_FEE_OVERRIDE','ACCOUNT_FEE_OVERRIDE_ID');
  assert_seq('SEQ_DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT','DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT','CUSTOMER_PACKAGE_ENROLLMENT_ID');
  assert_seq('SEQ_DEPOSIT_TAX_ADJUSTMENT','DEPOSIT_TAX_ADJUSTMENT','TAX_ADJUSTMENT_ID');
  assert_seq('SEQ_DEPOSIT_LOTTERY_DRAW','DEPOSIT_LOTTERY_DRAW','LOTTERY_DRAW_ID');
  assert_seq('SEQ_DEPOSIT_LOTTERY_ENTRY','DEPOSIT_LOTTERY_ENTRY','LOTTERY_ENTRY_ID');
  assert_seq('SEQ_DEPOSIT_LOTTERY_WINNER','DEPOSIT_LOTTERY_WINNER','LOTTERY_WINNER_ID');
  assert_zero('fee override approval trace is coherent',q'[SELECT COUNT(*) FROM DPS2.DEPOSIT_ACCOUNT_FEE_OVERRIDE F LEFT JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=F.APPROVAL_REQUEST_ID WHERE F.APPROVAL_REQUEST_ID IS NULL OR A.APPROVAL_REQUEST_ID IS NULL OR A.ACCOUNT_ID<>F.ACCOUNT_ID]');
  assert_zero('tax adjustment approval trace is coherent',q'[SELECT COUNT(*) FROM DPS2.DEPOSIT_TAX_ADJUSTMENT J LEFT JOIN DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST A ON A.APPROVAL_REQUEST_ID=J.APPROVAL_REQUEST_ID WHERE J.APPROVAL_REQUEST_ID IS NOT NULL AND A.APPROVAL_REQUEST_ID IS NULL]');
  assert_zero('lottery entry enrollment program matches draw program',q'[SELECT COUNT(*) FROM DPS2.DEPOSIT_LOTTERY_ENTRY E JOIN DPS2.DEPOSIT_LOTTERY_DRAW D ON D.LOTTERY_DRAW_ID=E.LOTTERY_DRAW_ID JOIN DPS2.DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE D.PROGRAM_ID<>R.PROGRAM_ID]');
  assert_zero('paid lottery winner points to reward prize Step05 transaction',q'[SELECT COUNT(*) FROM DPS2.DEPOSIT_LOTTERY_WINNER W LEFT JOIN DPS2.DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=W.PAYMENT_TRANSACTION_ID WHERE W.PAYMENT_TRANSACTION_ID IS NOT NULL AND (T.TRANSACTION_ID IS NULL OR T.TRANSACTION_TYPE_CODE<>'REWARD_PRIZE_PAYMENT' OR T.TRANSACTION_STATUS_CODE<>'POSTED')]');
  assert_zero('reward prize transaction has account subledger trace',q'[SELECT COUNT(*) FROM DPS2.DEPOSIT_LOTTERY_WINNER W JOIN DPS2.DEPOSIT_LOTTERY_ENTRY E ON E.LOTTERY_ENTRY_ID=W.LOTTERY_ENTRY_ID JOIN DPS2.DEPOSIT_REWARD_ENROLLMENT R ON R.REWARD_ENROLLMENT_ID=E.REWARD_ENROLLMENT_ID WHERE W.PAYMENT_TRANSACTION_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.TRANSACTION_ID=W.PAYMENT_TRANSACTION_ID AND S.ACCOUNT_ID=R.ACCOUNT_ID)]');
  DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('PHASE11N_RAPID_DB_VERIFIER_PASS='||v_pass);
  DBMS_OUTPUT.PUT_LINE('PHASE11N_RAPID_DB_VERIFIER_FAIL='||v_fail);
  IF v_fail>0 THEN RAISE_APPLICATION_ERROR(-21419,'Phase11N rapid DB verifier failed: '||v_fail); END IF;
  DBMS_OUTPUT.PUT_LINE('PHASE11N_RAPID_DB_BASELINE_PASS');
END;
/
