package com.behsazan.corebanking.deposit.account.term.application;

import com.behsazan.corebanking.deposit.account.balance.application.DepositBalanceService;
import com.behsazan.corebanking.deposit.account.balance.domain.DepositBalanceModels.PostEntryRequest;
import com.behsazan.corebanking.deposit.account.closure.application.DepositClosureService;
import com.behsazan.corebanking.deposit.account.closure.domain.DepositClosureModels.ClosureRequest;
import com.behsazan.corebanking.deposit.account.error.DepositAccountLifecycleException;
import com.behsazan.corebanking.deposit.account.error.DepositAccountNotFoundException;
import com.behsazan.corebanking.deposit.account.term.domain.DepositTermModels.*;
import com.behsazan.corebanking.deposit.account.term.oracle.DepositTermRepository;
import com.behsazan.corebanking.deposit.account.term.oracle.DepositTermRepository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.*;

@Service
public class DepositTermService {
    private static final Set<String> TERM_FAMILIES=Set.of("SHORT_TERM_DEPOSIT","LONG_TERM_DEPOSIT");
    private static final Set<String> INSTRUCTIONS=Set.of("RENEW_PRINCIPAL","RENEW_PRINCIPAL_PAY_PROFIT","PAY_TO_ACCOUNT","CLOSE_AND_SETTLE","WAIT_INSTRUCTION");
    private static final Set<String> SOURCES=Set.of("CUSTOMER","PRODUCT_DEFAULT","ACCOUNT_SERVICING");
    private final DepositTermRepository repository; private final DepositBalanceService balanceService; private final DepositClosureService closureService;
    public DepositTermService(DepositTermRepository repository,DepositBalanceService balanceService,DepositClosureService closureService){this.repository=repository;this.balanceService=balanceService;this.closureService=closureService;}

    @Transactional(readOnly=true)
    public TermOperationsView get(long accountId){requireTermAccount(accountId,false);return state(accountId);}

    @Transactional
    public TermActionResponse updateInstruction(long accountId,UpdateMaturityInstructionRequest request,String actor,String correlationId,String idempotencyKey){
        AccountRow a=requireTermAccount(accountId,true); TermLock t=requireTerm(accountId);
        String code=upper(required(request==null?null:request.instructionCode(),"INSTRUCTION_CODE")); if(!INSTRUCTIONS.contains(code))throw new IllegalArgumentException("INSTRUCTION_CODE نامعتبر است.");
        String src=upper(request.instructionSourceCode()==null?"CUSTOMER":request.instructionSourceCode()); if(!SOURCES.contains(src))throw new IllegalArgumentException("INSTRUCTION_SOURCE_CODE نامعتبر است.");
        String ref=trim(request.settlementAccountReference()); if("PAY_TO_ACCOUNT".equals(code)&&request.settlementAccountId()==null&&ref==null)throw new IllegalArgumentException("برای PAY_TO_ACCOUNT حساب مقصد الزامی است.");
        String h=hash("INSTRUCTION|"+accountId+"|"+code+"|"+src+"|"+request.settlementAccountId()+"|"+ref+"|"+request.expectedRecordVersion());
        if(replayOrClaim(idempotencyKey,accountId,"TERM_MATURITY_INSTRUCTION",h,actor,correlationId))return new TermActionResponse(state(accountId),t.termContractId(),true);
        if(repository.updateInstruction(t.termContractId(),code,src,request.settlementAccountId(),ref,request.expectedRecordVersion(),actor)!=1)throw lifecycle("قرارداد مدت‌دار همزمان تغییر کرده است.","DEPOSIT_TERM_CONTRACT.RECORD_VERSION",String.valueOf(request.expectedRecordVersion()));
        repository.completeIdempotency(idempotencyKey,"TERM:"+t.termContractId()); return new TermActionResponse(state(accountId),t.termContractId(),false);
    }

    @Transactional
    public TermActionResponse requestPartialWithdrawal(long accountId,PartialWithdrawalRequest request,String actor,String correlationId,String idempotencyKey){
        requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);BigDecimal amount=request==null?null:request.amount();if(amount==null||amount.signum()<=0||amount.compareTo(t.principalAmount())>=0)throw new IllegalArgumentException("برداشت بخشی باید مثبت و کمتر از اصل قرارداد باشد.");
        String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);
        String h=hash("PARTIAL|"+accountId+"|"+amount.toPlainString()+"|"+approver+"|"+org);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"PARTIAL:"),true);
        long id=repository.next("SEQ_DEPOSIT_TERM_PARTIAL_WITHDRAWAL"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_PARTIAL_WITHDRAWAL","DEPOSIT_TERM_PARTIAL_WITHDRAWAL",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertPartialWithdrawal(id,t.termContractId(),accountId,amount,t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);
    }
    @Transactional public TermActionResponse approvePartialWithdrawal(long accountId,long id,String actor,String correlationId,String idempotencyKey){PartialWithdrawal w=partial(accountId,id);String h=hash("PARTIAL_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"REQUESTED".equals(upper(w.statusCode())))throw lifecycle("برداشت بخشی در وضعیت قابل تأیید نیست.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());if(repository.approve(Objects.requireNonNull(w.approvalRequestId()),actor)!=1)throw lifecycle("تأیید فقط توسط Approver تعیین‌شده ممکن است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markPartialApproved(id,actor)!=1)throw lifecycle("وضعیت برداشت بخشی همزمان تغییر کرده است.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executePartialWithdrawal(long accountId,long id,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);PartialWithdrawal w=partial(accountId,id);String h=hash("PARTIAL_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"ACTIVE".equals(upper(a.status())))throw lifecycle("برداشت بخشی فقط روی حساب ACTIVE مجاز است.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",a.status());if(!"APPROVED".equals(upper(w.statusCode()))||!"APPROVED".equals(upper(w.approvalStatusCode())))throw lifecycle("برداشت بخشی باید APPROVED باشد.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());if(w.requestedAmount().compareTo(t.principalAmount())>=0)throw lifecycle("برداشت بخشی نمی‌تواند کل اصل قرارداد را مصرف کند؛ از Early Termination استفاده کنید.","DEPOSIT_TERM_CONTRACT.PRINCIPAL_AMOUNT",t.principalAmount().toPlainString());
        BigDecimal after=t.principalAmount().subtract(w.requestedAmount());String postKey=idempotencyKey+"-POST";balanceService.post(accountId,new PostEntryRequest("DEBIT",w.requestedAmount(),a.currencyCode(),LocalDate.now(ZoneOffset.UTC),LocalDate.now(ZoneOffset.UTC),"TERM-PW-"+id,"TERM_PARTIAL_WITHDRAWAL",id,null,null),actor,correlationId,postKey);if(repository.executePartial(id,t.termContractId(),w.requestedAmount(),after,LocalDate.now(ZoneOffset.UTC),actor)!=1)throw lifecycle("اجرای برداشت بخشی ناموفق بود.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional public TermActionResponse requestRenewal(long accountId,RenewalRequest request,String actor,String correlationId,String idempotencyKey){requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);long newPv=request.newProductVersionId()==null?t.productVersionId():request.newProductVersionId();requireTermProduct(newPv);LocalDate start=t.maturityDate(),newMat=Objects.requireNonNull(request.newMaturityDate(),"NEW_MATURITY_DATE الزامی است.");if(!newMat.isAfter(start))throw new IllegalArgumentException("NEW_MATURITY_DATE باید بعد از سررسید فعلی باشد.");String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);String h=hash("RENEW|"+accountId+"|"+newPv+"|"+newMat+"|"+request.newRate()+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"RENEWAL:"),true);long id=repository.next("SEQ_DEPOSIT_TERM_RENEWAL"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_RENEWAL","DEPOSIT_TERM_RENEWAL",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertRenewal(id,t.termContractId(),t.renewalCount()+1,t.productVersionId(),newPv,t.maturityDate(),start,newMat,t.contractRate(),request.newRate(),t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse approveRenewal(long accountId,long id,String actor,String correlationId,String idempotencyKey){Renewal r=renewal(accountId,id);String h=hash("RENEW_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(repository.approve(Objects.requireNonNull(r.approvalRequestId()),actor)!=1)throw lifecycle("Renewal فقط توسط Approver تعیین‌شده قابل تأیید است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markRenewalApproved(id,actor)!=1)throw lifecycle("Renewal در وضعیت REQUESTED نیست.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executeRenewal(long accountId,long id,String actor,String correlationId,String idempotencyKey){requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);Renewal r=renewal(accountId,id);String h=hash("RENEW_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"APPROVED".equals(upper(r.statusCode()))||!"APPROVED".equals(upper(r.approvalStatusCode())))throw lifecycle("Renewal باید APPROVED باشد.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());if(LocalDate.now(ZoneOffset.UTC).isBefore(r.fromMaturityDate()))throw lifecycle("اجرای Renewal قبل از سررسید مجاز نیست.","DEPOSIT_TERM_RENEWAL.FROM_MATURITY_DATE",r.fromMaturityDate().toString());if(repository.executeRenewal(id,t.termContractId(),r.newProductVersionId(),r.newStartDate(),r.newMaturityDate(),r.newRate(),r.renewedPrincipal(),actor)!=1)throw lifecycle("اجرای Renewal ناموفق بود.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());repository.insertMaturityEvent(repository.next("SEQ_DEPOSIT_MATURITY_EVENT"),t.termContractId(),accountId,r.fromMaturityDate(),t.instructionCode(),r.renewedPrincipal(),"RENEWED",id,actor);repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional public TermActionResponse requestConversion(long accountId,ConversionRequest request,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);requireTermProduct(request.toProductVersionId());if(request.toProductVersionId()==t.productVersionId())throw new IllegalArgumentException("محصول مقصد باید با محصول فعلی متفاوت باشد.");String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);LocalDate eff=request.effectiveDate()==null?LocalDate.now(ZoneOffset.UTC):request.effectiveDate();String h=hash("CONVERT|"+accountId+"|"+request.toProductVersionId()+"|"+eff+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"CONVERSION:"),true);long id=repository.next("SEQ_DEPOSIT_TERM_CONVERSION"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_CONVERSION","DEPOSIT_TERM_CONVERSION",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertConversion(id,t.termContractId(),accountId,a.currentProductVersionId(),request.toProductVersionId(),eff,t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse approveConversion(long accountId,long id,String actor,String correlationId,String idempotencyKey){TermConversion c=conversion(accountId,id);String h=hash("CONVERT_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(repository.approve(Objects.requireNonNull(c.approvalRequestId()),actor)!=1)throw lifecycle("Conversion فقط توسط Approver تعیین‌شده قابل تأیید است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markConversionApproved(id,actor)!=1)throw lifecycle("Conversion در وضعیت REQUESTED نیست.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executeConversion(long accountId,long id,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);TermConversion c=conversion(accountId,id);String h=hash("CONVERT_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"APPROVED".equals(upper(c.statusCode()))||!"APPROVED".equals(upper(c.approvalStatusCode())))throw lifecycle("Conversion باید APPROVED باشد.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());if(repository.executeConversion(id,t.termContractId(),accountId,c.fromProductVersionId(),c.toProductVersionId(),c.effectiveDate(),Objects.requireNonNull(c.approvalRequestId()),actor)!=1)throw lifecycle("اجرای Conversion ناموفق بود.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional public TermActionResponse requestEarlyTermination(long accountId,EarlyTerminationRequest request,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);if(!"ACTIVE".equals(upper(a.status())))throw lifecycle("فسخ پیش از موعد فقط برای حساب ACTIVE مجاز است.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",a.status());String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE"),settlement=required(request.settlementAccountReference(),"SETTLEMENT_ACCOUNT_REFERENCE");makerChecker(actor,approver);LocalDate dt=request.terminationDate()==null?LocalDate.now(ZoneOffset.UTC):request.terminationDate();String h=hash("EARLY_TERM|"+accountId+"|"+dt+"|"+settlement+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_EARLY_TERMINATION_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"EARLY:"),true);long id=repository.next("SEQ_DEPOSIT_TERM_EARLY_TERMINATION");var closure=closureService.requestClosure(accountId,new ClosureRequest("EARLY_TERMINATION","TERM_EARLY_TERMINATION",dt,settlement,approver,org),actor,correlationId,idempotencyKey+"-CLOSURE");Long approval=closure.closure().approvalRequestId();repository.insertEarlyTermination(id,t.termContractId(),accountId,dt,t.principalAmount(),Objects.requireNonNull(approval),actor);repository.insertSettlement(repository.next("SEQ_DEPOSIT_TERM_SETTLEMENT"),t.termContractId(),"EARLY_TERMINATION",t.principalAmount(),settlement,actor);repository.linkEarlyTerminationClosure(id,closure.closure().accountClosureId(),actor);repository.completeIdempotency(idempotencyKey,"EARLY:"+id);return new TermActionResponse(state(accountId),id,false);}

    private TermOperationsView state(long accountId){return new TermOperationsView(repository.term(accountId).orElseThrow(()->lifecycle("قرارداد مدت‌دار فعال برای حساب یافت نشد.","DEPOSIT_TERM_CONTRACT","missing")),repository.maturityEvents(accountId),repository.renewals(accountId),repository.partials(accountId),repository.conversions(accountId),repository.earlyTerminations(accountId),repository.settlements(accountId));}
    private AccountRow requireTermAccount(long accountId,boolean lock){AccountRow a=repository.account(accountId,lock).orElseThrow(()->new DepositAccountNotFoundException("حساب سپرده با شناسه "+accountId+" یافت نشد."));if(!TERM_FAMILIES.contains(upper(a.productFamilyCode())))throw lifecycle("عملیات 11F فقط برای سپرده کوتاه‌مدت/بلندمدت مجاز است.","PRODUCT_FAMILY_CODE",a.productFamilyCode());return a;}
    private TermLock requireTerm(long accountId){return repository.lockTerm(accountId).orElseThrow(()->lifecycle("قرارداد مدت‌دار فعال یافت نشد؛ migration فاز 11F را اجرا کنید.","DEPOSIT_TERM_CONTRACT.ACCOUNT_ID",String.valueOf(accountId)));}
    private void requireTermProduct(long pv){String f=repository.productFamily(pv).orElseThrow(()->new IllegalArgumentException("Product Version مقصد یافت نشد."));if(!TERM_FAMILIES.contains(upper(f)))throw new IllegalArgumentException("تبدیل/تمدید فقط به محصول SHORT_TERM_DEPOSIT یا LONG_TERM_DEPOSIT مجاز است.");}
    private PartialWithdrawal partial(long aid,long id){return repository.partials(aid).stream().filter(x->x.partialWithdrawalId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Partial Withdrawal یافت نشد."));}
    private Renewal renewal(long aid,long id){return repository.renewals(aid).stream().filter(x->x.termRenewalId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Renewal یافت نشد."));}
    private TermConversion conversion(long aid,long id){return repository.conversions(aid).stream().filter(x->x.termConversionId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Conversion یافت نشد."));}
    private void makerChecker(String maker,String checker){if(maker.equals(checker))throw new IllegalArgumentException("Maker و Approver باید متفاوت باشند.");}
    private boolean replayOrClaim(String key,long accountId,String operation,String hash,String actor,String corr){if(key==null||key.isBlank())throw new IllegalArgumentException("X-Idempotency-Key الزامی است.");var x=repository.findIdempotency(key);if(x.isPresent()){IdempotencyRow r=x.get();if(!Objects.equals(r.accountId(),accountId)||!operation.equals(r.operationType())||!hash.equals(r.payloadHash()))throw new IllegalArgumentException("Idempotency Key با درخواست دیگری استفاده شده است.");if("COMPLETED".equals(r.processingStatus()))return true;throw lifecycle("درخواست با همین Idempotency Key در حال پردازش است.","DEPOSIT_OPERATION_IDEMPOTENCY.PROCESSING_STATUS_CODE",r.processingStatus());}repository.insertIdempotency(key,accountId,operation,hash,actor,corr);return false;}
    private long parseResult(String key,String prefix){String ref=repository.findIdempotency(key).orElseThrow().resultReference();if(ref==null||!ref.startsWith(prefix))throw new IllegalArgumentException("Idempotency result نامعتبر است.");return Long.parseLong(ref.substring(prefix.length()));}
    private static String approvalKey(String key){return key.length()<=118?key+"-APPROVAL":key.substring(0,118)+"-APPROVAL";}
    private static String required(String s,String field){String v=trim(s);if(v==null)throw new IllegalArgumentException(field+" الزامی است.");return v;}
    private static String trim(String s){return s==null||s.isBlank()?null:s.trim();}private static String upper(String s){return s==null?null:s.trim().toUpperCase(Locale.ROOT);}
    private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static DepositAccountLifecycleException lifecycle(String msg,String k,String v){return new DepositAccountLifecycleException(msg,Map.of(k,Objects.toString(v,"null")));}
}
