package com.behsazan.corebanking.deposit.account.term.application;

import com.behsazan.corebanking.deposit.account.balance.application.DepositBalanceService;
import com.behsazan.corebanking.deposit.account.balance.domain.DepositBalanceModels.PostEntryRequest;
import com.behsazan.corebanking.deposit.account.closure.application.DepositClosureService;
import com.behsazan.corebanking.deposit.account.closure.domain.DepositClosureModels.ClosureRequest;
import com.behsazan.corebanking.deposit.account.error.DepositAccountLifecycleException;
import com.behsazan.corebanking.deposit.account.error.DepositAccountNotFoundException;
import com.behsazan.corebanking.deposit.account.term.domain.DepositTermModels.*;
import com.behsazan.corebanking.deposit.account.profit.application.DepositProfitService;
import com.behsazan.corebanking.deposit.account.term.oracle.DepositTermRepository;
import com.behsazan.corebanking.deposit.account.term.oracle.DepositTermRepository.*;
import com.behsazan.corebanking.deposit.account.transaction.application.DepositTransactionService;
import com.behsazan.corebanking.deposit.account.transaction.domain.DepositTransactionModels.DerivedTransactionLeg;
import com.behsazan.corebanking.deposit.account.transaction.domain.DepositTransactionModels.DerivedTransactionRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.*;

@Service
public class DepositTermService {
    private static final Set<String> TERM_FAMILIES=Set.of("SHORT_TERM_DEPOSIT","LONG_TERM_DEPOSIT");
    private static final Set<String> INSTRUCTIONS=Set.of("RENEW_PRINCIPAL","RENEW_PRINCIPAL_PAY_PROFIT","PAY_TO_ACCOUNT","CLOSE_AND_SETTLE","WAIT_INSTRUCTION");
    private static final Set<String> SOURCES=Set.of("CUSTOMER","PRODUCT_DEFAULT","ACCOUNT_SERVICING");
    private final DepositTermRepository repository; private final DepositBalanceService balanceService; private final DepositClosureService closureService; private final DepositTransactionService transactionService; private final DepositProfitService profitService;
    public DepositTermService(DepositTermRepository repository,DepositBalanceService balanceService,DepositClosureService closureService,DepositTransactionService transactionService,DepositProfitService profitService){this.repository=repository;this.balanceService=balanceService;this.closureService=closureService;this.transactionService=transactionService;this.profitService=profitService;}

    @Transactional(readOnly=true)
    public TermOperationsView get(long accountId){requireTermAccount(accountId,false);return state(accountId);}

    @Transactional
    public TermActionResponse updateInstruction(long accountId,UpdateMaturityInstructionRequest request,String actor,String correlationId,String idempotencyKey){
        AccountRow a=requireTermAccount(accountId,true); TermLock t=requireTerm(accountId);
        String code=upper(required(request==null?null:request.instructionCode(),"INSTRUCTION_CODE")); if(!INSTRUCTIONS.contains(code))throw new IllegalArgumentException("INSTRUCTION_CODE نامعتبر است.");
        String src=upper(request.instructionSourceCode()==null?"CUSTOMER":request.instructionSourceCode()); if(!SOURCES.contains(src))throw new IllegalArgumentException("INSTRUCTION_SOURCE_CODE نامعتبر است.");
        String ref=trim(request.settlementAccountReference()); if("PAY_TO_ACCOUNT".equals(code)&&request.settlementAccountId()==null&&ref==null)throw new IllegalArgumentException("برای PAY_TO_ACCOUNT حساب مقصد الزامی است.");
        String h=hash("INSTRUCTION|"+accountId+"|"+code+"|"+src+"|"+request.settlementAccountId()+"|"+ref+"|"+request.expectedRecordVersion());
        if(replayOrClaim(idempotencyKey,accountId,"TERM_MATURITY_INSTRUCTION",h,actor,correlationId))return new TermActionResponse(state(accountId),t.termContractId(),true);
        if(repository.updateInstruction(t.termContractId(),code,src,request.settlementAccountId(),ref,request.expectedRecordVersion(),actor)!=1)throw lifecycle("قرارداد مدت‌دار همزمان تغییر کرده است.","DEPOSIT_TERM_CONTRACT.RECORD_VERSION",String.valueOf(request.expectedRecordVersion()));
        repository.completeIdempotency(idempotencyKey,"TERM:"+t.termContractId()); return new TermActionResponse(state(accountId),t.termContractId(),false);
    }

    @Transactional
    public TermActionResponse executeMaturity(long accountId,String actor,String correlationId,String idempotencyKey){
        AccountRow account=requireTermAccount(accountId,true);
        TermContract current=repository.term(accountId).orElseThrow(()->lifecycle("قرارداد مدت‌دار برای حساب یافت نشد.","DEPOSIT_TERM_CONTRACT.ACCOUNT_ID",String.valueOf(accountId)));
        if(!"ACTIVE".equals(upper(current.statusCode()))){
            MaturityEvent prior=repository.maturityEvent(current.termContractId(),current.maturityDate()).orElse(null);
            if(prior!=null&&!"PENDING".equals(upper(prior.actionResultCode())))return new TermActionResponse(state(accountId),prior.maturityEventId(),true);
            throw lifecycle("قرارداد مدت‌دار برای اجرای سررسید ACTIVE نیست.","DEPOSIT_TERM_CONTRACT.STATUS_CODE",current.statusCode());
        }
        TermLock t=requireTerm(accountId);LocalDate businessDate=LocalDate.now(ZoneOffset.UTC);
        if(businessDate.isBefore(t.maturityDate()))throw lifecycle("اجرای دستور سررسید قبل از MATURITY_DATE مجاز نیست.","DEPOSIT_TERM_CONTRACT.MATURITY_DATE",t.maturityDate().toString());
        MaturityEvent prior=repository.maturityEvent(t.termContractId(),t.maturityDate()).orElse(null);
        if(prior!=null&&!"PENDING".equals(upper(prior.actionResultCode())))return new TermActionResponse(state(accountId),prior.maturityEventId(),true);
        String instruction=upper(t.instructionCode());if(!INSTRUCTIONS.contains(instruction))throw lifecycle("دستور سررسید معتبر نیست.","DEPOSIT_TERM_CONTRACT.MATURITY_INSTRUCTION_CODE",String.valueOf(t.instructionCode()));
        String h=hash("MATURITY_EXECUTE|"+accountId+"|"+t.termContractId()+"|"+t.maturityDate()+"|"+instruction);
        if(replayOrClaim(idempotencyKey,accountId,"TERM_MATURITY_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"MATURITY_EVENT:"),true);
        long eventSeed=repository.next("SEQ_DEPOSIT_MATURITY_EVENT");
        if("WAIT_INSTRUCTION".equals(instruction)){
            long eventId=repository.upsertMaturityEvent(eventSeed,t.termContractId(),accountId,t.maturityDate(),instruction,t.principalAmount(),null,"PENDING",null,null,false,actor);
            repository.completeIdempotency(idempotencyKey,"MATURITY_EVENT:"+eventId);return new TermActionResponse(state(accountId),eventId,false);
        }
        TermContract contract=repository.term(accountId).orElseThrow();BigDecimal profit=profitService.outstandingPayable(accountId);Long txId=null,renewalId=null;String result;
        if("RENEW_PRINCIPAL".equals(instruction)||"RENEW_PRINCIPAL_PAY_PROFIT".equals(instruction)){
            if("RENEW_PRINCIPAL_PAY_PROFIT".equals(instruction)){var paid=profitService.postOutstandingViaStep05(accountId,t.maturityDate(),actor,correlationId,childKey(idempotencyKey,"MATURITY-PROFIT"));txId=paid.transactionId();profit=paid.amount();}
            LocalDate newMaturity=advanceMaturity(t.maturityDate(),contract.termValue(),contract.termUnitCode());
            renewalId=repository.executeAutomaticRenewal(t.termContractId(),accountId,t.renewalCount()+1,t.productVersionId(),t.maturityDate(),t.maturityDate(),newMaturity,t.contractRate(),t.principalAmount(),actor);
            result="RENEWED";
        } else {
            SettlementAccount target=null;String destinationRef;
            if("PAY_TO_ACCOUNT".equals(instruction)){
                target=resolveSettlementAccount(contract,account);
                destinationRef=target.accountNo();
            } else {
                destinationRef="MATURITY_SETTLEMENT:"+accountId+":"+t.maturityDate();
            }
            BigDecimal net=t.principalAmount().add(profit).setScale(4,RoundingMode.HALF_UP);List<DerivedTransactionLeg> legs=new ArrayList<>();
            legs.add(new DerivedTransactionLeg(accountId,null,"DEBIT",t.principalAmount()));if(profit.signum()>0)legs.add(new DerivedTransactionLeg(null,"PROFIT_EXPENSE:"+accountId,"DEBIT",profit));
            legs.add(new DerivedTransactionLeg(target==null?null:target.accountId(),destinationRef,"CREDIT",net));
            String requester=repository.instructionActor(t.termContractId(),actor),policy=policyActor(requester,"deposit.maturity.policy");
            var tx=transactionService.postDerived(new DerivedTransactionRequest(accountId,"MATURITY_SETTLEMENT",net,account.currencyCode(),t.maturityDate(),businessDate,"DEBIT","MATURITY:"+t.termContractId()+":"+t.maturityDate(),"POLICY_INSTRUCTION",requester,policy,"MATURITY_INSTRUCTION_EXECUTED",legs),actor,correlationId,childKey(idempotencyKey,"MATURITY-TX"));txId=tx.transaction().transaction().transactionId();
            if(profit.signum()>0)profitService.recordPaidByTransaction(accountId,txId,t.maturityDate(),target==null?"MATURITY_SETTLEMENT":"CUSTOMER_SELECTED_ACCOUNT",destinationRef,profit,actor);
            repository.insertPostedSettlement(repository.next("SEQ_DEPOSIT_TERM_SETTLEMENT"),t.termContractId(),"MATURITY",t.principalAmount(),profit,BigDecimal.ZERO,net,destinationRef,txId,actor);
            if(repository.markContractMatured(t.termContractId(),actor)!=1)throw lifecycle("قرارداد همزمان تغییر کرده است.","DEPOSIT_TERM_CONTRACT.STATUS_CODE",t.statusCode());
            String org=repository.accountOrgUnit(accountId).orElseThrow(()->lifecycle("واحد متولی حساب برای Closure سررسید موجود نیست.","DEPOSIT_ACCOUNT.ORG_UNIT_CODE","missing"));
            var closure=closureService.requestClosure(accountId,new ClosureRequest("MATURITY","MATURITY_INSTRUCTION",t.maturityDate(),target==null?null:destinationRef,policy,org),actor,correlationId,childKey128(idempotencyKey,"MATURITY-CLOSURE"));
            closureService.approveClosure(accountId,closure.closure().accountClosureId(),policy,correlationId,childKey128(idempotencyKey,"MATURITY-CLOSURE-APPROVE"));
            closureService.executePreSettledClosure(accountId,closure.closure().accountClosureId(),"TX-"+txId,actor,correlationId,childKey128(idempotencyKey,"MATURITY-CLOSURE-EXECUTE"));
            result="PAY_TO_ACCOUNT".equals(instruction)?"TRANSFERRED":"SETTLED";
        }
        long eventId=repository.upsertMaturityEvent(eventSeed,t.termContractId(),accountId,t.maturityDate(),instruction,t.principalAmount(),profit,result,renewalId,txId,true,actor);
        repository.completeIdempotency(idempotencyKey,"MATURITY_EVENT:"+eventId);return new TermActionResponse(state(accountId),eventId,false);
    }

    @Transactional
    public TermActionResponse requestPartialWithdrawal(long accountId,PartialWithdrawalRequest request,String actor,String correlationId,String idempotencyKey){
        requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);BigDecimal amount=request==null?null:request.amount();if(amount==null||amount.signum()<=0||amount.compareTo(t.principalAmount())>=0)throw new IllegalArgumentException("برداشت بخشی باید مثبت و کمتر از اصل قرارداد باشد.");
        String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);
        String h=hash("PARTIAL|"+accountId+"|"+amount.toPlainString()+"|"+approver+"|"+org);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"PARTIAL:"),true);
        long id=repository.next("SEQ_DEPOSIT_TERM_PARTIAL_WITHDRAWAL"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_PARTIAL_WITHDRAWAL","DEPOSIT_TERM_PARTIAL_WITHDRAWAL",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertPartialWithdrawal(id,t.termContractId(),accountId,amount,t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);
    }
    @Transactional public TermActionResponse approvePartialWithdrawal(long accountId,long id,String actor,String correlationId,String idempotencyKey){PartialWithdrawal w=partial(accountId,id);String h=hash("PARTIAL_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"REQUESTED".equals(upper(w.statusCode())))throw lifecycle("برداشت بخشی در وضعیت قابل تأیید نیست.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());if(repository.approve(Objects.requireNonNull(w.approvalRequestId()),actor)!=1)throw lifecycle("تأیید فقط توسط Approver تعیین‌شده ممکن است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markPartialApproved(id,actor)!=1)throw lifecycle("وضعیت برداشت بخشی همزمان تغییر کرده است.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executePartialWithdrawal(long accountId,long id,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);PartialWithdrawal w=partial(accountId,id);String h=hash("PARTIAL_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_PARTIAL_WITHDRAWAL_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"ACTIVE".equals(upper(a.status())))throw lifecycle("برداشت بخشی فقط روی حساب ACTIVE مجاز است.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",a.status());if(!"APPROVED".equals(upper(w.statusCode()))||!"APPROVED".equals(upper(w.approvalStatusCode())))throw lifecycle("برداشت بخشی باید APPROVED باشد.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());if(w.requestedAmount().compareTo(t.principalAmount())>=0)throw lifecycle("برداشت بخشی نمی‌تواند کل اصل قرارداد را مصرف کند؛ از Early Termination استفاده کنید.","DEPOSIT_TERM_CONTRACT.PRINCIPAL_AMOUNT",t.principalAmount().toPlainString());
        BigDecimal after=t.principalAmount().subtract(w.requestedAmount());LocalDate dt=LocalDate.now(ZoneOffset.UTC);ApprovalRow approval=repository.approval(Objects.requireNonNull(w.approvalRequestId())).orElseThrow(()->lifecycle("Approval برداشت بخشی یافت نشد.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVAL_REQUEST_ID",String.valueOf(w.approvalRequestId())));
        var tx=transactionService.postDerived(new DerivedTransactionRequest(accountId,"TERM_PARTIAL_WITHDRAWAL",w.requestedAmount(),a.currencyCode(),dt,dt,"DEBIT","TERM_PARTIAL_WITHDRAWAL:"+id,"SOURCE_APPROVAL",approval.requestedByUserId(),approval.approverUserId(),"TERM_PARTIAL_WITHDRAWAL_APPROVED",List.of(new DerivedTransactionLeg(accountId,null,"DEBIT",w.requestedAmount()),new DerivedTransactionLeg(null,"TERM_PARTIAL_WITHDRAWAL:"+id,"CREDIT",w.requestedAmount()))),actor,correlationId,childKey(idempotencyKey,"PARTIAL-TX"));long txId=tx.transaction().transaction().transactionId();
        if(repository.executePartial(id,t.termContractId(),w.requestedAmount(),after,dt,txId,actor)!=1)throw lifecycle("اجرای برداشت بخشی ناموفق بود.","DEPOSIT_TERM_PARTIAL_WITHDRAWAL.STATUS_CODE",w.statusCode());repository.insertPostedSettlement(repository.next("SEQ_DEPOSIT_TERM_SETTLEMENT"),t.termContractId(),"PARTIAL_WITHDRAWAL",w.requestedAmount(),BigDecimal.ZERO,BigDecimal.ZERO,w.requestedAmount(),null,txId,actor);repository.completeIdempotency(idempotencyKey,"PARTIAL:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional public TermActionResponse requestRenewal(long accountId,RenewalRequest request,String actor,String correlationId,String idempotencyKey){requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);long newPv=request.newProductVersionId()==null?t.productVersionId():request.newProductVersionId();requireTermProduct(newPv);LocalDate start=t.maturityDate(),newMat=Objects.requireNonNull(request.newMaturityDate(),"NEW_MATURITY_DATE الزامی است.");if(!newMat.isAfter(start))throw new IllegalArgumentException("NEW_MATURITY_DATE باید بعد از سررسید فعلی باشد.");String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);String h=hash("RENEW|"+accountId+"|"+newPv+"|"+newMat+"|"+request.newRate()+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"RENEWAL:"),true);long id=repository.next("SEQ_DEPOSIT_TERM_RENEWAL"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_RENEWAL","DEPOSIT_TERM_RENEWAL",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertRenewal(id,t.termContractId(),t.renewalCount()+1,t.productVersionId(),newPv,t.maturityDate(),start,newMat,t.contractRate(),request.newRate(),t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse approveRenewal(long accountId,long id,String actor,String correlationId,String idempotencyKey){Renewal r=renewal(accountId,id);String h=hash("RENEW_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(repository.approve(Objects.requireNonNull(r.approvalRequestId()),actor)!=1)throw lifecycle("Renewal فقط توسط Approver تعیین‌شده قابل تأیید است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markRenewalApproved(id,actor)!=1)throw lifecycle("Renewal در وضعیت REQUESTED نیست.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executeRenewal(long accountId,long id,String actor,String correlationId,String idempotencyKey){requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);Renewal r=renewal(accountId,id);String h=hash("RENEW_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_RENEWAL_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"APPROVED".equals(upper(r.statusCode()))||!"APPROVED".equals(upper(r.approvalStatusCode())))throw lifecycle("Renewal باید APPROVED باشد.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());if(LocalDate.now(ZoneOffset.UTC).isBefore(r.fromMaturityDate()))throw lifecycle("اجرای Renewal قبل از سررسید مجاز نیست.","DEPOSIT_TERM_RENEWAL.FROM_MATURITY_DATE",r.fromMaturityDate().toString());if(repository.executeRenewal(id,t.termContractId(),r.newProductVersionId(),r.newStartDate(),r.newMaturityDate(),r.newRate(),r.renewedPrincipal(),actor)!=1)throw lifecycle("اجرای Renewal ناموفق بود.","DEPOSIT_TERM_RENEWAL.STATUS_CODE",r.statusCode());repository.insertMaturityEvent(repository.next("SEQ_DEPOSIT_MATURITY_EVENT"),t.termContractId(),accountId,r.fromMaturityDate(),t.instructionCode(),r.renewedPrincipal(),"RENEWED",id,actor);repository.completeIdempotency(idempotencyKey,"RENEWAL:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional public TermActionResponse requestConversion(long accountId,ConversionRequest request,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);requireTermProduct(request.toProductVersionId());if(request.toProductVersionId()==t.productVersionId())throw new IllegalArgumentException("محصول مقصد باید با محصول فعلی متفاوت باشد.");String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE");makerChecker(actor,approver);LocalDate eff=request.effectiveDate()==null?LocalDate.now(ZoneOffset.UTC):request.effectiveDate();String h=hash("CONVERT|"+accountId+"|"+request.toProductVersionId()+"|"+eff+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"CONVERSION:"),true);long id=repository.next("SEQ_DEPOSIT_TERM_CONVERSION"),ap=repository.nextApproval();repository.insertApproval(ap,accountId,"TERM_CONVERSION","DEPOSIT_TERM_CONVERSION",id,actor,approver,org,approvalKey(idempotencyKey),correlationId);repository.insertConversion(id,t.termContractId(),accountId,a.currentProductVersionId(),request.toProductVersionId(),eff,t.principalAmount(),ap,actor);repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse approveConversion(long accountId,long id,String actor,String correlationId,String idempotencyKey){TermConversion c=conversion(accountId,id);String h=hash("CONVERT_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_APPROVE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(repository.approve(Objects.requireNonNull(c.approvalRequestId()),actor)!=1)throw lifecycle("Conversion فقط توسط Approver تعیین‌شده قابل تأیید است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVER_USER_ID",actor);if(repository.markConversionApproved(id,actor)!=1)throw lifecycle("Conversion در وضعیت REQUESTED نیست.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}
    @Transactional public TermActionResponse executeConversion(long accountId,long id,String actor,String correlationId,String idempotencyKey){AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);TermConversion c=conversion(accountId,id);String h=hash("CONVERT_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_CONVERSION_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);if(!"APPROVED".equals(upper(c.statusCode()))||!"APPROVED".equals(upper(c.approvalStatusCode())))throw lifecycle("Conversion باید APPROVED باشد.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());if(repository.executeConversion(id,t.termContractId(),accountId,c.fromProductVersionId(),c.toProductVersionId(),c.effectiveDate(),Objects.requireNonNull(c.approvalRequestId()),actor)!=1)throw lifecycle("اجرای Conversion ناموفق بود.","DEPOSIT_TERM_CONVERSION.STATUS_CODE",c.statusCode());repository.completeIdempotency(idempotencyKey,"CONVERSION:"+id);return new TermActionResponse(state(accountId),id,false);}

    @Transactional
    public TermActionResponse requestEarlyTermination(long accountId,EarlyTerminationRequest request,String actor,String correlationId,String idempotencyKey){
        AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);if(!"ACTIVE".equals(upper(a.status())))throw lifecycle("فسخ پیش از موعد فقط برای حساب ACTIVE مجاز است.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",a.status());
        String approver=required(request.approverUserId(),"APPROVER_USER_ID"),org=required(request.orgUnitCode(),"ORG_UNIT_CODE"),settlement=required(request.settlementAccountReference(),"SETTLEMENT_ACCOUNT_REFERENCE");makerChecker(actor,approver);
        BigDecimal rate=request.earlyTerminationRate();if(rate==null||rate.signum()<0||rate.compareTo(BigDecimal.valueOf(100))>0)throw new IllegalArgumentException("EARLY_TERMINATION_RATE باید بین صفر و 100 باشد.");rate=rate.setScale(6,RoundingMode.HALF_UP);
        BigDecimal accrued=t.principalAmount().multiply(rate).divide(BigDecimal.valueOf(1200),4,RoundingMode.HALF_UP);BigDecimal adjustment=accrued.multiply(new BigDecimal("0.15")).setScale(4,RoundingMode.HALF_UP).negate();BigDecimal tax=BigDecimal.ZERO.setScale(4),fee=BigDecimal.ZERO.setScale(4);BigDecimal net=t.principalAmount().add(accrued).add(adjustment).subtract(tax).subtract(fee).setScale(4,RoundingMode.HALF_UP);if(net.signum()<=0)throw lifecycle("خالص تسویه فسخ پیش از موعد باید مثبت باشد.","DEPOSIT_TERM_EARLY_TERMINATION.NET_SETTLEMENT_AMOUNT",net.toPlainString());
        LocalDate dt=request.terminationDate()==null?LocalDate.now(ZoneOffset.UTC):request.terminationDate();String h=hash("EARLY_TERM|"+accountId+"|"+dt+"|"+settlement+"|"+rate.toPlainString()+"|"+approver);if(replayOrClaim(idempotencyKey,accountId,"TERM_EARLY_TERMINATION_REQUEST",h,actor,correlationId))return new TermActionResponse(state(accountId),parseResult(idempotencyKey,"EARLY:"),true);
        long id=repository.next("SEQ_DEPOSIT_TERM_EARLY_TERMINATION");var closure=closureService.requestClosure(accountId,new ClosureRequest("EARLY_TERMINATION","TERM_EARLY_TERMINATION",dt,settlement,approver,org),actor,correlationId,childKey128(idempotencyKey,"EARLY-CLOSURE"));Long approval=closure.closure().approvalRequestId();
        repository.insertEarlyTermination(id,t.termContractId(),accountId,dt,t.principalAmount(),accrued,rate,adjustment,tax,fee,net,Objects.requireNonNull(approval),actor);repository.insertCalculatedSettlement(repository.next("SEQ_DEPOSIT_TERM_SETTLEMENT"),t.termContractId(),"EARLY_TERMINATION",t.principalAmount(),accrued,adjustment,tax,fee,net,settlement,actor);repository.completeIdempotency(idempotencyKey,"EARLY:"+id);return new TermActionResponse(state(accountId),id,false);
    }

    @Transactional
    public TermActionResponse executeEarlyTermination(long accountId,long id,String actor,String correlationId,String idempotencyKey){
        AccountRow a=requireTermAccount(accountId,true);TermLock t=requireTerm(accountId);EarlyTermination e=early(accountId,id);String h=hash("EARLY_EXECUTE|"+accountId+"|"+id);if(replayOrClaim(idempotencyKey,accountId,"TERM_EARLY_TERMINATION_EXECUTE",h,actor,correlationId))return new TermActionResponse(state(accountId),id,true);
        if(!"ACTIVE".equals(upper(a.status())))throw lifecycle("فسخ پیش از موعد فقط روی حساب ACTIVE قابل اجرا است.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",a.status());if(!"REQUESTED".equals(upper(e.statusCode())))throw lifecycle("Early Termination در وضعیت قابل اجرا نیست.","DEPOSIT_TERM_EARLY_TERMINATION.STATUS_CODE",e.statusCode());if(!"APPROVED".equals(upper(e.closureStatusCode())))throw lifecycle("Controlled Closure مربوط به Early Termination باید APPROVED باشد.","DEPOSIT_ACCOUNT_CLOSURE.CLOSURE_STATUS_CODE",e.closureStatusCode());
        ApprovalRow approval=repository.approval(Objects.requireNonNull(e.approvalRequestId())).orElseThrow(()->lifecycle("Approval فسخ پیش از موعد یافت نشد.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVAL_REQUEST_ID",String.valueOf(e.approvalRequestId())));if(!"APPROVED".equals(upper(approval.approvalStatus())))throw lifecycle("Approval فسخ پیش از موعد تأیید نشده است.","DEPOSIT_OPERATION_APPROVAL_REQUEST.APPROVAL_STATUS_CODE",approval.approvalStatus());
        TermSettlement settlement=repository.settlements(accountId).stream().filter(x->"EARLY_TERMINATION".equals(upper(x.settlementTypeCode()))&&"CALCULATED".equals(upper(x.statusCode()))).findFirst().orElseThrow(()->lifecycle("Settlement محاسبه‌شده فسخ یافت نشد.","DEPOSIT_TERM_SETTLEMENT.STATUS_CODE","CALCULATED"));
        SettlementAccount target=repository.settlementAccountByReference(required(settlement.destinationAccountReference(),"SETTLEMENT_ACCOUNT_REFERENCE")).orElseThrow(()->lifecycle("حساب مقصد داخلی فسخ پیش از موعد یافت نشد.","DEPOSIT_TERM_SETTLEMENT.DESTINATION_ACCOUNT_REFERENCE",settlement.destinationAccountReference()));validateSettlementTarget(accountId,a,target);
        BigDecimal principal=nz(e.principalAmount()),profit=nz(e.accruedProfitAmount()),adjustment=nz(e.adjustmentAmount()),tax=nz(e.taxAmount()),fee=nz(e.feeAmount()),net=nz(e.netSettlementAmount());List<DerivedTransactionLeg> legs=settlementLegs(accountId,target,principal,profit,adjustment,tax,fee,net,"EARLY_TERMINATION:"+id);
        var tx=transactionService.postDerived(new DerivedTransactionRequest(accountId,"TERM_EARLY_TERMINATION",net,a.currencyCode(),e.terminationDate(),LocalDate.now(ZoneOffset.UTC),"DEBIT","EARLY_TERMINATION:"+id,"SOURCE_APPROVAL",approval.requestedByUserId(),approval.approverUserId(),"TERM_EARLY_TERMINATION_APPROVED",legs),actor,correlationId,childKey(idempotencyKey,"EARLY-TX"));long txId=tx.transaction().transaction().transactionId();
        if(repository.executeEarlyTermination(id,t.termContractId(),txId,actor)!=1)throw lifecycle("اجرای Early Termination ناموفق بود.","DEPOSIT_TERM_EARLY_TERMINATION.STATUS_CODE",e.statusCode());if(repository.markCalculatedSettlementPosted(t.termContractId(),"EARLY_TERMINATION",txId,actor)!=1)throw lifecycle("Settlement فسخ برای POST شدن یافت نشد.","DEPOSIT_TERM_SETTLEMENT.STATUS_CODE","CALCULATED");
        closureService.executePreSettledClosure(accountId,Objects.requireNonNull(e.closureId()),"TX-"+txId,actor,correlationId,childKey128(idempotencyKey,"EARLY-CLOSURE-EXECUTE"));repository.completeIdempotency(idempotencyKey,"EARLY:"+id);return new TermActionResponse(state(accountId),id,false);
    }

    private TermOperationsView state(long accountId){return new TermOperationsView(repository.term(accountId).orElseThrow(()->lifecycle("قرارداد مدت‌دار برای حساب یافت نشد.","DEPOSIT_TERM_CONTRACT","missing")),repository.maturityEvents(accountId),repository.renewals(accountId),repository.partials(accountId),repository.conversions(accountId),repository.earlyTerminations(accountId),repository.settlements(accountId));}
    private AccountRow requireTermAccount(long accountId,boolean lock){AccountRow a=repository.account(accountId,lock).orElseThrow(()->new DepositAccountNotFoundException("حساب سپرده با شناسه "+accountId+" یافت نشد."));if(!TERM_FAMILIES.contains(upper(a.productFamilyCode())))throw lifecycle("عملیات 11F فقط برای سپرده کوتاه‌مدت/بلندمدت مجاز است.","PRODUCT_FAMILY_CODE",a.productFamilyCode());return a;}
    private TermLock requireTerm(long accountId){return repository.lockTerm(accountId).orElseThrow(()->lifecycle("قرارداد مدت‌دار فعال یافت نشد؛ migration فاز 11F را اجرا کنید.","DEPOSIT_TERM_CONTRACT.ACCOUNT_ID",String.valueOf(accountId)));}
    private void requireTermProduct(long pv){String f=repository.productFamily(pv).orElseThrow(()->new IllegalArgumentException("Product Version مقصد یافت نشد."));if(!TERM_FAMILIES.contains(upper(f)))throw new IllegalArgumentException("تبدیل/تمدید فقط به محصول SHORT_TERM_DEPOSIT یا LONG_TERM_DEPOSIT مجاز است.");}
    private PartialWithdrawal partial(long aid,long id){return repository.partials(aid).stream().filter(x->x.partialWithdrawalId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Partial Withdrawal یافت نشد."));}
    private Renewal renewal(long aid,long id){return repository.renewals(aid).stream().filter(x->x.termRenewalId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Renewal یافت نشد."));}
    private TermConversion conversion(long aid,long id){return repository.conversions(aid).stream().filter(x->x.termConversionId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Conversion یافت نشد."));}
    private EarlyTermination early(long aid,long id){return repository.earlyTerminations(aid).stream().filter(x->x.earlyTerminationId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Early Termination یافت نشد."));}
    private SettlementAccount resolveSettlementAccount(TermContract contract,AccountRow source){SettlementAccount target=null;if(contract.maturitySettlementAccountId()!=null)target=repository.settlementAccount(contract.maturitySettlementAccountId()).orElse(null);if(target==null&&trim(contract.maturitySettlementAccountReference())!=null)target=repository.settlementAccountByReference(contract.maturitySettlementAccountReference()).orElse(null);if(target==null)throw lifecycle("حساب مقصد داخلی دستور PAY_TO_ACCOUNT یافت نشد.","DEPOSIT_TERM_CONTRACT.MATURITY_SETTLEMENT_ACCOUNT_REFERENCE",String.valueOf(contract.maturitySettlementAccountReference()));if(contract.maturitySettlementAccountReference()!=null&&!contract.maturitySettlementAccountReference().equals(target.accountNo()))throw lifecycle("شناسه و مرجع حساب مقصد سررسید سازگار نیستند.","DEPOSIT_TERM_CONTRACT.MATURITY_SETTLEMENT_ACCOUNT_REFERENCE",contract.maturitySettlementAccountReference());validateSettlementTarget(contract.accountId(),source,target);return target;}
    private void validateSettlementTarget(long sourceAccountId,AccountRow source,SettlementAccount target){if(target.accountId()==sourceAccountId)throw lifecycle("حساب مقصد Settlement باید با حساب مبدأ متفاوت باشد.","DEPOSIT_ACCOUNT.ACCOUNT_ID",String.valueOf(target.accountId()));if(!"ACTIVE".equals(upper(target.status())))throw lifecycle("حساب مقصد Settlement باید ACTIVE باشد.","DEPOSIT_ACCOUNT.ACCOUNT_STATUS_CODE",target.status());if(!upper(source.currencyCode()).equals(upper(target.currencyCode())))throw lifecycle("ارز حساب مقصد Settlement با حساب مبدأ یکسان نیست.","DEPOSIT_ACCOUNT.CURRENCY_CODE",target.currencyCode());}
    private List<DerivedTransactionLeg> settlementLegs(long sourceAccountId,SettlementAccount target,BigDecimal principal,BigDecimal profit,BigDecimal adjustment,BigDecimal tax,BigDecimal fee,BigDecimal net,String reference){List<DerivedTransactionLeg> legs=new ArrayList<>();legs.add(new DerivedTransactionLeg(sourceAccountId,null,"DEBIT",principal));if(profit.signum()>0)legs.add(new DerivedTransactionLeg(null,"PROFIT_EXPENSE:"+reference,"DEBIT",profit));if(adjustment.signum()>0)legs.add(new DerivedTransactionLeg(null,"ADJUSTMENT_EXPENSE:"+reference,"DEBIT",adjustment));else if(adjustment.signum()<0)legs.add(new DerivedTransactionLeg(null,"ADJUSTMENT_INCOME:"+reference,"CREDIT",adjustment.abs()));if(tax.signum()>0)legs.add(new DerivedTransactionLeg(null,"TAX_PAYABLE:"+reference,"CREDIT",tax));if(fee.signum()>0)legs.add(new DerivedTransactionLeg(null,"FEE_INCOME:"+reference,"CREDIT",fee));legs.add(new DerivedTransactionLeg(target.accountId(),target.accountNo(),"CREDIT",net));BigDecimal debits=legs.stream().filter(x->"DEBIT".equals(x.debitCreditCode())).map(DerivedTransactionLeg::amount).reduce(BigDecimal.ZERO,BigDecimal::add),credits=legs.stream().filter(x->"CREDIT".equals(x.debitCreditCode())).map(DerivedTransactionLeg::amount).reduce(BigDecimal.ZERO,BigDecimal::add);if(debits.compareTo(credits)!=0)throw lifecycle("مولفه‌های Settlement تراز نیستند.","DEPOSIT_TERM_SETTLEMENT.NET_AMOUNT","debit="+debits+", credit="+credits);return legs;}
    private static LocalDate advanceMaturity(LocalDate maturity,long termValue,String termUnit){if(termValue<=0)throw new IllegalArgumentException("TERM_VALUE باید مثبت باشد.");return switch(upper(termUnit)){case "DAY"->maturity.plusDays(termValue);case "MONTH"->maturity.plusMonths(termValue);case "YEAR"->maturity.plusYears(termValue);default->throw new IllegalArgumentException("TERM_UNIT_CODE پشتیبانی نمی‌شود: "+termUnit);};}
    private static String policyActor(String requester,String preferred){return preferred.equalsIgnoreCase(requester)?preferred+".authorizer":preferred;}
    private static String childKey(String base,String suffix){String x=base+"-"+suffix;return x.length()<=80?x:hash(base+"|"+suffix);}
    private static String childKey128(String base,String suffix){String x=base+"-"+suffix;return x.length()<=128?x:hash(base+"|"+suffix);}
    private static BigDecimal nz(BigDecimal v){return v==null?BigDecimal.ZERO.setScale(4):v;}
    private void makerChecker(String maker,String checker){if(maker.equals(checker))throw new IllegalArgumentException("Maker و Approver باید متفاوت باشند.");}
    private boolean replayOrClaim(String key,long accountId,String operation,String hash,String actor,String corr){if(key==null||key.isBlank())throw new IllegalArgumentException("X-Idempotency-Key الزامی است.");var x=repository.findIdempotency(key);if(x.isPresent()){IdempotencyRow r=x.get();if(!Objects.equals(r.accountId(),accountId)||!operation.equals(r.operationType())||!hash.equals(r.payloadHash()))throw new IllegalArgumentException("Idempotency Key با درخواست دیگری استفاده شده است.");if("COMPLETED".equals(r.processingStatus()))return true;throw lifecycle("درخواست با همین Idempotency Key در حال پردازش است.","DEPOSIT_OPERATION_IDEMPOTENCY.PROCESSING_STATUS_CODE",r.processingStatus());}repository.insertIdempotency(key,accountId,operation,hash,actor,corr);return false;}
    private long parseResult(String key,String prefix){String ref=repository.findIdempotency(key).orElseThrow().resultReference();if(ref==null||!ref.startsWith(prefix))throw new IllegalArgumentException("Idempotency result نامعتبر است.");return Long.parseLong(ref.substring(prefix.length()));}
    private static String approvalKey(String key){return key.length()<=118?key+"-APPROVAL":key.substring(0,118)+"-APPROVAL";}
    private static String required(String s,String field){String v=trim(s);if(v==null)throw new IllegalArgumentException(field+" الزامی است.");return v;}
    private static String trim(String s){return s==null||s.isBlank()?null:s.trim();}private static String upper(String s){return s==null?null:s.trim().toUpperCase(Locale.ROOT);}
    private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static DepositAccountLifecycleException lifecycle(String msg,String k,String v){return new DepositAccountLifecycleException(msg,Map.of(k,Objects.toString(v,"null")));}
}
