-- ============================================================================
-- CAL_CAL2_FIXED_OCCASION_COVERAGE_AUDIT.sql
-- Read-only audit. No DML / no COMMIT required.
-- Purpose:
--   1) Confirm CAL occurrence projection matches CAL2 source data.
--   2) Show date/year coverage of fixed recurring occasions.
--   3) Detect missing CAL2 GENERATED occurrences before any rebuild.
-- ============================================================================
SET PAGESIZE 500
SET LINESIZE 220
SET VERIFY OFF

PROMPT === A. Overall occurrence counts ===
SELECT 'CAL2.EVENT_OCCURRENCE' OBJECT_NAME, COUNT(*) ROW_COUNT FROM CAL2.EVENT_OCCURRENCE
UNION ALL
SELECT 'CAL.OCCASION_OCCURRENCE', COUNT(*) FROM CAL.OCCASION_OCCURRENCE
UNION ALL
SELECT 'CAL.CALENDAR_DAY_OCCASION', COUNT(*) FROM CAL.CALENDAR_DAY_OCCASION;

PROMPT === B. Canonical date span ===
SELECT 'CAL2' MODEL_NAME,
       MIN(D.CANONICAL_DATE) MIN_DATE,
       MAX(D.CANONICAL_DATE) MAX_DATE,
       COUNT(*) OCCURRENCE_COUNT
  FROM CAL2.EVENT_OCCURRENCE EO
  JOIN CAL2.CANONICAL_DAY D ON D.DAY_ID = EO.DAY_ID
UNION ALL
SELECT 'CAL1',
       MIN(D.CANONICAL_DATE),
       MAX(D.CANONICAL_DATE),
       COUNT(*)
  FROM CAL.OCCASION_OCCURRENCE OO
  JOIN CAL.CALENDAR_DAY D ON D.DAY_ID = OO.START_DAY_ID;

PROMPT === C. CAL2 occurrences that do not have an equivalent CAL1 occurrence ===
SELECT COUNT(*) AS CAL2_WITHOUT_CAL1
FROM
(
    SELECT E.EVENT_CODE,
           TO_CHAR(D.CANONICAL_DATE,'YYYY-MM-DD') OCCURRENCE_DATE,
           NVL(SA.SOURCE_CODE,'~') SOURCE_CODE
      FROM CAL2.EVENT_OCCURRENCE EO
      JOIN CAL2.EVENT E ON E.EVENT_ID = EO.EVENT_ID
      JOIN CAL2.CANONICAL_DAY D ON D.DAY_ID = EO.DAY_ID
      LEFT JOIN CAL2.SOURCE_AUTHORITY SA ON SA.SOURCE_ID = EO.SOURCE_ID
    MINUS
    SELECT O.OCCASION_CODE,
           TO_CHAR(D.CANONICAL_DATE,'YYYY-MM-DD'),
           NVL(OO.SOURCE_AUTHORITY_CODE,'~')
      FROM CAL.OCCASION_OCCURRENCE OO
      JOIN CAL.OCCASION O ON O.OCCASION_ID = OO.OCCASION_ID
      JOIN CAL.CALENDAR_DAY D ON D.DAY_ID = OO.START_DAY_ID
);

PROMPT === D. CAL1 occurrences that do not have an equivalent CAL2 occurrence ===
SELECT COUNT(*) AS CAL1_WITHOUT_CAL2
FROM
(
    SELECT O.OCCASION_CODE,
           TO_CHAR(D.CANONICAL_DATE,'YYYY-MM-DD') OCCURRENCE_DATE,
           NVL(OO.SOURCE_AUTHORITY_CODE,'~') SOURCE_CODE
      FROM CAL.OCCASION_OCCURRENCE OO
      JOIN CAL.OCCASION O ON O.OCCASION_ID = OO.OCCASION_ID
      JOIN CAL.CALENDAR_DAY D ON D.DAY_ID = OO.START_DAY_ID
    MINUS
    SELECT E.EVENT_CODE,
           TO_CHAR(D.CANONICAL_DATE,'YYYY-MM-DD'),
           NVL(SA.SOURCE_CODE,'~')
      FROM CAL2.EVENT_OCCURRENCE EO
      JOIN CAL2.EVENT E ON E.EVENT_ID = EO.EVENT_ID
      JOIN CAL2.CANONICAL_DAY D ON D.DAY_ID = EO.DAY_ID
      LEFT JOIN CAL2.SOURCE_AUTHORITY SA ON SA.SOURCE_ID = EO.SOURCE_ID
);

PROMPT === E. CAL2 recurring rule summary ===
SELECT R.RULE_TYPE,
       COUNT(*) RULE_COUNT,
       MIN(NVL(R.START_YEAR_NO,R.YEAR_NO)) MIN_RULE_YEAR,
       MAX(NVL(R.END_YEAR_NO,R.YEAR_NO)) MAX_RULE_YEAR
  FROM CAL2.EVENT_RECURRENCE_RULE R
 GROUP BY R.RULE_TYPE
 ORDER BY R.RULE_TYPE;

PROMPT === F. Active fixed rules and generated occurrence coverage ===
SELECT R.EVENT_RULE_ID,
       E.EVENT_CODE,
       E.NAME_FA,
       R.RULE_TYPE,
       S.CALENDAR_CODE,
       V.VARIANT_CODE,
       R.MONTH_NO,
       R.DAY_NO,
       R.YEAR_NO,
       R.START_YEAR_NO,
       R.END_YEAR_NO,
       COUNT(EO.EVENT_OCCURRENCE_ID) AS GENERATED_OCCURRENCES,
       MIN(D.CANONICAL_DATE) AS FIRST_GENERATED_DATE,
       MAX(D.CANONICAL_DATE) AS LAST_GENERATED_DATE
  FROM CAL2.EVENT_RECURRENCE_RULE R
  JOIN CAL2.EVENT E ON E.EVENT_ID = R.EVENT_ID
  JOIN CAL2.CALENDAR_VARIANT V ON V.CALENDAR_VARIANT_ID = R.CALENDAR_VARIANT_ID
  JOIN CAL2.CALENDAR_SYSTEM S ON S.CALENDAR_SYSTEM_ID = V.CALENDAR_SYSTEM_ID
  LEFT JOIN CAL2.EVENT_OCCURRENCE EO
         ON EO.EVENT_RULE_ID = R.EVENT_RULE_ID
        AND EO.OCCURRENCE_SOURCE = 'GENERATED'
  LEFT JOIN CAL2.CANONICAL_DAY D ON D.DAY_ID = EO.DAY_ID
 WHERE R.ACTIVE_FLAG = 'Y'
   AND E.ACTIVE_FLAG = 'Y'
   AND R.RULE_TYPE IN ('ANNUAL_FIXED_DATE','ONE_TIME_DATE')
 GROUP BY R.EVENT_RULE_ID,E.EVENT_CODE,E.NAME_FA,R.RULE_TYPE,S.CALENDAR_CODE,V.VARIANT_CODE,
          R.MONTH_NO,R.DAY_NO,R.YEAR_NO,R.START_YEAR_NO,R.END_YEAR_NO
 ORDER BY E.EVENT_CODE,R.EVENT_RULE_ID;

PROMPT === G. Active CAL2 rules with zero generated occurrences ===
SELECT R.EVENT_RULE_ID,
       E.EVENT_CODE,
       E.NAME_FA,
       R.RULE_TYPE,
       R.MONTH_NO,
       R.DAY_NO,
       R.YEAR_NO,
       R.START_YEAR_NO,
       R.END_YEAR_NO
  FROM CAL2.EVENT_RECURRENCE_RULE R
  JOIN CAL2.EVENT E ON E.EVENT_ID = R.EVENT_ID
 WHERE R.ACTIVE_FLAG = 'Y'
   AND E.ACTIVE_FLAG = 'Y'
   AND R.RULE_TYPE IN ('ANNUAL_FIXED_DATE','ONE_TIME_DATE')
   AND NOT EXISTS
       (
         SELECT 1
           FROM CAL2.EVENT_OCCURRENCE EO
          WHERE EO.EVENT_RULE_ID = R.EVENT_RULE_ID
            AND EO.OCCURRENCE_SOURCE = 'GENERATED'
       )
 ORDER BY E.EVENT_CODE,R.EVENT_RULE_ID;

PROMPT === H. Duplicate natural occurrence keys in CAL2 ===
SELECT E.EVENT_CODE,
       D.CANONICAL_DATE,
       NVL(SA.SOURCE_CODE,'~') SOURCE_CODE,
       COUNT(*) CNT
  FROM CAL2.EVENT_OCCURRENCE EO
  JOIN CAL2.EVENT E ON E.EVENT_ID = EO.EVENT_ID
  JOIN CAL2.CANONICAL_DAY D ON D.DAY_ID = EO.DAY_ID
  LEFT JOIN CAL2.SOURCE_AUTHORITY SA ON SA.SOURCE_ID = EO.SOURCE_ID
 GROUP BY E.EVENT_CODE,D.CANONICAL_DATE,NVL(SA.SOURCE_CODE,'~')
HAVING COUNT(*) > 1
 ORDER BY D.CANONICAL_DATE,E.EVENT_CODE;

PROMPT === Audit finished. This script does not modify data. ===
