SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT ============================================================
PROMPT DPS2 Phase 10 - Operational Opening v5 Foundation 0.10.0
PROMPT Source: Deposit_Account_Opening_Operational_Final_2026-09-17.html
PROMPT ============================================================

DECLARE
  FUNCTION table_exists(p_table VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_TABLES
     WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table);
    RETURN v_count > 0;
  END;

  FUNCTION column_exists(p_table VARCHAR2, p_column VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
     WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_column);
    RETURN v_count > 0;
  END;

  FUNCTION sequence_exists(p_sequence VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_SEQUENCES
     WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p_sequence);
    RETURN v_count > 0;
  END;

  FUNCTION constraint_exists(p_constraint VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS
     WHERE OWNER='DPS2' AND CONSTRAINT_NAME=UPPER(p_constraint);
    RETURN v_count > 0;
  END;

  FUNCTION index_exists(p_index VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
     WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p_index);
    RETURN v_count > 0;
  END;

  PROCEDURE require_table(p_table VARCHAR2) IS
  BEGIN
    IF NOT table_exists(p_table) THEN
      RAISE_APPLICATION_ERROR(-21000, 'Required table DPS2.'||p_table||' is missing. Apply 0.9.3 baseline first.');
    END IF;
  END;

  PROCEDURE add_col(p_table VARCHAR2, p_column VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    IF column_exists(p_table,p_column) THEN
      DBMS_OUTPUT.PUT_LINE('OK  : '||p_table||'.'||p_column);
    ELSE
      EXECUTE IMMEDIATE 'ALTER TABLE DPS2.'||p_table||' ADD ('||p_column||' '||p_ddl||')';
      DBMS_OUTPUT.PUT_LINE('ADD : '||p_table||'.'||p_column);
    END IF;
  END;

  PROCEDURE add_constraint(p_name VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    IF constraint_exists(p_name) THEN
      DBMS_OUTPUT.PUT_LINE('OK  : constraint '||p_name);
    ELSE
      BEGIN
        EXECUTE IMMEDIATE p_ddl;
        DBMS_OUTPUT.PUT_LINE('ADD : constraint '||p_name);
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE = -2275 THEN
            DBMS_OUTPUT.PUT_LINE('OK  : equivalent referential constraint already exists for '||p_name||' (preserved under existing name).');
          ELSE
            RAISE;
          END IF;
      END;
    END IF;
  END;

  PROCEDURE add_index(p_name VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    IF index_exists(p_name) THEN
      DBMS_OUTPUT.PUT_LINE('OK  : index '||p_name);
    ELSE
      EXECUTE IMMEDIATE p_ddl;
      DBMS_OUTPUT.PUT_LINE('ADD : index '||p_name);
    END IF;
  END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Preflight baseline ===');
  require_table('DEPOSIT_OPENING_REQUEST');
  require_table('DEPOSIT_OPENING_FUNDING');
  require_table('DEPOSIT_OPENING_CHECK');
  require_table('DEPOSIT_OPENING_BATCH');
  require_table('DEPOSIT_ACCOUNT');
  require_table('REF_DEP_OPEN_JOINT_BASIS');
  require_table('REF_DEP_OPEN_ACTIVATION_STATUS');
  require_table('REF_DEP_OPEN_FUND_PURPOSE');
  require_table('REF_DEP_OPEN_CHECK_PHASE');
  require_table('REF_DEP_OPEN_BLOCKING_SCOPE');
  require_table('REF_DEP_OPEN_CHECK_TYPE');
  require_table('REF_DEP_OPEN_CHECK');
  require_table('REF_DEP_OPEN_OBLIGATION_TYPE');
  require_table('REF_DEP_OPEN_SETTLEMENT_STATUS');

  DBMS_OUTPUT.PUT_LINE('=== DEPOSIT_OPENING_REQUEST delta ===');
  add_col('DEPOSIT_OPENING_REQUEST','CUSTOMER_RISK_LEVEL_CODE','VARCHAR2(30)');
  add_col('DEPOSIT_OPENING_REQUEST','RISK_ASSESSMENT_REFERENCE','VARCHAR2(120)');
  add_col('DEPOSIT_OPENING_REQUEST','EXPECTED_ACTIVITY_REFERENCE','VARCHAR2(120)');
  add_col('DEPOSIT_OPENING_REQUEST','JOINT_ACCOUNT_BASIS_CODE','VARCHAR2(30)');
  add_col('DEPOSIT_OPENING_REQUEST','JOINT_BASIS_REFERENCE','VARCHAR2(120)');
  add_col('DEPOSIT_OPENING_REQUEST','ACTIVATION_STATUS_CODE','VARCHAR2(30) DEFAULT ''NOT_CREATED'' NOT NULL');
  add_col('DEPOSIT_OPENING_REQUEST','ACTIVATION_DEADLINE_AT','TIMESTAMP(6)');

  DBMS_OUTPUT.PUT_LINE('=== DEPOSIT_OPENING_FUNDING delta ===');
  IF NOT sequence_exists('SEQ_DEPOSIT_OPENING_FUNDING') THEN
    DECLARE v_start NUMBER; BEGIN
      SELECT NVL(MAX(OPENING_FUNDING_ID),0)+1 INTO v_start FROM DPS2.DEPOSIT_OPENING_FUNDING;
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.SEQ_DEPOSIT_OPENING_FUNDING START WITH '||v_start||' INCREMENT BY 1 NOCACHE NOCYCLE';
      DBMS_OUTPUT.PUT_LINE('ADD : SEQ_DEPOSIT_OPENING_FUNDING starting at '||v_start);
    END;
  ELSE DBMS_OUTPUT.PUT_LINE('OK  : SEQ_DEPOSIT_OPENING_FUNDING'); END IF;

  add_col('DEPOSIT_OPENING_FUNDING','SOURCE_PARTY_ID','NUMBER(19)');
  add_col('DEPOSIT_OPENING_FUNDING','SOURCE_ACCOUNT_ID','NUMBER(19)');
  add_col('DEPOSIT_OPENING_FUNDING','FUNDING_PURPOSE_CODE','VARCHAR2(30)');
  add_col('DEPOSIT_OPENING_FUNDING','SOURCE_OWNERSHIP_VERIFIED_FLAG','NUMBER(1) DEFAULT 0 NOT NULL');
  add_col('DEPOSIT_OPENING_FUNDING','SOURCE_VERIFICATION_REFERENCE','VARCHAR2(120)');
  add_col('DEPOSIT_OPENING_FUNDING','CASH_MANAGEMENT_TXN_REF','VARCHAR2(120)');
  add_col('DEPOSIT_OPENING_FUNDING','ATTEMPT_AT','TIMESTAMP(6)');

  DBMS_OUTPUT.PUT_LINE('=== DEPOSIT_OPENING_CHECK delta ===');
  add_col('DEPOSIT_OPENING_CHECK','CHECK_PHASE_CODE','VARCHAR2(30)');
  add_col('DEPOSIT_OPENING_CHECK','BLOCKING_SCOPE_CODE','VARCHAR2(30)');
  add_col('DEPOSIT_OPENING_CHECK','REQUIRED_FLAG','NUMBER(1) DEFAULT 1 NOT NULL');
  add_col('DEPOSIT_OPENING_CHECK','RECHECK_REQUIRED_FLAG','NUMBER(1) DEFAULT 0 NOT NULL');
  add_col('DEPOSIT_OPENING_CHECK','VALID_UNTIL','TIMESTAMP(6)');
  add_col('DEPOSIT_OPENING_CHECK','SOURCE_EVALUATION_REFERENCE','VARCHAR2(120)');

  DBMS_OUTPUT.PUT_LINE('=== DEPOSIT_OPENING_BATCH delta ===');
  add_col('DEPOSIT_OPENING_BATCH','BULK_OPENING_BASIS_CODE','VARCHAR2(50)');
  add_col('DEPOSIT_OPENING_BATCH','LEGAL_BASIS_REFERENCE','VARCHAR2(255)');
  add_col('DEPOSIT_OPENING_BATCH','CDD_APPROVAL_REFERENCE','VARCHAR2(120)');

  DBMS_OUTPUT.PUT_LINE('=== DEPOSIT_ACCOUNT delta ===');
  add_col('DEPOSIT_ACCOUNT','OPENED_PRODUCT_VERSION_ID','NUMBER(19)');
  add_col('DEPOSIT_ACCOUNT','CURRENT_PRODUCT_VERSION_ID','NUMBER(19)');
  add_col('DEPOSIT_ACCOUNT','OWNERSHIP_TYPE_CODE','VARCHAR2(20)');
  add_col('DEPOSIT_ACCOUNT','OPENED_ON','DATE');
  add_col('DEPOSIT_ACCOUNT','ACTIVATION_DEADLINE_AT','TIMESTAMP(6)');
  add_col('DEPOSIT_ACCOUNT','ACTIVATION_POLICY_VERSION','VARCHAR2(60)');
  add_col('DEPOSIT_ACCOUNT','LEDGER_BALANCE','NUMBER(19,4)');
  add_col('DEPOSIT_ACCOUNT','AVAILABLE_BALANCE','NUMBER(19,4)');
  add_col('DEPOSIT_ACCOUNT','DEBIT_CAPABILITY_CODE','VARCHAR2(30)');

  DBMS_OUTPUT.PUT_LINE('=== New obligation/allocation structures ===');
  IF NOT sequence_exists('SEQ_DEP_OPEN_OBLIGATION') THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.SEQ_DEP_OPEN_OBLIGATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('ADD : SEQ_DEP_OPEN_OBLIGATION');
  ELSE DBMS_OUTPUT.PUT_LINE('OK  : SEQ_DEP_OPEN_OBLIGATION'); END IF;

  IF NOT table_exists('DEPOSIT_OPENING_OBLIGATION') THEN
    EXECUTE IMMEDIATE q'[CREATE TABLE DPS2.DEPOSIT_OPENING_OBLIGATION (
      OPENING_OBLIGATION_ID NUMBER(19) NOT NULL,
      OPENING_REQUEST_ID NUMBER(19) NOT NULL,
      OBLIGATION_TYPE_CODE VARCHAR2(40) NOT NULL,
      SOURCE_SYSTEM_CODE VARCHAR2(40) NOT NULL,
      SOURCE_REFERENCE VARCHAR2(120),
      DESCRIPTION VARCHAR2(500),
      GROSS_AMOUNT NUMBER(19,4) NOT NULL,
      WAIVED_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
      FINAL_AMOUNT NUMBER(19,4) NOT NULL,
      CURRENCY_CODE VARCHAR2(3) NOT NULL,
      MANDATORY_FOR_ACTIVATION_FLAG NUMBER(1) DEFAULT 1 NOT NULL,
      SETTLEMENT_STATUS_CODE VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
      SETTLEMENT_REFERENCE VARCHAR2(120),
      WAIVER_REFERENCE VARCHAR2(120),
      SETTLED_AT TIMESTAMP(6),
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY VARCHAR2(100) NOT NULL,
      UPDATED_AT TIMESTAMP(6),
      UPDATED_BY VARCHAR2(100),
      RECORD_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEP_OPEN_OBLIGATION PRIMARY KEY (OPENING_OBLIGATION_ID)
    )]';
    DBMS_OUTPUT.PUT_LINE('ADD : DEPOSIT_OPENING_OBLIGATION');
  ELSE DBMS_OUTPUT.PUT_LINE('OK  : DEPOSIT_OPENING_OBLIGATION'); END IF;

  IF NOT sequence_exists('SEQ_DEP_OPEN_FUND_ALLOC') THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.SEQ_DEP_OPEN_FUND_ALLOC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('ADD : SEQ_DEP_OPEN_FUND_ALLOC');
  ELSE DBMS_OUTPUT.PUT_LINE('OK  : SEQ_DEP_OPEN_FUND_ALLOC'); END IF;

  IF NOT table_exists('DEPOSIT_OPENING_FUND_ALLOC') THEN
    EXECUTE IMMEDIATE q'[CREATE TABLE DPS2.DEPOSIT_OPENING_FUND_ALLOC (
      OPENING_FUND_ALLOC_ID NUMBER(19) NOT NULL,
      OPENING_FUNDING_ID NUMBER(19) NOT NULL,
      OPENING_OBLIGATION_ID NUMBER(19) NOT NULL,
      ALLOCATED_AMOUNT NUMBER(19,4) NOT NULL,
      ALLOCATION_STATUS_CODE VARCHAR2(30) NOT NULL,
      SETTLEMENT_REFERENCE VARCHAR2(120),
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY VARCHAR2(100) NOT NULL,
      UPDATED_AT TIMESTAMP(6),
      UPDATED_BY VARCHAR2(100),
      RECORD_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEP_OPEN_FUND_ALLOC PRIMARY KEY (OPENING_FUND_ALLOC_ID)
    )]';
    DBMS_OUTPUT.PUT_LINE('ADD : DEPOSIT_OPENING_FUND_ALLOC');
  ELSE DBMS_OUTPUT.PUT_LINE('OK  : DEPOSIT_OPENING_FUND_ALLOC'); END IF;

  add_constraint('FK_DOR_JOINT_BASIS','ALTER TABLE DPS2.DEPOSIT_OPENING_REQUEST ADD CONSTRAINT FK_DOR_JOINT_BASIS FOREIGN KEY (JOINT_ACCOUNT_BASIS_CODE) REFERENCES DPS2.REF_DEP_OPEN_JOINT_BASIS (JOINT_ACCOUNT_BASIS_CODE)');
  add_constraint('FK_DOR_ACT_STATUS','ALTER TABLE DPS2.DEPOSIT_OPENING_REQUEST ADD CONSTRAINT FK_DOR_ACT_STATUS FOREIGN KEY (ACTIVATION_STATUS_CODE) REFERENCES DPS2.REF_DEP_OPEN_ACTIVATION_STATUS (ACTIVATION_STATUS_CODE)');
  add_constraint('FK_DOF_FUND_PURPOSE','ALTER TABLE DPS2.DEPOSIT_OPENING_FUNDING ADD CONSTRAINT FK_DOF_FUND_PURPOSE FOREIGN KEY (FUNDING_PURPOSE_CODE) REFERENCES DPS2.REF_DEP_OPEN_FUND_PURPOSE (FUNDING_PURPOSE_CODE)');
  add_constraint('CK_DOF_OWN_VER','ALTER TABLE DPS2.DEPOSIT_OPENING_FUNDING ADD CONSTRAINT CK_DOF_OWN_VER CHECK (SOURCE_OWNERSHIP_VERIFIED_FLAG IN (0,1))');
  add_constraint('FK_DOCHECK_PHASE','ALTER TABLE DPS2.DEPOSIT_OPENING_CHECK ADD CONSTRAINT FK_DOCHECK_PHASE FOREIGN KEY (CHECK_PHASE_CODE) REFERENCES DPS2.REF_DEP_OPEN_CHECK_PHASE (CHECK_PHASE_CODE)');
  add_constraint('FK_DOCHECK_SCOPE','ALTER TABLE DPS2.DEPOSIT_OPENING_CHECK ADD CONSTRAINT FK_DOCHECK_SCOPE FOREIGN KEY (BLOCKING_SCOPE_CODE) REFERENCES DPS2.REF_DEP_OPEN_BLOCKING_SCOPE (BLOCKING_SCOPE_CODE)');
  add_constraint('CK_DOC_REQ_FLAG','ALTER TABLE DPS2.DEPOSIT_OPENING_CHECK ADD CONSTRAINT CK_DOC_REQ_FLAG CHECK (REQUIRED_FLAG IN (0,1))');
  add_constraint('CK_DOC_RECHECK_FLAG','ALTER TABLE DPS2.DEPOSIT_OPENING_CHECK ADD CONSTRAINT CK_DOC_RECHECK_FLAG CHECK (RECHECK_REQUIRED_FLAG IN (0,1))');
  add_constraint('FK_DOO_REQ','ALTER TABLE DPS2.DEPOSIT_OPENING_OBLIGATION ADD CONSTRAINT FK_DOO_REQ FOREIGN KEY (OPENING_REQUEST_ID) REFERENCES DPS2.DEPOSIT_OPENING_REQUEST (OPENING_REQUEST_ID)');
  add_constraint('FK_DOO_TYPE','ALTER TABLE DPS2.DEPOSIT_OPENING_OBLIGATION ADD CONSTRAINT FK_DOO_TYPE FOREIGN KEY (OBLIGATION_TYPE_CODE) REFERENCES DPS2.REF_DEP_OPEN_OBLIGATION_TYPE (OBLIGATION_TYPE_CODE)');
  add_constraint('FK_DOO_SETTLE','ALTER TABLE DPS2.DEPOSIT_OPENING_OBLIGATION ADD CONSTRAINT FK_DOO_SETTLE FOREIGN KEY (SETTLEMENT_STATUS_CODE) REFERENCES DPS2.REF_DEP_OPEN_SETTLEMENT_STATUS (SETTLEMENT_STATUS_CODE)');
  add_constraint('CK_DOO_MANDATORY','ALTER TABLE DPS2.DEPOSIT_OPENING_OBLIGATION ADD CONSTRAINT CK_DOO_MANDATORY CHECK (MANDATORY_FOR_ACTIVATION_FLAG IN (0,1))');
  add_constraint('FK_DOFA_FUNDING','ALTER TABLE DPS2.DEPOSIT_OPENING_FUND_ALLOC ADD CONSTRAINT FK_DOFA_FUNDING FOREIGN KEY (OPENING_FUNDING_ID) REFERENCES DPS2.DEPOSIT_OPENING_FUNDING (OPENING_FUNDING_ID)');
  add_constraint('FK_DOFA_OBLIGATION','ALTER TABLE DPS2.DEPOSIT_OPENING_FUND_ALLOC ADD CONSTRAINT FK_DOFA_OBLIGATION FOREIGN KEY (OPENING_OBLIGATION_ID) REFERENCES DPS2.DEPOSIT_OPENING_OBLIGATION (OPENING_OBLIGATION_ID)');

  add_index('IX_DOO_REQUEST','CREATE INDEX DPS2.IX_DOO_REQUEST ON DPS2.DEPOSIT_OPENING_OBLIGATION (OPENING_REQUEST_ID)');
  add_index('IX_DOFA_FUNDING','CREATE INDEX DPS2.IX_DOFA_FUNDING ON DPS2.DEPOSIT_OPENING_FUND_ALLOC (OPENING_FUNDING_ID)');
  add_index('IX_DOFA_OBLIGATION','CREATE INDEX DPS2.IX_DOFA_OBLIGATION ON DPS2.DEPOSIT_OPENING_FUND_ALLOC (OPENING_OBLIGATION_ID)');
END;
/

PROMPT === Seed v5 reference deltas ===

MERGE INTO DPS2.REF_DEP_OPEN_CHECK_TYPE t
USING (SELECT 'REGULATORY' CHECK_TYPE_CODE FROM dual) s
ON (t.CHECK_TYPE_CODE=s.CHECK_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='نظارتی',t.TITLE_EN='Regulatory',t.DESCRIPTION='Operational Opening v5 alignment',t.DISPLAY_ORDER=80,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (CHECK_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('REGULATORY','نظارتی','Regulatory','Operational Opening v5 alignment',80,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK_TYPE t
USING (SELECT 'FINANCIAL' CHECK_TYPE_CODE FROM dual) s
ON (t.CHECK_TYPE_CODE=s.CHECK_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='مالی',t.TITLE_EN='Financial',t.DESCRIPTION='Operational Opening v5 alignment',t.DISPLAY_ORDER=90,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (CHECK_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('FINANCIAL','مالی','Financial','Operational Opening v5 alignment',90,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK_TYPE t
USING (SELECT 'PRODUCT' CHECK_TYPE_CODE FROM dual) s
ON (t.CHECK_TYPE_CODE=s.CHECK_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='محصول',t.TITLE_EN='Product',t.DESCRIPTION='Operational Opening v5 alignment',t.DISPLAY_ORDER=100,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (CHECK_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('PRODUCT','محصول','Product','Operational Opening v5 alignment',100,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK_TYPE t
USING (SELECT 'CONTRACTUAL' CHECK_TYPE_CODE FROM dual) s
ON (t.CHECK_TYPE_CODE=s.CHECK_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='قراردادی',t.TITLE_EN='Contractual',t.DESCRIPTION='Operational Opening v5 alignment',t.DISPLAY_ORDER=110,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (CHECK_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('CONTRACTUAL','قراردادی','Contractual','Operational Opening v5 alignment',110,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK_TYPE t
USING (SELECT 'NOTIFICATION' CHECK_TYPE_CODE FROM dual) s
ON (t.CHECK_TYPE_CODE=s.CHECK_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='اعلان',t.TITLE_EN='Notification',t.DESCRIPTION='Operational Opening v5 alignment',t.DISPLAY_ORDER=120,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (CHECK_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('NOTIFICATION','اعلان','Notification','Operational Opening v5 alignment',120,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_FUND_PURPOSE t
USING (SELECT 'OPENING_TOTAL' FUNDING_PURPOSE_CODE FROM dual) s
ON (t.FUNDING_PURPOSE_CODE=s.FUNDING_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='کل تعهدات افتتاح',t.TITLE_EN='Opening Total',t.DESCRIPTION='Operational Opening v5 funding allocation purpose',t.DISPLAY_ORDER=10,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (FUNDING_PURPOSE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('OPENING_TOTAL','کل تعهدات افتتاح','Opening Total','Operational Opening v5 funding allocation purpose',10,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_FUND_PURPOSE t
USING (SELECT 'INITIAL_BALANCE' FUNDING_PURPOSE_CODE FROM dual) s
ON (t.FUNDING_PURPOSE_CODE=s.FUNDING_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='فقط مانده اولیه',t.TITLE_EN='Initial Balance',t.DESCRIPTION='Operational Opening v5 funding allocation purpose',t.DISPLAY_ORDER=11,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (FUNDING_PURPOSE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('INITIAL_BALANCE','فقط مانده اولیه','Initial Balance','Operational Opening v5 funding allocation purpose',11,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_FUND_PURPOSE t
USING (SELECT 'CHARGES' FUNDING_PURPOSE_CODE FROM dual) s
ON (t.FUNDING_PURPOSE_CODE=s.FUNDING_PURPOSE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA='فقط هزینه‌ها / کارمزدها',t.TITLE_EN='Charges',t.DESCRIPTION='Operational Opening v5 funding allocation purpose',t.DISPLAY_ORDER=12,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT (FUNDING_PURPOSE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES ('CHARGES','فقط هزینه‌ها / کارمزدها','Charges','Operational Opening v5 funding allocation purpose',12,1,SYSTIMESTAMP,'DEP_OPEN_V5',1);

UPDATE DPS2.REF_DEP_OPEN_FUND_PURPOSE
   SET IS_ACTIVE=0, UPDATED_AT=SYSTIMESTAMP, UPDATED_BY='DEP_OPEN_V5', RECORD_VERSION=NVL(RECORD_VERSION,0)+1
 WHERE FUNDING_PURPOSE_CODE IN ('OPENING_BALANCE','OBLIGATION_SETTLEMENT','COMBINED')
   AND IS_ACTIVE<>0;

UPDATE DPS2.REF_DEP_OPEN_CHECK
   SET IS_ACTIVE=0, UPDATED_AT=SYSTIMESTAMP, UPDATED_BY='DEP_OPEN_V5', RECORD_VERSION=NVL(RECORD_VERSION,0)+1
 WHERE CHECK_CODE IN ('SANCTIONS','OPENING_RULES')
   AND IS_ACTIVE<>0;

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'CUSTOMER_IDENTITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='احراز هویت / نهاب / شناسه شهاب / داده مرجع',t.TITLE_EN='Customer Identity',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=10,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=10,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('CUSTOMER_IDENTITY','احراز هویت / نهاب / شناسه شهاب / داده مرجع','Customer Identity','Operational Opening v5 alignment',10,1,'COMPLIANCE',1,10,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'MOBILE_OWNERSHIP' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='تلفن همراه متعلق به مشتری / کانال اعلان معتبر',t.TITLE_EN='Mobile Ownership',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=20,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=20,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('MOBILE_OWNERSHIP','تلفن همراه متعلق به مشتری / کانال اعلان معتبر','Mobile Ownership','Operational Opening v5 alignment',20,1,'COMPLIANCE',1,20,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'LEGAL_CAPACITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اهلیت قانونی / سن / قیم / شخص حقوقی',t.TITLE_EN='Legal Capacity',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=30,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=30,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('LEGAL_CAPACITY','اهلیت قانونی / سن / قیم / شخص حقوقی','Legal Capacity','Operational Opening v5 alignment',30,1,'COMPLIANCE',1,30,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'RESIDENCY_ELIGIBILITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اقامت / تابعیت و شرایط اختصاصی مشتری خارجی یا غیرمقیم',t.TITLE_EN='Residency Eligibility',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=40,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=40,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('RESIDENCY_ELIGIBILITY','اقامت / تابعیت و شرایط اختصاصی مشتری خارجی یا غیرمقیم','Residency Eligibility','Operational Opening v5 alignment',40,1,'COMPLIANCE',0,40,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'REMOTE_IDENTITY_AUTH' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='احراز هویت الکترونیکی و کنترل ریسک کانال غیرحضوری',t.TITLE_EN='Remote Identity Authentication',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=50,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=50,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('REMOTE_IDENTITY_AUTH','احراز هویت الکترونیکی و کنترل ریسک کانال غیرحضوری','Remote Identity Authentication','Operational Opening v5 alignment',50,1,'COMPLIANCE',0,50,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'LEGAL_ENTITY_REGISTRY_STATUS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='وضعیت ثبتی شخص حقوقی / در شرف تأسیس / شناسه ملی',t.TITLE_EN='Legal Entity Registry Status',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=60,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='INQUIRY',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=60,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('LEGAL_ENTITY_REGISTRY_STATUS','وضعیت ثبتی شخص حقوقی / در شرف تأسیس / شناسه ملی','Legal Entity Registry Status','Operational Opening v5 alignment',60,1,'INQUIRY',0,60,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'BENEFICIAL_OWNER' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='مالک واقعی (در صورت شمول)',t.TITLE_EN='Beneficial Owner',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=70,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=70,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('BENEFICIAL_OWNER','مالک واقعی (در صورت شمول)','Beneficial Owner','Operational Opening v5 alignment',70,1,'COMPLIANCE',0,70,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'REPRESENTATIVE_AUTHORITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اختیار نماینده / وکیل / قیم (در صورت شمول)',t.TITLE_EN='Representative Authority',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=80,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='AUTHORITY',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=80,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('REPRESENTATIVE_AUTHORITY','اختیار نماینده / وکیل / قیم (در صورت شمول)','Representative Authority','Operational Opening v5 alignment',80,1,'AUTHORITY',0,80,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'KYC_CDD' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='KYC / CDD',t.TITLE_EN='KYC / CDD',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=90,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=90,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('KYC_CDD','KYC / CDD','KYC / CDD','Operational Opening v5 alignment',90,1,'COMPLIANCE',1,90,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'PEP_SANCTIONS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='PEP / تحریم / فهرست‌های محدودیتی',t.TITLE_EN='PEP / Sanctions',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=100,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=100,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=1,t.RESULT_VALIDITY_MINUTES=60,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('PEP_SANCTIONS','PEP / تحریم / فهرست‌های محدودیتی','PEP / Sanctions','Operational Opening v5 alignment',100,1,'COMPLIANCE',1,100,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',1,60,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'CUSTOMER_RISK' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='سطح ریسک و EDD / منبع ثروت / تأیید مدیر ارشد',t.TITLE_EN='Customer Risk / EDD',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=110,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=110,t.DEFAULT_PHASE_CODE='PRE_APPROVAL',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('CUSTOMER_RISK','سطح ریسک و EDD / منبع ثروت / تأیید مدیر ارشد','Customer Risk / EDD','Operational Opening v5 alignment',110,1,'COMPLIANCE',1,110,'PRE_APPROVAL','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'EXPECTED_ACTIVITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='سطح فعالیت مورد انتظار',t.TITLE_EN='Expected Activity',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=120,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=120,t.DEFAULT_PHASE_CODE='PRE_APPROVAL',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('EXPECTED_ACTIVITY','سطح فعالیت مورد انتظار','Expected Activity','Operational Opening v5 alignment',120,1,'COMPLIANCE',1,120,'PRE_APPROVAL','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'ACCOUNT_COUNT_STATUS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='حساب پایه / تعداد حساب‌ها / راکد یا تعیین‌تکلیف‌نشده',t.TITLE_EN='Account Count / Status',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=130,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='INQUIRY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=130,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('ACCOUNT_COUNT_STATUS','حساب پایه / تعداد حساب‌ها / راکد یا تعیین‌تکلیف‌نشده','Account Count / Status','Operational Opening v5 alignment',130,1,'INQUIRY',1,130,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'CURRENT_ACCOUNT_ELIGIBILITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='شرایط اختصاصی حساب جاری',t.TITLE_EN='Current Account Eligibility',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=140,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='INQUIRY',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=140,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('CURRENT_ACCOUNT_ELIGIBILITY','شرایط اختصاصی حساب جاری','Current Account Eligibility','Operational Opening v5 alignment',140,1,'INQUIRY',0,140,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'JOINT_ACCOUNT_ELIGIBILITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='مبنای مجاز حساب مشترک',t.TITLE_EN='Joint Account Eligibility',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=150,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=150,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('JOINT_ACCOUNT_ELIGIBILITY','مبنای مجاز حساب مشترک','Joint Account Eligibility','Operational Opening v5 alignment',150,1,'COMPLIANCE',0,150,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'PRODUCT_ELIGIBILITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اهلیت محصول / مشتری / کانال',t.TITLE_EN='Product Eligibility',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=160,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='PRODUCT_RULE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=160,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('PRODUCT_ELIGIBILITY','اهلیت محصول / مشتری / کانال','Product Eligibility','Operational Opening v5 alignment',160,1,'PRODUCT_RULE',1,160,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'DOCUMENTS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='مدارک الزامی',t.TITLE_EN='Required Documents',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=170,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='DOCUMENT',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=170,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('DOCUMENTS','مدارک الزامی','Required Documents','Operational Opening v5 alignment',170,1,'DOCUMENT',1,170,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'INQUIRIES' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='استعلام‌های الزامی',t.TITLE_EN='Required Inquiries',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=180,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='INQUIRY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=180,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('INQUIRIES','استعلام‌های الزامی','Required Inquiries','Operational Opening v5 alignment',180,1,'INQUIRY',1,180,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'SIGNATORY_AUTHORITY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='مالکیت / صاحب امضا / حدود اختیار',t.TITLE_EN='Signatory Authority',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=190,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='AUTHORITY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=190,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('SIGNATORY_AUTHORITY','مالکیت / صاحب امضا / حدود اختیار','Signatory Authority','Operational Opening v5 alignment',190,1,'AUTHORITY',1,190,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'TERMS_ACCEPTANCE' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='پذیرش قرارداد و شروط نسخه محصول',t.TITLE_EN='Terms Acceptance',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=200,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='CONSENT',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=200,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('TERMS_ACCEPTANCE','پذیرش قرارداد و شروط نسخه محصول','Terms Acceptance','Operational Opening v5 alignment',200,1,'CONSENT',1,200,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'SHARIA_CONTRACT' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='آمادگی قرارداد/پروفایل شرعی محصول',t.TITLE_EN='Sharia Contract Readiness',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=210,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='PRODUCT_RULE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=210,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('SHARIA_CONTRACT','آمادگی قرارداد/پروفایل شرعی محصول','Sharia Contract Readiness','Operational Opening v5 alignment',210,1,'PRODUCT_RULE',1,210,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'TAX_PROFILE' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='وضعیت مالیاتی / تجاری در صورت شمول',t.TITLE_EN='Tax Profile',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=220,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='INQUIRY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=220,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('TAX_PROFILE','وضعیت مالیاتی / تجاری در صورت شمول','Tax Profile','Operational Opening v5 alignment',220,1,'INQUIRY',1,220,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'DUPLICATE_REQUEST' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='عدم تکرار درخواست / Idempotency',t.TITLE_EN='Duplicate Request / Idempotency',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=230,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='OPERATIONAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=230,t.DEFAULT_PHASE_CODE='PRE_ACCOUNT_CREATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_CREATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('DUPLICATE_REQUEST','عدم تکرار درخواست / Idempotency','Duplicate Request / Idempotency','Operational Opening v5 alignment',230,1,'OPERATIONAL',1,230,'PRE_ACCOUNT_CREATION','ACCOUNT_CREATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'OPENING_CREATE_GATE' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اعتبار نهایی کنترل‌های مرحله ایجاد حساب',t.TITLE_EN='Opening Create Gate',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=240,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='OPERATIONAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=240,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('OPENING_CREATE_GATE','اعتبار نهایی کنترل‌های مرحله ایجاد حساب','Opening Create Gate','Operational Opening v5 alignment',240,1,'OPERATIONAL',1,240,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'ACTIVATION_WINDOW_VALID' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='عدم انقضای مهلت فعال‌سازی / تعیین‌تکلیف حساب Pending',t.TITLE_EN='Activation Window Valid',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=250,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='OPERATIONAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=250,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('ACTIVATION_WINDOW_VALID','عدم انقضای مهلت فعال‌سازی / تعیین‌تکلیف حساب Pending','Activation Window Valid','Operational Opening v5 alignment',250,1,'OPERATIONAL',1,250,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'CBI_SIAH_REGISTRATION' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='ثبت حساب در سامانه مرجع بانک مرکزی / سیاح و دریافت شماره پیگیری',t.TITLE_EN='CBI SIAH Registration',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=260,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='REGULATORY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=260,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('CBI_SIAH_REGISTRATION','ثبت حساب در سامانه مرجع بانک مرکزی / سیاح و دریافت شماره پیگیری','CBI SIAH Registration','Operational Opening v5 alignment',260,1,'REGULATORY',1,260,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'FINANCIAL_SETTLEMENT' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='تأمین وجه و تسویه تمام تعهدات مالی الزامی',t.TITLE_EN='Financial Settlement',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=270,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='FINANCIAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=270,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('FINANCIAL_SETTLEMENT','تأمین وجه و تسویه تمام تعهدات مالی الزامی','Financial Settlement','Operational Opening v5 alignment',270,1,'FINANCIAL',1,270,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'MIN_OPENING_BALANCE' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='احراز مانده افتتاح موردنیاز محصول (در صورت شمول)',t.TITLE_EN='Minimum Opening Balance',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=280,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='FINANCIAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=280,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('MIN_OPENING_BALANCE','احراز مانده افتتاح موردنیاز محصول (در صورت شمول)','Minimum Opening Balance','Operational Opening v5 alignment',280,1,'FINANCIAL',1,280,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'FUNDING_SOURCE_VALIDATION' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اعتبار منبع وجه / مالکیت منبع / EDD',t.TITLE_EN='Funding Source Validation',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=290,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=290,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('FUNDING_SOURCE_VALIDATION','اعتبار منبع وجه / مالکیت منبع / EDD','Funding Source Validation','Operational Opening v5 alignment',290,1,'COMPLIANCE',1,290,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'FINAL_COMPLIANCE_RECHECK' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='تازه‌سازی کنترل‌های Compliance/Sanctions پیش از بهره‌برداری',t.TITLE_EN='Final Compliance Recheck',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=300,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='COMPLIANCE',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=300,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=1,t.RESULT_VALIDITY_MINUTES=60,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('FINAL_COMPLIANCE_RECHECK','تازه‌سازی کنترل‌های Compliance/Sanctions پیش از بهره‌برداری','Final Compliance Recheck','Operational Opening v5 alignment',300,1,'COMPLIANCE',1,300,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',1,60,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'SIGNATORY_MANDATE_READY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='Materialize شدن صاحبان امضا و Mandate عملیاتی',t.TITLE_EN='Signatory Mandate Ready',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=310,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='OPERATIONAL',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=310,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('SIGNATORY_MANDATE_READY','Materialize شدن صاحبان امضا و Mandate عملیاتی','Signatory Mandate Ready','Operational Opening v5 alignment',310,1,'OPERATIONAL',1,310,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'PRODUCT_OPERATIONAL_SETUP' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اعتبار نسخه محصول و تنظیمات عملیاتی الزامی',t.TITLE_EN='Product Operational Setup',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=320,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='PRODUCT',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=320,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('PRODUCT_OPERATIONAL_SETUP','اعتبار نسخه محصول و تنظیمات عملیاتی الزامی','Product Operational Setup','Operational Opening v5 alignment',320,1,'PRODUCT',1,320,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'TERM_PROFIT_INSTRUCTIONS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='مدت/سررسید/سود برای سپرده مدت‌دار (در صورت شمول)',t.TITLE_EN='Term / Profit Instructions',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=330,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='CONTRACTUAL',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=330,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('TERM_PROFIT_INSTRUCTIONS','مدت/سررسید/سود برای سپرده مدت‌دار (در صورت شمول)','Term / Profit Instructions','Operational Opening v5 alignment',330,1,'CONTRACTUAL',0,330,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'RESTRICTIONS_READY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اعمال محدودیت‌های قانونی/ریسکی لازم پیش از بهره‌برداری',t.TITLE_EN='Restrictions Ready',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=340,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='REGULATORY',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=340,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='ACCOUNT_ACTIVATION',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('RESTRICTIONS_READY','اعمال محدودیت‌های قانونی/ریسکی لازم پیش از بهره‌برداری','Restrictions Ready','Operational Opening v5 alignment',340,1,'REGULATORY',1,340,'PRE_ACTIVATION','ACCOUNT_ACTIVATION',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'JOINT_COMMERCIAL_CONFIRMATION' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='تأیید تجاری حساب مشترک (در صورت شمول)',t.TITLE_EN='Joint Commercial Confirmation',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=350,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='REGULATORY',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=350,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='DEBIT_CAPABILITY',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('JOINT_COMMERCIAL_CONFIRMATION','تأیید تجاری حساب مشترک (در صورت شمول)','Joint Commercial Confirmation','Operational Opening v5 alignment',350,1,'REGULATORY',0,350,'PRE_ACTIVATION','DEBIT_CAPABILITY',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'LEGAL_ENTITY_NATIONAL_ID_READY' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='اختصاص شناسه ملی شخص حقوقی در شرف تأسیس (در صورت شمول)',t.TITLE_EN='Legal Entity National Id Ready',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=360,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='REGULATORY',t.DEFAULT_REQUIRED_FLAG=0,
  t.EXECUTION_ORDER=360,t.DEFAULT_PHASE_CODE='PRE_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='DEBIT_CAPABILITY',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('LEGAL_ENTITY_NATIONAL_ID_READY','اختصاص شناسه ملی شخص حقوقی در شرف تأسیس (در صورت شمول)','Legal Entity National Id Ready','Operational Opening v5 alignment',360,1,'REGULATORY',0,360,'PRE_ACTIVATION','DEBIT_CAPABILITY',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);

MERGE INTO DPS2.REF_DEP_OPEN_CHECK t
USING (SELECT 'ACCOUNT_OPENED_SMS' CHECK_CODE FROM dual) s
ON (t.CHECK_CODE=s.CHECK_CODE)
WHEN MATCHED THEN UPDATE SET
  t.TITLE_FA='ثبت/ارسال اعلان افتتاح به موبایل متعلق به مشتری',t.TITLE_EN='Account Opened SMS',t.DESCRIPTION='Operational Opening v5 alignment',
  t.DISPLAY_ORDER=370,t.IS_ACTIVE=1,t.CHECK_TYPE_CODE='NOTIFICATION',t.DEFAULT_REQUIRED_FLAG=1,
  t.EXECUTION_ORDER=370,t.DEFAULT_PHASE_CODE='POST_ACTIVATION',t.DEFAULT_BLOCKING_SCOPE_CODE='NON_BLOCKING',
  t.DEFAULT_RECHECK_FLAG=0,t.RESULT_VALIDITY_MINUTES=NULL,
  t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='DEP_OPEN_V5',t.RECORD_VERSION=NVL(t.RECORD_VERSION,0)+1
WHEN NOT MATCHED THEN INSERT
  (CHECK_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CHECK_TYPE_CODE,DEFAULT_REQUIRED_FLAG,EXECUTION_ORDER,DEFAULT_PHASE_CODE,DEFAULT_BLOCKING_SCOPE_CODE,DEFAULT_RECHECK_FLAG,RESULT_VALIDITY_MINUTES,CREATED_AT,CREATED_BY,RECORD_VERSION)
VALUES
  ('ACCOUNT_OPENED_SMS','ثبت/ارسال اعلان افتتاح به موبایل متعلق به مشتری','Account Opened SMS','Operational Opening v5 alignment',370,1,'NOTIFICATION',1,370,'POST_ACTIVATION','NON_BLOCKING',0,NULL,SYSTIMESTAMP,'DEP_OPEN_V5',1);


COMMIT;

PROMPT === Backfill v5 metadata without inventing financial history ===
UPDATE DPS2.DEPOSIT_OPENING_REQUEST r
   SET ACTIVATION_STATUS_CODE = CASE
       WHEN r.CREATED_ACCOUNT_ID IS NULL THEN 'NOT_CREATED'
       WHEN EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT a WHERE a.ACCOUNT_ID=r.CREATED_ACCOUNT_ID AND a.ACCOUNT_STATUS_CODE='ACTIVE') THEN 'ACTIVATED'
       ELSE 'PENDING_READINESS'
     END,
       UPDATED_AT = SYSTIMESTAMP,
       UPDATED_BY = 'DEP_OPEN_V5',
       RECORD_VERSION = NVL(RECORD_VERSION,0)+1
 WHERE r.ACTIVATION_STATUS_CODE IS NULL
    OR (r.ACTIVATION_STATUS_CODE='NOT_CREATED' AND r.CREATED_ACCOUNT_ID IS NOT NULL);

UPDATE DPS2.DEPOSIT_ACCOUNT a
   SET OPENED_PRODUCT_VERSION_ID = NVL(a.OPENED_PRODUCT_VERSION_ID,a.PRODUCT_VERSION_ID),
       CURRENT_PRODUCT_VERSION_ID = NVL(a.CURRENT_PRODUCT_VERSION_ID,a.PRODUCT_VERSION_ID),
       OWNERSHIP_TYPE_CODE = NVL(a.OWNERSHIP_TYPE_CODE,(SELECT r.OWNERSHIP_TYPE_CODE FROM DPS2.DEPOSIT_OPENING_REQUEST r WHERE r.OPENING_REQUEST_ID=a.OPENING_REQUEST_ID)),
       OPENED_ON = NVL(a.OPENED_ON,(SELECT r.REQUESTED_OPENING_DATE FROM DPS2.DEPOSIT_OPENING_REQUEST r WHERE r.OPENING_REQUEST_ID=a.OPENING_REQUEST_ID)),
       UPDATED_AT = SYSTIMESTAMP,
       UPDATED_BY = 'DEP_OPEN_V5',
       RECORD_VERSION = NVL(a.RECORD_VERSION,0)+1
 WHERE a.OPENED_PRODUCT_VERSION_ID IS NULL
    OR a.CURRENT_PRODUCT_VERSION_ID IS NULL
    OR a.OWNERSHIP_TYPE_CODE IS NULL
    OR a.OPENED_ON IS NULL;

UPDATE DPS2.DEPOSIT_OPENING_CHECK c
   SET (CHECK_PHASE_CODE,BLOCKING_SCOPE_CODE,REQUIRED_FLAG,RECHECK_REQUIRED_FLAG) =
       (SELECT r.DEFAULT_PHASE_CODE,r.DEFAULT_BLOCKING_SCOPE_CODE,NVL(r.DEFAULT_REQUIRED_FLAG,1),NVL(r.DEFAULT_RECHECK_FLAG,0)
          FROM DPS2.REF_DEP_OPEN_CHECK r
         WHERE r.CHECK_CODE=c.CHECK_CODE)
 WHERE EXISTS (SELECT 1 FROM DPS2.REF_DEP_OPEN_CHECK r WHERE r.CHECK_CODE=c.CHECK_CODE)
   AND (c.CHECK_PHASE_CODE IS NULL OR c.BLOCKING_SCOPE_CODE IS NULL);

COMMIT;

PROMPT ============================================================
PROMPT Verification - v5 structural delta
PROMPT ============================================================
SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='DPS2'
   AND ((TABLE_NAME='DEPOSIT_OPENING_REQUEST' AND COLUMN_NAME IN ('CUSTOMER_RISK_LEVEL_CODE','RISK_ASSESSMENT_REFERENCE','EXPECTED_ACTIVITY_REFERENCE','JOINT_ACCOUNT_BASIS_CODE','JOINT_BASIS_REFERENCE','ACTIVATION_STATUS_CODE','ACTIVATION_DEADLINE_AT'))
     OR (TABLE_NAME='DEPOSIT_OPENING_FUNDING' AND COLUMN_NAME IN ('SOURCE_PARTY_ID','SOURCE_ACCOUNT_ID','FUNDING_PURPOSE_CODE','SOURCE_OWNERSHIP_VERIFIED_FLAG','SOURCE_VERIFICATION_REFERENCE','CASH_MANAGEMENT_TXN_REF','ATTEMPT_AT'))
     OR (TABLE_NAME='DEPOSIT_OPENING_CHECK' AND COLUMN_NAME IN ('CHECK_PHASE_CODE','BLOCKING_SCOPE_CODE','REQUIRED_FLAG','RECHECK_REQUIRED_FLAG','VALID_UNTIL','SOURCE_EVALUATION_REFERENCE'))
     OR (TABLE_NAME='DEPOSIT_OPENING_BATCH' AND COLUMN_NAME IN ('BULK_OPENING_BASIS_CODE','LEGAL_BASIS_REFERENCE','CDD_APPROVAL_REFERENCE'))
     OR (TABLE_NAME='DEPOSIT_ACCOUNT' AND COLUMN_NAME IN ('OPENED_PRODUCT_VERSION_ID','CURRENT_PRODUCT_VERSION_ID','OWNERSHIP_TYPE_CODE','OPENED_ON','ACTIVATION_DEADLINE_AT','ACTIVATION_POLICY_VERSION','LEDGER_BALANCE','AVAILABLE_BALANCE','DEBIT_CAPABILITY_CODE')))
 ORDER BY TABLE_NAME,COLUMN_ID;

SELECT OWNER,TABLE_NAME FROM ALL_TABLES
 WHERE OWNER='DPS2' AND TABLE_NAME IN ('DEPOSIT_OPENING_OBLIGATION','DEPOSIT_OPENING_FUND_ALLOC')
 ORDER BY TABLE_NAME;

SELECT c.TABLE_NAME,
       c.CONSTRAINT_NAME,
       cc.COLUMN_NAME,
       p.TABLE_NAME AS REFERENCED_TABLE,
       pc.COLUMN_NAME AS REFERENCED_COLUMN,
       c.STATUS
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONS_COLUMNS cc
    ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS p
    ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
  JOIN ALL_CONS_COLUMNS pc
    ON pc.OWNER=p.OWNER AND pc.CONSTRAINT_NAME=p.CONSTRAINT_NAME AND pc.POSITION=cc.POSITION
 WHERE c.OWNER='DPS2'
   AND c.CONSTRAINT_TYPE='R'
   AND (
        (c.TABLE_NAME='DEPOSIT_OPENING_REQUEST' AND cc.COLUMN_NAME IN ('JOINT_ACCOUNT_BASIS_CODE','ACTIVATION_STATUS_CODE'))
     OR (c.TABLE_NAME='DEPOSIT_OPENING_FUNDING' AND cc.COLUMN_NAME='FUNDING_PURPOSE_CODE')
     OR (c.TABLE_NAME='DEPOSIT_OPENING_CHECK' AND cc.COLUMN_NAME IN ('CHECK_PHASE_CODE','BLOCKING_SCOPE_CODE'))
     OR (c.TABLE_NAME='DEPOSIT_OPENING_OBLIGATION' AND cc.COLUMN_NAME IN ('OPENING_REQUEST_ID','OBLIGATION_TYPE_CODE','SETTLEMENT_STATUS_CODE'))
     OR (c.TABLE_NAME='DEPOSIT_OPENING_FUND_ALLOC' AND cc.COLUMN_NAME IN ('OPENING_FUNDING_ID','OPENING_OBLIGATION_ID'))
   )
 ORDER BY c.TABLE_NAME,cc.COLUMN_NAME;

SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE,STATUS
  FROM ALL_CONSTRAINTS
 WHERE OWNER='DPS2'
   AND CONSTRAINT_NAME IN ('CK_DOF_OWN_VER','CK_DOC_REQ_FLAG','CK_DOC_RECHECK_FLAG','CK_DOO_MANDATORY')
 ORDER BY TABLE_NAME,CONSTRAINT_NAME;

SELECT 'ACTIVE_V5_OPENING_CHECKS' METRIC,COUNT(*) VALUE FROM DPS2.REF_DEP_OPEN_CHECK WHERE IS_ACTIVE=1
UNION ALL SELECT 'ACTIVE_V5_CHECK_TYPES',COUNT(*) FROM DPS2.REF_DEP_OPEN_CHECK_TYPE WHERE IS_ACTIVE=1
UNION ALL SELECT 'ACTIVE_V5_FUND_PURPOSES',COUNT(*) FROM DPS2.REF_DEP_OPEN_FUND_PURPOSE WHERE IS_ACTIVE=1
UNION ALL SELECT 'LEGACY_CHECKS_ACTIVE',COUNT(*) FROM DPS2.REF_DEP_OPEN_CHECK WHERE CHECK_CODE IN ('SANCTIONS','OPENING_RULES') AND IS_ACTIVE=1
UNION ALL SELECT 'LEGACY_FUND_PURPOSES_ACTIVE',COUNT(*) FROM DPS2.REF_DEP_OPEN_FUND_PURPOSE WHERE FUNDING_PURPOSE_CODE IN ('OPENING_BALANCE','OBLIGATION_SETTLEMENT','COMBINED') AND IS_ACTIVE=1;

PROMPT ============================================================
PROMPT SUCCESS: Phase 10 Operational Opening v5 schema foundation reconciled.
PROMPT NOTE: Ledger/available balances, activation deadline and SIAH references are NOT fabricated for historical accounts.
PROMPT NOTE: CREATED_ACCOUNT_NO is intentionally not persisted; ACCOUNT_NO remains resolvable through CREATED_ACCOUNT_ID.
PROMPT ============================================================
