-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11K - Wave B Statements, Limits & Maturity Batch (Operational Steps 06-08)
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11K - Wave B Statements + Limits + Maturity
PROMPT Steps 06-08 / canonical tables / sequence reconciliation only
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21230,'Required Wave B table DPS2.'||UPPER(p)||' is missing.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS
    v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE';
      DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||UPPER(s)||' START WITH '||v_target);
      RETURN;
    END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN
      v_delta:=v_target-v_current;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta);
      BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy;
      EXCEPTION WHEN OTHERS THEN
        BEGIN EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
      END;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1';
      DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||UPPER(s)||' advanced above MAX('||UPPER(t)||'.'||UPPER(pk)||')='||(v_target-1));
    ELSE
      DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(s)||' next='||v_current||' max='||(v_target-1));
    END IF;
  END;
BEGIN
  req_table('DEPOSIT_STATEMENT_TEMPLATE');
  req_table('DEPOSIT_STATEMENT_REQUEST');
  req_table('DEPOSIT_STATEMENT');
  req_table('DEPOSIT_STATEMENT_ITEM');
  req_table('DEPOSIT_STATEMENT_DELIVERY');
  req_table('DEPOSIT_ACCOUNT_LIMIT');
  req_table('DEPOSIT_ACCOUNT_LIMIT_USAGE');
  req_table('DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION');
  req_table('DEPOSIT_MATURITY_PROCESS_RUN');
  req_table('DEPOSIT_MATURITY_PROCESS_ITEM');
  req_table('DEPOSIT_MATURITY_EVENT');
  req_table('DEPOSIT_OPERATION_IDEMPOTENCY');

  ensure_seq('SEQ_DEPOSIT_STATEMENT_TEMPLATE','DEPOSIT_STATEMENT_TEMPLATE','STATEMENT_TEMPLATE_ID');
  ensure_seq('SEQ_DEPOSIT_STATEMENT_REQUEST','DEPOSIT_STATEMENT_REQUEST','STATEMENT_REQUEST_ID');
  ensure_seq('SEQ_DEPOSIT_STATEMENT','DEPOSIT_STATEMENT','STATEMENT_ID');
  ensure_seq('SEQ_DEPOSIT_STATEMENT_ITEM','DEPOSIT_STATEMENT_ITEM','STATEMENT_ITEM_ID');
  ensure_seq('SEQ_DEPOSIT_STATEMENT_DELIVERY','DEPOSIT_STATEMENT_DELIVERY','STATEMENT_DELIVERY_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_LIMIT','DEPOSIT_ACCOUNT_LIMIT','ACCOUNT_LIMIT_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_LIMIT_USAGE','DEPOSIT_ACCOUNT_LIMIT_USAGE','ACCOUNT_LIMIT_USAGE_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION','DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION','ACCOUNT_TX_RESTRICTION_ID');
  ensure_seq('SEQ_DEPOSIT_MATURITY_PROCESS_RUN','DEPOSIT_MATURITY_PROCESS_RUN','MATURITY_PROCESS_RUN_ID');
  ensure_seq('SEQ_DEPOSIT_MATURITY_PROCESS_ITEM','DEPOSIT_MATURITY_PROCESS_ITEM','MATURITY_PROCESS_ITEM_ID');
  ensure_seq('SEQ_DEPOSIT_MATURITY_EVENT','DEPOSIT_MATURITY_EVENT','MATURITY_EVENT_ID');
  ensure_seq('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11K_WAVE_B_RECONCILIATION_PASS
PROMPT ============================================================
