-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11E - Controlled Closure + Reopening
-- Scope: four deposits / DPS2 only. No business-data DML.
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11E - Controlled Closure + Reopening
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p_table VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table); RETURN v>0; END;
  FUNCTION index_exists(p_index VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p_index); RETURN v>0; END;
  FUNCTION index_columns_exist(p_table VARCHAR2,p_columns VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
    SELECT COUNT(*) INTO v FROM (
      SELECT IC.INDEX_NAME FROM ALL_IND_COLUMNS IC
       WHERE IC.INDEX_OWNER='DPS2' AND IC.TABLE_OWNER='DPS2' AND IC.TABLE_NAME=UPPER(p_table)
       GROUP BY IC.INDEX_NAME
      HAVING LISTAGG(IC.COLUMN_NAME,',') WITHIN GROUP (ORDER BY IC.COLUMN_POSITION)=UPPER(REPLACE(p_columns,' ',''))
    ); RETURN v>0;
  END;
  PROCEDURE require_table(p_table VARCHAR2) IS BEGIN IF NOT table_exists(p_table) THEN RAISE_APPLICATION_ERROR(-21150,'Required table DPS2.'||UPPER(p_table)||' is missing.'); END IF; END;
  PROCEDURE ensure_index(p_table VARCHAR2,p_columns VARCHAR2,p_index VARCHAR2,p_sql VARCHAR2) IS BEGIN
    IF index_columns_exist(p_table,p_columns) THEN DBMS_OUTPUT.PUT_LINE('KEEP : DPS2.'||UPPER(p_table)||' index coverage ('||UPPER(REPLACE(p_columns,' ',''))||')');
    ELSIF index_exists(p_index) THEN RAISE_APPLICATION_ERROR(-21151,'Index DPS2.'||UPPER(p_index)||' exists with different columns.');
    ELSE EXECUTE IMMEDIATE p_sql; DBMS_OUTPUT.PUT_LINE('ADD  : DPS2.'||UPPER(p_index)); END IF;
  END;
BEGIN
  require_table('DEPOSIT_ACCOUNT_CLOSURE');
  require_table('DEPOSIT_ACCOUNT_CLOSURE_CHECK');
  require_table('DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM');
  require_table('DEPOSIT_ACCOUNT_REOPENING');
  require_table('DEPOSIT_OPERATION_APPROVAL_REQUEST');
  require_table('DEPOSIT_ACCOUNT');
  require_table('DEPOSIT_ACCOUNT_HOLD');
  require_table('DEPOSIT_ACCOUNT_BALANCE');
  require_table('DEPOSIT_BALANCE_RESERVATION');
  require_table('DEPOSIT_SUBLEDGER_ENTRY');
  require_table('DEPOSIT_ACCOUNT_STATUS_HISTORY');
  require_table('DEPOSIT_ACCOUNT_LIFECYCLE_EVENT');
  require_table('DEPOSIT_OPERATION_IDEMPOTENCY');

  ensure_index('DEPOSIT_ACCOUNT_CLOSURE','ACCOUNT_ID,CLOSURE_STATUS_CODE','IX_DEP_CLOSURE_ACCOUNT_STATUS',
    'CREATE INDEX DPS2.IX_DEP_CLOSURE_ACCOUNT_STATUS ON DPS2.DEPOSIT_ACCOUNT_CLOSURE(ACCOUNT_ID,CLOSURE_STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_ACCOUNT_REOPENING','ACCOUNT_ID,REOPEN_STATUS_CODE','IX_DEP_REOPEN_ACCOUNT_STATUS',
    'CREATE INDEX DPS2.IX_DEP_REOPEN_ACCOUNT_STATUS ON DPS2.DEPOSIT_ACCOUNT_REOPENING(ACCOUNT_ID,REOPEN_STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_OPERATION_APPROVAL_REQUEST','ACCOUNT_ID,APPROVAL_STATUS_CODE','IX_DEP_APPROVAL_ACCOUNT_STATUS',
    'CREATE INDEX DPS2.IX_DEP_APPROVAL_ACCOUNT_STATUS ON DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST(ACCOUNT_ID,APPROVAL_STATUS_CODE) TABLESPACE ITS_DPS2');

  DBMS_OUTPUT.PUT_LINE('SUCCESS: Phase 11E closure/reopening runtime readiness reconciled.');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11E_SCHEMA_RUNTIME_READINESS_PASS
PROMPT ============================================================
