WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
PROMPT ============================================================
PROMPT DPS2 Phase 11N-C - Steps 03-04 Canonical Closure
PROMPT Schema contract reconciliation (no business DML; minimal canonical CHECK reconciliation)
PROMPT ============================================================
DECLARE
  v NUMBER;
  PROCEDURE req_table(p_table VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table);
    IF v=0 THEN RAISE_APPLICATION_ERROR(-20401,'Missing DPS2 table: '||p_table); END IF;
  END;
  PROCEDURE req_col(p_table VARCHAR2,p_col VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_col);
    IF v=0 THEN RAISE_APPLICATION_ERROR(-20402,'Missing DPS2 column: '||p_table||'.'||p_col); END IF;
  END;
BEGIN
  req_table('DEPOSIT_TERM_CONTRACT');
  req_table('DEPOSIT_MATURITY_EVENT');
  req_table('DEPOSIT_TERM_RENEWAL');
  req_table('DEPOSIT_TERM_SETTLEMENT');
  req_table('DEPOSIT_TERM_PARTIAL_WITHDRAWAL');
  req_table('DEPOSIT_TERM_EARLY_TERMINATION');
  req_table('DEPOSIT_TRANSACTION');
  req_table('DEPOSIT_TRANSACTION_LEG');
  req_table('DEPOSIT_TRANSACTION_AUTHORIZATION');
  req_table('DEPOSIT_SUBLEDGER_ENTRY');
  req_table('DEPOSIT_ACCOUNT_BALANCE');
  req_table('DEPOSIT_ACCOUNT_CLOSURE');
  req_table('DEPOSIT_ACCOUNT_STATUS_HISTORY');
  req_table('DEPOSIT_ACCOUNT_PROFIT_PROFILE');
  req_table('DEPOSIT_PROFIT_PERIOD');
  req_table('DEPOSIT_PROFIT_ACCRUAL');
  req_table('DEPOSIT_PROFIT_ACCRUAL_DETAIL');
  req_table('DEPOSIT_PROFIT_ADJUSTMENT');
  req_table('DEPOSIT_PROFIT_PAYMENT');
  req_table('DEPOSIT_PROFIT_CONTRACT');
  req_table('DEPOSIT_PROFIT_POSTING');

  req_col('DEPOSIT_TERM_PARTIAL_WITHDRAWAL','TRANSACTION_ID');
  req_col('DEPOSIT_TERM_EARLY_TERMINATION','SETTLEMENT_TRANSACTION_ID');
  req_col('DEPOSIT_TERM_EARLY_TERMINATION','EARLY_TERMINATION_RATE');
  req_col('DEPOSIT_TERM_SETTLEMENT','TRANSACTION_ID');
  req_col('DEPOSIT_MATURITY_EVENT','SETTLEMENT_TRANSACTION_ID');
  req_col('DEPOSIT_ACCOUNT_CLOSURE','SETTLEMENT_TRANSACTION_REFERENCE');
  req_col('DEPOSIT_ACCOUNT_STATUS_HISTORY','REASON_CODE');
  req_col('DEPOSIT_PROFIT_PAYMENT','POSTING_REFERENCE');
  req_col('DEPOSIT_TRANSACTION_LEG','POSTING_REFERENCE');
  req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_ID');
  req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_LEG_ID');
  DBMS_OUTPUT.PUT_LINE('KEEP   | Canonical Step 03/04 tables/columns are present');
END;
/

DECLARE
  v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v
    FROM ALL_CONSTRAINTS
   WHERE OWNER='DPS2'
     AND TABLE_NAME='DEPOSIT_ACCOUNT_STATUS_HISTORY'
     AND CONSTRAINT_NAME='CHK_DEPOSIT_ACCOUNT_STATUS_HISTORY_REASON_CODE';
  IF v>0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_ACCOUNT_STATUS_HISTORY DROP CONSTRAINT CHK_DEPOSIT_ACCOUNT_STATUS_HISTORY_REASON_CODE';
  END IF;
  EXECUTE IMMEDIATE q'[ALTER TABLE DPS2.DEPOSIT_ACCOUNT_STATUS_HISTORY ADD CONSTRAINT CHK_DEPOSIT_ACCOUNT_STATUS_HISTORY_REASON_CODE CHECK (REASON_CODE IS NULL OR REASON_CODE IN ('CUSTOMER_REQUEST','OPERATIONAL_CONTROL','COMPLIANCE_ACTION','INACTIVITY_POLICY','MATURITY_INSTRUCTION','BULK_CONTROLLED','NO_LONGER_NEEDED','SERVICE_CONSOLIDATION','PRODUCT_REPLACEMENT','NON_RENEWAL','LEGAL_ENFORCEMENT','REGULATORY_ENFORCEMENT','FRAUD_CONFIRMED','PROLONGED_INACTIVITY','BANK_POLICY','DATA_CORRECTION','TERM_EARLY_TERMINATION'))]';
  DBMS_OUTPUT.PUT_LINE('RECONCILE | DEPOSIT_ACCOUNT_STATUS_HISTORY.REASON_CODE accepts documented TERM_EARLY_TERMINATION');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11NC_SCHEMA_RECONCILIATION_PASS
PROMPT ============================================================
