-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11I - Operational Step 05 Deposit Transaction Processing
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11I - Step 05 Deposit Transaction Processing
PROMPT Validation / Authorization / Legs / Posting / Reversal
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION column_exists(t VARCHAR2,c VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t) AND COLUMN_NAME=UPPER(c); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION constraint_exists(t VARCHAR2,c VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(t) AND CONSTRAINT_NAME=UPPER(c) AND STATUS='ENABLED'; RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21190,'Required canonical Step 05 table DPS2.'||UPPER(p)||' is missing. Apply the attached DPS2 canonical DDL before Phase 11I.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE req_col(t VARCHAR2,c VARCHAR2) IS BEGIN IF NOT column_exists(t,c) THEN RAISE_APPLICATION_ERROR(-21191,'Required column DPS2.'||UPPER(t)||'.'||UPPER(c)||' is missing.'); END IF; END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS
    v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE';
      DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||UPPER(s)||' START WITH '||v_target);
      RETURN;
    END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN
      v_delta:=v_target-v_current;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta);
      BEGIN
        EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy;
      EXCEPTION WHEN OTHERS THEN
        BEGIN EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
      END;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1';
      DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||UPPER(s)||' advanced above MAX('||UPPER(t)||'.'||UPPER(pk)||')='||(v_target-1));
    ELSE
      DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(s)||' next='||v_current||' max='||(v_target-1));
    END IF;
  END;
  PROCEDURE ensure_fk(t VARCHAR2,c VARCHAR2,sql_text VARCHAR2) IS BEGIN IF constraint_exists(t,c) THEN DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||c); ELSE EXECUTE IMMEDIATE sql_text; DBMS_OUTPUT.PUT_LINE('ADD    | DPS2.'||c); END IF; END;
BEGIN
  req_table('DEPOSIT_TRANSACTION');
  req_table('DEPOSIT_TRANSACTION_VALIDATION');
  req_table('DEPOSIT_TRANSACTION_AUTHORIZATION');
  req_table('DEPOSIT_TRANSACTION_STATUS_HISTORY');
  req_table('DEPOSIT_TRANSACTION_LEG');
  req_table('DEPOSIT_TRANSFER_DETAIL');
  req_table('DEPOSIT_CASH_TRANSACTION_DETAIL');
  req_table('DEPOSIT_TRANSACTION_REVERSAL');
  req_table('DEPOSIT_SUBLEDGER_ENTRY');
  req_table('DEPOSIT_ACCOUNT_BALANCE');
  req_table('DEPOSIT_ACCOUNT_HOLD');
  req_table('DEPOSIT_ACCOUNT_LIMIT');
  req_table('DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION');
  req_table('DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION');
  req_table('DEPOSIT_OPERATION_IDEMPOTENCY');

  req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_ID'); req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_LEG_ID'); req_col('DEPOSIT_SUBLEDGER_ENTRY','REVERSAL_OF_ENTRY_ID');
  req_col('DEPOSIT_TRANSACTION','IDEMPOTENCY_KEY'); req_col('DEPOSIT_TRANSACTION','TRANSACTION_STATUS_CODE'); req_col('DEPOSIT_TRANSACTION','DEBIT_CREDIT_CODE');

  ensure_seq('SEQ_DEPOSIT_TRANSACTION','DEPOSIT_TRANSACTION','TRANSACTION_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSACTION_VALIDATION','DEPOSIT_TRANSACTION_VALIDATION','TRANSACTION_VALIDATION_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSACTION_AUTHORIZATION','DEPOSIT_TRANSACTION_AUTHORIZATION','TRANSACTION_AUTHORIZATION_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSACTION_STATUS_HISTORY','DEPOSIT_TRANSACTION_STATUS_HISTORY','TRANSACTION_STATUS_HISTORY_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSACTION_LEG','DEPOSIT_TRANSACTION_LEG','TRANSACTION_LEG_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSFER_DETAIL','DEPOSIT_TRANSFER_DETAIL','TRANSFER_DETAIL_ID');
  ensure_seq('SEQ_DEPOSIT_CASH_TRANSACTION_DETAIL','DEPOSIT_CASH_TRANSACTION_DETAIL','CASH_TRANSACTION_DETAIL_ID');
  ensure_seq('SEQ_DEPOSIT_TRANSACTION_REVERSAL','DEPOSIT_TRANSACTION_REVERSAL','TRANSACTION_REVERSAL_ID');
  ensure_seq('SEQ_DEPOSIT_SUBLEDGER_ENTRY','DEPOSIT_SUBLEDGER_ENTRY','SUBLEDGER_ENTRY_ID');

  ensure_fk('DEPOSIT_SUBLEDGER_ENTRY','FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID','ALTER TABLE DPS2.DEPOSIT_SUBLEDGER_ENTRY ADD CONSTRAINT FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES DPS2.DEPOSIT_TRANSACTION(TRANSACTION_ID) ENABLE');
  ensure_fk('DEPOSIT_SUBLEDGER_ENTRY','FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_LEG_ID','ALTER TABLE DPS2.DEPOSIT_SUBLEDGER_ENTRY ADD CONSTRAINT FK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_LEG_ID FOREIGN KEY (TRANSACTION_LEG_ID) REFERENCES DPS2.DEPOSIT_TRANSACTION_LEG(TRANSACTION_LEG_ID) ENABLE');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11I_STEP05_TRANSACTION_RECONCILIATION_PASS
PROMPT ============================================================
