-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11G - Profit / Interest Processing
-- Scope: operational profit contract snapshot, accrual, and same-deposit posting through Phase 11D.
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11G - Profit / Interest Processing
PROMPT ============================================================

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS BEGIN EXECUTE IMMEDIATE p_sql; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-955 THEN RAISE; END IF; END;
BEGIN
  ddl('CREATE SEQUENCE DPS2.SEQ_DEP_PROFIT_CONTRACT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  ddl('CREATE SEQUENCE DPS2.SEQ_DEP_PROFIT_ACCRUAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  ddl('CREATE SEQUENCE DPS2.SEQ_DEP_PROFIT_POSTING START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');

  ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_CONTRACT(
    PROFIT_CONTRACT_ID NUMBER(19) NOT NULL,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    OPENING_REQUEST_ID NUMBER(19) NOT NULL,
    PRODUCT_VERSION_ID NUMBER(19) NOT NULL,
    PRICING_RULE_ID NUMBER(19), PRICING_COMPONENT_ID NUMBER(19), RATE_TIER_ID NUMBER(19), PROFIT_PAYMENT_RULE_ID NUMBER(19),
    ANNUAL_RATE NUMBER(18,8) NOT NULL,
    CALCULATION_METHOD_CODE VARCHAR2(30 CHAR) NOT NULL,
    DAY_COUNT_BASIS_CODE VARCHAR2(30 CHAR) NOT NULL,
    ACCRUAL_FREQUENCY_CODE VARCHAR2(30 CHAR) NOT NULL,
    PAYMENT_FREQUENCY_CODE VARCHAR2(30 CHAR) NOT NULL,
    PAYMENT_DAY_RULE_CODE VARCHAR2(30 CHAR) NOT NULL,
    FIRST_PAYMENT_RULE_CODE VARCHAR2(30 CHAR) NOT NULL,
    HOLIDAY_ADJUSTMENT_CODE VARCHAR2(30 CHAR) NOT NULL,
    PAYMENT_DESTINATION_CODE VARCHAR2(40 CHAR) NOT NULL,
    DESTINATION_ACCOUNT_REFERENCE VARCHAR2(120 CHAR),
    EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
    ACCRUED_AMOUNT NUMBER(24,4) DEFAULT 0 NOT NULL,
    PAID_AMOUNT NUMBER(24,4) DEFAULT 0 NOT NULL,
    LAST_ACCRUAL_DATE DATE, LAST_PAYMENT_DATE DATE,
    STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    SOURCE_OPENING_PROFIT_INSTRUCTION_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DEP_PROFIT_CONTRACT PRIMARY KEY(PROFIT_CONTRACT_ID),
    CONSTRAINT FK_DEP_PROFIT_CONTRACT_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_DEP_PROFIT_RATE CHECK(ANNUAL_RATE>=0),
    CONSTRAINT CK_DEP_PROFIT_DATES CHECK(EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=EFFECTIVE_FROM),
    CONSTRAINT CK_DEP_PROFIT_AMOUNTS CHECK(ACCRUED_AMOUNT>=0 AND PAID_AMOUNT>=0),
    CONSTRAINT CK_DEP_PROFIT_STATUS CHECK(STATUS_CODE IN ('ACTIVE','ENDED','CANCELLED')),
    CONSTRAINT CK_DEP_PROFIT_METHOD CHECK(CALCULATION_METHOD_CODE IN ('PERCENTAGE')),
    CONSTRAINT CK_DEP_PROFIT_DAYCOUNT CHECK(DAY_COUNT_BASIS_CODE IN ('ACT_365','ACT_360')),
    CONSTRAINT CK_DEP_PROFIT_DEST CHECK(PAYMENT_DESTINATION_CODE IN ('SAME_DEPOSIT','LINKED_ACCOUNT','CUSTOMER_SELECTED_ACCOUNT')),
    CONSTRAINT CK_DEP_PROFIT_RECVER CHECK(RECORD_VERSION>0)
  )~');

  ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_ACCRUAL(
    PROFIT_ACCRUAL_ID NUMBER(19) NOT NULL, PROFIT_CONTRACT_ID NUMBER(19) NOT NULL, ACCOUNT_ID NUMBER(19) NOT NULL,
    ACCRUAL_FROM_DATE DATE NOT NULL, ACCRUAL_TO_DATE DATE NOT NULL, DAY_COUNT NUMBER(10) NOT NULL,
    BASIS_AMOUNT NUMBER(24,4) NOT NULL, ANNUAL_RATE NUMBER(18,8) NOT NULL, ACCRUED_AMOUNT NUMBER(24,4) NOT NULL,
    DAY_COUNT_BASIS_CODE VARCHAR2(30 CHAR) NOT NULL, CALCULATION_METHOD_CODE VARCHAR2(30 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'ACCRUED' NOT NULL, PROFIT_POSTING_ID NUMBER(19),
    CALCULATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CALCULATED_BY VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT PK_DEP_PROFIT_ACCRUAL PRIMARY KEY(PROFIT_ACCRUAL_ID),
    CONSTRAINT FK_DEP_PROFIT_ACCRUAL_CON FOREIGN KEY(PROFIT_CONTRACT_ID) REFERENCES DPS2.DEPOSIT_PROFIT_CONTRACT(PROFIT_CONTRACT_ID),
    CONSTRAINT FK_DEP_PROFIT_ACCRUAL_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_DEP_PROFIT_ACCR_DATES CHECK(ACCRUAL_TO_DATE>=ACCRUAL_FROM_DATE),
    CONSTRAINT CK_DEP_PROFIT_ACCR_DAY CHECK(DAY_COUNT>0),
    CONSTRAINT CK_DEP_PROFIT_ACCR_AMT CHECK(BASIS_AMOUNT>=0 AND ACCRUED_AMOUNT>=0),
    CONSTRAINT CK_DEP_PROFIT_ACCR_STATUS CHECK(STATUS_CODE IN ('ACCRUED','POSTED','REVERSED'))
  )~');

  ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_POSTING(
    PROFIT_POSTING_ID NUMBER(19) NOT NULL, PROFIT_CONTRACT_ID NUMBER(19) NOT NULL, ACCOUNT_ID NUMBER(19) NOT NULL,
    POSTING_DATE DATE NOT NULL, AMOUNT NUMBER(24,4) NOT NULL, DESTINATION_CODE VARCHAR2(40 CHAR) NOT NULL,
    DESTINATION_ACCOUNT_REFERENCE VARCHAR2(120 CHAR), SUBLEDGER_ENTRY_ID NUMBER(19), STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'POSTED' NOT NULL,
    POSTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, POSTED_BY VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT PK_DEP_PROFIT_POSTING PRIMARY KEY(PROFIT_POSTING_ID),
    CONSTRAINT FK_DEP_PROFIT_POST_CON FOREIGN KEY(PROFIT_CONTRACT_ID) REFERENCES DPS2.DEPOSIT_PROFIT_CONTRACT(PROFIT_CONTRACT_ID),
    CONSTRAINT FK_DEP_PROFIT_POST_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_DEP_PROFIT_POST_SUB FOREIGN KEY(SUBLEDGER_ENTRY_ID) REFERENCES DPS2.DEPOSIT_SUBLEDGER_ENTRY(SUBLEDGER_ENTRY_ID),
    CONSTRAINT CK_DEP_PROFIT_POST_AMT CHECK(AMOUNT>0),
    CONSTRAINT CK_DEP_PROFIT_POST_STATUS CHECK(STATUS_CODE IN ('POSTED','REVERSED'))
  )~');
END;
/

-- Reconcile earlier Phase 11G physical models before indexes/FKs/query usage.
-- Earlier prototype iterations may have created one or more profit tables with a smaller
-- column set. Because CREATE TABLE above is idempotent (-955 ignored), reconcile the
-- full Repository contract here. Missing required columns are auto-added only when the
-- legacy table is empty; if rows exist, stop rather than fabricate financial data.
DECLARE
  v_rows NUMBER;
  v_col  NUMBER;

  PROCEDURE ensure_col(p_table VARCHAR2, p_name VARCHAR2, p_ddl VARCHAR2, p_required NUMBER DEFAULT 1) IS
  BEGIN
    SELECT COUNT(*) INTO v_col
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='DPS2'
       AND TABLE_NAME=UPPER(p_table)
       AND COLUMN_NAME=UPPER(p_name);

    IF v_col=0 THEN
      EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM DPS2.'||p_table INTO v_rows;
      IF p_required=1 AND v_rows>0 THEN
        RAISE_APPLICATION_ERROR(-21181,
          'Legacy DPS2.'||UPPER(p_table)||' contains '||v_rows||
          ' row(s) but required column '||UPPER(p_name)||
          ' is missing. Manual legacy-data mapping is required; no financial value was fabricated.');
      END IF;
      EXECUTE IMMEDIATE 'ALTER TABLE DPS2.'||p_table||' ADD ('||p_name||' '||p_ddl||')';
      DBMS_OUTPUT.PUT_LINE('RECONCILE | DPS2.'||UPPER(p_table)||'.'||UPPER(p_name)||' added');
    ELSE
      DBMS_OUTPUT.PUT_LINE('RECONCILE | DPS2.'||UPPER(p_table)||'.'||UPPER(p_name)||' already exists');
    END IF;
  END;
BEGIN
  -- Contract columns used by DepositProfitRepository.contract/lockContract/provisioning.
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PROFIT_CONTRACT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','ACCOUNT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','OPENING_REQUEST_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PRODUCT_VERSION_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PRICING_RULE_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PRICING_COMPONENT_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','RATE_TIER_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PROFIT_PAYMENT_RULE_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','ANNUAL_RATE','NUMBER(18,8) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','CALCULATION_METHOD_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','DAY_COUNT_BASIS_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','ACCRUAL_FREQUENCY_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PAYMENT_FREQUENCY_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PAYMENT_DAY_RULE_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','FIRST_PAYMENT_RULE_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','HOLIDAY_ADJUSTMENT_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PAYMENT_DESTINATION_CODE','VARCHAR2(40 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','DESTINATION_ACCOUNT_REFERENCE','VARCHAR2(120 CHAR)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','EFFECTIVE_FROM','DATE NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','EFFECTIVE_TO','DATE',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','ACCRUED_AMOUNT','NUMBER(24,4) DEFAULT 0 NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','PAID_AMOUNT','NUMBER(24,4) DEFAULT 0 NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','LAST_ACCRUAL_DATE','DATE',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','LAST_PAYMENT_DATE','DATE',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','STATUS_CODE',q'~VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL~');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','SOURCE_OPENING_PROFIT_INSTRUCTION_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','CREATED_AT','TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','CREATED_BY','VARCHAR2(100 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_CONTRACT','UPDATED_AT','TIMESTAMP(6)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','UPDATED_BY','VARCHAR2(100 CHAR)',0);
  ensure_col('DEPOSIT_PROFIT_CONTRACT','RECORD_VERSION','NUMBER(10) DEFAULT 1 NOT NULL');

  -- Accrual columns used by accrual calculation, query, posting linkage, and account index.
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','PROFIT_ACCRUAL_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','PROFIT_CONTRACT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','ACCOUNT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','ACCRUAL_FROM_DATE','DATE NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','ACCRUAL_TO_DATE','DATE NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','DAY_COUNT','NUMBER(10) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','BASIS_AMOUNT','NUMBER(24,4) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','ANNUAL_RATE','NUMBER(18,8) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','ACCRUED_AMOUNT','NUMBER(24,4) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','DAY_COUNT_BASIS_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','CALCULATION_METHOD_CODE','VARCHAR2(30 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','STATUS_CODE',q'~VARCHAR2(20 CHAR) DEFAULT 'ACCRUED' NOT NULL~');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','PROFIT_POSTING_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','CALCULATED_AT','TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL');
  ensure_col('DEPOSIT_PROFIT_ACCRUAL','CALCULATED_BY','VARCHAR2(100 CHAR) NOT NULL');

  -- Posting columns used by same-deposit posting and 11D subledger traceability.
  ensure_col('DEPOSIT_PROFIT_POSTING','PROFIT_POSTING_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','PROFIT_CONTRACT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','ACCOUNT_ID','NUMBER(19) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','POSTING_DATE','DATE NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','AMOUNT','NUMBER(24,4) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','DESTINATION_CODE','VARCHAR2(40 CHAR) NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','DESTINATION_ACCOUNT_REFERENCE','VARCHAR2(120 CHAR)',0);
  ensure_col('DEPOSIT_PROFIT_POSTING','SUBLEDGER_ENTRY_ID','NUMBER(19)',0);
  ensure_col('DEPOSIT_PROFIT_POSTING','STATUS_CODE',q'~VARCHAR2(20 CHAR) DEFAULT 'POSTED' NOT NULL~');
  ensure_col('DEPOSIT_PROFIT_POSTING','POSTED_AT','TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL');
  ensure_col('DEPOSIT_PROFIT_POSTING','POSTED_BY','VARCHAR2(100 CHAR) NOT NULL');
END;
/

-- Reconcile legacy-only accrual period column from pre-11G prototypes.
-- The canonical 11G accrual contract is date-range based (ACCRUAL_FROM_DATE / ACCRUAL_TO_DATE)
-- and DepositProfitRepository does not write PROFIT_PERIOD_ID. Never invent a period identifier.
-- If a legacy table is still empty, relax the obsolete NOT NULL requirement; if rows exist, stop.
DECLARE
  v_exists   NUMBER:=0;
  v_nullable VARCHAR2(1);
  v_rows     NUMBER:=0;
BEGIN
  SELECT COUNT(*) INTO v_exists
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='DPS2'
     AND TABLE_NAME='DEPOSIT_PROFIT_ACCRUAL'
     AND COLUMN_NAME='PROFIT_PERIOD_ID';

  IF v_exists=1 THEN
    SELECT NULLABLE INTO v_nullable
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='DPS2'
       AND TABLE_NAME='DEPOSIT_PROFIT_ACCRUAL'
       AND COLUMN_NAME='PROFIT_PERIOD_ID';

    IF v_nullable='N' THEN
      SELECT COUNT(*) INTO v_rows FROM DPS2.DEPOSIT_PROFIT_ACCRUAL;
      IF v_rows>0 THEN
        RAISE_APPLICATION_ERROR(-21182,
          'Legacy DPS2.DEPOSIT_PROFIT_ACCRUAL contains '||v_rows||
          ' row(s) and obsolete required column PROFIT_PERIOD_ID. Manual legacy-period mapping is required; no period identifier was fabricated.');
      END IF;
      EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_PROFIT_ACCRUAL MODIFY (PROFIT_PERIOD_ID NULL)';
      DBMS_OUTPUT.PUT_LINE('RECONCILE | DPS2.DEPOSIT_PROFIT_ACCRUAL.PROFIT_PERIOD_ID legacy NOT NULL relaxed (empty table)');
    ELSE
      DBMS_OUTPUT.PUT_LINE('RECONCILE | DPS2.DEPOSIT_PROFIT_ACCRUAL.PROFIT_PERIOD_ID legacy column already nullable');
    END IF;
  ELSE
    DBMS_OUTPUT.PUT_LINE('RECONCILE | DPS2.DEPOSIT_PROFIT_ACCRUAL.PROFIT_PERIOD_ID legacy column not present');
  END IF;
END;
/

DECLARE
  v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND CONSTRAINT_NAME='FK_DEP_PROFIT_ACCR_POST';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_PROFIT_ACCRUAL ADD CONSTRAINT FK_DEP_PROFIT_ACCR_POST FOREIGN KEY(PROFIT_POSTING_ID) REFERENCES DPS2.DEPOSIT_PROFIT_POSTING(PROFIT_POSTING_ID)';
  END IF;
END;
/

DECLARE
  FUNCTION index_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p); RETURN v>0; END;
BEGIN
  IF NOT index_exists('UX_DEP_PROFIT_ACTIVE_ACCOUNT') THEN EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX DPS2.UX_DEP_PROFIT_ACTIVE_ACCOUNT ON DPS2.DEPOSIT_PROFIT_CONTRACT(CASE WHEN STATUS_CODE='ACTIVE' THEN ACCOUNT_ID END) TABLESPACE ITS_DPS2~'; END IF;
  IF NOT index_exists('IX_DEP_PROFIT_ACCRUAL_ACCOUNT') THEN EXECUTE IMMEDIATE 'CREATE INDEX DPS2.IX_DEP_PROFIT_ACCRUAL_ACCOUNT ON DPS2.DEPOSIT_PROFIT_ACCRUAL(ACCOUNT_ID,ACCRUAL_TO_DATE) TABLESPACE ITS_DPS2'; END IF;
  IF NOT index_exists('IX_DEP_PROFIT_POST_ACCOUNT') THEN EXECUTE IMMEDIATE 'CREATE INDEX DPS2.IX_DEP_PROFIT_POST_ACCOUNT ON DPS2.DEPOSIT_PROFIT_POSTING(ACCOUNT_ID,POSTING_DATE) TABLESPACE ITS_DPS2'; END IF;
END;
/

-- Backfill only where Opening already contains an explicit profit snapshot. No product rate is fabricated here.
INSERT INTO DPS2.DEPOSIT_PROFIT_CONTRACT(
  PROFIT_CONTRACT_ID,ACCOUNT_ID,OPENING_REQUEST_ID,PRODUCT_VERSION_ID,PRICING_RULE_ID,PRICING_COMPONENT_ID,RATE_TIER_ID,PROFIT_PAYMENT_RULE_ID,
  ANNUAL_RATE,CALCULATION_METHOD_CODE,DAY_COUNT_BASIS_CODE,ACCRUAL_FREQUENCY_CODE,PAYMENT_FREQUENCY_CODE,PAYMENT_DAY_RULE_CODE,
  FIRST_PAYMENT_RULE_CODE,HOLIDAY_ADJUSTMENT_CODE,PAYMENT_DESTINATION_CODE,DESTINATION_ACCOUNT_REFERENCE,EFFECTIVE_FROM,EFFECTIVE_TO,
  ACCRUED_AMOUNT,PAID_AMOUNT,LAST_ACCRUAL_DATE,STATUS_CODE,SOURCE_OPENING_PROFIT_INSTRUCTION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION)
SELECT DPS2.SEQ_DEP_PROFIT_CONTRACT.NEXTVAL,A.ACCOUNT_ID,A.OPENING_REQUEST_ID,A.CURRENT_PRODUCT_VERSION_ID,
       P.PRICING_RULE_ID,P.PRICING_COMPONENT_ID,P.RATE_TIER_ID,P.PROFIT_PAYMENT_RULE_ID,P.RATE_VALUE,
       NVL(P.CALCULATION_METHOD_CODE,'PERCENTAGE'),NVL(P.DAY_COUNT_BASIS_CODE,'ACT_365'),NVL(P.ACCRUAL_FREQUENCY_CODE,'DAILY'),
       NVL(P.PAYMENT_FREQUENCY_CODE,'MATURITY'),NVL(P.PAYMENT_DAY_RULE_CODE,'MATURITY_DATE'),NVL(P.FIRST_PAYMENT_RULE_CODE,'MATURITY_ONLY'),
       NVL(P.HOLIDAY_ADJUSTMENT_CODE,'NEXT_BUSINESS_DAY'),NVL(P.PAYMENT_DESTINATION_CODE,'SAME_DEPOSIT'),P.DESTINATION_ACCOUNT_REFERENCE,
       NVL(OT.START_DATE,NVL(A.OPENED_ON,TRUNC(SYSDATE))),OT.MATURITY_DATE,0,0,NVL(OT.START_DATE,NVL(A.OPENED_ON,TRUNC(SYSDATE))),
       'ACTIVE',P.OPENING_PROFIT_INSTRUCTION_ID,SYSTIMESTAMP,'PHASE11G_MIGRATION',1
  FROM DPS2.DEPOSIT_ACCOUNT A
  JOIN DPS2.DEPOSIT_OPENING_PROFIT_INSTRUCTION P ON P.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID
  LEFT JOIN DPS2.DEPOSIT_OPENING_TERM OT ON OT.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID
 WHERE P.RATE_VALUE IS NOT NULL AND P.RATE_VALUE>=0
   AND NOT EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_CONTRACT C WHERE C.ACCOUNT_ID=A.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE');

UPDATE DPS2.DEPOSIT_TERM_CONTRACT T
   SET T.CONTRACT_RATE=(SELECT C.ANNUAL_RATE FROM DPS2.DEPOSIT_PROFIT_CONTRACT C WHERE C.ACCOUNT_ID=T.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE'),
       T.UPDATED_AT=SYSTIMESTAMP,T.UPDATED_BY='PHASE11G_MIGRATION',T.RECORD_VERSION=T.RECORD_VERSION+1
 WHERE T.STATUS_CODE='ACTIVE' AND T.CONTRACT_RATE IS NULL
   AND EXISTS(SELECT 1 FROM DPS2.DEPOSIT_PROFIT_CONTRACT C WHERE C.ACCOUNT_ID=T.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE');

COMMIT;
PROMPT ============================================================
PROMPT PHASE11G_PROFIT_PROCESSING_RECONCILIATION_PASS
PROMPT ============================================================
