SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 0.11.0 - Phase 11N Rapid Completion
PROMPT Steps 11-17 canonical operational trace / no business seed DML
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21410,'Required Phase11N table DPS2.'||UPPER(p)||' is missing.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER; BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE'; DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||s||' START WITH '||v_target); RETURN; END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN v_delta:=v_target-v_current; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta); EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||s||' advanced above max='||(v_target-1)); ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||s||' next='||v_current||' max='||(v_target-1)); END IF;
  END;
BEGIN
  -- Step 11
  req_table('DEPOSIT_REGULATORY_RULE'); req_table('DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION'); req_table('DEPOSIT_COMPLIANCE_EVALUATION'); req_table('DEPOSIT_RESERVE_REQUIREMENT'); req_table('DEPOSIT_RESERVE_POSITION'); req_table('DEPOSIT_REGULATORY_REPORT'); req_table('DEPOSIT_REGULATORY_REPORT_ITEM');
  -- Step 12
  req_table('DEPOSIT_FEE_RULE'); req_table('DEPOSIT_FEE_TIER'); req_table('DEPOSIT_ACCOUNT_FEE_OVERRIDE'); req_table('DEPOSIT_FEE_ASSESSMENT'); req_table('DEPOSIT_PRICING_PACKAGE'); req_table('DEPOSIT_PRICING_PACKAGE_BENEFIT'); req_table('DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT'); req_table('DEPOSIT_PROFITABILITY_SNAPSHOT');
  -- Step 13
  req_table('DEPOSIT_TAX_RULE'); req_table('DEPOSIT_TAX_EXEMPTION'); req_table('DEPOSIT_TAX_CALCULATION'); req_table('DEPOSIT_TAX_ADJUSTMENT'); req_table('DEPOSIT_TAX_LIABILITY'); req_table('DEPOSIT_TAX_PAYMENT'); req_table('DEPOSIT_TAX_CERTIFICATE'); req_table('DEPOSIT_TAX_RECONCILIATION');
  -- Steps 14-17
  req_table('DEPOSIT_RECONCILIATION_RUN'); req_table('DEPOSIT_RECONCILIATION_ITEM'); req_table('DEPOSIT_DISCREPANCY'); req_table('DEPOSIT_SUSPENSE_OPEN_ITEM'); req_table('DEPOSIT_EXCEPTION_CASE'); req_table('DEPOSIT_EXCEPTION_ASSIGNMENT'); req_table('DEPOSIT_CORRECTION_REQUEST'); req_table('DEPOSIT_CORRECTION_AUTHORIZATION'); req_table('DEPOSIT_CORRECTION_ENTRY'); req_table('DEPOSIT_ROOT_CAUSE_ANALYSIS');
  req_table('CORRESPONDENT_ACCOUNT_EXTENSION'); req_table('CORRESPONDENT_RECONCILIATION_PROFILE');
  req_table('DEPOSIT_REWARD_PROGRAM'); req_table('DEPOSIT_REWARD_ELIGIBILITY_RULE'); req_table('DEPOSIT_REWARD_ENROLLMENT'); req_table('DEPOSIT_LOTTERY_DRAW'); req_table('DEPOSIT_LOTTERY_ENTRY'); req_table('DEPOSIT_LOTTERY_WINNER');
  req_table('DEPOSIT_TRANSACTION'); req_table('DEPOSIT_OPERATION_APPROVAL_REQUEST'); req_table('DEPOSIT_OPERATION_IDEMPOTENCY');

  ensure_seq('SEQ_DEPOSIT_ACCOUNT_FEE_OVERRIDE','DEPOSIT_ACCOUNT_FEE_OVERRIDE','ACCOUNT_FEE_OVERRIDE_ID');
  ensure_seq('SEQ_DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT','DEPOSIT_CUSTOMER_PACKAGE_ENROLLMENT','CUSTOMER_PACKAGE_ENROLLMENT_ID');
  ensure_seq('SEQ_DEPOSIT_TAX_ADJUSTMENT','DEPOSIT_TAX_ADJUSTMENT','TAX_ADJUSTMENT_ID');
  ensure_seq('SEQ_DEPOSIT_LOTTERY_DRAW','DEPOSIT_LOTTERY_DRAW','LOTTERY_DRAW_ID');
  ensure_seq('SEQ_DEPOSIT_LOTTERY_ENTRY','DEPOSIT_LOTTERY_ENTRY','LOTTERY_ENTRY_ID');
  ensure_seq('SEQ_DEPOSIT_LOTTERY_WINNER','DEPOSIT_LOTTERY_WINNER','LOTTERY_WINNER_ID');
END;
/
COMMIT;
PROMPT PHASE11N_STEPS11_17_RAPID_RECONCILIATION_PASS
