SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11M - Wave D Steps 14-17
PROMPT Reconciliation / Exceptions / Correspondent / Rewards
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21260,'Required Wave D table DPS2.'||UPPER(p)||' is missing.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER; BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE'; DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||s||' START WITH '||v_target); RETURN; END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN v_delta:=v_target-v_current; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta); EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||s||' advanced above max='||(v_target-1)); ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||s||' next='||v_current||' max='||(v_target-1)); END IF;
  END;
BEGIN
  req_table('DEPOSIT_RECONCILIATION_RUN'); req_table('DEPOSIT_RECONCILIATION_ITEM'); req_table('DEPOSIT_DISCREPANCY'); req_table('DEPOSIT_SUSPENSE_OPEN_ITEM');
  req_table('DEPOSIT_EXCEPTION_CASE'); req_table('DEPOSIT_EXCEPTION_ASSIGNMENT'); req_table('DEPOSIT_CORRECTION_REQUEST'); req_table('DEPOSIT_CORRECTION_AUTHORIZATION'); req_table('DEPOSIT_CORRECTION_ENTRY'); req_table('DEPOSIT_ROOT_CAUSE_ANALYSIS');
  req_table('CORRESPONDENT_ACCOUNT_EXTENSION'); req_table('CORRESPONDENT_RECONCILIATION_PROFILE');
  req_table('DEPOSIT_REWARD_PROGRAM'); req_table('DEPOSIT_REWARD_ELIGIBILITY_RULE'); req_table('DEPOSIT_REWARD_ENROLLMENT'); req_table('DEPOSIT_LOTTERY_DRAW'); req_table('DEPOSIT_LOTTERY_ENTRY'); req_table('DEPOSIT_LOTTERY_WINNER');
  req_table('DEPOSIT_TRANSACTION'); req_table('DEPOSIT_TRANSACTION_REVERSAL'); req_table('DEPOSIT_SUBLEDGER_ENTRY'); req_table('DEPOSIT_ACCOUNT_BALANCE'); req_table('DEPOSIT_OPERATION_IDEMPOTENCY');
  ensure_seq('SEQ_DEPOSIT_RECONCILIATION_RUN','DEPOSIT_RECONCILIATION_RUN','RECONCILIATION_RUN_ID'); ensure_seq('SEQ_DEPOSIT_RECONCILIATION_ITEM','DEPOSIT_RECONCILIATION_ITEM','RECONCILIATION_ITEM_ID'); ensure_seq('SEQ_DEPOSIT_DISCREPANCY','DEPOSIT_DISCREPANCY','DISCREPANCY_ID'); ensure_seq('SEQ_DEPOSIT_SUSPENSE_OPEN_ITEM','DEPOSIT_SUSPENSE_OPEN_ITEM','SUSPENSE_OPEN_ITEM_ID');
  ensure_seq('SEQ_DEPOSIT_EXCEPTION_CASE','DEPOSIT_EXCEPTION_CASE','EXCEPTION_CASE_ID'); ensure_seq('SEQ_DEPOSIT_EXCEPTION_ASSIGNMENT','DEPOSIT_EXCEPTION_ASSIGNMENT','EXCEPTION_ASSIGNMENT_ID'); ensure_seq('SEQ_DEPOSIT_CORRECTION_REQUEST','DEPOSIT_CORRECTION_REQUEST','CORRECTION_REQUEST_ID'); ensure_seq('SEQ_DEPOSIT_CORRECTION_AUTHORIZATION','DEPOSIT_CORRECTION_AUTHORIZATION','CORRECTION_AUTHORIZATION_ID'); ensure_seq('SEQ_DEPOSIT_CORRECTION_ENTRY','DEPOSIT_CORRECTION_ENTRY','CORRECTION_ENTRY_ID'); ensure_seq('SEQ_DEPOSIT_ROOT_CAUSE_ANALYSIS','DEPOSIT_ROOT_CAUSE_ANALYSIS','ROOT_CAUSE_ANALYSIS_ID');
  ensure_seq('SEQ_CORRESPONDENT_ACCOUNT_EXTENSION','CORRESPONDENT_ACCOUNT_EXTENSION','CORRESPONDENT_ACCOUNT_EXTENSION_ID'); ensure_seq('SEQ_CORRESPONDENT_RECONCILIATION_PROFILE','CORRESPONDENT_RECONCILIATION_PROFILE','CORRESPONDENT_RECON_PROFILE_ID');
  ensure_seq('SEQ_DEPOSIT_REWARD_ENROLLMENT','DEPOSIT_REWARD_ENROLLMENT','REWARD_ENROLLMENT_ID'); ensure_seq('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID');
END;
/
COMMIT;
PROMPT PHASE11M_WAVE_D_RECONCILIATION_PASS
