SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11L - Wave C Steps 09-13
PROMPT Services / Party Access / Compliance / Pricing / Tax
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21250,'Required Wave C table DPS2.'||UPPER(p)||' is missing.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER; BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE'; DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||s||' START WITH '||v_target); RETURN; END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN v_delta:=v_target-v_current; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta); EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy; EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||s||' advanced above max='||(v_target-1)); ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||s||' next='||v_current||' max='||(v_target-1)); END IF;
  END;
BEGIN
  req_table('DEPOSIT_ACCOUNT_INQUIRY'); req_table('DEPOSIT_ACCOUNT_CONFIRMATION'); req_table('DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE'); req_table('DEPOSIT_ACCOUNT_NOTIFICATION_EVENT'); req_table('DEPOSIT_ACCOUNT_API_ACCESS');
  req_table('DEPOSIT_ACCOUNT_SIGNATURE_RULE'); req_table('DEPOSIT_ACCOUNT_DELEGATION'); req_table('DEPOSIT_ACCOUNT_AUTHORIZED_USER'); req_table('DEPOSIT_ACCOUNT_BENEFICIARY'); req_table('DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT');
  req_table('DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION'); req_table('DEPOSIT_REGULATORY_RULE'); req_table('DEPOSIT_COMPLIANCE_EVALUATION');
  req_table('DEPOSIT_ACCOUNT_PRICING_OVERRIDE'); req_table('DEPOSIT_FEE_ASSESSMENT'); req_table('DEPOSIT_PROFITABILITY_SNAPSHOT');
  req_table('DEPOSIT_TAX_EXEMPTION'); req_table('DEPOSIT_TAX_RULE'); req_table('DEPOSIT_TAX_CALCULATION'); req_table('DEPOSIT_TAX_CERTIFICATE');
  req_table('DEPOSIT_OPERATION_APPROVAL_REQUEST'); req_table('DEPOSIT_OPERATION_IDEMPOTENCY');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_INQUIRY','DEPOSIT_ACCOUNT_INQUIRY','ACCOUNT_INQUIRY_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_CONFIRMATION','DEPOSIT_ACCOUNT_CONFIRMATION','ACCOUNT_CONFIRMATION_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','NOTIFICATION_PREFERENCE_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','NOTIFICATION_EVENT_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_API_ACCESS','DEPOSIT_ACCOUNT_API_ACCESS','ACCOUNT_API_ACCESS_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_SIGNATURE_RULE','DEPOSIT_ACCOUNT_SIGNATURE_RULE','ACCOUNT_SIGNATURE_RULE_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_DELEGATION','DEPOSIT_ACCOUNT_DELEGATION','ACCOUNT_DELEGATION_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_AUTHORIZED_USER','DEPOSIT_ACCOUNT_AUTHORIZED_USER','ACCOUNT_AUTHORIZED_USER_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_BENEFICIARY','DEPOSIT_ACCOUNT_BENEFICIARY','ACCOUNT_BENEFICIARY_ID'); ensure_seq('SEQ_DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','ACCOUNT_PAYMENT_INSTRUMENT_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION','DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION','ACCOUNT_REG_RESTRICTION_ID'); ensure_seq('SEQ_DEPOSIT_COMPLIANCE_EVALUATION','DEPOSIT_COMPLIANCE_EVALUATION','COMPLIANCE_EVALUATION_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_PRICING_OVERRIDE','DEPOSIT_ACCOUNT_PRICING_OVERRIDE','ACCOUNT_PRICING_OVERRIDE_ID'); ensure_seq('SEQ_DEPOSIT_TAX_EXEMPTION','DEPOSIT_TAX_EXEMPTION','TAX_EXEMPTION_ID'); ensure_seq('SEQ_DEPOSIT_TAX_CALCULATION','DEPOSIT_TAX_CALCULATION','TAX_CALCULATION_ID'); ensure_seq('SEQ_DEPOSIT_TAX_CERTIFICATE','DEPOSIT_TAX_CERTIFICATE','TAX_CERTIFICATE_ID');
  ensure_seq('SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST','DEPOSIT_OPERATION_APPROVAL_REQUEST','APPROVAL_REQUEST_ID'); ensure_seq('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID');
END;
/
COMMIT;
PROMPT PHASE11L_WAVE_C_RECONCILIATION_PASS
