SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
PROMPT ============================================================
PROMPT DPS2 Phase 11H - Step 04 Canonical Profit Completion
PROMPT Profile / Period / Accrual Detail / Adjustment / Payment
PROMPT ============================================================

DECLARE
  FUNCTION table_exists(p_name VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM all_tables WHERE owner='DPS2' AND table_name=UPPER(p_name); RETURN n>0; END;
  FUNCTION seq_exists(p_name VARCHAR2) RETURN BOOLEAN IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM all_sequences WHERE sequence_owner='DPS2' AND sequence_name=UPPER(p_name); RETURN n>0; END;
  PROCEDURE ddl(p_sql CLOB) IS BEGIN EXECUTE IMMEDIATE p_sql; END;
  PROCEDURE ensure_seq(p_name VARCHAR2,p_table VARCHAR2,p_pk VARCHAR2) IS
    v_start NUMBER:=1;
  BEGIN
    IF NOT seq_exists(p_name) THEN
      IF table_exists(p_table) THEN
        EXECUTE IMMEDIATE 'SELECT NVL(MAX('||p_pk||'),0)+1 FROM DPS2.'||p_table INTO v_start;
      END IF;
      ddl('CREATE SEQUENCE DPS2.'||p_name||' START WITH '||TO_CHAR(v_start)||' INCREMENT BY 1 NOCACHE');
      DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||p_name||' START='||v_start);
    ELSE
      DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||p_name);
    END IF;
  END;
BEGIN
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_PROFIT_PROFILE','DEPOSIT_ACCOUNT_PROFIT_PROFILE','ACCOUNT_PROFIT_PROFILE_ID');
  ensure_seq('SEQ_DEPOSIT_PROFIT_PERIOD','DEPOSIT_PROFIT_PERIOD','PROFIT_PERIOD_ID');
  ensure_seq('SEQ_DEPOSIT_PROFIT_ACCRUAL_DETAIL','DEPOSIT_PROFIT_ACCRUAL_DETAIL','PROFIT_ACCRUAL_DETAIL_ID');
  ensure_seq('SEQ_DEPOSIT_PROFIT_ADJUSTMENT','DEPOSIT_PROFIT_ADJUSTMENT','PROFIT_ADJUSTMENT_ID');
  ensure_seq('SEQ_DEPOSIT_PROFIT_PAYMENT','DEPOSIT_PROFIT_PAYMENT','PROFIT_PAYMENT_ID');

  IF NOT table_exists('DEPOSIT_ACCOUNT_PROFIT_PROFILE') THEN
    ddl(q'~CREATE TABLE DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE(
      ACCOUNT_PROFIT_PROFILE_ID NUMBER(19) DEFAULT DPS2.SEQ_DEPOSIT_ACCOUNT_PROFIT_PROFILE.NEXTVAL NOT NULL,
      ACCOUNT_ID NUMBER(19) NOT NULL, PRODUCT_PRICING_RULE_ID NUMBER(19), PRODUCT_PRICING_COMPONENT_ID NUMBER(19), PRODUCT_RATE_TIER_ID NUMBER(19), PROFIT_PAYMENT_RULE_ID NUMBER(19),
      RATE_VALUE NUMBER(12,6) NOT NULL, CALCULATION_METHOD_CODE VARCHAR2(30 CHAR) NOT NULL, DAY_COUNT_BASIS_CODE VARCHAR2(20 CHAR) NOT NULL,
      ACCRUAL_FREQUENCY_CODE VARCHAR2(20 CHAR) NOT NULL, PAYMENT_FREQUENCY_CODE VARCHAR2(20 CHAR) NOT NULL, PAYMENT_DAY_RULE_CODE VARCHAR2(30 CHAR), PAYMENT_DAY_NO NUMBER(2),
      FIRST_PAYMENT_RULE_CODE VARCHAR2(40 CHAR), HOLIDAY_ADJUSTMENT_CODE VARCHAR2(40 CHAR), PAYMENT_DESTINATION_CODE VARCHAR2(30 CHAR) NOT NULL,
      DESTINATION_ACCOUNT_ID NUMBER(19), DESTINATION_SELECTED_BY_CUSTOMER NUMBER(1), DESTINATION_ACCOUNT_REFERENCE VARCHAR2(80 CHAR),
      VALID_FROM DATE NOT NULL, VALID_TO DATE, STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL, SOURCE_OPENING_PROFIT_INST_ID NUMBER(19),
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEPOSIT_ACCOUNT_PROFIT_PROFILE PRIMARY KEY(ACCOUNT_PROFIT_PROFILE_ID),
      CONSTRAINT FK_DEP_ACC_PROFIT_PROFILE_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID),
      CONSTRAINT CK_DEP_ACC_PROFIT_PROFILE_RATE CHECK(RATE_VALUE>=0), CONSTRAINT CK_DEP_ACC_PROFIT_PROFILE_STATUS CHECK(STATUS_CODE IN ('ACTIVE','INACTIVE')),
      CONSTRAINT CK_DEP_ACC_PROFIT_PROFILE_DATES CHECK(VALID_TO IS NULL OR VALID_TO>=VALID_FROM),
      CONSTRAINT UK_DEP_ACC_PROFIT_PROFILE_SOURCE UNIQUE(SOURCE_OPENING_PROFIT_INST_ID))~');
    DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE');
  ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE'); END IF;

  IF NOT table_exists('DEPOSIT_PROFIT_PERIOD') THEN
    ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_PERIOD(
      PROFIT_PERIOD_ID NUMBER(19) DEFAULT DPS2.SEQ_DEPOSIT_PROFIT_PERIOD.NEXTVAL NOT NULL, ACCOUNT_PROFIT_PROFILE_ID NUMBER(19) NOT NULL,
      PERIOD_START_DATE DATE NOT NULL, PERIOD_END_DATE DATE NOT NULL, PERIOD_STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
      TOTAL_ACCRUED_AMOUNT NUMBER(20,4) DEFAULT 0 NOT NULL, TOTAL_ADJUSTMENT_AMOUNT NUMBER(20,4) DEFAULT 0 NOT NULL,
      PAYABLE_AMOUNT NUMBER(20,4) DEFAULT 0 NOT NULL, PAID_AMOUNT NUMBER(20,4) DEFAULT 0 NOT NULL,
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEPOSIT_PROFIT_PERIOD PRIMARY KEY(PROFIT_PERIOD_ID),
      CONSTRAINT FK_DEP_PROFIT_PERIOD_PROFILE FOREIGN KEY(ACCOUNT_PROFIT_PROFILE_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE(ACCOUNT_PROFIT_PROFILE_ID),
      CONSTRAINT CK_DEP_PROFIT_PERIOD_DATES CHECK(PERIOD_END_DATE>=PERIOD_START_DATE),
      CONSTRAINT CK_DEP_PROFIT_PERIOD_STATUS CHECK(PERIOD_STATUS_CODE IN ('OPEN','CALCULATED','APPROVED','PAID','CLOSED')),
      CONSTRAINT UK_DEP_PROFIT_PERIOD_RANGE UNIQUE(ACCOUNT_PROFIT_PROFILE_ID,PERIOD_START_DATE,PERIOD_END_DATE))~');
    DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.DEPOSIT_PROFIT_PERIOD');
  ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.DEPOSIT_PROFIT_PERIOD'); END IF;

  IF NOT table_exists('DEPOSIT_PROFIT_ACCRUAL_DETAIL') THEN
    ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL(
      PROFIT_ACCRUAL_DETAIL_ID NUMBER(19) DEFAULT DPS2.SEQ_DEPOSIT_PROFIT_ACCRUAL_DETAIL.NEXTVAL NOT NULL, PROFIT_ACCRUAL_ID NUMBER(19) NOT NULL,
      COMPONENT_CODE VARCHAR2(50 CHAR) NOT NULL, BASIS_AMOUNT NUMBER(20,4) NOT NULL, RATE_VALUE NUMBER(12,6) NOT NULL, ACCRUAL_AMOUNT NUMBER(20,4) NOT NULL,
      CALCULATION_NOTE VARCHAR2(1000 CHAR), CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
      UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEPOSIT_PROFIT_ACCRUAL_DETAIL PRIMARY KEY(PROFIT_ACCRUAL_DETAIL_ID),
      CONSTRAINT FK_DEP_PROFIT_ACCR_DETAIL_ACC FOREIGN KEY(PROFIT_ACCRUAL_ID) REFERENCES DPS2.DEPOSIT_PROFIT_ACCRUAL(PROFIT_ACCRUAL_ID),
      CONSTRAINT CK_DEP_PROFIT_ACCR_DETAIL_AMT CHECK(BASIS_AMOUNT>=0 AND RATE_VALUE>=0 AND ACCRUAL_AMOUNT>=0))~');
    DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL');
  ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL'); END IF;

  IF NOT table_exists('DEPOSIT_PROFIT_PAYMENT') THEN
    ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_PAYMENT(
      PROFIT_PAYMENT_ID NUMBER(19) DEFAULT DPS2.SEQ_DEPOSIT_PROFIT_PAYMENT.NEXTVAL NOT NULL, PROFIT_PERIOD_ID NUMBER(19) NOT NULL, ACCOUNT_ID NUMBER(19) NOT NULL,
      PAYMENT_DUE_DATE DATE NOT NULL, PAYMENT_DATE DATE, PAYMENT_AMOUNT NUMBER(20,4) NOT NULL, PAYMENT_DESTINATION_CODE VARCHAR2(30 CHAR) NOT NULL,
      DESTINATION_ACCOUNT_REFERENCE VARCHAR2(80 CHAR), PAYMENT_STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'DUE' NOT NULL, POSTING_REFERENCE VARCHAR2(80 CHAR), ATTEMPT_NO NUMBER(5) DEFAULT 1 NOT NULL,
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEPOSIT_PROFIT_PAYMENT PRIMARY KEY(PROFIT_PAYMENT_ID), CONSTRAINT FK_DEP_PROFIT_PAYMENT_PERIOD FOREIGN KEY(PROFIT_PERIOD_ID) REFERENCES DPS2.DEPOSIT_PROFIT_PERIOD(PROFIT_PERIOD_ID),
      CONSTRAINT FK_DEP_PROFIT_PAYMENT_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID), CONSTRAINT CK_DEP_PROFIT_PAYMENT_AMT CHECK(PAYMENT_AMOUNT>=0),
      CONSTRAINT CK_DEP_PROFIT_PAYMENT_STATUS CHECK(PAYMENT_STATUS_CODE IN ('DUE','PROCESSING','PAID','FAILED','REVERSED')), CONSTRAINT CK_DEP_PROFIT_PAYMENT_ATTEMPT CHECK(ATTEMPT_NO>=1))~');
    DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.DEPOSIT_PROFIT_PAYMENT');
  ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.DEPOSIT_PROFIT_PAYMENT'); END IF;

  IF NOT table_exists('DEPOSIT_PROFIT_ADJUSTMENT') THEN
    ddl(q'~CREATE TABLE DPS2.DEPOSIT_PROFIT_ADJUSTMENT(
      PROFIT_ADJUSTMENT_ID NUMBER(19) DEFAULT DPS2.SEQ_DEPOSIT_PROFIT_ADJUSTMENT.NEXTVAL NOT NULL, ACCOUNT_ID NUMBER(19) NOT NULL, PROFIT_PERIOD_ID NUMBER(19) NOT NULL,
      ORIGINAL_ACCRUAL_ID NUMBER(19), ORIGINAL_PAYMENT_ID NUMBER(19), ADJUSTMENT_TYPE_CODE VARCHAR2(20 CHAR) NOT NULL, ADJUSTMENT_AMOUNT NUMBER(20,4) NOT NULL,
      REASON_CODE VARCHAR2(50 CHAR) NOT NULL, ADJUSTMENT_STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL, APPROVAL_REQUEST_ID NUMBER(19), POSTING_REFERENCE VARCHAR2(80 CHAR),
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(100 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6), UPDATED_BY VARCHAR2(100 CHAR), RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_DEPOSIT_PROFIT_ADJUSTMENT PRIMARY KEY(PROFIT_ADJUSTMENT_ID), CONSTRAINT FK_DEP_PROFIT_ADJ_ACC FOREIGN KEY(ACCOUNT_ID) REFERENCES DPS2.DEPOSIT_ACCOUNT(ACCOUNT_ID),
      CONSTRAINT FK_DEP_PROFIT_ADJ_PERIOD FOREIGN KEY(PROFIT_PERIOD_ID) REFERENCES DPS2.DEPOSIT_PROFIT_PERIOD(PROFIT_PERIOD_ID),
      CONSTRAINT FK_DEP_PROFIT_ADJ_ACCR FOREIGN KEY(ORIGINAL_ACCRUAL_ID) REFERENCES DPS2.DEPOSIT_PROFIT_ACCRUAL(PROFIT_ACCRUAL_ID),
      CONSTRAINT FK_DEP_PROFIT_ADJ_PAY FOREIGN KEY(ORIGINAL_PAYMENT_ID) REFERENCES DPS2.DEPOSIT_PROFIT_PAYMENT(PROFIT_PAYMENT_ID),
      CONSTRAINT FK_DEP_PROFIT_ADJ_APPROVAL FOREIGN KEY(APPROVAL_REQUEST_ID) REFERENCES DPS2.DEPOSIT_OPERATION_APPROVAL_REQUEST(APPROVAL_REQUEST_ID),
      CONSTRAINT CK_DEP_PROFIT_ADJ_SOURCE CHECK(ORIGINAL_ACCRUAL_ID IS NOT NULL OR ORIGINAL_PAYMENT_ID IS NOT NULL), CONSTRAINT CK_DEP_PROFIT_ADJ_AMT CHECK(ADJUSTMENT_AMOUNT>0),
      CONSTRAINT CK_DEP_PROFIT_ADJ_TYPE CHECK(ADJUSTMENT_TYPE_CODE IN ('INCREASE','DECREASE','REVERSAL')), CONSTRAINT CK_DEP_PROFIT_ADJ_STATUS CHECK(ADJUSTMENT_STATUS_CODE IN ('DRAFT','APPROVED','POSTED','REJECTED')))~');
    DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.DEPOSIT_PROFIT_ADJUSTMENT');
  ELSE DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.DEPOSIT_PROFIT_ADJUSTMENT'); END IF;
END;
/

PROMPT [11H] Backfilling canonical Profit Profile from governed Opening snapshot ...
INSERT INTO DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE(
  ACCOUNT_PROFIT_PROFILE_ID,ACCOUNT_ID,PRODUCT_PRICING_RULE_ID,PRODUCT_PRICING_COMPONENT_ID,PRODUCT_RATE_TIER_ID,PROFIT_PAYMENT_RULE_ID,
  RATE_VALUE,CALCULATION_METHOD_CODE,DAY_COUNT_BASIS_CODE,ACCRUAL_FREQUENCY_CODE,PAYMENT_FREQUENCY_CODE,PAYMENT_DAY_RULE_CODE,FIRST_PAYMENT_RULE_CODE,
  HOLIDAY_ADJUSTMENT_CODE,PAYMENT_DESTINATION_CODE,DESTINATION_ACCOUNT_ID,DESTINATION_SELECTED_BY_CUSTOMER,DESTINATION_ACCOUNT_REFERENCE,
  VALID_FROM,VALID_TO,STATUS_CODE,SOURCE_OPENING_PROFIT_INST_ID,CREATED_AT,CREATED_BY,RECORD_VERSION)
SELECT DPS2.SEQ_DEPOSIT_ACCOUNT_PROFIT_PROFILE.NEXTVAL,C.ACCOUNT_ID,C.PRICING_RULE_ID,C.PRICING_COMPONENT_ID,C.RATE_TIER_ID,C.PROFIT_PAYMENT_RULE_ID,
       C.ANNUAL_RATE,C.CALCULATION_METHOD_CODE,C.DAY_COUNT_BASIS_CODE,C.ACCRUAL_FREQUENCY_CODE,C.PAYMENT_FREQUENCY_CODE,C.PAYMENT_DAY_RULE_CODE,C.FIRST_PAYMENT_RULE_CODE,
       C.HOLIDAY_ADJUSTMENT_CODE,C.PAYMENT_DESTINATION_CODE,O.DESTINATION_ACCOUNT_ID,O.DESTINATION_SELECTED_BY_CUSTOMER,C.DESTINATION_ACCOUNT_REFERENCE,
       C.EFFECTIVE_FROM,C.EFFECTIVE_TO,'ACTIVE',C.SOURCE_OPENING_PROFIT_INSTRUCTION_ID,SYSTIMESTAMP,'phase11h.migration',1
  FROM DPS2.DEPOSIT_PROFIT_CONTRACT C
  JOIN DPS2.DEPOSIT_OPENING_PROFIT_INSTRUCTION O ON O.OPENING_PROFIT_INSTRUCTION_ID=C.SOURCE_OPENING_PROFIT_INSTRUCTION_ID
 WHERE C.STATUS_CODE='ACTIVE'
   AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE P WHERE P.SOURCE_OPENING_PROFIT_INST_ID=C.SOURCE_OPENING_PROFIT_INSTRUCTION_ID);

PROMPT [11H] Backfilling MATURITY Profit Period ...
INSERT INTO DPS2.DEPOSIT_PROFIT_PERIOD(
  PROFIT_PERIOD_ID,ACCOUNT_PROFIT_PROFILE_ID,PERIOD_START_DATE,PERIOD_END_DATE,PERIOD_STATUS_CODE,TOTAL_ACCRUED_AMOUNT,TOTAL_ADJUSTMENT_AMOUNT,PAYABLE_AMOUNT,PAID_AMOUNT,CREATED_AT,CREATED_BY,RECORD_VERSION)
SELECT DPS2.SEQ_DEPOSIT_PROFIT_PERIOD.NEXTVAL,P.ACCOUNT_PROFIT_PROFILE_ID,C.EFFECTIVE_FROM,C.EFFECTIVE_TO,'OPEN',0,0,0,0,SYSTIMESTAMP,'phase11h.migration',1
  FROM DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE P
  JOIN DPS2.DEPOSIT_PROFIT_CONTRACT C ON C.ACCOUNT_ID=P.ACCOUNT_ID AND C.STATUS_CODE='ACTIVE'
 WHERE P.STATUS_CODE='ACTIVE' AND P.PAYMENT_FREQUENCY_CODE='MATURITY' AND C.EFFECTIVE_TO IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PERIOD X WHERE X.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID AND X.PERIOD_START_DATE=C.EFFECTIVE_FROM AND X.PERIOD_END_DATE=C.EFFECTIVE_TO);

PROMPT [11H] Mapping canonical accruals to Profit Period ...
UPDATE DPS2.DEPOSIT_PROFIT_ACCRUAL A
   SET A.PROFIT_PERIOD_ID=(SELECT MAX(P.PROFIT_PERIOD_ID)
      FROM DPS2.DEPOSIT_PROFIT_PERIOD P
      JOIN DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE F ON F.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID
     WHERE F.ACCOUNT_ID=A.ACCOUNT_ID AND A.ACCRUAL_TO_DATE BETWEEN P.PERIOD_START_DATE AND P.PERIOD_END_DATE)
 WHERE A.PROFIT_PERIOD_ID IS NULL
   AND EXISTS (SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PERIOD P JOIN DPS2.DEPOSIT_ACCOUNT_PROFIT_PROFILE F ON F.ACCOUNT_PROFIT_PROFILE_ID=P.ACCOUNT_PROFIT_PROFILE_ID WHERE F.ACCOUNT_ID=A.ACCOUNT_ID AND A.ACCRUAL_TO_DATE BETWEEN P.PERIOD_START_DATE AND P.PERIOD_END_DATE);

PROMPT [11H] Backfilling Accrual Detail evidence ...
INSERT INTO DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL(PROFIT_ACCRUAL_DETAIL_ID,PROFIT_ACCRUAL_ID,COMPONENT_CODE,BASIS_AMOUNT,RATE_VALUE,ACCRUAL_AMOUNT,CALCULATION_NOTE,CREATED_AT,CREATED_BY,RECORD_VERSION)
SELECT DPS2.SEQ_DEPOSIT_PROFIT_ACCRUAL_DETAIL.NEXTVAL,A.PROFIT_ACCRUAL_ID,'BASE_PROFIT',A.BASIS_AMOUNT,A.ANNUAL_RATE,A.ACCRUED_AMOUNT,
       'Backfilled from canonical 11G accrual',SYSTIMESTAMP,'phase11h.migration',1
  FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A
 WHERE A.PROFIT_PERIOD_ID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_PROFIT_ACCRUAL_DETAIL D WHERE D.PROFIT_ACCRUAL_ID=A.PROFIT_ACCRUAL_ID);

PROMPT [11H] Backfilling Payment evidence for existing 11G postings ...
INSERT INTO DPS2.DEPOSIT_PROFIT_PAYMENT(PROFIT_PAYMENT_ID,PROFIT_PERIOD_ID,ACCOUNT_ID,PAYMENT_DUE_DATE,PAYMENT_DATE,PAYMENT_AMOUNT,PAYMENT_DESTINATION_CODE,DESTINATION_ACCOUNT_REFERENCE,PAYMENT_STATUS_CODE,POSTING_REFERENCE,ATTEMPT_NO,CREATED_AT,CREATED_BY,RECORD_VERSION)
SELECT DPS2.SEQ_DEPOSIT_PROFIT_PAYMENT.NEXTVAL,
       (SELECT MAX(A.PROFIT_PERIOD_ID) FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_POSTING_ID=G.PROFIT_POSTING_ID),
       G.ACCOUNT_ID,G.POSTING_DATE,G.POSTING_DATE,G.AMOUNT,G.DESTINATION_CODE,G.DESTINATION_ACCOUNT_REFERENCE,'PAID','P11G-PROFIT-'||G.PROFIT_POSTING_ID,1,SYSTIMESTAMP,'phase11h.migration',1
  FROM DPS2.DEPOSIT_PROFIT_POSTING G
 WHERE EXISTS (SELECT 1 FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_POSTING_ID=G.PROFIT_POSTING_ID AND A.PROFIT_PERIOD_ID IS NOT NULL)
   AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_PROFIT_PAYMENT P WHERE P.ACCOUNT_ID=G.ACCOUNT_ID AND P.PAYMENT_STATUS_CODE='PAID' AND P.PAYMENT_AMOUNT=G.AMOUNT AND P.PAYMENT_DATE=G.POSTING_DATE AND P.POSTING_REFERENCE IN ('P11G-PROFIT-'||G.PROFIT_POSTING_ID,'P11H-PROFIT-'||G.PROFIT_POSTING_ID));

PROMPT [11H] Recomputing Profit Period totals ...
MERGE INTO DPS2.DEPOSIT_PROFIT_PERIOD P
USING (
  SELECT P0.PROFIT_PERIOD_ID,
         NVL((SELECT SUM(A.ACCRUED_AMOUNT) FROM DPS2.DEPOSIT_PROFIT_ACCRUAL A WHERE A.PROFIT_PERIOD_ID=P0.PROFIT_PERIOD_ID),0) AS ACCRUED,
         NVL((SELECT SUM(CASE J.ADJUSTMENT_TYPE_CODE WHEN 'INCREASE' THEN J.ADJUSTMENT_AMOUNT ELSE -J.ADJUSTMENT_AMOUNT END) FROM DPS2.DEPOSIT_PROFIT_ADJUSTMENT J WHERE J.PROFIT_PERIOD_ID=P0.PROFIT_PERIOD_ID AND J.ADJUSTMENT_STATUS_CODE='POSTED'),0) AS ADJUSTED,
         NVL((SELECT SUM(X.PAYMENT_AMOUNT) FROM DPS2.DEPOSIT_PROFIT_PAYMENT X WHERE X.PROFIT_PERIOD_ID=P0.PROFIT_PERIOD_ID AND X.PAYMENT_STATUS_CODE='PAID'),0) AS PAID
    FROM DPS2.DEPOSIT_PROFIT_PERIOD P0
) S ON (S.PROFIT_PERIOD_ID=P.PROFIT_PERIOD_ID)
WHEN MATCHED THEN UPDATE SET
  P.TOTAL_ACCRUED_AMOUNT=S.ACCRUED,
  P.TOTAL_ADJUSTMENT_AMOUNT=S.ADJUSTED,
  P.PAYABLE_AMOUNT=GREATEST(S.ACCRUED+S.ADJUSTED,0),
  P.PAID_AMOUNT=S.PAID,
  P.PERIOD_STATUS_CODE=CASE WHEN S.ACCRUED+S.ADJUSTED>0 AND S.PAID>=S.ACCRUED+S.ADJUSTED THEN 'PAID' WHEN S.ACCRUED>0 THEN 'CALCULATED' ELSE 'OPEN' END,
  P.UPDATED_AT=SYSTIMESTAMP,P.UPDATED_BY='phase11h.migration',P.RECORD_VERSION=P.RECORD_VERSION+1;

COMMIT;
PROMPT [11H] Reconciling reopened payable Profit Period status ...
UPDATE DPS2.DEPOSIT_PROFIT_PERIOD
   SET PERIOD_STATUS_CODE='CALCULATED',
       UPDATED_AT=SYSTIMESTAMP,
       UPDATED_BY='PHASE11H_RECONCILE',
       RECORD_VERSION=RECORD_VERSION+1
 WHERE PERIOD_STATUS_CODE='PAID'
   AND PAYABLE_AMOUNT>PAID_AMOUNT;

COMMIT;

PROMPT ============================================================
PROMPT PHASE11H_STEP04_CANONICAL_PROFIT_RECONCILIATION_PASS
PROMPT ============================================================
