WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
PROMPT ============================================================
PROMPT DPS2 Phase 11N-D - Steps 05-10 Canonical Audit
PROMPT Scope: Steps 05-10 only; no business DML; Step09-10 sequence reconciliation
PROMPT ============================================================
DECLARE
  v NUMBER;
  FUNCTION seq_exists(p_seq VARCHAR2) RETURN BOOLEAN IS n NUMBER;
  BEGIN SELECT COUNT(*) INTO n FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p_seq); RETURN n>0; END;
  PROCEDURE req_table(p_table VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table);
    IF v=0 THEN RAISE_APPLICATION_ERROR(-20431,'Missing DPS2 table: '||p_table); END IF;
  END;
  PROCEDURE req_col(p_table VARCHAR2,p_col VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_col);
    IF v=0 THEN RAISE_APPLICATION_ERROR(-20432,'Missing DPS2 column: '||p_table||'.'||p_col); END IF;
  END;
  PROCEDURE ensure_seq(p_seq VARCHAR2,p_table VARCHAR2,p_pk VARCHAR2) IS
    v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||p_pk||'),0)+1 FROM DPS2.'||p_table INTO v_target;
    IF NOT seq_exists(p_seq) THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||p_seq||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE';
      DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||p_seq||' START WITH '||v_target);
      RETURN;
    END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||p_seq||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN
      v_delta:=v_target-v_current;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||p_seq||' INCREMENT BY '||TO_CHAR(v_delta);
      BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||p_seq||'.NEXTVAL FROM DUAL' INTO v_dummy;
      EXCEPTION WHEN OTHERS THEN BEGIN EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||p_seq||' INCREMENT BY 1'; EXCEPTION WHEN OTHERS THEN NULL; END; RAISE; END;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||p_seq||' INCREMENT BY 1';
      DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||p_seq||' advanced above MAX('||p_table||'.'||p_pk||')='||(v_target-1));
    ELSE
      DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||p_seq||' next='||v_current||' max='||(v_target-1));
    END IF;
  END;
BEGIN
  -- Step 05
  req_table('DEPOSIT_TRANSACTION'); req_table('DEPOSIT_TRANSACTION_VALIDATION'); req_table('DEPOSIT_TRANSACTION_AUTHORIZATION');
  req_table('DEPOSIT_TRANSACTION_STATUS_HISTORY'); req_table('DEPOSIT_TRANSACTION_LEG'); req_table('DEPOSIT_TRANSACTION_REVERSAL');
  req_table('DEPOSIT_SUBLEDGER_ENTRY'); req_table('DEPOSIT_ACCOUNT_BALANCE');
  -- Step 06
  req_table('DEPOSIT_STATEMENT_TEMPLATE'); req_table('DEPOSIT_STATEMENT_REQUEST'); req_table('DEPOSIT_STATEMENT');
  req_table('DEPOSIT_STATEMENT_ITEM'); req_table('DEPOSIT_STATEMENT_DELIVERY');
  -- Step 07
  req_table('DEPOSIT_ACCOUNT_LIMIT'); req_table('DEPOSIT_ACCOUNT_LIMIT_USAGE'); req_table('DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION');
  -- Step 08
  req_table('DEPOSIT_ACCOUNT_CLOSURE'); req_table('DEPOSIT_ACCOUNT_CLOSURE_CHECK'); req_table('DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM');
  req_table('DEPOSIT_ACCOUNT_REOPENING'); req_table('DEPOSIT_MATURITY_PROCESS_RUN'); req_table('DEPOSIT_MATURITY_PROCESS_ITEM'); req_table('DEPOSIT_MATURITY_EVENT');
  -- Step 09 only
  req_table('DEPOSIT_ACCOUNT_INQUIRY'); req_table('DEPOSIT_ACCOUNT_CONFIRMATION'); req_table('DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE');
  req_table('DEPOSIT_ACCOUNT_NOTIFICATION_EVENT'); req_table('DEPOSIT_ACCOUNT_API_ACCESS');
  -- Step 10 only
  req_table('DEPOSIT_ACCOUNT_SIGNATURE_RULE'); req_table('DEPOSIT_ACCOUNT_DELEGATION'); req_table('DEPOSIT_ACCOUNT_AUTHORIZED_USER');
  req_table('DEPOSIT_ACCOUNT_BENEFICIARY'); req_table('DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT');

  req_col('DEPOSIT_ACCOUNT_CLOSURE_SETTLEMENT_ITEM','TRANSACTION_ID');
  req_col('DEPOSIT_ACCOUNT_CLOSURE','SETTLEMENT_TRANSACTION_REFERENCE');
  req_col('DEPOSIT_ACCOUNT_STATUS_HISTORY','APPROVAL_REQUEST_ID');
  req_col('DEPOSIT_TRANSACTION','TRANSACTION_TYPE_CODE');
  req_col('DEPOSIT_TRANSACTION_LEG','POSTING_REFERENCE');
  req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_ID');
  req_col('DEPOSIT_SUBLEDGER_ENTRY','TRANSACTION_LEG_ID');

  -- Reconcile only Step 09-10 sequences here. Steps 05-08 remain owned by their closed 11I/11K migrations.
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_INQUIRY','DEPOSIT_ACCOUNT_INQUIRY','ACCOUNT_INQUIRY_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_CONFIRMATION','DEPOSIT_ACCOUNT_CONFIRMATION','ACCOUNT_CONFIRMATION_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE','NOTIFICATION_PREFERENCE_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','DEPOSIT_ACCOUNT_NOTIFICATION_EVENT','NOTIFICATION_EVENT_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_API_ACCESS','DEPOSIT_ACCOUNT_API_ACCESS','ACCOUNT_API_ACCESS_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_SIGNATURE_RULE','DEPOSIT_ACCOUNT_SIGNATURE_RULE','ACCOUNT_SIGNATURE_RULE_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_DELEGATION','DEPOSIT_ACCOUNT_DELEGATION','ACCOUNT_DELEGATION_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_AUTHORIZED_USER','DEPOSIT_ACCOUNT_AUTHORIZED_USER','ACCOUNT_AUTHORIZED_USER_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_BENEFICIARY','DEPOSIT_ACCOUNT_BENEFICIARY','ACCOUNT_BENEFICIARY_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT','ACCOUNT_PAYMENT_INSTRUMENT_ID');

  DBMS_OUTPUT.PUT_LINE('KEEP   | Canonical Steps 05-10 scope preserved; Steps 11-13 are not touched by 11N-D');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11ND_SCHEMA_RECONCILIATION_PASS
PROMPT ============================================================
