-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11J - Wave A Servicing & Lifecycle Completion (Operational Steps 01-02)
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11J - Wave A Servicing + Lifecycle Completion
PROMPT Steps 01-02 / existing canonical tables / sequence reconciliation
PROMPT ============================================================
DECLARE
  FUNCTION table_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p); RETURN v>0; END;
  FUNCTION sequence_exists(p VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='DPS2' AND SEQUENCE_NAME=UPPER(p); RETURN v>0; END;
  PROCEDURE req_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21210,'Required Wave A table DPS2.'||UPPER(p)||' is missing.'); END IF; DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(p)); END;
  PROCEDURE ensure_seq(s VARCHAR2,t VARCHAR2,pk VARCHAR2) IS
    v_target NUMBER; v_current NUMBER; v_delta NUMBER; v_dummy NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('||pk||'),0)+1 FROM DPS2.'||t INTO v_target;
    IF NOT sequence_exists(s) THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE DPS2.'||s||' START WITH '||TO_CHAR(v_target)||' INCREMENT BY 1 NOCACHE NOCYCLE';
      DBMS_OUTPUT.PUT_LINE('CREATE | DPS2.'||UPPER(s)||' START WITH '||v_target);
      RETURN;
    END IF;
    EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_current;
    IF v_current < v_target THEN
      v_delta:=v_target-v_current;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY '||TO_CHAR(v_delta);
      BEGIN EXECUTE IMMEDIATE 'SELECT DPS2.'||s||'.NEXTVAL FROM DUAL' INTO v_dummy;
      EXCEPTION WHEN OTHERS THEN
        BEGIN EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1'; EXCEPTION WHEN OTHERS THEN NULL; END;
        RAISE;
      END;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE DPS2.'||s||' INCREMENT BY 1';
      DBMS_OUTPUT.PUT_LINE('REPAIR | DPS2.'||UPPER(s)||' advanced above MAX('||UPPER(t)||'.'||UPPER(pk)||')='||(v_target-1));
    ELSE
      DBMS_OUTPUT.PUT_LINE('KEEP   | DPS2.'||UPPER(s)||' next='||v_current||' max='||(v_target-1));
    END IF;
  END;
BEGIN
  req_table('DEPOSIT_ACCOUNT_ATTRIBUTE');
  req_table('DEPOSIT_ACCOUNT_CONDITION_OVERRIDE');
  req_table('DEPOSIT_ACCOUNT_PRODUCT_HISTORY');
  req_table('DEPOSIT_ACCOUNT_PARTY');
  req_table('DEPOSIT_ACCOUNT_SIGNATORY');
  req_table('DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY');
  req_table('DEPOSIT_OPERATION_APPROVAL_REQUEST');
  req_table('DEPOSIT_ACTIVATION_RUN');
  req_table('DEPOSIT_ACTIVATION_CHECK');
  req_table('DEPOSIT_ACCOUNT_BULK_ACTION');
  req_table('DEPOSIT_ACCOUNT_BULK_ACTION_ITEM');
  req_table('DEPOSIT_ACCOUNT_SERVICING_HISTORY');
  req_table('DEPOSIT_OPERATION_IDEMPOTENCY');

  ensure_seq('SEQ_DEPOSIT_ACCOUNT_ATTRIBUTE','DEPOSIT_ACCOUNT_ATTRIBUTE','ACCOUNT_ATTRIBUTE_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_CONDITION_OVERRIDE','DEPOSIT_ACCOUNT_CONDITION_OVERRIDE','ACCOUNT_CONDITION_OVERRIDE_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_PRODUCT_HISTORY','DEPOSIT_ACCOUNT_PRODUCT_HISTORY','ACCOUNT_PRODUCT_HISTORY_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_SIGNATORY','DEPOSIT_ACCOUNT_SIGNATORY','SIGNATORY_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY','DEPOSIT_ACCOUNT_SIGNATORY_AUTHORITY','SIGNATORY_AUTHORITY_ID');
  ensure_seq('SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST','DEPOSIT_OPERATION_APPROVAL_REQUEST','APPROVAL_REQUEST_ID');
  ensure_seq('SEQ_DEPOSIT_ACTIVATION_RUN','DEPOSIT_ACTIVATION_RUN','ACTIVATION_RUN_ID');
  ensure_seq('SEQ_DEPOSIT_ACTIVATION_CHECK','DEPOSIT_ACTIVATION_CHECK','ACTIVATION_CHECK_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_BULK_ACTION','DEPOSIT_ACCOUNT_BULK_ACTION','BULK_ACTION_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_BULK_ACTION_ITEM','DEPOSIT_ACCOUNT_BULK_ACTION_ITEM','BULK_ACTION_ITEM_ID');
  ensure_seq('SEQ_DEPOSIT_ACCOUNT_SERVICING_HISTORY','DEPOSIT_ACCOUNT_SERVICING_HISTORY','SERVICING_HISTORY_ID');
  ensure_seq('SEQ_DEPOSIT_OPERATION_IDEMPOTENCY','DEPOSIT_OPERATION_IDEMPOTENCY','OPERATION_IDEMPOTENCY_ID');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11J_WAVE_A_RECONCILIATION_PASS
PROMPT ============================================================
