-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11F - Term Deposit Operations
-- Scope: SHORT_TERM_DEPOSIT / LONG_TERM_DEPOSIT operational contract only.
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11F - Term Deposit Operations
PROMPT ============================================================
DECLARE
  v NUMBER;
  FUNCTION table_exists(p_table VARCHAR2) RETURN BOOLEAN IS x NUMBER; BEGIN SELECT COUNT(*) INTO x FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table); RETURN x>0; END;
  FUNCTION index_exists(p_index VARCHAR2) RETURN BOOLEAN IS x NUMBER; BEGIN SELECT COUNT(*) INTO x FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p_index); RETURN x>0; END;
  FUNCTION index_columns_exist(p_table VARCHAR2,p_columns VARCHAR2) RETURN BOOLEAN IS x NUMBER; BEGIN
    SELECT COUNT(*) INTO x FROM (SELECT IC.INDEX_NAME FROM ALL_IND_COLUMNS IC WHERE IC.INDEX_OWNER='DPS2' AND IC.TABLE_OWNER='DPS2' AND IC.TABLE_NAME=UPPER(p_table) GROUP BY IC.INDEX_NAME HAVING LISTAGG(IC.COLUMN_NAME,',') WITHIN GROUP (ORDER BY IC.COLUMN_POSITION)=UPPER(REPLACE(p_columns,' ',''))); RETURN x>0;
  END;
  PROCEDURE require_table(p VARCHAR2) IS BEGIN IF NOT table_exists(p) THEN RAISE_APPLICATION_ERROR(-21160,'Required table DPS2.'||UPPER(p)||' is missing.'); END IF; END;
  PROCEDURE ensure_index(p_table VARCHAR2,p_columns VARCHAR2,p_index VARCHAR2,p_sql VARCHAR2) IS BEGIN
    IF index_columns_exist(p_table,p_columns) THEN DBMS_OUTPUT.PUT_LINE('KEEP : DPS2.'||UPPER(p_table)||' index coverage ('||UPPER(REPLACE(p_columns,' ',''))||')');
    ELSIF index_exists(p_index) THEN RAISE_APPLICATION_ERROR(-21161,'Index DPS2.'||UPPER(p_index)||' exists with different columns.');
    ELSE EXECUTE IMMEDIATE p_sql; DBMS_OUTPUT.PUT_LINE('ADD  : DPS2.'||UPPER(p_index)); END IF;
  END;
BEGIN
  require_table('DEPOSIT_TERM_CONTRACT');
  require_table('DEPOSIT_MATURITY_EVENT');
  require_table('DEPOSIT_TERM_RENEWAL');
  require_table('DEPOSIT_TERM_SETTLEMENT');
  require_table('DEPOSIT_TERM_CONVERSION');
  require_table('DEPOSIT_TERM_PARTIAL_WITHDRAWAL');
  require_table('DEPOSIT_TERM_EARLY_TERMINATION');
  require_table('DEPOSIT_ACCOUNT_PRODUCT_HISTORY');
  require_table('DEPOSIT_OPERATION_APPROVAL_REQUEST');
  require_table('DEPOSIT_OPERATION_IDEMPOTENCY');
  require_table('DEPOSIT_ACCOUNT_BALANCE');
  require_table('DEPOSIT_OPENING_TERM');
  require_table('DEPOSIT_OPENING_MATURITY_INSTRUCTION');

  ensure_index('DEPOSIT_TERM_CONTRACT','ACCOUNT_ID,STATUS_CODE','IX_DEP_TERM_ACCOUNT_STATUS','CREATE INDEX DPS2.IX_DEP_TERM_ACCOUNT_STATUS ON DPS2.DEPOSIT_TERM_CONTRACT(ACCOUNT_ID,STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_TERM_PARTIAL_WITHDRAWAL','ACCOUNT_ID,STATUS_CODE','IX_DEP_TERM_PW_ACCOUNT_STATUS','CREATE INDEX DPS2.IX_DEP_TERM_PW_ACCOUNT_STATUS ON DPS2.DEPOSIT_TERM_PARTIAL_WITHDRAWAL(ACCOUNT_ID,STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_TERM_CONVERSION','ACCOUNT_ID,STATUS_CODE','IX_DEP_TERM_CONV_ACCOUNT_STATUS','CREATE INDEX DPS2.IX_DEP_TERM_CONV_ACCOUNT_STATUS ON DPS2.DEPOSIT_TERM_CONVERSION(ACCOUNT_ID,STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_TERM_EARLY_TERMINATION','ACCOUNT_ID,STATUS_CODE','IX_DEP_TERM_EARLY_ACCOUNT_STATUS','CREATE INDEX DPS2.IX_DEP_TERM_EARLY_ACCOUNT_STATUS ON DPS2.DEPOSIT_TERM_EARLY_TERMINATION(ACCOUNT_ID,STATUS_CODE) TABLESPACE ITS_DPS2');
  ensure_index('DEPOSIT_MATURITY_EVENT','ACCOUNT_ID,MATURITY_DATE','IX_DEP_MATURITY_ACCOUNT_DATE','CREATE INDEX DPS2.IX_DEP_MATURITY_ACCOUNT_DATE ON DPS2.DEPOSIT_MATURITY_EVENT(ACCOUNT_ID,MATURITY_DATE) TABLESPACE ITS_DPS2');

  SELECT COUNT(*) INTO v FROM DPS2.DEPOSIT_OPENING_TERM OT WHERE OT.MATURITY_DATE<=OT.START_DATE;
  IF v>0 THEN RAISE_APPLICATION_ERROR(-21162,'Opening term rows with MATURITY_DATE <= START_DATE: '||v); END IF;

  INSERT INTO DPS2.DEPOSIT_TERM_CONTRACT(
    TERM_CONTRACT_ID,ACCOUNT_ID,PRODUCT_VERSION_ID,TERM_CODE,TERM_VALUE,TERM_UNIT_CODE,START_DATE,MATURITY_DATE,
    PRINCIPAL_AMOUNT,CONTRACT_RATE,RENEWAL_COUNT,MATURITY_SETTLEMENT_ACCOUNT_ID,MATURITY_SETTLEMENT_ACCOUNT_REFERENCE,
    MATURITY_INSTRUCTION_SOURCE_CODE,MATURITY_INSTRUCTION_CODE,STATUS_CODE,SOURCE_OPENING_TERM_ID,SOURCE_OPENING_MATURITY_ID,
    CREATED_AT,CREATED_BY,RECORD_VERSION)
  SELECT DPS2.SEQ_DEPOSIT_TERM_CONTRACT.NEXTVAL,A.ACCOUNT_ID,A.CURRENT_PRODUCT_VERSION_ID,OT.TERM_CODE,OT.TERM_VALUE,OT.TERM_UNIT_CODE,
         OT.START_DATE,OT.MATURITY_DATE,NVL(B.LEDGER_BALANCE,NVL(A.OPENING_AMOUNT,0)),NULL,0,
         MI.SETTLEMENT_ACCOUNT_ID,MI.SETTLEMENT_ACCOUNT_REFERENCE,NVL(MI.INSTRUCTION_SOURCE_CODE,'PRODUCT_DEFAULT'),
         NVL(MI.MATURITY_ACTION_CODE,CASE WHEN OT.AUTO_RENEW_FLAG=1 THEN 'RENEW_PRINCIPAL' ELSE 'WAIT_INSTRUCTION' END),
         'ACTIVE',OT.OPENING_TERM_ID,MI.OPENING_MATURITY_INSTRUCTION_ID,SYSTIMESTAMP,'PHASE11F_MIGRATION',1
    FROM DPS2.DEPOSIT_ACCOUNT A
    JOIN DPS2.DEPOSIT_OPENING_TERM OT ON OT.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID
    LEFT JOIN DPS2.DEPOSIT_OPENING_MATURITY_INSTRUCTION MI ON MI.OPENING_TERM_ID=OT.OPENING_TERM_ID
    LEFT JOIN DPS2.DEPOSIT_ACCOUNT_BALANCE B ON B.ACCOUNT_ID=A.ACCOUNT_ID
   WHERE NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_TERM_CONTRACT T WHERE T.SOURCE_OPENING_TERM_ID=OT.OPENING_TERM_ID);
  DBMS_OUTPUT.PUT_LINE('BACKFILL: DEPOSIT_TERM_CONTRACT rows='||SQL%ROWCOUNT);

  DBMS_OUTPUT.PUT_LINE('SUCCESS: Phase 11F term-deposit operational readiness reconciled.');
END;
/
COMMIT;
PROMPT ============================================================
PROMPT PHASE11F_TERM_OPERATIONS_RECONCILIATION_PASS
PROMPT ============================================================
