-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11C - Lifecycle + Hold/Block Runtime Readiness
-- DDL only. No business DML.

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT ============================================================
PROMPT DPS2 Phase 11C - Lifecycle + Hold/Block Runtime Readiness
PROMPT ============================================================

DECLARE
    FUNCTION table_exists(p_table VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table); RETURN v>0;
    END;
    FUNCTION column_exists(p_table VARCHAR2,p_column VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_column); RETURN v>0;
    END;
    FUNCTION index_exists(p_index VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p_index); RETURN v>0;
    END;
    FUNCTION constraint_exists(p_table VARCHAR2,p_constraint VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND CONSTRAINT_NAME=UPPER(p_constraint); RETURN v>0;
    END;
    PROCEDURE require_table(p_table VARCHAR2) IS BEGIN
        IF NOT table_exists(p_table) THEN RAISE_APPLICATION_ERROR(-21130,'Required table DPS2.'||UPPER(p_table)||' is missing.'); END IF;
    END;
    PROCEDURE require_column(p_table VARCHAR2,p_column VARCHAR2) IS BEGIN
        IF NOT column_exists(p_table,p_column) THEN RAISE_APPLICATION_ERROR(-21131,'Required column DPS2.'||UPPER(p_table)||'.'||UPPER(p_column)||' is missing.'); END IF;
    END;
    PROCEDURE create_index_if_missing(p_index VARCHAR2,p_sql VARCHAR2) IS BEGIN
        IF NOT index_exists(p_index) THEN EXECUTE IMMEDIATE p_sql; DBMS_OUTPUT.PUT_LINE('ADD : DPS2.'||UPPER(p_index)); ELSE DBMS_OUTPUT.PUT_LINE('KEEP: DPS2.'||UPPER(p_index)); END IF;
    END;
BEGIN
    require_table('DEPOSIT_ACCOUNT');
    require_column('DEPOSIT_ACCOUNT','ACCOUNT_STATUS_CODE');
    require_column('DEPOSIT_ACCOUNT','DORMANCY_DATE');
    require_column('DEPOSIT_ACCOUNT','RECORD_VERSION');
    require_table('DEPOSIT_ACCOUNT_LIFECYCLE_EVENT');
    require_table('DEPOSIT_ACCOUNT_STATUS_HISTORY');
    require_table('DEPOSIT_ACCOUNT_HOLD');
    require_table('DEPOSIT_ACCOUNT_HOLD_HISTORY');
    require_table('DEPOSIT_OPERATION_IDEMPOTENCY');
    require_table('DEPOSIT_ACCOUNT_SERVICING_HISTORY');

    IF constraint_exists('DEPOSIT_ACCOUNT_SERVICING_HISTORY','CHK_DEPOSIT_ACCOUNT_SERVICING_HISTORY_CHANGE_TYPE_CODE') THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_ACCOUNT_SERVICING_HISTORY DROP CONSTRAINT CHK_DEPOSIT_ACCOUNT_SERVICING_HISTORY_CHANGE_TYPE_CODE';
        DBMS_OUTPUT.PUT_LINE('DROP: DPS2.DEPOSIT_ACCOUNT_SERVICING_HISTORY.CHK_DEPOSIT_ACCOUNT_SERVICING_HISTORY_CHANGE_TYPE_CODE');
    END IF;
    EXECUTE IMMEDIATE q'[ALTER TABLE DPS2.DEPOSIT_ACCOUNT_SERVICING_HISTORY ADD CONSTRAINT CHK_DEPOSIT_ACCOUNT_SERVICING_HISTORY_CHANGE_TYPE_CODE CHECK (CHANGE_TYPE_CODE IN ('BASIC_INFO','ORG_UNIT','PRODUCT_VERSION','CONDITION','OWNER','CONTACT','SIGNATORY','STATUS','HOLD')) ENABLE VALIDATE]';
    DBMS_OUTPUT.PUT_LINE('ADD : servicing-history change types STATUS/HOLD.');

    create_index_if_missing('IX_DEP_HOLD_ACCOUNT_STATUS',
        'CREATE INDEX DPS2.IX_DEP_HOLD_ACCOUNT_STATUS ON DPS2.DEPOSIT_ACCOUNT_HOLD (ACCOUNT_ID,HOLD_STATUS_CODE) TABLESPACE ITS_DPS2');
    create_index_if_missing('IX_DEP_STATUS_HIST_ACCOUNT_AT',
        'CREATE INDEX DPS2.IX_DEP_STATUS_HIST_ACCOUNT_AT ON DPS2.DEPOSIT_ACCOUNT_STATUS_HISTORY (ACCOUNT_ID,EFFECTIVE_AT) TABLESPACE ITS_DPS2');
    create_index_if_missing('IX_DEP_IDEMP_ACCOUNT_OP',
        'CREATE INDEX DPS2.IX_DEP_IDEMP_ACCOUNT_OP ON DPS2.DEPOSIT_OPERATION_IDEMPOTENCY (ACCOUNT_ID,OPERATION_TYPE_CODE,REQUESTED_AT) TABLESPACE ITS_DPS2');

    DBMS_OUTPUT.PUT_LINE('SUCCESS: Phase 11C runtime-readiness DDL completed.');
    DBMS_OUTPUT.PUT_LINE('NOTE: No business row was inserted, updated, deleted or merged.');
END;
/

PROMPT ============================================================
PROMPT PHASE11C_SCHEMA_RUNTIME_READINESS_PASS
PROMPT ============================================================
