-- Core Banking Prototype 0.11.0 - Phase 11B
-- Account Servicing Core + Account Party operationalization
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
PROMPT ============================================================
PROMPT DPS2 Phase 11B - Account Servicing Core + Account Party
PROMPT ============================================================

DECLARE
  v_missing NUMBER;
  v_inserted NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_missing FROM (
    SELECT 'DEPOSIT_ACCOUNT_PARTY' n FROM dual UNION ALL
    SELECT 'DEPOSIT_ACCOUNT_CONTACT' FROM dual UNION ALL
    SELECT 'DEPOSIT_ACCOUNT_SERVICING_HISTORY' FROM dual
  ) x WHERE NOT EXISTS (SELECT 1 FROM ALL_TABLES t WHERE t.OWNER='DPS2' AND t.TABLE_NAME=x.n);
  IF v_missing>0 THEN RAISE_APPLICATION_ERROR(-21120,'Phase 11B prerequisite Account Servicing tables are missing.'); END IF;

  INSERT INTO DPS2.DEPOSIT_ACCOUNT_PARTY(
    ACCOUNT_PARTY_ID,ACCOUNT_ID,PARTY_ID,ROLE_CODE,IS_PRIMARY,OWNERSHIP_PERCENT,
    VALID_FROM,STATUS_CODE,SOURCE_OPENING_PARTY_ID,CREATED_AT,CREATED_BY,RECORD_VERSION
  )
  SELECT DPS2.SEQ_DEPOSIT_ACCOUNT_PARTY.NEXTVAL,A.ACCOUNT_ID,OP.PARTY_ID,OP.ROLE_CODE,
         OP.IS_PRIMARY,OP.OWNERSHIP_PERCENT,TRUNC(A.CREATED_AT),'ACTIVE',OP.OPENING_PARTY_ID,
         SYSTIMESTAMP,'PHASE11B_BACKFILL',1
    FROM DPS2.DEPOSIT_ACCOUNT A
    JOIN DPS2.DEPOSIT_OPENING_PARTY OP ON OP.OPENING_REQUEST_ID=A.OPENING_REQUEST_ID
   WHERE NOT EXISTS (
     SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_PARTY AP
      WHERE AP.SOURCE_OPENING_PARTY_ID=OP.OPENING_PARTY_ID
   );
  v_inserted := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('BACKFILL: DEPOSIT_ACCOUNT_PARTY rows inserted='||v_inserted);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('SUCCESS: Phase 11B Account Party backfill/reconciliation completed.');
END;
/

PROMPT ------------------------------------------------------------
SELECT COUNT(*) AS ACCOUNT_PARTY_ROWS FROM DPS2.DEPOSIT_ACCOUNT_PARTY;
SELECT COUNT(*) AS ACTIVE_ACCOUNT_PARTY_ROWS FROM DPS2.DEPOSIT_ACCOUNT_PARTY WHERE STATUS_CODE='ACTIVE';
PROMPT ============================================================
PROMPT PHASE11B_SCHEMA_DATA_RECONCILIATION_PASS
PROMPT ============================================================
