-- Core Banking Prototype 0.11.0
-- DPS2 Phase 11D - Balance + Subledger
-- Scope: four deposits / DPS2 only.
-- Reconciles Package 17 as the monetary balance source of truth.

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT ============================================================
PROMPT DPS2 Phase 11D - Balance + Subledger
PROMPT ============================================================

DECLARE
    -- Scalar variables must be declared before local FUNCTION/PROCEDURE declarations in PL/SQL.
    v_entries NUMBER:=0;
    v_balances NUMBER:=0;
    v_reconciled NUMBER:=0;
    v_controls NUMBER:=0;
    v_null_entry_base NUMBER:=0;
    v_migration_entry_need NUMBER:=0;

    FUNCTION table_exists(p_table VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table); RETURN v>0;
    END;
    FUNCTION column_exists(p_table VARCHAR2,p_column VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_TAB_COLUMNS WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_column); RETURN v>0;
    END;
    FUNCTION index_exists(p_index VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_INDEXES WHERE OWNER='DPS2' AND INDEX_NAME=UPPER(p_index); RETURN v>0;
    END;
    FUNCTION index_columns_exist(p_table VARCHAR2,p_columns VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v
          FROM (
                SELECT IC.INDEX_NAME
                  FROM ALL_IND_COLUMNS IC
                 WHERE IC.INDEX_OWNER='DPS2'
                   AND IC.TABLE_OWNER='DPS2'
                   AND IC.TABLE_NAME=UPPER(p_table)
                 GROUP BY IC.INDEX_NAME
                HAVING LISTAGG(IC.COLUMN_NAME,',') WITHIN GROUP (ORDER BY IC.COLUMN_POSITION)=UPPER(REPLACE(p_columns,' ',''))
               );
        RETURN v>0;
    END;
    FUNCTION constraint_exists(p_table VARCHAR2,p_constraint VARCHAR2) RETURN BOOLEAN IS v NUMBER; BEGIN
        SELECT COUNT(*) INTO v FROM ALL_CONSTRAINTS
         WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND CONSTRAINT_NAME=UPPER(p_constraint) AND STATUS='ENABLED';
        RETURN v>0;
    END;
    PROCEDURE reconcile_tx_sequence_uniqueness IS v NUMBER; BEGIN
        -- ENTRY_SEQUENCE_NO is scoped to a real transaction. Non-transactional postings deliberately use TRANSACTION_ID=NULL
        -- and may all use sequence 1. Enforce uniqueness only when TRANSACTION_ID is present.
        SELECT COUNT(*) INTO v FROM (
            SELECT TRANSACTION_ID,ENTRY_SEQUENCE_NO
              FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY
             WHERE TRANSACTION_ID IS NOT NULL
             GROUP BY TRANSACTION_ID,ENTRY_SEQUENCE_NO
            HAVING COUNT(*)>1
        );
        IF v>0 THEN
            RAISE_APPLICATION_ERROR(-21144,'Duplicate non-null TRANSACTION_ID/ENTRY_SEQUENCE_NO rows prevent Phase 11D uniqueness reconciliation.');
        END IF;

        IF constraint_exists('DEPOSIT_SUBLEDGER_ENTRY','UK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID_ENTRY_SEQUENCE_NO') THEN
            EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_SUBLEDGER_ENTRY DROP CONSTRAINT UK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID_ENTRY_SEQUENCE_NO';
            DBMS_OUTPUT.PUT_LINE('DROP : DPS2.UK_DEPOSIT_SUBLEDGER_ENTRY_TRANSACTION_ID_ENTRY_SEQUENCE_NO');
        ELSE
            DBMS_OUTPUT.PUT_LINE('KEEP : legacy transaction/sequence constraint already absent');
        END IF;

        IF NOT index_exists('UX_DEP_SUBLEDGER_TX_SEQ_NN') THEN
            EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX DPS2.UX_DEP_SUBLEDGER_TX_SEQ_NN
                ON DPS2.DEPOSIT_SUBLEDGER_ENTRY (
                    CASE WHEN TRANSACTION_ID IS NOT NULL THEN TRANSACTION_ID ELSE NULL END,
                    CASE WHEN TRANSACTION_ID IS NOT NULL THEN ENTRY_SEQUENCE_NO ELSE NULL END
                ) TABLESPACE ITS_DPS2]';
            DBMS_OUTPUT.PUT_LINE('ADD  : DPS2.UX_DEP_SUBLEDGER_TX_SEQ_NN (transaction-scoped uniqueness)');
        ELSE
            DBMS_OUTPUT.PUT_LINE('KEEP : DPS2.UX_DEP_SUBLEDGER_TX_SEQ_NN');
        END IF;
    END;
    PROCEDURE require_table(p_table VARCHAR2) IS BEGIN
        IF NOT table_exists(p_table) THEN RAISE_APPLICATION_ERROR(-21140,'Required table DPS2.'||UPPER(p_table)||' is missing.'); END IF;
    END;
    PROCEDURE require_column(p_table VARCHAR2,p_column VARCHAR2) IS BEGIN
        IF NOT column_exists(p_table,p_column) THEN RAISE_APPLICATION_ERROR(-21141,'Required column DPS2.'||UPPER(p_table)||'.'||UPPER(p_column)||' is missing.'); END IF;
    END;
    PROCEDURE widen_number(p_table VARCHAR2,p_column VARCHAR2) IS p NUMBER; s NUMBER; BEGIN
        SELECT DATA_PRECISION,DATA_SCALE INTO p,s FROM ALL_TAB_COLUMNS
         WHERE OWNER='DPS2' AND TABLE_NAME=UPPER(p_table) AND COLUMN_NAME=UPPER(p_column);
        IF NVL(p,0)<24 OR NVL(s,0)<4 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE DPS2.'||UPPER(p_table)||' MODIFY ('||UPPER(p_column)||' NUMBER(24,4))';
            DBMS_OUTPUT.PUT_LINE('WIDEN: DPS2.'||UPPER(p_table)||'.'||UPPER(p_column)||' -> NUMBER(24,4)');
        ELSE
            DBMS_OUTPUT.PUT_LINE('KEEP : DPS2.'||UPPER(p_table)||'.'||UPPER(p_column)||' NUMBER('||p||','||s||')');
        END IF;
    END;
    PROCEDURE create_index_if_missing(p_table VARCHAR2,p_columns VARCHAR2,p_index VARCHAR2,p_sql VARCHAR2) IS BEGIN
        IF index_columns_exist(p_table,p_columns) THEN
            DBMS_OUTPUT.PUT_LINE('KEEP : DPS2.'||UPPER(p_table)||' index coverage ('||UPPER(REPLACE(p_columns,' ',''))||')');
        ELSIF index_exists(p_index) THEN
            RAISE_APPLICATION_ERROR(-21143,'Index DPS2.'||UPPER(p_index)||' exists with a different column list.');
        ELSE
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('ADD  : DPS2.'||UPPER(p_index));
        END IF;
    END;
BEGIN
    require_table('DEPOSIT_ACCOUNT');
    require_table('DEPOSIT_ACCOUNT_BALANCE');
    require_table('DEPOSIT_SUBLEDGER_ENTRY');
    require_table('DEPOSIT_BALANCE_RESERVATION');
    require_table('DEPOSIT_ACCOUNT_HOLD');
    require_table('DEPOSIT_OPERATION_IDEMPOTENCY');
    require_column('DEPOSIT_ACCOUNT','LEDGER_BALANCE');
    require_column('DEPOSIT_ACCOUNT','AVAILABLE_BALANCE');

    widen_number('DEPOSIT_ACCOUNT_BALANCE','LEDGER_BALANCE');
    widen_number('DEPOSIT_ACCOUNT_BALANCE','AVAILABLE_BALANCE');
    widen_number('DEPOSIT_ACCOUNT_BALANCE','BLOCKED_AMOUNT');
    widen_number('DEPOSIT_ACCOUNT_BALANCE','UNCLEARED_AMOUNT');
    widen_number('DEPOSIT_ACCOUNT_BALANCE','PENDING_DEBIT_AMOUNT');
    widen_number('DEPOSIT_ACCOUNT_BALANCE','PENDING_CREDIT_AMOUNT');
    widen_number('DEPOSIT_SUBLEDGER_ENTRY','AMOUNT');
    widen_number('DEPOSIT_BALANCE_RESERVATION','AMOUNT');

    reconcile_tx_sequence_uniqueness;

    -- Traceable baseline for legacy balances. This is a migration marker, not a fabricated business transaction.
    -- TRANSACTION_ID stays NULL by design. The migration still allocates a deterministic unique
    -- sequence range for baseline traceability and compatibility with databases upgraded from older contracts.
    SELECT NVL(MAX(S.ENTRY_SEQUENCE_NO),0)
      INTO v_null_entry_base
      FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
     WHERE S.TRANSACTION_ID IS NULL;

    SELECT COUNT(*)
      INTO v_migration_entry_need
      FROM DPS2.DEPOSIT_ACCOUNT A
     WHERE NVL(A.LEDGER_BALANCE,0)<>0
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.ACCOUNT_ID=A.ACCOUNT_ID)
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.POSTING_REFERENCE='PH11D-MIG-'||A.ACCOUNT_ID);

    IF v_null_entry_base + v_migration_entry_need > 999999 THEN
        RAISE_APPLICATION_ERROR(-21142,'Insufficient ENTRY_SEQUENCE_NO range for Phase 11D migration baseline.');
    END IF;

    INSERT INTO DPS2.DEPOSIT_SUBLEDGER_ENTRY(
        SUBLEDGER_ENTRY_ID,ACCOUNT_ID,TRANSACTION_ID,TRANSACTION_LEG_ID,ENTRY_SEQUENCE_NO,
        POSTING_REFERENCE,SOURCE_ENTITY_TYPE,SOURCE_ENTITY_ID,DEBIT_CREDIT_CODE,AMOUNT,CURRENCY_CODE,
        BOOKING_DATE,VALUE_DATE,POSTED_AT,REVERSAL_OF_ENTRY_ID,GL_POSTING_REFERENCE,CREATED_AT,CREATED_BY
    )
    SELECT DPS2.SEQ_DEPOSIT_SUBLEDGER_ENTRY.NEXTVAL,A.ACCOUNT_ID,NULL,NULL,
           v_null_entry_base + ROW_NUMBER() OVER (ORDER BY A.ACCOUNT_ID),
           'PH11D-MIG-'||A.ACCOUNT_ID,'BALANCE_MIGRATION',A.ACCOUNT_ID,
           CASE WHEN NVL(A.LEDGER_BALANCE,0)<0 THEN 'DEBIT' ELSE 'CREDIT' END,
           ABS(NVL(A.LEDGER_BALANCE,0)),A.CURRENCY_CODE,
           NVL(A.OPENED_ON,TRUNC(SYSDATE)),NVL(A.OPENED_ON,TRUNC(SYSDATE)),SYSTIMESTAMP,NULL,
           'LEGACY-DEPOSIT_ACCOUNT',SYSTIMESTAMP,'PHASE11D_MIGRATION'
      FROM DPS2.DEPOSIT_ACCOUNT A
     WHERE NVL(A.LEDGER_BALANCE,0)<>0
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.ACCOUNT_ID=A.ACCOUNT_ID)
       AND NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S WHERE S.POSTING_REFERENCE='PH11D-MIG-'||A.ACCOUNT_ID);
    v_entries:=SQL%ROWCOUNT;

    INSERT INTO DPS2.DEPOSIT_ACCOUNT_BALANCE(
        ACCOUNT_BALANCE_ID,ACCOUNT_ID,CURRENCY_CODE,LEDGER_BALANCE,AVAILABLE_BALANCE,BLOCKED_AMOUNT,
        UNCLEARED_AMOUNT,PENDING_DEBIT_AMOUNT,PENDING_CREDIT_AMOUNT,LAST_SUBLEDGER_ENTRY_ID,
        BALANCE_AS_OF,CREATED_AT,CREATED_BY,RECORD_VERSION
    )
    SELECT DPS2.SEQ_DEPOSIT_ACCOUNT_BALANCE.NEXTVAL,
           A.ACCOUNT_ID,
           A.CURRENCY_CODE,
           NVL(A.LEDGER_BALANCE,0),
           CASE
             WHEN EXISTS (
                 SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                  WHERE H.ACCOUNT_ID=A.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                    AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                    AND H.HOLD_TYPE_CODE IN ('FULL','DEBIT_ONLY')
             ) THEN 0
             ELSE GREATEST(NVL(A.LEDGER_BALANCE,0)
                  - NVL((SELECT SUM(H.HOLD_AMOUNT) FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                          WHERE H.ACCOUNT_ID=A.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                            AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                            AND H.HOLD_TYPE_CODE='PARTIAL'),0)
                  - NVL((SELECT SUM(R.AMOUNT) FROM DPS2.DEPOSIT_BALANCE_RESERVATION R
                          WHERE R.ACCOUNT_ID=A.ACCOUNT_ID AND R.RESERVATION_STATUS_CODE='ACTIVE'
                            AND (R.EXPIRES_AT IS NULL OR R.EXPIRES_AT>SYSTIMESTAMP)),0),0)
           END,
           CASE
             WHEN EXISTS (
                 SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                  WHERE H.ACCOUNT_ID=A.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                    AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                    AND H.HOLD_TYPE_CODE IN ('FULL','DEBIT_ONLY')
             ) THEN GREATEST(NVL(A.LEDGER_BALANCE,0),0)
             ELSE NVL((SELECT SUM(H.HOLD_AMOUNT) FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                        WHERE H.ACCOUNT_ID=A.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                          AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                          AND H.HOLD_TYPE_CODE='PARTIAL'),0)
           END,
           0,
           NVL((SELECT SUM(R.AMOUNT) FROM DPS2.DEPOSIT_BALANCE_RESERVATION R
                 WHERE R.ACCOUNT_ID=A.ACCOUNT_ID AND R.RESERVATION_STATUS_CODE='ACTIVE'
                   AND (R.EXPIRES_AT IS NULL OR R.EXPIRES_AT>SYSTIMESTAMP)),0),
           0,
           (SELECT MAX(S.SUBLEDGER_ENTRY_ID) KEEP (DENSE_RANK LAST ORDER BY S.SUBLEDGER_ENTRY_ID)
              FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
             WHERE S.ACCOUNT_ID=A.ACCOUNT_ID AND S.POSTING_REFERENCE='PH11D-MIG-'||A.ACCOUNT_ID),
           SYSTIMESTAMP,SYSTIMESTAMP,'PHASE11D_MIGRATION',1
      FROM DPS2.DEPOSIT_ACCOUNT A
     WHERE NOT EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B WHERE B.ACCOUNT_ID=A.ACCOUNT_ID);
    v_balances:=SQL%ROWCOUNT;

    -- Existing pre-11D balance rows with no prior subledger trace are cut over from the legacy account balance.
    UPDATE DPS2.DEPOSIT_ACCOUNT_BALANCE B
       SET (LEDGER_BALANCE,LAST_SUBLEDGER_ENTRY_ID,UPDATED_AT,UPDATED_BY,RECORD_VERSION) = (
           SELECT NVL(A.LEDGER_BALANCE,0),
                  (SELECT MAX(S.SUBLEDGER_ENTRY_ID) FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
                    WHERE S.ACCOUNT_ID=A.ACCOUNT_ID AND S.POSTING_REFERENCE='PH11D-MIG-'||A.ACCOUNT_ID),
                  SYSTIMESTAMP,'PHASE11D_MIGRATION',B.RECORD_VERSION+1
             FROM DPS2.DEPOSIT_ACCOUNT A WHERE A.ACCOUNT_ID=B.ACCOUNT_ID
       )
     WHERE B.LAST_SUBLEDGER_ENTRY_ID IS NULL
       AND EXISTS (SELECT 1 FROM DPS2.DEPOSIT_SUBLEDGER_ENTRY S
                    WHERE S.ACCOUNT_ID=B.ACCOUNT_ID AND S.POSTING_REFERENCE='PH11D-MIG-'||B.ACCOUNT_ID);
    v_reconciled:=SQL%ROWCOUNT;

    -- Derived balance controls are reconciled only when values differ, keeping the migration rerunnable.
    MERGE INTO DPS2.DEPOSIT_ACCOUNT_BALANCE B
    USING (
        SELECT X.ACCOUNT_ID,
               CASE WHEN X.DEBIT_BLOCKED=1 THEN 0
                    ELSE GREATEST(X.LEDGER_BALANCE-X.PARTIAL_HOLD-X.ACTIVE_RESERVATION,0) END AS DESIRED_AVAILABLE,
               CASE WHEN X.DEBIT_BLOCKED=1 THEN GREATEST(X.LEDGER_BALANCE,0)
                    ELSE X.PARTIAL_HOLD END AS DESIRED_BLOCKED,
               X.ACTIVE_RESERVATION AS DESIRED_PENDING_DEBIT
          FROM (
              SELECT B2.ACCOUNT_ID,B2.LEDGER_BALANCE,
                     CASE WHEN EXISTS (SELECT 1 FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                                        WHERE H.ACCOUNT_ID=B2.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                                          AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                                          AND H.HOLD_TYPE_CODE IN ('FULL','DEBIT_ONLY')) THEN 1 ELSE 0 END AS DEBIT_BLOCKED,
                     NVL((SELECT SUM(H.HOLD_AMOUNT) FROM DPS2.DEPOSIT_ACCOUNT_HOLD H
                           WHERE H.ACCOUNT_ID=B2.ACCOUNT_ID AND H.HOLD_STATUS_CODE='ACTIVE'
                             AND (H.VALID_TO IS NULL OR H.VALID_TO>SYSTIMESTAMP)
                             AND H.HOLD_TYPE_CODE='PARTIAL'),0) AS PARTIAL_HOLD,
                     NVL((SELECT SUM(R.AMOUNT) FROM DPS2.DEPOSIT_BALANCE_RESERVATION R
                           WHERE R.ACCOUNT_ID=B2.ACCOUNT_ID AND R.RESERVATION_STATUS_CODE='ACTIVE'
                             AND (R.EXPIRES_AT IS NULL OR R.EXPIRES_AT>SYSTIMESTAMP)),0) AS ACTIVE_RESERVATION
                FROM DPS2.DEPOSIT_ACCOUNT_BALANCE B2
          ) X
    ) D
    ON (D.ACCOUNT_ID=B.ACCOUNT_ID)
    WHEN MATCHED THEN UPDATE SET
         B.AVAILABLE_BALANCE=D.DESIRED_AVAILABLE,
         B.BLOCKED_AMOUNT=D.DESIRED_BLOCKED,
         B.PENDING_DEBIT_AMOUNT=D.DESIRED_PENDING_DEBIT,
         B.BALANCE_AS_OF=SYSTIMESTAMP,
         B.UPDATED_AT=SYSTIMESTAMP,
         B.UPDATED_BY='PHASE11D_MIGRATION',
         B.RECORD_VERSION=B.RECORD_VERSION+1
     WHERE B.AVAILABLE_BALANCE<>D.DESIRED_AVAILABLE
        OR B.BLOCKED_AMOUNT<>D.DESIRED_BLOCKED
        OR B.PENDING_DEBIT_AMOUNT<>D.DESIRED_PENDING_DEBIT;
    v_controls:=SQL%ROWCOUNT;

    create_index_if_missing('DEPOSIT_SUBLEDGER_ENTRY','ACCOUNT_ID,POSTED_AT','IX_DEP_SUBLEDGER_ACCOUNT_POSTED',
        'CREATE INDEX DPS2.IX_DEP_SUBLEDGER_ACCOUNT_POSTED ON DPS2.DEPOSIT_SUBLEDGER_ENTRY (ACCOUNT_ID,POSTED_AT) TABLESPACE ITS_DPS2');
    create_index_if_missing('DEPOSIT_BALANCE_RESERVATION','ACCOUNT_ID,RESERVATION_STATUS_CODE,EXPIRES_AT','IX_DEP_RESERV_ACCOUNT_STATUS',
        'CREATE INDEX DPS2.IX_DEP_RESERV_ACCOUNT_STATUS ON DPS2.DEPOSIT_BALANCE_RESERVATION (ACCOUNT_ID,RESERVATION_STATUS_CODE,EXPIRES_AT) TABLESPACE ITS_DPS2');

    DBMS_OUTPUT.PUT_LINE('BACKFILL: DEPOSIT_SUBLEDGER_ENTRY baseline rows='||v_entries);
    DBMS_OUTPUT.PUT_LINE('BACKFILL: DEPOSIT_ACCOUNT_BALANCE rows='||v_balances);
    DBMS_OUTPUT.PUT_LINE('RECONCILE: existing Package 17 rows cut over='||v_reconciled);
    DBMS_OUTPUT.PUT_LINE('RECONCILE: derived balance-control rows updated='||v_controls);
    DBMS_OUTPUT.PUT_LINE('SUCCESS: Phase 11D Balance/Subledger reconciliation completed.');
END;
/
COMMIT;

PROMPT ============================================================
PROMPT PHASE11D_BALANCE_SUBLEDGER_RECONCILIATION_PASS
PROMPT ============================================================
