PROMPT ============================================================
PROMPT DPS2 Phase 6 - Batch / Bulk Deposit Opening
PROMPT Version 0.6.0
PROMPT Scope: seed source-defined Batch references + HTML-aligned provisional error codes
PROMPT Existing operational tables are NOT recreated.
PROMPT ============================================================

-- Source-defined request type used by each normalized Batch item.
MERGE INTO DPS2.REF_DEP_OPEN_REQUEST_TYPE t
USING (SELECT 'BULK' REQUEST_TYPE_CODE, 'افتتاح گروهی' TITLE_FA, 'Bulk opening' TITLE_EN,
              'درخواست افتتاح تولیدشده از DEPOSIT_OPENING_BATCH_ITEM' DESCRIPTION, 30 DISPLAY_ORDER FROM DUAL) s
ON (t.REQUEST_TYPE_CODE=s.REQUEST_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.TITLE_FA,t.TITLE_EN=s.TITLE_EN,t.DESCRIPTION=s.DESCRIPTION,t.DISPLAY_ORDER=s.DISPLAY_ORDER,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (REQUEST_TYPE_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY)
VALUES (s.REQUEST_TYPE_CODE,s.TITLE_FA,s.TITLE_EN,s.DESCRIPTION,s.DISPLAY_ORDER,1,'MIGRATION_0.6.0');

-- Batch lifecycle codes documented by the EA model.
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'DRAFT' C,'پیش‌نویس' F,'Draft' E,10 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'VALIDATING' C,'در حال اعتبارسنجی' F,'Validating' E,20 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'READY' C,'آماده پردازش' F,'Ready' E,30 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'PROCESSING' C,'در حال پردازش' F,'Processing' E,40 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'COMPLETED' C,'تکمیل‌شده' F,'Completed' E,50 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'PARTIAL' C,'تکمیل جزئی' F,'Partial' E,60 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_STATUS t USING (SELECT 'FAILED' C,'ناموفق' F,'Failed' E,70 O FROM DUAL) s ON (t.BATCH_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (BATCH_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');

-- Item lifecycle codes documented by the EA model / HTML flow.
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'PENDING' C,'در انتظار' F,'Pending' E,10 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'VALID' C,'معتبر' F,'Valid' E,20 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'INVALID' C,'نامعتبر' F,'Invalid' E,30 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'PROCESSING' C,'در حال پردازش' F,'Processing' E,40 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'SUCCESS' C,'موفق' F,'Success' E,50 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ITEM_STATUS t USING (SELECT 'FAILED' C,'ناموفق' F,'Failed' E,60 O FROM DUAL) s ON (t.ITEM_STATUS_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ITEM_STATUS_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');

-- Source types documented by the EA model and exposed by the HTML form.
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_SOURCE_TYPE t USING (SELECT 'FILE' C,'فایل' F,'File' E,10 O FROM DUAL) s ON (t.SOURCE_TYPE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (SOURCE_TYPE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_SOURCE_TYPE t USING (SELECT 'API' C,'API' F,'API' E,20 O FROM DUAL) s ON (t.SOURCE_TYPE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (SOURCE_TYPE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_SOURCE_TYPE t USING (SELECT 'MANUAL' C,'ورود دستی' F,'Manual' E,30 O FROM DUAL) s ON (t.SOURCE_TYPE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (SOURCE_TYPE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');

-- Error stages are source-defined: VALIDATION, PROCESSING, POSTING.
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_STAGE t USING (SELECT 'VALIDATION' C,'اعتبارسنجی' F,'Validation' E,10 O FROM DUAL) s ON (t.ERROR_STAGE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_STAGE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_STAGE t USING (SELECT 'PROCESSING' C,'پردازش' F,'Processing' E,20 O FROM DUAL) s ON (t.ERROR_STAGE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_STAGE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_STAGE t USING (SELECT 'POSTING' C,'ثبت/فعال‌سازی نتیجه' F,'Posting' E,30 O FROM DUAL) s ON (t.ERROR_STAGE_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_STAGE_CODE,TITLE_FA,TITLE_EN,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,s.O,1,'MIGRATION_0.6.0');

-- The EA model deliberately leaves definitive ERROR_CODE values governed externally.
-- These three are minimal prototype codes required by the supplied HTML-aligned workflow.
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_CODE t USING (SELECT 'ROW_INVALID' C,'ردیف نامعتبر' F,'Invalid row' E,'VALIDATION' S,10 O FROM DUAL) s ON (t.ERROR_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.ERROR_STAGE_CODE=s.S,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,ERROR_STAGE_CODE,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,'Prototype provisional code aligned with supplied Deposit Account Opening HTML.',s.S,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_CODE t USING (SELECT 'PROCESSING_FAILED' C,'خطای پردازش ردیف' F,'Item processing failed' E,'PROCESSING' S,20 O FROM DUAL) s ON (t.ERROR_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.ERROR_STAGE_CODE=s.S,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,ERROR_STAGE_CODE,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,'Prototype provisional technical code; final bank taxonomy remains Data-Governance owned.',s.S,s.O,1,'MIGRATION_0.6.0');
MERGE INTO DPS2.REF_DEP_OPEN_BATCH_ERROR_CODE t USING (SELECT 'ACTIVATION_FAILED' C,'خطای فعال‌سازی حساب' F,'Account activation failed' E,'POSTING' S,30 O FROM DUAL) s ON (t.ERROR_CODE=s.C)
WHEN MATCHED THEN UPDATE SET t.TITLE_FA=s.F,t.TITLE_EN=s.E,t.ERROR_STAGE_CODE=s.S,t.DISPLAY_ORDER=s.O,t.IS_ACTIVE=1,t.UPDATED_AT=SYSTIMESTAMP,t.UPDATED_BY='MIGRATION_0.6.0'
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,TITLE_FA,TITLE_EN,DESCRIPTION,ERROR_STAGE_CODE,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) VALUES(s.C,s.F,s.E,'Prototype provisional technical code; final bank taxonomy remains Data-Governance owned.',s.S,s.O,1,'MIGRATION_0.6.0');

COMMIT;
PROMPT Phase 6 Batch / Bulk Deposit Opening migration completed.
