PROMPT ============================================================
PROMPT DPS2 0.7.0 - Phase 7 Deposit Opening E2E Runtime Hardening
PROMPT Scope: database-level idempotency/concurrency guards only
PROMPT Existing business tables are not recreated.
PROMPT ============================================================

SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM (
      SELECT IDEMPOTENCY_KEY
        FROM DPS2.DEPOSIT_OPENING_REQUEST
       WHERE IDEMPOTENCY_KEY IS NOT NULL
       GROUP BY IDEMPOTENCY_KEY
      HAVING COUNT(*) > 1
    );
  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20701,
      'DPS2.DEPOSIT_OPENING_REQUEST contains duplicate IDEMPOTENCY_KEY values. Resolve duplicates before 0.7.0 migration.');
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM (
      SELECT IDEMPOTENCY_KEY
        FROM DPS2.DEPOSIT_OPENING_BATCH
       WHERE IDEMPOTENCY_KEY IS NOT NULL
       GROUP BY IDEMPOTENCY_KEY
      HAVING COUNT(*) > 1
    );
  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20702,
      'DPS2.DEPOSIT_OPENING_BATCH contains duplicate IDEMPOTENCY_KEY values. Resolve duplicates before 0.7.0 migration.');
  END IF;

  SELECT COUNT(*) INTO v_count
    FROM (
      SELECT OPENING_BATCH_ID, EXTERNAL_ROW_KEY
        FROM DPS2.DEPOSIT_OPENING_BATCH_ITEM
       WHERE EXTERNAL_ROW_KEY IS NOT NULL
       GROUP BY OPENING_BATCH_ID, EXTERNAL_ROW_KEY
      HAVING COUNT(*) > 1
    );
  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20703,
      'DPS2.DEPOSIT_OPENING_BATCH_ITEM contains duplicate EXTERNAL_ROW_KEY inside a Batch. Resolve duplicates before 0.7.0 migration.');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='DPS2' AND INDEX_NAME='UX_DEP_OPEN_REQ_IDEMPOTENCY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DPS2.UX_DEP_OPEN_REQ_IDEMPOTENCY ON DPS2.DEPOSIT_OPENING_REQUEST (IDEMPOTENCY_KEY)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='DPS2' AND INDEX_NAME='UX_DEP_OPEN_BATCH_IDEMPOTENCY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DPS2.UX_DEP_OPEN_BATCH_IDEMPOTENCY ON DPS2.DEPOSIT_OPENING_BATCH (IDEMPOTENCY_KEY)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='DPS2' AND INDEX_NAME='UX_DEP_OPEN_BATCH_EXT_ROW_KEY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DPS2.UX_DEP_OPEN_BATCH_EXT_ROW_KEY ON DPS2.DEPOSIT_OPENING_BATCH_ITEM (OPENING_BATCH_ID, EXTERNAL_ROW_KEY)';
  END IF;
END;
/

PROMPT 0.7.0 Phase 7 hardening migration completed.
