-- Core Banking Prototype 0.9.0
-- Phase 9 - Deposit Account Servicing / Account Closure
-- Target schema: DPS2
--
-- Source-model boundary:
--   The physical DEPOSIT_ACCOUNT contract already supports CLOSED.
--   This migration only enables the corresponding CLOSE lifecycle event and
--   protects lifecycle events as append-only audit history.
--   HOLD/BLOCKED/DORMANT/REACTIVATION are intentionally NOT introduced here.

SET DEFINE OFF;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM ALL_CONSTRAINTS
     WHERE OWNER='DPS2'
       AND TABLE_NAME='DEPOSIT_ACCOUNT_LIFECYCLE_EVENT'
       AND CONSTRAINT_NAME='CK_DEP_ACCT_EVT_TYPE';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT DROP CONSTRAINT CK_DEP_ACCT_EVT_TYPE';
    END IF;
END;
/

ALTER TABLE DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT
    ADD CONSTRAINT CK_DEP_ACCT_EVT_TYPE
    CHECK (EVENT_TYPE_CODE IN ('CREATE','ACTIVATE','CLOSE'));

CREATE OR REPLACE TRIGGER DPS2.TRG_DEP_ACCT_EVT_APPEND_ONLY
BEFORE UPDATE OR DELETE ON DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT
BEGIN
    RAISE_APPLICATION_ERROR(-20091, 'DEPOSIT_ACCOUNT_LIFECYCLE_EVENT is append-only');
END;
/

COMMENT ON TABLE DPS2.DEPOSIT_ACCOUNT_LIFECYCLE_EVENT IS
'Append-only Account Operations lifecycle history. Phase 9 supports CREATE, ACTIVATE and CLOSE.';

COMMIT;

PROMPT Phase 9 verification
SELECT CONSTRAINT_NAME, STATUS, SEARCH_CONDITION
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME='DEPOSIT_ACCOUNT_LIFECYCLE_EVENT'
   AND CONSTRAINT_NAME='CK_DEP_ACCT_EVT_TYPE';

SELECT TRIGGER_NAME, STATUS
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME='TRG_DEP_ACCT_EVT_APPEND_ONLY';
