package com.behsazan.corebanking.deposit.account.waved.application;

import com.behsazan.corebanking.deposit.account.error.DepositAccountNotFoundException;
import com.behsazan.corebanking.deposit.account.transaction.application.DepositTransactionService;
import com.behsazan.corebanking.deposit.account.transaction.domain.DepositTransactionModels.ReversalRequest;
import com.behsazan.corebanking.deposit.account.waved.domain.DepositAccountWaveDModels.*;
import com.behsazan.corebanking.deposit.account.waved.oracle.DepositAccountWaveDRepository;
import com.behsazan.corebanking.deposit.account.waved.oracle.DepositAccountWaveDRepository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.util.*;

@Service
public class DepositAccountWaveDService {
    private static final Set<String> RECON_TYPES=Set.of("BALANCE","TRANSACTION","PROFIT","FEE","TAX","SUSPENSE");
    private static final Set<String> EXC_TYPES=Set.of("INCOMPLETE_TRANSACTION","DUPLICATE_TRANSACTION","RECONCILIATION","PROFIT","FEE","TAX");
    private static final Set<String> EXC_REASONS=Set.of("DATA_MISMATCH","DUPLICATE_POSTING","MISSING_REFERENCE","BALANCE_DIFFERENCE","RULE_VIOLATION","SYSTEM_ERROR");
    private static final Set<String> CORR_TYPES=Set.of("REVERSAL","CORRECTION","BACKDATED_CORRECTION","DUPLICATE_CANCEL");
    private static final Set<String> CORR_REASONS=Set.of("CUSTOMER_COMPLAINT","OPERATOR_ERROR","DUPLICATE_POSTING","SYSTEM_ERROR","ACCOUNTING_ADJUSTMENT","REGULATORY_ORDER");
    private final DepositAccountWaveDRepository repository; private final DepositTransactionService transactions;
    public DepositAccountWaveDService(DepositAccountWaveDRepository repository,DepositTransactionService transactions){this.repository=repository;this.transactions=transactions;}

    @Transactional(readOnly=true) public WaveDView get(long accountId){requireAccount(accountId);return view(accountId);}

    @Transactional public WaveDView startReconciliation(long accountId,ReconciliationRunRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Reconciliation Run الزامی است.");String type=upper(required(r.reconciliationTypeCode(),"RECONCILIATION_TYPE_CODE"));if(!RECON_TYPES.contains(type))throw new IllegalArgumentException("RECONCILIATION_TYPE_CODE نامعتبر است.");LocalDate bd=r.businessDate()==null?LocalDate.now():r.businessDate();String src=upper(required(r.sourceSystemCode(),"SOURCE_SYSTEM_CODE")),target=upper(required(r.targetLedgerCode(),"TARGET_LEDGER_CODE"));String h=hash("RECON_RUN|"+accountId+"|"+bd+"|"+type+"|"+src+"|"+target);if(replayOrClaim(idem,accountId,"RECONCILIATION_RUN",h,actor,corr))return view(accountId);long id=repository.next("SEQ_DEPOSIT_RECONCILIATION_RUN");repository.insertReconRun(id,bd,type,src,target,actor);repository.completeIdempotency(idem,"RECONRUN:"+id);return view(accountId);}
    @Transactional public WaveDView addReconciliationItem(long accountId,long runId,ReconciliationItemRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Reconciliation Item الزامی است.");BigDecimal sa=r.sourceAmount()==null?BigDecimal.ZERO:r.sourceAmount(),ta=r.targetAmount()==null?BigDecimal.ZERO:r.targetAmount();BigDecimal diff=sa.subtract(ta);String match=diff.signum()==0?"MATCHED":"MISMATCHED",dtype=diff.signum()==0?null:upper(Optional.ofNullable(r.discrepancyTypeCode()).orElse("BALANCE_DIFFERENCE")),sev=upper(Optional.ofNullable(r.severityCode()).orElse("MEDIUM"));String h=hash("RECON_ITEM|"+accountId+"|"+runId+"|"+r.sourceReference()+"|"+r.targetReference()+"|"+sa+"|"+ta);if(replayOrClaim(idem,accountId,"RECONCILIATION_ITEM",h,actor,corr))return view(accountId);long item=repository.next("SEQ_DEPOSIT_RECONCILIATION_ITEM");repository.insertReconItem(item,runId,accountId,trim(r.sourceReference()),trim(r.targetReference()),sa,ta,match,dtype,actor);if(diff.signum()!=0){long d=repository.next("SEQ_DEPOSIT_DISCREPANCY");repository.insertDiscrepancy(d,item,dtype,sa,ta,sev,actor);long s=repository.next("SEQ_DEPOSIT_SUSPENSE_OPEN_ITEM");repository.insertSuspense(s,accountId,"DPS2_RECON_SUSPENSE","RECON-ITEM-"+item,diff.abs(),repository.accountCurrency(accountId),null,actor);}repository.completeReconRun(runId,actor);repository.completeIdempotency(idem,"RECONITEM:"+item);return view(accountId);}

    @Transactional public WaveDView openException(long accountId,ExceptionRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Exception Case الزامی است.");String type=upper(required(r.exceptionTypeCode(),"EXCEPTION_TYPE_CODE")),reason=upper(required(r.reasonCode(),"REASON_CODE")),severity=upper(required(r.severityCode(),"SEVERITY_CODE")),queue=upper(required(r.queueCode(),"QUEUE_CODE"));if(!EXC_TYPES.contains(type)||!EXC_REASONS.contains(reason))throw new IllegalArgumentException("Exception type/reason نامعتبر است.");String h=hash("EXCEPTION|"+accountId+"|"+r.transactionId()+"|"+type+"|"+reason+"|"+queue);if(replayOrClaim(idem,accountId,"EXCEPTION_OPEN",h,actor,corr))return view(accountId);long id=repository.next("SEQ_DEPOSIT_EXCEPTION_CASE");repository.insertException(id,accountId,r.transactionId(),type,reason,severity,queue,r.slaDueAt(),actor);repository.insertAssignment(repository.next("SEQ_DEPOSIT_EXCEPTION_ASSIGNMENT"),id,queue,null,r.slaDueAt(),actor);repository.completeIdempotency(idem,"EXCEPTION:"+id);return view(accountId);}
    @Transactional public WaveDView referDiscrepancy(long accountId,long discrepancyId,ExceptionRequest r,String actor,String corr,String idem){WaveDView v=openException(accountId,r,actor,corr,idem);long exceptionId=v.exceptions().cases().isEmpty()?0:v.exceptions().cases().get(0).exceptionCaseId();if(exceptionId>0)repository.linkDiscrepancy(discrepancyId,exceptionId,actor);return view(accountId);}
    @Transactional public WaveDView assignException(long accountId,long exceptionId,AssignmentRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Assignment الزامی است.");String h=hash("EXC_ASSIGN|"+accountId+"|"+exceptionId+"|"+r.queueCode()+"|"+r.assigneeReference());if(replayOrClaim(idem,accountId,"EXCEPTION_ASSIGN",h,actor,corr))return view(accountId);repository.insertAssignment(repository.next("SEQ_DEPOSIT_EXCEPTION_ASSIGNMENT"),exceptionId,upper(required(r.queueCode(),"QUEUE_CODE")),trim(r.assigneeReference()),r.slaDueAt(),actor);repository.completeIdempotency(idem,"EXCASSIGN:"+exceptionId);return view(accountId);}
    @Transactional public WaveDView requestCorrection(long accountId,CorrectionRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Correction Request الزامی است.");String type=upper(required(r.correctionTypeCode(),"CORRECTION_TYPE_CODE")),reason=upper(required(r.reasonCode(),"REASON_CODE")),approver=required(r.approverUserId(),"APPROVER_USER_ID");if(!CORR_TYPES.contains(type)||!CORR_REASONS.contains(reason))throw new IllegalArgumentException("Correction type/reason نامعتبر است.");if(actor.equalsIgnoreCase(approver))throw new IllegalArgumentException("Maker و Approver باید متفاوت باشند.");if("REVERSAL".equals(type)&&(r.originalTransactionId()==null||!repository.postedTransaction(accountId,r.originalTransactionId())))throw new IllegalArgumentException("REVERSAL فقط برای تراکنش POSTED همین حساب مجاز است.");LocalDate ed=r.requestedEffectiveDate()==null?LocalDate.now():r.requestedEffectiveDate();String h=hash("CORR_REQ|"+accountId+"|"+r.originalTransactionId()+"|"+r.exceptionCaseId()+"|"+type+"|"+reason+"|"+ed+"|"+approver);if(replayOrClaim(idem,accountId,"CORRECTION_REQUEST",h,actor,corr))return view(accountId);long id=repository.next("SEQ_DEPOSIT_CORRECTION_REQUEST");repository.insertCorrectionRequest(id,accountId,r.originalTransactionId(),r.exceptionCaseId(),type,reason,ed,actor,actor);repository.insertCorrectionAuthorization(repository.next("SEQ_DEPOSIT_CORRECTION_AUTHORIZATION"),id,approver,actor);repository.completeIdempotency(idem,"CORRREQ:"+id);return view(accountId);}
    @Transactional public WaveDView approveCorrection(long accountId,long correctionId,String actor,String corr,String idem){requireAccount(accountId);String h=hash("CORR_APPROVE|"+accountId+"|"+correctionId+"|"+actor);if(replayOrClaim(idem,accountId,"CORRECTION_APPROVE",h,actor,corr))return view(accountId);CorrectionLock c=repository.correction(accountId,correctionId);if(c==null||!"PENDING_APPROVAL".equals(c.status())||!"PENDING".equals(c.decision())||!actor.equals(c.approver()))throw new IllegalArgumentException("Correction/Approver معتبر نیست.");if(repository.approveCorrection(c,actor)!=1)throw new IllegalStateException("Correction همزمان تغییر کرده است.");repository.completeIdempotency(idem,"CORRAPPROVED:"+correctionId);return view(accountId);}
    @Transactional public WaveDView executeCorrection(long accountId,long correctionId,String actor,String corr,String idem){requireAccount(accountId);String h=hash("CORR_EXEC|"+accountId+"|"+correctionId);if(replayOrClaim(idem,accountId,"CORRECTION_EXECUTE",h,actor,corr))return view(accountId);CorrectionLock c=repository.correction(accountId,correctionId);if(c==null||!"APPROVED".equals(c.status()))throw new IllegalArgumentException("Correction تأییدشده یافت نشد.");if(!"REVERSAL".equals(c.type()))throw new IllegalArgumentException("اجرای مالی این Prototype فعلاً فقط REVERSAL را به Step 05 واگذار می‌کند؛ سایر Correctionها نیازمند instruction مالی مستقل هستند.");var result=transactions.reverse(accountId,Objects.requireNonNull(c.originalTransactionId()),new ReversalRequest("CORRECTION_REQUEST"),actor,corr,idem+"-TXREV");long corrective=result.transaction().transaction().transactionId();BigDecimal amount=repository.transactionAmount(c.originalTransactionId());long entry=repository.next("SEQ_DEPOSIT_CORRECTION_ENTRY");repository.insertCorrectionEntry(entry,correctionId,c.originalTransactionId(),corrective,"REVERSAL",c.effectiveDate(),amount,"DPS2-CORR-"+entry,"CORRECTION_REQUEST:"+correctionId,actor);repository.completeIdempotency(idem,"CORRENTRY:"+entry);return view(accountId);}
    @Transactional public WaveDView rootCause(long accountId,long exceptionId,RootCauseRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Root Cause Analysis الزامی است.");String h=hash("RCA|"+accountId+"|"+exceptionId+"|"+r.rootCauseCode()+"|"+r.description());if(replayOrClaim(idem,accountId,"ROOT_CAUSE",h,actor,corr))return view(accountId);repository.upsertRootCause(repository.next("SEQ_DEPOSIT_ROOT_CAUSE_ANALYSIS"),exceptionId,upper(required(r.rootCauseCode(),"ROOT_CAUSE_CODE")),required(r.description(),"ROOT_CAUSE_DESCRIPTION"),trim(r.correctiveAction()),trim(r.preventiveAction()),trim(r.ownerReference()),r.targetDate(),actor);repository.completeIdempotency(idem,"RCA:"+exceptionId);return view(accountId);}

    @Transactional public WaveDView configureCorrespondent(long accountId,CorrespondentRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Correspondent configuration الزامی است.");String type=upper(required(r.accountTypeCode(),"ACCOUNT_TYPE_CODE")),freq=upper(required(r.reconciliationFrequencyCode(),"RECONCILIATION_FREQUENCY_CODE"));if(!Set.of("NOSTRO","VOSTRO").contains(type)||!Set.of("INTRADAY","DAILY","WEEKLY").contains(freq))throw new IllegalArgumentException("Correspondent type/frequency نامعتبر است.");BigDecimal tol=r.toleranceAmount()==null?BigDecimal.ZERO:r.toleranceAmount();if(tol.signum()<0)throw new IllegalArgumentException("TOLERANCE_AMOUNT منفی مجاز نیست.");String cur=upper(required(r.settlementCurrencyCode(),"SETTLEMENT_CURRENCY_CODE"));String h=hash("CORRESPONDENT|"+accountId+"|"+type+"|"+r.correspondentBankPartyId()+"|"+r.externalAccountReference()+"|"+cur+"|"+freq);if(replayOrClaim(idem,accountId,"CORRESPONDENT_CONFIG",h,actor,corr))return view(accountId);repository.upsertCorrespondent(repository.next("SEQ_CORRESPONDENT_ACCOUNT_EXTENSION"),repository.next("SEQ_CORRESPONDENT_RECONCILIATION_PROFILE"),accountId,type,r.correspondentBankPartyId(),upper(trim(r.correspondentBic())),required(r.externalAccountReference(),"EXTERNAL_ACCOUNT_REFERENCE"),cur,upper(required(r.statementSourceCode(),"STATEMENT_SOURCE_CODE")),freq,r.autoMatchAllowed()==null||r.autoMatchAllowed(),tol,actor);repository.completeIdempotency(idem,"CORRESPONDENT:"+accountId);return view(accountId);}

    @Transactional public WaveDView enrollReward(long accountId,RewardEnrollmentRequest r,String actor,String corr,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Reward Enrollment الزامی است.");if(!repository.programEligible(r.programId(),accountId))throw new IllegalArgumentException("Reward Program فعال/مجاز برای این حساب نیست.");String h=hash("REWARD_ENROLL|"+accountId+"|"+r.programId()+"|"+r.consentReference());if(replayOrClaim(idem,accountId,"REWARD_ENROLL",h,actor,corr))return view(accountId);repository.insertEnrollment(repository.next("SEQ_DEPOSIT_REWARD_ENROLLMENT"),r.programId(),accountId,trim(r.consentReference()),actor);repository.completeIdempotency(idem,"REWARDENROLL:"+r.programId());return view(accountId);}

    private WaveDView view(long accountId){return new WaveDView(new ReconciliationView(repository.reconRuns(accountId),repository.reconItems(accountId),repository.discrepancies(accountId),repository.suspense(accountId)),new ExceptionView(repository.exceptionCases(accountId),repository.assignments(accountId),repository.corrections(accountId),repository.authorizations(accountId),repository.correctionEntries(accountId),repository.rootCauses(accountId)),new CorrespondentView(repository.correspondents(accountId)),new RewardView(repository.activePrograms(repository.currentProductVersion(accountId)),repository.enrollments(accountId),repository.lotteryEntries(accountId),repository.lotteryWinners(accountId)));}
    private void requireAccount(long id){if(!repository.accountExists(id))throw new DepositAccountNotFoundException("حساب سپرده یافت نشد: "+id);}
    private boolean replayOrClaim(String key,long accountId,String operation,String payloadHash,String actor,String correlation){String k=required(key,"X-Idempotency-Key");var row=repository.idempotency(k);if(row.isPresent()){IdemRow x=row.get();if(!operation.equals(x.operation())||!payloadHash.equals(x.payloadHash())||!Objects.equals(accountId,x.accountId()))throw new IllegalArgumentException("Idempotency-Key با payload قبلی سازگار نیست.");if("COMPLETED".equals(x.status()))return true;throw new IllegalStateException("درخواست با Idempotency-Key در حال پردازش است.");}repository.claimIdempotency(repository.next("SEQ_DEPOSIT_OPERATION_IDEMPOTENCY"),k,accountId,operation,payloadHash,actor,correlation);return false;}
    private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" الزامی است.");return v.trim();}
    private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}
    private static String upper(String v){return v==null?null:v.trim().toUpperCase(Locale.ROOT);}
    private static String hash(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
