-- Generated from Party_Customer_Reference_Data_Interactive_Forms_FA.html
-- Phase 1: Identity and Party + REF_LEGAL_CAPACITY
-- Target schema: CIF
-- Tablespace: TS_CIF; PK indexes: ITS_CIF

PROMPT Creating CIF.REF_ASSIGNMENT_REASON
CREATE TABLE CIF.REF_ASSIGNMENT_REASON (
  ASSIGNMENT_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ASSIGNMENT_REASON PRIMARY KEY (ASSIGNMENT_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ASSIGNMENT_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ASSIGNMENT_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ASSIGNMENT_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ASSIGNMENT_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUTHORITY_SCOPE
CREATE TABLE CIF.REF_AUTHORITY_SCOPE (
  AUTHORITY_SCOPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUTHORITY_SCOPE PRIMARY KEY (AUTHORITY_SCOPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUTHORITY_SCOPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUTHORITY_SCOPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUTHORITY_SCOPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUTHORITY_SCOPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUTHORITY_TYPE
CREATE TABLE CIF.REF_AUTHORITY_TYPE (
  AUTHORITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUTHORITY_TYPE PRIMARY KEY (AUTHORITY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUTHORITY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUTHORITY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUTHORITY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUTHORITY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CLASSIFICATION_TYPE
CREATE TABLE CIF.REF_CLASSIFICATION_TYPE (
  CLASSIFICATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CLASSIFICATION_TYPE PRIMARY KEY (CLASSIFICATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CLASSIFICATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CLASSIFICATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CLASSIFICATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CLASSIFICATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CLASSIFICATION_VALUE
CREATE TABLE CIF.REF_CLASSIFICATION_VALUE (
  CLASSIFICATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  CLASSIFICATION_VALUE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CLASSIFICATION_VALUE PRIMARY KEY (CLASSIFICATION_TYPE_CODE, CLASSIFICATION_VALUE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CLASSIFICATION_VALUE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CLASSIFICATION_VALUE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CLASSIFICATION_VALUE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CLASSIFICATION_VALUE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTEXT_TYPE
CREATE TABLE CIF.REF_CONTEXT_TYPE (
  CONTEXT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTEXT_TYPE PRIMARY KEY (CONTEXT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTEXT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTEXT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTEXT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTEXT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTROL_BASIS
CREATE TABLE CIF.REF_CONTROL_BASIS (
  CONTROL_BASIS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTROL_BASIS PRIMARY KEY (CONTROL_BASIS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTROL_BASIS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTROL_BASIS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTROL_BASIS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTROL_BASIS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DATA_QUALITY_STATUS
CREATE TABLE CIF.REF_DATA_QUALITY_STATUS (
  DATA_QUALITY_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DATA_QUALITY_STATUS PRIMARY KEY (DATA_QUALITY_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DATA_QUALITY_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DATA_QUALITY_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DATA_QUALITY_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DATA_QUALITY_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DATA_SOURCE
CREATE TABLE CIF.REF_DATA_SOURCE (
  DATA_SOURCE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DATA_SOURCE PRIMARY KEY (DATA_SOURCE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DATA_SOURCE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DATA_SOURCE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DATA_SOURCE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DATA_SOURCE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DOCUMENT_TYPE
CREATE TABLE CIF.REF_DOCUMENT_TYPE (
  DOCUMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DOCUMENT_TYPE PRIMARY KEY (DOCUMENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DOCUMENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DOCUMENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DOCUMENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DOCUMENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_EXTERNAL_PROVIDER
CREATE TABLE CIF.REF_EXTERNAL_PROVIDER (
  EXTERNAL_PROVIDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_EXTERNAL_PROVIDER PRIMARY KEY (EXTERNAL_PROVIDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_EXTERNAL_PROVIDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_EXTERNAL_PROVIDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_EXTERNAL_PROVIDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_EXTERNAL_PROVIDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GENDER
CREATE TABLE CIF.REF_GENDER (
  GENDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GENDER PRIMARY KEY (GENDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GENDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GENDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GENDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GENDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GROUP_MEMBER_ROLE
CREATE TABLE CIF.REF_GROUP_MEMBER_ROLE (
  MEMBER_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GROUP_MEMBER_ROLE PRIMARY KEY (MEMBER_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GROUP_MEMBER_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GROUP_TYPE
CREATE TABLE CIF.REF_GROUP_TYPE (
  GROUP_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GROUP_TYPE PRIMARY KEY (GROUP_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GROUP_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GROUP_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GROUP_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GROUP_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_IDENTIFIER_TYPE
CREATE TABLE CIF.REF_IDENTIFIER_TYPE (
  IDENTIFIER_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_IDENTIFIER_TYPE PRIMARY KEY (IDENTIFIER_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_IDENTIFIER_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_IDENTIFIER_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_IDENTIFIER_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_IDENTIFIER_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ISSUING_AUTHORITY
CREATE TABLE CIF.REF_ISSUING_AUTHORITY (
  ISSUING_AUTHORITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ISSUING_AUTHORITY PRIMARY KEY (ISSUING_AUTHORITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ISSUING_AUTHORITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ISSUING_AUTHORITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ISSUING_AUTHORITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ISSUING_AUTHORITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LIFE_STATUS
CREATE TABLE CIF.REF_LIFE_STATUS (
  LIFE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LIFE_STATUS PRIMARY KEY (LIFE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LIFE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LIFE_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LIFE_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LIFE_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LIMIT_TYPE
CREATE TABLE CIF.REF_LIMIT_TYPE (
  LIMIT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LIMIT_TYPE PRIMARY KEY (LIMIT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LIMIT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LIMIT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LIMIT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LIMIT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_MARITAL_STATUS
CREATE TABLE CIF.REF_MARITAL_STATUS (
  MARITAL_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_MARITAL_STATUS PRIMARY KEY (MARITAL_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_MARITAL_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_MARITAL_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_MARITAL_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_MARITAL_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_NAME_TYPE
CREATE TABLE CIF.REF_NAME_TYPE (
  NAME_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_NAME_TYPE PRIMARY KEY (NAME_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_NAME_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_NAME_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_NAME_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_NAME_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_PURPOSE
CREATE TABLE CIF.REF_PARTY_CONSENT_PURPOSE (
  PARTY_CONSENT_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_PURPOSE PRIMARY KEY (PARTY_CONSENT_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_STATUS
CREATE TABLE CIF.REF_PARTY_CONSENT_STATUS (
  CONSENT_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_STATUS PRIMARY KEY (CONSENT_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_TYPE
CREATE TABLE CIF.REF_PARTY_CONSENT_TYPE (
  CONSENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_TYPE PRIMARY KEY (CONSENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_LIFECYCLE_STATUS
CREATE TABLE CIF.REF_PARTY_LIFECYCLE_STATUS (
  LIFECYCLE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_LIFECYCLE_STATUS PRIMARY KEY (LIFECYCLE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_STATUS_REASON
CREATE TABLE CIF.REF_PARTY_STATUS_REASON (
  REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_STATUS_REASON PRIMARY KEY (REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_STATUS_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_STATUS_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_STATUS_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_STATUS_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_TYPE
CREATE TABLE CIF.REF_PARTY_TYPE (
  PARTY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_TYPE PRIMARY KEY (PARTY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESIDENCE_STATUS
CREATE TABLE CIF.REF_RESIDENCE_STATUS (
  RESIDENCE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESIDENCE_STATUS PRIMARY KEY (RESIDENCE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESIDENCE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESIDENCE_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESIDENCE_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESIDENCE_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ROLE_TYPE
CREATE TABLE CIF.REF_ROLE_TYPE (
  ROLE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ROLE_TYPE PRIMARY KEY (ROLE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ROLE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ROLE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ROLE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ROLE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SIGNING_RULE
CREATE TABLE CIF.REF_SIGNING_RULE (
  SIGNING_RULE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SIGNING_RULE PRIMARY KEY (SIGNING_RULE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SIGNING_RULE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SIGNING_RULE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SIGNING_RULE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SIGNING_RULE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_SYSTEM
CREATE TABLE CIF.REF_SOURCE_SYSTEM (
  SOURCE_SYSTEM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_SYSTEM PRIMARY KEY (SOURCE_SYSTEM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_SYSTEM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_SYSTEM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_SYSTEM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_SYSTEM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SPECIMEN_TYPE
CREATE TABLE CIF.REF_SPECIMEN_TYPE (
  SPECIMEN_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SPECIMEN_TYPE PRIMARY KEY (SPECIMEN_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SPECIMEN_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SPECIMEN_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SPECIMEN_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SPECIMEN_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LEGAL_CAPACITY
CREATE TABLE CIF.REF_LEGAL_CAPACITY (
  LEGAL_CAPACITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LEGAL_CAPACITY PRIMARY KEY (LEGAL_CAPACITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LEGAL_CAPACITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LEGAL_CAPACITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LEGAL_CAPACITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LEGAL_CAPACITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

ALTER TABLE CIF.REF_CLASSIFICATION_VALUE ADD CONSTRAINT FK_CLASSIFICATION_VALUE_CLASSIFICATION_TYPE FOREIGN KEY (CLASSIFICATION_TYPE_CODE) REFERENCES CIF.REF_CLASSIFICATION_TYPE (CLASSIFICATION_TYPE_CODE);


PROMPT Creating CIF.REF_TENURE_TYPE
CREATE TABLE CIF.REF_TENURE_TYPE (
  TENURE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_TENURE_TYPE PRIMARY KEY (TENURE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_TENURE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_TENURE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_TENURE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_TENURE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
