-- Generated from Party_Customer_Reference_Data_Interactive_Forms_FA.html
-- Phase 1: Identity and Party + REF_LEGAL_CAPACITY
-- Target schema: CIF
-- Tablespace: TS_CIF; PK indexes: ITS_CIF

PROMPT Creating CIF.REF_ASSIGNMENT_REASON
CREATE TABLE CIF.REF_ASSIGNMENT_REASON (
  ASSIGNMENT_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ASSIGNMENT_REASON PRIMARY KEY (ASSIGNMENT_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ASSIGNMENT_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ASSIGNMENT_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ASSIGNMENT_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ASSIGNMENT_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUTHORITY_SCOPE
CREATE TABLE CIF.REF_AUTHORITY_SCOPE (
  AUTHORITY_SCOPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUTHORITY_SCOPE PRIMARY KEY (AUTHORITY_SCOPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUTHORITY_SCOPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUTHORITY_SCOPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUTHORITY_SCOPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUTHORITY_SCOPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUTHORITY_TYPE
CREATE TABLE CIF.REF_AUTHORITY_TYPE (
  AUTHORITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUTHORITY_TYPE PRIMARY KEY (AUTHORITY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUTHORITY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUTHORITY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUTHORITY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUTHORITY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUTHORITY_DOCUMENT_TYPE
CREATE TABLE CIF.REF_AUTHORITY_DOCUMENT_TYPE (
  AUTHORITY_DOCUMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUTHORITY_DOCUMENT_TYPE PRIMARY KEY (AUTHORITY_DOCUMENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUTHORITY_DOC_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUTHORITY_DOC_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUTHORITY_DOC_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUTHORITY_DOC_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CLASSIFICATION_TYPE
CREATE TABLE CIF.REF_CLASSIFICATION_TYPE (
  CLASSIFICATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CLASSIFICATION_TYPE PRIMARY KEY (CLASSIFICATION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CLASSIFICATION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CLASSIFICATION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CLASSIFICATION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CLASSIFICATION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CLASSIFICATION_VALUE
CREATE TABLE CIF.REF_CLASSIFICATION_VALUE (
  CLASSIFICATION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  CLASSIFICATION_VALUE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CLASSIFICATION_VALUE PRIMARY KEY (CLASSIFICATION_TYPE_CODE, CLASSIFICATION_VALUE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CLASSIFICATION_VALUE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CLASSIFICATION_VALUE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CLASSIFICATION_VALUE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CLASSIFICATION_VALUE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTEXT_TYPE
CREATE TABLE CIF.REF_CONTEXT_TYPE (
  CONTEXT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTEXT_TYPE PRIMARY KEY (CONTEXT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTEXT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTEXT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTEXT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTEXT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_CONTROL_BASIS
CREATE TABLE CIF.REF_CONTROL_BASIS (
  CONTROL_BASIS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONTROL_BASIS PRIMARY KEY (CONTROL_BASIS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_CONTROL_BASIS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CONTROL_BASIS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_CONTROL_BASIS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_CONTROL_BASIS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DATA_QUALITY_STATUS
CREATE TABLE CIF.REF_DATA_QUALITY_STATUS (
  DATA_QUALITY_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DATA_QUALITY_STATUS PRIMARY KEY (DATA_QUALITY_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DATA_QUALITY_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DATA_QUALITY_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DATA_QUALITY_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DATA_QUALITY_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DATA_SOURCE
CREATE TABLE CIF.REF_DATA_SOURCE (
  DATA_SOURCE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DATA_SOURCE PRIMARY KEY (DATA_SOURCE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DATA_SOURCE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DATA_SOURCE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DATA_SOURCE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DATA_SOURCE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DOCUMENT_TYPE
CREATE TABLE CIF.REF_DOCUMENT_TYPE (
  DOCUMENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DOCUMENT_TYPE PRIMARY KEY (DOCUMENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DOCUMENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DOCUMENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DOCUMENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DOCUMENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_EXTERNAL_PROVIDER
CREATE TABLE CIF.REF_EXTERNAL_PROVIDER (
  EXTERNAL_PROVIDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_EXTERNAL_PROVIDER PRIMARY KEY (EXTERNAL_PROVIDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_EXTERNAL_PROVIDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_EXTERNAL_PROVIDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_EXTERNAL_PROVIDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_EXTERNAL_PROVIDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GENDER
CREATE TABLE CIF.REF_GENDER (
  GENDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GENDER PRIMARY KEY (GENDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GENDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GENDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GENDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GENDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GROUP_MEMBER_ROLE
CREATE TABLE CIF.REF_GROUP_MEMBER_ROLE (
  MEMBER_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GROUP_MEMBER_ROLE PRIMARY KEY (MEMBER_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GROUP_MEMBER_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GROUP_MEMBER_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_GROUP_TYPE
CREATE TABLE CIF.REF_GROUP_TYPE (
  GROUP_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_GROUP_TYPE PRIMARY KEY (GROUP_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_GROUP_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_GROUP_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_GROUP_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_GROUP_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_IDENTIFIER_TYPE
CREATE TABLE CIF.REF_IDENTIFIER_TYPE (
  IDENTIFIER_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_IDENTIFIER_TYPE PRIMARY KEY (IDENTIFIER_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_IDENTIFIER_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_IDENTIFIER_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_IDENTIFIER_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_IDENTIFIER_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ISSUING_AUTHORITY
CREATE TABLE CIF.REF_ISSUING_AUTHORITY (
  ISSUING_AUTHORITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ISSUING_AUTHORITY PRIMARY KEY (ISSUING_AUTHORITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ISSUING_AUTHORITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ISSUING_AUTHORITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ISSUING_AUTHORITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ISSUING_AUTHORITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LIFE_STATUS
CREATE TABLE CIF.REF_LIFE_STATUS (
  LIFE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LIFE_STATUS PRIMARY KEY (LIFE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LIFE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LIFE_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LIFE_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LIFE_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LIMIT_TYPE
CREATE TABLE CIF.REF_LIMIT_TYPE (
  LIMIT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LIMIT_TYPE PRIMARY KEY (LIMIT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LIMIT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LIMIT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LIMIT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LIMIT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_MARITAL_STATUS
CREATE TABLE CIF.REF_MARITAL_STATUS (
  MARITAL_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_MARITAL_STATUS PRIMARY KEY (MARITAL_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_MARITAL_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_MARITAL_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_MARITAL_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_MARITAL_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_NAME_TYPE
CREATE TABLE CIF.REF_NAME_TYPE (
  NAME_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_NAME_TYPE PRIMARY KEY (NAME_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_NAME_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_NAME_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_NAME_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_NAME_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_PURPOSE
CREATE TABLE CIF.REF_PARTY_CONSENT_PURPOSE (
  PARTY_CONSENT_PURPOSE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_PURPOSE PRIMARY KEY (PARTY_CONSENT_PURPOSE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_PURPOSE_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_STATUS
CREATE TABLE CIF.REF_PARTY_CONSENT_STATUS (
  CONSENT_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_STATUS PRIMARY KEY (CONSENT_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_CONSENT_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_CONSENT_TYPE
CREATE TABLE CIF.REF_PARTY_CONSENT_TYPE (
  CONSENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_CONSENT_TYPE PRIMARY KEY (CONSENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_CONSENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_CONSENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_LIFECYCLE_STATUS
CREATE TABLE CIF.REF_PARTY_LIFECYCLE_STATUS (
  LIFECYCLE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_LIFECYCLE_STATUS PRIMARY KEY (LIFECYCLE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_03 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_LIFECYCLE_STATUS_04 CHECK (SORT_ORDER >= 0)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_STATUS_REASON
CREATE TABLE CIF.REF_PARTY_STATUS_REASON (
  REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_STATUS_REASON PRIMARY KEY (REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_STATUS_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_STATUS_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_STATUS_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_STATUS_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PARTY_TYPE
CREATE TABLE CIF.REF_PARTY_TYPE (
  PARTY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PARTY_TYPE PRIMARY KEY (PARTY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PARTY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PARTY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PARTY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PARTY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESIDENCE_STATUS
CREATE TABLE CIF.REF_RESIDENCE_STATUS (
  RESIDENCE_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESIDENCE_STATUS PRIMARY KEY (RESIDENCE_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESIDENCE_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESIDENCE_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESIDENCE_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESIDENCE_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ROLE_TYPE
CREATE TABLE CIF.REF_ROLE_TYPE (
  ROLE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ROLE_TYPE PRIMARY KEY (ROLE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ROLE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ROLE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ROLE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ROLE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SIGNING_RULE
CREATE TABLE CIF.REF_SIGNING_RULE (
  SIGNING_RULE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SIGNING_RULE PRIMARY KEY (SIGNING_RULE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SIGNING_RULE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SIGNING_RULE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SIGNING_RULE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SIGNING_RULE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_SYSTEM
CREATE TABLE CIF.REF_SOURCE_SYSTEM (
  SOURCE_SYSTEM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_SYSTEM PRIMARY KEY (SOURCE_SYSTEM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_SYSTEM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_SYSTEM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_SYSTEM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_SYSTEM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SPECIMEN_TYPE
CREATE TABLE CIF.REF_SPECIMEN_TYPE (
  SPECIMEN_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SPECIMEN_TYPE PRIMARY KEY (SPECIMEN_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SPECIMEN_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SPECIMEN_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SPECIMEN_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SPECIMEN_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_LEGAL_CAPACITY
CREATE TABLE CIF.REF_LEGAL_CAPACITY (
  LEGAL_CAPACITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_LEGAL_CAPACITY PRIMARY KEY (LEGAL_CAPACITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_LEGAL_CAPACITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_LEGAL_CAPACITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_LEGAL_CAPACITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_LEGAL_CAPACITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

ALTER TABLE CIF.REF_CLASSIFICATION_VALUE ADD CONSTRAINT FK_CLASSIFICATION_VALUE_CLASSIFICATION_TYPE FOREIGN KEY (CLASSIFICATION_TYPE_CODE) REFERENCES CIF.REF_CLASSIFICATION_TYPE (CLASSIFICATION_TYPE_CODE);


PROMPT Creating CIF.REF_TENURE_TYPE
CREATE TABLE CIF.REF_TENURE_TYPE (
  TENURE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_TENURE_TYPE PRIMARY KEY (TENURE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_TENURE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_TENURE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_TENURE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_TENURE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;


-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.ASSIGNMENT_REASON_CODE IS 'کد دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.NAME_FA IS 'عنوان فارسی دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.NAME_EN IS 'عنوان انگلیسی دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.DESCRIPTION_FA IS 'توضیحات فارسی دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.SORT_ORDER IS 'ترتیب نمایش دلیل تخصیص در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.IS_ACTIVE IS 'نشانگر فعال بودن دلیل تخصیص؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.PARENT_CODE IS 'کد والد دلیل تخصیص در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.VALID_FROM IS 'تاریخ شروع اعتبار دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.VALID_TO IS 'تاریخ پایان اعتبار دلیل تخصیص';
COMMENT ON COLUMN CIF.REF_ASSIGNMENT_REASON.RECORD_VERSION IS 'شماره نسخه رکورد دلیل تخصیص برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.AUTHORITY_SCOPE_CODE IS 'کد دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.NAME_FA IS 'عنوان فارسی دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.NAME_EN IS 'عنوان انگلیسی دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.DESCRIPTION_FA IS 'توضیحات فارسی دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.SORT_ORDER IS 'ترتیب نمایش دامنه اختیار در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.IS_ACTIVE IS 'نشانگر فعال بودن دامنه اختیار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.PARENT_CODE IS 'کد والد دامنه اختیار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.VALID_FROM IS 'تاریخ شروع اعتبار دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.VALID_TO IS 'تاریخ پایان اعتبار دامنه اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_SCOPE.RECORD_VERSION IS 'شماره نسخه رکورد دامنه اختیار برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.AUTHORITY_TYPE_CODE IS 'کد نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.NAME_FA IS 'عنوان فارسی نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.NAME_EN IS 'عنوان انگلیسی نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع اختیار در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع اختیار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.PARENT_CODE IS 'کد والد نوع اختیار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع اختیار برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.CLASSIFICATION_TYPE_CODE IS 'کد نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.NAME_FA IS 'عنوان فارسی نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.NAME_EN IS 'عنوان انگلیسی نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع طبقه‌بندی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع طبقه‌بندی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.PARENT_CODE IS 'کد والد نوع طبقه‌بندی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع طبقه‌بندی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.CLASSIFICATION_TYPE_CODE IS 'نوع طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.CLASSIFICATION_VALUE_CODE IS 'کد مقدار طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.NAME_FA IS 'عنوان فارسی مقادیر طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.NAME_EN IS 'عنوان انگلیسی مقادیر طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.DESCRIPTION_FA IS 'توضیحات فارسی مقادیر طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.SORT_ORDER IS 'ترتیب نمایش مقادیر طبقه‌بندی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.IS_ACTIVE IS 'نشانگر فعال بودن مقادیر طبقه‌بندی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.PARENT_CODE IS 'کد والد مقادیر طبقه‌بندی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.VALID_FROM IS 'تاریخ شروع اعتبار مقادیر طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.VALID_TO IS 'تاریخ پایان اعتبار مقادیر طبقه‌بندی';
COMMENT ON COLUMN CIF.REF_CLASSIFICATION_VALUE.RECORD_VERSION IS 'شماره نسخه رکورد مقادیر طبقه‌بندی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.CONTEXT_TYPE_CODE IS 'کد نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.NAME_FA IS 'عنوان فارسی نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع زمینه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع زمینه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.PARENT_CODE IS 'کد والد نوع زمینه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع زمینه';
COMMENT ON COLUMN CIF.REF_CONTEXT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع زمینه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.CONTROL_BASIS_CODE IS 'کد مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.NAME_FA IS 'عنوان فارسی مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.NAME_EN IS 'عنوان انگلیسی مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.DESCRIPTION_FA IS 'توضیحات فارسی مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.SORT_ORDER IS 'ترتیب نمایش مبنای کنترل در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.IS_ACTIVE IS 'نشانگر فعال بودن مبنای کنترل؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.PARENT_CODE IS 'کد والد مبنای کنترل در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.VALID_FROM IS 'تاریخ شروع اعتبار مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.VALID_TO IS 'تاریخ پایان اعتبار مبنای کنترل';
COMMENT ON COLUMN CIF.REF_CONTROL_BASIS.RECORD_VERSION IS 'شماره نسخه رکورد مبنای کنترل برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.DATA_QUALITY_STATUS_CODE IS 'کد وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.NAME_FA IS 'عنوان فارسی وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت کیفیت داده در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت کیفیت داده؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.PARENT_CODE IS 'کد والد وضعیت کیفیت داده در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت کیفیت داده';
COMMENT ON COLUMN CIF.REF_DATA_QUALITY_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت کیفیت داده برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.DATA_SOURCE_CODE IS 'کد منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.NAME_FA IS 'عنوان فارسی منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.NAME_EN IS 'عنوان انگلیسی منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.DESCRIPTION_FA IS 'توضیحات فارسی منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.SORT_ORDER IS 'ترتیب نمایش منبع داده در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.IS_ACTIVE IS 'نشانگر فعال بودن منبع داده؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.PARENT_CODE IS 'کد والد منبع داده در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.VALID_FROM IS 'تاریخ شروع اعتبار منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.VALID_TO IS 'تاریخ پایان اعتبار منبع داده';
COMMENT ON COLUMN CIF.REF_DATA_SOURCE.RECORD_VERSION IS 'شماره نسخه رکورد منبع داده برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.DOCUMENT_TYPE_CODE IS 'کد نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.NAME_FA IS 'عنوان فارسی نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع مدرک در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع مدرک؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.PARENT_CODE IS 'کد والد نوع مدرک در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع مدرک';
COMMENT ON COLUMN CIF.REF_DOCUMENT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع مدرک برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.EXTERNAL_PROVIDER_CODE IS 'کد ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.NAME_FA IS 'عنوان فارسی ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.NAME_EN IS 'عنوان انگلیسی ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.DESCRIPTION_FA IS 'توضیحات فارسی ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.SORT_ORDER IS 'ترتیب نمایش ارائه‌دهنده خارجی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.IS_ACTIVE IS 'نشانگر فعال بودن ارائه‌دهنده خارجی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.PARENT_CODE IS 'کد والد ارائه‌دهنده خارجی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.VALID_FROM IS 'تاریخ شروع اعتبار ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.VALID_TO IS 'تاریخ پایان اعتبار ارائه‌دهنده خارجی';
COMMENT ON COLUMN CIF.REF_EXTERNAL_PROVIDER.RECORD_VERSION IS 'شماره نسخه رکورد ارائه‌دهنده خارجی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_GENDER.GENDER_CODE IS 'کد جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.NAME_FA IS 'عنوان فارسی جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.NAME_EN IS 'عنوان انگلیسی جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.DESCRIPTION_FA IS 'توضیحات فارسی جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.SORT_ORDER IS 'ترتیب نمایش جنسیت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_GENDER.IS_ACTIVE IS 'نشانگر فعال بودن جنسیت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_GENDER.PARENT_CODE IS 'کد والد جنسیت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_GENDER.VALID_FROM IS 'تاریخ شروع اعتبار جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.VALID_TO IS 'تاریخ پایان اعتبار جنسیت';
COMMENT ON COLUMN CIF.REF_GENDER.RECORD_VERSION IS 'شماره نسخه رکورد جنسیت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.MEMBER_ROLE_CODE IS 'کد نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.NAME_FA IS 'عنوان فارسی نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.NAME_EN IS 'عنوان انگلیسی نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.DESCRIPTION_FA IS 'توضیحات فارسی نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.SORT_ORDER IS 'ترتیب نمایش نقش عضو گروه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.IS_ACTIVE IS 'نشانگر فعال بودن نقش عضو گروه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.PARENT_CODE IS 'کد والد نقش عضو گروه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.VALID_FROM IS 'تاریخ شروع اعتبار نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.VALID_TO IS 'تاریخ پایان اعتبار نقش عضو گروه';
COMMENT ON COLUMN CIF.REF_GROUP_MEMBER_ROLE.RECORD_VERSION IS 'شماره نسخه رکورد نقش عضو گروه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.GROUP_TYPE_CODE IS 'کد نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.NAME_FA IS 'عنوان فارسی نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.NAME_EN IS 'عنوان انگلیسی نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع گروه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع گروه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.PARENT_CODE IS 'کد والد نوع گروه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع گروه';
COMMENT ON COLUMN CIF.REF_GROUP_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع گروه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.IDENTIFIER_TYPE_CODE IS 'کد نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.NAME_FA IS 'عنوان فارسی نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.NAME_EN IS 'عنوان انگلیسی نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع شناسه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع شناسه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.PARENT_CODE IS 'کد والد نوع شناسه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع شناسه';
COMMENT ON COLUMN CIF.REF_IDENTIFIER_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع شناسه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.ISSUING_AUTHORITY_CODE IS 'کد مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.NAME_FA IS 'عنوان فارسی مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.NAME_EN IS 'عنوان انگلیسی مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.DESCRIPTION_FA IS 'توضیحات فارسی مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.SORT_ORDER IS 'ترتیب نمایش مرجع صادرکننده در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.IS_ACTIVE IS 'نشانگر فعال بودن مرجع صادرکننده؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.PARENT_CODE IS 'کد والد مرجع صادرکننده در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.VALID_FROM IS 'تاریخ شروع اعتبار مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.VALID_TO IS 'تاریخ پایان اعتبار مرجع صادرکننده';
COMMENT ON COLUMN CIF.REF_ISSUING_AUTHORITY.RECORD_VERSION IS 'شماره نسخه رکورد مرجع صادرکننده برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.LIFE_STATUS_CODE IS 'کد وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.NAME_FA IS 'عنوان فارسی وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت حیات در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت حیات؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.PARENT_CODE IS 'کد والد وضعیت حیات در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت حیات';
COMMENT ON COLUMN CIF.REF_LIFE_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت حیات برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.LIMIT_TYPE_CODE IS 'کد نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.NAME_FA IS 'عنوان فارسی نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع حد در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع حد؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.PARENT_CODE IS 'کد والد نوع حد در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع حد';
COMMENT ON COLUMN CIF.REF_LIMIT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع حد برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.MARITAL_STATUS_CODE IS 'کد وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.NAME_FA IS 'عنوان فارسی وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت تأهل در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت تأهل؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.PARENT_CODE IS 'کد والد وضعیت تأهل در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت تأهل';
COMMENT ON COLUMN CIF.REF_MARITAL_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت تأهل برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.NAME_TYPE_CODE IS 'کد نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.NAME_FA IS 'عنوان فارسی نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.NAME_EN IS 'عنوان انگلیسی نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع نام در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع نام؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.PARENT_CODE IS 'کد والد نوع نام در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع نام';
COMMENT ON COLUMN CIF.REF_NAME_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع نام برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.PARTY_CONSENT_PURPOSE_CODE IS 'کد هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.NAME_FA IS 'عنوان فارسی هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.NAME_EN IS 'عنوان انگلیسی هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.DESCRIPTION_FA IS 'توضیحات فارسی هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.SORT_ORDER IS 'ترتیب نمایش هدف رضایت Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.IS_ACTIVE IS 'نشانگر فعال بودن هدف رضایت Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.PARENT_CODE IS 'کد والد هدف رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.VALID_FROM IS 'تاریخ شروع اعتبار هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.VALID_TO IS 'تاریخ پایان اعتبار هدف رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_PURPOSE.RECORD_VERSION IS 'شماره نسخه رکورد هدف رضایت Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.CONSENT_STATUS_CODE IS 'کد وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.NAME_FA IS 'عنوان فارسی وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت رضایت Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت رضایت Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.PARENT_CODE IS 'کد والد وضعیت رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت رضایت Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.CONSENT_TYPE_CODE IS 'کد نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.NAME_FA IS 'عنوان فارسی نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع رضایت Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع رضایت Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.PARENT_CODE IS 'کد والد نوع رضایت Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع رضایت Party';
COMMENT ON COLUMN CIF.REF_PARTY_CONSENT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع رضایت Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.LIFECYCLE_STATUS_CODE IS 'کد وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.NAME_FA IS 'عنوان فارسی وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت چرخه‌حیات Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت چرخه‌حیات Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.PARENT_CODE IS 'کد والد وضعیت چرخه‌حیات Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت چرخه‌حیات Party';
COMMENT ON COLUMN CIF.REF_PARTY_LIFECYCLE_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت چرخه‌حیات Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.REASON_CODE IS 'کد دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.NAME_FA IS 'عنوان فارسی دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.NAME_EN IS 'عنوان انگلیسی دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.DESCRIPTION_FA IS 'توضیحات فارسی دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.SORT_ORDER IS 'ترتیب نمایش دلیل وضعیت Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.IS_ACTIVE IS 'نشانگر فعال بودن دلیل وضعیت Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.PARENT_CODE IS 'کد والد دلیل وضعیت Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.VALID_FROM IS 'تاریخ شروع اعتبار دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.VALID_TO IS 'تاریخ پایان اعتبار دلیل وضعیت Party';
COMMENT ON COLUMN CIF.REF_PARTY_STATUS_REASON.RECORD_VERSION IS 'شماره نسخه رکورد دلیل وضعیت Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.PARTY_TYPE_CODE IS 'کد نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.NAME_FA IS 'عنوان فارسی نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.NAME_EN IS 'عنوان انگلیسی نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع Party در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع Party؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.PARENT_CODE IS 'کد والد نوع Party در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع Party';
COMMENT ON COLUMN CIF.REF_PARTY_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع Party برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.RESIDENCE_STATUS_CODE IS 'کد وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.NAME_FA IS 'عنوان فارسی وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت اقامت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت اقامت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.PARENT_CODE IS 'کد والد وضعیت اقامت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت اقامت';
COMMENT ON COLUMN CIF.REF_RESIDENCE_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت اقامت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.ROLE_TYPE_CODE IS 'کد نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.NAME_FA IS 'عنوان فارسی نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.NAME_EN IS 'عنوان انگلیسی نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع نقش در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع نقش؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.PARENT_CODE IS 'کد والد نوع نقش در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع نقش';
COMMENT ON COLUMN CIF.REF_ROLE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع نقش برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.SIGNING_RULE_CODE IS 'کد قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.NAME_FA IS 'عنوان فارسی قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.NAME_EN IS 'عنوان انگلیسی قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.DESCRIPTION_FA IS 'توضیحات فارسی قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.SORT_ORDER IS 'ترتیب نمایش قاعده امضا در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.IS_ACTIVE IS 'نشانگر فعال بودن قاعده امضا؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.PARENT_CODE IS 'کد والد قاعده امضا در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.VALID_FROM IS 'تاریخ شروع اعتبار قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.VALID_TO IS 'تاریخ پایان اعتبار قاعده امضا';
COMMENT ON COLUMN CIF.REF_SIGNING_RULE.RECORD_VERSION IS 'شماره نسخه رکورد قاعده امضا برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.SOURCE_SYSTEM_CODE IS 'کد سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.NAME_FA IS 'عنوان فارسی سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.NAME_EN IS 'عنوان انگلیسی سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.DESCRIPTION_FA IS 'توضیحات فارسی سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.SORT_ORDER IS 'ترتیب نمایش سامانه مبدأ در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.IS_ACTIVE IS 'نشانگر فعال بودن سامانه مبدأ؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.PARENT_CODE IS 'کد والد سامانه مبدأ در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.VALID_FROM IS 'تاریخ شروع اعتبار سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.VALID_TO IS 'تاریخ پایان اعتبار سامانه مبدأ';
COMMENT ON COLUMN CIF.REF_SOURCE_SYSTEM.RECORD_VERSION IS 'شماره نسخه رکورد سامانه مبدأ برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.SPECIMEN_TYPE_CODE IS 'کد نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.NAME_FA IS 'عنوان فارسی نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.NAME_EN IS 'عنوان انگلیسی نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع نمونه امضا در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع نمونه امضا؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.PARENT_CODE IS 'کد والد نوع نمونه امضا در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع نمونه امضا';
COMMENT ON COLUMN CIF.REF_SPECIMEN_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع نمونه امضا برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.TENURE_TYPE_CODE IS 'کد وضعیت تصرف';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.NAME_FA IS 'عنوان فارسی وضعیت تصرف نشانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.NAME_EN IS 'عنوان انگلیسی وضعیت تصرف نشانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت تصرف نشانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.SORT_ORDER IS 'ترتیب نمایش وضعیت تصرف نشانی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت تصرف نشانی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.PARENT_CODE IS 'کد والد وضعیت تصرف نشانی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت تصرف نشانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار وضعیت تصرف نشانی';
COMMENT ON COLUMN CIF.REF_TENURE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت تصرف نشانی برای کنترل هم‌زمانی';


COMMENT ON TABLE CIF.REF_AUTHORITY_DOCUMENT_TYPE IS 'اطلاعات پایه مرجع سند اختیار و نمایندگی';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.AUTHORITY_DOCUMENT_TYPE_CODE IS 'کد مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.NAME_FA IS 'عنوان فارسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.NAME_EN IS 'عنوان انگلیسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.SORT_ORDER IS 'ترتیب نمایش مرجع سند اختیار در فهرست مرجع';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن مرجع سند اختیار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.PARENT_CODE IS 'کد والد مرجع سند اختیار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار مرجع سند اختیار';
COMMENT ON COLUMN CIF.REF_AUTHORITY_DOCUMENT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد مرجع سند اختیار برای کنترل هم‌زمانی';


PROMPT Creating CIF.REF_RELIGION
CREATE TABLE CIF.REF_RELIGION (
  RELIGION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_REF_RELIGION PRIMARY KEY (RELIGION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_REF_RELIGION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_REF_RELIGION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_REF_RELIGION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_REF_RELIGION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RELIGIOUS_DENOMINATION
CREATE TABLE CIF.REF_RELIGIOUS_DENOMINATION (
  DENOMINATION_CODE VARCHAR2(50 CHAR) NOT NULL,
  RELIGION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_REF_REL_DENOM PRIMARY KEY (DENOMINATION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_REF_REL_DENOM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_REF_REL_DENOM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_REF_REL_DENOM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_REF_REL_DENOM_04 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT FK_REF_REL_DENOM_RELIGION FOREIGN KEY (RELIGION_CODE) REFERENCES CIF.REF_RELIGION (RELIGION_CODE),
  CONSTRAINT FK_REF_REL_DENOM_PARENT FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_RELIGIOUS_DENOMINATION (DENOMINATION_CODE)
) TABLESPACE TS_CIF;
CREATE INDEX CIF.IX_REF_REL_DENOM_RELIGION ON CIF.REF_RELIGIOUS_DENOMINATION (RELIGION_CODE) TABLESPACE ITS_CIF;

COMMENT ON TABLE CIF.REF_RELIGION IS 'اطلاعات پایه دین برای Party شخص حقیقی؛ داده حساس و مشمول کنترل دسترسی و حریم خصوصی';
COMMENT ON TABLE CIF.REF_RELIGIOUS_DENOMINATION IS 'اطلاعات پایه مذهب یا شاخه دینی وابسته به دین';
COMMENT ON COLUMN CIF.REF_RELIGION.RELIGION_CODE IS 'کد دین';
COMMENT ON COLUMN CIF.REF_RELIGION.NAME_FA IS 'عنوان فارسی دین';
COMMENT ON COLUMN CIF.REF_RELIGION.NAME_EN IS 'عنوان انگلیسی دین';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.DENOMINATION_CODE IS 'کد مذهب یا شاخه دینی';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.RELIGION_CODE IS 'کد دین والد';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.NAME_FA IS 'عنوان فارسی مذهب';
COMMENT ON COLUMN CIF.REF_RELIGIOUS_DENOMINATION.NAME_EN IS 'عنوان انگلیسی مذهب';
