package com.behsazan.corebanking.deposit.account.wavec.application;

import com.behsazan.corebanking.deposit.account.error.DepositAccountNotFoundException;
import com.behsazan.corebanking.deposit.account.wavec.domain.DepositAccountWaveCModels.*;
import com.behsazan.corebanking.deposit.account.wavec.oracle.DepositAccountWaveCRepository;
import com.behsazan.corebanking.deposit.account.wavec.oracle.DepositAccountWaveCRepository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;

@Service
public class DepositAccountWaveCService {
    private static final Set<String> CHANNELS=Set.of("BRANCH","MOBILE","INTERNET","API","EMAIL","SMS","PORTAL");
    private static final Set<String> COMPLIANCE_RESULTS=Set.of("PASS","FAIL","REVIEW","WAIVED");
    private static final Set<String> RELEASE_POLICIES=Set.of("ORIGIN_ONLY","ORIGIN_OR_AUTHORITY","ORIGIN_OR_OVERRIDE","AUTO_EXPIRY");
    private final DepositAccountWaveCRepository repository;
    public DepositAccountWaveCService(DepositAccountWaveCRepository repository){this.repository=repository;}

    @Transactional(readOnly=true)
    public WaveCView get(long accountId){requireAccount(accountId);return view(accountId);}

    @Transactional
    public WaveCView inquiry(long accountId,InquiryRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات استعلام الزامی است.");String type=upper(required(request.inquiryTypeCode(),"INQUIRY_TYPE_CODE")),channel=upper(required(request.channelCode(),"CHANNEL_CODE"));if(!CHANNELS.contains(channel))throw new IllegalArgumentException("CHANNEL_CODE نامعتبر است: "+channel);if(request.requestedByPartyId()!=null&&!repository.activeAccountParty(accountId,request.requestedByPartyId()))throw new IllegalArgumentException("REQUESTED_BY_PARTY_ID باید Party فعال حساب باشد.");String h=hash("INQUIRY|"+accountId+"|"+type+"|"+channel+"|"+request.requestedByPartyId());if(replayOrClaim(idem,accountId,"ACCOUNT_INQUIRY",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_INQUIRY");repository.insertInquiry(id,accountId,type,channel,"DPS2-INQ-"+id,request.requestedByPartyId(),"DPS2-INQ-RESP-"+id,actor);repository.completeIdempotency(idem,"INQ:"+id);return view(accountId);}

    @Transactional
    public WaveCView issueConfirmation(long accountId,ConfirmationRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات تأییدیه الزامی است.");String type=upper(required(request.confirmationTypeCode(),"CONFIRMATION_TYPE_CODE")),delivery=upper(trim(request.deliveryChannelCode()));String h=hash("CONFIRM|"+accountId+"|"+type+"|"+delivery);if(replayOrClaim(idem,accountId,"ACCOUNT_CONFIRMATION",h,actor,correlation))return view(accountId);AccountFact fact=repository.accountFact(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_CONFIRMATION");repository.insertConfirmation(id,accountId,"CNF-"+id,type,fact.ledgerBalance(),fact.status(),fact.currency(),"DPS2-CONFIRMATION-"+id,delivery,actor);repository.completeIdempotency(idem,"CONF:"+id);return view(accountId);}

    @Transactional
    public WaveCView notificationPreference(long accountId,NotificationPreferenceRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("ترجیح اطلاع‌رسانی الزامی است.");String event=upper(required(request.eventCode(),"EVENT_CODE")),channel=upper(required(request.channelCode(),"CHANNEL_CODE")),target=required(request.deliveryTarget(),"DELIVERY_TARGET");validateTarget(accountId,channel,target);LocalDate from=request.validFrom()==null?LocalDate.now():request.validFrom();if(request.validTo()!=null&&request.validTo().isBefore(from))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");boolean enabled=request.enabled()==null||request.enabled();String h=hash("NOTIF_PREF|"+accountId+"|"+event+"|"+channel+"|"+target+"|"+enabled+"|"+from+"|"+request.validTo());if(replayOrClaim(idem,accountId,"NOTIFICATION_PREFERENCE",h,actor,correlation))return view(accountId);repository.upsertNotificationPreference(repository.next("SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_PREFERENCE"),accountId,event,channel,target,enabled,from,request.validTo(),actor);repository.completeIdempotency(idem,"NOTIFPREF:"+event+":"+channel);return view(accountId);}

    @Transactional
    public WaveCView notificationEvent(long accountId,NotificationEventRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("رویداد اطلاع‌رسانی الزامی است.");String event=upper(required(request.eventCode(),"EVENT_CODE")),ref=required(request.eventReference(),"EVENT_REFERENCE"),channel=upper(required(request.channelCode(),"CHANNEL_CODE"));String target=trim(request.deliveryTarget());if(target!=null)validateTarget(accountId,channel,target);String h=hash("NOTIF_EVENT|"+accountId+"|"+event+"|"+ref+"|"+channel+"|"+target);if(replayOrClaim(idem,accountId,"NOTIFICATION_EVENT",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_NOTIFICATION_EVENT");repository.insertNotificationEvent(id,accountId,event,ref,channel,target,trim(request.providerReference()),actor);repository.completeIdempotency(idem,"NOTIFEV:"+id);return view(accountId);}

    @Transactional
    public WaveCView grantApiAccess(long accountId,ApiAccessRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("اطلاعات دسترسی API الزامی است.");String client=required(request.clientReference(),"CLIENT_REFERENCE"),scope=required(request.apiScopeCode(),"API_SCOPE_CODE");if(request.authorizedPartyId()!=null&&!repository.activeAccountParty(accountId,request.authorizedPartyId()))throw new IllegalArgumentException("AUTHORIZED_PARTY_ID باید Party فعال حساب باشد.");if(request.validFrom()!=null&&request.validTo()!=null&&request.validTo().isBefore(request.validFrom()))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");String h=hash("API_ACCESS|"+accountId+"|"+client+"|"+scope+"|"+request.authorizedPartyId()+"|"+request.consentReference()+"|"+request.validFrom()+"|"+request.validTo());if(replayOrClaim(idem,accountId,"API_ACCESS_GRANT",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_API_ACCESS");repository.insertApiAccess(id,accountId,client,scope,request.authorizedPartyId(),trim(request.consentReference()),request.validFrom(),request.validTo(),actor);repository.completeIdempotency(idem,"APIACCESS:"+id);return view(accountId);}
    @Transactional public WaveCView revokeApiAccess(long accountId,long id,String actor,String correlation,String idem){requireAccount(accountId);String h=hash("API_REVOKE|"+accountId+"|"+id);if(replayOrClaim(idem,accountId,"API_ACCESS_REVOKE",h,actor,correlation))return view(accountId);if(repository.revokeApiAccess(accountId,id,actor)!=1)throw new IllegalArgumentException("دسترسی API فعال یافت نشد.");repository.completeIdempotency(idem,"APIACCESS_REVOKED:"+id);return view(accountId);}

    @Transactional
    public WaveCView addSignatureRule(long accountId,SignatureRuleRequest request,String actor,String correlation,String idem){requireAccount(accountId);if(request==null)throw new IllegalArgumentException("قاعده امضا الزامی است.");String code=upper(required(request.signatureRuleCode(),"SIGNATURE_RULE_CODE"));Integer min=request.minSignatureCount();if(min!=null&&min<1)throw new IllegalArgumentException("MIN_SIGNATURE_COUNT باید حداقل 1 باشد.");LocalDate from=request.validFrom()==null?LocalDate.now():request.validFrom();if(request.validTo()!=null&&request.validTo().isBefore(from))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");String h=hash("SIGRULE|"+accountId+"|"+code+"|"+min+"|"+from+"|"+request.validTo());if(replayOrClaim(idem,accountId,"SIGNATURE_RULE_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_SIGNATURE_RULE");repository.insertSignatureRule(id,accountId,code,min,from,request.validTo(),actor);repository.completeIdempotency(idem,"SIGRULE:"+id);return view(accountId);}
    @Transactional public WaveCView addDelegation(long accountId,DelegationRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("اطلاعات وکالت الزامی است.");requireParty(accountId,r.grantorPartyId(),"GRANTOR_PARTY_ID");requireParty(accountId,r.delegatePartyId(),"DELEGATE_PARTY_ID");LocalDate from=r.validFrom()==null?LocalDate.now():r.validFrom();if(r.validTo()!=null&&r.validTo().isBefore(from))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");if(r.maxAmount()!=null&&r.maxAmount().signum()<0)throw new IllegalArgumentException("MAX_AMOUNT منفی مجاز نیست.");String h=hash("DELEGATION|"+accountId+"|"+r.grantorPartyId()+"|"+r.delegatePartyId()+"|"+r.delegationTypeCode()+"|"+r.authorityScopeCode()+"|"+r.documentReference());if(replayOrClaim(idem,accountId,"DELEGATION_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_DELEGATION");repository.insertDelegation(id,accountId,r.grantorPartyId(),r.delegatePartyId(),upper(required(r.delegationTypeCode(),"DELEGATION_TYPE_CODE")),required(r.authorityScopeCode(),"AUTHORITY_SCOPE_CODE"),r.maxAmount(),required(r.documentReference(),"DOCUMENT_REFERENCE"),from,r.validTo(),actor);repository.completeIdempotency(idem,"DELEGATION:"+id);return view(accountId);}
    @Transactional public WaveCView addAuthorizedUser(long accountId,AuthorizedUserRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("کاربر مجاز الزامی است.");requireParty(accountId,r.partyId(),"PARTY_ID");LocalDate from=r.validFrom()==null?LocalDate.now():r.validFrom();String h=hash("AUTHUSER|"+accountId+"|"+r.partyId()+"|"+r.accessRoleCode()+"|"+r.channelScopeCode()+"|"+from);if(replayOrClaim(idem,accountId,"AUTHORIZED_USER_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_AUTHORIZED_USER");repository.insertAuthorizedUser(id,accountId,r.partyId(),upper(required(r.accessRoleCode(),"ACCESS_ROLE_CODE")),upper(trim(r.channelScopeCode())),from,r.validTo(),actor);repository.completeIdempotency(idem,"AUTHUSER:"+id);return view(accountId);}
    @Transactional public WaveCView addBeneficiary(long accountId,BeneficiaryRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("ذی‌نفع الزامی است.");if(r.beneficiaryPartyId()==null&&trim(r.beneficiaryReference())==null)throw new IllegalArgumentException("BENEFICIARY_PARTY_ID یا BENEFICIARY_REFERENCE الزامی است.");if(r.beneficiaryPartyId()!=null)requireParty(accountId,r.beneficiaryPartyId(),"BENEFICIARY_PARTY_ID");if(r.sharePercent()!=null&&(r.sharePercent().signum()<0||r.sharePercent().compareTo(new BigDecimal("100"))>0))throw new IllegalArgumentException("SHARE_PERCENT باید بین 0 و 100 باشد.");String h=hash("BENEF|"+accountId+"|"+r.beneficiaryPartyId()+"|"+r.beneficiaryReference()+"|"+r.beneficiaryTypeCode()+"|"+r.sharePercent());if(replayOrClaim(idem,accountId,"BENEFICIARY_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_BENEFICIARY");repository.insertBeneficiary(id,accountId,r.beneficiaryPartyId(),trim(r.beneficiaryReference()),upper(required(r.beneficiaryTypeCode(),"BENEFICIARY_TYPE_CODE")),r.sharePercent(),r.validFrom(),r.validTo(),actor);repository.completeIdempotency(idem,"BENEFICIARY:"+id);return view(accountId);}
    @Transactional public WaveCView addPaymentInstrument(long accountId,PaymentInstrumentRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("ابزار پرداخت الزامی است.");if(r.holderPartyId()!=null)requireParty(accountId,r.holderPartyId(),"HOLDER_PARTY_ID");if(r.issuedAt()!=null&&r.expiresAt()!=null&&r.expiresAt().isBefore(r.issuedAt()))throw new IllegalArgumentException("EXPIRES_AT قبل از ISSUED_AT مجاز نیست.");String h=hash("PAYINST|"+accountId+"|"+r.instrumentTypeCode()+"|"+r.instrumentReference()+"|"+r.holderPartyId());if(replayOrClaim(idem,accountId,"PAYMENT_INSTRUMENT_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT");repository.insertPaymentInstrument(id,accountId,upper(required(r.instrumentTypeCode(),"INSTRUMENT_TYPE_CODE")),required(r.instrumentReference(),"INSTRUMENT_REFERENCE"),r.holderPartyId(),r.issuedAt(),r.expiresAt(),actor);repository.completeIdempotency(idem,"PAYINST:"+id);return view(accountId);}
    @Transactional public WaveCView deactivatePartyAccess(long accountId,String entity,long id,String actor,String correlation,String idem){requireAccount(accountId);String table,pk;switch(upper(entity)){case "SIGNATURE_RULE"->{table="DEPOSIT_ACCOUNT_SIGNATURE_RULE";pk="ACCOUNT_SIGNATURE_RULE_ID";}case "DELEGATION"->{table="DEPOSIT_ACCOUNT_DELEGATION";pk="ACCOUNT_DELEGATION_ID";}case "AUTHORIZED_USER"->{table="DEPOSIT_ACCOUNT_AUTHORIZED_USER";pk="ACCOUNT_AUTHORIZED_USER_ID";}case "BENEFICIARY"->{table="DEPOSIT_ACCOUNT_BENEFICIARY";pk="ACCOUNT_BENEFICIARY_ID";}case "PAYMENT_INSTRUMENT"->{table="DEPOSIT_ACCOUNT_PAYMENT_INSTRUMENT";pk="ACCOUNT_PAYMENT_INSTRUMENT_ID";}default->throw new IllegalArgumentException("نوع Party Access نامعتبر است.");}String h=hash("PARTYACCESS_OFF|"+accountId+"|"+entity+"|"+id);if(replayOrClaim(idem,accountId,"PARTY_ACCESS_DEACTIVATE",h,actor,correlation))return view(accountId);if(repository.deactivate(table,pk,accountId,id,actor)!=1)throw new IllegalArgumentException("رکورد فعال Party Access یافت نشد.");repository.completeIdempotency(idem,"PARTYACCESS_OFF:"+id);return view(accountId);}

    @Transactional public WaveCView addRegulatoryRestriction(long accountId,RegulatoryRestrictionRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("محدودیت نظارتی الزامی است.");if(r.regulatoryRuleId()!=null&&!repository.regulatoryRuleExists(r.regulatoryRuleId()))throw new IllegalArgumentException("REGULATORY_RULE_ID فعال/معتبر نیست.");String release=upper(required(r.releasePolicyCode(),"RELEASE_POLICY_CODE"));if(!RELEASE_POLICIES.contains(release))throw new IllegalArgumentException("RELEASE_POLICY_CODE نامعتبر است.");String h=hash("REGRESTRICT|"+accountId+"|"+r.regulatoryRuleId()+"|"+r.restrictionTypeCode()+"|"+r.legalOrderReference());if(replayOrClaim(idem,accountId,"REGULATORY_RESTRICTION_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_REGULATORY_RESTRICTION");repository.insertRegRestriction(id,accountId,r.regulatoryRuleId(),upper(required(r.restrictionTypeCode(),"RESTRICTION_TYPE_CODE")),upper(trim(r.transactionTypeCode())),upper(trim(r.channelCode())),r.limitAmount(),trim(r.legalOrderReference()),upper(trim(r.issuingAuthorityCode())),r.validFrom(),r.validTo(),release,actor);repository.completeIdempotency(idem,"REGRESTRICT:"+id);return view(accountId);}
    @Transactional public WaveCView releaseRegulatoryRestriction(long accountId,long id,String actor,String correlation,String idem){requireAccount(accountId);String h=hash("REGRELEASE|"+accountId+"|"+id);if(replayOrClaim(idem,accountId,"REGULATORY_RESTRICTION_RELEASE",h,actor,correlation))return view(accountId);if(repository.releaseRegRestriction(accountId,id,actor)!=1)throw new IllegalArgumentException("محدودیت نظارتی فعال یافت نشد.");repository.completeIdempotency(idem,"REGRELEASE:"+id);return view(accountId);}
    @Transactional public WaveCView evaluateCompliance(long accountId,ComplianceEvaluationRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("ارزیابی انطباق الزامی است.");if(!repository.regulatoryRuleExists(r.regulatoryRuleId()))throw new IllegalArgumentException("فقط Regulatory Rule فعال قابل ارزیابی است.");String result=upper(required(r.resultStatusCode(),"RESULT_STATUS_CODE"));if(!COMPLIANCE_RESULTS.contains(result))throw new IllegalArgumentException("RESULT_STATUS_CODE نامعتبر است.");String h=hash("COMPLIANCE|"+accountId+"|"+r.regulatoryRuleId()+"|"+result+"|"+r.engineReference()+"|"+r.evaluationPhaseCode());if(replayOrClaim(idem,accountId,"COMPLIANCE_EVALUATE",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_COMPLIANCE_EVALUATION");repository.insertComplianceEvaluation(id,r.regulatoryRuleId(),accountId,result,upper(trim(r.resultReasonCode())),trim(r.engineReference()),trim(r.waiverReference()),upper(trim(r.evaluationPhaseCode())),r.validUntil(),Boolean.TRUE.equals(r.recheckRequired()),actor);repository.completeIdempotency(idem,"COMPLIANCE:"+id);return view(accountId);}

    @Transactional public WaveCView requestPricingOverride(long accountId,PricingOverrideRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("Pricing Override الزامی است.");String approver=required(r.approverUserId(),"APPROVER_USER_ID");if(approver.equalsIgnoreCase(actor))throw new IllegalArgumentException("Maker و Approver باید متفاوت باشند.");LocalDate from=r.effectiveFrom()==null?LocalDate.now():r.effectiveFrom();if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(from))throw new IllegalArgumentException("EFFECTIVE_TO قبل از EFFECTIVE_FROM مجاز نیست.");String h=hash("PRICING_OVERRIDE|"+accountId+"|"+r.pricingRuleId()+"|"+r.overrideTypeCode()+"|"+r.baseValue()+"|"+r.overrideValue()+"|"+r.authorityLevelCode()+"|"+approver+"|"+from);if(replayOrClaim(idem,accountId,"PRICING_OVERRIDE_REQUEST",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_ACCOUNT_PRICING_OVERRIDE"),approval=repository.next("SEQ_DEPOSIT_OPERATION_APPROVAL_REQUEST");repository.insertApproval(approval,accountId,"PRICING_OVERRIDE","DEPOSIT_ACCOUNT_PRICING_OVERRIDE",id,actor,approver,idem,correlation,actor);repository.insertPricingOverride(id,accountId,r.pricingRuleId(),upper(required(r.overrideTypeCode(),"OVERRIDE_TYPE_CODE")),r.baseValue(),Objects.requireNonNull(r.overrideValue(),"OVERRIDE_VALUE الزامی است."),upper(required(r.authorityLevelCode(),"AUTHORITY_LEVEL_CODE")),approval,from,r.effectiveTo(),actor);repository.completeIdempotency(idem,"PRICING_OVERRIDE:"+id);return view(accountId);}
    @Transactional public WaveCView approvePricingOverride(long accountId,long id,String actor,String correlation,String idem){requireAccount(accountId);String h=hash("PRICING_APPROVE|"+accountId+"|"+id+"|"+actor);if(replayOrClaim(idem,accountId,"PRICING_OVERRIDE_APPROVE",h,actor,correlation))return view(accountId);PricingOverrideLock p=repository.pricingOverride(accountId,id);if(p==null||p.approvalId()==null)throw new IllegalArgumentException("Pricing Override قابل تأیید یافت نشد.");ApprovalLock a=repository.approval(p.approvalId());if(a==null||!"PENDING_APPROVAL".equals(a.status())||!actor.equals(a.approver()))throw new IllegalArgumentException("Approver تعیین‌شده یا وضعیت Approval معتبر نیست.");if(repository.approveApproval(a.id(),a.version(),actor)!=1||repository.activatePricingOverride(p.id(),p.version(),actor)!=1)throw new IllegalStateException("تأیید Pricing Override همزمان تغییر کرده است.");repository.completeIdempotency(idem,"PRICING_APPROVED:"+id);return view(accountId);}

    @Transactional public WaveCView addTaxExemption(long accountId,TaxExemptionRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("معافیت مالیاتی الزامی است.");requireParty(accountId,r.partyId(),"PARTY_ID");LocalDate from=r.validFrom()==null?LocalDate.now():r.validFrom();if(r.validTo()!=null&&r.validTo().isBefore(from))throw new IllegalArgumentException("VALID_TO قبل از VALID_FROM مجاز نیست.");String h=hash("TAX_EXEMPT|"+accountId+"|"+r.partyId()+"|"+r.exemptionCode()+"|"+r.taxTypeCode()+"|"+r.documentReference()+"|"+from);if(replayOrClaim(idem,accountId,"TAX_EXEMPTION_ADD",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_TAX_EXEMPTION");repository.insertTaxExemption(id,r.partyId(),accountId,upper(required(r.exemptionCode(),"EXEMPTION_CODE")),upper(required(r.taxTypeCode(),"TAX_TYPE_CODE")),required(r.documentReference(),"DOCUMENT_REFERENCE"),from,r.validTo(),actor);repository.completeIdempotency(idem,"TAXEXEMPT:"+id);return view(accountId);}
    @Transactional public WaveCView calculateTax(long accountId,TaxCalculationRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("محاسبه مالیات الزامی است.");if(r.profitPaymentId()==null&&r.transactionId()==null)throw new IllegalArgumentException("PROFIT_PAYMENT_ID یا TRANSACTION_ID برای Trace مالیات الزامی است.");if(r.taxableBaseAmount()==null||r.taxableBaseAmount().signum()<0)throw new IllegalArgumentException("TAXABLE_BASE_AMOUNT نامعتبر است.");TaxRule rule=repository.taxRule(r.taxRuleId());if(rule==null)throw new IllegalArgumentException("Tax Rule فعال/معتبر یافت نشد.");BigDecimal base=r.taxableBaseAmount(),exempt=repository.activeTaxExemptionAmount(accountId,rule.taxType(),base);BigDecimal taxable=base.subtract(exempt).max(BigDecimal.ZERO);if(rule.minTaxable()!=null&&taxable.compareTo(rule.minTaxable())<0)taxable=BigDecimal.ZERO;BigDecimal amount=taxable.multiply(rule.rate()).divide(new BigDecimal("100"),4,RoundingMode.HALF_UP);String h=hash("TAXCALC|"+accountId+"|"+r.taxRuleId()+"|"+r.profitPaymentId()+"|"+r.transactionId()+"|"+base);if(replayOrClaim(idem,accountId,"TAX_CALCULATE",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_TAX_CALCULATION");repository.insertTaxCalculation(id,accountId,r.taxRuleId(),r.profitPaymentId(),r.transactionId(),base,exempt,rule.rate(),amount,actor);repository.completeIdempotency(idem,"TAXCALC:"+id);return view(accountId);}
    @Transactional public WaveCView issueTaxCertificate(long accountId,TaxCertificateRequest r,String actor,String correlation,String idem){requireAccount(accountId);if(r==null)throw new IllegalArgumentException("گواهی مالیاتی الزامی است.");requireParty(accountId,r.partyId(),"PARTY_ID");if(r.periodStart()==null||r.periodEnd()==null||r.periodEnd().isBefore(r.periodStart()))throw new IllegalArgumentException("بازه گواهی مالیاتی نامعتبر است.");if(r.grossAmount()==null||r.taxAmount()==null||r.grossAmount().signum()<0||r.taxAmount().signum()<0)throw new IllegalArgumentException("مبالغ گواهی مالیاتی نامعتبر است.");String h=hash("TAXCERT|"+accountId+"|"+r.partyId()+"|"+r.taxTypeCode()+"|"+r.periodStart()+"|"+r.periodEnd()+"|"+r.grossAmount()+"|"+r.taxAmount());if(replayOrClaim(idem,accountId,"TAX_CERTIFICATE_ISSUE",h,actor,correlation))return view(accountId);long id=repository.next("SEQ_DEPOSIT_TAX_CERTIFICATE");repository.insertTaxCertificate(id,accountId,r.partyId(),"TAXCERT-"+id,upper(required(r.taxTypeCode(),"TAX_TYPE_CODE")),r.periodStart(),r.periodEnd(),r.grossAmount(),r.taxAmount(),trim(r.documentReference()),actor);repository.completeIdempotency(idem,"TAXCERT:"+id);return view(accountId);}

    private WaveCView view(long accountId){return new WaveCView(new AccountServicesView(repository.inquiries(accountId),repository.confirmations(accountId),repository.notificationPreferences(accountId),repository.notificationEvents(accountId),repository.apiAccesses(accountId)),new PartyAccessView(repository.signatureRules(accountId),repository.delegations(accountId),repository.authorizedUsers(accountId),repository.beneficiaries(accountId),repository.paymentInstruments(accountId)),new ComplianceView(repository.regulatoryRestrictions(accountId),repository.complianceEvaluations(accountId)),new PricingView(repository.pricingOverrides(accountId),repository.feeAssessments(accountId),repository.profitability(accountId)),new TaxView(repository.taxExemptions(accountId),repository.taxCalculations(accountId),repository.taxCertificates(accountId)));}
    private void requireAccount(long id){if(!repository.accountExists(id))throw new DepositAccountNotFoundException("حساب سپرده یافت نشد: "+id);}
    private void requireParty(long aid,long pid,String field){if(!repository.activeAccountParty(aid,pid))throw new IllegalArgumentException(field+" باید Party فعال حساب باشد.");}
    private void validateTarget(long accountId,String channel,String target){if(("EMAIL".equals(channel)||"SMS".equals(channel))&&!repository.activeContact(accountId,channel,target))throw new IllegalArgumentException("مقصد "+channel+" باید Contact فعال حساب باشد.");}
    private boolean replayOrClaim(String key,long accountId,String operation,String payloadHash,String actor,String correlation){String k=required(key,"X-Idempotency-Key");var row=repository.idempotency(k);if(row.isPresent()){IdemRow x=row.get();if(!operation.equals(x.operation())||!payloadHash.equals(x.payloadHash())||!Objects.equals(accountId,x.accountId()))throw new IllegalArgumentException("Idempotency-Key با payload قبلی سازگار نیست.");if("COMPLETED".equals(x.status()))return true;throw new IllegalStateException("درخواست با Idempotency-Key در حال پردازش است.");}repository.claimIdempotency(repository.next("SEQ_DEPOSIT_OPERATION_IDEMPOTENCY"),k,accountId,operation,payloadHash,actor,correlation);return false;}
    private static String required(String v,String field){if(v==null||v.isBlank())throw new IllegalArgumentException(field+" الزامی است.");return v.trim();}
    private static String trim(String v){return v==null||v.isBlank()?null:v.trim();}
    private static String upper(String v){return v==null?null:v.trim().toUpperCase(Locale.ROOT);}
    private static String hash(String s){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(d);}catch(Exception e){throw new IllegalStateException(e);}}
}
