-- ============================================================================
-- Oracle DDL inferred from the supplied GEO hierarchy INSERT scripts
-- Scope: PROVINCES -> COUNTIES -> DISTRICTS -> CITIES / RURAL_DISTRICTS -> VILLAGES
-- Encoding: UTF-8
-- Assumption: Oracle user/schema GEO already exists.
-- ============================================================================

SET DEFINE OFF;
SET SQLBLANKLINES ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

PROMPT Creating sequences ...

CREATE SEQUENCE GEO.SEQ_PROVINCES
    START WITH 33 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

CREATE SEQUENCE GEO.SEQ_COUNTIES
    START WITH 458 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

CREATE SEQUENCE GEO.SEQ_DISTRICTS
    START WITH 1125 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

CREATE SEQUENCE GEO.SEQ_CITIES
    START WITH 1391 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

CREATE SEQUENCE GEO.SEQ_RURAL_DISTRICTS
    START WITH 2673 INCREMENT BY 1 NOCACHE NOCYCLE NOORDER;

CREATE SEQUENCE GEO.SEQ_VILLAGES
    START WITH 98244 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER;

PROMPT Creating GEO.PROVINCES ...

CREATE TABLE GEO.PROVINCES
(
    PROVINCE_ID             NUMBER(10) DEFAULT GEO.SEQ_PROVINCES.NEXTVAL NOT NULL,
    PROVINCE_CODE           VARCHAR2(3 CHAR) NOT NULL,
    PROVINCE_NAME           VARCHAR2(100 CHAR) NOT NULL,
    PROVINCE_ENGLISH_NAME   VARCHAR2(150 CHAR),
    DIALLING_CODE           VARCHAR2(10 CHAR),
    COUNTRY_ID              NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD        NUMBER(12),
    CENSUS_POPULATION       NUMBER(12),
    CENSUS_MALE             NUMBER(12),
    CENSUS_FEMALE           NUMBER(12),
    GEO_TYPE                NUMBER(2) DEFAULT 1 NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER              NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY              NUMBER(10) NOT NULL,
    CREATED_DATE            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        NUMBER(10),
    LAST_MODIFIED_DATE      TIMESTAMP(6),

    CONSTRAINT PK_PROVINCES
        PRIMARY KEY (PROVINCE_ID),

    CONSTRAINT UK_PROVINCES_CODE
        UNIQUE (PROVINCE_CODE),

    CONSTRAINT CK_PROVINCES_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    -- GEO_TYPE=0 is retained because the supplied data contains one such row.
    CONSTRAINT CK_PROVINCES_GTYPE
        CHECK (GEO_TYPE IN (0, 1))
);

PROMPT Creating GEO.COUNTIES ...

CREATE TABLE GEO.COUNTIES
(
    COUNTY_ID               NUMBER(10) DEFAULT GEO.SEQ_COUNTIES.NEXTVAL NOT NULL,
    COUNTY_CODE             VARCHAR2(4 CHAR) NOT NULL,
    COUNTY_NAME             VARCHAR2(100 CHAR) NOT NULL,
    COUNTY_ENGLISH_NAME     VARCHAR2(150 CHAR),
    PROVINCE_ID             NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD        NUMBER(12),
    CENSUS_POPULATION       NUMBER(12),
    CENSUS_MALE             NUMBER(12),
    CENSUS_FEMALE           NUMBER(12),
    GEO_TYPE                NUMBER(2) DEFAULT 2 NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER              NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY              NUMBER(10) NOT NULL,
    CREATED_DATE            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        NUMBER(10),
    LAST_MODIFIED_DATE      TIMESTAMP(6),

    CONSTRAINT PK_COUNTIES
        PRIMARY KEY (COUNTY_ID),

    CONSTRAINT UK_COUNTIES_CODE
        UNIQUE (COUNTY_CODE),

    CONSTRAINT CK_COUNTIES_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    CONSTRAINT CK_COUNTIES_GTYPE
        CHECK (GEO_TYPE = 2),

    CONSTRAINT FK_COUNTIES_PROVINCE
        FOREIGN KEY (PROVINCE_ID)
        REFERENCES GEO.PROVINCES (PROVINCE_ID)
);

PROMPT Creating GEO.DISTRICTS ...

CREATE TABLE GEO.DISTRICTS
(
    DISTRICT_ID             NUMBER(10) DEFAULT GEO.SEQ_DISTRICTS.NEXTVAL NOT NULL,
    DISTRICT_CODE           VARCHAR2(6 CHAR) NOT NULL,
    DISTRICT_NAME           VARCHAR2(100 CHAR) NOT NULL,
    DISTRICT_ENGLISH_NAME   VARCHAR2(150 CHAR),
    COUNTY_ID               NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD        NUMBER(12),
    CENSUS_POPULATION       NUMBER(12),
    CENSUS_MALE             NUMBER(12),
    CENSUS_FEMALE           NUMBER(12),
    GEO_TYPE                NUMBER(2) DEFAULT 3 NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER              NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY              NUMBER(10) NOT NULL,
    CREATED_DATE            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        NUMBER(10),
    LAST_MODIFIED_DATE      TIMESTAMP(6),

    CONSTRAINT PK_DISTRICTS
        PRIMARY KEY (DISTRICT_ID),

    CONSTRAINT UK_DISTRICTS_CODE
        UNIQUE (DISTRICT_CODE),

    CONSTRAINT CK_DISTRICTS_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    CONSTRAINT CK_DISTRICTS_GTYPE
        CHECK (GEO_TYPE = 3),

    CONSTRAINT FK_DISTRICTS_COUNTY
        FOREIGN KEY (COUNTY_ID)
        REFERENCES GEO.COUNTIES (COUNTY_ID)
);

PROMPT Creating GEO.CITIES ...

CREATE TABLE GEO.CITIES
(
    CITY_ID                 NUMBER(10) DEFAULT GEO.SEQ_CITIES.NEXTVAL NOT NULL,
    CITY_CODE               VARCHAR2(10 CHAR) NOT NULL,
    CITY_NAME               VARCHAR2(100 CHAR) NOT NULL,
    CITY_ENGLISH_NAME       VARCHAR2(150 CHAR),
    DISTRICT_ID             NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD        NUMBER(12),
    CENSUS_POPULATION       NUMBER(12),
    CENSUS_MALE             NUMBER(12),
    CENSUS_FEMALE           NUMBER(12),
    GEO_TYPE                NUMBER(2) DEFAULT 5 NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER              NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY              NUMBER(10) NOT NULL,
    CREATED_DATE            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        NUMBER(10),
    LAST_MODIFIED_DATE      TIMESTAMP(6),

    CONSTRAINT PK_CITIES
        PRIMARY KEY (CITY_ID),

    CONSTRAINT UK_CITIES_CODE
        UNIQUE (CITY_CODE),

    CONSTRAINT CK_CITIES_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    CONSTRAINT CK_CITIES_GTYPE
        CHECK (GEO_TYPE = 5),

    CONSTRAINT FK_CITIES_DISTRICT
        FOREIGN KEY (DISTRICT_ID)
        REFERENCES GEO.DISTRICTS (DISTRICT_ID)
);

PROMPT Creating GEO.RURAL_DISTRICTS ...

CREATE TABLE GEO.RURAL_DISTRICTS
(
    RURAL_DISTRICT_ID             NUMBER(10) DEFAULT GEO.SEQ_RURAL_DISTRICTS.NEXTVAL NOT NULL,
    RURAL_DISTRICT_CODE           VARCHAR2(10 CHAR) NOT NULL,
    RURAL_DISTRICT_NAME           VARCHAR2(150 CHAR) NOT NULL,
    RURAL_DISTRICT_ENGLISH_NAME   VARCHAR2(150 CHAR),
    DISTRICT_ID                   NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD              NUMBER(12),
    CENSUS_POPULATION             NUMBER(12),
    CENSUS_MALE                   NUMBER(12),
    CENSUS_FEMALE                 NUMBER(12),
    GEO_TYPE                      NUMBER(2) DEFAULT 4 NOT NULL,
    IS_ACTIVE                     NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER                    NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY                    NUMBER(10) NOT NULL,
    CREATED_DATE                  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY              NUMBER(10),
    LAST_MODIFIED_DATE            TIMESTAMP(6),

    CONSTRAINT PK_RURAL_DISTRICTS
        PRIMARY KEY (RURAL_DISTRICT_ID),

    CONSTRAINT UK_RURAL_DIST_CODE
        UNIQUE (RURAL_DISTRICT_CODE),

    CONSTRAINT CK_RURAL_DIST_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    CONSTRAINT CK_RURAL_DIST_GTYPE
        CHECK (GEO_TYPE = 4),

    CONSTRAINT FK_RURAL_DIST_DISTRICT
        FOREIGN KEY (DISTRICT_ID)
        REFERENCES GEO.DISTRICTS (DISTRICT_ID)
);

PROMPT Creating GEO.VILLAGES ...

CREATE TABLE GEO.VILLAGES
(
    VILLAGE_ID              NUMBER(10) DEFAULT GEO.SEQ_VILLAGES.NEXTVAL NOT NULL,
    VILLAGE_CODE            VARCHAR2(16 CHAR) NOT NULL,
    VILLAGE_NAME            VARCHAR2(250 CHAR) NOT NULL,
    VILLAGE_ENGLISH_NAME    VARCHAR2(150 CHAR),
    RURAL_DISTRICT_ID       NUMBER(10) NOT NULL,
    CENSUS_HOUSEHOLD        NUMBER(12),
    CENSUS_POPULATION       NUMBER(12),
    CENSUS_MALE             NUMBER(12),
    CENSUS_FEMALE           NUMBER(12),
    GEO_TYPE                NUMBER(2) DEFAULT 6 NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_ORDER              NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY              NUMBER(10) NOT NULL,
    CREATED_DATE            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        NUMBER(10),
    LAST_MODIFIED_DATE      TIMESTAMP(6),

    CONSTRAINT PK_VILLAGES
        PRIMARY KEY (VILLAGE_ID),

    CONSTRAINT UK_VILLAGES_CODE
        UNIQUE (VILLAGE_CODE),

    CONSTRAINT CK_VILLAGES_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1)),

    -- The supplied data contains GEO_TYPE values 6 and 8.
    CONSTRAINT CK_VILLAGES_GTYPE
        CHECK (GEO_TYPE IN (6, 8)),

    CONSTRAINT FK_VILLAGES_RURAL_DIST
        FOREIGN KEY (RURAL_DISTRICT_ID)
        REFERENCES GEO.RURAL_DISTRICTS (RURAL_DISTRICT_ID)
);

PROMPT Creating parent-navigation indexes ...

CREATE INDEX GEO.IX_COUNTIES_PROV_NAME
    ON GEO.COUNTIES (PROVINCE_ID, COUNTY_NAME);

CREATE INDEX GEO.IX_DISTRICTS_COUNTY_NAME
    ON GEO.DISTRICTS (COUNTY_ID, DISTRICT_NAME);

CREATE INDEX GEO.IX_CITIES_DISTRICT_NAME
    ON GEO.CITIES (DISTRICT_ID, CITY_NAME);

CREATE INDEX GEO.IX_RURAL_DIST_DIST_NAME
    ON GEO.RURAL_DISTRICTS (DISTRICT_ID, RURAL_DISTRICT_NAME);

CREATE INDEX GEO.IX_VILLAGES_RURAL_NAME
    ON GEO.VILLAGES (RURAL_DISTRICT_ID, VILLAGE_NAME);

PROMPT Adding comments ...

COMMENT ON TABLE GEO.PROVINCES IS 'استان‌ها';
COMMENT ON TABLE GEO.COUNTIES IS 'شهرستان‌ها';
COMMENT ON TABLE GEO.DISTRICTS IS 'بخش‌ها';
COMMENT ON TABLE GEO.CITIES IS 'شهرها';
COMMENT ON TABLE GEO.RURAL_DISTRICTS IS 'دهستان‌ها';
COMMENT ON TABLE GEO.VILLAGES IS 'روستاها و آبادی‌ها';

COMMENT ON COLUMN GEO.PROVINCES.COUNTRY_ID IS 'External country reference; FK is intentionally omitted from this prototype DDL.';
COMMENT ON COLUMN GEO.PROVINCES.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.PROVINCES.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.COUNTIES.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.COUNTIES.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.DISTRICTS.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.DISTRICTS.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.CITIES.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.CITIES.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.RURAL_DISTRICTS.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.RURAL_DISTRICTS.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.VILLAGES.LAST_MODIFIED_BY IS 'Optional; populated only on UPDATE.';
COMMENT ON COLUMN GEO.VILLAGES.LAST_MODIFIED_DATE IS 'Optional; populated only on UPDATE.';

COMMIT;

PROMPT GEO hierarchy DDL completed successfully.
