-- ============================================================================
-- Reference Data Prototype
-- Oracle DDL for the uploaded reference-data exports
-- Generated: 2026-07-30
--
-- Assumptions
--   1. Schema GEO already exists.
--   2. Existing geography tables GEO.PROVINCES and GEO.CITIES are already
--      available before this script is executed.
--   3. Column data types and sizes are inferred from the supplied INSERT files.
--   4. LAST_MODIFIED_BY / LAST_MODIFIED_DATE are added for CRUD form support.
--   5. Sequence starting values are set above the maximum IDs in the supplied
--      data exports so the exports can be loaded without sequence collisions.
-- ============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

PROMPT ================================================================
PROMPT Creating GEO reference tables
PROMPT ================================================================

-- --------------------------------------------------------------------------
-- GEO.CONTINENTS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.CONTINENTS (
    CONTINENT_ID             NUMBER(10)          NOT NULL,
    CONTINENT_CODE           VARCHAR2(10 CHAR)   NOT NULL,
    CONTINENT_NAME           VARCHAR2(100 CHAR)  NOT NULL,
    CONTINENT_ENGLISH_NAME   VARCHAR2(100 CHAR)  NOT NULL,
    CREATED_BY               NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY         NUMBER(19),
    LAST_MODIFIED_DATE       TIMESTAMP(6),
    CONSTRAINT PK_CONTINENTS PRIMARY KEY (CONTINENT_ID),
    CONSTRAINT UK_CONTINENTS_CODE UNIQUE (CONTINENT_CODE)
);

CREATE SEQUENCE GEO.SEQ_CONTINENTS
    START WITH 10 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.LANGUAGES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.LANGUAGES (
    LANGUAGE_ID              NUMBER(10)          NOT NULL,
    LANGUAGE_ISO_CODE        VARCHAR2(10 CHAR)   NOT NULL,
    LANGUAGE_NAME            VARCHAR2(100 CHAR)  NOT NULL,
    LANGUAGE_ENGLISH_NAME    VARCHAR2(100 CHAR)  NOT NULL,
    IS_ACTIVE                NUMBER(1)           DEFAULT 1 NOT NULL,
    SORT_ORDER               NUMBER(10)          DEFAULT 0 NOT NULL,
    CREATED_BY               NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY         NUMBER(19),
    LAST_MODIFIED_DATE       TIMESTAMP(6),
    CONSTRAINT PK_LANGUAGES PRIMARY KEY (LANGUAGE_ID),
    CONSTRAINT UK_LANGUAGES_ISO UNIQUE (LANGUAGE_ISO_CODE),
    CONSTRAINT CK_LANGUAGES_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE SEQUENCE GEO.SEQ_LANGUAGES
    START WITH 130 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.CURRENCIES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.CURRENCIES (
    CURRENCY_ID              NUMBER(10)          NOT NULL,
    CURRENCY_ALPHABETIC_ISO  VARCHAR2(10 CHAR)   NOT NULL,
    CURRENCY_NUMERIC_ISO     VARCHAR2(10 CHAR)   NOT NULL,
    CURRENCY_NAME            VARCHAR2(150 CHAR)  NOT NULL,
    CURRENCY_ENGLISH_NAME    VARCHAR2(150 CHAR)  NOT NULL,
    CURRENCY_SYMBOL          VARCHAR2(20 CHAR),
    FLOATING_POINT           NUMBER(2)           DEFAULT 0 NOT NULL,
    IS_BASE_CURRENCY         NUMBER(1)           DEFAULT 0 NOT NULL,
    IS_DEFAULT_CURRENCY      NUMBER(1)           DEFAULT 0 NOT NULL,
    CONVERSION_METHOD        NUMBER(2)           DEFAULT 1 NOT NULL,
    IS_ACTIVE                NUMBER(1)           DEFAULT 1 NOT NULL,
    SORT_ORDER               NUMBER(10)          DEFAULT 0 NOT NULL,
    CREATED_BY               NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY         NUMBER(19),
    LAST_MODIFIED_DATE       TIMESTAMP(6),
    CONSTRAINT PK_CURRENCIES PRIMARY KEY (CURRENCY_ID),
    CONSTRAINT UK_CURRENCIES_ALPHA UNIQUE (CURRENCY_ALPHABETIC_ISO),
    CONSTRAINT UK_CURRENCIES_NUM UNIQUE (CURRENCY_NUMERIC_ISO),
    CONSTRAINT CK_CUR_FLOAT_POINT CHECK (FLOATING_POINT BETWEEN 0 AND 9),
    CONSTRAINT CK_CUR_BASE CHECK (IS_BASE_CURRENCY IN (0, 1)),
    CONSTRAINT CK_CUR_DEFAULT CHECK (IS_DEFAULT_CURRENCY IN (0, 1)),
    CONSTRAINT CK_CUR_METHOD CHECK (CONVERSION_METHOD IN (1, 2)),
    CONSTRAINT CK_CUR_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE SEQUENCE GEO.SEQ_CURRENCIES
    START WITH 169 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.COUNTRIES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.COUNTRIES (
    COUNTRY_ID                 NUMBER(10)          NOT NULL,
    COUNTRY_NAME               VARCHAR2(150 CHAR)  NOT NULL,
    COUNTRY_ENGLISH_NAME       VARCHAR2(150 CHAR)  NOT NULL,
    COUNTRY_FULL_NAME          VARCHAR2(200 CHAR)  NOT NULL,
    COUNTRY_ENGLISH_FULL_NAME  VARCHAR2(200 CHAR),
    CONTINENT_ID               NUMBER(10)          NOT NULL,
    COUNTRY_ISO_CODE           VARCHAR2(10 CHAR)   NOT NULL,
    COUNTRY_ISO_CODE2          VARCHAR2(10 CHAR)   NOT NULL,
    DIALLING_CODE              NUMBER(10),
    IS_DEFAULT_COUNTRY         NUMBER(1)           DEFAULT 0 NOT NULL,
    CURRENCY_ID                NUMBER(10)          NOT NULL,
    OFFICIAL_LANGUAGE_ID       NUMBER(10)          NOT NULL,
    NATIONALITY                VARCHAR2(150 CHAR)  NOT NULL,
    ENGLISH_NATIONALITY        VARCHAR2(150 CHAR)  NOT NULL,
    COUNTRY_REGION             VARCHAR2(100 CHAR),
    IS_ACTIVE                  NUMBER(1)           DEFAULT 1 NOT NULL,
    SORT_ORDER                 NUMBER(10)          DEFAULT 0 NOT NULL,
    CREATED_BY                 NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE               TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY           NUMBER(19),
    LAST_MODIFIED_DATE         TIMESTAMP(6),
    CONSTRAINT PK_COUNTRIES PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT UK_COUNTRIES_ISO3 UNIQUE (COUNTRY_ISO_CODE),
    CONSTRAINT UK_COUNTRIES_ISO2 UNIQUE (COUNTRY_ISO_CODE2),
    CONSTRAINT CK_COUNTRY_DEFAULT CHECK (IS_DEFAULT_COUNTRY IN (0, 1)),
    CONSTRAINT CK_COUNTRY_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_COUNTRY_CONTINENT FOREIGN KEY (CONTINENT_ID)
        REFERENCES GEO.CONTINENTS (CONTINENT_ID),
    CONSTRAINT FK_COUNTRY_CURRENCY FOREIGN KEY (CURRENCY_ID)
        REFERENCES GEO.CURRENCIES (CURRENCY_ID),
    CONSTRAINT FK_COUNTRY_LANGUAGE FOREIGN KEY (OFFICIAL_LANGUAGE_ID)
        REFERENCES GEO.LANGUAGES (LANGUAGE_ID)
);

CREATE INDEX GEO.IX_COUNTRY_CONTINENT ON GEO.COUNTRIES (CONTINENT_ID);
CREATE INDEX GEO.IX_COUNTRY_CURRENCY ON GEO.COUNTRIES (CURRENCY_ID);
CREATE INDEX GEO.IX_COUNTRY_LANGUAGE ON GEO.COUNTRIES (OFFICIAL_LANGUAGE_ID);

CREATE SEQUENCE GEO.SEQ_COUNTRIES
    START WITH 250 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.BLOOD_TYPES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.BLOOD_TYPES (
    BLOOD_TYPE_ID            NUMBER(10)          NOT NULL,
    BLOOD_TYPE_CODE          VARCHAR2(10 CHAR)   NOT NULL,
    BLOOD_TYPE_NAME          VARCHAR2(100 CHAR)  NOT NULL,
    BLOOD_TYPE_ENGLISH_NAME  VARCHAR2(100 CHAR)  NOT NULL,
    CREATED_BY               NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY         NUMBER(19),
    LAST_MODIFIED_DATE       TIMESTAMP(6),
    CONSTRAINT PK_BLOOD_TYPES PRIMARY KEY (BLOOD_TYPE_ID),
    CONSTRAINT UK_BLOOD_TYPES_CODE UNIQUE (BLOOD_TYPE_CODE)
);

CREATE SEQUENCE GEO.SEQ_BLOOD_TYPES
    START WITH 9 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.BANKS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.BANKS (
    BANK_ID                  NUMBER(10)          NOT NULL,
    BANK_CODE                VARCHAR2(20 CHAR)   NOT NULL,
    BANK_NAME                VARCHAR2(150 CHAR)  NOT NULL,
    BANK_ENGLISH_NAME        VARCHAR2(150 CHAR),
    COUNTRY_ID               NUMBER(10)          NOT NULL,
    BANK_URL                 VARCHAR2(500 CHAR),
    IS_ACTIVE                NUMBER(1)           DEFAULT 1 NOT NULL,
    SORT_ORDER               NUMBER(10),
    CREATED_BY               NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY         NUMBER(19),
    LAST_MODIFIED_DATE       TIMESTAMP(6),
    CONSTRAINT PK_BANKS PRIMARY KEY (BANK_ID),
    CONSTRAINT UK_BANKS_CODE UNIQUE (BANK_CODE),
    CONSTRAINT CK_BANKS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_BANKS_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES GEO.COUNTRIES (COUNTRY_ID)
);

CREATE INDEX GEO.IX_BANKS_COUNTRY ON GEO.BANKS (COUNTRY_ID);

CREATE SEQUENCE GEO.SEQ_BANKS
    START WITH 32 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.EDUCATION_GROUPS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.EDUCATION_GROUPS (
    EDUCATION_GROUP_ID            NUMBER(10)          NOT NULL,
    EDUCATION_GROUP_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    EDUCATION_GROUP_NAME          VARCHAR2(150 CHAR)  NOT NULL,
    EDUCATION_GROUP_ENGLISH_NAME  VARCHAR2(150 CHAR),
    CREATED_BY                    NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE                  TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY              NUMBER(19),
    LAST_MODIFIED_DATE            TIMESTAMP(6),
    CONSTRAINT PK_EDU_GROUPS PRIMARY KEY (EDUCATION_GROUP_ID),
    CONSTRAINT UK_EDU_GROUPS_CODE UNIQUE (EDUCATION_GROUP_CODE)
);

CREATE SEQUENCE GEO.SEQ_EDUCATION_GROUPS
    START WITH 4 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.EDUCATION_SUBGROUPS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.EDUCATION_SUBGROUPS (
    EDUCATION_SUBGROUP_ID            NUMBER(10)          NOT NULL,
    EDUCATION_SUBGROUP_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    EDUCATION_SUBGROUP_NAME          VARCHAR2(200 CHAR)  NOT NULL,
    EDUCATION_SUBGROUP_ENGLISH_NAME  VARCHAR2(200 CHAR),
    EDUCATION_GROUP_ID               NUMBER(10)          NOT NULL,
    CREATED_BY                       NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE                     TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY                 NUMBER(19),
    LAST_MODIFIED_DATE               TIMESTAMP(6),
    CONSTRAINT PK_EDU_SUBGROUPS PRIMARY KEY (EDUCATION_SUBGROUP_ID),
    CONSTRAINT UK_EDU_SUBGROUP_CODE UNIQUE (EDUCATION_SUBGROUP_CODE),
    CONSTRAINT FK_EDUSUB_GROUP FOREIGN KEY (EDUCATION_GROUP_ID)
        REFERENCES GEO.EDUCATION_GROUPS (EDUCATION_GROUP_ID)
);

CREATE INDEX GEO.IX_EDUSUB_GROUP
    ON GEO.EDUCATION_SUBGROUPS (EDUCATION_GROUP_ID);

CREATE SEQUENCE GEO.SEQ_EDUCATION_SUBGROUPS
    START WITH 7 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.EDUCATION_DEGREES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.EDUCATION_DEGREES (
    EDUCATION_DEGREE_ID            NUMBER(10)          NOT NULL,
    EDUCATION_DEGREE_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    EDUCATION_DEGREE_NAME          VARCHAR2(150 CHAR)  NOT NULL,
    EDUCATION_DEGREE_ENGLISH_NAME  VARCHAR2(150 CHAR),
    EDUCATION_GROUP_ID             NUMBER(10)          NOT NULL,
    CREATED_BY                     NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE                   TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY               NUMBER(19),
    LAST_MODIFIED_DATE             TIMESTAMP(6),
    CONSTRAINT PK_EDU_DEGREES PRIMARY KEY (EDUCATION_DEGREE_ID),
    CONSTRAINT UK_EDU_DEGREES_CODE UNIQUE (EDUCATION_DEGREE_CODE),
    CONSTRAINT FK_EDUDEG_GROUP FOREIGN KEY (EDUCATION_GROUP_ID)
        REFERENCES GEO.EDUCATION_GROUPS (EDUCATION_GROUP_ID)
);

CREATE INDEX GEO.IX_EDUDEG_GROUP
    ON GEO.EDUCATION_DEGREES (EDUCATION_GROUP_ID);

CREATE SEQUENCE GEO.SEQ_EDUCATION_DEGREES
    START WITH 16 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.EDUCATION_FIELDS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.EDUCATION_FIELDS (
    EDUCATION_FIELD_ID            NUMBER(10)          NOT NULL,
    EDUCATION_FIELD_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    EDUCATION_FIELD_NAME          VARCHAR2(300 CHAR)  NOT NULL,
    EDUCATION_FIELD_ENGLISH_NAME  VARCHAR2(300 CHAR),
    EDUCATION_SUBGROUP_ID         NUMBER(10)          NOT NULL,
    IS_ACTIVE                    NUMBER(1)           DEFAULT 1 NOT NULL,
    CREATED_BY                   NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE                 TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY             NUMBER(19),
    LAST_MODIFIED_DATE           TIMESTAMP(6),
    CONSTRAINT PK_EDU_FIELDS PRIMARY KEY (EDUCATION_FIELD_ID),
    CONSTRAINT UK_EDU_FIELDS_CODE UNIQUE (EDUCATION_FIELD_CODE),
    CONSTRAINT CK_EDU_FIELDS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_EDUFLD_SUBGROUP FOREIGN KEY (EDUCATION_SUBGROUP_ID)
        REFERENCES GEO.EDUCATION_SUBGROUPS (EDUCATION_SUBGROUP_ID)
);

CREATE INDEX GEO.IX_EDUFLD_SUBGROUP
    ON GEO.EDUCATION_FIELDS (EDUCATION_SUBGROUP_ID);

CREATE SEQUENCE GEO.SEQ_EDUCATION_FIELDS
    START WITH 1036 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.EDUCATION_UNIVERSITIES
-- --------------------------------------------------------------------------
CREATE TABLE GEO.EDUCATION_UNIVERSITIES (
    EDUCATION_UNIVERSITY_ID            NUMBER(10)          NOT NULL,
    EDUCATION_UNIVERSITY_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    EDUCATION_UNIVERSITY_NAME          VARCHAR2(300 CHAR)  NOT NULL,
    EDUCATION_UNIVERSITY_ENGLISH_NAME  VARCHAR2(300 CHAR),
    UNIVERSITY_CATEGORY                NUMBER(3)           NOT NULL,
    UNIVERSITY_RANKING                 NUMBER(10)          NOT NULL,
    COUNTRY_ID                         NUMBER(10)          NOT NULL,
    PROVINCE_ID                        NUMBER(10),
    CITY_ID                            NUMBER(10),
    IS_ACTIVE                          NUMBER(1)           DEFAULT 1 NOT NULL,
    CREATED_BY                         NUMBER(19)          DEFAULT 1 NOT NULL,
    CREATED_DATE                       TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_BY                   NUMBER(19),
    LAST_MODIFIED_DATE                 TIMESTAMP(6),
    CONSTRAINT PK_EDU_UNIVERSITIES PRIMARY KEY (EDUCATION_UNIVERSITY_ID),
    CONSTRAINT UK_EDU_UNIVERSITY_CODE UNIQUE (EDUCATION_UNIVERSITY_CODE),
    CONSTRAINT CK_EDU_UNI_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_EDUUNI_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES GEO.COUNTRIES (COUNTRY_ID),
    CONSTRAINT FK_EDUUNI_PROVINCE FOREIGN KEY (PROVINCE_ID)
        REFERENCES GEO.PROVINCES (PROVINCE_ID),
    CONSTRAINT FK_EDUUNI_CITY FOREIGN KEY (CITY_ID)
        REFERENCES GEO.CITIES (CITY_ID)
);

CREATE INDEX GEO.IX_EDUUNI_COUNTRY
    ON GEO.EDUCATION_UNIVERSITIES (COUNTRY_ID);
CREATE INDEX GEO.IX_EDUUNI_PROVINCE
    ON GEO.EDUCATION_UNIVERSITIES (PROVINCE_ID);
CREATE INDEX GEO.IX_EDUUNI_CITY
    ON GEO.EDUCATION_UNIVERSITIES (CITY_ID);

CREATE SEQUENCE GEO.SEQ_EDUCATION_UNIVERSITIES
    START WITH 1443 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

PROMPT ================================================================
PROMPT Creating GEO occupation reference tables
PROMPT ================================================================

-- --------------------------------------------------------------------------
-- GEO.JOB_GROUPS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.JOB_GROUPS (
    JOB_GROUP_ID            NUMBER(10)          NOT NULL,
    JOB_GROUP_CODE          VARCHAR2(20 CHAR)   NOT NULL,
    JOB_GROUP_NAME          VARCHAR2(200 CHAR)  NOT NULL,
    JOB_GROUP_ENGLISH_NAME  VARCHAR2(200 CHAR),
    IS_ACTIVE               NUMBER(1)           DEFAULT 1 NOT NULL,
    CREATE_DATE             TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATE_USER_ID          NUMBER(19)          DEFAULT 1 NOT NULL,
    LAST_MODIFIED_BY        NUMBER(19),
    LAST_MODIFIED_DATE      TIMESTAMP(6),
    CONSTRAINT PK_JOB_GROUPS PRIMARY KEY (JOB_GROUP_ID),
    CONSTRAINT UK_JOB_GROUPS_CODE UNIQUE (JOB_GROUP_CODE),
    CONSTRAINT CK_JOB_GROUPS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE SEQUENCE GEO.SEQ_JOB_GROUPS
    START WITH 212 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

-- --------------------------------------------------------------------------
-- GEO.JOBS
-- --------------------------------------------------------------------------
CREATE TABLE GEO.JOBS (
    JOB_ID                NUMBER(10)          NOT NULL,
    JOB_CODE              VARCHAR2(20 CHAR)   NOT NULL,
    JOB_NAME              VARCHAR2(200 CHAR)  NOT NULL,
    JOB_ENGLISH_NAME      VARCHAR2(200 CHAR),
    JOB_GROUP_ID          NUMBER(10)          NOT NULL,
    IS_ACTIVE             NUMBER(1)           DEFAULT 1 NOT NULL,
    CREATE_DATE           TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATE_USER_ID        NUMBER(19)          DEFAULT 1 NOT NULL,
    LAST_MODIFIED_BY      NUMBER(19),
    LAST_MODIFIED_DATE    TIMESTAMP(6),
    CONSTRAINT PK_JOBS PRIMARY KEY (JOB_ID),
    CONSTRAINT UK_JOBS_CODE UNIQUE (JOB_CODE),
    CONSTRAINT CK_JOBS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_JOBS_GROUP FOREIGN KEY (JOB_GROUP_ID)
        REFERENCES GEO.JOB_GROUPS (JOB_GROUP_ID)
);

CREATE INDEX GEO.IX_JOBS_GROUP ON GEO.JOBS (JOB_GROUP_ID);

CREATE SEQUENCE GEO.SEQ_JOBS
    START WITH 5317 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE CACHE 20 NOCYCLE;

PROMPT ================================================================
PROMPT DDL completed successfully.
PROMPT Load data in parent-to-child order and COMMIT the transaction.
PROMPT ================================================================

COMMIT;
