package com.behsazan.corebanking.deposit.account.waveb.oracle;

import com.behsazan.corebanking.deposit.account.waveb.domain.DepositAccountWaveBModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.*;
import java.util.*;

@Repository
public class DepositAccountWaveBRepository {
    private final NamedParameterJdbcTemplate jdbc;
    private final String schema;
    public DepositAccountWaveBRepository(NamedParameterJdbcTemplate jdbc,@Value("${core-banking.oracle.business-schema:DPS2}") String schema){this.jdbc=jdbc;this.schema=id(schema);}

    public long next(String sequence){return jdbc.queryForObject("SELECT "+schema+"."+id(sequence)+".NEXTVAL FROM DUAL",Map.of(),Long.class);}
    public boolean accountExists(long accountId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT WHERE ACCOUNT_ID=:id",Map.of("id",accountId),Long.class);return n!=null&&n>0;}
    public boolean hasActiveContact(long accountId,String type,String value,LocalDate on){String sql="SELECT COUNT(*) FROM "+schema+".DEPOSIT_ACCOUNT_CONTACT WHERE ACCOUNT_ID=:aid AND CONTACT_TYPE_CODE=:type AND CONTACT_VALUE=:value AND VALID_FROM<=:on AND (VALID_TO IS NULL OR VALID_TO>=:on)";Long n=jdbc.queryForObject(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("type",type).addValue("value",value).addValue("on",Date.valueOf(on),Types.DATE),Long.class);return n!=null&&n>0;}

    public List<StatementTemplate> templates(){String sql="SELECT STATEMENT_TEMPLATE_ID,TEMPLATE_CODE,TEMPLATE_NAME,FORMAT_CODE,LANGUAGE_CODE,VERSION_NO,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_STATEMENT_TEMPLATE ORDER BY TEMPLATE_CODE,VERSION_NO DESC";return jdbc.query(sql,Map.of(),(r,n)->new StatementTemplate(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getLong(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10)));}
    public Optional<StatementTemplate> template(long id){String sql="SELECT STATEMENT_TEMPLATE_ID,TEMPLATE_CODE,TEMPLATE_NAME,FORMAT_CODE,LANGUAGE_CODE,VERSION_NO,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,RECORD_VERSION FROM "+schema+".DEPOSIT_STATEMENT_TEMPLATE WHERE STATEMENT_TEMPLATE_ID=:id";return jdbc.query(sql,Map.of("id",id),(r,n)->new StatementTemplate(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getLong(6),date(r.getDate(7)),date(r.getDate(8)),r.getString(9),r.getLong(10))).stream().findFirst();}
    public void retireOlderTemplates(String code,long keepId,String actor){jdbc.update("UPDATE "+schema+".DEPOSIT_STATEMENT_TEMPLATE SET STATUS_CODE='RETIRED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE TEMPLATE_CODE=:code AND STATEMENT_TEMPLATE_ID<>:id AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("code",code).addValue("id",keepId));}
    public void insertTemplate(long id,String code,String name,String format,String language,String body,long version,LocalDate from,LocalDate to,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_STATEMENT_TEMPLATE(STATEMENT_TEMPLATE_ID,TEMPLATE_CODE,TEMPLATE_NAME,FORMAT_CODE,LANGUAGE_CODE,TEMPLATE_BODY,VERSION_NO,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:code,:name,:format,:language,:body,:version,:from,:to,'ACTIVE',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("code",code).addValue("name",name).addValue("format",format).addValue("language",language).addValue("body",body,Types.CLOB).addValue("version",version).addValue("from",Date.valueOf(from),Types.DATE).addValue("to",to==null?null:Date.valueOf(to),Types.DATE).addValue("actor",actor));}

    public long insertStatementRequest(long id,long accountId,long templateId,LocalDate from,LocalDate to,String requestChannel,String deliveryChannel,String target,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_STATEMENT_REQUEST(STATEMENT_REQUEST_ID,ACCOUNT_ID,STATEMENT_TEMPLATE_ID,DATE_FROM,DATE_TO,REQUEST_CHANNEL_CODE,DELIVERY_CHANNEL_CODE,DELIVERY_TARGET,REQUEST_STATUS_CODE,REQUESTED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:tid,:df,:dt,:rc,:dc,:target,'PROCESSING',SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("tid",templateId).addValue("df",Date.valueOf(from),Types.DATE).addValue("dt",Date.valueOf(to),Types.DATE).addValue("rc",requestChannel).addValue("dc",deliveryChannel,Types.VARCHAR).addValue("target",target,Types.VARCHAR).addValue("actor",actor));return id;}
    public BigDecimal openingBalance(long accountId,LocalDate from){String sql="SELECT NVL(SUM(CASE WHEN DEBIT_CREDIT_CODE='CREDIT' THEN AMOUNT ELSE -AMOUNT END),0) FROM "+schema+".DEPOSIT_SUBLEDGER_ENTRY WHERE ACCOUNT_ID=:aid AND BOOKING_DATE<:df";BigDecimal b=jdbc.queryForObject(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("df",Date.valueOf(from),Types.DATE),BigDecimal.class);return b==null?BigDecimal.ZERO:b;}
    public List<StatementSourceLine> statementSourceLines(long accountId,LocalDate from,LocalDate to){String sql="SELECT S.SUBLEDGER_ENTRY_ID,S.TRANSACTION_ID,S.BOOKING_DATE,S.VALUE_DATE,NVL(T.REFERENCE_NO,S.SOURCE_ENTITY_TYPE||':'||TO_CHAR(S.SOURCE_ENTITY_ID)),S.DEBIT_CREDIT_CODE,S.AMOUNT FROM "+schema+".DEPOSIT_SUBLEDGER_ENTRY S LEFT JOIN "+schema+".DEPOSIT_TRANSACTION T ON T.TRANSACTION_ID=S.TRANSACTION_ID WHERE S.ACCOUNT_ID=:aid AND S.BOOKING_DATE BETWEEN :df AND :dt ORDER BY S.BOOKING_DATE,S.VALUE_DATE,S.SUBLEDGER_ENTRY_ID";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("df",Date.valueOf(from),Types.DATE).addValue("dt",Date.valueOf(to),Types.DATE),(r,n)->new StatementSourceLine(r.getLong(1),r.getObject(2,Long.class),date(r.getDate(3)),date(r.getDate(4)),r.getString(5),r.getString(6),r.getBigDecimal(7)));}
    public void insertStatement(long id,long requestId,long accountId,BigDecimal opening,BigDecimal closing,String format,String documentReference,String documentHash,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_STATEMENT(STATEMENT_ID,STATEMENT_REQUEST_ID,ACCOUNT_ID,OPENING_BALANCE,CLOSING_BALANCE,GENERATED_AT,FORMAT_CODE,DOCUMENT_REFERENCE,DOCUMENT_HASH,STATEMENT_STATUS_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:rid,:aid,:opening,:closing,SYSTIMESTAMP,:format,:doc,:hash,'GENERATED',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("rid",requestId).addValue("aid",accountId).addValue("opening",opening).addValue("closing",closing).addValue("format",format).addValue("doc",documentReference,Types.VARCHAR).addValue("hash",documentHash,Types.VARCHAR).addValue("actor",actor));}
    public void insertStatementItem(long id,long statementId,Long transactionId,long sequenceNo,LocalDate booking,LocalDate value,String description,BigDecimal debit,BigDecimal credit,BigDecimal running,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_STATEMENT_ITEM(STATEMENT_ITEM_ID,STATEMENT_ID,TRANSACTION_ID,SEQUENCE_NO,BOOKING_DATE,VALUE_DATE,DESCRIPTION,DEBIT_AMOUNT,CREDIT_AMOUNT,RUNNING_BALANCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:sid,:tx,:seq,:booking,:value,:description,:debit,:credit,:running,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("sid",statementId).addValue("tx",transactionId,Types.NUMERIC).addValue("seq",sequenceNo).addValue("booking",Date.valueOf(booking),Types.DATE).addValue("value",value==null?null:Date.valueOf(value),Types.DATE).addValue("description",description,Types.VARCHAR).addValue("debit",debit).addValue("credit",credit).addValue("running",running).addValue("actor",actor));}
    public void completeStatementRequest(long requestId,String actor){jdbc.update("UPDATE "+schema+".DEPOSIT_STATEMENT_REQUEST SET REQUEST_STATUS_CODE='COMPLETED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE STATEMENT_REQUEST_ID=:id",new MapSqlParameterSource().addValue("actor",actor).addValue("id",requestId));}
    public long nextDeliveryAttempt(long statementId,String channel){Long v=jdbc.queryForObject("SELECT NVL(MAX(ATTEMPT_NO),0)+1 FROM "+schema+".DEPOSIT_STATEMENT_DELIVERY WHERE STATEMENT_ID=:sid AND CHANNEL_CODE=:ch",new MapSqlParameterSource().addValue("sid",statementId).addValue("ch",channel),Long.class);return v==null?1:v;}
    public void insertDelivery(long id,long statementId,String channel,String destination,long attempt,String status,String providerRef,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_STATEMENT_DELIVERY(STATEMENT_DELIVERY_ID,STATEMENT_ID,CHANNEL_CODE,DESTINATION,ATTEMPT_NO,DELIVERY_STATUS_CODE,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:sid,:ch,:dest,:attempt,:status,SYSTIMESTAMP,CASE WHEN :status='DELIVERED' THEN SYSTIMESTAMP ELSE NULL END,:provider,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("sid",statementId).addValue("ch",channel).addValue("dest",destination,Types.VARCHAR).addValue("attempt",attempt).addValue("status",status).addValue("provider",providerRef,Types.VARCHAR).addValue("actor",actor));}
    public void markStatementDelivered(long statementId,String actor){jdbc.update("UPDATE "+schema+".DEPOSIT_STATEMENT SET STATEMENT_STATUS_CODE='DELIVERED',UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE STATEMENT_ID=:id",new MapSqlParameterSource().addValue("actor",actor).addValue("id",statementId));}
    public List<Statement> statements(long accountId){String sql="SELECT S.STATEMENT_ID,S.STATEMENT_REQUEST_ID,S.ACCOUNT_ID,R.DATE_FROM,R.DATE_TO,R.REQUEST_CHANNEL_CODE,R.DELIVERY_CHANNEL_CODE,R.DELIVERY_TARGET,S.OPENING_BALANCE,S.CLOSING_BALANCE,S.FORMAT_CODE,S.STATEMENT_STATUS_CODE,S.GENERATED_AT FROM "+schema+".DEPOSIT_STATEMENT S JOIN "+schema+".DEPOSIT_STATEMENT_REQUEST R ON R.STATEMENT_REQUEST_ID=S.STATEMENT_REQUEST_ID WHERE S.ACCOUNT_ID=:aid ORDER BY S.STATEMENT_ID DESC FETCH FIRST 20 ROWS ONLY";return jdbc.query(sql,Map.of("aid",accountId),(r,n)->new Statement(r.getLong(1),r.getLong(2),r.getLong(3),date(r.getDate(4)),date(r.getDate(5)),r.getString(6),r.getString(7),r.getString(8),r.getBigDecimal(9),r.getBigDecimal(10),r.getString(11),r.getString(12),offset(r.getTimestamp(13)),statementItems(r.getLong(1)),statementDeliveries(r.getLong(1))));}
    public Optional<Statement> statement(long accountId,long statementId){return statements(accountId).stream().filter(x->x.statementId()==statementId).findFirst();}
    private List<StatementItem> statementItems(long statementId){String sql="SELECT STATEMENT_ITEM_ID,STATEMENT_ID,TRANSACTION_ID,SEQUENCE_NO,BOOKING_DATE,VALUE_DATE,DESCRIPTION,DEBIT_AMOUNT,CREDIT_AMOUNT,RUNNING_BALANCE FROM "+schema+".DEPOSIT_STATEMENT_ITEM WHERE STATEMENT_ID=:id ORDER BY SEQUENCE_NO";return jdbc.query(sql,Map.of("id",statementId),(r,n)->new StatementItem(r.getLong(1),r.getLong(2),r.getObject(3,Long.class),r.getLong(4),date(r.getDate(5)),date(r.getDate(6)),r.getString(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getBigDecimal(10)));}
    private List<StatementDelivery> statementDeliveries(long statementId){String sql="SELECT STATEMENT_DELIVERY_ID,STATEMENT_ID,CHANNEL_CODE,DESTINATION,ATTEMPT_NO,DELIVERY_STATUS_CODE,SENT_AT,DELIVERED_AT,PROVIDER_REFERENCE,ERROR_CODE,ERROR_MESSAGE FROM "+schema+".DEPOSIT_STATEMENT_DELIVERY WHERE STATEMENT_ID=:id ORDER BY ATTEMPT_NO";return jdbc.query(sql,Map.of("id",statementId),(r,n)->new StatementDelivery(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5),r.getString(6),offset(r.getTimestamp(7)),offset(r.getTimestamp(8)),r.getString(9),r.getString(10),r.getString(11)));}

    public void insertLimit(long id,long accountId,String type,String txType,String channel,BigDecimal amount,Long count,String periodUnit,Integer periodValue,String source,OffsetDateTime from,OffsetDateTime to,String originSystem,String originModule,String originRequest,String revocationPolicy,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_LIMIT(ACCOUNT_LIMIT_ID,ACCOUNT_ID,LIMIT_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,AMOUNT_LIMIT,COUNT_LIMIT,PERIOD_UNIT_CODE,PERIOD_VALUE,SOURCE_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,REVOCATION_POLICY_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:type,:tx,:ch,:amount,:count,:unit,:pval,:source,NVL(:ef,CAST(SYSTIMESTAMP AS TIMESTAMP)),:et,'ACTIVE',:os,:om,:oref,:policy,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("type",type).addValue("tx",txType,Types.VARCHAR).addValue("ch",channel,Types.VARCHAR).addValue("amount",amount,Types.NUMERIC).addValue("count",count,Types.NUMERIC).addValue("unit",periodUnit,Types.VARCHAR).addValue("pval",periodValue,Types.NUMERIC).addValue("source",source).addValue("ef",ts(from),Types.TIMESTAMP).addValue("et",ts(to),Types.TIMESTAMP).addValue("os",originSystem).addValue("om",originModule,Types.VARCHAR).addValue("oref",originRequest,Types.VARCHAR).addValue("policy",revocationPolicy).addValue("actor",actor));}
    public int revokeLimit(long accountId,long limitId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_LIMIT SET STATUS_CODE='REVOKED',EFFECTIVE_TO=NVL(EFFECTIVE_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_LIMIT_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",limitId).addValue("aid",accountId));}
    public List<AccountLimit> limits(long accountId){String sql="SELECT ACCOUNT_LIMIT_ID,ACCOUNT_ID,LIMIT_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,AMOUNT_LIMIT,COUNT_LIMIT,PERIOD_UNIT_CODE,PERIOD_VALUE,SOURCE_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,REVOCATION_POLICY_CODE,APPROVAL_REQUEST_ID,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_LIMIT WHERE ACCOUNT_ID=:aid ORDER BY ACCOUNT_LIMIT_ID DESC";return jdbc.query(sql,Map.of("aid",accountId),(r,n)->new AccountLimit(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getObject(7,Long.class),r.getString(8),r.getObject(9,Integer.class),r.getString(10),offset(r.getTimestamp(11)),offset(r.getTimestamp(12)),r.getString(13),r.getString(14),r.getString(15),r.getString(16),r.getString(17),r.getObject(18,Long.class),r.getLong(19)));}
    public List<UsageLimit> activeLimitsForUsage(long accountId,String txType,String channel,LocalDate booking){String sql="SELECT ACCOUNT_LIMIT_ID,LIMIT_TYPE_CODE,TRANSACTION_TYPE_CODE,CHANNEL_CODE,PERIOD_UNIT_CODE,PERIOD_VALUE,EFFECTIVE_FROM,EFFECTIVE_TO FROM "+schema+".DEPOSIT_ACCOUNT_LIMIT WHERE ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE' AND EFFECTIVE_FROM<=SYSTIMESTAMP AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=SYSTIMESTAMP) AND (TRANSACTION_TYPE_CODE IS NULL OR TRANSACTION_TYPE_CODE=:tx) AND (CHANNEL_CODE IS NULL OR CHANNEL_CODE=:ch)";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("tx",txType).addValue("ch",channel),(r,n)->new UsageLimit(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getObject(6,Integer.class),offset(r.getTimestamp(7)),offset(r.getTimestamp(8))));}
    public UsageTotals postedUsage(long accountId,String txType,String channel,LocalDate from,LocalDate to,OffsetDateTime effectiveFrom,OffsetDateTime effectiveTo){String sql="SELECT NVL(SUM(X.AMOUNT),0),COUNT(*),MAX(X.TRANSACTION_ID) KEEP (DENSE_RANK LAST ORDER BY X.POSTED_AT,X.TRANSACTION_ID) FROM (SELECT T.TRANSACTION_ID,T.AMOUNT,MAX(H.EFFECTIVE_AT) POSTED_AT FROM "+schema+".DEPOSIT_TRANSACTION T JOIN "+schema+".DEPOSIT_TRANSACTION_STATUS_HISTORY H ON H.TRANSACTION_ID=T.TRANSACTION_ID AND H.TO_STATUS_CODE='POSTED' WHERE T.ACCOUNT_ID=:aid AND T.TRANSACTION_STATUS_CODE='POSTED' AND (:tx IS NULL OR T.TRANSACTION_TYPE_CODE=:tx) AND (:ch IS NULL OR T.CHANNEL_CODE=:ch) AND T.BOOKING_DATE BETWEEN :df AND :dt GROUP BY T.TRANSACTION_ID,T.AMOUNT HAVING MAX(H.EFFECTIVE_AT)>=:ef AND (:et IS NULL OR MAX(H.EFFECTIVE_AT)<=:et)) X";return jdbc.query(sql,new MapSqlParameterSource().addValue("aid",accountId).addValue("tx",txType,Types.VARCHAR).addValue("ch",channel,Types.VARCHAR).addValue("df",Date.valueOf(from),Types.DATE).addValue("dt",Date.valueOf(to),Types.DATE).addValue("ef",ts(effectiveFrom),Types.TIMESTAMP).addValue("et",ts(effectiveTo),Types.TIMESTAMP),(r,n)->new UsageTotals(r.getBigDecimal(1),r.getLong(2),r.getObject(3,Long.class))).stream().findFirst().orElse(new UsageTotals(BigDecimal.ZERO,0,null));}
    public void upsertLimitUsage(long limitId,long accountId,OffsetDateTime start,OffsetDateTime end,BigDecimal usedAmount,long usedCount,Long lastTxId,String actor){String q="SELECT ACCOUNT_LIMIT_USAGE_ID FROM "+schema+".DEPOSIT_ACCOUNT_LIMIT_USAGE WHERE ACCOUNT_LIMIT_ID=:lid AND ACCOUNT_ID=:aid AND PERIOD_START=:ps AND PERIOD_END=:pe FOR UPDATE";MapSqlParameterSource p=new MapSqlParameterSource().addValue("lid",limitId).addValue("aid",accountId).addValue("ps",Timestamp.from(start.toInstant())).addValue("pe",Timestamp.from(end.toInstant()));List<Long> ids=jdbc.query(q,p,(r,n)->r.getLong(1));if(ids.isEmpty()){long id=next("SEQ_DEPOSIT_ACCOUNT_LIMIT_USAGE");jdbc.update("INSERT INTO "+schema+".DEPOSIT_ACCOUNT_LIMIT_USAGE(ACCOUNT_LIMIT_USAGE_ID,ACCOUNT_LIMIT_ID,ACCOUNT_ID,PERIOD_START,PERIOD_END,USED_AMOUNT,USED_COUNT,LAST_TRANSACTION_ID,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:lid,:aid,:ps,:pe,:amount,:count,:tx,SYSTIMESTAMP,:actor,1)",p.addValue("id",id).addValue("amount",usedAmount).addValue("count",usedCount).addValue("tx",lastTxId,Types.NUMERIC).addValue("actor",actor));}else{jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_LIMIT_USAGE SET USED_AMOUNT=:amount,USED_COUNT=:count,LAST_TRANSACTION_ID=:tx,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_LIMIT_USAGE_ID=:id",new MapSqlParameterSource().addValue("amount",usedAmount).addValue("count",usedCount).addValue("tx",lastTxId,Types.NUMERIC).addValue("actor",actor).addValue("id",ids.getFirst()));}}
    public List<AccountLimitUsage> usages(long accountId){String sql="SELECT ACCOUNT_LIMIT_USAGE_ID,ACCOUNT_LIMIT_ID,ACCOUNT_ID,PERIOD_START,PERIOD_END,USED_AMOUNT,USED_COUNT,LAST_TRANSACTION_ID,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_LIMIT_USAGE WHERE ACCOUNT_ID=:aid ORDER BY PERIOD_START DESC,ACCOUNT_LIMIT_USAGE_ID DESC FETCH FIRST 50 ROWS ONLY";return jdbc.query(sql,Map.of("aid",accountId),(r,n)->new AccountLimitUsage(r.getLong(1),r.getLong(2),r.getLong(3),offset(r.getTimestamp(4)),offset(r.getTimestamp(5)),r.getBigDecimal(6),r.getLong(7),r.getObject(8,Long.class),r.getLong(9)));}

    public void insertRestriction(long id,long accountId,String txType,String channel,String direction,String mode,BigDecimal maxAmount,String source,String authorityRef,OffsetDateTime from,OffsetDateTime to,String originSystem,String originModule,String originRequest,String releasePolicy,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION(ACCOUNT_TX_RESTRICTION_ID,ACCOUNT_ID,TRANSACTION_TYPE_CODE,CHANNEL_CODE,DIRECTION_CODE,RESTRICTION_MODE_CODE,MAX_AMOUNT,SOURCE_CODE,AUTHORITY_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,RELEASE_POLICY_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:aid,:tx,:ch,:dir,:mode,:max,:source,:auth,NVL(:vf,CAST(SYSTIMESTAMP AS TIMESTAMP)),:vt,'ACTIVE',:os,:om,:oref,:policy,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("aid",accountId).addValue("tx",txType).addValue("ch",channel,Types.VARCHAR).addValue("dir",direction,Types.VARCHAR).addValue("mode",mode).addValue("max",maxAmount,Types.NUMERIC).addValue("source",source).addValue("auth",authorityRef,Types.VARCHAR).addValue("vf",ts(from)).addValue("vt",ts(to),Types.TIMESTAMP).addValue("os",originSystem).addValue("om",originModule,Types.VARCHAR).addValue("oref",originRequest,Types.VARCHAR).addValue("policy",releasePolicy).addValue("actor",actor));}
    public int releaseRestriction(long accountId,long restrictionId,String actor){return jdbc.update("UPDATE "+schema+".DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION SET STATUS_CODE='RELEASED',VALID_TO=NVL(VALID_TO,SYSTIMESTAMP),UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE ACCOUNT_TX_RESTRICTION_ID=:id AND ACCOUNT_ID=:aid AND STATUS_CODE='ACTIVE'",new MapSqlParameterSource().addValue("actor",actor).addValue("id",restrictionId).addValue("aid",accountId));}
    public List<TransactionRestriction> restrictions(long accountId){String sql="SELECT ACCOUNT_TX_RESTRICTION_ID,ACCOUNT_ID,TRANSACTION_TYPE_CODE,CHANNEL_CODE,DIRECTION_CODE,RESTRICTION_MODE_CODE,MAX_AMOUNT,SOURCE_CODE,AUTHORITY_REFERENCE,VALID_FROM,VALID_TO,STATUS_CODE,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,RELEASE_POLICY_CODE,APPROVAL_REQUEST_ID,RECORD_VERSION FROM "+schema+".DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION WHERE ACCOUNT_ID=:aid ORDER BY ACCOUNT_TX_RESTRICTION_ID DESC";return jdbc.query(sql,Map.of("aid",accountId),(r,n)->new TransactionRestriction(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10)),offset(r.getTimestamp(11)),r.getString(12),r.getString(13),r.getString(14),r.getString(15),r.getString(16),r.getObject(17,Long.class),r.getLong(18)));}

    public void insertMaturityRun(long id,LocalDate businessDate,String mode,String actor){jdbc.update("INSERT INTO "+schema+".DEPOSIT_MATURITY_PROCESS_RUN(MATURITY_PROCESS_RUN_ID,BUSINESS_DATE,RUN_MODE_CODE,STATUS_CODE,TOTAL_COUNT,PROCESSED_COUNT,FAILED_COUNT,STARTED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:bd,:mode,'PROCESSING',0,0,0,SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)",new MapSqlParameterSource().addValue("id",id).addValue("bd",Date.valueOf(businessDate)).addValue("mode",mode).addValue("actor",actor));}
    public List<DueTerm> dueTerms(LocalDate businessDate){String sql="SELECT TERM_CONTRACT_ID,ACCOUNT_ID,MATURITY_DATE,MATURITY_INSTRUCTION_CODE,PRINCIPAL_AMOUNT FROM "+schema+".DEPOSIT_TERM_CONTRACT WHERE STATUS_CODE='ACTIVE' AND MATURITY_DATE<=:bd ORDER BY MATURITY_DATE,TERM_CONTRACT_ID";return jdbc.query(sql,new MapSqlParameterSource().addValue("bd",Date.valueOf(businessDate)),(r,n)->new DueTerm(r.getLong(1),r.getLong(2),date(r.getDate(3)),r.getString(4),r.getBigDecimal(5)));}
    public Optional<ExistingMaturityEvent> maturityEvent(long termId,LocalDate maturity){String sql="SELECT MATURITY_EVENT_ID,ACTION_RESULT_CODE FROM "+schema+".DEPOSIT_MATURITY_EVENT WHERE TERM_CONTRACT_ID=:tid AND MATURITY_DATE=:md";return jdbc.query(sql,new MapSqlParameterSource().addValue("tid",termId).addValue("md",Date.valueOf(maturity)),(r,n)->new ExistingMaturityEvent(r.getLong(1),r.getString(2))).stream().findFirst();}
    public long insertPendingMaturityEvent(long id,DueTerm t,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_MATURITY_EVENT(MATURITY_EVENT_ID,TERM_CONTRACT_ID,ACCOUNT_ID,MATURITY_DATE,INSTRUCTION_CODE,PRINCIPAL_AMOUNT,ACTION_RESULT_CODE,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:tid,:aid,:md,:ins,:p,'PENDING',SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("tid",t.termContractId()).addValue("aid",t.accountId()).addValue("md",Date.valueOf(t.maturityDate())).addValue("ins",t.instructionCode()).addValue("p",t.principalAmount()).addValue("actor",actor));return id;}
    public void insertMaturityItem(long id,long runId,DueTerm t,Long eventId,String status,String errorCode,String errorMessage,String actor){String sql="INSERT INTO "+schema+".DEPOSIT_MATURITY_PROCESS_ITEM(MATURITY_PROCESS_ITEM_ID,MATURITY_PROCESS_RUN_ID,ACCOUNT_ID,TERM_CONTRACT_ID,MATURITY_EVENT_ID,ACTION_CODE,ITEM_STATUS_CODE,ERROR_CODE,ERROR_MESSAGE,PROCESSED_AT,CREATED_AT,CREATED_BY,RECORD_VERSION) VALUES(:id,:run,:aid,:tid,:event,:action,:status,:code,:msg,SYSTIMESTAMP,SYSTIMESTAMP,:actor,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("run",runId).addValue("aid",t.accountId()).addValue("tid",t.termContractId()).addValue("event",eventId,Types.NUMERIC).addValue("action",t.instructionCode()).addValue("status",status).addValue("code",errorCode,Types.VARCHAR).addValue("msg",errorMessage,Types.VARCHAR).addValue("actor",actor));}
    public void completeMaturityRun(long runId,long total,long processed,long failed,String actor){String status=failed==0?"COMPLETED":processed==0?"FAILED":"PARTIAL";jdbc.update("UPDATE "+schema+".DEPOSIT_MATURITY_PROCESS_RUN SET STATUS_CODE=:status,TOTAL_COUNT=:total,PROCESSED_COUNT=:processed,FAILED_COUNT=:failed,FINISHED_AT=SYSTIMESTAMP,UPDATED_AT=SYSTIMESTAMP,UPDATED_BY=:actor,RECORD_VERSION=RECORD_VERSION+1 WHERE MATURITY_PROCESS_RUN_ID=:id",new MapSqlParameterSource().addValue("status",status).addValue("total",total).addValue("processed",processed).addValue("failed",failed).addValue("actor",actor).addValue("id",runId));}
    public MaturityProcessRun maturityRun(long runId){String sql="SELECT MATURITY_PROCESS_RUN_ID,BUSINESS_DATE,RUN_MODE_CODE,STATUS_CODE,TOTAL_COUNT,PROCESSED_COUNT,FAILED_COUNT,STARTED_AT,FINISHED_AT FROM "+schema+".DEPOSIT_MATURITY_PROCESS_RUN WHERE MATURITY_PROCESS_RUN_ID=:id";return jdbc.query(sql,Map.of("id",runId),(r,n)->new MaturityProcessRun(r.getLong(1),date(r.getDate(2)),r.getString(3),r.getString(4),r.getLong(5),r.getLong(6),r.getLong(7),offset(r.getTimestamp(8)),offset(r.getTimestamp(9)),maturityItems(r.getLong(1)))).stream().findFirst().orElse(null);}
    public List<MaturityProcessRun> recentMaturityRuns(){String sql="SELECT MATURITY_PROCESS_RUN_ID,BUSINESS_DATE,RUN_MODE_CODE,STATUS_CODE,TOTAL_COUNT,PROCESSED_COUNT,FAILED_COUNT,STARTED_AT,FINISHED_AT FROM "+schema+".DEPOSIT_MATURITY_PROCESS_RUN ORDER BY MATURITY_PROCESS_RUN_ID DESC FETCH FIRST 10 ROWS ONLY";return jdbc.query(sql,Map.of(),(r,n)->new MaturityProcessRun(r.getLong(1),date(r.getDate(2)),r.getString(3),r.getString(4),r.getLong(5),r.getLong(6),r.getLong(7),offset(r.getTimestamp(8)),offset(r.getTimestamp(9)),maturityItems(r.getLong(1))));}
    private List<MaturityProcessItem> maturityItems(long runId){String sql="SELECT MATURITY_PROCESS_ITEM_ID,MATURITY_PROCESS_RUN_ID,ACCOUNT_ID,TERM_CONTRACT_ID,MATURITY_EVENT_ID,ACTION_CODE,ITEM_STATUS_CODE,ERROR_CODE,ERROR_MESSAGE,PROCESSED_AT FROM "+schema+".DEPOSIT_MATURITY_PROCESS_ITEM WHERE MATURITY_PROCESS_RUN_ID=:id ORDER BY MATURITY_PROCESS_ITEM_ID";return jdbc.query(sql,Map.of("id",runId),(r,n)->new MaturityProcessItem(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getObject(5,Long.class),r.getString(6),r.getString(7),r.getString(8),r.getString(9),offset(r.getTimestamp(10))));}

    public Optional<IdemRow> idempotency(String key){String sql="SELECT IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,RESULT_REFERENCE FROM "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY WHERE IDEMPOTENCY_KEY=:k";return jdbc.query(sql,Map.of("k",key),(r,n)->new IdemRow(r.getString(1),r.getObject(2,Long.class),r.getString(3),r.getString(4),r.getString(5),r.getString(6))).stream().findFirst();}
    public void claimIdempotency(long id,String key,Long accountId,String operation,String hash,String actor,String correlation){String sql="INSERT INTO "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY(OPERATION_IDEMPOTENCY_ID,IDEMPOTENCY_KEY,ACCOUNT_ID,OPERATION_TYPE_CODE,PAYLOAD_HASH,PROCESSING_STATUS_CODE,REQUESTED_BY_USER_ID,REQUESTED_AT,ORIGIN_SYSTEM_CODE,ORIGIN_MODULE_CODE,ORIGIN_REQUEST_REF,CORRELATION_ID,RECORD_VERSION) VALUES(:id,:key,:aid,:op,:hash,'IN_PROGRESS',:actor,SYSTIMESTAMP,'CORE_BANKING','WAVE_B',:key,:corr,1)";jdbc.update(sql,new MapSqlParameterSource().addValue("id",id).addValue("key",key).addValue("aid",accountId,Types.NUMERIC).addValue("op",operation).addValue("hash",hash).addValue("actor",actor).addValue("corr",correlation,Types.VARCHAR));}
    public void completeIdempotency(String key,String result){jdbc.update("UPDATE "+schema+".DEPOSIT_OPERATION_IDEMPOTENCY SET PROCESSING_STATUS_CODE='COMPLETED',RESULT_REFERENCE=:ref,COMPLETED_AT=SYSTIMESTAMP,RECORD_VERSION=RECORD_VERSION+1 WHERE IDEMPOTENCY_KEY=:key",new MapSqlParameterSource().addValue("ref",result).addValue("key",key));}

    public record StatementSourceLine(long subledgerEntryId,Long transactionId,LocalDate bookingDate,LocalDate valueDate,String description,String debitCreditCode,BigDecimal amount){}
    public record UsageLimit(long limitId,String limitType,String transactionType,String channel,String periodUnit,Integer periodValue,OffsetDateTime effectiveFrom,OffsetDateTime effectiveTo){}
    public record UsageTotals(BigDecimal amount,long count,Long lastTransactionId){}
    public record DueTerm(long termContractId,long accountId,LocalDate maturityDate,String instructionCode,BigDecimal principalAmount){}
    public record ExistingMaturityEvent(long maturityEventId,String actionResultCode){}
    public record IdemRow(String key,Long accountId,String operation,String payloadHash,String status,String resultReference){}

    private static String id(String v){if(v==null||!v.matches("[A-Za-z0-9_]+"))throw new IllegalArgumentException("Oracle identifier نامعتبر است: "+v);return v.toUpperCase(Locale.ROOT);}
    private static LocalDate date(Date d){return d==null?null:d.toLocalDate();}
    private static OffsetDateTime offset(Timestamp t){return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}
    private static Timestamp ts(OffsetDateTime v){return v==null?null:Timestamp.from(v.toInstant());}
}
