-- CAL2 / 0.11.0: versioned BLOB images for calendar events and occasions.
-- Requirement: one active image per EVENT; uploading a new image deactivates prior versions without deleting history.
-- Safe to rerun.
SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME='EVENT_MEDIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CAL2.EVENT_MEDIA (
        EVENT_MEDIA_ID          NUMBER(19) NOT NULL,
        EVENT_ID                NUMBER(19) NOT NULL,
        DISPLAY_YEAR_NO         NUMBER(6) NOT NULL,
        DISPLAY_CALENDAR_CODE   VARCHAR2(20 CHAR) DEFAULT 'PERSIAN' NOT NULL,
        FILE_NAME               VARCHAR2(250 CHAR) NOT NULL,
        MIME_TYPE               VARCHAR2(100 CHAR) NOT NULL,
        FILE_SIZE_BYTES         NUMBER(19) NOT NULL,
        IMAGE_CONTENT           BLOB NOT NULL,
        CAPTION_FA              VARCHAR2(500 CHAR),
        ALT_TEXT_FA             VARCHAR2(500 CHAR),
        ACTIVE_FLAG             CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CREATED_BY              VARCHAR2(120 CHAR),
        DEACTIVATED_AT          TIMESTAMP(6),
        DEACTIVATED_BY          VARCHAR2(120 CHAR),
        CONSTRAINT PK_CAL2_EVENT_MEDIA PRIMARY KEY (EVENT_MEDIA_ID),
        CONSTRAINT FK_CAL2_EVENT_MEDIA_EVENT FOREIGN KEY (EVENT_ID) REFERENCES CAL2.EVENT (EVENT_ID),
        CONSTRAINT CK_CAL2_EVENT_MEDIA_CAL CHECK (DISPLAY_CALENDAR_CODE IN ('PERSIAN','GREGORIAN','ISLAMIC')),
        CONSTRAINT CK_CAL2_EVENT_MEDIA_YEAR CHECK (DISPLAY_YEAR_NO > 0),
        CONSTRAINT CK_CAL2_EVENT_MEDIA_SIZE CHECK (FILE_SIZE_BYTES > 0),
        CONSTRAINT CK_CAL2_EVENT_MEDIA_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
      )
    ~';
    DBMS_OUTPUT.PUT_LINE('Created CAL2.EVENT_MEDIA');
  ELSE
    DBMS_OUTPUT.PUT_LINE('CAL2.EVENT_MEDIA already exists');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='CAL2' AND SEQUENCE_NAME='SEQ_CAL2_EVENT_MEDIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE CAL2.SEQ_CAL2_EVENT_MEDIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('Created CAL2.SEQ_CAL2_EVENT_MEDIA');
  ELSE
    DBMS_OUTPUT.PUT_LINE('CAL2.SEQ_CAL2_EVENT_MEDIA already exists');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES WHERE OWNER='CAL2' AND INDEX_NAME='IX_CAL2_EVENT_MEDIA_EVENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX CAL2.IX_CAL2_EVENT_MEDIA_EVENT ON CAL2.EVENT_MEDIA (EVENT_ID, CREATED_AT)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES WHERE OWNER='CAL2' AND INDEX_NAME='UQ_CAL2_EVENT_MEDIA_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX CAL2.UQ_CAL2_EVENT_MEDIA_ACTIVE ON CAL2.EVENT_MEDIA (CASE WHEN ACTIVE_FLAG='Y' THEN EVENT_ID END)~';
  END IF;
END;
/

COMMENT ON TABLE CAL2.EVENT_MEDIA IS 'نسخه‌های تصویری رویداد/مناسبت برای نمایش در ورود و داشبورد؛ تاریخچه حذف نمی‌شود و فقط یک نسخه Active برای هر EVENT مجاز است';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.EVENT_MEDIA_ID IS 'شناسه نسخه تصویر مناسبت';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.EVENT_ID IS 'شناسه رویداد/مناسبت';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.DISPLAY_YEAR_NO IS 'سال محتوایی تصویر برای تاریخچه و گزارش';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.DISPLAY_CALENDAR_CODE IS 'تقویم سال محتوایی: PERSIAN/GREGORIAN/ISLAMIC';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.FILE_NAME IS 'نام فایل تصویر بارگذاری‌شده';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.MIME_TYPE IS 'نوع MIME تصویر';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.FILE_SIZE_BYTES IS 'حجم تصویر به بایت';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.IMAGE_CONTENT IS 'محتوای تصویر در قالب BLOB';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.CAPTION_FA IS 'عنوان یا توضیح فارسی تصویر';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.ALT_TEXT_FA IS 'متن جایگزین دسترس‌پذیری تصویر';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.ACTIVE_FLAG IS 'نسخه فعال نمایش؛ Upload جدید نسخه قبلی همان EVENT را غیرفعال می‌کند';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.CREATED_AT IS 'زمان ثبت نسخه تصویر';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.CREATED_BY IS 'کاربر ثبت‌کننده در صورت وجود Context احراز هویت';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.DEACTIVATED_AT IS 'زمان غیرفعال‌شدن نسخه قبلی';
COMMENT ON COLUMN CAL2.EVENT_MEDIA.DEACTIVATED_BY IS 'کاربر غیرفعال‌کننده در صورت وجود Context احراز هویت';

PROMPT === EVENT_MEDIA verification ===
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME='EVENT_MEDIA';
SELECT INDEX_NAME, UNIQUENESS FROM ALL_INDEXES WHERE OWNER='CAL2' AND INDEX_NAME IN ('IX_CAL2_EVENT_MEDIA_EVENT','UQ_CAL2_EVENT_MEDIA_ACTIVE') ORDER BY INDEX_NAME;
SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER='CAL2' AND SEQUENCE_NAME='SEQ_CAL2_EVENT_MEDIA';
PROMPT CAL2 EVENT_MEDIA migration completed.
