-- FIX93 / 0.3.85: range-based business-calendar schedules, weekly working hours and single-day exceptions.
-- Existing BUSINESS_CALENDAR_DAY becomes the materialized/resolved output of these policies.
-- Safe to rerun: tables, columns, constraints and indexes are checked before creation.
SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME='BUSINESS_CALENDAR_SCHEDULE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CAL2.BUSINESS_CALENDAR_SCHEDULE (
        BUSINESS_CALENDAR_SCHEDULE_ID NUMBER(19) NOT NULL,
        BUSINESS_CALENDAR_ID          NUMBER(19) NOT NULL,
        SCHEDULE_CODE                 VARCHAR2(80 CHAR) NOT NULL,
        NAME_FA                       VARCHAR2(200 CHAR) NOT NULL,
        NAME_EN                       VARCHAR2(200 CHAR),
        EFFECTIVE_FROM                DATE NOT NULL,
        EFFECTIVE_TO                  DATE NOT NULL,
        STATUS                        VARCHAR2(30 CHAR) DEFAULT 'DRAFT' NOT NULL,
        PRIORITY_NO                   NUMBER(9) DEFAULT 100 NOT NULL,
        SOURCE_ID                     NUMBER(19),
        SOURCE_REFERENCE              VARCHAR2(250 CHAR),
        SOURCE_DATE                   DATE,
        SOURCE_URI                    VARCHAR2(1000 CHAR),
        DESCRIPTION                   VARCHAR2(2000 CHAR),
        ACTIVE_FLAG                   CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        CONSTRAINT PK_CAL2_BUS_CAL_SCHED PRIMARY KEY (BUSINESS_CALENDAR_SCHEDULE_ID),
        CONSTRAINT UQ_CAL2_BUS_CAL_SCHED UNIQUE (BUSINESS_CALENDAR_ID, SCHEDULE_CODE),
        CONSTRAINT FK_CAL2_BCS_CAL FOREIGN KEY (BUSINESS_CALENDAR_ID) REFERENCES CAL2.BUSINESS_CALENDAR (BUSINESS_CALENDAR_ID),
        CONSTRAINT FK_CAL2_BCS_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
        CONSTRAINT CK_CAL2_BCS_STATUS CHECK (STATUS IN ('DRAFT','ACTIVE','SUPERSEDED')),
        CONSTRAINT CK_CAL2_BCS_PRIORITY CHECK (PRIORITY_NO >= 0),
        CONSTRAINT CK_CAL2_BCS_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCS_RANGE CHECK (EFFECTIVE_TO >= EFFECTIVE_FROM)
      )
    ~';
    DBMS_OUTPUT.PUT_LINE('Created CAL2.BUSINESS_CALENDAR_SCHEDULE');
  ELSE DBMS_OUTPUT.PUT_LINE('CAL2.BUSINESS_CALENDAR_SCHEDULE already exists'); END IF;
END;
/

ALTER TABLE CAL2.BUSINESS_CALENDAR_SCHEDULE MODIFY (STATUS DEFAULT 'DRAFT');

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME='BUSINESS_CALENDAR_SCHEDULE_DAY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY (
        BUSINESS_CALENDAR_SCHEDULE_DAY_ID NUMBER(19) NOT NULL,
        BUSINESS_CALENDAR_SCHEDULE_ID     NUMBER(19) NOT NULL,
        WEEKDAY_ID                        NUMBER(19) NOT NULL,
        DAY_STATUS                        VARCHAR2(30 CHAR) DEFAULT 'OPEN' NOT NULL,
        STAFF_START_TIME                  VARCHAR2(5 CHAR),
        STAFF_END_TIME                    VARCHAR2(5 CHAR),
        CUSTOMER_OPEN_TIME                VARCHAR2(5 CHAR),
        CUSTOMER_CLOSE_TIME               VARCHAR2(5 CHAR),
        IS_BUSINESS_DAY                   CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        IS_SETTLEMENT_DAY                 CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        IS_CLEARING_DAY                   CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        IS_PROCESSING_DAY                 CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        ACTIVE_FLAG                       CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        CONSTRAINT PK_CAL2_BUS_CAL_SCHED_DAY PRIMARY KEY (BUSINESS_CALENDAR_SCHEDULE_DAY_ID),
        CONSTRAINT UQ_CAL2_BUS_CAL_SCHED_DAY UNIQUE (BUSINESS_CALENDAR_SCHEDULE_ID, WEEKDAY_ID),
        CONSTRAINT FK_CAL2_BCSD_SCHED FOREIGN KEY (BUSINESS_CALENDAR_SCHEDULE_ID) REFERENCES CAL2.BUSINESS_CALENDAR_SCHEDULE (BUSINESS_CALENDAR_SCHEDULE_ID),
        CONSTRAINT FK_CAL2_BCSD_WEEKDAY FOREIGN KEY (WEEKDAY_ID) REFERENCES CAL2.WEEKDAY (WEEKDAY_ID),
        CONSTRAINT CK_CAL2_BCSD_STATUS CHECK (DAY_STATUS IN ('OPEN','CLOSED','PARTIAL')),
        CONSTRAINT CK_CAL2_BCSD_BUSINESS CHECK (IS_BUSINESS_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCSD_SETTLEMENT CHECK (IS_SETTLEMENT_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCSD_CLEARING CHECK (IS_CLEARING_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCSD_PROCESSING CHECK (IS_PROCESSING_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCSD_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCSD_STAFF_START CHECK (STAFF_START_TIME IS NULL OR REGEXP_LIKE(STAFF_START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCSD_STAFF_END CHECK (STAFF_END_TIME IS NULL OR REGEXP_LIKE(STAFF_END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCSD_CUST_OPEN CHECK (CUSTOMER_OPEN_TIME IS NULL OR REGEXP_LIKE(CUSTOMER_OPEN_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCSD_CUST_CLOSE CHECK (CUSTOMER_CLOSE_TIME IS NULL OR REGEXP_LIKE(CUSTOMER_CLOSE_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCSD_STAFF_RANGE CHECK (STAFF_END_TIME IS NULL OR STAFF_START_TIME IS NULL OR STAFF_END_TIME >= STAFF_START_TIME),
        CONSTRAINT CK_CAL2_BCSD_CUST_RANGE CHECK (CUSTOMER_CLOSE_TIME IS NULL OR CUSTOMER_OPEN_TIME IS NULL OR CUSTOMER_CLOSE_TIME >= CUSTOMER_OPEN_TIME)
      )
    ~';
    DBMS_OUTPUT.PUT_LINE('Created CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY');
  ELSE DBMS_OUTPUT.PUT_LINE('CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY already exists'); END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME='BUSINESS_CALENDAR_EXCEPTION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE CAL2.BUSINESS_CALENDAR_EXCEPTION (
        BUSINESS_CALENDAR_EXCEPTION_ID NUMBER(19) NOT NULL,
        BUSINESS_CALENDAR_ID           NUMBER(19) NOT NULL,
        EXCEPTION_DATE                 DATE NOT NULL,
        EXCEPTION_TYPE                 VARCHAR2(30 CHAR) DEFAULT 'MANUAL_OVERRIDE' NOT NULL,
        DAY_STATUS                     VARCHAR2(30 CHAR),
        STAFF_START_TIME               VARCHAR2(5 CHAR),
        STAFF_END_TIME                 VARCHAR2(5 CHAR),
        CUSTOMER_OPEN_TIME             VARCHAR2(5 CHAR),
        CUSTOMER_CLOSE_TIME            VARCHAR2(5 CHAR),
        IS_BUSINESS_DAY                CHAR(1 CHAR),
        IS_SETTLEMENT_DAY              CHAR(1 CHAR),
        IS_CLEARING_DAY                CHAR(1 CHAR),
        IS_PROCESSING_DAY              CHAR(1 CHAR),
        REASON_CODE                    VARCHAR2(80 CHAR),
        SOURCE_ID                      NUMBER(19),
        SOURCE_REFERENCE               VARCHAR2(250 CHAR),
        SOURCE_DATE                    DATE,
        SOURCE_URI                     VARCHAR2(1000 CHAR),
        DESCRIPTION                    VARCHAR2(2000 CHAR),
        ACTIVE_FLAG                    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        CONSTRAINT PK_CAL2_BUS_CAL_EX PRIMARY KEY (BUSINESS_CALENDAR_EXCEPTION_ID),
        CONSTRAINT UQ_CAL2_BUS_CAL_EX_DATE UNIQUE (BUSINESS_CALENDAR_ID, EXCEPTION_DATE),
        CONSTRAINT FK_CAL2_BCE_CAL FOREIGN KEY (BUSINESS_CALENDAR_ID) REFERENCES CAL2.BUSINESS_CALENDAR (BUSINESS_CALENDAR_ID),
        CONSTRAINT FK_CAL2_BCE_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CAL2.SOURCE_AUTHORITY (SOURCE_ID),
        CONSTRAINT CK_CAL2_BCE_TYPE CHECK (EXCEPTION_TYPE IN ('FORCE_MAJEURE','OFFICIAL_CLOSURE','SPECIAL_HOURS','MANUAL_OVERRIDE')),
        CONSTRAINT CK_CAL2_BCE_STATUS CHECK (DAY_STATUS IS NULL OR DAY_STATUS IN ('OPEN','CLOSED','PARTIAL')),
        CONSTRAINT CK_CAL2_BCE_BUSINESS CHECK (IS_BUSINESS_DAY IS NULL OR IS_BUSINESS_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCE_SETTLEMENT CHECK (IS_SETTLEMENT_DAY IS NULL OR IS_SETTLEMENT_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCE_CLEARING CHECK (IS_CLEARING_DAY IS NULL OR IS_CLEARING_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCE_PROCESSING CHECK (IS_PROCESSING_DAY IS NULL OR IS_PROCESSING_DAY IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCE_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N')),
        CONSTRAINT CK_CAL2_BCE_STAFF_START CHECK (STAFF_START_TIME IS NULL OR REGEXP_LIKE(STAFF_START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCE_STAFF_END CHECK (STAFF_END_TIME IS NULL OR REGEXP_LIKE(STAFF_END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCE_CUST_OPEN CHECK (CUSTOMER_OPEN_TIME IS NULL OR REGEXP_LIKE(CUSTOMER_OPEN_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCE_CUST_CLOSE CHECK (CUSTOMER_CLOSE_TIME IS NULL OR REGEXP_LIKE(CUSTOMER_CLOSE_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
        CONSTRAINT CK_CAL2_BCE_STAFF_RANGE CHECK (STAFF_END_TIME IS NULL OR STAFF_START_TIME IS NULL OR STAFF_END_TIME >= STAFF_START_TIME),
        CONSTRAINT CK_CAL2_BCE_CUST_RANGE CHECK (CUSTOMER_CLOSE_TIME IS NULL OR CUSTOMER_OPEN_TIME IS NULL OR CUSTOMER_CLOSE_TIME >= CUSTOMER_OPEN_TIME)
      )
    ~';
    DBMS_OUTPUT.PUT_LINE('Created CAL2.BUSINESS_CALENDAR_EXCEPTION');
  ELSE DBMS_OUTPUT.PUT_LINE('CAL2.BUSINESS_CALENDAR_EXCEPTION already exists'); END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_col(p_name VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
     WHERE OWNER='CAL2' AND TABLE_NAME='BUSINESS_CALENDAR_DAY' AND COLUMN_NAME=p_name;
    IF v_count=0 THEN EXECUTE IMMEDIATE p_ddl; DBMS_OUTPUT.PUT_LINE('Added BUSINESS_CALENDAR_DAY.'||p_name); END IF;
  END;
BEGIN
  add_col('STAFF_START_TIME', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (STAFF_START_TIME TIMESTAMP(6))~');
  add_col('STAFF_END_TIME', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (STAFF_END_TIME TIMESTAMP(6))~');
  add_col('RESOLUTION_SOURCE', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (RESOLUTION_SOURCE VARCHAR2(30 CHAR))~');
  add_col('SCHEDULE_ID', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (SCHEDULE_ID NUMBER(19))~');
  add_col('EXCEPTION_ID', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (EXCEPTION_ID NUMBER(19))~');
  add_col('RESOLVED_AT', q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD (RESOLVED_AT TIMESTAMP(6))~');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CAL2' AND CONSTRAINT_NAME='FK_CAL2_BCD_SCHEDULE';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD CONSTRAINT FK_CAL2_BCD_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES CAL2.BUSINESS_CALENDAR_SCHEDULE (BUSINESS_CALENDAR_SCHEDULE_ID)'; END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CAL2' AND CONSTRAINT_NAME='FK_CAL2_BCD_EXCEPTION';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD CONSTRAINT FK_CAL2_BCD_EXCEPTION FOREIGN KEY (EXCEPTION_ID) REFERENCES CAL2.BUSINESS_CALENDAR_EXCEPTION (BUSINESS_CALENDAR_EXCEPTION_ID)'; END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CAL2' AND CONSTRAINT_NAME='CK_CAL2_BCD_RESOLUTION';
  IF v_count=0 THEN EXECUTE IMMEDIATE q'~ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD CONSTRAINT CK_CAL2_BCD_RESOLUTION CHECK (RESOLUTION_SOURCE IS NULL OR RESOLUTION_SOURCE IN ('SCHEDULE','HOLIDAY','EXCEPTION','DEFAULT'))~'; END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_CONSTRAINTS WHERE OWNER='CAL2' AND CONSTRAINT_NAME='CK_CAL2_BCD_STAFF_RANGE';
  IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CAL2.BUSINESS_CALENDAR_DAY ADD CONSTRAINT CK_CAL2_BCD_STAFF_RANGE CHECK (STAFF_END_TIME IS NULL OR STAFF_START_TIME IS NULL OR STAFF_END_TIME >= STAFF_START_TIME)'; END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_ix(p_name VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ALL_INDEXES WHERE OWNER='CAL2' AND INDEX_NAME=p_name;
    IF v_count=0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
  END;
BEGIN
  add_ix('IX_CAL2_BCS_CAL', 'CREATE INDEX CAL2.IX_CAL2_BCS_CAL ON CAL2.BUSINESS_CALENDAR_SCHEDULE (BUSINESS_CALENDAR_ID)');
  add_ix('IX_CAL2_BCS_RANGE', 'CREATE INDEX CAL2.IX_CAL2_BCS_RANGE ON CAL2.BUSINESS_CALENDAR_SCHEDULE (EFFECTIVE_FROM, EFFECTIVE_TO)');
  add_ix('IX_CAL2_BCSD_SCHED', 'CREATE INDEX CAL2.IX_CAL2_BCSD_SCHED ON CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY (BUSINESS_CALENDAR_SCHEDULE_ID)');
  add_ix('IX_CAL2_BCSD_WEEKDAY', 'CREATE INDEX CAL2.IX_CAL2_BCSD_WEEKDAY ON CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY (WEEKDAY_ID)');
  add_ix('IX_CAL2_BCE_CAL_DATE', 'CREATE INDEX CAL2.IX_CAL2_BCE_CAL_DATE ON CAL2.BUSINESS_CALENDAR_EXCEPTION (BUSINESS_CALENDAR_ID, EXCEPTION_DATE)');
  add_ix('IX_CAL2_BCD_SCHEDULE', 'CREATE INDEX CAL2.IX_CAL2_BCD_SCHEDULE ON CAL2.BUSINESS_CALENDAR_DAY (SCHEDULE_ID)');
  add_ix('IX_CAL2_BCD_EXCEPTION', 'CREATE INDEX CAL2.IX_CAL2_BCD_EXCEPTION ON CAL2.BUSINESS_CALENDAR_DAY (EXCEPTION_ID)');
END;
/

COMMENT ON TABLE CAL2.BUSINESS_CALENDAR_SCHEDULE IS 'سیاست ساعات کاری معتبر در یک بازه زمانی برای تقویم کاری';
COMMENT ON TABLE CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY IS 'الگوی هفتگی ساعات حضور کارکنان و خدمت‌رسانی به مشتریان';
COMMENT ON TABLE CAL2.BUSINESS_CALENDAR_EXCEPTION IS 'استثنای تک‌روز برای تعطیلی اضطراری یا ساعات خاص';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.STAFF_START_TIME IS 'زمان Resolve‌شده شروع حضور کارکنان';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.STAFF_END_TIME IS 'زمان Resolve‌شده پایان حضور کارکنان';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.RESOLUTION_SOURCE IS 'منشأ نتیجه: برنامه، تعطیلی، استثنا یا پیش‌فرض';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.SCHEDULE_ID IS 'برنامه ساعات کاری مبنای Resolve';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.EXCEPTION_ID IS 'استثنای تک‌روز مبنای Resolve';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_DAY.RESOLVED_AT IS 'زمان آخرین Resolve روز';

COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.BUSINESS_CALENDAR_SCHEDULE_ID IS 'شناسه برنامه ساعات کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.BUSINESS_CALENDAR_ID IS 'شناسه تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.SCHEDULE_CODE IS 'کد یکتای برنامه ساعات کاری در تقویم';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.NAME_FA IS 'عنوان فارسی برنامه ساعات کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.NAME_EN IS 'عنوان انگلیسی برنامه ساعات کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.EFFECTIVE_FROM IS 'تاریخ شروع اعتبار برنامه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.EFFECTIVE_TO IS 'تاریخ پایان اعتبار برنامه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.STATUS IS 'وضعیت چرخه عمر برنامه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.PRIORITY_NO IS 'اولویت برنامه هنگام همپوشانی بازه‌ها';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.SOURCE_ID IS 'مرجع صادرکننده اطلاعیه یا بخشنامه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.SOURCE_REFERENCE IS 'شماره یا شناسه بخشنامه و اطلاعیه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.SOURCE_DATE IS 'تاریخ صدور بخشنامه یا اطلاعیه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.SOURCE_URI IS 'نشانی الکترونیکی سند مرجع';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.DESCRIPTION IS 'توضیحات برنامه ساعات کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE.ACTIVE_FLAG IS 'نشانگر فعال بودن برنامه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.BUSINESS_CALENDAR_SCHEDULE_DAY_ID IS 'شناسه ردیف الگوی هفتگی';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.BUSINESS_CALENDAR_SCHEDULE_ID IS 'شناسه برنامه ساعات کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.WEEKDAY_ID IS 'شناسه روز هفته';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.DAY_STATUS IS 'وضعیت باز، بسته یا نیمه‌وقت در این روز هفته';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.STAFF_START_TIME IS 'ساعت شروع حضور کارکنان به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.STAFF_END_TIME IS 'ساعت پایان حضور کارکنان به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.CUSTOMER_OPEN_TIME IS 'ساعت بازشدن شعب برای مشتری به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.CUSTOMER_CLOSE_TIME IS 'ساعت پایان خدمت‌رسانی شعب به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.IS_BUSINESS_DAY IS 'نشانگر روز کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.IS_SETTLEMENT_DAY IS 'نشانگر روز تسویه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.IS_CLEARING_DAY IS 'نشانگر روز پایاپای';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.IS_PROCESSING_DAY IS 'نشانگر روز پردازش';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_SCHEDULE_DAY.ACTIVE_FLAG IS 'نشانگر فعال بودن ردیف الگوی هفتگی';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.BUSINESS_CALENDAR_EXCEPTION_ID IS 'شناسه استثنای روز تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.BUSINESS_CALENDAR_ID IS 'شناسه تقویم کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.EXCEPTION_DATE IS 'تاریخ استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.EXCEPTION_TYPE IS 'نوع استثنا مانند فورس ماژور، تعطیلی رسمی یا ساعات خاص';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.DAY_STATUS IS 'وضعیت روز که برنامه هفتگی را Override می‌کند';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.STAFF_START_TIME IS 'ساعت شروع استثنایی حضور کارکنان به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.STAFF_END_TIME IS 'ساعت پایان استثنایی حضور کارکنان به قالب HH24:MI';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.CUSTOMER_OPEN_TIME IS 'ساعت بازشدن استثنایی شعب برای مشتری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.CUSTOMER_CLOSE_TIME IS 'ساعت پایان استثنایی خدمت‌رسانی به مشتری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.IS_BUSINESS_DAY IS 'Override نشانگر روز کاری';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.IS_SETTLEMENT_DAY IS 'Override نشانگر روز تسویه';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.IS_CLEARING_DAY IS 'Override نشانگر روز پایاپای';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.IS_PROCESSING_DAY IS 'Override نشانگر روز پردازش';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.REASON_CODE IS 'کد دلیل استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.SOURCE_ID IS 'مرجع صادرکننده استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.SOURCE_REFERENCE IS 'شماره یا شناسه اطلاعیه استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.SOURCE_DATE IS 'تاریخ صدور اطلاعیه استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.SOURCE_URI IS 'نشانی الکترونیکی اطلاعیه استثنا';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.DESCRIPTION IS 'توضیحات استثنای تک‌روز';
COMMENT ON COLUMN CAL2.BUSINESS_CALENDAR_EXCEPTION.ACTIVE_FLAG IS 'نشانگر فعال بودن استثنا';

PROMPT === FIX93 verification ===
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='CAL2' AND TABLE_NAME IN (
  'BUSINESS_CALENDAR_SCHEDULE','BUSINESS_CALENDAR_SCHEDULE_DAY','BUSINESS_CALENDAR_EXCEPTION'
) ORDER BY TABLE_NAME;

SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='CAL2' AND TABLE_NAME='BUSINESS_CALENDAR_DAY'
 AND COLUMN_NAME IN ('STAFF_START_TIME','STAFF_END_TIME','RESOLUTION_SOURCE','SCHEDULE_ID','EXCEPTION_ID','RESOLVED_AT')
 ORDER BY COLUMN_ID;

PROMPT FIX93 completed. Create a schedule in UI, edit its seven weekly rows, optionally add a one-day exception, then rebuild BUSINESS_CALENDAR_DAY from the new resolver panel.
