-- FIX88 / 0.3.80: explicit invalid-day resolution policy for CAL2 recurrence rules.
-- Corrected rerunnable migration: avoids ORA-01442 when the column is already NOT NULL.
SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
  v_count    NUMBER;
  v_nullable VARCHAR2(1);
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='CAL2'
     AND TABLE_NAME='EVENT_RECURRENCE_RULE'
     AND COLUMN_NAME='DAY_RESOLUTION_POLICY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~ALTER TABLE CAL2.EVENT_RECURRENCE_RULE
      ADD (DAY_RESOLUTION_POLICY VARCHAR2(40 CHAR) DEFAULT 'EXACT' NOT NULL)~';
    DBMS_OUTPUT.PUT_LINE('Added CAL2.EVENT_RECURRENCE_RULE.DAY_RESOLUTION_POLICY');
  ELSE
    DBMS_OUTPUT.PUT_LINE('DAY_RESOLUTION_POLICY already exists');

    EXECUTE IMMEDIATE q'~UPDATE CAL2.EVENT_RECURRENCE_RULE
                           SET DAY_RESOLUTION_POLICY = 'EXACT'
                         WHERE DAY_RESOLUTION_POLICY IS NULL~';

    SELECT NULLABLE INTO v_nullable
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='CAL2'
       AND TABLE_NAME='EVENT_RECURRENCE_RULE'
       AND COLUMN_NAME='DAY_RESOLUTION_POLICY';

    IF v_nullable = 'Y' THEN
      EXECUTE IMMEDIATE q'~ALTER TABLE CAL2.EVENT_RECURRENCE_RULE
                             MODIFY (DAY_RESOLUTION_POLICY DEFAULT 'EXACT' NOT NULL)~';
      DBMS_OUTPUT.PUT_LINE('DAY_RESOLUTION_POLICY default/NOT NULL normalized');
    ELSE
      -- Column is already NOT NULL; only normalize the default.
      EXECUTE IMMEDIATE q'~ALTER TABLE CAL2.EVENT_RECURRENCE_RULE
                             MODIFY (DAY_RESOLUTION_POLICY DEFAULT 'EXACT')~';
      DBMS_OUTPUT.PUT_LINE('DAY_RESOLUTION_POLICY already NOT NULL; default normalized');
    END IF;
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS
   WHERE OWNER='CAL2'
     AND CONSTRAINT_NAME='CK_CAL2_ER_DAY_POLICY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'~ALTER TABLE CAL2.EVENT_RECURRENCE_RULE
      ADD CONSTRAINT CK_CAL2_ER_DAY_POLICY
      CHECK (DAY_RESOLUTION_POLICY IN ('EXACT','LAST_DAY_IF_INVALID'))~';
    DBMS_OUTPUT.PUT_LINE('Added CK_CAL2_ER_DAY_POLICY');
  ELSE
    DBMS_OUTPUT.PUT_LINE('CK_CAL2_ER_DAY_POLICY already exists');
  END IF;
END;
/

COMMENT ON COLUMN CAL2.EVENT_RECURRENCE_RULE.DAY_RESOLUTION_POLICY IS
  'سیاست حل روز نامعتبر: EXACT=فقط همان روز؛ LAST_DAY_IF_INVALID=اگر آن روز در ماه/سال وجود نداشت آخرین روز همان ماه';

UPDATE CAL2.EVENT_RECURRENCE_RULE R
   SET R.DAY_RESOLUTION_POLICY = 'LAST_DAY_IF_INVALID'
 WHERE NVL(R.DAY_RESOLUTION_POLICY, 'EXACT') <> 'LAST_DAY_IF_INVALID'
   AND R.RULE_TYPE = 'ANNUAL_FIXED_DATE'
   AND R.MONTH_NO = 2
   AND R.DAY_NO = 30
   AND EXISTS (
       SELECT 1
         FROM CAL2.EVENT E
        WHERE E.EVENT_ID = R.EVENT_ID
          AND E.EVENT_CODE = 'IR_IMAM_REZA_MARTYRDOM'
   );

PROMPT === Verification ===
SELECT R.EVENT_RULE_ID,
       E.EVENT_CODE,
       E.NAME_FA,
       R.MONTH_NO,
       R.DAY_NO,
       R.DAY_RESOLUTION_POLICY
  FROM CAL2.EVENT_RECURRENCE_RULE R
  JOIN CAL2.EVENT E ON E.EVENT_ID = R.EVENT_ID
 WHERE E.EVENT_CODE = 'IR_IMAM_REZA_MARTYRDOM';

PROMPT Expected DAY_RESOLUTION_POLICY = LAST_DAY_IF_INVALID.
PROMPT Run COMMIT manually after review, deploy/start Runtime 0.3.80, then POST /api/v1/calendar2/event-recurrence/rebuild-all.
