-- ============================================================================
-- 00_fee_seed_cleanup.sql - OPTIONAL, deletes only negative-ID seed rows
-- Fee Prototype Target Model Baseline 1.0 / Oracle
-- UTF-8
-- ============================================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = FEE;

PROMPT WARNING: This script deletes Baseline seed records identified by negative primary keys.

DELETE FROM FEE_AUDIT_EVIDENCE WHERE AUDIT_EVIDENCE_ID < 0;
DELETE FROM FEE_POSTING_REFERENCE WHERE POSTING_REFERENCE_ID < 0;
DELETE FROM FEE_SETTLEMENT_REFERENCE WHERE SETTLEMENT_REFERENCE_ID < 0;
DELETE FROM FEE_APPLIED_ADJUSTMENT WHERE APPLIED_ADJUSTMENT_ID < 0;
DELETE FROM FEE_DECISION_TRACE WHERE TRACE_ID < 0;
DELETE FROM FEE_REVERSAL WHERE FEE_REVERSAL_ID < 0;
DELETE FROM FEE_OVERRIDE_REQUEST WHERE OVERRIDE_REQUEST_ID < 0;
DELETE FROM FEE_ALLOCATION_RESULT WHERE ALLOCATION_RESULT_ID < 0;
DELETE FROM FEE_CALCULATION_SNAPSHOT WHERE CALCULATION_SNAPSHOT_ID < 0;
DELETE FROM FEE_TRANSACTION_COMPONENT WHERE TRANSACTION_COMPONENT_ID < 0;
DELETE FROM FEE_ADJUSTMENT_POLICY WHERE ADJUSTMENT_POLICY_ID < 0;
DELETE FROM FEE_CHARGE_STAGE WHERE CHARGE_STAGE_ID < 0;
DELETE FROM FEE_TRANSACTION WHERE FEE_TRANSACTION_ID < 0;
DELETE FROM FEE_ARRANGEMENT_CALC_TERM WHERE ARRANGEMENT_CALC_TERM_ID < 0;
DELETE FROM FEE_CHARGE_COMPONENT WHERE CHARGE_COMPONENT_ID < 0;
DELETE FROM FEE_RULE_COMPONENT WHERE RULE_COMPONENT_ID < 0;
DELETE FROM FEE_CALCULATION_TIER WHERE TIER_ID < 0;
DELETE FROM FEE_INPUT_DEFINITION WHERE INPUT_DEF_ID < 0;
DELETE FROM FEE_INSTRUCTION WHERE FEE_INSTRUCTION_ID < 0;
DELETE FROM FEE_ARRANGEMENT_MODALITY WHERE ARRANGEMENT_MODALITY_ID < 0;
DELETE FROM FEE_ARRANGEMENT_ACCOUNT WHERE ARRANGEMENT_ACCOUNT_ID < 0;
DELETE FROM FEE_ARRANGEMENT_INVOLVEMENT WHERE INVOLVEMENT_ID < 0;
DELETE FROM FEE_ALLOCATION_RULE WHERE ALLOCATION_RULE_ID < 0;
DELETE FROM FEE_CALCULATION_RULE WHERE CALCULATION_RULE_ID < 0;
DELETE FROM FEE_APPLICABILITY_CONDITION WHERE CONDITION_ID < 0;
DELETE FROM FEE_ARRANGEMENT WHERE FEE_ARRANGEMENT_ID < 0;
DELETE FROM FEE_ALLOCATION_POLICY WHERE ALLOCATION_POLICY_ID < 0;
DELETE FROM FEE_POSTING_RULE WHERE POSTING_RULE_ID < 0;
DELETE FROM FEE_COLLECTION_RULE WHERE COLLECTION_RULE_ID < 0;
DELETE FROM FEE_CURRENCY_RULE WHERE CURRENCY_RULE_ID < 0;
DELETE FROM FEE_TIMING_RULE WHERE TIMING_RULE_ID < 0;
DELETE FROM FEE_APPLICABILITY_RULE WHERE APPLICABILITY_RULE_ID < 0;
DELETE FROM FEE_PRODUCT_FEATURE WHERE FEE_PRODUCT_FEATURE_ID < 0;
DELETE FROM FEE_DEFINITION_VERSION WHERE FEE_DEFINITION_VERSION_ID < 0;
DELETE FROM FEE_DEMO_ACCOUNT WHERE DEMO_ACCOUNT_ID < 0;
DELETE FROM FEE_DEMO_PRODUCT_FEATURE WHERE DEMO_PRODUCT_FEATURE_ID < 0;
DELETE FROM FEE_REF_VALUE WHERE VALUE_ID < 0;
DELETE FROM FEE_DEFINITION WHERE FEE_DEFINITION_ID < 0;
DELETE FROM FEE_REGULATORY_DISCOUNT_LIMIT WHERE REG_DISCOUNT_LIMIT_ID < 0;
DELETE FROM FEE_POLICY_VERSION WHERE POLICY_VERSION_ID < 0;
DELETE FROM FEE_DEMO_FX_RATE WHERE DEMO_FX_RATE_ID < 0;
DELETE FROM FEE_DEMO_PRODUCT WHERE DEMO_PRODUCT_ID < 0;
DELETE FROM FEE_DEMO_PARTY WHERE DEMO_PARTY_ID < 0;
DELETE FROM FEE_REF_DOMAIN WHERE DOMAIN_ID < 0;
DELETE FROM FEE_FEATURE WHERE FEE_FEATURE_ID < 0;
DELETE FROM FEE_REGULATORY_SOURCE WHERE REGULATORY_SOURCE_ID < 0;
DELETE FROM FEE_POLICY_SET WHERE POLICY_SET_ID < 0;
COMMIT;
