-- ============================================================================
-- 05_fee_arrangement_data.sql
-- Fee Prototype Target Model Baseline 1.0 / Oracle
-- UTF-8
-- ============================================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = FEE;

PROMPT Loading FEE_ARRANGEMENT ...
INSERT INTO FEE_ARRANGEMENT (
    FEE_ARRANGEMENT_ID,
    ARRANGEMENT_NO,
    FEE_PRODUCT_FEATURE_ID,
    FEE_DEFINITION_VERSION_ID,
    ORIGIN_CODE,
    STATUS_CODE,
    EFFECTIVE_FROM,
    DESCRIPTION,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11001,
    'ARR-TRANSFER-VIP-001',
    -7201,
    -7101,
    'NEGOTIATED',
    'ACTIVE',
    DATE '2026-01-01',
    'ترتیب آزمایشی انتقال برای مشتری VIP',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT (
    FEE_ARRANGEMENT_ID,
    ARRANGEMENT_NO,
    FEE_PRODUCT_FEATURE_ID,
    FEE_DEFINITION_VERSION_ID,
    ORIGIN_CODE,
    STATUS_CODE,
    EFFECTIVE_FROM,
    DESCRIPTION,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11002,
    'ARR-GUARANTEE-001',
    -7202,
    -7102,
    'STANDARD',
    'ACTIVE',
    DATE '2025-05-04',
    'ترتیب استاندارد ضمانت‌نامه',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

PROMPT Loading FEE_ARRANGEMENT_INVOLVEMENT ...
INSERT INTO FEE_ARRANGEMENT_INVOLVEMENT (
    INVOLVEMENT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_PARTY_ID,
    INVOLVEMENT_ROLE_CODE,
    ROLE_DETAIL_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11101,
    -11001,
    -2004,
    'ChargeBearer',
    'CUSTOMER',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_INVOLVEMENT (
    INVOLVEMENT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_PARTY_ID,
    INVOLVEMENT_ROLE_CODE,
    ROLE_DETAIL_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11102,
    -11001,
    -2001,
    'ChargeRecipient',
    'BANK',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_INVOLVEMENT (
    INVOLVEMENT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_PARTY_ID,
    INVOLVEMENT_ROLE_CODE,
    ROLE_DETAIL_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11103,
    -11001,
    -2002,
    'ChargeAgent',
    'BRANCH',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_INVOLVEMENT (
    INVOLVEMENT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_PARTY_ID,
    INVOLVEMENT_ROLE_CODE,
    ROLE_DETAIL_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11104,
    -11002,
    -2003,
    'ChargeBearer',
    'CUSTOMER',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_INVOLVEMENT (
    INVOLVEMENT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_PARTY_ID,
    INVOLVEMENT_ROLE_CODE,
    ROLE_DETAIL_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11105,
    -11002,
    -2001,
    'ChargeRecipient',
    'BANK',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

PROMPT Loading FEE_ARRANGEMENT_ACCOUNT ...
INSERT INTO FEE_ARRANGEMENT_ACCOUNT (
    ARRANGEMENT_ACCOUNT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_ACCOUNT_ID,
    ACCOUNT_ROLE_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11201,
    -11001,
    -3202,
    'CHARGE_ACCOUNT',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_ACCOUNT (
    ARRANGEMENT_ACCOUNT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_ACCOUNT_ID,
    ACCOUNT_ROLE_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11202,
    -11001,
    -3204,
    'CREDIT_ACCOUNT',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_ACCOUNT (
    ARRANGEMENT_ACCOUNT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_ACCOUNT_ID,
    ACCOUNT_ROLE_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11203,
    -11002,
    -3201,
    'CHARGE_ACCOUNT',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_ACCOUNT (
    ARRANGEMENT_ACCOUNT_ID,
    FEE_ARRANGEMENT_ID,
    DEMO_ACCOUNT_ID,
    ACCOUNT_ROLE_CODE,
    IS_PRIMARY_FLAG,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11204,
    -11002,
    -3204,
    'CREDIT_ACCOUNT',
    'Y',
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

PROMPT Loading FEE_ARRANGEMENT_MODALITY ...
INSERT INTO FEE_ARRANGEMENT_MODALITY (
    ARRANGEMENT_MODALITY_ID,
    FEE_ARRANGEMENT_ID,
    MODALITY_TYPE_CODE,
    TIMING_RULE_ID,
    CURRENCY_RULE_ID,
    COLLECTION_RULE_ID,
    POSTING_RULE_ID,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11301,
    -11001,
    'Fee Application Timing Modality',
    -9601,
    NULL,
    NULL,
    NULL,
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_MODALITY (
    ARRANGEMENT_MODALITY_ID,
    FEE_ARRANGEMENT_ID,
    MODALITY_TYPE_CODE,
    TIMING_RULE_ID,
    CURRENCY_RULE_ID,
    COLLECTION_RULE_ID,
    POSTING_RULE_ID,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11302,
    -11001,
    'Fee Currency Modality',
    NULL,
    -9701,
    NULL,
    NULL,
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_MODALITY (
    ARRANGEMENT_MODALITY_ID,
    FEE_ARRANGEMENT_ID,
    MODALITY_TYPE_CODE,
    TIMING_RULE_ID,
    CURRENCY_RULE_ID,
    COLLECTION_RULE_ID,
    POSTING_RULE_ID,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11303,
    -11001,
    'Fee Calculation Modality',
    NULL,
    NULL,
    NULL,
    NULL,
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_MODALITY (
    ARRANGEMENT_MODALITY_ID,
    FEE_ARRANGEMENT_ID,
    MODALITY_TYPE_CODE,
    TIMING_RULE_ID,
    CURRENCY_RULE_ID,
    COLLECTION_RULE_ID,
    POSTING_RULE_ID,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11304,
    -11001,
    'Fee Posting Modality',
    NULL,
    NULL,
    NULL,
    -9901,
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

INSERT INTO FEE_ARRANGEMENT_MODALITY (
    ARRANGEMENT_MODALITY_ID,
    FEE_ARRANGEMENT_ID,
    MODALITY_TYPE_CODE,
    TIMING_RULE_ID,
    CURRENCY_RULE_ID,
    COLLECTION_RULE_ID,
    POSTING_RULE_ID,
    EFFECTIVE_FROM,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11305,
    -11001,
    'Payment Modality',
    NULL,
    NULL,
    -9801,
    NULL,
    DATE '2026-01-01',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

PROMPT Loading FEE_ARRANGEMENT_CALC_TERM ...
INSERT INTO FEE_ARRANGEMENT_CALC_TERM (
    ARRANGEMENT_CALC_TERM_ID,
    FEE_ARRANGEMENT_ID,
    BASE_CALCULATION_RULE_ID,
    CALCULATION_STRATEGY_CODE,
    RATE_VALUE,
    MIN_FEE_AMOUNT,
    MAX_FEE_AMOUNT,
    CURRENCY_CODE,
    ROUNDING_MODE_CODE,
    ROUNDING_SCALE,
    EFFECTIVE_FROM,
    APPROVAL_REF,
    DESCRIPTION,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -11401,
    -11001,
    -9001,
    'PERCENTAGE_FLOOR_CAP',
    0.0015,
    50000,
    2000000,
    'IRR',
    'HALF_UP',
    0,
    DATE '2026-01-01',
    'NEG-APP-001',
    'نرخ توافقی ۰.۱۵ درصد برای مشتری VIP',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

COMMIT;
