-- ============================================================================
-- 06_fee_runtime_sample_data.sql
-- Fee Prototype Target Model Baseline 1.0 / Oracle
-- UTF-8
-- ============================================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = FEE;

PROMPT Loading FEE_INSTRUCTION ...
INSERT INTO FEE_INSTRUCTION (
    FEE_INSTRUCTION_ID,
    INSTRUCTION_NO,
    IDEMPOTENCY_KEY,
    REQUEST_ID,
    CORRELATION_ID,
    FEE_ARRANGEMENT_ID,
    FEE_DEFINITION_VERSION_ID,
    DEMO_PARTY_ID,
    DEMO_ACCOUNT_ID,
    DEMO_PRODUCT_ID,
    BUSINESS_TRANSACTION_REF,
    EVENT_TYPE_CODE,
    ACTIVITY_CODE,
    TRANSACTION_TYPE_CODE,
    CHANNEL_CODE,
    BASIS_AMOUNT,
    BASIS_CURRENCY_CODE,
    QUANTITY_VALUE,
    EVENT_DATE_TIME,
    STATUS_CODE,
    REQUESTED_AT,
    CREATED_AT,
    CREATED_BY,
    RECORD_VERSION
) VALUES (
    -12001,
    'FINSTR-0001',
    'FEE-SEED-TRANSFER-0001',
    'REQ-0001',
    'CORR-0001',
    -11001,
    -7101,
    -2004,
    -3202,
    -3001,
    'BUS-TX-0001',
    'TRANSFER',
    'MONEY_TRANSFER',
    'TRANSFER',
    'MOBILE',
    500000000,
    'IRR',
    1,
    TIMESTAMP '2026-08-29 10:00:00',
    'COMPLETED',
    TIMESTAMP '2026-08-29 10:00:00',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0',
    1
);

PROMPT Loading FEE_TRANSACTION ...
INSERT INTO FEE_TRANSACTION (
    FEE_TRANSACTION_ID,
    TRANSACTION_NO,
    FEE_INSTRUCTION_ID,
    FEE_DEFINITION_VERSION_ID,
    FEE_ARRANGEMENT_ID,
    CALCULATION_RULE_ID,
    TRANSACTION_DATE,
    CALCULATED_AMOUNT,
    GROSS_FEE_AMOUNT,
    ACCRUED_FEE_AMOUNT,
    APPLIED_FEE_AMOUNT,
    ADJUSTMENT_AMOUNT,
    NET_FEE_AMOUNT,
    COLLECTED_AMOUNT,
    FEE_CURRENCY_CODE,
    STATUS_CODE,
    CALCULATED_AT,
    APPLIED_AT,
    COLLECTED_AT,
    CREATED_AT,
    CREATED_BY
) VALUES (
    -12101,
    'FTX-0001',
    -12001,
    -7101,
    -11001,
    -9001,
    DATE '2026-08-29',
    750000,
    750000,
    750000,
    600000,
    150000,
    600000,
    600000,
    'IRR',
    'PARTIALLY_REVERSED',
    TIMESTAMP '2026-08-29 10:00:01',
    TIMESTAMP '2026-08-29 10:00:02',
    TIMESTAMP '2026-08-29 10:00:03',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0'
);

PROMPT Loading FEE_TRANSACTION_COMPONENT ...
INSERT INTO FEE_TRANSACTION_COMPONENT (
    TRANSACTION_COMPONENT_ID,
    FEE_TRANSACTION_ID,
    CHARGE_COMPONENT_ID,
    SEQUENCE_NO,
    COMPONENT_CODE,
    COMPONENT_TYPE_CODE,
    CALCULATED_AMOUNT,
    APPLIED_AMOUNT,
    DISCOUNT_AMOUNT,
    REFUNDABLE_AMOUNT,
    REVENUE_AMOUNT,
    PASS_THROUGH_AMOUNT,
    CURRENCY_CODE,
    DESCRIPTION
) VALUES (
    -12201,
    -12101,
    -9401,
    1,
    'BANK_FEE',
    'BANK_REVENUE',
    750000,
    600000,
    150000,
    600000,
    600000,
    0,
    'IRR',
    'جزء درآمدی کارمزد انتقال'
);

PROMPT Loading FEE_CALCULATION_SNAPSHOT ...
INSERT INTO FEE_CALCULATION_SNAPSHOT (
    CALCULATION_SNAPSHOT_ID,
    FEE_TRANSACTION_ID,
    POLICY_VERSION_ID,
    FEE_DEFINITION_VERSION_ID,
    CALCULATION_RULE_ID,
    APPLICABILITY_RULE_ID,
    CONFIG_HASH,
    INPUT_CONTEXT_HASH,
    INPUT_CONTEXT_JSON,
    SNAPSHOT_JSON,
    EXPLANATION_TEXT,
    BASIS_AMOUNT,
    GROSS_FEE_AMOUNT,
    TOTAL_ADJUSTMENT_AMOUNT,
    NET_FEE_AMOUNT,
    CALCULATED_AT
) VALUES (
    -12301,
    -12101,
    -5102,
    -7101,
    -9001,
    -8001,
    'SEED-DEMO_TRANSFER_FEE-V1',
    'SEED-CTX-TRANSFER-0001',
    TO_CLOB('{"basisAmount":500000000,"currency":"IRR","segment":"VIP","channel":"MOBILE"}'),
    TO_CLOB('{"arrangementRate":0.0015,"gross":750000,"discountRate":0.20,"discount":150000,"net":600000}'),
    TO_CLOB('مبلغ مبنا ۵۰۰,۰۰۰,۰۰۰ ریال × نرخ توافقی ۰.۱۵٪ = ۷۵۰,۰۰۰ ریال؛ سپس تخفیف VIP به میزان ۲۰٪ اعمال و مبلغ نهایی ۶۰۰,۰۰۰ ریال محاسبه شد.'),
    500000000,
    750000,
    150000,
    600000,
    TIMESTAMP '2026-08-29 10:00:01'
);

PROMPT Loading FEE_APPLIED_ADJUSTMENT ...
INSERT INTO FEE_APPLIED_ADJUSTMENT (
    APPLIED_ADJUSTMENT_ID,
    FEE_TRANSACTION_ID,
    ADJUSTMENT_POLICY_ID,
    SEQUENCE_NO,
    ADJUSTMENT_TYPE_CODE,
    BASE_AMOUNT,
    PERCENT_VALUE,
    ADJUSTMENT_AMOUNT,
    RESULT_AMOUNT,
    CURRENCY_CODE,
    APPLIED_AT
) VALUES (
    -12401,
    -12101,
    -10001,
    1,
    'PERCENT_REDUCTION',
    750000,
    0.2,
    150000,
    600000,
    'IRR',
    TIMESTAMP '2026-08-29 10:00:02'
);

PROMPT Loading FEE_ALLOCATION_RESULT ...
INSERT INTO FEE_ALLOCATION_RESULT (
    ALLOCATION_RESULT_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_POLICY_ID,
    ALLOCATION_RULE_ID,
    BENEFICIARY_PARTY_ID,
    BENEFICIARY_ROLE_CODE,
    ALLOCATION_BASIS_CODE,
    ALLOCATION_PERCENT,
    ALLOCATION_AMOUNT,
    CURRENCY_CODE,
    CALCULATED_AT,
    STATUS_CODE
) VALUES (
    -12501,
    -12101,
    -10101,
    -10201,
    -2001,
    'BANK',
    'PERCENT',
    0.7,
    420000,
    'IRR',
    TIMESTAMP '2026-08-29 10:00:02',
    'CALCULATED'
);

INSERT INTO FEE_ALLOCATION_RESULT (
    ALLOCATION_RESULT_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_POLICY_ID,
    ALLOCATION_RULE_ID,
    BENEFICIARY_PARTY_ID,
    BENEFICIARY_ROLE_CODE,
    ALLOCATION_BASIS_CODE,
    ALLOCATION_PERCENT,
    ALLOCATION_AMOUNT,
    CURRENCY_CODE,
    CALCULATED_AT,
    STATUS_CODE
) VALUES (
    -12502,
    -12101,
    -10101,
    -10202,
    -2002,
    'AGENT_BRANCH',
    'PERCENT',
    0.2,
    120000,
    'IRR',
    TIMESTAMP '2026-08-29 10:00:02',
    'CALCULATED'
);

INSERT INTO FEE_ALLOCATION_RESULT (
    ALLOCATION_RESULT_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_POLICY_ID,
    ALLOCATION_RULE_ID,
    BENEFICIARY_PARTY_ID,
    BENEFICIARY_ROLE_CODE,
    ALLOCATION_BASIS_CODE,
    ALLOCATION_PERCENT,
    ALLOCATION_AMOUNT,
    CURRENCY_CODE,
    CALCULATED_AT,
    STATUS_CODE
) VALUES (
    -12503,
    -12101,
    -10101,
    -10203,
    -2007,
    'EXTERNAL_ORG',
    'PERCENT',
    0.1,
    60000,
    'IRR',
    TIMESTAMP '2026-08-29 10:00:02',
    'CALCULATED'
);

PROMPT Loading FEE_OVERRIDE_REQUEST ...
INSERT INTO FEE_OVERRIDE_REQUEST (
    OVERRIDE_REQUEST_ID,
    FEE_ARRANGEMENT_ID,
    FEE_TRANSACTION_ID,
    FEE_DEFINITION_VERSION_ID,
    OVERRIDE_TYPE_CODE,
    OVERRIDE_AMOUNT,
    REASON_CODE,
    REASON_TEXT,
    REQUESTED_BY,
    REQUESTED_AT,
    STATUS_CODE,
    APPROVED_BY,
    APPROVED_AT,
    RECORD_VERSION
) VALUES (
    -12601,
    -11001,
    -12101,
    -7101,
    'AMOUNT_OVERRIDE',
    500000,
    'MANUAL_EXCEPTION',
    'درخواست نمونه برای آزمون گردش کار Override',
    'DEMO_USER',
    TIMESTAMP '2026-08-29 10:05:00',
    'REJECTED',
    'DEMO_SUPERVISOR',
    TIMESTAMP '2026-08-29 10:06:00',
    1
);

PROMPT Loading FEE_REVERSAL ...
INSERT INTO FEE_REVERSAL (
    FEE_REVERSAL_ID,
    REVERSAL_NO,
    FEE_TRANSACTION_ID,
    REVERSAL_TYPE_CODE,
    REVERSAL_CALC_RULE_ID,
    REQUESTED_AMOUNT,
    CALCULATED_REVERSAL_AMOUNT,
    NON_REFUNDABLE_AMOUNT,
    REVERSAL_CURRENCY_CODE,
    REASON_CODE,
    REASON_TEXT,
    AUTHORIZATION_REF,
    REFUND_ACCOUNT_ID,
    STATUS_CODE,
    REQUESTED_AT,
    COMPLETED_AT,
    CREATED_AT,
    CREATED_BY
) VALUES (
    -12701,
    'FREV-0001',
    -12101,
    'PARTIAL',
    NULL,
    100000,
    100000,
    0,
    'IRR',
    'CUSTOMER_REQUEST',
    'برگشت جزئی نمونه',
    'AUTH-REV-0001',
    -3202,
    'COMPLETED',
    TIMESTAMP '2026-08-29 10:10:00',
    TIMESTAMP '2026-08-29 10:11:00',
    TIMESTAMP '2026-01-01 00:00:00',
    'SEED_BASELINE_1_0'
);

PROMPT Loading FEE_POSTING_REFERENCE ...
INSERT INTO FEE_POSTING_REFERENCE (
    POSTING_REFERENCE_ID,
    FEE_TRANSACTION_ID,
    POSTING_PURPOSE_CODE,
    POSTING_MODALITY_CODE,
    ACCOUNTING_PROFILE_CODE,
    DEBIT_DEMO_ACCOUNT_ID,
    CREDIT_DEMO_ACCOUNT_ID,
    AMOUNT,
    CURRENCY_CODE,
    ACCOUNTING_INSTRUCTION_REF,
    POSTING_REF,
    JOURNAL_REF,
    LEDGER_TRANSACTION_REF,
    POSTING_STATUS_CODE,
    REQUESTED_AT,
    COMPLETED_AT,
    CREATED_AT
) VALUES (
    -12801,
    -12101,
    'CHARGE',
    'Immediate Posting',
    'FEE_DEFAULT',
    -3202,
    -3204,
    600000,
    'IRR',
    'ACC-I-0001',
    'POST-0001',
    'JRN-0001',
    'LEDGER-DEMO-0001',
    'COMPLETED',
    TIMESTAMP '2026-08-29 10:00:03',
    TIMESTAMP '2026-08-29 10:00:04',
    TIMESTAMP '2026-01-01 00:00:00'
);

INSERT INTO FEE_POSTING_REFERENCE (
    POSTING_REFERENCE_ID,
    FEE_TRANSACTION_ID,
    FEE_REVERSAL_ID,
    POSTING_PURPOSE_CODE,
    POSTING_MODALITY_CODE,
    ACCOUNTING_PROFILE_CODE,
    DEBIT_DEMO_ACCOUNT_ID,
    CREDIT_DEMO_ACCOUNT_ID,
    AMOUNT,
    CURRENCY_CODE,
    ACCOUNTING_INSTRUCTION_REF,
    POSTING_REF,
    JOURNAL_REF,
    LEDGER_TRANSACTION_REF,
    POSTING_STATUS_CODE,
    REQUESTED_AT,
    COMPLETED_AT,
    CREATED_AT
) VALUES (
    -12802,
    -12101,
    -12701,
    'REVERSAL',
    'Immediate Posting',
    'FEE_REVERSAL',
    -3204,
    -3202,
    100000,
    'IRR',
    'ACC-I-0002',
    'POST-0002',
    'JRN-0002',
    'LEDGER-DEMO-0002',
    'COMPLETED',
    TIMESTAMP '2026-08-29 10:10:30',
    TIMESTAMP '2026-08-29 10:11:00',
    TIMESTAMP '2026-01-01 00:00:00'
);

PROMPT Loading FEE_SETTLEMENT_REFERENCE ...
INSERT INTO FEE_SETTLEMENT_REFERENCE (
    SETTLEMENT_REFERENCE_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_RESULT_ID,
    SETTLEMENT_METHOD_CODE,
    SETTLEMENT_STATUS_CODE,
    SETTLEMENT_DATE,
    SETTLEMENT_ACCOUNT_ID,
    SETTLEMENT_AMOUNT,
    CURRENCY_CODE,
    SETTLEMENT_REFERENCE,
    CREATED_AT
) VALUES (
    -12901,
    -12101,
    -12501,
    'INTERNAL',
    'COMPLETED',
    DATE '2026-08-29',
    -3205,
    420000,
    'IRR',
    'SET-BANK-0001',
    TIMESTAMP '2026-01-01 00:00:00'
);

INSERT INTO FEE_SETTLEMENT_REFERENCE (
    SETTLEMENT_REFERENCE_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_RESULT_ID,
    SETTLEMENT_METHOD_CODE,
    SETTLEMENT_STATUS_CODE,
    SETTLEMENT_DATE,
    SETTLEMENT_ACCOUNT_ID,
    SETTLEMENT_AMOUNT,
    CURRENCY_CODE,
    SETTLEMENT_REFERENCE,
    CREATED_AT
) VALUES (
    -12902,
    -12101,
    -12502,
    'INTERNAL',
    'COMPLETED',
    DATE '2026-08-29',
    -3205,
    120000,
    'IRR',
    'SET-BR-0001',
    TIMESTAMP '2026-01-01 00:00:00'
);

INSERT INTO FEE_SETTLEMENT_REFERENCE (
    SETTLEMENT_REFERENCE_ID,
    FEE_TRANSACTION_ID,
    ALLOCATION_RESULT_ID,
    SETTLEMENT_METHOD_CODE,
    SETTLEMENT_STATUS_CODE,
    SETTLEMENT_DATE,
    SETTLEMENT_ACCOUNT_ID,
    SETTLEMENT_AMOUNT,
    CURRENCY_CODE,
    SETTLEMENT_REFERENCE,
    CREATED_AT
) VALUES (
    -12903,
    -12101,
    -12503,
    'TRANSFER',
    'COMPLETED',
    DATE '2026-08-29',
    -3206,
    60000,
    'IRR',
    'SET-EXT-0001',
    TIMESTAMP '2026-01-01 00:00:00'
);

PROMPT Loading FEE_DECISION_TRACE ...
INSERT INTO FEE_DECISION_TRACE (
    TRACE_ID,
    FEE_TRANSACTION_ID,
    STEP_NO,
    STEP_NAME,
    STEP_TYPE_CODE,
    CALCULATION_RULE_ID,
    APPLICABILITY_RULE_ID,
    RULE_COMPONENT_ID,
    INPUT_PAYLOAD,
    OUTPUT_PAYLOAD,
    EVALUATION_RESULT_CODE,
    CREATED_AT
) VALUES (
    -13001,
    -12101,
    1,
    'Resolve applicability',
    'APPLICABILITY',
    NULL,
    -8001,
    NULL,
    TO_CLOB('{"activity":"MONEY_TRANSFER","currency":"IRR"}'),
    TO_CLOB('{"matched":true}'),
    'MATCHED',
    TIMESTAMP '2026-08-29 10:00:01'
);

INSERT INTO FEE_DECISION_TRACE (
    TRACE_ID,
    FEE_TRANSACTION_ID,
    STEP_NO,
    STEP_NAME,
    STEP_TYPE_CODE,
    CALCULATION_RULE_ID,
    APPLICABILITY_RULE_ID,
    RULE_COMPONENT_ID,
    INPUT_PAYLOAD,
    OUTPUT_PAYLOAD,
    EVALUATION_RESULT_CODE,
    CREATED_AT
) VALUES (
    -13002,
    -12101,
    2,
    'Resolve arrangement rate',
    'ARRANGEMENT',
    -9001,
    NULL,
    NULL,
    TO_CLOB('{"standardRate":0.002,"arrangementRate":0.0015}'),
    TO_CLOB('{"selectedRate":0.0015}'),
    'OVERRIDDEN_BY_ARRANGEMENT',
    TIMESTAMP '2026-08-29 10:00:01'
);

INSERT INTO FEE_DECISION_TRACE (
    TRACE_ID,
    FEE_TRANSACTION_ID,
    STEP_NO,
    STEP_NAME,
    STEP_TYPE_CODE,
    CALCULATION_RULE_ID,
    APPLICABILITY_RULE_ID,
    RULE_COMPONENT_ID,
    INPUT_PAYLOAD,
    OUTPUT_PAYLOAD,
    EVALUATION_RESULT_CODE,
    CREATED_AT
) VALUES (
    -13003,
    -12101,
    3,
    'Calculate gross fee',
    'CALCULATION',
    -9001,
    -8001,
    NULL,
    TO_CLOB('{"basis":500000000,"rate":0.0015}'),
    TO_CLOB('{"gross":750000}'),
    'CALCULATED',
    TIMESTAMP '2026-08-29 10:00:01'
);

INSERT INTO FEE_DECISION_TRACE (
    TRACE_ID,
    FEE_TRANSACTION_ID,
    STEP_NO,
    STEP_NAME,
    STEP_TYPE_CODE,
    CALCULATION_RULE_ID,
    APPLICABILITY_RULE_ID,
    RULE_COMPONENT_ID,
    INPUT_PAYLOAD,
    OUTPUT_PAYLOAD,
    EVALUATION_RESULT_CODE,
    CREATED_AT
) VALUES (
    -13004,
    -12101,
    4,
    'Apply VIP discount',
    'ADJUSTMENT',
    NULL,
    -8002,
    NULL,
    TO_CLOB('{"gross":750000,"discountRate":0.20}'),
    TO_CLOB('{"net":600000}'),
    'APPLIED',
    TIMESTAMP '2026-08-29 10:00:01'
);

PROMPT Loading FEE_AUDIT_EVIDENCE ...
INSERT INTO FEE_AUDIT_EVIDENCE (
    AUDIT_EVIDENCE_ID,
    FEE_TRANSACTION_ID,
    EVIDENCE_TYPE_CODE,
    ENTITY_TYPE_CODE,
    ENTITY_ID,
    EVIDENCE_REF,
    EVIDENCE_HASH,
    EVIDENCE_PAYLOAD,
    CAPTURED_AT,
    CAPTURED_BY
) VALUES (
    -13101,
    -12101,
    'RULE',
    'FEE_TRANSACTION',
    'FTX-0001',
    'seed://calculation/FTX-0001',
    'HASH-SEED-FTX-0001',
    TO_CLOB('{"policyVersion":"1.0","feeDefinition":"DEMO_TRANSFER_FEE"}'),
    TIMESTAMP '2026-08-29 10:00:04',
    'FEE_ENGINE'
);

INSERT INTO FEE_AUDIT_EVIDENCE (
    AUDIT_EVIDENCE_ID,
    OVERRIDE_REQUEST_ID,
    EVIDENCE_TYPE_CODE,
    ENTITY_TYPE_CODE,
    ENTITY_ID,
    EVIDENCE_REF,
    CAPTURED_AT,
    CAPTURED_BY
) VALUES (
    -13102,
    -12601,
    'OVERRIDE',
    'FEE_OVERRIDE_REQUEST',
    '-12601',
    'seed://override/-12601',
    TIMESTAMP '2026-08-29 10:06:00',
    'DEMO_SUPERVISOR'
);

INSERT INTO FEE_AUDIT_EVIDENCE (
    AUDIT_EVIDENCE_ID,
    FEE_REVERSAL_ID,
    EVIDENCE_TYPE_CODE,
    ENTITY_TYPE_CODE,
    ENTITY_ID,
    EVIDENCE_REF,
    CAPTURED_AT,
    CAPTURED_BY
) VALUES (
    -13103,
    -12701,
    'REVERSAL',
    'FEE_REVERSAL',
    'FREV-0001',
    'seed://reversal/FREV-0001',
    TIMESTAMP '2026-08-29 10:11:00',
    'FEE_ENGINE'
);

COMMIT;
