-- ============================================================================
-- 99_fee_seed_verify.sql
-- Fee Prototype Target Model Baseline 1.0 / Oracle
-- UTF-8
-- ============================================================================
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = FEE;

SET PAGESIZE 200
SET LINESIZE 220
COLUMN TABLE_NAME FORMAT A40
PROMPT === Seed row counts (negative PKs) ===
SELECT 'FEE_POLICY_SET' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_POLICY_SET WHERE POLICY_SET_ID < 0;
SELECT 'FEE_REGULATORY_SOURCE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_REGULATORY_SOURCE WHERE REGULATORY_SOURCE_ID < 0;
SELECT 'FEE_FEATURE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_FEATURE WHERE FEE_FEATURE_ID < 0;
SELECT 'FEE_REF_DOMAIN' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_REF_DOMAIN WHERE DOMAIN_ID < 0;
SELECT 'FEE_DEMO_PARTY' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEMO_PARTY WHERE DEMO_PARTY_ID < 0;
SELECT 'FEE_DEMO_PRODUCT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEMO_PRODUCT WHERE DEMO_PRODUCT_ID < 0;
SELECT 'FEE_DEMO_FX_RATE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEMO_FX_RATE WHERE DEMO_FX_RATE_ID < 0;
SELECT 'FEE_POLICY_VERSION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_POLICY_VERSION WHERE POLICY_VERSION_ID < 0;
SELECT 'FEE_REGULATORY_DISCOUNT_LIMIT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_REGULATORY_DISCOUNT_LIMIT WHERE REG_DISCOUNT_LIMIT_ID < 0;
SELECT 'FEE_DEFINITION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEFINITION WHERE FEE_DEFINITION_ID < 0;
SELECT 'FEE_REF_VALUE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_REF_VALUE WHERE VALUE_ID < 0;
SELECT 'FEE_DEMO_PRODUCT_FEATURE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEMO_PRODUCT_FEATURE WHERE DEMO_PRODUCT_FEATURE_ID < 0;
SELECT 'FEE_DEMO_ACCOUNT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEMO_ACCOUNT WHERE DEMO_ACCOUNT_ID < 0;
SELECT 'FEE_DEFINITION_VERSION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DEFINITION_VERSION WHERE FEE_DEFINITION_VERSION_ID < 0;
SELECT 'FEE_PRODUCT_FEATURE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_PRODUCT_FEATURE WHERE FEE_PRODUCT_FEATURE_ID < 0;
SELECT 'FEE_APPLICABILITY_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_APPLICABILITY_RULE WHERE APPLICABILITY_RULE_ID < 0;
SELECT 'FEE_TIMING_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_TIMING_RULE WHERE TIMING_RULE_ID < 0;
SELECT 'FEE_CURRENCY_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CURRENCY_RULE WHERE CURRENCY_RULE_ID < 0;
SELECT 'FEE_COLLECTION_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_COLLECTION_RULE WHERE COLLECTION_RULE_ID < 0;
SELECT 'FEE_POSTING_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_POSTING_RULE WHERE POSTING_RULE_ID < 0;
SELECT 'FEE_ALLOCATION_POLICY' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ALLOCATION_POLICY WHERE ALLOCATION_POLICY_ID < 0;
SELECT 'FEE_ARRANGEMENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ARRANGEMENT WHERE FEE_ARRANGEMENT_ID < 0;
SELECT 'FEE_APPLICABILITY_CONDITION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_APPLICABILITY_CONDITION WHERE CONDITION_ID < 0;
SELECT 'FEE_CALCULATION_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CALCULATION_RULE WHERE CALCULATION_RULE_ID < 0;
SELECT 'FEE_ALLOCATION_RULE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ALLOCATION_RULE WHERE ALLOCATION_RULE_ID < 0;
SELECT 'FEE_ARRANGEMENT_INVOLVEMENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ARRANGEMENT_INVOLVEMENT WHERE INVOLVEMENT_ID < 0;
SELECT 'FEE_ARRANGEMENT_ACCOUNT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ARRANGEMENT_ACCOUNT WHERE ARRANGEMENT_ACCOUNT_ID < 0;
SELECT 'FEE_ARRANGEMENT_MODALITY' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ARRANGEMENT_MODALITY WHERE ARRANGEMENT_MODALITY_ID < 0;
SELECT 'FEE_INSTRUCTION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_INSTRUCTION WHERE FEE_INSTRUCTION_ID < 0;
SELECT 'FEE_INPUT_DEFINITION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_INPUT_DEFINITION WHERE INPUT_DEF_ID < 0;
SELECT 'FEE_CALCULATION_TIER' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CALCULATION_TIER WHERE TIER_ID < 0;
SELECT 'FEE_RULE_COMPONENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_RULE_COMPONENT WHERE RULE_COMPONENT_ID < 0;
SELECT 'FEE_CHARGE_COMPONENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CHARGE_COMPONENT WHERE CHARGE_COMPONENT_ID < 0;
SELECT 'FEE_ARRANGEMENT_CALC_TERM' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ARRANGEMENT_CALC_TERM WHERE ARRANGEMENT_CALC_TERM_ID < 0;
SELECT 'FEE_TRANSACTION' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_TRANSACTION WHERE FEE_TRANSACTION_ID < 0;
SELECT 'FEE_CHARGE_STAGE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CHARGE_STAGE WHERE CHARGE_STAGE_ID < 0;
SELECT 'FEE_ADJUSTMENT_POLICY' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ADJUSTMENT_POLICY WHERE ADJUSTMENT_POLICY_ID < 0;
SELECT 'FEE_TRANSACTION_COMPONENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_TRANSACTION_COMPONENT WHERE TRANSACTION_COMPONENT_ID < 0;
SELECT 'FEE_CALCULATION_SNAPSHOT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_CALCULATION_SNAPSHOT WHERE CALCULATION_SNAPSHOT_ID < 0;
SELECT 'FEE_ALLOCATION_RESULT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_ALLOCATION_RESULT WHERE ALLOCATION_RESULT_ID < 0;
SELECT 'FEE_OVERRIDE_REQUEST' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_OVERRIDE_REQUEST WHERE OVERRIDE_REQUEST_ID < 0;
SELECT 'FEE_REVERSAL' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_REVERSAL WHERE FEE_REVERSAL_ID < 0;
SELECT 'FEE_DECISION_TRACE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_DECISION_TRACE WHERE TRACE_ID < 0;
SELECT 'FEE_APPLIED_ADJUSTMENT' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_APPLIED_ADJUSTMENT WHERE APPLIED_ADJUSTMENT_ID < 0;
SELECT 'FEE_SETTLEMENT_REFERENCE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_SETTLEMENT_REFERENCE WHERE SETTLEMENT_REFERENCE_ID < 0;
SELECT 'FEE_POSTING_REFERENCE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_POSTING_REFERENCE WHERE POSTING_REFERENCE_ID < 0;
SELECT 'FEE_AUDIT_EVIDENCE' TABLE_NAME, COUNT(*) SEED_ROWS FROM FEE_AUDIT_EVIDENCE WHERE AUDIT_EVIDENCE_ID < 0;

PROMPT === Core scenario verification ===
SELECT FEE_CODE, NAME_FA FROM FEE_DEFINITION WHERE FEE_DEFINITION_ID < 0 ORDER BY FEE_CODE;
SELECT TRANSACTION_NO, GROSS_FEE_AMOUNT, ADJUSTMENT_AMOUNT, NET_FEE_AMOUNT, COLLECTED_AMOUNT, STATUS_CODE FROM FEE_TRANSACTION WHERE FEE_TRANSACTION_ID < 0;
SELECT BENEFICIARY_ROLE_CODE, ALLOCATION_PERCENT, ALLOCATION_AMOUNT FROM FEE_ALLOCATION_RESULT WHERE FEE_TRANSACTION_ID=-12101 ORDER BY ALLOCATION_RESULT_ID;
