
  CREATE TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE 
   (	ACCRUAL_FREQUENCY_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_ACCRUAL_FREQUENCY_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_AML_RISK_MAX_CODE 
   (	AML_RISK_MAX_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_AML_RISK_MAX_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_APPROVAL_LEVEL_CODE 
   (	APPROVAL_LEVEL_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_APPROVAL_LEVEL_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_BALANCE_DESTINATION_CODE 
   (	BALANCE_DESTINATION_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_BALANCE_DESTINATION_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_CHANNEL_CODE 
   (	CHANNEL_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_CHANNEL_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_CHECK_TYPE_CODE 
   (	CHECK_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_CHECK_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_CLOSURE_TYPE_CODE 
   (	CLOSURE_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_CLOSURE_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_CUSTOMER_SEGMENT_CODE 
   (	CUSTOMER_SEGMENT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_CUSTOMER_SEGMENT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DAY_COUNT_BASIS_CODE 
   (	DAY_COUNT_BASIS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DAY_COUNT_BASIS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DEFAULT_CURRENCY_CODE 
   (	DEFAULT_CURRENCY_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DEFAULT_CURRENCY_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DEPOSIT_GROUP_CODE 
   (	DEPOSIT_GROUP_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DEPOSIT_GROUP_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DEPOSIT_PRODUCT_CODE 
   (	DEPOSIT_PRODUCT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DEPOSIT_PRODUCT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DEPOSIT_TYPE_CODE 
   (	DEPOSIT_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DEPOSIT_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DESTINATION_CODE 
   (	DESTINATION_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DESTINATION_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_DOCUMENT_TYPE_CODE 
   (	DOCUMENT_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_DOCUMENT_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_FAILURE_ACTION_CODE 
   (	FAILURE_ACTION_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_FAILURE_ACTION_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_GENDER_CODE 
   (	GENDER_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_GENDER_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_HOLD_TYPE_CODE 
   (	HOLD_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_HOLD_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE 
   (	HOLIDAY_ADJUSTMENT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_HOLIDAY_ADJUSTMENT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE 
   (	INACTIVITY_PERIOD_UNIT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_INACTIVITY_PERIOD_UNIT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_INQUIRY_TYPE_CODE 
   (	INQUIRY_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_INQUIRY_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_KYC_LEVEL_CODE 
   (	KYC_LEVEL_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_KYC_LEVEL_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_NATIONALITY_SCOPE_CODE 
   (	NATIONALITY_SCOPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_NATIONALITY_SCOPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_OPENING_STATUS_CODE 
   (	OPENING_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_OPENING_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_ORG_UNIT_CODE 
   (	ORG_UNIT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_ORG_UNIT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_ORG_UNIT_TYPE_CODE 
   (	ORG_UNIT_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_ORG_UNIT_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_OWNERSHIP_TYPE_CODE 
   (	OWNERSHIP_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_OWNERSHIP_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PARTY_TYPE_CODE 
   (	PARTY_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PARTY_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PAYMENT_FREQUENCY_CODE 
   (	PAYMENT_FREQUENCY_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PAYMENT_FREQUENCY_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PRODUCT_FAMILY_CODE 
   (	PRODUCT_FAMILY_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PRODUCT_FAMILY_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PRODUCT_STATUS_CODE 
   (	PRODUCT_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PRODUCT_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE 
   (	PROFIT_DESTINATION_RULE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PROFIT_DESTINATION_RULE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE 
   (	PROFIT_DISTRIBUTION_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PROFIT_DISTRIBUTION_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_PROFIT_METHOD_CODE 
   (	PROFIT_METHOD_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_PROFIT_METHOD_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_REACTIVATION_METHOD_CODE 
   (	REACTIVATION_METHOD_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_REACTIVATION_METHOD_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_RELATIONSHIP_TYPE_CODE 
   (	RELATIONSHIP_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_RELATIONSHIP_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE 
   (	RENEWAL_INSTRUCTION_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_RENEWAL_INSTRUCTION_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_REQUIREMENT_STAGE_CODE 
   (	REQUIREMENT_STAGE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_REQUIREMENT_STAGE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_RESIDENCY_STATUS_CODE 
   (	RESIDENCY_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_RESIDENCY_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_RULE_STATUS_CODE 
   (	RULE_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_RULE_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_SERVICING_STATUS_CODE 
   (	SERVICING_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_SERVICING_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE 
   (	SETTLEMENT_COMPONENT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_SETTLEMENT_COMPONENT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_SETTLEMENT_METHOD_CODE 
   (	SETTLEMENT_METHOD_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_SETTLEMENT_METHOD_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_SIGNING_RULE_CODE 
   (	SIGNING_RULE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_SIGNING_RULE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_STATUS_CODE 
   (	STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_TERM_UNIT_CODE 
   (	TERM_UNIT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_TERM_UNIT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_TRANSACTION_TYPE_CODE 
   (	TRANSACTION_TYPE_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_TRANSACTION_TYPE_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	PARENT_CODE VARCHAR2(50 CHAR), 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_VERSION_STATUS_CODE 
   (	VERSION_STATUS_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_VERSION_STATUS_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE 
   (	WARNING_PERIOD_UNIT_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_WARNING_PERIOD_UNIT_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;

  CREATE TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE 
   (	WITHDRAWAL_MEDIA_ID NUMBER(19,0) DEFAULT DPS.SEQ_REF_WITHDRAWAL_MEDIA_CODE.NEXTVAL, 
	CODE VARCHAR2(50 CHAR), 
	NAME_FA VARCHAR2(200 CHAR), 
	NAME_EN VARCHAR2(200 CHAR), 
	DESCRIPTION VARCHAR2(1000 CHAR), 
	IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
	VALID_FROM DATE, 
	VALID_TO DATE, 
	VERSION_NO NUMBER(10,0) DEFAULT 1, 
	IS_CURRENT NUMBER(1,0) DEFAULT 1, 
	RECORD_VERSION NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE TS_DPS ;