
ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE ADD CONSTRAINT CK_ACCRUAL_FREQUEN_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE ADD CONSTRAINT CK_ACCRUAL_FREQUEN_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE ADD CONSTRAINT CK_ACCRUAL_FREQ_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (ACCRUAL_FREQUENCY_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE ADD CONSTRAINT CK_AML_RISK_MAX_CO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE ADD CONSTRAINT CK_AML_RISK_MAX_CO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE ADD CONSTRAINT CK_AML_RISK_MAX_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (AML_RISK_MAX_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_AML_RISK_MAX_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE ADD CONSTRAINT CK_APPROVAL_LEVEL_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE ADD CONSTRAINT CK_APPROVAL_LEVEL_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE ADD CONSTRAINT CK_APPROVAL_LEV_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (APPROVAL_LEVEL_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE ADD CONSTRAINT CK_BALANCE_DESTINA_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE ADD CONSTRAINT CK_BALANCE_DESTINA_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE ADD CONSTRAINT CK_BALANCE_DEST_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (BALANCE_DESTINATION_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT CK_CHANNEL_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT CK_CHANNEL_CODE_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT CK_CHANNEL_CODE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT CK_CHANNEL_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (CHANNEL_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHANNEL_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE ADD CONSTRAINT CK_CHECK_TYPE_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_CHECK_TYPE_CODE ADD CONSTRAINT CK_CHECK_TYPE_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_CHECK_TYPE_CODE ADD CONSTRAINT CK_CHECK_TYPE_C_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (CHECK_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_CHECK_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE ADD CONSTRAINT CK_CLOSURE_TYPE_CO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE ADD CONSTRAINT CK_CLOSURE_TYPE_CO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE ADD CONSTRAINT CK_CLOSURE_TYPE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (CLOSURE_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT CK_CUSTOMER_SEGMEN_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT CK_CUSTOMER_SEGMEN_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT CK_CUSTOMER_SEGMEN_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT CK_CUSTOMER_SEG_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (CUSTOMER_SEGMENT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE ADD CONSTRAINT CK_DAY_COUNT_BASIS_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE ADD CONSTRAINT CK_DAY_COUNT_BASIS_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE ADD CONSTRAINT CK_DAY_COUNT_BA_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (DAY_COUNT_BASIS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE ADD CONSTRAINT CK_DEFAULT_CURRENC_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE ADD CONSTRAINT CK_DEFAULT_CURRENC_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE ADD CONSTRAINT CK_DEFAULT_CURR_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (DEFAULT_CURRENCY_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE ADD CONSTRAINT CK_DEPOSIT_GROUP_C_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE ADD CONSTRAINT CK_DEPOSIT_GROUP_C_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE ADD CONSTRAINT CK_DEPOSIT_GROU_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (DEPOSIT_GROUP_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE ADD CONSTRAINT CK_DEPOSIT_PRODUCT_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE ADD CONSTRAINT CK_DEPOSIT_PRODUCT_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE ADD CONSTRAINT CK_DEPOSIT_PROD_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (DEPOSIT_PRODUCT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE ADD CONSTRAINT CK_DEPOSIT_TYPE_CO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE ADD CONSTRAINT CK_DEPOSIT_TYPE_CO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE ADD CONSTRAINT CK_DEPOSIT_TYPE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (DEPOSIT_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT CK_DESTINATION_COD_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT CK_DESTINATION_COD_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT CK_DESTINATION_COD_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT CK_DESTINATION_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (DESTINATION_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DESTINATION_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT CK_DOCUMENT_TYPE_C_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT CK_DOCUMENT_TYPE_C_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT CK_DOCUMENT_TYPE_C_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT CK_DOCUMENT_TYP_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (DOCUMENT_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE ADD CONSTRAINT CK_FAILURE_ACTION_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE ADD CONSTRAINT CK_FAILURE_ACTION_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE ADD CONSTRAINT CK_FAILURE_ACTI_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (FAILURE_ACTION_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_FAILURE_ACTION_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE ADD CONSTRAINT CK_GENDER_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_GENDER_CODE ADD CONSTRAINT CK_GENDER_CODE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (GENDER_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_GENDER_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE ADD CONSTRAINT CK_HOLD_TYPE_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_HOLD_TYPE_CODE ADD CONSTRAINT CK_HOLD_TYPE_CODE_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_HOLD_TYPE_CODE ADD CONSTRAINT CK_HOLD_TYPE_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (HOLD_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLD_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE ADD CONSTRAINT CK_HOLIDAY_ADJUSTM_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE ADD CONSTRAINT CK_HOLIDAY_ADJUSTM_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE ADD CONSTRAINT CK_HOLIDAY_ADJU_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (HOLIDAY_ADJUSTMENT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE ADD CONSTRAINT CK_INACTIVITY_PERI_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE ADD CONSTRAINT CK_INACTIVITY_P_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (INACTIVITY_PERIOD_UNIT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT CK_INQUIRY_TYPE_CO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT CK_INQUIRY_TYPE_CO_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT CK_INQUIRY_TYPE_CO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT CK_INQUIRY_TYPE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (INQUIRY_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE ADD CONSTRAINT CK_KYC_LEVEL_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_KYC_LEVEL_CODE ADD CONSTRAINT CK_KYC_LEVEL_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_KYC_LEVEL_CODE ADD CONSTRAINT CK_KYC_LEVEL_CO_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (KYC_LEVEL_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_KYC_LEVEL_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE ADD CONSTRAINT CK_NATIONALITY_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE ADD CONSTRAINT CK_NATIONALITY_SCO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE ADD CONSTRAINT CK_NATIONALITY_SCO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (NATIONALITY_SCOPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE ADD CONSTRAINT CK_OPENING_STATUS_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_OPENING_STATUS_CODE ADD CONSTRAINT CK_OPENING_STATUS_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_OPENING_STATUS_CODE ADD CONSTRAINT CK_OPENING_STAT_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (OPENING_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_OPENING_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT CK_ORG_UNIT_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT CK_ORG_UNIT_CODE_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT CK_ORG_UNIT_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT CK_ORG_UNIT_COD_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (ORG_UNIT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE ADD CONSTRAINT CK_ORG_UNIT_TYPE_C_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE ADD CONSTRAINT CK_ORG_UNIT_TYPE_C_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE ADD CONSTRAINT CK_ORG_UNIT_TYP_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (ORG_UNIT_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE ADD CONSTRAINT CK_OWNERSHIP_TYPE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE ADD CONSTRAINT CK_OWNERSHIP_TYPE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE ADD CONSTRAINT CK_OWNERSHIP_TY_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (OWNERSHIP_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT CK_PARTY_TYPE_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT CK_PARTY_TYPE_CODE_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT CK_PARTY_TYPE_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT CK_PARTY_TYPE_C_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (PARTY_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PARTY_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE ADD CONSTRAINT CK_PAYMENT_FREQUEN_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE ADD CONSTRAINT CK_PAYMENT_FREQUEN_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE ADD CONSTRAINT CK_PAYMENT_FREQ_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (PAYMENT_FREQUENCY_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE ADD CONSTRAINT CK_PRODUCT_FAMILY_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE ADD CONSTRAINT CK_PRODUCT_FAMILY_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE ADD CONSTRAINT CK_PRODUCT_FAMI_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (PRODUCT_FAMILY_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE ADD CONSTRAINT CK_PRODUCT_STATUS_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE ADD CONSTRAINT CK_PRODUCT_STATUS_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE ADD CONSTRAINT CK_PRODUCT_STAT_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE MODIFY (PRODUCT_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE ADD CONSTRAINT CK_PROFIT_DESTINAT_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE ADD CONSTRAINT CK_PROFIT_DESTINAT_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE ADD CONSTRAINT CK_PROFIT_DESTI_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (PROFIT_DESTINATION_RULE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE ADD CONSTRAINT CK_PROFIT_DISTRIBU_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE ADD CONSTRAINT CK_PROFIT_DISTRIBU_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE ADD CONSTRAINT CK_PROFIT_DISTR_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (PROFIT_DISTRIBUTION_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE ADD CONSTRAINT CK_PROFIT_METHOD_C_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE ADD CONSTRAINT CK_PROFIT_METHOD_C_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE ADD CONSTRAINT CK_PROFIT_METHO_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (PROFIT_METHOD_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_PROFIT_METHOD_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE ADD CONSTRAINT CK_REACTIVATION_ME_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE ADD CONSTRAINT CK_REACTIVATION_ME_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE ADD CONSTRAINT CK_REACTIVATION_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (REACTIVATION_METHOD_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT CK_RELATIONSHIP_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT CK_RELATIONSHIP_TY_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT CK_RELATIONSHIP_TY_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT CK_RELATIONSHIP_TY_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (RELATIONSHIP_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE ADD CONSTRAINT CK_RENEWAL_INSTRUC_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE ADD CONSTRAINT CK_RENEWAL_INSTRUC_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE ADD CONSTRAINT CK_RENEWAL_INST_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (RENEWAL_INSTRUCTION_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE ADD CONSTRAINT CK_REQUIREMENT_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE ADD CONSTRAINT CK_REQUIREMENT_STA_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE ADD CONSTRAINT CK_REQUIREMENT_STA_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (REQUIREMENT_STAGE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE ADD CONSTRAINT CK_RESIDENCY_STATU_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE ADD CONSTRAINT CK_RESIDENCY_STATU_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE ADD CONSTRAINT CK_RESIDENCY_ST_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (RESIDENCY_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE ADD CONSTRAINT CK_RULE_STATUS_COD_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_RULE_STATUS_CODE ADD CONSTRAINT CK_RULE_STATUS_COD_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_RULE_STATUS_CODE ADD CONSTRAINT CK_RULE_STATUS_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (RULE_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_RULE_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE ADD CONSTRAINT CK_SERVICING_STATU_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE ADD CONSTRAINT CK_SERVICING_STATU_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE ADD CONSTRAINT CK_SERVICING_ST_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (SERVICING_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_SERVICING_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE ADD CONSTRAINT CK_SETTLEMENT_COMP_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE ADD CONSTRAINT CK_SETTLEMENT_COMP_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE ADD CONSTRAINT CK_SETTLEMENT_C_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (SETTLEMENT_COMPONENT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE ADD CONSTRAINT CK_SETTLEMENT_METH_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE ADD CONSTRAINT CK_SETTLEMENT_METH_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE ADD CONSTRAINT CK_SETTLEMENT_M_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (SETTLEMENT_METHOD_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE ADD CONSTRAINT CK_SIGNING_RULE_CO_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_SIGNING_RULE_CODE ADD CONSTRAINT CK_SIGNING_RULE_CO_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_SIGNING_RULE_CODE ADD CONSTRAINT CK_SIGNING_RULE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (SIGNING_RULE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_SIGNING_RULE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE ADD CONSTRAINT CK_STATUS_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_STATUS_CODE ADD CONSTRAINT CK_STATUS_CODE_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_STATUS_CODE ADD CONSTRAINT CK_STATUS_CODE_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE ADD CONSTRAINT CK_TERM_UNIT_CODE_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_TERM_UNIT_CODE ADD CONSTRAINT CK_TERM_UNIT_CO_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (TERM_UNIT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_TERM_UNIT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT CK_TRANSACTION_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT CK_TRANSACTION_TYP_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT CK_TRANSACTION_TYP_PARENT_CODE CHECK (PARENT_CODE IS NULL OR PARENT_CODE <> CODE) ENABLE;

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT CK_TRANSACTION_TYP_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (TRANSACTION_TYPE_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE ADD CONSTRAINT CK_VERSION_STATUS_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_VERSION_STATUS_CODE ADD CONSTRAINT CK_VERSION_STATUS_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_VERSION_STATUS_CODE ADD CONSTRAINT CK_VERSION_STAT_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (VERSION_STATUS_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_VERSION_STATUS_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE ADD CONSTRAINT CK_WARNING_PERIOD_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE ADD CONSTRAINT CK_WARNING_PERI_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (WARNING_PERIOD_UNIT_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE ADD CONSTRAINT CK_WITHDRAWAL_MEDI_ACTIVE_FLAG CHECK (IS_ACTIVE IN (0,1)) ENABLE;

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE ADD CONSTRAINT CK_WITHDRAWAL_MEDI_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM) ENABLE;

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE ADD CONSTRAINT CK_WITHDRAWAL_M_RECORD_VERSION CHECK (RECORD_VERSION > 0) ENABLE;

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (WITHDRAWAL_MEDIA_ID NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (NAME_FA NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (IS_ACTIVE NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (VERSION_NO NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (IS_CURRENT NOT NULL ENABLE);

ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE MODIFY (RECORD_VERSION NOT NULL ENABLE);