
  ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE ADD CONSTRAINT PK_REF_ACCRUAL_FREQUENCY_CODE_ID PRIMARY KEY (ACCRUAL_FREQUENCY_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_ACCRUAL_FREQUENCY_CODE ADD CONSTRAINT UK_REF_ACCRUAL_FREQUENCY_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_AML_RISK_MAX_CODE ADD CONSTRAINT PK_REF_AML_RISK_MAX_CODE_ID PRIMARY KEY (AML_RISK_MAX_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_AML_RISK_MAX_CODE ADD CONSTRAINT UK_REF_AML_RISK_MAX_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE ADD CONSTRAINT PK_REF_APPROVAL_LEVEL_CODE_ID PRIMARY KEY (APPROVAL_LEVEL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_APPROVAL_LEVEL_CODE ADD CONSTRAINT UK_REF_APPROVAL_LEVEL_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE ADD CONSTRAINT PK_REF_BALANCE_DESTINATION_CODE_ID PRIMARY KEY (BALANCE_DESTINATION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_BALANCE_DESTINATION_CODE ADD CONSTRAINT UK_REF_BALANCE_DESTINATION_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT PK_REF_CHANNEL_CODE_ID PRIMARY KEY (CHANNEL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CHANNEL_CODE ADD CONSTRAINT UK_REF_CHANNEL_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CHECK_TYPE_CODE ADD CONSTRAINT PK_REF_CHECK_TYPE_CODE_ID PRIMARY KEY (CHECK_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CHECK_TYPE_CODE ADD CONSTRAINT UK_REF_CHECK_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE ADD CONSTRAINT PK_REF_CLOSURE_TYPE_CODE_ID PRIMARY KEY (CLOSURE_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CLOSURE_TYPE_CODE ADD CONSTRAINT UK_REF_CLOSURE_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT PK_REF_CUSTOMER_SEGMENT_CODE_ID PRIMARY KEY (CUSTOMER_SEGMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_CUSTOMER_SEGMENT_CODE ADD CONSTRAINT UK_REF_CUSTOMER_SEGMENT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE ADD CONSTRAINT PK_REF_DAY_COUNT_BASIS_CODE_ID PRIMARY KEY (DAY_COUNT_BASIS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DAY_COUNT_BASIS_CODE ADD CONSTRAINT UK_REF_DAY_COUNT_BASIS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE ADD CONSTRAINT PK_REF_DEFAULT_CURRENCY_CODE_ID PRIMARY KEY (DEFAULT_CURRENCY_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEFAULT_CURRENCY_CODE ADD CONSTRAINT UK_REF_DEFAULT_CURRENCY_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE ADD CONSTRAINT PK_REF_DEPOSIT_GROUP_CODE_ID PRIMARY KEY (DEPOSIT_GROUP_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_GROUP_CODE ADD CONSTRAINT UK_REF_DEPOSIT_GROUP_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE ADD CONSTRAINT PK_REF_DEPOSIT_PRODUCT_CODE_ID PRIMARY KEY (DEPOSIT_PRODUCT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_PRODUCT_CODE ADD CONSTRAINT UK_REF_DEPOSIT_PRODUCT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE ADD CONSTRAINT PK_REF_DEPOSIT_TYPE_CODE_ID PRIMARY KEY (DEPOSIT_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DEPOSIT_TYPE_CODE ADD CONSTRAINT UK_REF_DEPOSIT_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT PK_REF_DESTINATION_CODE_ID PRIMARY KEY (DESTINATION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DESTINATION_CODE ADD CONSTRAINT UK_REF_DESTINATION_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT PK_REF_DOCUMENT_TYPE_CODE_ID PRIMARY KEY (DOCUMENT_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_DOCUMENT_TYPE_CODE ADD CONSTRAINT UK_REF_DOCUMENT_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_FAILURE_ACTION_CODE ADD CONSTRAINT PK_REF_FAILURE_ACTION_CODE_ID PRIMARY KEY (FAILURE_ACTION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_FAILURE_ACTION_CODE ADD CONSTRAINT UK_REF_FAILURE_ACTION_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_GENDER_CODE ADD CONSTRAINT PK_REF_GENDER_CODE_ID PRIMARY KEY (GENDER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_GENDER_CODE ADD CONSTRAINT UK_REF_GENDER_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_HOLD_TYPE_CODE ADD CONSTRAINT PK_REF_HOLD_TYPE_CODE_ID PRIMARY KEY (HOLD_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_HOLD_TYPE_CODE ADD CONSTRAINT UK_REF_HOLD_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE ADD CONSTRAINT PK_REF_HOLIDAY_ADJUSTMENT_CODE_ID PRIMARY KEY (HOLIDAY_ADJUSTMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_HOLIDAY_ADJUSTMENT_CODE ADD CONSTRAINT UK_REF_HOLIDAY_ADJUSTMENT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE ADD CONSTRAINT PK_REF_INACTIVITY_PERIOD_UNIT_CODE_ID PRIMARY KEY (INACTIVITY_PERIOD_UNIT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_INACTIVITY_PERIOD_UNIT_CODE ADD CONSTRAINT UK_REF_INACTIVITY_PERIOD_UNIT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT PK_REF_INQUIRY_TYPE_CODE_ID PRIMARY KEY (INQUIRY_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_INQUIRY_TYPE_CODE ADD CONSTRAINT UK_REF_INQUIRY_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_KYC_LEVEL_CODE ADD CONSTRAINT PK_REF_KYC_LEVEL_CODE_ID PRIMARY KEY (KYC_LEVEL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_KYC_LEVEL_CODE ADD CONSTRAINT UK_REF_KYC_LEVEL_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE ADD CONSTRAINT PK_REF_NATIONALITY_SCOPE_CODE_ID PRIMARY KEY (NATIONALITY_SCOPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_NATIONALITY_SCOPE_CODE ADD CONSTRAINT UK_REF_NATIONALITY_SCOPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_OPENING_STATUS_CODE ADD CONSTRAINT PK_REF_OPENING_STATUS_CODE_ID PRIMARY KEY (OPENING_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_OPENING_STATUS_CODE ADD CONSTRAINT UK_REF_OPENING_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT PK_REF_ORG_UNIT_CODE_ID PRIMARY KEY (ORG_UNIT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_ORG_UNIT_CODE ADD CONSTRAINT UK_REF_ORG_UNIT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE ADD CONSTRAINT PK_REF_ORG_UNIT_TYPE_CODE_ID PRIMARY KEY (ORG_UNIT_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_ORG_UNIT_TYPE_CODE ADD CONSTRAINT UK_REF_ORG_UNIT_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE ADD CONSTRAINT PK_REF_OWNERSHIP_TYPE_CODE_ID PRIMARY KEY (OWNERSHIP_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_OWNERSHIP_TYPE_CODE ADD CONSTRAINT UK_REF_OWNERSHIP_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT PK_REF_PARTY_TYPE_CODE_ID PRIMARY KEY (PARTY_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PARTY_TYPE_CODE ADD CONSTRAINT UK_REF_PARTY_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE ADD CONSTRAINT PK_REF_PAYMENT_FREQUENCY_CODE_ID PRIMARY KEY (PAYMENT_FREQUENCY_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PAYMENT_FREQUENCY_CODE ADD CONSTRAINT UK_REF_PAYMENT_FREQUENCY_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE ADD CONSTRAINT PK_REF_PRODUCT_FAMILY_CODE_ID PRIMARY KEY (PRODUCT_FAMILY_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PRODUCT_FAMILY_CODE ADD CONSTRAINT UK_REF_PRODUCT_FAMILY_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE ADD CONSTRAINT PK_REF_PRODUCT_STATUS_CODE_ID PRIMARY KEY (PRODUCT_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PRODUCT_STATUS_CODE ADD CONSTRAINT UK_REF_PRODUCT_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE ADD CONSTRAINT PK_REF_PROFIT_DESTINATION_RULE_CODE_ID PRIMARY KEY (PROFIT_DESTINATION_RULE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_DESTINATION_RULE_CODE ADD CONSTRAINT UK_REF_PROFIT_DESTINATION_RULE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE ADD CONSTRAINT PK_REF_PROFIT_DISTRIBUTION_CODE_ID PRIMARY KEY (PROFIT_DISTRIBUTION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_DISTRIBUTION_CODE ADD CONSTRAINT UK_REF_PROFIT_DISTRIBUTION_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_METHOD_CODE ADD CONSTRAINT PK_REF_PROFIT_METHOD_CODE_ID PRIMARY KEY (PROFIT_METHOD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_PROFIT_METHOD_CODE ADD CONSTRAINT UK_REF_PROFIT_METHOD_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE ADD CONSTRAINT PK_REF_REACTIVATION_METHOD_CODE_ID PRIMARY KEY (REACTIVATION_METHOD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_REACTIVATION_METHOD_CODE ADD CONSTRAINT UK_REF_REACTIVATION_METHOD_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT PK_REF_RELATIONSHIP_TYPE_CODE_ID PRIMARY KEY (RELATIONSHIP_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RELATIONSHIP_TYPE_CODE ADD CONSTRAINT UK_REF_RELATIONSHIP_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE ADD CONSTRAINT PK_REF_RENEWAL_INSTRUCTION_CODE_ID PRIMARY KEY (RENEWAL_INSTRUCTION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RENEWAL_INSTRUCTION_CODE ADD CONSTRAINT UK_REF_RENEWAL_INSTRUCTION_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE ADD CONSTRAINT PK_REF_REQUIREMENT_STAGE_CODE_ID PRIMARY KEY (REQUIREMENT_STAGE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_REQUIREMENT_STAGE_CODE ADD CONSTRAINT UK_REF_REQUIREMENT_STAGE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE ADD CONSTRAINT PK_REF_RESIDENCY_STATUS_CODE_ID PRIMARY KEY (RESIDENCY_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RESIDENCY_STATUS_CODE ADD CONSTRAINT UK_REF_RESIDENCY_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RULE_STATUS_CODE ADD CONSTRAINT PK_REF_RULE_STATUS_CODE_ID PRIMARY KEY (RULE_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_RULE_STATUS_CODE ADD CONSTRAINT UK_REF_RULE_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SERVICING_STATUS_CODE ADD CONSTRAINT PK_REF_SERVICING_STATUS_CODE_ID PRIMARY KEY (SERVICING_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SERVICING_STATUS_CODE ADD CONSTRAINT UK_REF_SERVICING_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE ADD CONSTRAINT PK_REF_SETTLEMENT_COMPONENT_CODE_ID PRIMARY KEY (SETTLEMENT_COMPONENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SETTLEMENT_COMPONENT_CODE ADD CONSTRAINT UK_REF_SETTLEMENT_COMPONENT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE ADD CONSTRAINT PK_REF_SETTLEMENT_METHOD_CODE_ID PRIMARY KEY (SETTLEMENT_METHOD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SETTLEMENT_METHOD_CODE ADD CONSTRAINT UK_REF_SETTLEMENT_METHOD_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SIGNING_RULE_CODE ADD CONSTRAINT PK_REF_SIGNING_RULE_CODE_ID PRIMARY KEY (SIGNING_RULE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_SIGNING_RULE_CODE ADD CONSTRAINT UK_REF_SIGNING_RULE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_STATUS_CODE ADD CONSTRAINT PK_REF_STATUS_CODE_ID PRIMARY KEY (STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_STATUS_CODE ADD CONSTRAINT UK_REF_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_TERM_UNIT_CODE ADD CONSTRAINT PK_REF_TERM_UNIT_CODE_ID PRIMARY KEY (TERM_UNIT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_TERM_UNIT_CODE ADD CONSTRAINT UK_REF_TERM_UNIT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT PK_REF_TRANSACTION_TYPE_CODE_ID PRIMARY KEY (TRANSACTION_TYPE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_TRANSACTION_TYPE_CODE ADD CONSTRAINT UK_REF_TRANSACTION_TYPE_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_VERSION_STATUS_CODE ADD CONSTRAINT PK_REF_VERSION_STATUS_CODE_ID PRIMARY KEY (VERSION_STATUS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_VERSION_STATUS_CODE ADD CONSTRAINT UK_REF_VERSION_STATUS_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE ADD CONSTRAINT PK_REF_WARNING_PERIOD_UNIT_CODE_ID PRIMARY KEY (WARNING_PERIOD_UNIT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_WARNING_PERIOD_UNIT_CODE ADD CONSTRAINT UK_REF_WARNING_PERIOD_UNIT_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE ADD CONSTRAINT PK_REF_WITHDRAWAL_MEDIA_CODE_ID PRIMARY KEY (WITHDRAWAL_MEDIA_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS  ENABLE;

  ALTER TABLE DPS.REF_WITHDRAWAL_MEDIA_CODE ADD CONSTRAINT UK_REF_WITHDRAWAL_MEDIA_CODE_CODE_VER UNIQUE (CODE, VERSION_NO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS  ENABLE;