
  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT ON DPS.DEPOSIT_PRODUCT (DEPOSIT_PRODUCT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DEPOSIT_PRODUCT_CODE ON DPS.DEPOSIT_PRODUCT (DEPOSIT_PRODUCT_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPCR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_CHANNEL_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_CHANNEL_RUL ON DPS.DEPOSIT_PRODUCT_CHANNEL_RULE (CHANNEL_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPCR_VER_CHANNEL ON DPS.DEPOSIT_PRODUCT_CHANNEL_RULE (DEPOSIT_PRODUCT_VERSION_ID, CHANNEL_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DP_CLOSURE_APPROVAL ON DPS.DEPOSIT_PRODUCT_CLOSURE_APPROVAL_RULE (CLOSURE_APPROVAL_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DP_CLOS_APPROVAL_LEVEL ON DPS.DEPOSIT_PRODUCT_CLOSURE_APPROVAL_RULE (CLOSURE_RULE_ID, APPROVAL_LEVEL_CODE, APPROVAL_SEQUENCE_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DP_CLOSURE_PRECHECK ON DPS.DEPOSIT_PRODUCT_CLOSURE_PRECHECK (CLOSURE_PRECHECK_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DP_CLOS_PRECHECK_TYPE ON DPS.DEPOSIT_PRODUCT_CLOSURE_PRECHECK (CLOSURE_RULE_ID, CHECK_TYPE_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DP_CLOSURE_VERSION ON DPS.DEPOSIT_PRODUCT_CLOSURE_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_CLOSURE_RULE ON DPS.DEPOSIT_PRODUCT_CLOSURE_RULE (CLOSURE_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DP_CLOSURE_VER_TYPE_FROM ON DPS.DEPOSIT_PRODUCT_CLOSURE_RULE (DEPOSIT_PRODUCT_VERSION_ID, CLOSURE_TYPE_CODE, EFFECTIVE_FROM_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DP_CLOSURE_SETTLEMENT ON DPS.DEPOSIT_PRODUCT_CLOSURE_SETTLEMENT_RULE (CLOSURE_SETTLEMENT_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DP_CLOS_SETTLEMENT_COMP ON DPS.DEPOSIT_PRODUCT_CLOSURE_SETTLEMENT_RULE (CLOSURE_RULE_ID, SETTLEMENT_COMPONENT_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPDR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_DORMANCY_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_DORMANCY_RU ON DPS.DEPOSIT_PRODUCT_DORMANCY_RULE (DORMANCY_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPE_VERSION_ID ON DPS.DEPOSIT_PRODUCT_ELIGIBILITY (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_ELIGIBILITY ON DPS.DEPOSIT_PRODUCT_ELIGIBILITY (ELIGIBILITY_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_HOLD_RULE ON DPS.DEPOSIT_PRODUCT_HOLD_RULE (HOLD_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPJR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_JOINT_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_JOINT_RULE ON DPS.DEPOSIT_PRODUCT_JOINT_RULE (JOINT_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPOR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_OPENING_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_OPENING_RUL ON DPS.DEPOSIT_PRODUCT_OPENING_RULE (OPENING_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPOS_VERSION_ID ON DPS.DEPOSIT_PRODUCT_ORG_SCOPE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_ORG_SCOPE ON DPS.DEPOSIT_PRODUCT_ORG_SCOPE (ORG_SCOPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPOS_VER_UNIT ON DPS.DEPOSIT_PRODUCT_ORG_SCOPE (DEPOSIT_PRODUCT_VERSION_ID, ORG_UNIT_TYPE_CODE, ORG_UNIT_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPPR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_PROFIT_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_PROFIT_RULE ON DPS.DEPOSIT_PRODUCT_PROFIT_RULE (PROFIT_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPPT_RULE_ID ON DPS.DEPOSIT_PRODUCT_PROFIT_TIER (PROFIT_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_PROFIT_TIER ON DPS.DEPOSIT_PRODUCT_PROFIT_TIER (PROFIT_TIER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPPT_RULE_TIER ON DPS.DEPOSIT_PRODUCT_PROFIT_TIER (PROFIT_RULE_ID, TIER_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPREL_SOURCE_ID ON DPS.DEPOSIT_PRODUCT_RELATIONSHIP (SOURCE_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPREL_TARGET_ID ON DPS.DEPOSIT_PRODUCT_RELATIONSHIP (TARGET_PRODUCT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_RELATIONSHIP ON DPS.DEPOSIT_PRODUCT_RELATIONSHIP (PRODUCT_RELATIONSHIP_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPRD_VERSION_ID ON DPS.DEPOSIT_PRODUCT_REQUIRED_DOCUMENT (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_REQUIRED_DO ON DPS.DEPOSIT_PRODUCT_REQUIRED_DOCUMENT (REQUIRED_DOCUMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPRD_VER_DOC_STAGE ON DPS.DEPOSIT_PRODUCT_REQUIRED_DOCUMENT (DEPOSIT_PRODUCT_VERSION_ID, DOCUMENT_TYPE_CODE, REQUIREMENT_STAGE_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPRI_VERSION_ID ON DPS.DEPOSIT_PRODUCT_REQUIRED_INQUIRY (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_REQUIRED_IN ON DPS.DEPOSIT_PRODUCT_REQUIRED_INQUIRY (REQUIRED_INQUIRY_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPRI_VER_INQ_STAGE ON DPS.DEPOSIT_PRODUCT_REQUIRED_INQUIRY (DEPOSIT_PRODUCT_VERSION_ID, INQUIRY_TYPE_CODE, REQUIREMENT_STAGE_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPTR_VERSION_ID ON DPS.DEPOSIT_PRODUCT_TERM_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_TERM_RULE ON DPS.DEPOSIT_PRODUCT_TERM_RULE (TERM_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPTRX_VERSION_ID ON DPS.DEPOSIT_PRODUCT_TRANSACTION_RULE (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_TRANSACTION ON DPS.DEPOSIT_PRODUCT_TRANSACTION_RULE (TRANSACTION_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPTRX_VER_TYPE ON DPS.DEPOSIT_PRODUCT_TRANSACTION_RULE (DEPOSIT_PRODUCT_VERSION_ID, TRANSACTION_TYPE_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPV_PRODUCT_ID ON DPS.DEPOSIT_PRODUCT_VERSION (DEPOSIT_PRODUCT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_VERSION ON DPS.DEPOSIT_PRODUCT_VERSION (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPV_PRODUCT_VERSION ON DPS.DEPOSIT_PRODUCT_VERSION (DEPOSIT_PRODUCT_ID, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE INDEX DPS.IX_DPWM_VERSION_ID ON DPS.DEPOSIT_PRODUCT_WITHDRAWAL_MEDIA (DEPOSIT_PRODUCT_VERSION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_DEPOSIT_PRODUCT_WITHDRAWAL ON DPS.DEPOSIT_PRODUCT_WITHDRAWAL_MEDIA (DEPOSIT_PRODUCT_WITHDRAWAL_MEDIA_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_DPWM_VER_MEDIA_CHANNEL ON DPS.DEPOSIT_PRODUCT_WITHDRAWAL_MEDIA (DEPOSIT_PRODUCT_VERSION_ID, WITHDRAWAL_MEDIA_CODE, CHANNEL_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_ACCRUAL_FREQUENCY_CODE_ID ON DPS.REF_ACCRUAL_FREQUENCY_CODE (ACCRUAL_FREQUENCY_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_ACCRUAL_FREQUENCY_CODE_CODE_VER ON DPS.REF_ACCRUAL_FREQUENCY_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_AML_RISK_MAX_CODE_ID ON DPS.REF_AML_RISK_MAX_CODE (AML_RISK_MAX_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_AML_RISK_MAX_CODE_CODE_VER ON DPS.REF_AML_RISK_MAX_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_APPROVAL_LEVEL_CODE_ID ON DPS.REF_APPROVAL_LEVEL_CODE (APPROVAL_LEVEL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_APPROVAL_LEVEL_CODE_CODE_VER ON DPS.REF_APPROVAL_LEVEL_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_BALANCE_DESTINATION_CODE_ID ON DPS.REF_BALANCE_DESTINATION_CODE (BALANCE_DESTINATION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_BALANCE_DESTINATION_CODE_CODE_VER ON DPS.REF_BALANCE_DESTINATION_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_CHANNEL_CODE_ID ON DPS.REF_CHANNEL_CODE (CHANNEL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_CHANNEL_CODE_CODE_VER ON DPS.REF_CHANNEL_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_CHECK_TYPE_CODE_ID ON DPS.REF_CHECK_TYPE_CODE (CHECK_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_CHECK_TYPE_CODE_CODE_VER ON DPS.REF_CHECK_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_CLOSURE_TYPE_CODE_ID ON DPS.REF_CLOSURE_TYPE_CODE (CLOSURE_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_CLOSURE_TYPE_CODE_CODE_VER ON DPS.REF_CLOSURE_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_CUSTOMER_SEGMENT_CODE_ID ON DPS.REF_CUSTOMER_SEGMENT_CODE (CUSTOMER_SEGMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_CUSTOMER_SEGMENT_CODE_CODE_VER ON DPS.REF_CUSTOMER_SEGMENT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DAY_COUNT_BASIS_CODE_ID ON DPS.REF_DAY_COUNT_BASIS_CODE (DAY_COUNT_BASIS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DAY_COUNT_BASIS_CODE_CODE_VER ON DPS.REF_DAY_COUNT_BASIS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DEFAULT_CURRENCY_CODE_ID ON DPS.REF_DEFAULT_CURRENCY_CODE (DEFAULT_CURRENCY_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DEFAULT_CURRENCY_CODE_CODE_VER ON DPS.REF_DEFAULT_CURRENCY_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DEPOSIT_GROUP_CODE_ID ON DPS.REF_DEPOSIT_GROUP_CODE (DEPOSIT_GROUP_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DEPOSIT_GROUP_CODE_CODE_VER ON DPS.REF_DEPOSIT_GROUP_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DEPOSIT_PRODUCT_CODE_ID ON DPS.REF_DEPOSIT_PRODUCT_CODE (DEPOSIT_PRODUCT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DEPOSIT_PRODUCT_CODE_CODE_VER ON DPS.REF_DEPOSIT_PRODUCT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DEPOSIT_TYPE_CODE_ID ON DPS.REF_DEPOSIT_TYPE_CODE (DEPOSIT_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DEPOSIT_TYPE_CODE_CODE_VER ON DPS.REF_DEPOSIT_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DESTINATION_CODE_ID ON DPS.REF_DESTINATION_CODE (DESTINATION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DESTINATION_CODE_CODE_VER ON DPS.REF_DESTINATION_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_DOCUMENT_TYPE_CODE_ID ON DPS.REF_DOCUMENT_TYPE_CODE (DOCUMENT_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_DOCUMENT_TYPE_CODE_CODE_VER ON DPS.REF_DOCUMENT_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_FAILURE_ACTION_CODE_ID ON DPS.REF_FAILURE_ACTION_CODE (FAILURE_ACTION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_FAILURE_ACTION_CODE_CODE_VER ON DPS.REF_FAILURE_ACTION_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_GENDER_CODE_ID ON DPS.REF_GENDER_CODE (GENDER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_GENDER_CODE_CODE_VER ON DPS.REF_GENDER_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_HOLD_TYPE_CODE_ID ON DPS.REF_HOLD_TYPE_CODE (HOLD_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_HOLD_TYPE_CODE_CODE_VER ON DPS.REF_HOLD_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_HOLIDAY_ADJUSTMENT_CODE_ID ON DPS.REF_HOLIDAY_ADJUSTMENT_CODE (HOLIDAY_ADJUSTMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_HOLIDAY_ADJUSTMENT_CODE_CODE_VER ON DPS.REF_HOLIDAY_ADJUSTMENT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_INACTIVITY_PERIOD_UNIT_CODE_ID ON DPS.REF_INACTIVITY_PERIOD_UNIT_CODE (INACTIVITY_PERIOD_UNIT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_INACTIVITY_PERIOD_UNIT_CODE_CODE_VER ON DPS.REF_INACTIVITY_PERIOD_UNIT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_INQUIRY_TYPE_CODE_ID ON DPS.REF_INQUIRY_TYPE_CODE (INQUIRY_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_INQUIRY_TYPE_CODE_CODE_VER ON DPS.REF_INQUIRY_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_KYC_LEVEL_CODE_ID ON DPS.REF_KYC_LEVEL_CODE (KYC_LEVEL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_KYC_LEVEL_CODE_CODE_VER ON DPS.REF_KYC_LEVEL_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_NATIONALITY_SCOPE_CODE_ID ON DPS.REF_NATIONALITY_SCOPE_CODE (NATIONALITY_SCOPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_NATIONALITY_SCOPE_CODE_CODE_VER ON DPS.REF_NATIONALITY_SCOPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_OPENING_STATUS_CODE_ID ON DPS.REF_OPENING_STATUS_CODE (OPENING_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_OPENING_STATUS_CODE_CODE_VER ON DPS.REF_OPENING_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_ORG_UNIT_CODE_ID ON DPS.REF_ORG_UNIT_CODE (ORG_UNIT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_ORG_UNIT_CODE_CODE_VER ON DPS.REF_ORG_UNIT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_ORG_UNIT_TYPE_CODE_ID ON DPS.REF_ORG_UNIT_TYPE_CODE (ORG_UNIT_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_ORG_UNIT_TYPE_CODE_CODE_VER ON DPS.REF_ORG_UNIT_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_OWNERSHIP_TYPE_CODE_ID ON DPS.REF_OWNERSHIP_TYPE_CODE (OWNERSHIP_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_OWNERSHIP_TYPE_CODE_CODE_VER ON DPS.REF_OWNERSHIP_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PARTY_TYPE_CODE_ID ON DPS.REF_PARTY_TYPE_CODE (PARTY_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PARTY_TYPE_CODE_CODE_VER ON DPS.REF_PARTY_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PAYMENT_FREQUENCY_CODE_ID ON DPS.REF_PAYMENT_FREQUENCY_CODE (PAYMENT_FREQUENCY_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PAYMENT_FREQUENCY_CODE_CODE_VER ON DPS.REF_PAYMENT_FREQUENCY_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PRODUCT_FAMILY_CODE_ID ON DPS.REF_PRODUCT_FAMILY_CODE (PRODUCT_FAMILY_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PRODUCT_FAMILY_CODE_CODE_VER ON DPS.REF_PRODUCT_FAMILY_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PRODUCT_STATUS_CODE_ID ON DPS.REF_PRODUCT_STATUS_CODE (PRODUCT_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PRODUCT_STATUS_CODE_CODE_VER ON DPS.REF_PRODUCT_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PROFIT_DESTINATION_RULE_CODE_ID ON DPS.REF_PROFIT_DESTINATION_RULE_CODE (PROFIT_DESTINATION_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PROFIT_DESTINATION_RULE_CODE_CODE_VER ON DPS.REF_PROFIT_DESTINATION_RULE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PROFIT_DISTRIBUTION_CODE_ID ON DPS.REF_PROFIT_DISTRIBUTION_CODE (PROFIT_DISTRIBUTION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PROFIT_DISTRIBUTION_CODE_CODE_VER ON DPS.REF_PROFIT_DISTRIBUTION_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_PROFIT_METHOD_CODE_ID ON DPS.REF_PROFIT_METHOD_CODE (PROFIT_METHOD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_PROFIT_METHOD_CODE_CODE_VER ON DPS.REF_PROFIT_METHOD_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_REACTIVATION_METHOD_CODE_ID ON DPS.REF_REACTIVATION_METHOD_CODE (REACTIVATION_METHOD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_REACTIVATION_METHOD_CODE_CODE_VER ON DPS.REF_REACTIVATION_METHOD_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_RELATIONSHIP_TYPE_CODE_ID ON DPS.REF_RELATIONSHIP_TYPE_CODE (RELATIONSHIP_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_RELATIONSHIP_TYPE_CODE_CODE_VER ON DPS.REF_RELATIONSHIP_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_RENEWAL_INSTRUCTION_CODE_ID ON DPS.REF_RENEWAL_INSTRUCTION_CODE (RENEWAL_INSTRUCTION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_RENEWAL_INSTRUCTION_CODE_CODE_VER ON DPS.REF_RENEWAL_INSTRUCTION_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_REQUIREMENT_STAGE_CODE_ID ON DPS.REF_REQUIREMENT_STAGE_CODE (REQUIREMENT_STAGE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_REQUIREMENT_STAGE_CODE_CODE_VER ON DPS.REF_REQUIREMENT_STAGE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_RESIDENCY_STATUS_CODE_ID ON DPS.REF_RESIDENCY_STATUS_CODE (RESIDENCY_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_RESIDENCY_STATUS_CODE_CODE_VER ON DPS.REF_RESIDENCY_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_RULE_STATUS_CODE_ID ON DPS.REF_RULE_STATUS_CODE (RULE_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_RULE_STATUS_CODE_CODE_VER ON DPS.REF_RULE_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_SERVICING_STATUS_CODE_ID ON DPS.REF_SERVICING_STATUS_CODE (SERVICING_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_SERVICING_STATUS_CODE_CODE_VER ON DPS.REF_SERVICING_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_SETTLEMENT_COMPONENT_CODE_ID ON DPS.REF_SETTLEMENT_COMPONENT_CODE (SETTLEMENT_COMPONENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_SETTLEMENT_COMPONENT_CODE_CODE_VER ON DPS.REF_SETTLEMENT_COMPONENT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_SETTLEMENT_METHOD_CODE_ID ON DPS.REF_SETTLEMENT_METHOD_CODE (SETTLEMENT_METHOD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_SETTLEMENT_METHOD_CODE_CODE_VER ON DPS.REF_SETTLEMENT_METHOD_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_SIGNING_RULE_CODE_ID ON DPS.REF_SIGNING_RULE_CODE (SIGNING_RULE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_SIGNING_RULE_CODE_CODE_VER ON DPS.REF_SIGNING_RULE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_STATUS_CODE_ID ON DPS.REF_STATUS_CODE (STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_STATUS_CODE_CODE_VER ON DPS.REF_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_TERM_UNIT_CODE_ID ON DPS.REF_TERM_UNIT_CODE (TERM_UNIT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_TERM_UNIT_CODE_CODE_VER ON DPS.REF_TERM_UNIT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_TRANSACTION_TYPE_CODE_ID ON DPS.REF_TRANSACTION_TYPE_CODE (TRANSACTION_TYPE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_TRANSACTION_TYPE_CODE_CODE_VER ON DPS.REF_TRANSACTION_TYPE_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_VERSION_STATUS_CODE_ID ON DPS.REF_VERSION_STATUS_CODE (VERSION_STATUS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_VERSION_STATUS_CODE_CODE_VER ON DPS.REF_VERSION_STATUS_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_WARNING_PERIOD_UNIT_CODE_ID ON DPS.REF_WARNING_PERIOD_UNIT_CODE (WARNING_PERIOD_UNIT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_WARNING_PERIOD_UNIT_CODE_CODE_VER ON DPS.REF_WARNING_PERIOD_UNIT_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.PK_REF_WITHDRAWAL_MEDIA_CODE_ID ON DPS.REF_WITHDRAWAL_MEDIA_CODE (WITHDRAWAL_MEDIA_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ITS_DPS; 

  CREATE UNIQUE INDEX DPS.UK_REF_WITHDRAWAL_MEDIA_CODE_CODE_VER ON DPS.REF_WITHDRAWAL_MEDIA_CODE (CODE, VERSION_NO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE ITS_DPS; 