-- R10 diagnostic only. No DML. Reports active duplicate business definitions.
-- Review output before any cleanup decision.

PROMPT === ACTIVE DEPOSIT ACCOUNT LIMIT DUPLICATES ===
SELECT
    ACCOUNT_ID,
    LIMIT_TYPE_CODE,
    NVL(TRANSACTION_TYPE_CODE,'*') AS TRANSACTION_SCOPE,
    NVL(CHANNEL_CODE,'*') AS CHANNEL_SCOPE,
    AMOUNT_LIMIT,
    COUNT_LIMIT,
    SOURCE_CODE,
    COUNT(*) AS DUPLICATE_COUNT,
    MIN(ACCOUNT_LIMIT_ID) AS FIRST_LIMIT_ID,
    MAX(ACCOUNT_LIMIT_ID) AS LAST_LIMIT_ID
FROM DPS2.DEPOSIT_ACCOUNT_LIMIT
WHERE STATUS_CODE = 'ACTIVE'
GROUP BY
    ACCOUNT_ID,
    LIMIT_TYPE_CODE,
    NVL(TRANSACTION_TYPE_CODE,'*'),
    NVL(CHANNEL_CODE,'*'),
    AMOUNT_LIMIT,
    COUNT_LIMIT,
    SOURCE_CODE
HAVING COUNT(*) > 1
ORDER BY ACCOUNT_ID, LIMIT_TYPE_CODE, TRANSACTION_SCOPE, CHANNEL_SCOPE;

PROMPT === ACTIVE TRANSACTION RESTRICTION DUPLICATES ===
SELECT
    ACCOUNT_ID,
    TRANSACTION_TYPE_CODE,
    NVL(CHANNEL_CODE,'*') AS CHANNEL_SCOPE,
    NVL(DIRECTION_CODE,'*') AS DIRECTION_SCOPE,
    RESTRICTION_MODE_CODE,
    MAX_AMOUNT,
    SOURCE_CODE,
    COUNT(*) AS DUPLICATE_COUNT,
    MIN(ACCOUNT_TX_RESTRICTION_ID) AS FIRST_RESTRICTION_ID,
    MAX(ACCOUNT_TX_RESTRICTION_ID) AS LAST_RESTRICTION_ID
FROM DPS2.DEPOSIT_ACCOUNT_TRANSACTION_RESTRICTION
WHERE STATUS_CODE = 'ACTIVE'
GROUP BY
    ACCOUNT_ID,
    TRANSACTION_TYPE_CODE,
    NVL(CHANNEL_CODE,'*'),
    NVL(DIRECTION_CODE,'*'),
    RESTRICTION_MODE_CODE,
    MAX_AMOUNT,
    SOURCE_CODE
HAVING COUNT(*) > 1
ORDER BY ACCOUNT_ID, TRANSACTION_TYPE_CODE, CHANNEL_SCOPE, DIRECTION_SCOPE;
