-- Phase 5: Workflow and Interaction reference data.
-- Generated from the supplied Party/Customer reference model; Persian UI labels were reviewed manually.
-- Target schema CIF

PROMPT Creating CIF.REF_ACTOR_ROLE
CREATE TABLE CIF.REF_ACTOR_ROLE (
  ACTOR_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ACTOR_ROLE PRIMARY KEY (ACTOR_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ACTOR_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ACTOR_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ACTOR_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ACTOR_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_ACTION
CREATE TABLE CIF.REF_AUDIT_ACTION (
  AUDIT_ACTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_ACTION PRIMARY KEY (AUDIT_ACTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_ACTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_ACTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_ACTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_ACTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_ENTITY_TYPE
CREATE TABLE CIF.REF_AUDIT_ENTITY_TYPE (
  AUDIT_ENTITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_ENTITY_TYPE PRIMARY KEY (AUDIT_ENTITY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_REASON
CREATE TABLE CIF.REF_AUDIT_REASON (
  AUDIT_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_REASON PRIMARY KEY (AUDIT_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_RESOLUTION
CREATE TABLE CIF.REF_COMPLAINT_RESOLUTION (
  COMPLAINT_RESOLUTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_RESOLUTION PRIMARY KEY (COMPLAINT_RESOLUTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_RESOLUTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_STATUS
CREATE TABLE CIF.REF_COMPLAINT_STATUS (
  COMPLAINT_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_STATUS PRIMARY KEY (COMPLAINT_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_STATUS_REASON
CREATE TABLE CIF.REF_COMPLAINT_STATUS_REASON (
  COMPLAINT_STATUS_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_STATUS_REASON PRIMARY KEY (COMPLAINT_STATUS_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_01 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_03 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_04 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_TYPE
CREATE TABLE CIF.REF_COMPLAINT_TYPE (
  COMPLAINT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_TYPE PRIMARY KEY (COMPLAINT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_HASH_ALGORITHM
CREATE TABLE CIF.REF_HASH_ALGORITHM (
  HASH_ALGORITHM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HASH_ALGORITHM PRIMARY KEY (HASH_ALGORITHM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_HASH_ALGORITHM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_HASH_ALGORITHM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_HASH_ALGORITHM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_HASH_ALGORITHM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INTERACTION_OUTCOME
CREATE TABLE CIF.REF_INTERACTION_OUTCOME (
  INTERACTION_OUTCOME_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INTERACTION_OUTCOME PRIMARY KEY (INTERACTION_OUTCOME_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INTERACTION_OUTCOME_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INTERACTION_OUTCOME_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INTERACTION_OUTCOME_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INTERACTION_OUTCOME_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INTERACTION_TYPE
CREATE TABLE CIF.REF_INTERACTION_TYPE (
  INTERACTION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INTERACTION_TYPE PRIMARY KEY (INTERACTION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INTERACTION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INTERACTION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INTERACTION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INTERACTION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY
CREATE TABLE CIF.REF_JOURNEY (
  JOURNEY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY PRIMARY KEY (JOURNEY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY_EVENT_TYPE
CREATE TABLE CIF.REF_JOURNEY_EVENT_TYPE (
  JOURNEY_EVENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY_EVENT_TYPE PRIMARY KEY (JOURNEY_EVENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY_STAGE
CREATE TABLE CIF.REF_JOURNEY_STAGE (
  JOURNEY_STAGE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY_STAGE PRIMARY KEY (JOURNEY_STAGE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_STAGE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_STAGE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_STAGE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_STAGE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PREFERENCE_TYPE
CREATE TABLE CIF.REF_PREFERENCE_TYPE (
  PREFERENCE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PREFERENCE_TYPE PRIMARY KEY (PREFERENCE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PREFERENCE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PREFERENCE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PREFERENCE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PREFERENCE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_REFERENCE_TYPE
CREATE TABLE CIF.REF_REFERENCE_TYPE (
  REFERENCE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_REFERENCE_TYPE PRIMARY KEY (REFERENCE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_REFERENCE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_REFERENCE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_REFERENCE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_REFERENCE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_WORKFLOW_STATUS
CREATE TABLE CIF.REF_WORKFLOW_STATUS (
  STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_WORKFLOW_STATUS PRIMARY KEY (STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_WORKFLOW_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_WORKFLOW_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_WORKFLOW_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_WORKFLOW_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

ALTER TABLE CIF.REF_JOURNEY_STAGE ADD CONSTRAINT FK_JOURNEY_STAGE_JOURNEY FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_JOURNEY (JOURNEY_CODE);
ALTER TABLE CIF.REF_JOURNEY_EVENT_TYPE ADD CONSTRAINT FK_JOURNEY_EVENT_STAGE FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_JOURNEY_STAGE (JOURNEY_STAGE_CODE);
