-- Phase 5: Workflow and Interaction reference data.
-- Generated from the supplied Party/Customer reference model; Persian UI labels were reviewed manually.
-- Target schema CIF

PROMPT Creating CIF.REF_ACTOR_ROLE
CREATE TABLE CIF.REF_ACTOR_ROLE (
  ACTOR_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ACTOR_ROLE PRIMARY KEY (ACTOR_ROLE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ACTOR_ROLE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ACTOR_ROLE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ACTOR_ROLE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ACTOR_ROLE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_ACTION
CREATE TABLE CIF.REF_AUDIT_ACTION (
  AUDIT_ACTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_ACTION PRIMARY KEY (AUDIT_ACTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_ACTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_ACTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_ACTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_ACTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_ENTITY_TYPE
CREATE TABLE CIF.REF_AUDIT_ENTITY_TYPE (
  AUDIT_ENTITY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_ENTITY_TYPE PRIMARY KEY (AUDIT_ENTITY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_ENTITY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_AUDIT_REASON
CREATE TABLE CIF.REF_AUDIT_REASON (
  AUDIT_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_AUDIT_REASON PRIMARY KEY (AUDIT_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_AUDIT_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_AUDIT_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_AUDIT_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_AUDIT_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_RESOLUTION
CREATE TABLE CIF.REF_COMPLAINT_RESOLUTION (
  COMPLAINT_RESOLUTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_RESOLUTION PRIMARY KEY (COMPLAINT_RESOLUTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_RESOLUTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_RESOLUTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_STATUS
CREATE TABLE CIF.REF_COMPLAINT_STATUS (
  COMPLAINT_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_STATUS PRIMARY KEY (COMPLAINT_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_STATUS_REASON
CREATE TABLE CIF.REF_COMPLAINT_STATUS_REASON (
  COMPLAINT_STATUS_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_STATUS_REASON PRIMARY KEY (COMPLAINT_STATUS_REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_01 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_02 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_03 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_STATUS_REASON_04 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_COMPLAINT_TYPE
CREATE TABLE CIF.REF_COMPLAINT_TYPE (
  COMPLAINT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMPLAINT_TYPE PRIMARY KEY (COMPLAINT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_COMPLAINT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_COMPLAINT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_COMPLAINT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_COMPLAINT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_HASH_ALGORITHM
CREATE TABLE CIF.REF_HASH_ALGORITHM (
  HASH_ALGORITHM_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HASH_ALGORITHM PRIMARY KEY (HASH_ALGORITHM_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_HASH_ALGORITHM_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_HASH_ALGORITHM_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_HASH_ALGORITHM_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_HASH_ALGORITHM_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INTERACTION_OUTCOME
CREATE TABLE CIF.REF_INTERACTION_OUTCOME (
  INTERACTION_OUTCOME_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INTERACTION_OUTCOME PRIMARY KEY (INTERACTION_OUTCOME_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INTERACTION_OUTCOME_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INTERACTION_OUTCOME_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INTERACTION_OUTCOME_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INTERACTION_OUTCOME_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INTERACTION_TYPE
CREATE TABLE CIF.REF_INTERACTION_TYPE (
  INTERACTION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INTERACTION_TYPE PRIMARY KEY (INTERACTION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INTERACTION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INTERACTION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INTERACTION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INTERACTION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY
CREATE TABLE CIF.REF_JOURNEY (
  JOURNEY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY PRIMARY KEY (JOURNEY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY_EVENT_TYPE
CREATE TABLE CIF.REF_JOURNEY_EVENT_TYPE (
  JOURNEY_EVENT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY_EVENT_TYPE PRIMARY KEY (JOURNEY_EVENT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_EVENT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_JOURNEY_STAGE
CREATE TABLE CIF.REF_JOURNEY_STAGE (
  JOURNEY_STAGE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JOURNEY_STAGE PRIMARY KEY (JOURNEY_STAGE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_JOURNEY_STAGE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_JOURNEY_STAGE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_JOURNEY_STAGE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_JOURNEY_STAGE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_PREFERENCE_TYPE
CREATE TABLE CIF.REF_PREFERENCE_TYPE (
  PREFERENCE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PREFERENCE_TYPE PRIMARY KEY (PREFERENCE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_PREFERENCE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PREFERENCE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_PREFERENCE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_PREFERENCE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_REFERENCE_TYPE
CREATE TABLE CIF.REF_REFERENCE_TYPE (
  REFERENCE_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_REFERENCE_TYPE PRIMARY KEY (REFERENCE_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_REFERENCE_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_REFERENCE_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_REFERENCE_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_REFERENCE_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_WORKFLOW_STATUS
CREATE TABLE CIF.REF_WORKFLOW_STATUS (
  STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_WORKFLOW_STATUS PRIMARY KEY (STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_WORKFLOW_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_WORKFLOW_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_WORKFLOW_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_WORKFLOW_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

ALTER TABLE CIF.REF_JOURNEY_STAGE ADD CONSTRAINT FK_JOURNEY_STAGE_JOURNEY FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_JOURNEY (JOURNEY_CODE);
ALTER TABLE CIF.REF_JOURNEY_EVENT_TYPE ADD CONSTRAINT FK_JOURNEY_EVENT_STAGE FOREIGN KEY (PARENT_CODE) REFERENCES CIF.REF_JOURNEY_STAGE (JOURNEY_STAGE_CODE);


-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.ACTOR_ROLE_CODE IS 'کد نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.NAME_FA IS 'عنوان فارسی نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.NAME_EN IS 'عنوان انگلیسی نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.DESCRIPTION_FA IS 'توضیحات فارسی نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.SORT_ORDER IS 'ترتیب نمایش نقش عامل عملیات در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.IS_ACTIVE IS 'نشانگر فعال بودن نقش عامل عملیات؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.PARENT_CODE IS 'کد والد نقش عامل عملیات در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.VALID_FROM IS 'تاریخ شروع اعتبار نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.VALID_TO IS 'تاریخ پایان اعتبار نقش عامل عملیات';
COMMENT ON COLUMN CIF.REF_ACTOR_ROLE.RECORD_VERSION IS 'شماره نسخه رکورد نقش عامل عملیات برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.AUDIT_ACTION_CODE IS 'کد نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.NAME_FA IS 'عنوان فارسی نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.NAME_EN IS 'عنوان انگلیسی نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.DESCRIPTION_FA IS 'توضیحات فارسی نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.SORT_ORDER IS 'ترتیب نمایش نوع عملیات ممیزی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.IS_ACTIVE IS 'نشانگر فعال بودن نوع عملیات ممیزی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.PARENT_CODE IS 'کد والد نوع عملیات ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.VALID_FROM IS 'تاریخ شروع اعتبار نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.VALID_TO IS 'تاریخ پایان اعتبار نوع عملیات ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ACTION.RECORD_VERSION IS 'شماره نسخه رکورد نوع عملیات ممیزی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.AUDIT_ENTITY_TYPE_CODE IS 'کد نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.NAME_FA IS 'عنوان فارسی نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.NAME_EN IS 'عنوان انگلیسی نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع موجودیت ممیزی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع موجودیت ممیزی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.PARENT_CODE IS 'کد والد نوع موجودیت ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع موجودیت ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_ENTITY_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع موجودیت ممیزی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.AUDIT_REASON_CODE IS 'کد دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.NAME_FA IS 'عنوان فارسی دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.NAME_EN IS 'عنوان انگلیسی دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.DESCRIPTION_FA IS 'توضیحات فارسی دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.SORT_ORDER IS 'ترتیب نمایش دلیل ممیزی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.IS_ACTIVE IS 'نشانگر فعال بودن دلیل ممیزی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.PARENT_CODE IS 'کد والد دلیل ممیزی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.VALID_FROM IS 'تاریخ شروع اعتبار دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.VALID_TO IS 'تاریخ پایان اعتبار دلیل ممیزی';
COMMENT ON COLUMN CIF.REF_AUDIT_REASON.RECORD_VERSION IS 'شماره نسخه رکورد دلیل ممیزی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.COMPLAINT_RESOLUTION_CODE IS 'کد نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.NAME_FA IS 'عنوان فارسی نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.NAME_EN IS 'عنوان انگلیسی نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.DESCRIPTION_FA IS 'توضیحات فارسی نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.SORT_ORDER IS 'ترتیب نمایش نتیجه رسیدگی به شکایت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.IS_ACTIVE IS 'نشانگر فعال بودن نتیجه رسیدگی به شکایت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.PARENT_CODE IS 'کد والد نتیجه رسیدگی به شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.VALID_FROM IS 'تاریخ شروع اعتبار نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.VALID_TO IS 'تاریخ پایان اعتبار نتیجه رسیدگی به شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_RESOLUTION.RECORD_VERSION IS 'شماره نسخه رکورد نتیجه رسیدگی به شکایت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.COMPLAINT_STATUS_CODE IS 'کد وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.NAME_FA IS 'عنوان فارسی وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت شکایت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت شکایت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.PARENT_CODE IS 'کد والد وضعیت شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت شکایت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.COMPLAINT_STATUS_REASON_CODE IS 'کد دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.NAME_FA IS 'عنوان فارسی دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.NAME_EN IS 'عنوان انگلیسی دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.DESCRIPTION_FA IS 'توضیحات فارسی دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.SORT_ORDER IS 'ترتیب نمایش دلیل تغییر وضعیت شکایت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.IS_ACTIVE IS 'نشانگر فعال بودن دلیل تغییر وضعیت شکایت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.PARENT_CODE IS 'کد والد دلیل تغییر وضعیت شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.VALID_FROM IS 'تاریخ شروع اعتبار دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.VALID_TO IS 'تاریخ پایان اعتبار دلیل تغییر وضعیت شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_STATUS_REASON.RECORD_VERSION IS 'شماره نسخه رکورد دلیل تغییر وضعیت شکایت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.COMPLAINT_TYPE_CODE IS 'کد نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.NAME_FA IS 'عنوان فارسی نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع شکایت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع شکایت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.PARENT_CODE IS 'کد والد نوع شکایت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع شکایت';
COMMENT ON COLUMN CIF.REF_COMPLAINT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع شکایت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.HASH_ALGORITHM_CODE IS 'کد الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.NAME_FA IS 'عنوان فارسی الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.NAME_EN IS 'عنوان انگلیسی الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.DESCRIPTION_FA IS 'توضیحات فارسی الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.SORT_ORDER IS 'ترتیب نمایش الگوریتم هش در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.IS_ACTIVE IS 'نشانگر فعال بودن الگوریتم هش؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.PARENT_CODE IS 'کد والد الگوریتم هش در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.VALID_FROM IS 'تاریخ شروع اعتبار الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.VALID_TO IS 'تاریخ پایان اعتبار الگوریتم هش';
COMMENT ON COLUMN CIF.REF_HASH_ALGORITHM.RECORD_VERSION IS 'شماره نسخه رکورد الگوریتم هش برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.INTERACTION_OUTCOME_CODE IS 'کد نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.NAME_FA IS 'عنوان فارسی نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.NAME_EN IS 'عنوان انگلیسی نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.DESCRIPTION_FA IS 'توضیحات فارسی نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.SORT_ORDER IS 'ترتیب نمایش نتیجه تعامل در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.IS_ACTIVE IS 'نشانگر فعال بودن نتیجه تعامل؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.PARENT_CODE IS 'کد والد نتیجه تعامل در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.VALID_FROM IS 'تاریخ شروع اعتبار نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.VALID_TO IS 'تاریخ پایان اعتبار نتیجه تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_OUTCOME.RECORD_VERSION IS 'شماره نسخه رکورد نتیجه تعامل برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.INTERACTION_TYPE_CODE IS 'کد نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.NAME_FA IS 'عنوان فارسی نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.NAME_EN IS 'عنوان انگلیسی نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع تعامل در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع تعامل؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.PARENT_CODE IS 'کد والد نوع تعامل در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع تعامل';
COMMENT ON COLUMN CIF.REF_INTERACTION_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع تعامل برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_JOURNEY.JOURNEY_CODE IS 'کد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.NAME_FA IS 'عنوان فارسی سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.NAME_EN IS 'عنوان انگلیسی سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.DESCRIPTION_FA IS 'توضیحات فارسی سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.SORT_ORDER IS 'ترتیب نمایش سفر مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_JOURNEY.IS_ACTIVE IS 'نشانگر فعال بودن سفر مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_JOURNEY.PARENT_CODE IS 'کد والد سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_JOURNEY.VALID_FROM IS 'تاریخ شروع اعتبار سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.VALID_TO IS 'تاریخ پایان اعتبار سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY.RECORD_VERSION IS 'شماره نسخه رکورد سفر مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.JOURNEY_EVENT_TYPE_CODE IS 'کد نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.NAME_FA IS 'عنوان فارسی نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع رویداد سفر مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع رویداد سفر مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.PARENT_CODE IS 'کد والد نوع رویداد سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع رویداد سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_EVENT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع رویداد سفر مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.JOURNEY_STAGE_CODE IS 'کد مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.NAME_FA IS 'عنوان فارسی مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.NAME_EN IS 'عنوان انگلیسی مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.DESCRIPTION_FA IS 'توضیحات فارسی مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.SORT_ORDER IS 'ترتیب نمایش مرحله سفر مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.IS_ACTIVE IS 'نشانگر فعال بودن مرحله سفر مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.PARENT_CODE IS 'کد والد مرحله سفر مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.VALID_FROM IS 'تاریخ شروع اعتبار مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.VALID_TO IS 'تاریخ پایان اعتبار مرحله سفر مشتری';
COMMENT ON COLUMN CIF.REF_JOURNEY_STAGE.RECORD_VERSION IS 'شماره نسخه رکورد مرحله سفر مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.PREFERENCE_TYPE_CODE IS 'کد نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.NAME_FA IS 'عنوان فارسی نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.NAME_EN IS 'عنوان انگلیسی نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع ترجیح مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع ترجیح مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.PARENT_CODE IS 'کد والد نوع ترجیح مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع ترجیح مشتری';
COMMENT ON COLUMN CIF.REF_PREFERENCE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع ترجیح مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.REFERENCE_TYPE_CODE IS 'کد نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.NAME_FA IS 'عنوان فارسی نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.NAME_EN IS 'عنوان انگلیسی نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع مرجع مرتبط در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع مرجع مرتبط؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.PARENT_CODE IS 'کد والد نوع مرجع مرتبط در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع مرجع مرتبط';
COMMENT ON COLUMN CIF.REF_REFERENCE_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع مرجع مرتبط برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.STATUS_CODE IS 'کد وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.NAME_FA IS 'عنوان فارسی وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت گردش‌کار در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت گردش‌کار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.PARENT_CODE IS 'کد والد وضعیت گردش‌کار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت گردش‌کار';
COMMENT ON COLUMN CIF.REF_WORKFLOW_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت گردش‌کار برای کنترل هم‌زمانی';
