-- Generated from Party_Customer_Reference_Data_Interactive_Forms_FA.html
-- Phase 2: Compliance, Risk and KYC reference data
-- Target schema: CIF
-- Tablespace: TS_CIF; PK indexes: ITS_CIF

PROMPT Creating CIF.REF_ALERT_RESOLUTION
CREATE TABLE CIF.REF_ALERT_RESOLUTION (
  RESOLUTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ALERT_RESOLUTION PRIMARY KEY (RESOLUTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ALERT_RESOLUTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ALERT_RESOLUTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ALERT_RESOLUTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ALERT_RESOLUTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ALERT_TYPE
CREATE TABLE CIF.REF_ALERT_TYPE (
  ALERT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ALERT_TYPE PRIMARY KEY (ALERT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ALERT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ALERT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ALERT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ALERT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DECISION
CREATE TABLE CIF.REF_DECISION (
  DECISION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DECISION PRIMARY KEY (DECISION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DECISION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DECISION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DECISION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DECISION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DUE_DILIGENCE_LEVEL
CREATE TABLE CIF.REF_DUE_DILIGENCE_LEVEL (
  DUE_DILIGENCE_LEVEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DUE_DILIGENCE_LEVEL PRIMARY KEY (DUE_DILIGENCE_LEVEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INQUIRY_RESULT
CREATE TABLE CIF.REF_INQUIRY_RESULT (
  INQUIRY_RESULT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INQUIRY_RESULT PRIMARY KEY (INQUIRY_RESULT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INQUIRY_RESULT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INQUIRY_RESULT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INQUIRY_RESULT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INQUIRY_RESULT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INQUIRY_TYPE
CREATE TABLE CIF.REF_INQUIRY_TYPE (
  INQUIRY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INQUIRY_TYPE PRIMARY KEY (INQUIRY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INQUIRY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INQUIRY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INQUIRY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INQUIRY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_KYC_TYPE
CREATE TABLE CIF.REF_KYC_TYPE (
  KYC_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_KYC_TYPE PRIMARY KEY (KYC_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_KYC_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_KYC_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_KYC_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_KYC_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESTRICTION_REASON
CREATE TABLE CIF.REF_RESTRICTION_REASON (
  REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESTRICTION_REASON PRIMARY KEY (REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESTRICTION_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESTRICTION_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESTRICTION_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESTRICTION_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESTRICTION_TYPE
CREATE TABLE CIF.REF_RESTRICTION_TYPE (
  RESTRICTION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESTRICTION_TYPE PRIMARY KEY (RESTRICTION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESTRICTION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESTRICTION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESTRICTION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESTRICTION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_LEVEL
CREATE TABLE CIF.REF_RISK_LEVEL (
  RISK_LEVEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_LEVEL PRIMARY KEY (RISK_LEVEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_LEVEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_LEVEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_LEVEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_LEVEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_MODEL
CREATE TABLE CIF.REF_RISK_MODEL (
  MODEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  MODEL_VERSION VARCHAR2(30 CHAR) NOT NULL,
  MIN_SCORE NUMBER(12,6) NOT NULL,
  MAX_SCORE NUMBER(12,6) NOT NULL,
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_MODEL PRIMARY KEY (MODEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_MODEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_MODEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_MODEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_MODEL_04 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_RISK_MODEL_05 CHECK (MIN_SCORE <= MAX_SCORE)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_TYPE
CREATE TABLE CIF.REF_RISK_TYPE (
  RISK_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_TYPE PRIMARY KEY (RISK_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_LIST
CREATE TABLE CIF.REF_SCREENING_LIST (
  SOURCE_LIST_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_LIST PRIMARY KEY (SOURCE_LIST_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_LIST_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_LIST_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_LIST_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_LIST_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_PROVIDER
CREATE TABLE CIF.REF_SCREENING_PROVIDER (
  PROVIDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_PROVIDER PRIMARY KEY (PROVIDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_PROVIDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_PROVIDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_PROVIDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_PROVIDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_TYPE
CREATE TABLE CIF.REF_SCREENING_TYPE (
  SCREENING_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_TYPE PRIMARY KEY (SCREENING_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SEVERITY
CREATE TABLE CIF.REF_SEVERITY (
  SEVERITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SEVERITY PRIMARY KEY (SEVERITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SEVERITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SEVERITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SEVERITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SEVERITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_OF_FUNDS
CREATE TABLE CIF.REF_SOURCE_OF_FUNDS (
  SOURCE_OF_FUNDS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_OF_FUNDS PRIMARY KEY (SOURCE_OF_FUNDS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_OF_FUNDS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_OF_FUNDS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_OF_FUNDS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_OF_FUNDS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_OF_WEALTH
CREATE TABLE CIF.REF_SOURCE_OF_WEALTH (
  SOURCE_OF_WEALTH_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_OF_WEALTH PRIMARY KEY (SOURCE_OF_WEALTH_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_OF_WEALTH_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_OF_WEALTH_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_OF_WEALTH_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_OF_WEALTH_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_TAX_STATUS
CREATE TABLE CIF.REF_TAX_STATUS (
  TAX_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_TAX_STATUS PRIMARY KEY (TAX_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_TAX_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_TAX_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_TAX_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_TAX_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_VERIFICATION_METHOD
CREATE TABLE CIF.REF_VERIFICATION_METHOD (
  VERIFICATION_METHOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_VERIFICATION_METHOD PRIMARY KEY (VERIFICATION_METHOD_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_VERIFICATION_METHOD_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_VERIFICATION_METHOD_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_VERIFICATION_METHOD_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_VERIFICATION_METHOD_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_VERIFICATION_STATUS
CREATE TABLE CIF.REF_VERIFICATION_STATUS (
  VERIFICATION_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_VERIFICATION_STATUS PRIMARY KEY (VERIFICATION_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_VERIFICATION_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_VERIFICATION_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_VERIFICATION_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_VERIFICATION_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;


-- FIX21: GOVERNED PERSIAN COLUMN COMMENTS
-- Generated from party-reference-model.json; keep labels synchronized with governed metadata.
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.RESOLUTION_CODE IS 'کد نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.NAME_FA IS 'عنوان فارسی نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.NAME_EN IS 'عنوان انگلیسی نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.DESCRIPTION_FA IS 'توضیحات فارسی نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.SORT_ORDER IS 'ترتیب نمایش نتیجه رسیدگی به هشدار در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.IS_ACTIVE IS 'نشانگر فعال بودن نتیجه رسیدگی به هشدار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.PARENT_CODE IS 'کد والد نتیجه رسیدگی به هشدار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.VALID_FROM IS 'تاریخ شروع اعتبار نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.VALID_TO IS 'تاریخ پایان اعتبار نتیجه رسیدگی به هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_RESOLUTION.RECORD_VERSION IS 'شماره نسخه رکورد نتیجه رسیدگی به هشدار برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.ALERT_TYPE_CODE IS 'کد نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.NAME_FA IS 'عنوان فارسی نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.NAME_EN IS 'عنوان انگلیسی نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع هشدار در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع هشدار؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.PARENT_CODE IS 'کد والد نوع هشدار در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع هشدار';
COMMENT ON COLUMN CIF.REF_ALERT_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع هشدار برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_DECISION.DECISION_CODE IS 'کد تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.NAME_FA IS 'عنوان فارسی تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.NAME_EN IS 'عنوان انگلیسی تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.DESCRIPTION_FA IS 'توضیحات فارسی تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.SORT_ORDER IS 'ترتیب نمایش تصمیم در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_DECISION.IS_ACTIVE IS 'نشانگر فعال بودن تصمیم؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_DECISION.PARENT_CODE IS 'کد والد تصمیم در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_DECISION.VALID_FROM IS 'تاریخ شروع اعتبار تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.VALID_TO IS 'تاریخ پایان اعتبار تصمیم';
COMMENT ON COLUMN CIF.REF_DECISION.RECORD_VERSION IS 'شماره نسخه رکورد تصمیم برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.DUE_DILIGENCE_LEVEL_CODE IS 'کد سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.NAME_FA IS 'عنوان فارسی سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.NAME_EN IS 'عنوان انگلیسی سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.DESCRIPTION_FA IS 'توضیحات فارسی سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.SORT_ORDER IS 'ترتیب نمایش سطح بررسی مشتری در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.IS_ACTIVE IS 'نشانگر فعال بودن سطح بررسی مشتری؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.PARENT_CODE IS 'کد والد سطح بررسی مشتری در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.VALID_FROM IS 'تاریخ شروع اعتبار سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.VALID_TO IS 'تاریخ پایان اعتبار سطح بررسی مشتری';
COMMENT ON COLUMN CIF.REF_DUE_DILIGENCE_LEVEL.RECORD_VERSION IS 'شماره نسخه رکورد سطح بررسی مشتری برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.INQUIRY_RESULT_CODE IS 'کد نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.NAME_FA IS 'عنوان فارسی نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.NAME_EN IS 'عنوان انگلیسی نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.DESCRIPTION_FA IS 'توضیحات فارسی نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.SORT_ORDER IS 'ترتیب نمایش نتیجه استعلام در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.IS_ACTIVE IS 'نشانگر فعال بودن نتیجه استعلام؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.PARENT_CODE IS 'کد والد نتیجه استعلام در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.VALID_FROM IS 'تاریخ شروع اعتبار نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.VALID_TO IS 'تاریخ پایان اعتبار نتیجه استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_RESULT.RECORD_VERSION IS 'شماره نسخه رکورد نتیجه استعلام برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.INQUIRY_TYPE_CODE IS 'کد نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.NAME_FA IS 'عنوان فارسی نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.NAME_EN IS 'عنوان انگلیسی نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع استعلام در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع استعلام؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.PARENT_CODE IS 'کد والد نوع استعلام در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع استعلام';
COMMENT ON COLUMN CIF.REF_INQUIRY_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع استعلام برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.KYC_TYPE_CODE IS 'کد نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.NAME_FA IS 'عنوان فارسی نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.NAME_EN IS 'عنوان انگلیسی نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع KYC در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع KYC؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.PARENT_CODE IS 'کد والد نوع KYC در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع KYC';
COMMENT ON COLUMN CIF.REF_KYC_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع KYC برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.REASON_CODE IS 'کد دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.NAME_FA IS 'عنوان فارسی دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.NAME_EN IS 'عنوان انگلیسی دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.DESCRIPTION_FA IS 'توضیحات فارسی دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.SORT_ORDER IS 'ترتیب نمایش دلیل محدودیت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.IS_ACTIVE IS 'نشانگر فعال بودن دلیل محدودیت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.PARENT_CODE IS 'کد والد دلیل محدودیت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.VALID_FROM IS 'تاریخ شروع اعتبار دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.VALID_TO IS 'تاریخ پایان اعتبار دلیل محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_REASON.RECORD_VERSION IS 'شماره نسخه رکورد دلیل محدودیت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.RESTRICTION_TYPE_CODE IS 'کد نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.NAME_FA IS 'عنوان فارسی نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.NAME_EN IS 'عنوان انگلیسی نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع محدودیت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع محدودیت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.PARENT_CODE IS 'کد والد نوع محدودیت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع محدودیت';
COMMENT ON COLUMN CIF.REF_RESTRICTION_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع محدودیت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.RISK_LEVEL_CODE IS 'کد سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.NAME_FA IS 'عنوان فارسی سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.NAME_EN IS 'عنوان انگلیسی سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.DESCRIPTION_FA IS 'توضیحات فارسی سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.SORT_ORDER IS 'ترتیب نمایش سطح ریسک در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.IS_ACTIVE IS 'نشانگر فعال بودن سطح ریسک؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.PARENT_CODE IS 'کد والد سطح ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.VALID_FROM IS 'تاریخ شروع اعتبار سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.VALID_TO IS 'تاریخ پایان اعتبار سطح ریسک';
COMMENT ON COLUMN CIF.REF_RISK_LEVEL.RECORD_VERSION IS 'شماره نسخه رکورد سطح ریسک برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MODEL_CODE IS 'کد مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.NAME_FA IS 'عنوان فارسی مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.NAME_EN IS 'عنوان انگلیسی مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.DESCRIPTION_FA IS 'توضیحات فارسی مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MODEL_VERSION IS 'نسخه فعال مدل ریسک که هنگام ثبت ارزیابی ریسک توسط سامانه استفاده می‌شود';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MIN_SCORE IS 'حداقل امتیاز مجاز برای ارزیابی با این مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.MAX_SCORE IS 'حداکثر امتیاز مجاز برای ارزیابی با این مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.SORT_ORDER IS 'ترتیب نمایش مدل ریسک در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.IS_ACTIVE IS 'نشانگر فعال بودن مدل ریسک؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.PARENT_CODE IS 'کد والد مدل ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.VALID_FROM IS 'تاریخ شروع اعتبار مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.VALID_TO IS 'تاریخ پایان اعتبار مدل ریسک';
COMMENT ON COLUMN CIF.REF_RISK_MODEL.RECORD_VERSION IS 'شماره نسخه رکورد مدل ریسک برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.RISK_TYPE_CODE IS 'کد نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.NAME_FA IS 'عنوان فارسی نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.NAME_EN IS 'عنوان انگلیسی نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع ریسک در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع ریسک؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.PARENT_CODE IS 'کد والد نوع ریسک در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع ریسک';
COMMENT ON COLUMN CIF.REF_RISK_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع ریسک برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.SOURCE_LIST_CODE IS 'کد فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.NAME_FA IS 'عنوان فارسی فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.NAME_EN IS 'عنوان انگلیسی فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.DESCRIPTION_FA IS 'توضیحات فارسی فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.SORT_ORDER IS 'ترتیب نمایش فهرست پایش و تحریم در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.IS_ACTIVE IS 'نشانگر فعال بودن فهرست پایش و تحریم؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.PARENT_CODE IS 'کد والد فهرست پایش و تحریم در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.VALID_FROM IS 'تاریخ شروع اعتبار فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.VALID_TO IS 'تاریخ پایان اعتبار فهرست پایش و تحریم';
COMMENT ON COLUMN CIF.REF_SCREENING_LIST.RECORD_VERSION IS 'شماره نسخه رکورد فهرست پایش و تحریم برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.PROVIDER_CODE IS 'کد ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.NAME_FA IS 'عنوان فارسی ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.NAME_EN IS 'عنوان انگلیسی ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.DESCRIPTION_FA IS 'توضیحات فارسی ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.SORT_ORDER IS 'ترتیب نمایش ارائه‌دهنده سرویس پایش در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.IS_ACTIVE IS 'نشانگر فعال بودن ارائه‌دهنده سرویس پایش؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.PARENT_CODE IS 'کد والد ارائه‌دهنده سرویس پایش در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.VALID_FROM IS 'تاریخ شروع اعتبار ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.VALID_TO IS 'تاریخ پایان اعتبار ارائه‌دهنده سرویس پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_PROVIDER.RECORD_VERSION IS 'شماره نسخه رکورد ارائه‌دهنده سرویس پایش برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.SCREENING_TYPE_CODE IS 'کد نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.NAME_FA IS 'عنوان فارسی نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.NAME_EN IS 'عنوان انگلیسی نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.DESCRIPTION_FA IS 'توضیحات فارسی نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.SORT_ORDER IS 'ترتیب نمایش نوع پایش در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.IS_ACTIVE IS 'نشانگر فعال بودن نوع پایش؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.PARENT_CODE IS 'کد والد نوع پایش در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.VALID_FROM IS 'تاریخ شروع اعتبار نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.VALID_TO IS 'تاریخ پایان اعتبار نوع پایش';
COMMENT ON COLUMN CIF.REF_SCREENING_TYPE.RECORD_VERSION IS 'شماره نسخه رکورد نوع پایش برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SEVERITY.SEVERITY_CODE IS 'کد شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.NAME_FA IS 'عنوان فارسی شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.NAME_EN IS 'عنوان انگلیسی شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.DESCRIPTION_FA IS 'توضیحات فارسی شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.SORT_ORDER IS 'ترتیب نمایش شدت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SEVERITY.IS_ACTIVE IS 'نشانگر فعال بودن شدت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SEVERITY.PARENT_CODE IS 'کد والد شدت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SEVERITY.VALID_FROM IS 'تاریخ شروع اعتبار شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.VALID_TO IS 'تاریخ پایان اعتبار شدت';
COMMENT ON COLUMN CIF.REF_SEVERITY.RECORD_VERSION IS 'شماره نسخه رکورد شدت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.SOURCE_OF_FUNDS_CODE IS 'کد منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.NAME_FA IS 'عنوان فارسی منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.NAME_EN IS 'عنوان انگلیسی منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.DESCRIPTION_FA IS 'توضیحات فارسی منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.SORT_ORDER IS 'ترتیب نمایش منبع وجوه در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.IS_ACTIVE IS 'نشانگر فعال بودن منبع وجوه؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.PARENT_CODE IS 'کد والد منبع وجوه در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.VALID_FROM IS 'تاریخ شروع اعتبار منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.VALID_TO IS 'تاریخ پایان اعتبار منبع وجوه';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_FUNDS.RECORD_VERSION IS 'شماره نسخه رکورد منبع وجوه برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.SOURCE_OF_WEALTH_CODE IS 'کد منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.NAME_FA IS 'عنوان فارسی منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.NAME_EN IS 'عنوان انگلیسی منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.DESCRIPTION_FA IS 'توضیحات فارسی منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.SORT_ORDER IS 'ترتیب نمایش منبع ثروت در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.IS_ACTIVE IS 'نشانگر فعال بودن منبع ثروت؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.PARENT_CODE IS 'کد والد منبع ثروت در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.VALID_FROM IS 'تاریخ شروع اعتبار منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.VALID_TO IS 'تاریخ پایان اعتبار منبع ثروت';
COMMENT ON COLUMN CIF.REF_SOURCE_OF_WEALTH.RECORD_VERSION IS 'شماره نسخه رکورد منبع ثروت برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.TAX_STATUS_CODE IS 'کد وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.NAME_FA IS 'عنوان فارسی وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت مالیاتی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت مالیاتی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.PARENT_CODE IS 'کد والد وضعیت مالیاتی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت مالیاتی';
COMMENT ON COLUMN CIF.REF_TAX_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت مالیاتی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.VERIFICATION_METHOD_CODE IS 'کد روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.NAME_FA IS 'عنوان فارسی روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.NAME_EN IS 'عنوان انگلیسی روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.DESCRIPTION_FA IS 'توضیحات فارسی روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.SORT_ORDER IS 'ترتیب نمایش روش اعتبارسنجی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.IS_ACTIVE IS 'نشانگر فعال بودن روش اعتبارسنجی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.PARENT_CODE IS 'کد والد روش اعتبارسنجی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.VALID_FROM IS 'تاریخ شروع اعتبار روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.VALID_TO IS 'تاریخ پایان اعتبار روش اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_METHOD.RECORD_VERSION IS 'شماره نسخه رکورد روش اعتبارسنجی برای کنترل هم‌زمانی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.VERIFICATION_STATUS_CODE IS 'کد وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.NAME_FA IS 'عنوان فارسی وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.NAME_EN IS 'عنوان انگلیسی وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.DESCRIPTION_FA IS 'توضیحات فارسی وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.SORT_ORDER IS 'ترتیب نمایش وضعیت اعتبارسنجی در فهرست‌های مرجع';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.IS_ACTIVE IS 'نشانگر فعال بودن وضعیت اعتبارسنجی؛ 1 فعال و 0 غیرفعال';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.PARENT_CODE IS 'کد والد وضعیت اعتبارسنجی در ساختار سلسله‌مراتبی، در صورت کاربرد';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.VALID_FROM IS 'تاریخ شروع اعتبار وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.VALID_TO IS 'تاریخ پایان اعتبار وضعیت اعتبارسنجی';
COMMENT ON COLUMN CIF.REF_VERIFICATION_STATUS.RECORD_VERSION IS 'شماره نسخه رکورد وضعیت اعتبارسنجی برای کنترل هم‌زمانی';
