-- Generated from Party_Customer_Reference_Data_Interactive_Forms_FA.html
-- Phase 2: Compliance, Risk and KYC reference data
-- Target schema: CIF
-- Tablespace: TS_CIF; PK indexes: ITS_CIF

PROMPT Creating CIF.REF_ALERT_RESOLUTION
CREATE TABLE CIF.REF_ALERT_RESOLUTION (
  RESOLUTION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ALERT_RESOLUTION PRIMARY KEY (RESOLUTION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ALERT_RESOLUTION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ALERT_RESOLUTION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ALERT_RESOLUTION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ALERT_RESOLUTION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_ALERT_TYPE
CREATE TABLE CIF.REF_ALERT_TYPE (
  ALERT_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ALERT_TYPE PRIMARY KEY (ALERT_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_ALERT_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_ALERT_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_ALERT_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_ALERT_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DECISION
CREATE TABLE CIF.REF_DECISION (
  DECISION_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DECISION PRIMARY KEY (DECISION_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DECISION_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DECISION_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DECISION_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DECISION_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_DUE_DILIGENCE_LEVEL
CREATE TABLE CIF.REF_DUE_DILIGENCE_LEVEL (
  DUE_DILIGENCE_LEVEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_DUE_DILIGENCE_LEVEL PRIMARY KEY (DUE_DILIGENCE_LEVEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_DUE_DILIGENCE_LEVEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INQUIRY_RESULT
CREATE TABLE CIF.REF_INQUIRY_RESULT (
  INQUIRY_RESULT_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INQUIRY_RESULT PRIMARY KEY (INQUIRY_RESULT_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INQUIRY_RESULT_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INQUIRY_RESULT_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INQUIRY_RESULT_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INQUIRY_RESULT_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_INQUIRY_TYPE
CREATE TABLE CIF.REF_INQUIRY_TYPE (
  INQUIRY_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INQUIRY_TYPE PRIMARY KEY (INQUIRY_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_INQUIRY_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INQUIRY_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_INQUIRY_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_INQUIRY_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_KYC_TYPE
CREATE TABLE CIF.REF_KYC_TYPE (
  KYC_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_KYC_TYPE PRIMARY KEY (KYC_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_KYC_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_KYC_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_KYC_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_KYC_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESTRICTION_REASON
CREATE TABLE CIF.REF_RESTRICTION_REASON (
  REASON_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESTRICTION_REASON PRIMARY KEY (REASON_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESTRICTION_REASON_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESTRICTION_REASON_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESTRICTION_REASON_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESTRICTION_REASON_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RESTRICTION_TYPE
CREATE TABLE CIF.REF_RESTRICTION_TYPE (
  RESTRICTION_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RESTRICTION_TYPE PRIMARY KEY (RESTRICTION_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RESTRICTION_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RESTRICTION_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RESTRICTION_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RESTRICTION_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_LEVEL
CREATE TABLE CIF.REF_RISK_LEVEL (
  RISK_LEVEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_LEVEL PRIMARY KEY (RISK_LEVEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_LEVEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_LEVEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_LEVEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_LEVEL_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_MODEL
CREATE TABLE CIF.REF_RISK_MODEL (
  MODEL_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  MODEL_VERSION VARCHAR2(30 CHAR) NOT NULL,
  MIN_SCORE NUMBER(12,6) NOT NULL,
  MAX_SCORE NUMBER(12,6) NOT NULL,
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_MODEL PRIMARY KEY (MODEL_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_MODEL_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_MODEL_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_MODEL_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_MODEL_04 CHECK (RECORD_VERSION >= 1),
  CONSTRAINT CK_RISK_MODEL_05 CHECK (MIN_SCORE <= MAX_SCORE)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_RISK_TYPE
CREATE TABLE CIF.REF_RISK_TYPE (
  RISK_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RISK_TYPE PRIMARY KEY (RISK_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_RISK_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_RISK_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_RISK_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_RISK_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_LIST
CREATE TABLE CIF.REF_SCREENING_LIST (
  SOURCE_LIST_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_LIST PRIMARY KEY (SOURCE_LIST_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_LIST_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_LIST_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_LIST_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_LIST_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_PROVIDER
CREATE TABLE CIF.REF_SCREENING_PROVIDER (
  PROVIDER_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_PROVIDER PRIMARY KEY (PROVIDER_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_PROVIDER_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_PROVIDER_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_PROVIDER_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_PROVIDER_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SCREENING_TYPE
CREATE TABLE CIF.REF_SCREENING_TYPE (
  SCREENING_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SCREENING_TYPE PRIMARY KEY (SCREENING_TYPE_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SCREENING_TYPE_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SCREENING_TYPE_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SCREENING_TYPE_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SCREENING_TYPE_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SEVERITY
CREATE TABLE CIF.REF_SEVERITY (
  SEVERITY_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SEVERITY PRIMARY KEY (SEVERITY_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SEVERITY_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SEVERITY_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SEVERITY_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SEVERITY_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_OF_FUNDS
CREATE TABLE CIF.REF_SOURCE_OF_FUNDS (
  SOURCE_OF_FUNDS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_OF_FUNDS PRIMARY KEY (SOURCE_OF_FUNDS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_OF_FUNDS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_OF_FUNDS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_OF_FUNDS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_OF_FUNDS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_SOURCE_OF_WEALTH
CREATE TABLE CIF.REF_SOURCE_OF_WEALTH (
  SOURCE_OF_WEALTH_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SOURCE_OF_WEALTH PRIMARY KEY (SOURCE_OF_WEALTH_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_SOURCE_OF_WEALTH_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_SOURCE_OF_WEALTH_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_SOURCE_OF_WEALTH_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_SOURCE_OF_WEALTH_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_TAX_STATUS
CREATE TABLE CIF.REF_TAX_STATUS (
  TAX_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_TAX_STATUS PRIMARY KEY (TAX_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_TAX_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_TAX_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_TAX_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_TAX_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_VERIFICATION_METHOD
CREATE TABLE CIF.REF_VERIFICATION_METHOD (
  VERIFICATION_METHOD_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_VERIFICATION_METHOD PRIMARY KEY (VERIFICATION_METHOD_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_VERIFICATION_METHOD_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_VERIFICATION_METHOD_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_VERIFICATION_METHOD_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_VERIFICATION_METHOD_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;

PROMPT Creating CIF.REF_VERIFICATION_STATUS
CREATE TABLE CIF.REF_VERIFICATION_STATUS (
  VERIFICATION_STATUS_CODE VARCHAR2(50 CHAR) NOT NULL,
  NAME_FA VARCHAR2(200 CHAR) NOT NULL,
  NAME_EN VARCHAR2(200 CHAR),
  DESCRIPTION_FA VARCHAR2(1000 CHAR),
  SORT_ORDER NUMBER(10) DEFAULT 10 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PARENT_CODE VARCHAR2(50 CHAR),
  VALID_FROM DATE,
  VALID_TO DATE,
  RECORD_VERSION NUMBER(10) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_VERIFICATION_STATUS PRIMARY KEY (VERIFICATION_STATUS_CODE) USING INDEX TABLESPACE ITS_CIF,
  CONSTRAINT CK_VERIFICATION_STATUS_01 CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_VERIFICATION_STATUS_02 CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
  CONSTRAINT CK_VERIFICATION_STATUS_03 CHECK (SORT_ORDER >= 0),
  CONSTRAINT CK_VERIFICATION_STATUS_04 CHECK (RECORD_VERSION >= 1)
) TABLESPACE TS_CIF;
