SET SERVEROUTPUT ON
PROMPT Verifying Compliance/Risk reference tables

SELECT COUNT(*) AS ACTIVE_REFERENCE_TABLES FROM ALL_TABLES WHERE OWNER = 'CIF' AND TABLE_NAME IN (
  'REF_ALERT_RESOLUTION',
  'REF_ALERT_TYPE',
  'REF_DECISION',
  'REF_DUE_DILIGENCE_LEVEL',
  'REF_INQUIRY_RESULT',
  'REF_INQUIRY_TYPE',
  'REF_KYC_TYPE',
  'REF_RESTRICTION_REASON',
  'REF_RESTRICTION_TYPE',
  'REF_RISK_LEVEL',
  'REF_RISK_MODEL',
  'REF_RISK_TYPE',
  'REF_SCREENING_LIST',
  'REF_SCREENING_PROVIDER',
  'REF_SCREENING_TYPE',
  'REF_SEVERITY',
  'REF_SOURCE_OF_FUNDS',
  'REF_SOURCE_OF_WEALTH',
  'REF_TAX_STATUS',
  'REF_VERIFICATION_METHOD',
  'REF_VERIFICATION_STATUS'
);

SELECT 'REF_ALERT_RESOLUTION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_ALERT_RESOLUTION;
SELECT 'REF_ALERT_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_ALERT_TYPE;
SELECT 'REF_DECISION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 9 AS EXPECTED_MIN FROM CIF.REF_DECISION;
SELECT 'REF_DUE_DILIGENCE_LEVEL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 3 AS EXPECTED_MIN FROM CIF.REF_DUE_DILIGENCE_LEVEL;
SELECT 'REF_INQUIRY_RESULT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_INQUIRY_RESULT;
SELECT 'REF_INQUIRY_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_INQUIRY_TYPE;
SELECT 'REF_KYC_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 3 AS EXPECTED_MIN FROM CIF.REF_KYC_TYPE;
SELECT 'REF_RESTRICTION_REASON' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_RESTRICTION_REASON;
SELECT 'REF_RESTRICTION_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_RESTRICTION_TYPE;
SELECT 'REF_RISK_LEVEL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_RISK_LEVEL;
SELECT 'REF_RISK_MODEL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 3 AS EXPECTED_MIN FROM CIF.REF_RISK_MODEL;
SELECT 'REF_RISK_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_RISK_TYPE;
SELECT 'REF_SCREENING_LIST' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_SCREENING_LIST;
SELECT 'REF_SCREENING_PROVIDER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_SCREENING_PROVIDER;
SELECT 'REF_SCREENING_TYPE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_SCREENING_TYPE;
SELECT 'REF_SEVERITY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_SEVERITY;
SELECT 'REF_SOURCE_OF_FUNDS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 5 AS EXPECTED_MIN FROM CIF.REF_SOURCE_OF_FUNDS;
SELECT 'REF_SOURCE_OF_WEALTH' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_SOURCE_OF_WEALTH;
SELECT 'REF_TAX_STATUS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 3 AS EXPECTED_MIN FROM CIF.REF_TAX_STATUS;
SELECT 'REF_VERIFICATION_METHOD' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 4 AS EXPECTED_MIN FROM CIF.REF_VERIFICATION_METHOD;
SELECT 'REF_VERIFICATION_STATUS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 5 AS EXPECTED_MIN FROM CIF.REF_VERIFICATION_STATUS;

PROMPT Verifying operationally aligned codes
SELECT * FROM CIF.REF_VERIFICATION_STATUS WHERE VERIFICATION_STATUS_CODE='UNVERIFIED';
SELECT * FROM CIF.REF_KYC_TYPE WHERE KYC_TYPE_CODE='ONBOARDING';
SELECT * FROM CIF.REF_DUE_DILIGENCE_LEVEL WHERE DUE_DILIGENCE_LEVEL_CODE='CDD';
SELECT * FROM CIF.REF_RISK_LEVEL WHERE RISK_LEVEL_CODE='LOW';
SELECT * FROM CIF.REF_SCREENING_TYPE WHERE SCREENING_TYPE_CODE='SANCTIONS';
SELECT * FROM CIF.REF_SCREENING_PROVIDER WHERE PROVIDER_CODE='INTERNAL';
SELECT * FROM CIF.REF_DECISION WHERE DECISION_CODE='CLEAR';
