-- ============================================================================
-- Core Banking Prototype 0.11.0 / PDL R10U
-- Product Eligibility Rule - business UX and multi-value criteria model
--
-- Runtime source of truth for multi-valued eligibility dimensions:
--   PDL.PRODUCT_ELIGIBILITY_CRITERION
--
-- Semantics:
--   * Multiple rows of the same CRITERION_TYPE_CODE are OR-ed (IN semantics).
--   * Different criterion types are AND-ed.
--   * Absence of rows for an IN criterion means "all values / no restriction".
--   * Threshold criteria use OPERATOR_CODE=MIN/MAX with VALUE_NUMBER and UNIT_CODE.
--
-- Existing scalar columns on PRODUCT_ELIGIBILITY_RULE are intentionally retained
-- for backwards compatibility during the prototype transition; they are no longer
-- authoritative for multi-valued dimensions once criterion rows exist.
-- ============================================================================

SET DEFINE OFF;

PROMPT [PDL R10U] Marking eligibility rule criteria model version ...
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PDL.PRODUCT_ELIGIBILITY_RULE ADD (CRITERIA_MODEL_VERSION NUMBER(2) DEFAULT 2 NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_RULE.CRITERIA_MODEL_VERSION IS 'نسخه مدل معیارهای اهلیت؛ مقدار 2 یعنی معیارهای چندمقداری در PRODUCT_ELIGIBILITY_CRITERION منبع اصلی هستند.';

PROMPT [PDL R10U] Creating PRODUCT_ELIGIBILITY_CRITERION ...
BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE PDL.PRODUCT_ELIGIBILITY_CRITERION (
      ELIGIBILITY_CRITERION_ID NUMBER(19)        NOT NULL,
      ELIGIBILITY_RULE_ID      NUMBER(19)        NOT NULL,
      CRITERION_TYPE_CODE      VARCHAR2(50 CHAR) NOT NULL,
      OPERATOR_CODE            VARCHAR2(20 CHAR) DEFAULT 'IN' NOT NULL,
      CRITERION_VALUE_CODE     VARCHAR2(100 CHAR),
      CRITERION_VALUE_NUMBER   NUMBER(20,4),
      VALUE_UNIT_CODE          VARCHAR2(20 CHAR),
      DISPLAY_ORDER            NUMBER(5) DEFAULT 100 NOT NULL,
      IS_ACTIVE                NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY               VARCHAR2(100 CHAR) NOT NULL,
      UPDATED_AT               TIMESTAMP(6),
      UPDATED_BY               VARCHAR2(100 CHAR),
      RECORD_VERSION           NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_PDL_ELIG_CRIT PRIMARY KEY (ELIGIBILITY_CRITERION_ID),
      CONSTRAINT FK_PDL_ELIG_CRIT_RULE FOREIGN KEY (ELIGIBILITY_RULE_ID)
        REFERENCES PDL.PRODUCT_ELIGIBILITY_RULE (ELIGIBILITY_RULE_ID),
      CONSTRAINT CK_PDL_ELIG_CRIT_TYPE CHECK (CRITERION_TYPE_CODE IN (
        'CUSTOMER_TYPE','CUSTOMER_SEGMENT','CUSTOMER_STATUS','GENDER',
        'RESIDENCY_STATUS','NATIONALITY_SCOPE','CUSTOMER_TENURE','ACCOUNT_TENURE'
      )),
      CONSTRAINT CK_PDL_ELIG_CRIT_OP CHECK (OPERATOR_CODE IN ('IN','EQ','MIN','MAX')),
      CONSTRAINT CK_PDL_ELIG_CRIT_UNIT CHECK (VALUE_UNIT_CODE IS NULL OR VALUE_UNIT_CODE IN ('DAY','MONTH','YEAR')),
      CONSTRAINT CK_PDL_ELIG_CRIT_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
      CONSTRAINT CK_PDL_ELIG_CRIT_ORDER CHECK (DISPLAY_ORDER > 0),
      CONSTRAINT CK_PDL_ELIG_CRIT_RECVER CHECK (RECORD_VERSION > 0),
      CONSTRAINT CK_PDL_ELIG_CRIT_VALUE CHECK (
        (OPERATOR_CODE IN ('IN','EQ') AND CRITERION_VALUE_CODE IS NOT NULL AND CRITERION_VALUE_NUMBER IS NULL)
        OR
        (OPERATOR_CODE IN ('MIN','MAX') AND CRITERION_VALUE_CODE IS NULL AND CRITERION_VALUE_NUMBER IS NOT NULL)
      ),
      CONSTRAINT CK_PDL_ELIG_CRIT_TENURE CHECK (
        (CRITERION_TYPE_CODE IN ('CUSTOMER_TENURE','ACCOUNT_TENURE') AND OPERATOR_CODE='MIN' AND VALUE_UNIT_CODE IS NOT NULL AND CRITERION_VALUE_NUMBER >= 0)
        OR
        (CRITERION_TYPE_CODE NOT IN ('CUSTOMER_TENURE','ACCOUNT_TENURE') AND VALUE_UNIT_CODE IS NULL)
      )
    )~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PDL.UK_PDL_ELIG_CRIT_CODE ON PDL.PRODUCT_ELIGIBILITY_CRITERION '
                 || '(ELIGIBILITY_RULE_ID, CRITERION_TYPE_CODE, OPERATOR_CODE, CRITERION_VALUE_CODE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX PDL.IX_PDL_ELIG_CRIT_RULE ON PDL.PRODUCT_ELIGIBILITY_CRITERION (ELIGIBILITY_RULE_ID, CRITERION_TYPE_CODE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE PDL.PRODUCT_ELIGIBILITY_CRITERION IS 'معیارهای چندمقداری و آستانه‌ای قاعده مشترک اهلیت محصول. مقادیر متعدد یک نوع معیار با OR و انواع مختلف معیار با AND ارزیابی می‌شوند.';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.ELIGIBILITY_CRITERION_ID IS 'شناسه فنی معیار اهلیت';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.ELIGIBILITY_RULE_ID IS 'شناسه قاعده مشترک اهلیت والد';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.CRITERION_TYPE_CODE IS 'نوع معیار اهلیت';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.OPERATOR_CODE IS 'عملگر معیار: IN/EQ/MIN/MAX';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.CRITERION_VALUE_CODE IS 'کد مقدار مرجع برای معیارهای دامنه‌ای';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.CRITERION_VALUE_NUMBER IS 'مقدار عددی برای معیارهای آستانه‌ای';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.VALUE_UNIT_CODE IS 'واحد معیار عددی؛ برای سابقه: روز/ماه/سال';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.DISPLAY_ORDER IS 'ترتیب نمایش معیار';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.IS_ACTIVE IS 'فعال بودن معیار';
COMMENT ON COLUMN PDL.PRODUCT_ELIGIBILITY_CRITERION.RECORD_VERSION IS 'نسخه رکورد برای کنترل همزمانی';

-- --------------------------------------------------------------------------
-- Safe migration of existing scalar dimension values.
-- ALL / unrestricted values are deliberately not persisted as criterion rows;
-- absence of child rows means "all values" in the new model.
-- --------------------------------------------------------------------------
DECLARE
  PROCEDURE migrate_code(p_column VARCHAR2, p_type VARCHAR2, p_order NUMBER) IS
    l_count NUMBER;
    l_sql   VARCHAR2(32767);
  BEGIN
    SELECT COUNT(*) INTO l_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='PDL' AND TABLE_NAME='PRODUCT_ELIGIBILITY_RULE' AND COLUMN_NAME=UPPER(p_column);
    IF l_count = 0 THEN RETURN; END IF;

    l_sql := 'INSERT INTO PDL.PRODUCT_ELIGIBILITY_CRITERION '
          || '(ELIGIBILITY_CRITERION_ID,ELIGIBILITY_RULE_ID,CRITERION_TYPE_CODE,OPERATOR_CODE,CRITERION_VALUE_CODE,DISPLAY_ORDER,IS_ACTIVE,CREATED_BY) '
          || 'SELECT NVL((SELECT MAX(ELIGIBILITY_CRITERION_ID) FROM PDL.PRODUCT_ELIGIBILITY_CRITERION),0) + ROW_NUMBER() OVER (ORDER BY ELIGIBILITY_RULE_ID), '
          || 'ELIGIBILITY_RULE_ID, :type, ''IN'', TRIM(' || p_column || '), :ord, 1, ''R10U_MIGRATION'' '
          || 'FROM PDL.PRODUCT_ELIGIBILITY_RULE r '
          || 'WHERE ' || p_column || ' IS NOT NULL AND TRIM(' || p_column || ') IS NOT NULL '
          || 'AND UPPER(TRIM(' || p_column || ')) NOT IN (''ALL'',''ANY'',''NONE'',''3'') '
          || 'AND NOT EXISTS (SELECT 1 FROM PDL.PRODUCT_ELIGIBILITY_CRITERION c '
          || 'WHERE c.ELIGIBILITY_RULE_ID=r.ELIGIBILITY_RULE_ID AND c.CRITERION_TYPE_CODE=:type2 '
          || 'AND c.OPERATOR_CODE=''IN'' AND c.CRITERION_VALUE_CODE=TRIM(r.' || p_column || '))';
    EXECUTE IMMEDIATE l_sql USING p_type, p_order, p_type;
  END;
BEGIN
  migrate_code('CUSTOMER_TYPE_CODE',      'CUSTOMER_TYPE',      10);
  migrate_code('CUSTOMER_SEGMENT_CODE',   'CUSTOMER_SEGMENT',   20);
  migrate_code('CUSTOMER_STATUS_CODE',    'CUSTOMER_STATUS',    30);
  migrate_code('GENDER_CODE',             'GENDER',             40);
  migrate_code('RESIDENCY_STATUS_CODE',   'RESIDENCY_STATUS',   50);
  migrate_code('NATIONALITY_SCOPE_CODE',  'NATIONALITY_SCOPE',  60);
END;
/

PROMPT [PDL R10U] Validation ...
SELECT TABLE_NAME
  FROM ALL_TABLES
 WHERE OWNER='PDL'
   AND TABLE_NAME='PRODUCT_ELIGIBILITY_CRITERION';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
  FROM ALL_CONSTRAINTS
 WHERE OWNER='PDL'
   AND TABLE_NAME='PRODUCT_ELIGIBILITY_CRITERION'
 ORDER BY CONSTRAINT_NAME;

COMMIT;
PROMPT [PDL R10U] Done.
