-- ============================================================================
-- Core Banking Prototype 0.3.88 / FIX96
-- PDL - Unified Product Builder baseline extension
-- Source: Unified_Product_Builder_Deposit_Loan.html (2026-09-10)
-- Adds:
--   1) DEPOSIT_PROFIT_PAYMENT_RULE
--   2) CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE
--   3) CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE
-- Preconditions: PDL.PRODUCT_VERSION exists.
-- Re-runnable: CREATE TABLE blocks ignore ORA-00955 only.
-- ============================================================================

SET DEFINE OFF;

PROMPT [PDL FIX96] Creating DEPOSIT_PROFIT_PAYMENT_RULE ...
BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE PDL.DEPOSIT_PROFIT_PAYMENT_RULE (
      PROFIT_PAYMENT_RULE_ID     NUMBER(19)       NOT NULL,
      PRODUCT_VERSION_ID         NUMBER(19)       NOT NULL,
      PAYMENT_FREQUENCY_CODE     VARCHAR2(30 CHAR) NOT NULL,
      PAYMENT_DAY_RULE_CODE      VARCHAR2(30 CHAR) NOT NULL,
      PAYMENT_DAY_NO             NUMBER(2),
      FIRST_PAYMENT_RULE_CODE    VARCHAR2(30 CHAR) NOT NULL,
      HOLIDAY_ADJUSTMENT_CODE    VARCHAR2(30 CHAR) NOT NULL,
      PAYMENT_DESTINATION_CODE   VARCHAR2(30 CHAR) NOT NULL,
      CAPITALIZATION_ALLOWED     NUMBER(1) DEFAULT 0 NOT NULL,
      CAPITALIZATION_DEFAULT     NUMBER(1) DEFAULT 0 NOT NULL,
      VALID_FROM                 DATE,
      VALID_TO                   DATE,
      IS_ACTIVE                  NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_AT                 TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY                 VARCHAR2(100 CHAR) NOT NULL,
      UPDATED_AT                 TIMESTAMP(6),
      UPDATED_BY                 VARCHAR2(100 CHAR),
      RECORD_VERSION             NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_PDL_DEP_PROFIT_PAY PRIMARY KEY (PROFIT_PAYMENT_RULE_ID),
      CONSTRAINT UK_PDL_DEP_PROFIT_PAY_VER UNIQUE (PRODUCT_VERSION_ID),
      CONSTRAINT FK_PDL_DEP_PROFIT_PAY_VER FOREIGN KEY (PRODUCT_VERSION_ID)
        REFERENCES PDL.PRODUCT_VERSION (PRODUCT_VERSION_ID),
      CONSTRAINT CK_PDL_DPP_FREQ CHECK (PAYMENT_FREQUENCY_CODE IN ('MONTHLY','QUARTERLY','SEMI_ANNUAL','ANNUAL','MATURITY')),
      CONSTRAINT CK_PDL_DPP_DAY_RULE CHECK (PAYMENT_DAY_RULE_CODE IN ('OPENING_ANNIVERSARY','FIXED_DAY_OF_MONTH','LAST_DAY_OF_MONTH','MATURITY_DATE')),
      CONSTRAINT CK_PDL_DPP_FIRST_RULE CHECK (FIRST_PAYMENT_RULE_CODE IN ('PRORATE_FROM_OPENING','FULL_NEXT_CYCLE','MATURITY_ONLY')),
      CONSTRAINT CK_PDL_DPP_HOLIDAY CHECK (HOLIDAY_ADJUSTMENT_CODE IN ('NEXT_BUSINESS_DAY','PREVIOUS_BUSINESS_DAY','NO_ADJUSTMENT')),
      CONSTRAINT CK_PDL_DPP_DEST CHECK (PAYMENT_DESTINATION_CODE IN ('SAME_DEPOSIT','LINKED_ACCOUNT','CUSTOMER_SELECTED_ACCOUNT')),
      CONSTRAINT CK_PDL_DPP_CAP_ALLOWED CHECK (CAPITALIZATION_ALLOWED IN (0,1)),
      CONSTRAINT CK_PDL_DPP_CAP_DEFAULT CHECK (CAPITALIZATION_DEFAULT IN (0,1)),
      CONSTRAINT CK_PDL_DPP_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
      CONSTRAINT CK_PDL_DPP_DAY_NO CHECK (PAYMENT_DAY_NO IS NULL OR PAYMENT_DAY_NO BETWEEN 1 AND 31),
      CONSTRAINT CK_PDL_DPP_DAY_COND CHECK (
        (PAYMENT_DAY_RULE_CODE = 'FIXED_DAY_OF_MONTH' AND PAYMENT_DAY_NO IS NOT NULL)
        OR (PAYMENT_DAY_RULE_CODE <> 'FIXED_DAY_OF_MONTH' AND PAYMENT_DAY_NO IS NULL)
      ),
      CONSTRAINT CK_PDL_DPP_MATURITY CHECK (PAYMENT_FREQUENCY_CODE <> 'MATURITY' OR PAYMENT_DAY_RULE_CODE = 'MATURITY_DATE'),
      CONSTRAINT CK_PDL_DPP_CAP_DEP CHECK (CAPITALIZATION_DEFAULT = 0 OR CAPITALIZATION_ALLOWED = 1),
      CONSTRAINT CK_PDL_DPP_VALID_DATES CHECK (VALID_TO IS NULL OR VALID_FROM IS NULL OR VALID_TO >= VALID_FROM),
      CONSTRAINT CK_PDL_DPP_REC_VER CHECK (RECORD_VERSION > 0)
    )~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT [PDL FIX96] Creating CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE ...
BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE (
      CORRESPONDENT_PRODUCT_PROFILE_ID NUMBER(19) NOT NULL,
      PRODUCT_VERSION_ID               NUMBER(19) NOT NULL,
      ACCOUNT_TYPE_CODE                VARCHAR2(10 CHAR) NOT NULL,
      SETTLEMENT_CURRENCY_CODE          VARCHAR2(3 CHAR) NOT NULL,
      SETTLEMENT_SYSTEM_CODE            VARCHAR2(30 CHAR),
      RECONCILIATION_METHOD_CODE        VARCHAR2(30 CHAR) NOT NULL,
      STATEMENT_FORMAT_CODE             VARCHAR2(30 CHAR),
      OVERDRAFT_ALLOWED                 NUMBER(1) DEFAULT 0 NOT NULL,
      INTRADAY_LIMIT                    NUMBER(20,4),
      CREDIT_LIMIT                      NUMBER(20,4),
      VALUE_DATE_RULE_CODE              VARCHAR2(30 CHAR),
      CREATED_AT                        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY                        VARCHAR2(100 CHAR) NOT NULL,
      UPDATED_AT                        TIMESTAMP(6),
      UPDATED_BY                        VARCHAR2(100 CHAR),
      RECORD_VERSION                    NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_PDL_CORR_PROFILE PRIMARY KEY (CORRESPONDENT_PRODUCT_PROFILE_ID),
      CONSTRAINT FK_PDL_CORR_PROFILE_VER FOREIGN KEY (PRODUCT_VERSION_ID)
        REFERENCES PDL.PRODUCT_VERSION (PRODUCT_VERSION_ID),
      CONSTRAINT CK_PDL_CORR_ACC_TYPE CHECK (ACCOUNT_TYPE_CODE IN ('NOSTRO','VOSTRO')),
      CONSTRAINT CK_PDL_CORR_CUR CHECK (SETTLEMENT_CURRENCY_CODE IN ('IRR','USD','EUR','AED')),
      CONSTRAINT CK_PDL_CORR_SYS CHECK (SETTLEMENT_SYSTEM_CODE IN ('SWIFT','RTGS','CLEARING','INTERNAL')),
      CONSTRAINT CK_PDL_CORR_RECON CHECK (RECONCILIATION_METHOD_CODE IN ('AUTOMATIC','SEMI_AUTOMATIC','MANUAL')),
      CONSTRAINT CK_PDL_CORR_STMT CHECK (STATEMENT_FORMAT_CODE IN ('SWIFT_MT940','CAMT053','API','FILE')),
      CONSTRAINT CK_PDL_CORR_OD CHECK (OVERDRAFT_ALLOWED IN (0,1)),
      CONSTRAINT CK_PDL_CORR_VALUE_DATE CHECK (VALUE_DATE_RULE_CODE IN ('SAME_DAY','NEXT_BUSINESS_DAY','MARKET_RULE')),
      CONSTRAINT CK_PDL_CORR_LIMITS CHECK ((INTRADAY_LIMIT IS NULL OR INTRADAY_LIMIT >= 0) AND (CREDIT_LIMIT IS NULL OR CREDIT_LIMIT >= 0)),
      CONSTRAINT CK_PDL_CORR_REC_VER CHECK (RECORD_VERSION > 0)
    )~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT [PDL FIX96] Creating CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE ...
BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE (
      CORRESPONDENT_SETTLEMENT_RULE_ID NUMBER(19) NOT NULL,
      CORRESPONDENT_PRODUCT_PROFILE_ID NUMBER(19) NOT NULL,
      SETTLEMENT_FREQUENCY_CODE         VARCHAR2(20 CHAR) NOT NULL,
      CUTOFF_TIME                       VARCHAR2(5 CHAR),
      HOLIDAY_ADJUSTMENT_CODE           VARCHAR2(30 CHAR),
      NETTING_ALLOWED                   NUMBER(1) DEFAULT 0 NOT NULL,
      VALID_FROM                        DATE NOT NULL,
      VALID_TO                          DATE,
      CREATED_AT                        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CREATED_BY                        VARCHAR2(100 CHAR) NOT NULL,
      UPDATED_AT                        TIMESTAMP(6),
      UPDATED_BY                        VARCHAR2(100 CHAR),
      RECORD_VERSION                    NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_PDL_CORR_SETTLE PRIMARY KEY (CORRESPONDENT_SETTLEMENT_RULE_ID),
      CONSTRAINT FK_PDL_CORR_SETTLE_PROF FOREIGN KEY (CORRESPONDENT_PRODUCT_PROFILE_ID)
        REFERENCES PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE (CORRESPONDENT_PRODUCT_PROFILE_ID),
      CONSTRAINT CK_PDL_CORR_SET_FREQ CHECK (SETTLEMENT_FREQUENCY_CODE IN ('REALTIME','INTRADAY','DAILY')),
      CONSTRAINT CK_PDL_CORR_SET_TIME CHECK (CUTOFF_TIME IS NULL OR REGEXP_LIKE(CUTOFF_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
      CONSTRAINT CK_PDL_CORR_SET_HOL CHECK (HOLIDAY_ADJUSTMENT_CODE IN ('NONE','NEXT_BUSINESS_DAY','PREVIOUS_BUSINESS_DAY')),
      CONSTRAINT CK_PDL_CORR_SET_NET CHECK (NETTING_ALLOWED IN (0,1)),
      CONSTRAINT CK_PDL_CORR_SET_DATES CHECK (VALID_TO IS NULL OR VALID_TO >= VALID_FROM),
      CONSTRAINT CK_PDL_CORR_SET_REC_VER CHECK (RECORD_VERSION > 0)
    )~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE PDL.DEPOSIT_PROFIT_PAYMENT_RULE IS 'زمان‌بندی عملیاتی واریز سود سپرده؛ نرخ و روش محاسبه در PRODUCT_PRICING_* تعریف می‌شود.';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PROFIT_PAYMENT_RULE_ID IS 'شناسه برنامه پرداخت سود';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PRODUCT_VERSION_ID IS 'نسخه محصول (سیستمی)';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PAYMENT_FREQUENCY_CODE IS 'تناوب واریز سود';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PAYMENT_DAY_RULE_CODE IS 'قاعده تعیین روز پرداخت';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PAYMENT_DAY_NO IS 'روز ثابت ماه';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.FIRST_PAYMENT_RULE_CODE IS 'قاعده اولین پرداخت سود';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.HOLIDAY_ADJUSTMENT_CODE IS 'رفتار پرداخت در روز تعطیل';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.PAYMENT_DESTINATION_CODE IS 'مقصد واریز سود';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.CAPITALIZATION_ALLOWED IS 'امکان افزودن سود به اصل';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.CAPITALIZATION_DEFAULT IS 'سرمایه‌گذاری مجدد به‌صورت پیش‌فرض';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.VALID_FROM IS 'شروع اعتبار';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.VALID_TO IS 'پایان اعتبار';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.IS_ACTIVE IS 'فعال بودن برنامه';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.CREATED_AT IS 'زمان ایجاد';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.CREATED_BY IS 'ایجادکننده';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.UPDATED_AT IS 'زمان آخرین ویرایش';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.UPDATED_BY IS 'آخرین ویرایش‌کننده';
COMMENT ON COLUMN PDL.DEPOSIT_PROFIT_PAYMENT_RULE.RECORD_VERSION IS 'نسخه رکورد';

COMMENT ON TABLE PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE IS 'پروفایل تخصصی محصول برای حساب‌های کارگزاری NOSTRO/VOSTRO.';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.CORRESPONDENT_PRODUCT_PROFILE_ID IS 'شناسه پروفایل محصول کارگزاری';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.PRODUCT_VERSION_ID IS 'شناسه نسخه محصول';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.ACCOUNT_TYPE_CODE IS 'نوع حساب کارگزاری';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.SETTLEMENT_CURRENCY_CODE IS 'ارز تسویه';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.SETTLEMENT_SYSTEM_CODE IS 'سامانه تسویه';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.RECONCILIATION_METHOD_CODE IS 'روش تطبیق';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.STATEMENT_FORMAT_CODE IS 'فرمت صورتحساب';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.OVERDRAFT_ALLOWED IS 'اجازه اضافه‌برداشت';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.INTRADAY_LIMIT IS 'حد درون‌روزی';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.CREDIT_LIMIT IS 'حد اعتباری';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.VALUE_DATE_RULE_CODE IS 'قاعده تاریخ ارزش';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.CREATED_AT IS 'زمان ایجاد';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.CREATED_BY IS 'شناسه کاربر یا سامانه ایجادکننده';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.UPDATED_AT IS 'زمان آخرین ویرایش';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.UPDATED_BY IS 'شناسه کاربر یا سامانه آخرین ویرایش‌کننده';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE.RECORD_VERSION IS 'نسخه رکورد برای کنترل همزمانی';

COMMENT ON TABLE PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE IS 'زمان‌بندی، Cut-off، قاعده روز تعطیل و Netting برای محصول کارگزاری.';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.CORRESPONDENT_SETTLEMENT_RULE_ID IS 'شناسه قاعده تسویه';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.CORRESPONDENT_PRODUCT_PROFILE_ID IS 'شناسه پروفایل محصول کارگزاری';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.SETTLEMENT_FREQUENCY_CODE IS 'تناوب تسویه';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.CUTOFF_TIME IS 'ساعت Cut-off';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.HOLIDAY_ADJUSTMENT_CODE IS 'قاعده روز تعطیل';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.NETTING_ALLOWED IS 'اجازه Netting';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.VALID_FROM IS 'شروع اعتبار';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.VALID_TO IS 'پایان اعتبار';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.CREATED_AT IS 'زمان ایجاد';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.CREATED_BY IS 'شناسه کاربر یا سامانه ایجادکننده';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.UPDATED_AT IS 'زمان آخرین ویرایش';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.UPDATED_BY IS 'شناسه کاربر یا سامانه آخرین ویرایش‌کننده';
COMMENT ON COLUMN PDL.CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE.RECORD_VERSION IS 'نسخه رکورد برای کنترل همزمانی';

PROMPT [PDL FIX96] Validation ...
SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'PDL'
  AND TABLE_NAME IN ('DEPOSIT_PROFIT_PAYMENT_RULE','CORRESPONDENT_ACCOUNT_PRODUCT_PROFILE','CORRESPONDENT_ACCOUNT_SETTLEMENT_RULE')
ORDER BY TABLE_NAME;

COMMIT;
PROMPT [PDL FIX96] Done.
